### ISSUE TITLE
Plastic tool with Skeleton - Crash when rendering in Linux

### ISSUE THREAD

**Issue by sfepa** [opentoonz/opentoonz#1005]
Opentoonz crashes when trying to render animation (png ,jpg or other image sequences ) with Plastic tool+Skeleton .

Ubuntu 14.04 (64)
OpenToonz-1.1.2-2017.01.26-3ef2b-64bits.appimage
@morevnaproject @blackwarthog @ideasman42

**Comment by jabarrera** [comment]
I can't reproduce this (I can render fine a little plastic animation from a vector draw).

I think it could be an Appimage issue (maybe with writing in a location) but, could post the scene and drawings that you're trying to render? Maybe there is something wrong on it with an especific configuration.

**Comment by sfepa** [comment]
Attached  a simple scene  that i have created for test. I can record video if it is necessary.
[sandbox.zip](https://github.com/opentoonz/opentoonz/files/735290/sandbox.zip)

**Comment by jabarrera** [comment]
Hi @sfepa .

I have tested your scene and it is rendered fine ( here: https://youtu.be/YQnfgHKQ6CE ). So, it seems that is an **Appimage problem**. In that case, I think that it could be better if you post the issue in the Github of the Appimage.

I suspect that it is a problem with the location where creating the images. You can test it making a **preview** instead of a render. If it works fine (the preview don't create files. You can save that preview) you'll be pretty sure that the problem is that. Are you rendering to the **+output** directory or outside the project tree?

PD: if you think that it is still an **Opentoonz** problem, yes, posting a video with all the steps could be fine.

**Comment by sfepa** [comment]
Hi @jabarrera .
The same thing for **render** and **preview**
https://youtu.be/mWqp2s0ni8c

**Comment by ideasman42** [comment]
Most likely the header and library version of SuperLU are out of sync. See #962 for details.

**Comment by jabarrera** [comment]
What strange!

If it were the SuperLU issue, the crash should be get when trying to animate the skeleton. If the user can animate, I'm pretty sure that he is using the right SuperLU. But it is a good thing to check. It is required a constant SUPERLU_MAJOR_VERSION>=5 to make the right preprocessor (I think that Opentoonz should used the SuperLU upstream library instead of the thirdparty in Microsoft Windows and OSX, now that it's possible. It saves a lot of headache).

It is really strange that the preview doesn't work. I really thought that the problem could be saving.

@sfepa , could you run the Appimage from a terminal to see if it throw a message of exit? Look, too, the init looking for libraries messages (I don't know how works Appimage, but maybe it could be compiled using static or dynamic linking and maybe there is some strange there).

This only happens with plastic? You can succesful render a simple frame animation?

**Comment by sfepa** [comment]
@jabarrera frame animation is ok , only plastictool makes app crash.
Hope the video  can help.
https://youtu.be/c7Q1T92jhU4

**Comment by blackwarthog** [comment]
SuperLU includes really was out of sync. I've fixed it. But problem was not solved. I've checked SuperLU versions 4.1 and 4.3

I'll try latest version of SuperLU (5.2.1), but i'm not sure about compatibility of SuperLU APIs.

**Comment by blackwarthog** [comment]
With superlu-5.2.1 all works fine. I've updated appimages.

**Comment by sfepa** [comment]
Thanks @blackwarthog , now render and preview works fine, but another issue appeared: some frames are overlapping , see attached.  
![screenshot from 2017-02-02 12 06 13](https://cloud.githubusercontent.com/assets/25372144/22545447/776505ba-e941-11e6-939a-d83e0ef79808.png)
Should i create another bug report for this, or it is part of  the current issue?

**Comment by artisteacher** [comment]
Looks like it might be related to #856 - but without the weird background issue. There is definitely an issue with background transparency and the plastic tool - at least in OS X.

**Comment by ideasman42** [comment]
@sfepa this bug has been fixed, please report other bugs separately, although it looks as if this has already been reported.
