### ISSUE TITLE
FX Swatch Viewer Size Issues

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1016]
I've run into an issue where the swatch viewer (in some FX settings), keeps resetting so that it is hidden/minimized. In the particle settings, any change in the swatch viewer (ie. changing frames) results in the viewer minimizing. This has been ongoing and continues in the latest nightly build in OS X 10.11.6 and 10.12.3.
![fxglitch1](https://cloud.githubusercontent.com/assets/21159116/22476961/4b00451a-e7b2-11e6-8ebb-a05a62c7be79.gif)
In FX where there is only the swatch viewer and no adjustable settings, the swatch viewer opens in a strange minimized position.
![fxglitch2](https://cloud.githubusercontent.com/assets/21159116/22481338/ddf6ace6-e7c2-11e6-928b-5d41417b6a81.gif)

**Comment by mcjadski** [comment]
When I tried the problem with the Particles FX on OSX 10.11, I got almost the same result, except that my screen is bigger, so you can see that it's not actually minimizing:  

![swatch_minimize](https://cloud.githubusercontent.com/assets/25377429/22489006/c68ee498-e7da-11e6-9980-4702335816fa.gif)

When you go to a different frame (and when you first open the properties window), the big, gray region above the Swatch Viewer grows vertically, and seems to push the Swatch Viewer down below what is viewable.  You have to minimize and then maximize the Swatch Viewer before you can get a full view of it again.  

Also, when I try adjusting the properties window size, the window immediately adjusts itself so that the Swatch Viewer is in full view.  But then if I go to a different frame, the window expands vertically to take up the full height of the screen (minus top and bottom bars).  (The Swatch Viewer is in full view still; the window just refuses to stay the size I wanted it to be.)  

If I then go to a different frame a second time, the Swatch Viewer is once again pushed out of view.  

As for the second problem, it's even worse for me when I first open the Color Dodge effect:  

![tiny_window](https://cloud.githubusercontent.com/assets/25377429/22489140/6214a402-e7db-11e6-8347-ea41be68f3af.jpg)

But then if I resize the window, exit it, and reopen it again, it looks the way it does for artisteacher.  

I also tried these on Win 7.  I didn't have the same problem with the Particles properties window.  However, when I did the ColorDodge effect, the window starts way too small:  

![slightly_bigger_on_win](https://cloud.githubusercontent.com/assets/25377429/22489421/0d989134-e7dd-11e6-8b4b-f6d61fe9360d.jpg)

**Comment by artisteacher** [comment]
Interesting. For the particles settings, it looks like the size is based off of the content of the longest tab - ie. Birth Parameters. Changing the frame looks like it might reload the settings window entirely and so overrides any window size adjustments that were previously made. It would be great if adjustments to the window size were saved, which would minimize part of the problem. Another aspect that would help is the ability to show/hide the values for each property. 
![image](https://cloud.githubusercontent.com/assets/21159116/22614263/f031520c-ea4d-11e6-8773-e9baa8e89e2b.png)

**Comment by Qggh** [comment]
The size of the fx settings changes back  when I changed the frame
![videotogif_2018 05 15_02 03 11](https://user-images.githubusercontent.com/36899777/40027861-a8a1b6b0-57e4-11e8-8e73-ccdc5c7e18a7.gif)

**Comment by artisteacher** [comment]
The swatch viewer resizing, opening in a minimized state (for FX without editable settings), and settings window reverting the size upon changing frame number all seem to be resolved.

**Comment by RodneyBaker** [comment]
Thanks for the follow up @artisteacher. 
Much appreciated!
