### ISSUE TITLE
Loading external files does not truly import

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1017]
According to the Harlequin manual, loading an external file (audio, video or etc) as a level should give the option to import or to load from the existing location (creating an absolute path). Using OS X, I do not have that option and all external files are only linked. This is inconvenient for students that want to work at home or for anyone working on multiple computers. I know people can move the files to the correct location manually, but it seems like an unnecessary, additional step. Collecting assets does place the external files into the extras folder but the paths do not update in the level settings (which must be a bug). 

Anyways, it would  be super helpful to have a preference that could be enabled, such as "import external files into the extras folder". Or perhaps when right-clicking in the x-sheet to load a level, there could be an additional option to "import level". 

Thanks for everyone's hard work! OpenToonz is really coming along!

**Comment by turtletooth** [comment]
@shun-iwasawa Is this something that was changed at Studio Ghibli?  It sounds like a useful feature to have.

**Comment by RodneyBaker** [comment]
A few thought related to this...

I know first hand the usefulness of 'Embedding' files in a Project and use
it quite often in other software.  With embedding, the files that cannot be
embedded are linked to their original location  This sounds a lot like what
OpenToonz attempts to do in current configuration.  A separate process
called "Consolidation" can be used to bring everything together into one
file (a compressed zip file that maintains the original file structure so
that when unzipped everything can be found in the same place).  This
'Collection' of external files into the Extras folder you identify sounds
like a great intermediary between ( partial) Embedding and (complete)
Consolidating and thus a very useful option.

If this is indeed something that can be un-regressed that would indeed be
very useful.

**Comment by shun-iwasawa** [comment]
Yes, as @turtletooth pointed,  I changed the software not to ask whether import or load the external resources, which was demanded by Studio Ghibli staffs.
In Studio Ghibli they kept every data at designated folder organized by resource types and scene numbers. Allowing to import data may disturb such arrangement by mistake and may increase file size.

So, they demanded to skip to open the dialog asking "import or load", in order to increase work efficiency.
In particular, I changed the default value of `importPolicy` of a `struct LoadResourceArguments` from `ASK_USER` to `LOAD` in `iocommand.h`.

I think it would be OK to revert such dialog, but I think it should be optional (in preferences) since other Japanese animation studios are taking somewhat of a similar strategy as Ghibli regarding file management.

**Comment by mcjadski** [comment]
Maybe the dialog could have a "Remember my decision" or "Always do this" checkbox.

**Comment by artisteacher** [comment]
I agree, it could be annoying to have the "load or import" dialogue every time. Having a checkbox to save the user's decision would be great - or maybe it could be set directly in the preferences instead. I assume that the import would only happen to files from outside of the project and/or outside of OpenToonz. It would be so nice to have this brought back in some form!

**Comment by turtletooth** [comment]
Found it in the code.  It's a pretty easy fix- the hardest part is bringing it out to preferences.

**Comment by turtletooth** [comment]
#1037 Takes care of this.

**Comment by artisteacher** [comment]
Fantastic, thank you!
