### ISSUE TITLE
OSX 10.11.3: Color Model window has distorted content

### ISSUE THREAD

**Issue by trondarild** [opentoonz/opentoonz#104]
The Color Model window shows only distorted content or is completely black.
![skjermbilde 2016-03-29 kl 19 17 05](https://cloud.githubusercontent.com/assets/4227647/14117022/0887fcd0-f5e3-11e5-89ee-31a39bf7d7d6.png)

Update: the Flipbook window shows the same.

**Comment by tomosu** [comment]
Thank you for your report.
This problem seems to happen when no image is loaded on the window.
But it works correctly when some images(raster or vector) are loaded on Flip Book or Color Model Window.
As this problem looks a bit complicated, now we are trying to fix this problem gradually.
So please use Flip Book and Color Model Window as-is for a while, sorry.

**Comment by artisteacher** [comment]
On a related note (when a color model is not loaded) after switching rooms, the color model displays the same area of the last room. This is on OS X 10.11.6 and 10.12.4.

**Comment by artisteacher** [comment]
The transparency issue with the color model after changing rooms seems to be fixed in the latest nightly build.

**Comment by artisteacher** [comment]
This is definitely resolved in 1.2.

**Comment by artisteacher** [comment]
No longer an issue, recommend closing.

**Comment by trondarild** [comment]
Tested ok. Closed.
