### ISSUE TITLE
Subsheet Inside a Subsheet Doesn't Render

### ISSUE THREAD

**Issue by falls2lawrence** [opentoonz/opentoonz#1049]
When I have a subsheet/subsheets within another subsheet, the embedded subsheets do not render even though it is visible in the workspace;  I'm not sure why this happens but exploding the embedded subsheet enables the levels to render again. Unfortunately this "disappearance of subsheets" does not happen every time and recreating it is hit or miss. But I attached a file where the disappearance occurs, the second column (the eyes) inside the head of the character do not render.
[tuts.zip](https://github.com/opentoonz/opentoonz/files/784599/tuts.zip)

**Comment by shun-iwasawa** [comment]
I think it is not a bug.
Here is the simplified schematic of the subXsheet of your sample scene:
<img src ="https://cloud.githubusercontent.com/assets/17974955/23112650/39ee78dc-f775-11e6-82c6-346972e6ca14.png" width=500>
 
Please see the preview of VisibleMatteIn02 Fx which is connected to the Col3 (Mouth) in the subXsheet.
You applied Col1 (Head) to the "Down" Port, so the result of VisibleMatteIn02 becomes Head+Mouth like this:
<img src ="https://cloud.githubusercontent.com/assets/17974955/23112669/6d237d06-f775-11e6-8080-8f22e5d20285.png" width=500>

The placing order of the result of VisibleMatteIn02 is according to the source connected to the "Up" port (= Col3). And since Col2 (Eye) is behind Col3, it dissappears on render.
To prevent such behavior, put the "Eye" column above the "Mouse" column, by putting it right side or use "Over" Fx in order to explicitly specify the placing order.

**Comment by falls2lawrence** [comment]
And when I explode the subsheet I typically put the created column at the end of all the columns which why that fixes the problem for me in that instance. Thanks for making short work on my little issue. perhaps from here on out I'll just use the tried and true matte in effect.
