### ISSUE TITLE
Crash attempting new project

### ISSUE THREAD

**Issue by Petrazilla** [opentoonz/opentoonz#1095]
Regardless of whether I'm trying to create a new project on start-up or afterwards in the program, as soon as I ask it to start a new project, Opentoonz becomes unresponsive. I have uninstalled and reinstalled twice, restarting between each,. I have tried to wait and see if it just needs a minute, which doesn't seem to be the problem either. 

When I end the program though task manager, Windows tells me the program is waiting for a response from me.

It doesn't appear to be a CPU problem, I can open and use other programs while this issue is occurring.

Operating on Windows 7 64bit

**Comment by turtletooth** [comment]
When you click new project, does the new project window popup?

**Comment by Petrazilla** [comment]
The new project window does pop up, but is not responsive.

**Comment by jpturcotte** [comment]
@Petrazilla Is this still an issue?

**Comment by RodneyBaker** [comment]
@Petrazilla We are going to need more information in order to assess this problem.
Closing until additional information is received to diagnose the problem.

For additional assistance please visit one of the many Opentoonz venues:

Opentoonz forum:
https://groups.google.com/forum/#!forum/opentoonz_en

Also, as they tend to fix known problems make sure you are using a recent release such as:
https://github.com/opentoonz/opentoonz_nightlies/releases
