### ISSUE TITLE
Importing .psd Files

### ISSUE THREAD

**Issue by VektorHead** [opentoonz/opentoonz#1107]
I get all sorts of problems trying to import .psd files that I create in Krita. I prefer Krita to create my backgrounds and save them as .psd files. When I try to import them into OpenToonz, I get an error saying “Layer ID not exists.” Konstantin Dmitriev was able to reproduce this bug, as well.

**Comment by artisteacher** [comment]
I've had this same issue. That particular error message happens when loading the file as columns with a group option set to expose layers in a group. Psd files from Photoshop and Affinity Designer load in OpenToonz as expected. I opened a Krita .psd in Photoshop and it looked normal.  Saving the unaltered file in Photoshop made it load correctly in OpenToonz.

**Comment by VektorHead** [comment]
@artisteacher Yea, I remember reading in Krita's documentation that .psd is not really an interchange format. People just use it like it is. Anyway, I found the perfect workaround: just export each layer as .png. I simply hide all layers except the active one and then export it into a new folder. I then make another layer active and hide all others and export again until I have all layers exported. They then open perfectly in OpenToonz.

**Comment by bobbybutterfly** [comment]
why is this closed?
ist an Opentoonz Problem:
save artwork with layers as psd file in clipstudio paint
load Level as psd in OT = "LayerID does not exist"

Import this Clip Studio psd file into Affinity-Designer and it is shown correctly
Import this Clip Studio psd file into Photoshop and it is shown correctly

ergo, ist an OT problem

**Comment by artisteacher** [comment]
Since .psd is not an open format, the various graphics programs have backwards engineered their own versions of .psd. Technically, since OpenToonz has no issue with actual psd files, it’s not a problem with the OpenToonz side but a problem with how certain other programs have made their version of psd.

 It ought to be fixable from OpenToonz though - assuming Krita and Clip Studio have the same problem. Maybe when there are no layer id’s, OpenToonz should assign some?
