### ISSUE TITLE
(Proposal) Improve "$scenepath" wording

### ISSUE THREAD

**Issue by mcjadski** [opentoonz/opentoonz#1111]
When creating a new project, the user is confronted with the following checkboxes:  

- Append $scenepath to +drawings
- Append $scenepath to +inputs
- Append $scenepath to +extras

This is programmer speak and will make no sense to a great many people.  (I confess that I didn't understand it myself for a long time, even though I'm a programmer!)  

I think we should find a simpler, plain-English way of phrasing this.  For instance, "Store drawings in scene subfolders"

Thanks!

**Comment by artisteacher** [comment]
I think this is a great idea.

**Comment by konero** [comment]
I don't know, I know how to use $scenepath because I used Harlequin back in the day, but either way you phrase it TBH is going to be vague because it's not so black and white, it needs documentation, because you can place the variable where you prefer. Here from the manual...

-----

**Using the $scenepath Variable in Folder Definition**
The $scenepath variable can also be used in the definition of the +inputs, +drawings, and +extras aliases when typing the default folder path. In this case the path where you save the current scene will replace the $scenepath variable in the path definition, with the needed folders automatically created during the saving process.

For example if +drawings is $scenepath\mydrawings, and you save the scene scene01 in +scenes\seq01, Toonz drawn or cleaned up levels for that scene will be saved in seq01\scene01\mydrawings; when you save the scene scene02, in seq01\scene02\mydrawings; and so on. In this way the needed default folders are automatically created with the same given name (mydrawings), one for each scene, according to the path used when saving the scene. As a consequence, if the variable is used in this way for all the aliases, all the files related to a scene will be stored in a folder named as the scene.

A second example: if +drawings is mydrawings\$scenepath, when you save the scene scene01 in +scenes\seq01, Toonz drawn or cleaned up levels for that scene will be saved in mydrawings\seq01\scene01; when you save the scene scene02, in mydrawings\seq01\scene02; and so on. In this case the needed default folders are automatically created with the name and path of folders used when saving the scene, inside the path specified (mydrawings). As a consequence, if the variable is used in this way for all the aliases, all the files used in the project will be stored in a main folder, divided in scene folders. All files related to a scene are stored in a folder named as the scene.

**Note:** The definition of the +palettes alias cannot include $scenepath, as the palettes refer to the whole project, not to specific scenes.

**Note:** It is not possible to use at the same time for an alias the $scenepath variable in folder definition and the Append $scenepath option. The Append $scenepath option is available for the +inputs, +drawings and +extras aliases. If you activate the Append $scenepath option for an
alias, the path where you save the current scene will be added to the path of the alias, with the needed folders automatically created during the saving process.

For example if +drawings is mydrawings, and you save the scene scene01 in +scenes\seq01, Toonz drawn or cleaned up levels for that scene will be saved in mydrawings\seq01\scene01; if you save
the scene scene02 in +scenes\seq01, Toonz drawn or cleaned up levels for that scene will be saved in mydrawings\seq01\scene02; and so on.
This allows Toonz to create scene-related folders automatically when saving Toonz files or importing external files, while allowing the use of the generic aliases +drawings, +inputs and +extras, no matter where levels are loaded from within the current project.

**Note:** When a scene is saved in the +scenes folder, the value for $scenepath is the scene name; for example if you save the scene scene02 in +scenes, $scenepath will be scene02.

**Note:** It is not possible to use for an alias the Append $scenepath option and at the same time the $scenepath variable in defining the related folder.

**Comment by Jose-Moreno** [comment]
@konero Can you actually use this feature currently in Opentoonz 1.1.2? I've been trying to use it in both ways (e.g. drawings\$scenepath vs $scenepath\drawings vs append checkbox) and none of it works, in fact writing it on the project settings paths as the manual describes crashes the software just as you press return.

I don't know if I'm doing something wrong, but if it's a bug it may be worth tinkering with this proposal as well while fixing it, however I don't know if anyone can confirm this since I didn't find any related issue on the tracker.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
Closing this report as part of general housekeeping.
Let's review the thoughts presented here for the next development cycle.
