### ISSUE TITLE
Issue with converted vector levels and the inbetweener

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1119]
After converting a raster level to vector, tweening in the level strips fails. It looks like it recognizes one of the drawings but only the start/end? of the stroke in the other drawing. When working with different converted levels, there is not consistency in whether it is the first or last frame that fails.
![screen shot 2017-03-23 at 9 28 13 am](https://cloud.githubusercontent.com/assets/21159116/24249848/1d83ed32-0fab-11e7-8c69-f2fe4b25d88a.png)

**Comment by turtletooth** [comment]
I'm not sure that the auto-tweener was designed to work with converted levels.  The tweener looks for the order and direction that lines were drawn and extrapolates from there, I haven't looked in the code, but I would guess that any information that the tweener needs to work correctly isn't present for converted levels.

**Comment by artisteacher** [comment]
I thought that would be the case. Too bad - converting raster to vector is a great work around for those of us with tablet issues. If it will not be possible for the tweeter to function properly on converted levels, it might be helpful for it to be disabled on converted levels.

**Comment by RodneyBaker** [comment]
What follows is a naive look at what is happening and possible approaches to solutions.

First, I must assume at least two primary issues are at hand here, the first of which is segment order and the second of which is Control Point (CP) Order.  These taken together seem to equate to what is referred to as 'stroke order'.

Perhaps a PR could be generated that allows the reordering of stroke/curve IDs in such that a top to bottom, bottom to top, right to left, left to right, top left to bottom right reordering could be initiated just prior to the auto-inbetweening.  Not an easy task I'm sure but I know of a program that does tiddy up splines by reordering the CPs created on them.  Another approach might use similar sorting but include more direct interaction with the user... but more on that later.  

I further assume that as new inserts are made along a curve that create a new CP that point is identified based on the next available number (and not on some other criteria such as it's location on the canvas/grid*.  This will cause discontinuity in the order of CPs.  For instance a two point line (with CPs 1 and 2) dissected in half will be ordered 1, 3, 2 because the mid point was created after the second CP.  Reordering would place it back into numerical order; 1, 2, 3.  

*Reordering based on the location of the start and end points of a curve on the canvas (i.e. in world space) might be an interesting approach but there are a lot of variables in that approach as well.  At any rate, a higher level solution might be to 'paint' on top of frames to indicate where 'same space' exists and then have OT reorder the curves/CPs accordingly prior to auto-inbetweening.

One thing that might aid the user in determining the potential outcome of the auto-inbetween might be to display (perhaps in color) where the influence regions are in the second/target frame.  If those regions could then be moved about on the frame that would yield different but targeted results as defined by the user.

**Comment by beeheemooth** [comment]
RodneyBaker, 
This is a good idea. I think we need a special tool (something like a guide brush) that will more flexibly change the order of strokes, and determine the preferred trajectory of the strokes.

**Comment by blurymind** [comment]
@walkerka  had something developed for an alternative tweening for his app.
He noted it in my feature request here:
https://github.com/opentoonz/opentoonz/issues/287

I agree that tweening in OT in general should be improved

**Comment by turtletooth** [comment]
After making the timeline view @jaros3 was talking about possibly doing some work that would dig into the individual strokes.  If he gets his working it might be a good starting place for this change.
