### ISSUE TITLE
Possibility of pasting keyframe and skeleton data across scenes

### ISSUE THREAD

**Issue by agatre** [opentoonz/opentoonz#1160]
After doing a test animation separately, I wondered if this was possible at the moment or code wise. I wonder in which file does OT store the information of keyframes and composition so I can manually attempt to copy/paste data into a scene directly.

**Comment by RodneyBaker** [comment]
The data is stored in the toonz scene file.

To get a little better view of the breakdown, as the files are xml compatible you could try saving the file with an .xml extension and then either open it the file in an XML friendly text editor or browser.

This might be different depending on how the file is saved by Column data is given an ID and then subsequent changes stored within that container.  An example (from a quickly drawn line that was then  translated and rotated:

      <pegbar id="Col1">
        <parent handle="B" id="Table" parentHandle="B">
          </parent>
        <isOpened>
          0 
        </isOpened>
        <center>
          0 0 0 0 
        </center>
        <status>
          0 
        </status>
        <x>
          <default>
            0 
          </default>
          <keyframes>
            <S>
              0 0 1.66667 0 
            </S>
            <L>
              <prev>
                0.19685 0 0 
              </prev>
              5 0.19685 
            </L>
            </keyframes>
          </x>
        <sx>
          <default>
            1 
          </default>
          </sx>
        <sy>
          <default>
            1 
          </default>
          </sy>
        <sc>
          <default>
            1 
          </default>
          </sc>
        <rot>
          <default>
            0 
          </default>
          <keyframes>
            <S>
              0 0 1.66667 0 
            </S>
            <L>
              <prev>
                90 0 0 
              </prev>
              5 90 
            </L>
            </keyframes>
          </rot>
        <nodePos>
          24620 25500 
        </nodePos>
        </pegbar>

Within that framework we can see the specific 'nodes' that store data.

As for getting at that data progammatically... I'll defer to the experts on that.

**Comment by RodneyBaker** [comment]
It's worth noting that any curve (animation) created can be saved out and then reimported.
The way to do this is to right click on the object in the stage listing (I call this the project workspace).  Options to Save the Curve and import a Curve will be there.  Files saved have the .curve extension.

The last time I tried this I ran into a bug in importing the .curve file but I was able to save one out.

So a short answer might be to either save/reimport those curves, copy/paste those curves (in the Function Editor) or develop a plugin feature to further exploit those curves.  Prior to coding a new plugin/utility I would explore the Funtion Editor (to include the spline/channel editor) thoroughly as much can be accomplished there.

**Comment by agatre** [comment]
Thank you! I did try to open the scene file but I couldn't identify the corresponding code.
I'll see if what works for curves can work to copy the distortion of a skeleton.

**Comment by RodneyBaker** [comment]
The good news...

Plastic data is stored the same way as other data in the scene file and is also accessible via the stage listinging in the Function Editor.  Vertex data for each node of the skeleton are stored there as well.

The three main types of data for skeletons (as far as I can see) are: 

Angle
Distance
Sort Order

That's really all that is required to control and document skeletal/plastic deformation.  It looks like there might be other deformation data stored later in the scene file but I won't guess as to it's purpose other than that it may focus on deformation/distortion.  

I"m attaching a screen shot of a view of the stage listing and function editor.  
Of interest also might be the naming at the very top right (above the stage listing) that identifies the selected item.  To my understanding this would be useful with scripting because that is the name structure that would be used to get at that data.  In the image that is:  fx.col2.plastictool.vertex__2.angle

I haven't done any scripting in OpenToonz but someday I hope to so I thank you for asking the questions that make me dig deeper.
![skeletondata](https://cloud.githubusercontent.com/assets/2576432/25115996/92a8ee86-23cf-11e7-912b-bfa660f67602.png)

. :)

**Comment by RodneyBaker** [comment]
I note that modified data in the stage listing appears as red which is handy in identifying areas of interest.

I'll throw in a screen of the dialog that allows for saving out/reimporting data/curves.  When I last tried to copy curve data in this fashion the file saved out and reimported without problems but immediately after OpenToonz crashed.  So a suggestion would be to save immediately after importing a curve.
![savecurve](https://cloud.githubusercontent.com/assets/2576432/25116201/d832b0f8-23d0-11e7-8aea-8a941adb4b30.png)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
