### ISSUE TITLE
UI colours, Minor irritaion

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1164]
This is probably petty but the colour for an active column is red, Res is usually the colour for an error and this always makes me instinctively feel that there is an error especially since it is the colour for an error in a level. I think Blue or green would be a better colour. 

![tmp](https://cloud.githubusercontent.com/assets/18170954/25196313/9779abae-2540-11e7-8a4e-b69ad18f9f74.png)

**Comment by blurymind** [comment]
Something with more contrast to the dark background too

**Comment by BrundleThwaite** [comment]
It needs to be readable on the yellow when rendering is enabled as well.

**Comment by artisteacher** [comment]
I agree, the red always makes me feel something is wrong. Perhaps instead of changing the text to red when the level is active, the entire level could have a slightly different value or intensity.

**Comment by turtletooth** [comment]
Leaving myself a note for this: xsheetcolumnviewer line 739.  If anyone can play with colors that would work when the level is active/visible/empty. . . that would help.  It's an easy fix, I just don't have the time to play with colors right now.

**Comment by artisteacher** [comment]
It's tough with the light & dark themes but what about something like #5089EB?
<img width="146" alt="light" src="https://cloud.githubusercontent.com/assets/21159116/26475702/45be806a-4187-11e7-8a70-e9cc6c0d6a6a.png">
<img width="143" alt="dark" src="https://cloud.githubusercontent.com/assets/21159116/26475706/53cd4f2e-4187-11e7-995c-28d0342333c4.png">
<img width="150" alt="empty" src="https://cloud.githubusercontent.com/assets/21159116/26475854/4819116c-4188-11e7-8a1c-32ac32ec6df1.png">

**Comment by BrundleThwaite** [comment]
That is pretty close to what I was thinking. So I am not going to submit my colour choice because it it too similar to make a difference.

**Comment by turtletooth** [comment]
@artisteacher That looks pretty good.  Thanks for doing that.

**Comment by turtletooth** [comment]
I played with it and the font on Windows isn't as thick as yours, so the yellow bg overpowers the blue.  I also want to wait to hear what the response to #1239 is - as that will affect the degree of work.

**Comment by BrundleThwaite** [comment]
I have no problem with replacing the UI and removing the old ones as long as it does not change the workflow.

**Comment by artisteacher** [comment]
Here is #066EFF:
<img width="146" alt="dark2" src="https://cloud.githubusercontent.com/assets/21159116/26661323/f798b7fc-464a-11e7-8e79-ad0c3ac460b6.png">
<img width="150" alt="empty2" src="https://cloud.githubusercontent.com/assets/21159116/26661324/f7acfe1a-464a-11e7-9dcb-847d34ff2647.png">

Or #0CA0F7:
<img width="143" alt="dark3" src="https://cloud.githubusercontent.com/assets/21159116/26662098/c5d6a01c-464f-11e7-9129-52e50d9da599.png">
<img width="146" alt="light3" src="https://cloud.githubusercontent.com/assets/21159116/26662099/c5e20880-464f-11e7-876d-6c4a74e038f1.png">

Or green #06AF0B:
<img width="143" alt="greendark" src="https://cloud.githubusercontent.com/assets/21159116/26662290/e570459e-4650-11e7-928f-d6f472d49348.png">
<img width="146" alt="greenlight" src="https://cloud.githubusercontent.com/assets/21159116/26662291/e57f9724-4650-11e7-9346-47e5f81e1a27.png">


Or we could go warm with orange. It hopefully doesn't scream that something is wrong but overall, has slightly better contrast. This is #FE6F04.
<img width="143" alt="orangedark" src="https://cloud.githubusercontent.com/assets/21159116/26661745/958ba22e-464d-11e7-8895-c30051f028ce.png">
<img width="146" alt="orangelight" src="https://cloud.githubusercontent.com/assets/21159116/26661746/959c4b24-464d-11e7-9e8a-8f0cf2bdb12c.png">

It's not easy to find a color that is legible on such a range of values/colors - which is probably why red was chosen to begin with.  If there was a light theme color and a dark theme color it might be marginally easier since it would slightly minimize the range. Let me know if I should keep looking.

**Comment by BrundleThwaite** [comment]
There would always be the other option of have the selected column as black and all non selected ones as gray. I also see not reason why  the column name could not also be bold.

**Comment by artisteacher** [comment]
It might not be easy to find the correct gray - some of the column types are a couple different grays and there would still be the value issue.

**Comment by artisteacher** [comment]
This can be closed - the default active color is now yellow & can be customized in preferences.
