### ISSUE TITLE
Proposal: Feature freeze and bug fix

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1204]
Hi everyone,
With the exception of the features currently in development with active PRs and those needed for studio work, I would like to propose a feature freeze so focus can be given to bug bashing.  

The software is already very feature rich and most of the new feature requests are nice but not immediately crucial.  The biggest roadblock for greater adoption is stability and random crashes.  If we can focus on those, I think it will greatly help the user base.

I realize that 1.3 is hopefully coming out at the end of the month and it would be cool if some of the current features in development are there - notably MyPaint brushes (that feature is awesome), but perhaps 1.4 can be a stability release.

Just a thought.

**Comment by jpturcotte** [comment]
@turtletooth I hoped we could discuss this at our tentative meeting (#1202). It would be great if @morevnaproject, @ideasman42, @kogaki, and @shun-iwasawa could join too.

**Comment by turtletooth** [comment]
@jpturcotte I have not seen much interest here from actual developers in holding a meeting and getting the timezones figured out would be challenging.  I'm in Colorado, @shun-iwasawa is in Japan, @ideasman42 is in Australia etc. . .

@shun-iwasawa and the folks at Dwango are the ones who should be asking for a meeting if they want one.  It is an open source project, but they are the ones who manage it.

**Comment by jpturcotte** [comment]
It was brought up in issue #1177, admittedly by users such as my myself, and not developers. @morevnaproject seemed interested at the time, though. Organizing a meeting does require a bit of work, but that is something I would gladly help with (I have been sitting on a board since 2012). In fact, American and Asian timezones tend to be easier to reconcile, in my experience. Is there any way you would reconsider?

**Comment by artisteacher** [comment]
As a mac user, I would really appreciate a focus on stability across all OS over getting new features. Not that I'm not excited about the new features that are coming but many of my students are finding OpenToonz painfully glitchy. 

I do think that as a secondary focus, it would be helpful to improve UI consistency in some areas and work to minimize common user errors.

**Comment by deomacius** [comment]
If I might add my voice... stability and performance optimization would be
awesome.

Shay.

"The Alliance said they were gonna waltz through Serenity Valley, and we
choked 'em with those words. We've done the impossible, and that makes us
mighty."

 ~Captain Malcolm
<http://www.planetclaire.org/quotes/firefly/malcolm-reynolds/>, Firefly

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for your proposal. I'm now tackling with the issue #1201 (glitches in high-dpi monitors) and am thinking of introducing existing PRs as much as possible before the next release. 

@jpturcotte For me it's OK to join the meeting if you all will be tolerant of my poor English. Please let me check if I can prepare an instruments for voice chat in my office...

**Comment by jpturcotte** [comment]
@shun-iwasawa We would be extremely glad to have you! I do not think anyone will judge your English, especially since you will not be the only non-native. Certainly, your English is light years ahead of my Japanese! Please tell us if and when you can procure yourself a microphone, and we will check the schedule.

**Comment by turtletooth** [comment]
Closing since this has been seen by the devs.  Thank you all for your feedback.
