### ISSUE TITLE
Apostrophe in level name breaks path

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1226]
You can create or load a level with an apostrophe ' in the name. After saving all, closing and reopening, the level displays as missing - red name and all. The level is actually still in the original location, whether that is the scene's drawing folder or somewhere else. Going to the level settings, it looks like OpenToonz misinterprets the name. It adds a forward slash where there should not be, resulting in a false path. No other symbols seem to have this issue. 
![img_3931](https://cloud.githubusercontent.com/assets/21159116/26472972/bfd6b414-4176-11e7-9285-b8010266d3a2.JPG)

**Comment by artisteacher** [comment]
The same thing happens with columns made from psd layers when the layer name has an apostrophe.

**Comment by turtletooth** [comment]
It looks like it is inserting an escape character in there.

**Comment by artisteacher** [comment]
Looks like it. Personally I don't use apostrophes in file names but have had a couple students that have. It would be great if apostrophes could be disabled when naming a file (a few other symbols are). A warning about the file name would be necessary when loading a level outside of OT.

**Comment by artisteacher** [comment]
There's another case of this problem in the Google Group.

**Comment by manongjohn** [comment]
I think there is an issue related to this that involves special characters, not just apostrophe.

A user on Google Group posted a problem where the names of files had a special character in it, in this case the character was 'ö' (o-umlaut). When loading the scene it gave the error "There were problems loading the scene C:\\....tnz. Some files may be missing" but all the columns were blank.

I was able to verify this issue by constructing a simple scene before and after.  Renaming the affected file and editing the tnz file to match fixed the problem.

In the case of apostrophe it loaded the scene into the Xsheet but the file with the apostrophe appears missing.  In the case of the special character, it failed to load the entire scene into the Xsheet outright.  In either case, I think its an issue of how OT is reading filenames.  However this is fixed needs to address both issues.

**Comment by artisteacher** [comment]
Except for apostrophe, every symbol I've tried either cannot be input or does not cause a problem. For example dash - works just fine but a colon : cannot be input. Interestingly, using an apostrophe in the scene name does not cause an issue.

I'm not actually having an issue with the special characters that I've tried in OS X. However, that's a really long list to go through completely and a lot of the shortcuts I can't use with my keyboard. It's possible some of the character path issues may be OS specific.

**Comment by manongjohn** [comment]
I just wanted to add some more information regarding the umlaut character issue for whomever wants to try and fix this:

Working with the user's .tnz file, I was able to determine the issue was 2 fold:
1) OT does not like umlaut characters (not sure what other extended characters it doesn't like)
2) OT does not like when the .tnz file is encoded in UTF-8-BOM

For some reason, not sure when it happened, when the user entered the umlaut character and saved, the entire file got re-encoded to UTF-8-BOM.  So even when we replaced the umlaut character with a non-umlaut version ("ä, ö, ü" to a, o, u respectively), we were still getting the error.  I then discovered the bad file was encoded in UTF-8-BOM where as a prior good version was in UTF-8.  So I converted the file back to UTF-8 and it fixed the problem.  NOTE: Just fixing the UTF-8 issue wasn't enough. Have to do both the recoding and replacement.  He was using Windows 7 Home Premium, SP1, 64 bit

This is somewhat different than the apostrophe issue in that a \  is being added to the filename before being written to the .tnz file for certain characters which ultimately is causing problems when trying to find and load the file. The end error is different in that the apostrophe loads the scene into the xsheet and the other one does not.

Should the umlaut/UTF-8-BOM issue be a separate issue?  In both cases, how the data is stored in and read from the .tnz file matters so that would be the only reason to keep them together if the fix, fixes both.

**Comment by manongjohn** [comment]
Another user in the forum was having issues with ó and ñ characters in their .tnz files, that resulted in the same problem as the umlaut character, though without the secondary encoding issue.

However, I think I narrowed the issue to the column name, not the file name.  One thing I noted was that these special characters were in unquoted column names. Whatever is parsing the .tnz file appears to have trouble reading the rest of the file whenever it hits one of these special characters in an unquoted column name.

As a test, I left these special characters in and surrounded the column names in "" and the scene loaded without issue.

Ultimately quoting all column names is probably the best way to fix this particular issue.  Won't fix the apostrophe issue though.

**Comment by artisteacher** [comment]
It looks like the foreign character issue was already reported in #666. It sounds like the apostrophe issue while related is different, so I'll leave this open.

**Comment by manongjohn** [comment]
Sorry. Didn't realize that issue was there.  I should have checked the older open issues first. Granted, I thought they might be the same issue originally.

Anyway, I'll reiterate my findings in that thread so this one  can just be about the apostrophe.
