### ISSUE TITLE
Ease of Maintenance - Remove original and dark themes

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1239]
In updating the xsheet toolbar PR, there were 7 themes that need to be updated now.  The ones that @konero made are pretty easy to manage and changing one file changes them all for the most part.

I suggest removing all the themes except the Astral themes he has made for the sake of maintainability.

**Comment by konero** [comment]
Here's my two cents.

I think the UI should be reworked from scratch and perhaps just switch to using the basic built-in Qt Fusion theme like Krita, Nuke, DJV Viewer and Maya does to eliminate the overhead altogether, if this is possible.

And instead of relying on QSS to fix a lot of control alignment issues with the use of subcontrols/margins they should be fixed in the code. The 'theme' should only control colors.

I'd also settle for just the middle gray version like Toon Boom, CACANi and others do.

![scrn-ot-4834](https://cloud.githubusercontent.com/assets/19820721/26580123/aa8c4eaa-452e-11e7-8786-a34a3cb619fd.PNG)

An example dark theme could be just to give an idea...

>     qApp->setStyle(QStyleFactory::create("Fusion"));
> 
>     QPalette darkPalette;
>     darkPalette.setColor(QPalette::Window, QColor(53,53,53));
>     darkPalette.setColor(QPalette::WindowText, Qt::white);
>     darkPalette.setColor(QPalette::Base, QColor(25,25,25));
>     darkPalette.setColor(QPalette::AlternateBase, QColor(53,53,53));
>     darkPalette.setColor(QPalette::Text, Qt::white);
>     darkPalette.setColor(QPalette::Button, QColor(53,53,53));
>     darkPalette.setColor(QPalette::ButtonText, Qt::white);
>     darkPalette.setColor(QPalette::Highlight, QColor(42, 130, 218));
>     darkPalette.setColor(QPalette::HighlightedText, Qt::black);
>     
>     qApp->setPalette(darkPalette);

As long as all the widget alignments are fixed in the code and we stuck to in-built controls, this would be a much easier way to handle themes.

**Comment by adamearle** [comment]
just a side note to add to this but we use the record audio option in OT 
as way to give dailies feedback reviews. along with draw overs.

I have to agree on the rework of the UI it very dated and I love the 
suggestion

Adam Earle

**Comment by turtletooth** [comment]
@konero I actually really like the themes you created.  They look more polished that basic Qt widgets.  Since moving nearly all of the qss to code would be a rather large undertaking, in the meantime, I still think my original suggestion will make maintenance easier.

**Comment by konero** [comment]
Aye, but since the title mentions ease of maintenance, using Qt Fusion would make it dead easy since the onus rarely falls on small project developers to maintain it, its all built in.

_(and besides, I kind of like Qt Fusion)_ 😉 

If I remember, activating Fusion takes just a single line of code, but since I don't know the OT code too well I can't predict loading priority and stuff.

It would also reduce the 'color palette variables' down to a small handfall, maybe 10 or so, assuming it doesn't get all convoluted like Blender did.

I still think it would be good for somebody to give it a go though.

**Comment by artisteacher** [comment]
Personally, I also really like @konero's themes - I don't feel they look dated. However since I use Adobe CS5, Fontforge, and Audacity, which all have ridiculously dated UIs, my perspective may be skewed. I think for now at least, to make maintaining easier, getting rid of the old themes should be fine.

**Comment by shun-iwasawa** [comment]
@turtletooth I agree with your suggestion.

**Comment by turtletooth** [comment]
@shun-iwasawa I have two PRs in right now that include changes for all the themes.  Rather than modify these PRs, I will submit a new PR removing the themes after the PRs get merged.  Would that be ok?

**Comment by shun-iwasawa** [comment]
Fine. Then I'll see #989 and #1244 . Correct?
I'm thinking when should I release the next version (v1.1.3)... Would you like these changes to be included?

**Comment by turtletooth** [comment]
Those are the two.

As far as if these should be included in the next version- I do think that UI has been something many users have mentioned and if we release 1.1.3 with 7 themes and later release 1.1.4 with 3 - that would confuse some users.  I think it would be better to remove the themes before 1.1.3.  What do you think?

**Comment by shun-iwasawa** [comment]
OK. So I'll release the next version after these UI-related modifications ( #989 , #1244 , and the "remove styles" PR to be posted ) will be included, as well as other bug-fix PRs. As far as I noticed, for now the bug-fix PRs are #1206 , #1234 , and #1241 . #1218 seems to be still under discussion.

**Comment by turtletooth** [comment]
That sounds good.
