### ISSUE TITLE
Plastic Tool creates black contour

### ISSUE THREAD

**Issue by sfepa** [opentoonz/opentoonz#1249]
Plastic Tool creates black contour around mesh. The bug appears for both raster and vector layers, and  "premultiply" option (for raster +plastic tool) doesn't solve the problem.
![ot_issue](https://cloud.githubusercontent.com/assets/25372144/26753304/3fb30a38-486c-11e7-8ad0-d28b09b22f46.jpg)
how it appears - https://youtu.be/vaG4q1cW77Y

**Comment by falls2lawrence** [comment]
the effect erode/dilate in the matte sections does a good job of removing the add black color.

**Comment by sfepa** [comment]
the effect can be used  sometimes, but unfortunately  it is not a solution ( this character was made  in one Level and all the elements are placed together with the mesh tool, but erode/dilate affects only the outer contour, and since the nose and arms are overlapping  the body, the effect can do nothing with this..)
Actually  it is a problem with blending in OT , because  the exported png with alpha gives the same  dark stroke and it is  pain for motion designer when he puts  all the parts together :) hope this  issue will be fixed soon/

**Comment by falls2lawrence** [comment]
For anyone stumbling upon this looking for "a solution"/workaround in this exact situation.
 until the nice folks developing this software fix the issue, breaking your body parts onto different columns can be done in just a few clicks (clone cell, delete unwanted parts, repeat) and allows you to use the erode effect which gets rid of the line. or go "old school" with a patch, a skin colored blob, on a new column that covers the unwanted line.

**Comment by snapai** [comment]
This bug is still happening on the current version of OT/OTX. Erode/Dilate is not really an option since I have 30-40 plastic layers involved in this scene.
![image](https://user-images.githubusercontent.com/5098372/34076446-c7264104-e2b5-11e7-9b30-1bba63c3e9e5.png)

**Comment by falls2lawrence** [comment]
Increasing the mesh margin out beyond your art work when creating your mesh (to say 10 or 20) reduces this darkening effect. 
setup the erode for one of your columns then copy and paste into the connections of other columns that need this effect. most likely it wouldn't even take a minute to do 30 or 40 columns using this copy/paste route. 
but when all is said and done, I'd be happier if this "halo" didn't exist. I limit myself to one plastic tool application per character. for how elaborate this rig seems to be, you could probably getaway with not using the plastic tool as heavily as you are.

**Comment by Orphanlast** [comment]
Yeah, this is something that really needs some love.

**Comment by Orphanlast** [comment]
Why hasn't this recieved any donations? Seriously? This has been here forever and I'm sure there's plenty of people that use the plastic tool and cutouts on a regular basis. Seeing as my workflow currently doesn't utilize cutouts, I don't see a need FOR ME to donate. But there's gotta be a demand for this.

I reported this in my Opentoonz News video today. Hopefully that will get people gravitating towards giving a donation.

**Comment by snapai** [comment]
Is there a bounty on it? Has anyone agreed to work on it for one? I thought this was just waiting on a fix.


-------- Original message --------From: Orphanlast <notifications@github.com> Date: 1/14/18  4:00 AM  (GMT-05:00) To: opentoonz/opentoonz <opentoonz@noreply.github.com> Cc: snapai <snapai@weanimatethings.com>, Comment <comment@noreply.github.com> Subject: Re: [opentoonz/opentoonz] Plastic Tool creates black contour (#1249) 
Why hasn't this recieved any donations? Seriously? This has been here forever and I'm sure there's plenty of people that use the plastic tool and cutouts on a regular basis. Seeing as my workflow currently doesn't utilize cutouts, I don't see a need FOR ME to donate. But there's gotta be a demand for this.
I reported this in my Opentoonz News video today. Hopefully that will get people gravitating towards giving a donation.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opentoonz/opentoonz","title":"opentoonz/opentoonz","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opentoonz/opentoonz"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Orphanlast in #1249: Why hasn't this recieved any donations? Seriously? This has been here forever and I'm sure there's plenty of people that use the plastic tool and cutouts on a regular basis. Seeing as my workflow currently doesn't utilize cutouts, I don't see a need FOR ME to donate. But there's gotta be a demand for this.\r\n\r\nI reported this in my Opentoonz News video today. Hopefully that will get people gravitating towards giving a donation."}],"action":{"name":"View Issue","url":"https://github.com/opentoonz/opentoonz/issues/1249#issuecomment-357497689"}}}

**Comment by Orphanlast** [comment]
I saw it just today, like around 3AM

**Comment by Orphanlast** [comment]
Nope. That was this page. Here... let me see if I can find it

**Comment by jpturcotte** [comment]
Won't https://github.com/opentoonz/opentoonz/pull/1726 fix this, @shun-iwasawa?

**Comment by Orphanlast** [comment]
https://www.bountysource.com/issues/45860184-plastic-tool-creates-black-contour

**Comment by shun-iwasawa** [comment]
I found that the black contour appears because as follows:
- The plastic-deformed images are unpremultiplied before being stored in the texture. ( ` TRop::depremultiply` is called [here](https://github.com/opentoonz/opentoonz/blob/792dc2b6b402d622292efe815bfaa2635c43eeb9/toonz/sources/toonzlib/textureutils.cpp#L37) for camstand mode and [here](https://github.com/opentoonz/opentoonz/blob/792dc2b6b402d622292efe815bfaa2635c43eeb9/toonz/sources/toonzlib/plasticdeformerfx.cpp#L353) for render mode)
- The texture is linear-interpolated on rendering. ( set in [here](https://github.com/opentoonz/opentoonz/blob/792dc2b6b402d622292efe815bfaa2635c43eeb9/toonz/sources/tnzext/meshtexturizer.cpp#L141-L144) )
- The black contour appears at the border of the image because for now the interpolation is computed between colored pixel and full-transparent pixel. For instance, interpolation between red pixel (R255, G0, B0, A255) and full-transparent pixel (R0, G0, B0, A0) will be (R128, G0, B0, A128) - which will cause dark contour.
- The problem can be fixed by "expanding" border color before storing the raster - then the interpolation will become between red pixel (R255, G0, B0, A255) and **RED**-transparent pixel (**R255**, G0, B0, A0). Then it can get the ideal interpolated color (R255, G0, B0, A128) at the border.
