### ISSUE TITLE
(WIP) Translation management

### ISSUE THREAD

**Issue by mospina** [opentoonz/opentoonz#125]
Will the translations (UI and Docs) use a translation management system? Like zanata or pottle? This will make translation easy to manage and translators can use translation memories, glossaries and other tools.

**Comment by odysseywestra** [comment]
It still up in the air. I suggested using Weblate since MyPaint uses it and so far it doing pretty well.

**Comment by morevnaproject** [comment]
Transifex is also a good option. You can host your translation projects directly on their website (that reduces the maintenance work). Their service is free for open-source projects.

**Comment by mospina** [comment]
But it is not opensource as far as I know

**Comment by natowi** [comment]
I can also recommend Transifex.
@mospina "TOONZ GOES OPEN SOURCE" http://www.toonzpremium.com/#!news/aawrs

**Comment by mospina** [comment]
:-) Toonz goes open source but Transifex doesn't. They went close source since a couple of years.

**Comment by morevnaproject** [comment]
So, anyone interested in setting up account for community online translation? This will help to improve translations a lot.

P.S. I have nothing against Weblate. ^__^

**Comment by shun-iwasawa** [comment]
I'm very new to the online translation, but am quite interested in it since it would be suitable for translating [the user guide](https://github.com/opentoonz/opentoonz_docs) as well.
As far as I can see, both Transifex and Weblate seem to have a plan for open source project and also support managing Qt Linguist (.ts) files.
I'm currently focused on preparing the next release so I'll check them afterward. Any advice and suggestions will be greatly appreciated!

**Comment by gab3d** [comment]
@shun-iwasawa 
regarding release preparation and translation, what's the procedure to follow?
I mean, it'd be great to have some sort of "release ahoy" for translators to know the release will be in a certain period of time, so that everyone involved can complete the pending strings before that time, and we get in good shape for release date in as much languages possible.

**Comment by gab3d** [comment]
also, prior to the moment the release ahoy is issued, the .ts file strings should be updated for every locale (or at least updated in the japanese .ts file and we could update our language from there).
...something to make us sure that this are the latest (and all there is) to translate before release date.

**Comment by mospina** [comment]
Is there any schedule for string freeze or any other activities? I would be interesting in helping setting up thing.

**Comment by shun-iwasawa** [comment]
I'm thinking of (hoping for) releasing the next release by the end of this month.
After implementing some features which are requested by Japanese animation studios, I'll have period to concentrate on reviewing existing PRs for a few weeks before "freezing" features (strings will almost be frozen, accordingly). And as @gab3d and @mospina suggested, it would be nice to have one week for test, bug-fixes and updating translation before releasing.

... Wow, we don't have much time. I estimate for now that the release will be at some day in the last week in this month.

**Comment by jpturcotte** [comment]
Any updates on that front?

**Comment by RodneyBaker** [comment]
A few translation requirements are pending for this next release.
The one that comes immediately to mind is the addition of Korean language (PR #1589)

**Comment by RodneyBaker** [comment]
@gab3d can you assess this in light of current translation process and management.
It seems to me we have an effective process in place.

Closing for now pending discussion and determination to reopen.

**Comment by gab3d** [comment]
As to my personal experience, all I need to be able to translate the UI are updated .ts files, if that continue to come in a timely manner, then it's all OK.
Perhaps I'd like to be able to update my own TS files just to be able to have nightly builds with updated translations on a regular basis,  but I understand that's not critical. (and since I don't have the knowledge to do it myself, I'm prepared to just wait...) 😉 

As for the translation of docs I think the experience so far have been good, by having a local repository, translate using PoEdit, and finally using GitHub for uploading the updates directly to the repository.

...not much else to comment on that front.

**Comment by RodneyBaker** [comment]
I'm not that familiar with PoEdit.  Looks solid.
When I was looking before the one thing I wanted but couldn't find was a simple way to put all the translations side by side and see the differences.  I suppose any Diff editor can do that but most of those are designed for 1 to 1 comparisons.   Perhaps a good XML parser...
