### ISSUE TITLE
UI:  Text fields lose focus  while selected

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#1262]
![hoverbug](https://user-images.githubusercontent.com/29300971/26969077-bea0142a-4d04-11e7-855a-e73e07f7ac26.gif)
the textfield in the edit window looses its selection when hovering away from it.
you can only change the number when keeping the cursor exactly over the textfield.
other texfields work properly.
i use it often to flip my characters heads horizontaly by setting horizontal scale from 100% to -100%

**Comment by bobbybutterfly** [comment]
sorry, seems to be not a bug, but a feature.
All workspace texfields have this. Automaticly deselect on leaving the window:/
Did not know this behavior from other programs.
annoying, because the edit tool textfield is soo small and narrow.
in a way it brakes the fast and easy workflow for me

**Comment by shun-iwasawa** [comment]
As you pointed, for now the keyboard focus will move when the mouse cursor enters another panel. It is not a bug but a feature to make it easier to use shortcut keys without clicking on the panel.
I'll try to modify this behavior, preventing focus change if the current keyboard focus is on a widget of any subclass of `QLineEdit`.

**Comment by bobbybutterfly** [comment]
@shun-iwasawa great! thanks for your quick attention:)

**Comment by RodneyBaker** [comment]
This is still a considerable issue when trying to type into text fields.
In some cases it takes focused effort to enter values or text because the focus keeps slipping away.

Also:  I wonder if this might relate to other reports of loss of focus for other events and processes.
Perhaps if a delay could be introduced at the moment the cursor enters a text field so that the focus can remain there?  I know this can be challenging in the code because some users use the keyboard almost exclusively while others almost exclusively use their mouse/pen.

**Comment by artisteacher** [comment]
Perhaps the delay could be added for use with a stylus specifically? I think the stylus makes it much more challenging to maintain focus with compared to a mouse.

**Comment by RodneyBaker** [comment]
It is not clear if the solution discussed here was ever implemented.
@bobbybutterfly Are you still experiencing this issue?

cc:  @shun-iwasawa

**Comment by bobbybutterfly** [comment]
@RodneyBaker 
the issue still exists
