### ISSUE TITLE
RFE: Pixels as unit of measure

### ISSUE THREAD

**Issue by digitallysane** [opentoonz/opentoonz#127]
As the title says, would be great to have pixels along mm, inches etc. For people not formed in a strictly traditional workflow it makes more sense.
Toonz 7.2 has it AFAIK.

**Comment by CodyEakins** [comment]
In some important areas of the program, the pixel unit is available. For example, the Cleanup Settings, Canvas Size, and Camera/Render Settings all have pixel inputs. 
There are only a few areas I do not see pixel units where it would be convenient to have them. They are the edit tool, the selection tool, and the ruler tool...
Can you think of any other areas?

Please note that I am not criticizing this change, because I DO support it, I just want to know which areas should be updated/what you had in mind.

Another area I could think of that would be benefited by having **any measurement values at all** would be the Control Point Editor Tool, which allows users to select and manipulate individual vector points on a stroke/curve. The user should be able to input where exactly they want the selected point(s) to be located on the canvas/environment (or see what values they are currently located in), as well as be able to move the select points via the arrow keys. In some cases, if you try the lateral with the current edition of the tool, the program will crash.

When I think of this change, the vector controls Inkscape and Adobe Illustrator come to mind, in terms of good application of control point manipulation/presentation.

**Comment by digitallysane** [comment]
If by edit tool you mean transformations in general (including in the curve editor), that's pretty much what I had in mind.

**Comment by turtletooth** [comment]
They are actually there.  It is just not enabled in the code.  I will look into it.

**Comment by turtletooth** [comment]
Done and pull request submitted.

**Comment by shun-iwasawa** [comment]
merged.
