### ISSUE TITLE
Renaming levels in xsheet doesn’t update browser.

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1279]

**Comment by MikioKimura** [comment]
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 7
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by RodneyBaker** [comment]
@MikioKimura   Just to be sure... i
![watch file system preference](https://user-images.githubusercontent.com/2576432/49899133-762efe80-fe20-11e8-946d-570eabbc2eba.png)
s the option "Watch File System and Update Browser Automatically under Preferences > Geneneral turned on.

**Comment by RodneyBaker** [comment]
There appears to be an issue here where the 'name' of the level and the 'filename' are not necessarily  the same.  This is demonstrable by looking in Level Settings where there is a name field and a path to the file in the field beneath.  The 'name' can be changed and yet the actual path/filename do not change.

This as opposed to when using the Browser right clicking and using 'Rename' where the filename will be changed.

This is the long way of stating that the 'name' of the level and the 'name' used in the Browser listing are not the same thing.

Perhaps the 'name' field of the Level would be worded better as 'title'?

**Comment by gab3d** [comment]
This is not a bug, just the way the software works, letting the user assign a custom display name for a level in the Xsheet/Timeline.

**Comment by artisteacher** [comment]
I definitely found this confusing when I first started to use OT. I think the reason that it just changes the "display name" is that renaming the actual level breaks the paths. This is especially an issue if a level is used in multiple scenes.  When you are the only one working on a project, it might not be a big deal. However in a studio setting, it could be frustrating. Changing the name field to title or display name or something similar would be helpful. It would be even better if in the future an option could be added to "update all scene files in the current project" when something is renamed so that the paths updated upon renaming. Then renaming from the level settings could actually rename the level.

**Comment by RodneyBaker** [comment]
This issue has been described in several places but is normal usage although admittedly confusing.

The issue could use a review and determination is there is something that could assist the user in better identifying the level when moving back and forth between xsheet/timeline and browser... and presumably other locations within Opentoonz.
