### ISSUE TITLE
Cleanup causes Crashing

### ISSUE THREAD

**Issue by amotarzi** [opentoonz/opentoonz#1299]
Whenever I clean up a scanned drawing and change from greyscale to color it crashes the program. Is there no way to auto submit bugs so they can be worked on? How do you handle bug reporting and fixing??

**Comment by artisteacher** [comment]
This might be related to #654. When you are reporting a new bug, open an issue here like you have done. If it is a known bug, you should comment on the open issue to provide more information instead of starting a new issue. 

It is helpful to give the developers as much information as possible - ie. your operating system, version of OpenToonz, and any repeatable steps that always result in the problem. Including screenshots, animated gifs, and crash reports(in a text document format) can also be very helpful depending on the issue.

**Comment by amotarzi** [comment]
Hi, thanks will do a proper search next time (new here) and found your bug report and can definitely confirm it happening with tiffs. 

Thanks and wish I was a programmer :)
