### ISSUE TITLE
UI: Levels layout in schematic

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1324]
Now that you are discussing for redesign of the column #1316, Please take a look at toggle icons in schematic too.

![schematic toggle icons](https://user-images.githubusercontent.com/16509592/28021796-5d6f7684-659e-11e7-8589-295657486bfb.jpg)

**Update**:
It gets worse when zoom out in FX mode.

![fx-zoom-out](https://user-images.githubusercontent.com/16509592/29002771-45f4e134-7abf-11e7-8399-b51ee10bcb28.jpg)

**Comment by 2dvision** [comment]
Another problem is the length of the level is small and one size. There is no way to see the full name of the levels. For example in toon boom, The length of the level is the same as the level name.

![node toon boom](https://user-images.githubusercontent.com/16509592/28743247-abdb0930-745a-11e7-862e-b8a087ef471d.png)

**Comment by artisteacher** [comment]
I agree that whatever icons are chosen for the xsheet/timeline should also be used for the schematic nodes.

It would be great to have a visible off state for the visibility buttons too. Particularly when zoomed out, there is absolutely no cue that a visibility toggle is there. It can be hard to keep track anyway since the toggle position changes when zooming in and out.

Speaking of high dpi, are the triangles supposed to be so small and are they in the right positions?
<img width="175" alt="screen shot 2017-08-06 at 2 20 35 pm" src="https://user-images.githubusercontent.com/21159116/29005849-7f2e9be6-7ab2-11e7-9c50-44faf3830b97.png">
<img width="314" alt="screen shot 2017-08-06 at 2 14 52 pm" src="https://user-images.githubusercontent.com/21159116/29005818-b5666226-7ab1-11e7-83f1-b7d196fb4a3f.png">


Also, this is a little off topic but can the colors of the nodes be edited in the css? The column/layer colors can be changed for the xsheet/timeline but I haven't figured out where to do the same thing for the schematic. Having the colors changed in the xsheet but not in the schematic is not ideal.

**Comment by artisteacher** [comment]
The icons have been updated so this can may be able to be closed.

**Comment by RodneyBaker** [comment]
Will close pending input from @turtletooth @manongjohn or others who have been working to update/enhance the Schematic.  As of this date I don't think all of those commits have been reviewed/merged.  

I do think the specific bug identified here has been resolved.
