### ISSUE TITLE
PlasticTool not working on a Source of a Particle Fx

### ISSUE THREAD

**Issue by hogboon** [opentoonz/opentoonz#1330]
Adding a skeleton on a source column of a particle fx cause the disappearing of all the particles, in preview mode and on the rendering obviously. Only adding the first root node of the skeleton, without modifying the mesh. [Mac Os X Sierra]

**Comment by hogboon** [comment]
I've noticed that in the same situation, trying to add a second skeleton (click on the "+" in Build Skeleton Mode) cause a crash. This happens only if the column is a source of a particle fx.

**Comment by artisteacher** [comment]
I'm getting the same results.

**Comment by hogboon** [comment]
It seems that it's a non implemented feature, not a bug. Take a look at the question i post in this youtube tutorial: https://youtu.be/VDEtstJeSmk

**Comment by artisteacher** [comment]
Either way, adding a second skeleton shouldn't cause a crash.

**Comment by RodneyBaker** [comment]
This is one of several similar issues where a crash occurs where a feature is not implemented.
As the current feature set does not account for the unintended usage it should be investigated to at least prevent a crash.  

Potentially similar issues where unintended usage results in a crash include:

#2663

Currently there is no tag for this type of issue beyond the standard bug, crash tags with possible addition of enhancement and feature request tags where appropriate.  The issue does fit well into the  'known issue' so the more we can document about the problem the better.

**Comment by RodneyBaker** [comment]
This is one of several similar issues where a crash occurs where a feature is not implemented.
As the current feature set does not account for the unintended usage it should be investigated to at least prevent a crash.  

Potentially similar issues where unintended usage results in a crash include:

#2663

Currently there is no tag for this type of issue beyond the standard bug, crash tags with possible addition of enhancement and feature request tags where appropriate.  The issue does fit well into the  'known issue' category so the more we can document about the problem the better so that at least users are made aware of the problem.
