### ISSUE TITLE
New Contributor?

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1357]
@shun-iwasawa What are your thoughts on making @blackwarthog a contributor?  Right now, only you and I are active regarding PR reviews and it would be nice to have another on the team who is able to do some of that work.

**Comment by morevnaproject** [comment]
I also would appreciate if you add me as well. I do not want to do any PR merges or reviews, but contributor rights will allow me to create a Project Board (https://help.github.com/articles/about-project-boards/) to effectively manage work of @blackwarthog. ^__^

**Comment by shun-iwasawa** [comment]
Yes, I'm planning to assign @blackwarthog as a committer as soon as the MyPaint PR #1124 will be merged. He did the great work with it.
For now I'm reviewing & modifying #1304 . Then I'll see #1124 . 

@morevnaproject I did not actually know about the Project Board. I'll see the description.

**Comment by morevnaproject** [comment]
@shun-iwasawa Project Boards allow to group some issues together and arrange them by status. But it is not the same as Labels, because with Boards it is possible to change put issues in specific order, like tasks.

For examples, please see our Board for MyPaint brushes at @blackwarthog's repository - https://github.com/blackwarthog/opentoonz/projects/1
Here is another one for Synfig - https://github.com/synfig/synfig/projects/1
And one more for MyPaint - https://github.com/mypaint/libmypaint/projects/1

For OpenToonz I would like to have one board to collect Linux-related issues (since we are supporting this platform). And one more board for planning further improvements of MyPaint brushes feature.

**Comment by shun-iwasawa** [comment]
Invited @blackwarthog .
