### ISSUE TITLE
Column color filters not working for vector levels

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1359]
This is not a big deal and I'm not sure if this is a design choice, a mac specific issue or just a bug in general, but the color filters accessible in the xsheet column header do not seem to have any visible effect on vector levels or sub-xsheet levels.

This is on OS X 10.12.6.

**Comment by manongjohn** [comment]
According to the tooltip when you hover over it, it doesn't work for vector levels.

**Comment by artisteacher** [comment]
Thanks, I hadn't noticed the tooltip. In that case, either the filter dropdown should be disabled for vector levels or there should be a warning dialogue when trying to set a color.

**Comment by turtletooth** [comment]
Disabling the dropdown won't work since you can actually have vector and toonz raster on the same column.

**Comment by RodneyBaker** [comment]
There are a host of 'issues' that we as users navigate around that strictly relate to whether the Level is raster, Toonz Raster or Toonz Vector.  It may take some comparison charts and much research to identify all the various pros and cons to each 'flavor' and formulate optimal solutions.  Once all of these are better understood it may be possible to optimize the UI further but care must be taken not to lose some of the features that make the uniquely hybrid nature of OT such a joy to work with.  I'm currently investigating what appears to be several instances of lost functionality in the xsheet after the introduction of the Timeline view which concerns me.  The plus of heavy development is worth the frustration but none of us want to lose features that we enjoy using.

A supreme example of the kind of issues the user can face when trying to work outside of the range of the Level type is MyPaint brushes.  Users that attempt to be creative with MyPaint brushes will find themselves frustrated when they attempt to draw/paint on any Level that is not plain (generic) raster.  It would appear that an error routine might need to be created that fires when an 'out of range' option is attempted.  A graceful error might predict the users intent and solve the issue without them even realizing the error.  For instance, when attempting to draw/paint with a MyPaint brush on a Toonz raster or Toonz vector Level OT might automatically create a new (generic) raster Level and let the user go on being creative.  At some point the user will realize they cannot MyPaint on certain types of Level.  Even if they don't understand why or why not they know how it works through experience.

Solving this larger issue of context sensitivity and application awareness of Level types is a major undertaking but I'm confident it is one that will eventually be resolved.  A lot of it seems to rest on understanding and usage of common terminology.  This isn't easy at present because almost everyone is still learning OT's unique terms and parameters of functionality.

**Comment by manongjohn** [comment]
@RodneyBaker Lost functionality?  Let me know what you find. I tried to compare as much as I could between the official release and the updated xsheet/timeline, making sure everything was exactly the same if not slightly tweeked or fixed if I found an obvious bug.

**Comment by RodneyBaker** [comment]
@manongjohn 
I will definitely let you know if I can confirm/replicate any issue.
I want to set your mind at ease though as I have no confirmed issues that directly relate to the addition of the Timeline.

I should be more careful in my wording but... for the record:
I experienced several undesireable 'losses' after numerous changes that included your very welcome addition of the Timeline.   They don't appear to relate to the Timeline addition.

I will open a bug report for that issue at the point where I can record the difference between older functionality and new and post it so it can be readily observed and understood.   That particular issue relates to audio scrubbing in the xsheet and as far as I can tell doesn't have a similar capability as of yet in the Timeline.  There is at least one open issue relating to audio scrubbing so I'm trying to factor that in as well.  It appears to be a separate issue.

A related 'loss' I have yet to confirm because I need to re-install an older version of OT where I am reasonably certain the functionality existed so that I can compare to current releases.  This issue relates to being able to separate column entries at the frame level.  I am convinced we have lost the abilty to separate column data at the frame level but.... did I accidentally change a setting that now prevents this (user error?) or did some functionality actually change?  Interestingly, this also relates to audio (although I confirm the same issue with imagery.

As this topic concerns Column filters not working with vector levels I have taken us off topic, for which I apologize.  So, to put us back on topic...

If the topic title was reworded to "Column color filters do not work with vector levels" this would be a true statement of the current functionality of the filters.  To make the filters work with vector levels would be a new feature request.  As this is working as designed I believe this issue can be closed unless it can be reformed into a bug report.  Because this is part of a much larger issue with concern for interfacing with different Level types it may be prime fodder for a larger discussion in the OT Forum.  @artisteacher - what say you?

**Comment by artisteacher** [comment]
Since this is the expected functionality, I'll close this issue. I do still think a warning dialogue when trying to add a filter color to a column with vector levels would be more helpful than the tooltip in this case, but it's a very low priority.
