### ISSUE TITLE
Test project of sample sceens

### ISSUE THREAD

**Issue by damies13** [opentoonz/opentoonz#1369]
This is more a Feature Request or suggestion than an issue....

What I think could be useful is to have a project (possibly included in the source tree with the code?) that can be used for testing development build of OpenToonz are still rendering correctly.

The concept would work something like this:
- After completing a build of opentoonz (especially a build where changes were made to the rendering engine or tfarm components) a developer would load this test project and render the project, then connect to the tfarm and render again with the tfarm.
- The output of these renders can then be compared to a known good render
- if the output is png images we can use imagemagick compare the individual frame images (https://www.imagemagick.org/script/compare.php)
- If we output a video file then apparently we can use ffmpeg to compare the video files (https://stackoverflow.com/questions/25774996/how-to-compare-show-the-difference-between-2-videos-in-ffmpeg)

This project should contain various scenes that test specific features or combinations of features, e.g.:
- Vector only scenes
- Raster only scenes
- Combined Raster and Vector scenes
- Check plastic tool e.g. issues #856 & #1055 
- Check for artifacts from previous frames (issue #568)

I'm sure there are many more things that could be checked for as well, and a search for previous rendering issues would probably give a good starting list of issues to check for.

The scenes don't need to be long, 1-2 seconds (25-50 frames) is probably plenty to detect most issues. Ideally the scene should be named for what it tests. Also in many cases they don't need to be works of art, bouncing balls, rotating moving or twisting squares or grid patterns, calibration marks and colours, etc will probably be sufficient or even better for detecting rendering errors.

In my case this would be very useful as I make tweaks to the tfarm components so I can ensure i'm not breaking anything.

Unfortunately I'm not a guru of using OpenToonz's UI, so an experianced / power user of OpenToonz is probably best placed to create this project, but this could also provide an opportunity for people reporting bugs to add a scene to the project so that developers can know for sure if the reported bug is resolved.

I'm interested in feed back if others think this is a good idea, want to add suggestions on what features are important to them or want's to put their hand up to create this project.

Dave.

**Comment by turtletooth** [comment]
I like this idea.

**Comment by RodneyBaker** [comment]
Thanks @turtletooth for replying and bumping this topic back up.

I like the idea too.  OpenToonz (or any program for that matter) can use a
good benchmark testing 'protocol'.
I suppose the difficulty might be in what that testing data might be and
the methodologies to test the outcome.
OpenToonz does have the facility to run a Diff on rendered images via
Schematics.

Project file -wise it would be good to start really small and simple.
Anything too complex and no one will want to run those tests.

The primary issue that I see is that there isn't a internal testing system
inside of OT now so one would have to be created... I would think in like
fashion to @turtletooth's addition of the 'Quick Render to MP4' feature.

Also, it's one thing to run a test that is fully automated and largely
autonomous but quite another to have a user runs tests that require a lot
of steps.  Every step taken introduces variation and the possibility of
introducing error.

I suppose a useful testing project might be that of simply rendering out a
prepared scene that produces an image that says, "Welcome to OpenToonz" or
some equivalent.

I'll stop there because those others know vastly more than I about how
things like this work (and could work) except to say that a 'testing suite'
that also acts as an introduction to OpenToonz operation and production
itself I think would be optimal.  How does a user take a scene from start
to finish and in the end see success.  It is this outline that need to be
considered and then... I think... two tracks be presented.  The first would
be the actual steps involved in completing each individual task that makes
up the whole and the second would be an automation of that same process so
the user can manually go through those steps and also hit a button (or menu
item) that runs through that same process automatically on its own.  I
think perphaps some of the later.. .that automation... would rely on OT
scripting but I don't know if it (scripting) are up to that challenge.  I
suppose a useful testing project might be that of simply rendering out a
prepared scene that produces an image that says, "Welcome to OpenToonz" or
some equivalent.  I do think this is highly appropriate that @Dave is
suggesting this because the Render Farm seems a very likely place to
automate a good part of this testing process and at the same time benefit
the user by demonstrating a useful process that can aide them in
production, namely that if we as users swap out our own Project for that of
the project in the 'testing suite' we have now ran the OT test to establish
a baseline using.... Our Project!  :)


Those would be some of my thoughts.
As I said.  I like the idea.

**Comment by artisteacher** [comment]
How complex this gets depends on the testing focus. I agree if there are too many steps, the average user might not be interested. However for getting performance data when someone is dealing with a specific issue, it would be helpful to have some more complex scenes or perhaps just a bigger selection. Perhaps the default test scene would be very basic, with a variety of other scenes intended for specific scenarios.

Other scenes that could be useful for testing include:
- scene of cut-out animation with the skeleton tool
- scene utilizing fx

If the wiki gets going, it could be great to post tutorials using the test scenes.

I do like the idea of having the test process be either manual or automated. Would the automation be complex to code?

**Comment by RodneyBaker** [comment]
Would the automation be complex to code?

No but Yes.  ;)

Much will depend on the structure that is already there and much of that appears to be undocumented.  I'm speaking of OT's scripting engine here.  It is unknown (to me) what elements of OT are exposed to scripting.  For instance, how much of the renderfarm is exposed to scripting.  If none... there would need to at least be some.  If enough to run a project through the tfarm renderer then at least one full pipeline of a Project file can be tested.  

Note that I'm trying to attack/envision this from a very broad view with an eye for an underlying system that isn't just useful for testing and analysis but also useful for actual production.  The only difference is the input Projected.  *If* Project A is input then the output should be the same every time... on the same system... as long as nothing has changed.  The benchmarking aspect then relates to the various variables and how well they can be isolated.  For instance, I upgrade my computer so that it has 16GB of memory rather than 8.  I *should* see an improvement in render time but I *should not* see a change in the outputed image (quality or otherwise).

This is a big area but it need not be difficult to implement.  
It could be ran today by rendering an 'empty' project.
This is perhaps the ultimate 'baseline' with the setup being to test a generic default project as create in OpenToonz without any other variable introduced.

Steps would be:
1.  Start OpenToonz
2.  Via the Startup popup menu Create a new Scene named 'test'
2a.  **
3.  Via File menu select "Fast render to MP4" or use shortcut key "Alt+r"
4. Measure something

In this benchmark which I will nominate as Benchmark 0.0 the tester will notice a problem; OpenToonz will generate an error "The command cannot be executed because the scene is empty."

The immediate remedy to this would be to designate a project to test.
So, benchmark 0.0.1 needs to be a test where a specific project is opened and then rendered.
This 'project' would likely be the name of the benchmark.
For instance, a user desiring to run an official test (currently) might be instructed to download a tutorial file provided for the Toonz software as has been used in other testing by OT developers.  The steps then become:

1.  Start OpenToonz
2.  Via the Startup popup navigate to the test Project and open the Project
3.  Via File menu select 'Fast Render to MP4"
4.  Measure something

How well that will work will depend almost entirely on the setup and contents of the Project file.

Optimization and Automation
Optimization and automation of the testing process might be to identify and thoroughly examine a Project to determine what it can be used to measure and what it may not be optimally designed to test.  To fully automate the test as an official benchmark the process might be hardcoded into OpenToonz where a user simply presses a button that runs through the test and displays the results.

Disclaimer:  I use the word 'test' here but there is likely a better word.  It might sound a bit high-fallutin' but ulitimately when a series of tests are collected. vetted and launched as a suite to tools the simple process might be referenced as 'Diagnostics' with the user only having to push a button that states 'Run Diagnostics'.

**Comment by damies13** [comment]
Wow this got so many positive comments :)

I was envisioning starting out very simple and allowing it to grow organically. A project where each scene was only a few frames, just enough to test a specific feature / issue / bug. No scripting is really required to start, just open the project manually and render all scenes. Then comparing could be handled by a simple 2-5 line shell script / windows cmd file.

I take the point that if it get too big people won't want to run it, so perhaps we could initially start a "full" project, and if we get to the point that the full project is unwieldy then a "Quick / Lite" project could also be adapted with the "essential / important" scenes from the full project.

I love the idea of automating the test case, especially as that is close to my own profession, however I viewed that as out of scope of my initial suggestion. I think it's more important initially to have a way measurably knowing if new code has broken anything. As for the automation, that can come later, and is probably something I can help with, where as creating the test scenes is still outside my skill set. @RodneyBaker I'd be interested in knowing more about OT's scripting engine, is there documentation of it anywhere?

I'm glad for the positive response, and look forward to using the test project.

Dave.

**Comment by RodneyBaker** [comment]
@damies13  Yes, there is a Toonz webpage with sample scripts and a PDF document.

http://www.toonz.com/htm/support/script.htm

There is also a simple intro video (in two parts as I recall) by Simon.
I'll try to dig up the link but it's on youtube and it was linked several times in the OT Forum.

Disclaimer:  I do not know the extent of scripting that is active in OpenToonz as compared to Toonz Harlequin/Bravo.

The tutorial projects that some have used to troubleshoot features are located on the Toonz site as well.

**Comment by damies13** [comment]
ECMAScript and JavaScript, thats awesome, languages I'm familiar with so not much of a learning curve.

**Comment by RodneyBaker** [comment]
> ECMAScript and JavaScript, thats awesome, languages I'm familiar with so not much of a learning curve.

Sure.  YOU can say that.  ;)
(And I am very glad you can say that)

I made an attempt to learn a little Lua for scripting purposes in Blackmagic Design's Fusion (which just released v9 BTW... sweet...  but any scripting/programming I do is mostly restricted to copy/paste and minor tweaks to code.  I mention Fusion because the UI is very intuitive where it comes to identifying elements for use in scripting.  One of the hardest parts of scripting (in my estimation) is just identifying the various elements you want to work with.  If not familiar with Fusion I recommend checking it out.  It's a must have application for use in any artist/animation/vfx pipeline.  Free (and Studio version recently reduced from 1K to $300).  Blackmagick is also the company behind the Davinci Resolve color corrector video editor for those with a need for high end video editing and color correction.

I hope there is more available to OpenToonz scripting that is immediately apparent.   For instance, you are working with the Renderfarm and whatever can be automated there (and with rendering in general) would be most welcome.

**Comment by damies13** [comment]
Getting back to the original topic...

@artisteacher Great Idea's, Thanks.

I agree not something that the average use would want to run, but that's not really what I was intending, I was more intending it as a way for developers to verify new versions of the application hasn't broken features that people are already using, the first of a suite of test cases to help improve the quality of OT releases (not that it's bad, but we always can do better).

Would you like to have a go at creating the first couple of scenes using your suggestions?

**Comment by artisteacher** [comment]
Sure, I'm not a professional though :)

Are there any guidelines we want to start with to keep things uniform? Camera size, number of frames or anything?

**Comment by damies13** [comment]
@artisteacher I think the guidelines should be kept simple and open to allow all test cases, these would be my suggestions:
- Camera size: Use 720p (1280 x 720) as default (most digital tv broadcasts are this size) unless a higher resolution is needed to reproduce an issue, then use the minimum resolution that reproduces the issue. At 1280 x 720, the fame images should be small enough to not take up a lot of disk space while being big enough that when compared to the known good image they can be accurately compared.
- number of frames: Use minimum number of frames to reproduce / verify an issue, i.e if it can be tested with 1 frame use 1 frame, likewise to demonstrate a tweening issue it's likely you will need a minimum 3-5 frames. 
- General guide line would be to use the minimum resources you need to determine a pass/fail for the feature being tested.

**Comment by RodneyBaker** [comment]
While this request has not been fully implemented we are not taking advantage of the resources we have.
No updates to this request since Aug 2017 suggests perhaps we can move this discussion over to the OpenToonz forum where the OpenToonz community can dive in and complete the requirements.

Also, a basic sampler project is available and located here:

https://github.com/opentoonz/opentoonz_sample

While it lacks a lot of the specific vector and cutout requirements it is a good place to start and would be a good benchmark.

Recommend refreshing this request in some capacity to meet the stated desire.

@damies13 Your thoughts?
