### ISSUE TITLE
OT does not refresh altered image file

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#1388]
import layered psd file into column. Delete the column.
Modify the image in Photoshop, save it.
Drag the new file into a column.
Still the old Image is shown not the new modified one.
Happends with loaded and imported files.

Only restart of OT solves the Problem; the altered Image is shown correct now

a simple reload button could help

**Comment by shun-iwasawa** [comment]
For non-PSD image files, you can reload them with "Revert to Last Saved Version" command in the right-click menu of the xsheet cells containing the target levels.
Regarding the PSD image levels, this command will not be shown for now since (as far as I guess) the command cannot reproduce the loading option. 

Even the levels are removed from the xsheet, the level registration will remain in the scene cast (and the image cache remains as well). So, as a quick workaround, you can do as follows:
- After deleting the column, open the Scene Cast window.
- Right click on the cast pane and select "Remove All Unused Levels".
- Load the updated PSD file again.

**Comment by turtletooth** [comment]
@shun-iwasawa To make this more clear for non-psd levels, what do you think of changing the command to "Load Saved Version" or something like that so users might get a hint that it can also be used to refresh a file.

**Comment by turtletooth** [comment]
Maybe replace with saved version?

**Comment by shun-iwasawa** [comment]
@turtletooth 
It's reasonable to alter the command name. If possible, I would prefer to set some name which is already used for the similar functionality in another (major) software in order to gain consistency.
Your suggestion "Replace with Saved Version" would also be fine.

**Comment by bobbybutterfly** [comment]
Thanks, your workaround "remove all unused levels" works reliably.
"Replace with saved version" sounds to long for me. Simply "reload" 
MAYA for example has a "reload" button in its Attribute Editor.

Btw: i cant find "Revert to Last Saved Version" command in the right-click menu of the xsheet cells:
 
![rightclick](https://user-images.githubusercontent.com/29300971/29109976-54eb1d48-7ce5-11e7-9ad7-8d80dd88e3d2.jpg)
