### ISSUE TITLE
Access to Wiki?

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1394]
@shun-iwasawa There is a guy on the discord channel who would like to contribute to the wiki.  Is there a way to grant permissions to just the wiki?

**Comment by Orphanlast** [comment]
It'd be nice if just about anyone can just pop onto this wiki and make edits. If it was accessable to anyone, logged in or not, I can totally see this wiki quickly becoming the now "help menu" to Opentoonz.

**Comment by Orphanlast** [comment]
*new

**Comment by Orphanlast** [comment]
I have a youtube audience of 379 subscribers. 80% of my audience is unsubscribed. 

So -- that said. I'm sure a good number of them enjoy writing.

**Comment by Orphanlast** [comment]
Well -- it needs to be open to EVERYONE. Because currently, I'm logged in and there's no "add page" button. 

So there's no opportunity for people to contribute to what could easily be the new Help Menu for Opentoonz.

**Comment by morevnaproject** [comment]
I think the best way is to use https://readthedocs.org/ for documentation. That way all pages are stored in GitHub repository and rendered to HTML pages. People can contribute to documentation via pull requests. So, anyone can contribute, but contributions are moderated. 

Here is an example how typical documentation made with ReadTheDocs is looks like - http://docs.readthedocs.io/en/latest/getting_started.html

This solution also supports handling translations of content in multiple languages.

Another option is to have a documentation website in Jekyll. The content of Jekyll website also can be stored in GitHub repository. There are some really nice themes specifically targeted for documentation, like this one -http://idratherbewriting.com/documentation-theme-jekyll/ 

The advantage for both solutions is that documentation will have separate repository then, so it's easy to grant permissions.

**Comment by Orphanlast** [comment]
I just want a wiki help menu. As long as the platform is professional enough, I'll be happy with it.

**Comment by Orphanlast** [comment]
So the issue with the opentoonz help menu was that the "add pages" button isn't available to everyone. For example, even while I'm logged in, I can't add a page. Before I can suggest people add pages to the Github wiki, I need to know that it's available to be edited, not just for me, but to anyone, logged in or not. Otherwise the Github wiki has failed before it ever had the chance to begin. So in the "Aug 13 2017 OT NEWS" vid, I suggested people go to the wikia page for now.

https://youtu.be/V8weuRM4Gc0

Emotional attachments aside, should the github wiki indefinitely be unavailable for editing to the masses, I don't think it can function as a viable help menu, no one has the time to write up an entire book's worth of how-to-work-opentoonz for free, single handedly. So a full public wiki capabilities need to be opened so that MANY people can add a page or two and in time, we can have a full comprehensive help menu.

Currently the wikia page offers this. And if or when the github page is brought up as a viable option, it wouldn't be too much difficulty to copy and paste pages from the wikia page and place them into the githup wiki.

Until further notice I will be pushing for the wikia page to become the new help menu. Turtletooth really wants it to be the Github wiki, and I tend to refer to his judgement. But... as it sands, I can't: http://opentoonz.wikia.com/wiki/OpenToonz_Wikia

**Comment by Orphanlast** [comment]
To address a previous comment. Managing the wiki through pull requests... sounds like it'd confuse most end users, while any other wiki just has an "add page" and still has moderation. 

Github isn't the most user friendly website. And forcing people to use all its features for the wiki will kill it before it even starts... 

So... I'll continue pushing for the wikia page.

**Comment by artisteacher** [comment]
I don't know if absolutely everyone needs to be able to contribute. While the majority of people would likely be responsible enough to post accurate content, there's always a couple mischievous people that deliberately add false information. Sometimes it's completely unintentional. I know there have been multiple times where I misunderstood how something works in the program. So as far as that goes, I can see the need for moderation. On the other hand, there's a huge backlog of pull requests as it is.

I don't know if there's an easy way to both submit and moderate but the more complex the process is, the less likely we are to get many contributors.

**Comment by RodneyBaker** [comment]
I'm refraining from sharing my experience and opinion of wikis in hope that enthusiasm will prevail and much success will be forthcoming.  :)

I just registered, logged in and created an initial test page (Guided Drawing) on the wikia (thinking it was the initially preferred wiki... what can I say... I'm slow).  I'm now caught up and see the other (github) wiki is still an option being explored but other avenues are being explored too.  

The primary critique I have of the current OpenToonz wikia is that it's very difficult (near impossible) to read due to the Gibhli image ghosted behind the text.  It's a good effort but simple (and readable) is always better.  Fix that and you'll at least have a workable option.

I'm torn between encouraging pursuit of a wiki and trying to steer folks away from such but regardless I will support any effort the community chooses to pursue.  I do have opinions but I'm not sure they matter a lot at this stage of the game.  The open source nature of OpenToonz multiplied by even a little enthusiasm could rewrite all the rules.  :)

**Comment by morevnaproject** [comment]
@Orphanlast 

> Github isn't the most user friendly website. And forcing people to use all its features for the wiki will kill it before it even starts...

This is kind of guarantee that wiki is edited by competent and dedicated people. ^__^

Today more and more non-technical people starting using GitHub (for personal websites, blogs, project management, research, etc.), so it's not a big barrier.
The proof is that many opensource projects using this approach of keeping their docs in that way (Blender, Python, Syncthing, etc.).

From my experience of maintaining the official wiki of Synfig Studio - http://wiki.synfig.org/ - (which is more similar to wikia approach) - the moderation on "add page" level is not enough. Because an average non-competent person can bring a lot of noise to the existing pages. ^__^

So, you have to always keep an eye on edit history. So, if you aiming at providing quality documentation, it's best to have moderation before the content goes to live to public.

Also, If I understood correctly, the wikia approach doesn't provide support for handling translated content (I mean wiki in many languages).

Just my thoughts.

**Comment by RodneyBaker** [comment]
Disclaimer:  The following does not suggest there be no wiki in the OpenToonz community.  A wiki just needs the proper champion to make it successful.  

I'm going to go out on a limb and suggest we bypass the wiki and that a menu item in OpenToonz should point the the OpenToonz forum.  There are some rough edges that would need to be smoothed out but this would resolve a few things, namely:

1.  The primary source of official information related to OpenToonz is the Google Groups forum.
2.  The OpenToonz forum provides a direct and well traveled path OpenToonz on github.

It is these two arenas that form the nucleus of official development, documentation and community.  Other branches then grow outward from this root; branches of the software, Youtube channels, websites, reddits,... even wikis.

If a menu item in OpenToonz under Help  points the user to the OpenToonz forum they will be at the center of where they can best find the answers to their questions.  It then falls to innovative users to publish information that highlights their resources.  Then with all eyes in focus the broader distribution of resources available can be explored.

Additional benefits:
(I think) Currently the OpenToonz forum is underutilized. (I believe I can prove this)  ;)
Pointing people to the forum can be of benefit to all OpenToonz users.
As useful products and services become available they can be promoted on the forum.

A re-look at the original intent of this request:
@turtletooth's request was to grant access to the wiki for a particular person.
The perceived desire would be to also have an open 'forum' where everyone can contribute to the documentation related to OpenToonz.  Additional thoughts relate to aesthetics and preferred platforms (i.e. we want this thing to be easily accessible, accurate and appealing (which might be interpreted as 'professional')

Constraints
Several constraints have been raised and concerns for 'bottlenecks' and lack of access highlighted as key elements that present road blocks.  My past experience says there is a limit to what 'official' channels can support because of legal concerns.  There is also the underlying issue of documentation itself which is outdated even before the digital ink gets cold.  Wikis represent 'living' documents which are continuously being updated.  I submit the OpenToonz forum does this also.

Official documentation
The only place we are likely to find official documentation is at the source and that would appear to be github.  Most references would then point to that resource or act as byproducts of that source.  And here's something I fail to do continually... Sources should be cited as often as possible.  It's no accident that github contains the actual source code as well as most of the documentation for that code.

I'll stop there but my feel is that the OpenToonz help menu should likely point to the OpenToonz forum.  If implemented it is likely a new forum area should be created to receive people that arrive from clicking on that option.  There is one program (coded by one guy) called 'Screen to Gif' that has the best help menu/processes I've seen to date.  The only problem is that when last checked... it wasn't working.  ;)

**Comment by morevnaproject** [comment]
> A wiki just needs the proper champion to make it successful.

Absolutely agree.

> bypass the wiki and that a menu item in OpenToonz should point the the OpenToonz forum.

I think it's OK to have link to forums, but not as replacement for documentation link. It's ok to have it   called like "Ask a question", but this is not documentation. ^__^

Regarding documentation I am highly recommend to study existing practices of successful projects in (open-source) software world.

@Orphanlast Although, I personally don't feel the wikia as best solution, this is just my opinion and I highly acclaim any your efforts toward making documentation. Whatever solution you will choose, it will be much better than having nothing. ^__^

**Comment by RodneyBaker** [comment]
> Regarding documentation I am highly recommend to study existing practices of successful projects in (open-source) software world.

I'm still trying to figure out how to best relate my experience with documentation without it being detrimental.  I want to encourage others.  :)

I just drafted a topic for the forum where I was going to open a discussion on this general topic but I didn't post it.  The timing didn't seem right.  The gist of that post was that I thought that rather than features and documentation we (as individuals and as a community) should focus on productivity (individually and collectively).   From the standpoint of production the associated features and documentation pretty much work themselves out.  In the end it's not the features that we want (although they are awesome and I want every feature that I can get) nor is it the documentation (although it helps us navigate through seemingly unfathomable workflows and concepts) it's to produce something.  For developers they have the added blessing of being able to produce the product that helps people produce the production.  :)

How do you drive new features then?   Determine what is required by production.
How do we create useful documentation?  Record the production experience.

Wikis, Facebook pages, websites, films, etc. are all byproducts.

Disclaimer:  I am not trying to convince anyone of anything here but rather to get the thoughts in my mind out.  If I heeded my own advise I'd be to deep in production to be posting comments to github... except maybe bug reports.  ;)

**Comment by morevnaproject** [comment]
Just a note: 
I just found that OT wiki at GitHub (https://github.com/opentoonz/opentoonz/wiki) could be configured to be editable by anyone who have GitHub account (without the need to add to repository Collaborators list). Please see details here -  https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by shun-iwasawa** [comment]
Thanks guys for ideas and proposals for making the documentation. I'm preparing a new repository for making the documentation based on read-the-docs (thank @morevnaproject for information!) and will assign wider people as collaborator. Thank you for your patience.

**Comment by shun-iwasawa** [comment]
I've made a new repository for the documentation:
[https://github.com/opentoonz/opentoonz_docs](https://github.com/opentoonz/opentoonz_docs)

It is written in [reStructuredText](http://docutils.sourceforge.net/rst.html) format, built with [Sphinx](http://www.sphinx-doc.org/en/stable/) and released via [Read the Docs](https://readthedocs.org/).

The URL of the documentation is http://opentoonz.readthedocs.io

OpenToonz is based on Toonz Harlequin 7.1 by Digital Video and overlap in many part in functionality. Toonz Harlequin already has a nice and detailed [User Guide](http://www.toonz.com/cgi-shl/download/71H/Toonz%20Harlequin%2071%20User%20Guide.pdf), so IMO it is reasonable to make the OpenToonz manual based on it, adding a descriptions for OT's original features.

You can refer to (or even copy as-is) its contents (all rights of the documentation are transferred to Dwango for now). I put an empty chapters as an initial guide, following the chapters in the Harlequin's User Guide.
So it is much appreciated if someone could fill up these contents, or newly add a useful chapter.

In contrast to the OpenToonz main repo, I'm thinking of assigning wider people as collaborator. Please post a comment to [Collaborator access request](https://github.com/opentoonz/opentoonz_docs/issues/4) for obtaining it.

At some point in the future I will add a link to the manual in OpenToonz website.

Any comments or suggestions are appreciated.
Thank you for your continuous contributions!

**Comment by morevnaproject** [comment]
> You can refer to (or even copy as-is) its contents (all rights of the documentation are transferred to Dwango for now).

This is freaking awesome!

**Comment by turtletooth** [comment]
This can be closed.  Thanks @shun-iwasawa for the new site.  It'll be great to have an official documentation site.

**Comment by morevnaproject** [comment]
> all rights of the documentation are transferred to Dwango for now

@shun-iwasawa Does that mean the Dwango will re-publish the manual under some CC license? Since the manual at ReadTheDocs is CC-BY-NC, that would help to avoid some legal questions in the future.

**Comment by shun-iwasawa** [comment]
@morevnaproject 
Thank you for the suggestion and I fully understood your concern. Please give me some time for clarifying it. Thanks!
