### ISSUE TITLE
Level Strip Functionality

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1399]
Hey Everyone-
I'm doing some work on the level strip and want some feedback on how functionality should work.  I'm trying to make drag and drop into the xsheet more reliably as well as making drag select work.  Here is the question: How do you think we should make it distinguish between selecting, drag selecting and drag and drop to xsheet.  (I'm not talking drag and drop to reorder).  I don't want to make the functionality too complicated but its challenging to figure out a good workflow to distinguish between:
Starting a new selection
Drag Selecting
Dragging a selection to the xsheet

Right now it's click to select unless that frame already selected, or the start of a group selection.
You can group select with shift or ctrl
You can drag and drop to xsheet by dragging, but drag and dropping a group selection only works by dragging the first drawing selected in that group.

Drag selecting is in the code, but it's almost never triggered because OT usually opts for a new selection.

I'd like to not use middle click since that is probably going to be used for a feature that I will show later.

So how do we distinguish between the different types of clicks and movements in a way that doesn't make the interface too challenging.

One way I know I can get working but may introduce unwanted complexity is to divide the frame in half and make clicking on one half trigger a selection and the other half to trigger drag and drop (sort of like xsheet cells do right now with the strip on the side)

I have seen many complaints about selecting being difficult, wanting drag select, or drag and drop being finicky with group selections, and I would like to make those more predictable.

@artisteacher @konero @rodneybaker @shun-iwasawa @blurymind @blackwarthog  @morevnaproject @manongjohn I'd appreciate any insight you might have.  Sorry for the bulk mention, but I want to get a bunch of eyes looking at this to come up with a solution that is easy to use, functional and consistent.

**Comment by turtletooth** [comment]
Something that just occurred to me was the possibility of clicking on the numbers to start a drag select?  Just throwing ideas out here.

**Comment by artisteacher** [comment]
Drag select will be great to have!

Instead of dividing the frame in half, what about adding a more narrow drag bar along the left side? It could overlap the frame or it could just be directly next to the frame. If the drag bar is going to overlap the frames at all, some sort of visual cue would be helpful. 

A left-side dragbar would add more consistency between the Level Strip and levels/cells in the Xsheet. The more consistent the drag/select behaviors are, the easier it will be for users.

Could the drag select behavior just be the same as in the Xsheet?

**Comment by turtletooth** [comment]
@artisteacher I thought about that, but wasn't sure if that would make it too busy on the left since that is also where the onion skin controls are, but it would make the most sense from a consistency point of view.

**Comment by konero** [comment]
Toonz Raster Level supports pan navigation in the Level Strip thumbnail box, like the Photoshop navigator window. If you place things into that area then using it might be difficult.

Select a frame, zoom in, then drag on the thumbnail.

**Comment by turtletooth** [comment]
@konero - That was going to be my surprise.  It currently only works for Ghibli rooms in the InkNPaint room.  I am enabling this in non-ghibli rooms (without messing up the way Ghibli has it) for both toonz raster and raster levels.  Right now if the navigator is enabled, drag and drop doesn't work, so for non-ghibli rooms, I'm moving the navigator control to middle click.

**Comment by RodneyBaker** [comment]
Oh oh... I just had an odd thought...

What if... similarly to the xsheet there was a toolbar at the top of the Level Strip?
That toolbar could contain several targets that when a Level Strip icon was triggered (by drag/drop onto the icon) the desired outcome would result.

For instance, currently exposing a frame or set of frames from the Level Strip requires having the xsheet open or performing a Right Click with selection of 'Expose in xsheet'.  An interactive toolbar at the top of the Level Strip might provide an icon to that same functionality where whatever is dragged onto the 'xsheet icon' would expose the selected frames in a new column in the xsheet.  

Similarly, there might be 'sort forward' and 'sort backward' in typical A-Z with arrow form where whatever frames are dragged onto the icon get sorted accordingly.

To specifically consider your targeted areas of interest:

**Starting a new selection** 
Approach:  Drag frame(s) onto a 'new selection' icon
The main variable here would be whether the user wishes the new frame to be in front of or behind the selected frame(s) and what to do if multiple frames are selected.  For instance, if a user selects every other frame and then drags them all to the 'new frame' icon a new frame might be created inbetween each of those selected frames.  

The number of options can get complicated quickly because of the number of variables but the general logic might be to always create a new frame inbetween any set of selected frames.  If only one frame is selected the default might be to create the new frame *after*the selected frame.  This outcome allows for continued use of the Insert key that always inserts new frames *in front* of the selected frame(s).  This would solve a minor irritation in OT where the user might tend to want a new frame to appear after the current frame and Insert places it before it.. requiring a Right Click and selection of Reverse to get the frames properly ordered.  (Drag and drop to organize is obviously the optimal sorting solution but that is not yet implemented).

Drag Selecting
I confess I don't have much insight here except perhaps in the context of my thoughts on a Level Strip toolbar that provides targets for that drag selecting to hit.  The outcome is then dictated by the processes tied to the icon.

Dragging a selection to the xsheet
In current functionality I note that drag selection to the xsheet where frames selected via use of the Control key doesn't seem to work.  Upon dragging the selection appears to be lost.  That seems to be the primary function lacking in Level to Xsheet drag and drop.

At any rate, a Level Strip toobar might be a bit of a stretch but that was the thought.
By having targets to hit there would be less concern for where and how the drag and drop was selected and allowing the selection to be isolated from the desired outcome.  This might also create something of a roadmap of sorts for future development relating to tablet uses and even repurposing of a (theoretical) Level Strip toolbar for use in the xsheet itself where various processes are made to flow via drag/drop onto a specific target  This also echoes the basic usage found in the Schematics but there a more permanent connection between elements is established.

**Comment by turtletooth** [comment]
I think I figured out a workflow that makes sense and is easy to use.  Thanks for the feedback everyone.

**Comment by morevnaproject** [comment]
Sorry for late feedback, but I am both hands supporting consistency with XSheet suggested by @artisteacher 

> A left-side dragbar would add more consistency between the Level Strip and levels/cells in the Xsheet. The more consistent the drag/select behaviors are, the easier it will be for users.
