### ISSUE TITLE
Translate Japanese word (Zanzo) to English

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1412]
My native language is not English, What mean **Iwa** and **Ino** in FX Browser?

![ino_iwa](https://user-images.githubusercontent.com/16509592/29459072-589929ea-8437-11e7-8435-897d8b2227ce.jpg)

**Comment by 2dvision** [comment]
Another word is Zanzo, What mean this? I think this word is japanese, because i can't find this in dictionary.

![zanzo](https://user-images.githubusercontent.com/16509592/29459167-ae6f6352-8437-11e7-9a17-c496a0ebf245.jpg)

**Comment by RodneyBaker** [comment]
I'm not sure about Zanzo (it appears to be a japanese term such as 'penumbra' BUT I do know what and Iwa means!  :)

Iwa is short for Shun Iwasawa!  Developer extraordinare of OpenToonz FX plugins.

Ino is therefore another Japanese developer which I should know but the name escapes me.

**Comment by 2dvision** [comment]
> Iwa is short for Shun Iwasawa! Developer extraordinare of OpenToonz FX plugins.
Ino is therefore another Japanese developer which I should know but the name escapes me.

Oh boy! :))

**Comment by RodneyBaker** [comment]
Gah!  I should have known this.

Ino is very likely Masafumi Inoue who is the force behind GTS (Ghibli Toonz Scanner? Studio?)

Now it's your turn to educate me because I don't know what GTS stands for.  ;)

**Comment by 2dvision** [comment]
I don't know what mean **GTS** too. But about **Zanzo**, If this is the Japanese word, need to be translated into English. @shun-iwasawa

**Comment by RodneyBaker** [comment]
Yes, it would be good to translate that so others (English readers that is) don't have to guess.
Do you want to rename this issue or close and start another?

**Comment by RodneyBaker** [comment]
I will assume a renaming of this issue and do a little digging because someday I hope to be able to 'fix' issues  like this so developers are freed to press into more urgent matters.

I see that the term 'zanzo' occurs and would need to be changed in the following locations:

https://github.com/opentoonz/opentoonz/search?utf8=%E2%9C%93&q=zanzo&type=

**Comment by jpturcotte** [comment]
Could _zanzo_ be 残像: afterimage, imprint? (source: http://jisho.org/search/zanzo)

**Comment by RodneyBaker** [comment]
> Could zanzo be 残像: afterimage, imprint? (source: http://jisho.org/search/zanzo)

It not only could be but is.  :)

**Comment by jpturcotte** [comment]
Sorry, I did not see you had edited your post. ;)

**Comment by 2dvision** [comment]
Thank you very much @RodneyBaker

**Comment by RodneyBaker** [comment]
I'm going to attempt to take this on so please assign to me.
Here would be my proposal:

There is only two places where the term 'zanzo' would need to be changed and that is in a config/text file. 
 Any user could do this on their own computer but that wouldn't make a change that sticks for subsequent installs.

The underlying code can still use the term 'zanzo' without issue and thusly can be changed at a later time. 
 The UI change would be what users see and therefore "Afterimage Power" and "AfterImage Length" will be seen instead of "Zanzo Power" and "Zanzo Length" in the settings of the FX dialog.

I'll have to clone the OpenToonz repository to do this right (and learn the process) so that will take a little time.

@2dvision  I  see you've changed the title of this issue while I've been typing.  Thanks!

**Comment by RodneyBaker** [comment]
Here's success on my end.  Now I just need to figure out how to properly use github.

While we are at it we might want to look at that top desciption 'Depend Move'.
That seems like it need to be updated as well.
![1412update](https://user-images.githubusercontent.com/2576432/29465358-a0b2e0e2-83fe-11e7-94f7-d634c6d009b7.png)

**Comment by jpturcotte** [comment]
How would that work in localized versions, though?

**Comment by RodneyBaker** [comment]
> How would that work in localized versions, though?

Excellent question and I had considered that.
This *should* be okay because as I don't think localization looks for and changes the text but rather just populates the string that the current.txt file is referencing for English speaking users but we'll need someone in the know (QT knowledgeable) to confirm.

**Comment by RodneyBaker** [comment]
I had mentiond the description "Depend Move" seen at the top and wondered what that references.  It appears a loose translation might simply be "Setup".  

The first option, "P1 > P2", appears to  consider the image moving from one fixed point to another while the "Motion" setting would appear to Blur a constantly moving object.

I'm sure that isn't entirely accurate but that's my theory concerning the two options which I will have to confirm via actual use of the Motion Blur Ino FX.

**Comment by gab3d** [comment]
...it sounds to me that perhaps "Trail" could describe that also, and it's
a more common word.

**Comment by turtletooth** [comment]
Closing this since there is a PR for this and another issue for the zanzo question.
