### ISSUE TITLE
(WIP) Timeline Enhancements

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#1422]
You all already know me and should understand that in the Timeline I invest a lot of energy and all the more so in the idea of functional reals. I ask you to read my plan for the development of the timeline, I take into account many of your requests, but I also add new functions. This timeline will be integrated into the concept of the timelines sbeb (After Effects, TVPaint, Flash) https://docs.google.com/document/d/1CyVbJ6dlhFC-IjEIcG52RoUt45PQ6dvDvEO7eL5GQcw/edit?usp=sharing 
Now the concept is implemented only by 60% in the future will be added and other functions. I very much ask you to respect my concept. Thank you in advance!

**Comment by Agnyy** [comment]
P.S. 
I apologize for the bad translation. I do not know English therefore I translate through Google translator.

**Comment by bobbybutterfly** [comment]
@Agnyy  Thanks for your hard work!
Functionality like in After effects would be a dream come true. Especially the zoom/increase decrease frame size would be wonderful for scenes longer than 2 or 3 seconds.
Also: The function curves should be accessabble from the timeline directly
Thank you:)

**Comment by RodneyBaker** [comment]
Looking very good!
Thank you for your work and dedication to adding and enhancing the Timeline.

**Comment by openanim** [comment]
Impressive work ! Will this be compatible in xsheet mode? Or specific to the timeline ?

**Comment by manongjohn** [comment]
@Agnyy You should post a link to the video you have of the timeline enhancements so people can kind of see it in action.

**Comment by Agnyy** [comment]
https://www.youtube.com/watch?v=ZNJgmsilyt4

**Comment by artisteacher** [comment]
I'm super excited about the addition of keyframing the contents of the vector levels!

I'm curious about the new process for adding levels as new layers vs inside an existing layer once the empty columns are removed. Right now, the selected cell determines whether a new level makes a new column/layer or if the new level is added to an existing column/layer.

**Comment by gab3d** [comment]
@Agnyy, wooow!!  can I be your friend?!  :D 
If you complete this project, the workflow in OT for digital animation would be revolutionized, I am so excited!

I'd just like to comment on some topics that could be added, as well, to improve it even more:

1. What makes AE's timeline a truly great place to work in, is its ability to only show what's needed for a certain job, and nothing more than that. In that sense, I think a set of shortcuts to show "Only Keyed Channels" (like the 'u' in AE), and others like Position (p), Rotation (r), Scale (s), Opacity (t), etc. are needed, for this new timeline workflow to truly take off.

2. Perhaps a "Solo" option for layers (and contents) would come in handy too.

3. I still think dots (instead of icons) would be easier on the eyes, for activated layer properties (visible, locked, etc.).

Keep up that excellent work!!

**Comment by Agnyy** [comment]
DONE !!!!!!!
Change # 1
Change # 6
Change # 9
fulfilled this @manongjohn!!!!
Thank you so much!

Canceled !!!
Change # 3
All the information here, together with the plan. 
https://docs.google.com/document/d/1CyVbJ6dlhFC-IjEIcG52RoUt45PQ6dvDvEO7eL5GQcw/edit?usp=sharing

**Comment by Agnyy** [comment]
Add change #14 (Add “Function curves”) 
https://docs.google.com/document/d/1CyVbJ6dlhFC-IjEIcG52RoUt45PQ6dvDvEO7eL5GQcw/edit

**Comment by DarrenTea** [comment]
Q. When you drag a frame up or down on the timeline, it can creates lots of blank columns. I don't think it should ever create blank columns.  You should have 2 menu items in the right click menu of a column:
- Create new column above this
- Create a new column below this
and then you can drag frames onto them.

**Comment by artisteacher** [comment]
It is really easy to accidentally create empty columns/layers. I don't necessarily want to lose the capability but do wish that there was more control.

**Comment by DarrenTea** [comment]
If that was a requirement (I don't think it is because it's too easy to accidentally create them) then perhaps limit it to creating one and only if you drop the drawing. So if you move too far and create a column, you should be able to move it back and drop it and not have a new empty column.

**Comment by gab3d** [comment]
@DarrenTea 
I agree with that.

**Comment by adamearle** [comment]
Perhaps hold alt ctrl & shift drag mouse cursor can add new columns? Or kind of combInation like crtl & drag mouse or shift & drag? Its all up to you bud

**Comment by adamearle** [comment]
As for the curve Editor i find a 3D curve editor to be way more superior than after effects.

Have you looked at implementing Blenders curve editor? Or somerhing like that?

Love your work mate your helping change the world.

**Comment by Agnyy** [comment]
You are waiting for Change # 2 ?
https://docs.google.com/document/d/1CyVbJ6dlhFC-IjEIcG52RoUt45PQ6dvDvEO7eL5GQcw/edit?usp=sharing

![image](https://user-images.githubusercontent.com/25137502/42200497-32ee8b6c-7e9c-11e8-9da9-ebb3c750d0cb.png)



@manongjohn If we now proceed to this change, this strongly hinders the synronization with # 1878?

**Comment by Agnyy** [comment]
I needed to know your opinion. No work is currently being done in this direction. If this creates difficulties, then of course we will not do this. Thanks for your reply.

**Comment by openanim** [comment]
In my opinion, this should be an important request for many people, because a lot of animation software offers a thumbnail display now. It is a process of logical improvement. If it does not destroy the current performance, even if it's not set up now, I think it's a good direction.

**Comment by artisteacher** [comment]
I wonder how helpful thumbnails would actually be at that very small size - especially if you have really small drawings? I know having a visual cue about the level you are working on is great but I just switch into the Xsheet view for a moment when I need that.

**Comment by RodneyBaker** [comment]
I'm a fan of the ideas of having the thumbnail view capability in the xsheet even though the images might be so small as to barely see the content.  Often it isn't so much the image that is important and the ability to immediately recognize that something significant has changed from one frame or sequence to another.  This allows the user to hone in further on areas of interest.

**Comment by manongjohn** [comment]
Now that we have a zooming timeline, I was actually thinking of revisiting putting a thumbnail back into the Timeline header area (between buttons and column#/name).  I didn't add it before because it pushed out the timeline column headers out, eating up space for the timeline on smaller screens.  With the zooming timeline, you won't lose as much of the frames as before.  The only other problem I had at the time was the reduction of the images into a 36x20 box. It resulted in such a very poorly rendered image that it made it not worth while displaying. Example, I had a simple triangle shrink down to a single line.

**Comment by 711GM** [comment]
@manongjohn Do you want to do this? 
![image](https://user-images.githubusercontent.com/40460266/42224477-d16d747e-7ee2-11e8-9b32-9355a71a52aa.png)

**Comment by manongjohn** [comment]
@711GM No.  That eats up too much vertical space on the timeline and would render the timeline useless on smaller screens.  I like the current height of the timeline columns.  On my old smaller tablet I could work with 3-4 columns and lots of frames comfortably.

**Comment by beeheemooth** [comment]
The absence of such thumbnails is one of two reasons why I do not use a timeline, but prefer Xsheet.

**Comment by 711GM** [comment]
@manongjohn 
I do not understand English well. Could you show how it looked?

**Comment by openanim** [comment]
@manongjohn 
and in the case of cells that turns into thumbnails is it the problems are different?

**Comment by manongjohn** [comment]
@beeheemooth I do miss having a thumbnail as a reference as well, but find I work better on the timeline than on the xsheet so it's a small thing for me to give up.

@openanim Aside from reducing the image to a small thumbnail and dealing with potential reduction issues, having thumbnails in cells is more of a potential performance issue with the current code.   Every time the timeline moves or is modified in some way, it needs to calculate and redraw every piece of the visible cell. I fear this will bog down the system during playback.  If anything, it needs to be a huge consideration when adding this feature in.  I'm not familiar with how/when TVPaint displays these thumbnail cells.  Is it only on the active column, ones you specify or all visible columns?  And what do you do when you zoom out?

To support the thumbnail cells it might be that the height needs to change.  If all columns will change height, I will definitely be against it because you are going to eat up vertical space which is important on smaller screens.  If it's 1 or only certain columns you pick, the current code will not easily support that.  This will probably require somewhat of a rewrite of how column heights are tracked and managed as well as how the timeline flip is being handled.  Now add this with the curve animation stuff and make sure nothing is broken....let's just say I definitely won't be doing this. :)

I should hope that if this feature does get implemented that it is a preference setting so I can turn it off and negate some of the issues I've mentioned. I'd rather have more columns visible on a smaller screen than a thumbnail.  

Another thing to note is the timeline code was built on top of xsheet code so the code base is the same. Just has a lot of if conditions everywhere. Care needs to be taken to not impact xsheet functionality/performance, which this might do if not done properly.

Whomever decides to work on this will need a lot more detail on how this feature will need to work within OT than is currently described.

**Comment by bobbybutterfly** [comment]
for cut out animation style i could imagine a thumbnail image of an objects "bounding box" area.
For example forearm, hand, fingers are parented to an arm. So the arm column should generate an image of the whole arm, zoomed in to its borders

**Comment by openanim** [comment]
On tvpaint, the height does not change which it's probably easier I guess. It works with a zoom tool, to zoom in and out. when the zoom is maximized each cell is represented, if you actually have all the visible columns they will be as well. There is a heading thumbnail that also updates that represents all the cells on which the cursor is currently located. During the zoom out, the clips compress like what you did.

Tvpaint offers the same functions between xsheet and timeline  like us and so also offers thumbnails in xsheet mode which is rare, you have an icon on the timeline to activate or deactivate according to your taste just as you can show or hide the thumbnails. I know that there have been changes in their latest version in some points but it remains minor.

In CSP you can zoom in and zoom out too but it will not affect the thumbnails themselves but on the timeline, there is also a menu to choose a thumbnail size.

For what will follow the height varies between cells mode and thumbnails mode, sometimes it has to do in the quadruple of a normal cell.

In flash, there is a timeline sub menu that looks like what is also found in OT as the viewer sub menu. This menu allows you to choose between different zoom percentage of the timeline and in addition it offers a preview mode a "new timeline" appear with thumbnails instead of cells. This new timeline can be zoomed in, and zoom out like normal timeline.

In harmony, you have a thumbnail icon that would be next to the padlock on our timeline and it allows you to switch the timeline to this preview mode for each "column" you want. they also have a header like on Tvpaint which corresponds more or less to what we have with our Xsheet thumbnail.

In krita, for the moment, it is content with a rollover view with the pen cursor to display the thumbnails.

I imagine that the fact that a lot of software offers different views in the form of icons to activate or submenu, is a way perhaps to answer this problem that you describe ?

For all of them it is not a parameter put in the preferences but just added in the menu of the timeline with the choice between small medium large and thumbnail (it is not always presented as well, but I synthesized). But it is more or less a criterion of preference but which adapts to our needs. If you still want to look at it, I do not mind testing more and bring more details.

But I also understand that it is difficult to combine all these features in harmony whitout bugs. Now, this perspective i must admit that it is tasty :)

**Comment by manongjohn** [comment]
@openanim Thanks for your enlightening comparisons. If I had a choice, I'd probably like Krita's version. Keeps the timeline small and uncluttered while having access to a decent sized thumbnail when you want it.

**Comment by RodneyBaker** [comment]
@manongjohn  Should this be closed as a feature request on hiatus and/or no longer being developed?

**Comment by RodneyBaker** [comment]
I've been reviewing issues/reports and I'm not sure of the status of this WIP.
The title is (WIP) Timeline Enhancements but are additional timeline enhancements itemized here still being pursued?

Thanks.

**Comment by RodneyBaker** [comment]
Closing as abandoned.
Perhaps we can pick up any remaining elements of Timeline improvements in the 2020 development cycle.
