### ISSUE TITLE
Toonz 3D Export

### ISSUE THREAD

**Issue by MaxMixBug** [opentoonz/opentoonz#1432]
![image](https://user-images.githubusercontent.com/29537858/29706771-a87d5cb6-898b-11e7-8e39-552228b7ce9d.png)

http://www.toonz.com/htm/products/46productline/prod3dp.htm 
Has anyone worked with this?

**Comment by MaxMixBug** [comment]
http://www.toonz.com/htm/products/46productline/prod3dpfeat.htm
![image](https://user-images.githubusercontent.com/29537858/29706976-4e7eb588-898c-11e7-97e2-c39ff9dd92e2.png)

**Comment by RodneyBaker** [comment]
This is more of a post for the forum but...

Very interesting.

Two questions related to this product and it's pipeline:

Is it still available?   (Not that I would purchase because I don't use Softimage)
Since this is linked to Toonz 4.6 and is on a hidden page of a site no longer updated it would seem that it might be but only through contact with Digital Video.

The software generates an xsheet file (.xsh) but (in OpenToonz) I don't see any direct way to import or save an xsheet file.  That certainly would be useful and required for use with this product.

**Comment by RodneyBaker** [comment]
In reading the FAQ the plugin does generate only basic tracking information.  From that FAQ I read:

> How complex is it to place 2D levels in the right position once the xsheet file is exported?
> The exported xsheet file is a completely empty xsheet, except for some pegbars information about the N/S, E/W position and Field value. After you load levels in the scene, all you have to do is to assign the right pegbar to the right level, and the level will be "placed" automatically in the 3D environment. In addition, for easy reference, the pegbar in Xsheet will be labelled with the name of the object selected in the 3D environment.

Source:  http://www.toonz.com/htm/products/46productline/prod3dpfaq.htm

**Comment by jpturcotte** [comment]
SoftImage has been discontinued a while ago, though. However, the idea of it is very interesting. That could gain traction as a feature request if it could work with Blender. By the way, is @ideasman42 still around?

**Comment by turtletooth** [comment]
I'm going to close this as more of a feature requests.  Please post feature requests in the Google Group.

**Comment by blurymind** [comment]
Just an idea.. but why not write a similar plugin that works with blender?
Autodesk will never be able to buy and discontinue blender :b
