### ISSUE TITLE
Jumper Frame

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1455]
I do not know it's a bug or not. But for example, Copy and paste first frame in empty cell between two frame, The last frame will change position (and create an empty cell after pasted frame).

To restore the last frame to first position, I should select empty cell and cut (Ctrl+x) it.

![jumper-frame](https://user-images.githubusercontent.com/16509592/29997203-9fce411e-9022-11e7-8910-24e2495a5aa0.gif)

![jumper-frame-1](https://user-images.githubusercontent.com/16509592/30000685-22e0f80a-908a-11e7-9a4b-761648f48246.gif)

**Comment by RodneyBaker** [comment]
Rather than 'Paste' (Control V) you'll want to use 'Paste Into'.
Paste Into doesn't move the cells.
It also doesn't have a default Shortcut key assigned so we have to do that ourselves... hmmm... perhaps Shift + Control + V? 

I suppose we could also give 'Paste Into' the Control + V shortcut and leave regular paste unassigned BUT I will guess that might cause problems elsewhere where other pasting is used.

**Comment by RodneyBaker** [comment]
Nope.  I like Shift + V better as it is a quick two finger operation just like Control V... and it doesn't appear to be already assigned.  :)

Recommend closing.

**Comment by 2dvision** [comment]
"Paste Into" have a problem. This will replace existing frames with the copied frames.

![jumper-frame-2](https://user-images.githubusercontent.com/16509592/30000650-c254b02c-9088-11e7-9400-2e020c1b138a.gif)

**Comment by 2dvision** [comment]
I am so sorry. Copy and paste is different in OT. For paste frames without empty cell, you should select a frame and the frames will be pasted before.

![jumper-frame-3](https://user-images.githubusercontent.com/16509592/30000804-a99efa6a-908d-11e7-8673-5a6d2b137c58.gif)
