### ISSUE TITLE
Bug: Preview Visibility Toggle don't work for audio level

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1462]
Windows 7, Opentoonz Nightlies 2017-08-25 06:42:32 UTC

1. Import a audio to your project.
2. Change "Camera Stand Visibility Toggle" to off.
3. Export your project (MP4) and open exported video.
4. Audio will not be exported.

Export audio is not possible, When "Camera Stand Visibility Toggle" is off. Set the rendering of the levels is "Preview Visibility Toggle" task, Is it true?

**Comment by turtletooth** [comment]
@manongjohn I think you are most familiar with this right now.  Would you mind taking a look?

**Comment by manongjohn** [comment]
I can, but I need to know if that is how it should be.

@shun-iwasawa can you explain how the Preview Visibility and Camera Visibility buttons are supposed affect a Sound level?

In the official release, the Preview Visibility button has no impact to the Sound level. Camera Stand Visibility prevents playback during previews and when moving around in xsheet. It apparently also prevents being rendered out in the final animation.

What I would expect for behavior is, the Preview Visibility prevents rendering when off since turning off preview turns the column to a Reference column which doesn't get rendered. The Camera Stand Visibility should only prevent playback in preview mode, but still render. You are just effectively temporarily hiding a level while animating as you would hide any other columns.

**Comment by shun-iwasawa** [comment]
@2dvision Thank you for reporting this issue and @manongjohn thank you for the confirmation.
The current behavior of sound toggles is almost unchanged from Toonz Harlequin. And I agree with @manongjohn , it seems to be wrong. 
According to the Toonz Harlequin's manual (p.203) : 

> - A camera stand toggle allowing you to include or not the column content when scrubbing the audio with the current frame cursor; when activated an animation table icon is visible in the toggle.
> 
> - A render toggle allowing you to include or not the audio column content in the rendering; when activated an eye icon is visible in the toggle.

This is what Digital Video (and we) are expecting for this feature. 
However, Harlequin 7.1 seems to have the same problem as OT that the render toggle does not work and only the camera stand toggle is taken into account both for scrubbing and rendering.
