### ISSUE TITLE
Merge Vector levels broken

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#1477]
In official 1.1.3 (Windows build), it appears merging vector levels with Xsheet->Merge Levels is no longer working the way it used to.

When merging 2 or more vector columns, the frames do not merge.  They use to do that in older versions. The only thing that does merge are the palettes (which it does properly here, but not for Toonz Rasters!?!).

I would expect the behavior of Vector column merging to be the same as Toonz Raster column merging, where everything is merged (frames, palettes, keys, etc) into 1 column and the old ones are removed.

**Comment by artisteacher** [comment]
With OS X, when merging 2 vector columns, they do merge to the left but the original right column remains which seems like a strange behavior.

**Comment by manongjohn** [comment]
The old column not being removed I knew about already. 

Ok, I just checked again, it is sort of working, but probably not what I was expecting, which is why I was being thrown off.

In Toonz Raster merging, everything is merged as I would expect. Missing frames are created in the final merge while existing ones on the same frame are merged. Then the old columns are deleted.

In Toonz Vector and I think basic Raster levels, only frames that have cells in both are merged into the left most column.  So extra columns on the right are not merged into the left unless I expose blank ones on the left.  Seems rather inconsistent, though I guess that's why there is a different merge command for Toonz Raster and Toonz Vector.  

To avoid confusion, you'd think they would behave the same way and only have 1 command that handles either type.  Maybe Toonz Vector/basic Raster merge should be called something else since it behaves differently.  I can kind of see the need for it. Perhaps a good candidate for a feature request.

Since it is working (right or wrong), I guess I'll close this for now.

**Comment by beeheemooth** [comment]
Sorry to open the topic again. Animation and graphics from the second level, which remains after the Merge Levels, can sometimes be reused if it is moved to the desired place and edited. A complete fusion of vector levels (like Toonz Raster) would not allow us to use such a time-saving approach.
![ezgif-2-d024f6d97a](https://user-images.githubusercontent.com/25724133/30481525-dcbec030-9a27-11e7-8af9-782837538c14.gif)

**Comment by manongjohn** [comment]
I figured there was a reason for it. Wouldn't get rid of it. Rename it, maybe.

Having a destructive merge (Toonz Raster) and a non-destructive merge (Toonz Vector/Raster) would be more useful and less confusing if it wasn't restricted to specific column types. There may be times a user doesn't want to do a destructive merge on  TNZ Raster or maybe they want to do that on TNZ Vector/Raster.

Might explore changing it in the future.

**Comment by beeheemooth** [comment]
@manongjohn There is another way which I personally most often use: the merging of vector levels with the cleaning of the second level. After merging the levels, I delete all the drawings from the second level, and I use it to draw another part. Since the cleaned level already has the necessary keyframe layout in Xsheet, it helps to save time on creating a new level and arranging keys.
Summarizing, we can define three types of merge levels, each of which is useful in its own way:
1. Destructive (as you called it) - when the merge remains one level, the rest is deleted.
2. Collecting  - when the levels merge into the first, and the remaining levels (which participated in the merger) are cleared.
3. Cloning - when the levels merge into the first, and the remaining levels (which participated in the merger) are not cleared.

P.S. I hope Google Translate has translated that correctly. ^ _ ^

P.P.S. (This is not a Feature Request, it's just a thought)
