### ISSUE TITLE
File>Preferences>interface does NOT have a viewer color se of options

### ISSUE THREAD

**Issue by Orphanlast** [opentoonz/opentoonz#1478]
So I don't personally have this problem, but this is something like the third time I've heard someone complain about this within several weeks (all different people).

So you have two interface options for the "checkerboards", you have a slider for "viewer background", and "level strip background" (not direct quotes, but that's what they're for.

But nothing for the viewer. 

People are complaining that the consistant white is leading to eye strain.

Currently I'm telling them to make a toonz raster level on the bottom of the stacking order and to color it whatever they'd like and epose the frame for the full extent of the animation... seems like a weird workaround

**Comment by shun-iwasawa** [comment]
Please let me clarify the issue. 

- If you are selecting the scene frames (by touching xsheet) and you are in the camera-stand view mode, Viewer shows the "Camera BG Color" inside the camera box. Which is white by default and can be adjusted in the Scene Settings. It's not in the preferences since the Camera BG may affect the rendering result if it is non-transparent. Note that you can hide this in the Combo Viewer via `right click menu > GUI Show/Hide > Camera BG Color`

![bgcolors](https://user-images.githubusercontent.com/17974955/30467098-588e88ea-9a1d-11e7-80ab-240b9d61e53e.png)

- Only the case if you are selecting the level frame (by touching the level strip) and the current level is Toonz Raster, Viewer shows the solid white background and cannot be changed its color for now. Actually I added this feature in the Ghibli Edition reflecting the demands by ink&painters in the studio. And I'm thinking that it would better to make this color adjustable.

**Comment by Orphanlast** [comment]
Thank you
