### ISSUE TITLE
Enable to Specify Level Paths as the Relative Path from the Scene's Parent Folder

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1488]
This feature is what I mean to implement to OpenToonz, based on a request by Japanese animation studio.
For now, level paths are specified in the scene by one of the following ways;
 
1. Absolute path.

1. Relative path from the project folder ( using the project folder aliases such as `+drawings` ).

Using the project folder is powerful for managing the working data through production. However, for now both cases lacks **portability** of data. Once you move levels to another folder (for organizing, backup or another purposes) your scene cannot find the level resources unless you specify the paths in level settings.

In that context, I'm thinking of implementing a new variable (say, `$scenefolder` ) which can be used in the beginning of the file path. On loading the level, `$scenefolder` will be replaced by the folder path where the current scene file exists. By putting the scene and levels in the same relative position and using this variable, links to the levels will be maintained even if you move the folder anywhere or rename the folder.

(Please note that OpenToonz already has the `$scenepath` variable but it works quite different. Please refer to [the manual](http://opentoonz.readthedocs.io/en/latest/managing_projects.html#using-the-scenepath-variable-in-folder-definition) for details.)

![scenefolder_concepts](https://user-images.githubusercontent.com/17974955/30735858-75d801bc-9fbb-11e7-9089-602bbe0b3f1c.png)

Not only gaining data portability, implementing this feature will cause another beneficent influences as follows:

- Introducing this feature will allow us to make `Collect Files` command for collecting all resource file of the scene into one folder and make it portable, which is available in AfterEffects.

-  In June, [Celsys announced](https://www.celsys.co.jp/topic/20170626) that they started to study for formulating the universal x-sheet file format which is meant to be handled by multiple animation tools. In their initial proposal, all levels/resources used in the scene MUST be contained in the same folder as the scene file. IMO limiting the resources to be placed in one place would be inconvenient considering that there will be resources shared by multiple scenes. However, introducing `$scenefolder` will become capable to follow their concept. 
<img src=https://www.celsys.co.jp/files/user/news_release_20170626_02-600x0.jpg width=500>

**Comment by gab3d** [comment]
...sounds useful to me.

as always, it'd be a bonus to have this option exposed somehow in the UI,
so non technical users know they could make such a choice, when creating or
saving a project.


El sept. 22, 2017 5:54 AM, "shun-iwasawa" <notifications@github.com>
escribió:

This issue is what I mean to implement to OpenToonz, based on a request by
Japanese animation studio.
For now, level paths are specified in the scene by one of the following
ways;

   1.

   Absolute path.
   2.

   Relative path from the project folder ( using the project folder aliases
   such as +drawings ).

Using the project folder is powerful for managing the working data through
production. However, for now both cases lacks *portability* of data. Once
you move levels to another folder (for organizing, backup or another
purposes) your scene cannot find the level resources unless you specify the
paths in level settings.

In that context, I'm thinking of implementing a new variable (say,
$scenefolder ) which can be used in the beginning of the file path. On
loading the level, $scenefolder will be replaced by the folder path where
the current scene file exists. By putting the scene and levels in the same
relative position and using this variable, links to the levels will be
maintained even if you move the folder anywhere or rename the folder.

(Please note that OpenToonz already has the $scenepath variable but it
works quite different. Please refer to the manual
<http://opentoonz.readthedocs.io/en/latest/managing_projects.html#using-the-scenepath-variable-in-folder-definition>
for details.)

[image: scenefolder_concepts]
<https://user-images.githubusercontent.com/17974955/30735858-75d801bc-9fbb-11e7-9089-602bbe0b3f1c.png>

Not only gaining data portability, implementing this feature will cause
another beneficent influences as follows:

   -

   Introducing this feature will allow us to make Collect Files command for
   collecting all resource file of the scene into one folder and make it
   portable, which is available in AfterEffects.
   -

   In June, Celsys announced <https://www.celsys.co.jp/topic/20170626> that
   they started to study for formulating the universal x-sheet file format
   which is meant to be handled by multiple animation tools. In their initial
   proposal, all levels/resources used in the scene MUST be contained in the
   same folder as the scene file. IMO limiting the resources to be placed in
   one place would be inconvenient considering that there will be resources
   shared by multiple scenes. However, introducing $scenefolder will become
   capable to follow their concept.

<https://camo.githubusercontent.com/92ff154e449b71674d112406d4e06a41d8843197/68747470733a2f2f7777772e63656c7379732e636f2e6a702f66696c65732f757365722f6e6577735f72656c656173655f32303137303632365f30322d36303078302e6a7067>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opentoonz/opentoonz/issues/1488>, or mute the thread

**Comment by turtletooth** [comment]
I think this is completed in #1513.  We can reopen if more needs to be done.
