### ISSUE TITLE
Black icons

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1504]
![2017-10-04_133214](https://user-images.githubusercontent.com/25724133/31171584-e5593848-a908-11e7-987b-2bfdb245a3a7.png)
This is in 2017-10-04 07:31:45 UTC
 In an earlier version (2017-10-04 03:55:59 UTC), the icons are displayed normally.

**Comment by manongjohn** [comment]
Looks like you are missing the updates to the Opentoonz 1.1 stuff/config/qss folder that have the new and updated settings. It should be in the nightly.

**Comment by shun-iwasawa** [comment]
For Windows installer, activating `Overwrite all setting files in the Stuff folder except user's personal settings` check box will automatically overwrite the setting files, including contents in the qss folder.

**Comment by beeheemooth** [comment]
Many thanks!  It work!

**Comment by manongjohn** [comment]
@shun-iwasawa Can we default that to being automatically checked?  Depending on the build they have loaded, any upgrade to the latest without that checked could result in missing stuff.

To avoid black icons/backgrounds, I will go back and make sure the old internal defaults are used if something is missing in the stylesheets since some people may still have the original themes.

**Comment by shun-iwasawa** [comment]
@manongjohn 

> Can we default that to being automatically checked? Depending on the build they have loaded, any upgrade to the latest without that checked could result in missing stuff.

I've made this option OFF by default was because some of the settings in the stuff folder may be customized by user. In such case, they should not be overwritten by the installer. 
( In particular, `config\cleanupreslist.txt`, `config\reslist.txt, \config\safearea.ini`, `\profiles\project_folders.txt`, and `\studiopalette\cleanup_default.tpl` are tend to be modified from the original. )

However, it is true that almost all users use the stuff settings as-is. So I agree that making the checkbox to ON by default. Thank you for your suggestion.

Also, thank you for posting the PR #1507 -  but I think making sure to update the setting files on installation (as you suggested here) would be more fundamental solution.

**Comment by shun-iwasawa** [comment]
Changed the checkbox to be ON by default with [this commit](https://github.com/opentoonz/opentoonz_installer_windows/commit/6c10a60071f0d63232065a6e9069e148855b1ee2) .
