### ISSUE TITLE
Seek Help Opening The Nightly Build on Mac

### ISSUE THREAD

**Issue by falls2lawrence** [opentoonz/opentoonz#1508]
I'm sure this has more to do with something on my computer since the opentoonz version worked and then overnight stopped working, but I was hoping someone can help shed some light.
I'm on a MacBook pro and with the official release, audio causes crashes...... a lot. Almost two weeks ago the nightly build had a fix for this audio problem and I was ecstatic. Then yesterday, attempting to open the  opentoonz nightly build that I had been using for at least a week caused a crash immediately.  All the nightly builds now do the same, immediately crash. The official release still opens but it's sooooo hard to go back to dealing with the crashes relate to audio now that I've seen how great it is without that problem as well as I've become accustomed to great new features like Snapping and Vector Guided Drawing. 

Any info that helps me get the nightly builds open again would make my week.

**Comment by artisteacher** [comment]
Do you happen to have multiple graphics cards? If so & you have automatic graphics switching enabled (under Preferences —> Energy Saver), that is likely causing a crash #1439.

Otherwise, if you closed out of OT while in Fullscreen or Fullscreen mode, that would also cause a crash on opening #1396. In that case you can revert back to the 1.1.3 (or any build before August 14th) and exit Fullscreen before closing (without crashing). Then you should be able to open successfully after updating. Just don’t go Fullscreen afterwards until there is a fix. While not quite the same, you can hide the dock and hold alt while pressing the green Fullscreen button, which expands the window almost to Fullscreen with no crashing.

I usually save the crash report in a .txt document & attach the file.

**Comment by falls2lawrence** [comment]
THANK YOU THANK YOU THANK YOU. It was in fact the automatic graphics switch. You are always on top of this stuff. thank you. thank you.
