### ISSUE TITLE
Bug with video and MyPaint styles (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1510]
![ezgif-2-1d9fdacf09](https://user-images.githubusercontent.com/25724133/31317760-47af5c22-ac4f-11e7-9276-a6521265fa25.gif)
1. Download the video file (mov)
2. Create a raster level and MyPaint style
3. Draw something in the raster level using MyPaint brushes.
4. Go to the level with the downloaded video. There is also a created MyPaint style.
5. Try to delete it, or draw something here and save the scene.
The program hangs. After you have removed the task in Task Manager, a duplicate appears in the folder with the original video file.

**Comment by artisteacher** [comment]
I wasn’t able to duplicate in OS X, but I can’t load .mov files in OT - only mp4 video. It did take a long time to save but did save successfully. In OT working with video files often slows down the program drastically. I wish there was a way to import only every nth frame of video. Or it would help if we could use the “Each 2”, “Each 3”, “Each 4” commands on video levels in the Level Strip.

**Comment by RodneyBaker** [comment]
Trying to re-validate and investigate this issue.
The referenced video file (MOV) no longer appears to have a link so that part of the Repeatable Steps cannot be followed.

A question:
Does the issue only occur when using a MOV file?
If that is the case a workaround for known issue can at least be documented with recommendation to use file format other than MOV.

**Comment by RodneyBaker** [comment]
Closing pending update of status.
@beeheemooth  Can you provide any additional information and resources such as a replacement MOV for the broken link?
