### ISSUE TITLE
[Feature Request] Incremental Save

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#1547]
I think it would be pretty cool for OT to have an incremental save feature, much alike Blender, where every time you hit "Save", it could rename the previous saved file to "FileName.001.tnz" while it would save a new file to the original name "FileName.tnz". This would ensure that even if one accidentally (or due to crash or power outage, etc.) has their file corrupted or unworkable for whatever reason, the second file could be accessed so that a lot of time is saved and work can be recovered. 

The amount of increments could also be set in the settings / preferences menu. 

Some context: I actually experienced an incorrectly-saved corrupted file issue, and figured that this issue could be avoided an automated save / backup option. That thread can be found here: https://github.com/opentoonz/opentoonz/issues/1546

**Comment by Orphanlast** [comment]
Auto saves would kill your computer

**Comment by tushantin** [comment]
I don't think they would, but I wasn't talking about auto "saves" necessarily. I meant an automatic system that assigns saves to incremental "numbers", so that you always have a back-up in case your recent file was corrupted.

**Comment by Orphanlast** [comment]
It might break compatability with Toonz

**Comment by shun-iwasawa** [comment]
@Orphanlast 

> It might break compatability with Toonz

You mean that having period in the middle of file name will be misunderstood by Toonz as sequential image level and won't be handled properly, right? If so, I think we can avoid it by slightly adjust the way of naming.

**Comment by Orphanlast** [comment]
I'm being negative. Sorry. It sounds cool, what you're saying. But it needs to be intelligible. I just think... "save file"122937"  from "000001". No one's gonna use that. 

The interface needs to make sense.

**Comment by gab3d** [comment]
@Orphanlast
Incremental saving is a standard industry practice, do a little research and you will find out that's the case.
It simply allows to automatically generate new version files for projects, eliminating the possibility of ovewriting a good file with a bad one (for whichever reason: human error, power failure, program crash, etc.). 
It also allows to leave a history track of the changes made during the creative process.
It's no unusual when you present a daily to a client or supervisor to watermark the rendered video with the file name version from where that daily originated, so you know for sure that any feedback you receive later on would be related to that precise version of your scene.

the only penalty is the extra disk space used for storing the old versions, but luckily hard drives are cheap, and with a little management you could delete or archive very old versions elsewhere, if needed.

**Comment by Orphanlast** [comment]
Oh, it sounds cool. Just sayin' a good interface for a layman, that'd be nice. 

I'm just talking. Trying to understand. Not trying to be overly negative. Just posing questions from the momment I think of them. In the context of that momment. 

I agree, cool request.

**Comment by tushantin** [comment]
Hmm, while I disagree with Orphanlast, he does have a point. One could actually try to simplify incremental saving for the layman by, perhaps, having a separate folder called "backup" where increments are saved, which can be accessed / recovered via OpenToonz directly? Or perhaps something like how Krita does it with its Autosave feature? As it is, OpenToonz Startup box shows you the number of scenes to open it either way, and the number of increments may clutter the "Open Scene" section. 

I dunno, that would need some discussion on the design aspect of things. 

Personally, though, I think that may take too much work, and time too. So for now I'd be pretty satisfied with a simple, basic feature that allows incremental saving without an interface (just a check-box and number-box in the preference menu should do the trick).

**Comment by RodneyBaker** [comment]
I agree that this is a very deep area of discussion.

I'll note the desire for incremental saves and backing up of files is not necessarily the same thing.
Many people who incrementally save files do this more as a method of organization than for backup although the increment can certainly help with retrieving a specific version of a file especially if they are looking for the last file saved.

A 'test case' to determine whether a user is backing up a file might be to determine if the location of the backup is other than that of an original file.  In other words, a backup/copy of a file that is stored on the same harddrive as the original suggests an increased risk of losing both the original and the backup/copy should the hardrive fail.  Therefore a copy (or incremented file) stored on the same medium as the original might be seen more as a desire for organization than for security of the data contained in the file.  

Out of habit I I routinely use increments for file naming but must acknowledge my interest is almost entirely placed on the most recently saved file (the highest increment).  As an example:  when I download the OpenToonz installers I usually allow Windows to increment it, which the Chrome browser will automatically do when it recognizes that a file with the same name is already present in the directory.  When installing OpenToonz then I generally look for the highest incremented file in the directory and launch that.  Similarly, if I were to save a Scene incrementally I would know that the Scene with the latest increment designation should contain the latest and greatest updates to the Project.  I do something 'increment' files by annotating a date and time after the main file name so that the date triggers an associated memory such as what features were being released at that specific date/time.

Aside:  In my experience the best method to backup files is to share the files with as many people as reasonably possible.  This isn't always practical and it tends to run counter to our desire for exclusivity but I've seen more than a few files that were thought to be lost forever returned after someone remembered they had been given copies of those files to someone else.  If a file is shared with hundreds or thousands of people it will very likely survive.  Then we might reasonably expect the file to be 'safe' but the difficulty might then become that of finding it.

All this to suggest that incrementing files is first and foremost an organizational methodology.  It may or may not relate to backing up copies of files.

Following that logic I find myself wondering what organizational approaches might be best suited for organizing files rather than safegarding them.  The current trend in that area would seem to be Metadata.

**Comment by gab3d** [comment]
Yes, to be perfectly clear: Incremental Save has nothing to do with backups. And they usually coexist well.

Backups prevent accidental file loss, due to file corruption.

Saving files in incremental versions is, on the other hand, a consious workflow, established as a way to improve control over the evolution of the process and the comunication within a team.

There are basically 2 forms of incremental save:

1. where the current file (the most recent) one) has no version number, and the rest of the files lay inside a subfolder (with that same name) with an ever increasing number appended to the base file name.

2. just the same as 1, but with the current file also having a version number appended to the base file name.

Personally I find the second one more consistent as you usually make dailies based on the current file version at the moment, so being able to clearly see what version it is helps comunication. a lot.

There are also other variants that save all the versions inside the same folder as the current file, but that leads to having hundreds of files in the main scenes folder, and that is not good.

With respect to the Startup window and the Recent Scenes list, I would only include there the current version of the file (and not previous ones).

Another important consideration to me is that Incremental Save command should coexist with normal Save command. That is, it's best to leave to the user the decision of generating a new version or saving over the current file every time he/she saves the file. In that sense I'd go for a separate command and not putting Incremental Save as an option of the normal Save command.
That way there could also be separate keyboard shortcuts for both functions.

**Comment by Orphanlast** [comment]
So how are you thinking of doing this without it making a bunch of seperate Projects? Because we're talking about having multiple save versions of the same levels.

I'm just asking. Most of what I do here is interviewing for Opentoonz News videos and starting and fundind bounties.

If I'm here, it's because I'm interested.

**Comment by gab3d** [comment]
I think "Increment and Save" should apply independently to Scene and Level files (i.e. be 2 separate commands):

- "Increment and Save Scene" - that'd cover all changes done at scene level (transforms, hooks, skeletons, cameras, stage/fx nodes, etc.)
- "Increment and Save Levels (or All?)" - that'd cover all changes done directly to level contents, such as paint, pallettes, etc. (or changes donde to both levels and the scene)

...there should also be a prior check for changes, with respect to the previous saved versions (to prevent saving new identical versions with no changes between them, but honestly I'm not sure the best way to accomplish that, from a technical point of view. - perhaps having some sort of boolean variable for each level/scene, that when the first change occurs to that element, it receives a value of 1? I leave that to programmers...). ;)

**Comment by RodneyBaker** [comment]
There are a lot of moving parts here so, as has been suggested, one way forward would be to simply add an option to increment file saving by adding a sequential number to the filename.  The basic pseudo code might be:
- Upon user opting to Save any *Project or Scene file*
- If the filename already exists 
- and filename ends in a number
- Add 1 to the number
- Save the file

*The file incremented should probably be limited to Project and Scene files because incrementing Levels, Palettes, etc. is more likely to break a link to/from other files not aware of the change.  

@Orphanlast said:
we're talking about having multiple save versions of the same levels.

To my view this is very problematic.
@gab3d's suggestion to maintain keep the most recently updated data with the original filename would be prefrerred but there a presupposition that users will know that myFilename.tnz is a newer version than myFileame001.tnz.  This is possible but I'll guess that the majority of users will think the highest increment is the most recent.

Aside:  There is an interesting trend in programming that removes 'saving' entirely from user interfaces because every change is (incrementally) saved into the (current) file.  Presumably the histories of these files can then be moved through back and forward to any point because only the changes are saved (and no duplication.  The user is variously told via the interface that their files are continuously saved.  I must assume there is some way to control how much data is auto-saved before the data begins to overwrite that which was recorded prior.  I will further speculate that if external files are missing that round of file memory is set to purge before that of other data because an assumption is accepted that because the external file no longer exists it is no longer desired.  This methodology approaches the idea of 'self healing' files.

All this to say that one the one hand incremental saving is simple but on the other it is a part of an area of interest that is very complex and on cutting edge of software and hardware technology.

**Comment by adamearle** [comment]
Sorry guys 
I don't have to much time today but we have system that we use at the moment which is pretty simple and has saved us a few times

1. Final (The latest file is always in this scene)
2. WIP (This is is where  all working files go) 
3. Roll back Folder (this is the back up of all working files) 

On top of this, we have a ghost drive that keeps backups of all the first drive everything is pushed to this and nothing can be deleted without authorization.

So the way that it works is when the project is setup we have we set either have an automatic option or we have  you can set where folders are stored. Our system is still a work in progress.  We also have what we call the Omni Scene/Drive/project which houses all the smaller scenes.  

The idea behind all of this is to protect employers, employees and data loss.

It might also be worth mentioning we are looking into using TACTIC by Southpaw Technologies as we know that Toonboom operates on it now and Adobe CC it's opensource technology and the way that they make money is by renting servers space. This means that you could run this on your own machines/ server locally.

It might be time to think about the bigger picture of production?

Link: [](http://www.southpawtech.com/)

**Comment by damies13** [comment]
Hi all, say this and wanted to add a comment, if disk space is really a concern, there are ways of mitigating the issue.

Backup software such as timemachine (mac) and deja dup (linux) use a system where the file is stored once and linked to in subsequent / previous revisions when a file in the project changes the last version that had the previous version of the file keeps it and the newer revision get the new file and then subsequent revisions are then linked to the revised file.

I probably didn't explain this very clearly but could the backup saves use a similar system?

I think git also uses a similar system to save disk space for many branches, so perhaps an opentoonz project could be setup like a git repository and each time the user presses save it creates a for named with that date + time, you would then just need an interface in the project dialogue to remove the branches that are no longer required.

anyway just trowing suggestions out there, comments welcome.

**Comment by shun-iwasawa** [comment]
@damies13 Actually Toonz Harlequin has a [Version Control feature](http://opentoonz.readthedocs.io/en/latest/using_the_version_control.html). It is not maintained in OpenToonz but the source is still there as-is.

**Comment by DarrenTea** [comment]
I don't think this has to be complicated initially and because of how delicate the program is (I've had a few messed up scene files myself), we need to do something.

For most of us, disk space isn't that tight, so I wouldn't worry about how much space it takes up and when you setup the auto-backup, you could specify how long the backups last for. i.e. number of days or number of versions, so for instance, you could hold just the last 20 versions or just keep backups for a week. Or you could allow them to just build up until you manually deleted them.

The only option you really need is one to rollback to a previous version, which would copy the files back from the backup location to the main location.

I'm a developer, but the setup instructions for OT are so convoluted and I've not developed in C++ for a long time, so I might have a go at developing a separate backup app to work with OT to store backups -
 just for myself mainly, but I'd also share it if it works.

**Comment by jpturcotte** [comment]
@DarrenTea Maybe @turtletooth can help setting you up either here or on the Discord server. I never asked him nor succeeded myself with MSVC, but I know he helped many people.

**Comment by damies13** [comment]
> For most of us, disk space isn't that tight
@DarrenTea  true, however we shouldn't be glibly wasteful with it either (maybe that's the sys-admin / tester in me coming out).

As @shun-iwasawa pointed out there is already a Version Control Feature that provides a mechanism for this, so there really is no need to develop anything new, the Version Control Feature requires Subversion, however there are many Subversion servers available including free (open source) ones and ones with commercial support, so there should be one that meets the needs of your project.

I haven't tried using it in OpenToons yet, when I do I'll come back and advise if I find any differences from the documentation linked to above.

**Comment by turtletooth** [comment]
@damies13 I think setting up version control is cumbersome and potentially overkill for many people.  I think having a quick way to add _01, _02 to the end of a scene name would be very useful.

**Comment by RodneyBaker** [comment]
I agree, the vast majority of users won't take the time to set up version
control.
Version control is a separate track for (dare I say) 'pro' users.

**Comment by gab3d** [comment]
@damies13  @turtletooth @RodneyBaker 
I think there's room for both, and the key word should be "Options".

It's good to have both, the option to use a simple versioning system for small projects/studios, as well as a more developed and powerfull one (like CVS or SVN) for bigger working environments in need of a more "secure" system of controlling versioning permissions and ownership of files.

So, to me, it is fantastic that we could have both ways in OT, as different options, neither of which mandatory by default.

**Comment by konero** [comment]
Why not use Save Scene As on a shortcut? 🤕  

Besides, I can't tell if this issue is requesting versioning, or a temp file to guard against software crashes. The title suggests it's versioning, so if that's what you want why not just turn on File History in Windows? That will give you a one-click solution, already built-in.

I use it all the time. In a team, you can setup a homegroup which will let you control user access to the backup drive after setting it up on just one system. It allows you to purge old changes, for example when my project is complete, I delete all but the most recent changes with one-click. You can also schedule when to delete old changes automatically, to reserve disk space.

Saving an incremental on each save is overkill. If you let File History backup each night then at worst you'll lose a days work.

Sorry, I don't see much point in replicating a feature most modern operating systems already have baked in. Or have I misunderstood?

**Comment by gab3d** [comment]
@konero 
I see you don't currently:
1. Understand.
The purpose of the feature is to easily implement the saving of versions as a system of working. Of course this could lead to a smaller chance of losing work, but this is not necessarily the only benefit.
As I see it (others may think different) it should be a voluntary action of the user, to save a new version or not, but if he chooses to do so, there should be a quick way of just incrementing the current version number by one, by hitting a shortcut key. No dialogs, no comfirmations, just that.

Also, we're not inventing anything here, the most used programs have it.

2. Value.
Is evident that you don't currently work that way and hence don't value this feature. But that doesn"t mean it couldn't be very useful to others (count me in), so it's just a matter of adding something to OT that is useful to others and won't affect your working style.

As I see it, it should be a good situation for everyone. :)

**Comment by damies13** [comment]
@konero There is a similar feature in OSX (timemachine) and several apps for linux desktops that do this as well, actually windows is the poor cousin for this as it's not available or consistent, as I understand it, it was introduced in windows 7, behaved differently in windows 8.0/8.1 and was removed (partially?) in windows 10.

@gab3d I agree that if this is implemented as an off by default option that people can enable as an alternative to full version control then there is no reason not to provide people with options.

**Comment by DarrenTea** [comment]
Hi all. I've built my external backup and restore tool. I've built this mainly for me as I've had the issue of OT crashing during a save and had to manually edit the .tnz file. It works for my workflow, but might not for everyone, so if you try to use it, check it does what you think it does. The backup happens when you save the .tnx file (with Save all or save scene) and creates a new subfolder, OTBackup. I'm happy for anyone to use it. You can download it from: https://drive.google.com/file/d/1To9xXKO4hzU2xH2MD66-txygSJoLa28b/view?usp=sharing

**Comment by artisteacher** [comment]
Personally I don’t think the status quo is cutting it - I’ve had too many students lose levels - or less frequently find them corrupted.  An incremental save option could be helpful - assuming it worked for both scene and level files. There needs to be some sort of way to easily recover lost or corrupted files. For my personal work I backup with a time capsule & there is version control but neither of those options are feasible in a school setting. 

With Blender, you can recover the last session and recover the last autosave. The recover options are available both from the startup pop-up and the file menu. Those would both be handy options that could help recover lost/corrupted work at least more frequently than is now readily possible.

**Comment by artisteacher** [comment]
I don’t know how I missed this, but there is a “Backup Animation Levels when Saving” preference. This obviously only helps with levels & isn’t incremental saving, but this could really minimize issues with lost/corrupted levels. In the Level menu, it might be handy to have a revert to backup command when the preference is active.

**Comment by RodneyBaker** [comment]
Closing as a feature request slipping to the 2019 development cycle.
Tagged as 'roadmap' primarily to examine viability especially with respect to examining other aspects of saving, securing and sharing Opentoonz files.
