### ISSUE TITLE
Two problems...

### ISSUE THREAD

**Issue by SophieChieko** [opentoonz/opentoonz#1551]
Hello everyone.

Help me please! I have got two issues with Opentoonz. (Sorry for my english, it is not my native language).

1) When I change manually the size of the Brush tool or the Geometric tool (I erase the number and write over), the number is changed but the line's width/size is exactly the same as before! I have got the version 1.1.3 of Opentoonz and it seems to be the lastest, am I right? Maybe the problem it's because I use a PC with Windows. Because people with Mac don't seem to have this problem...

2) The line's size in a Vector level seems to be much larger than in a Raster level for me. Is it normal ? How to change that ? Because I want to draw vectorial lines but thiner...

Thank you so much if you accept to give me a little of your time to help me.

**Comment by openanim** [comment]
Your first problem seems related to this one too?  It seems that few users are affected by this problem.

On my side I can't write a decimal number, the point of my keyboard is not recognized by Opentoonz. Yet it is recognized when I change thickness with the selection tool manually. That's what's weird.

With brush/ geometry tools , if I write whole numbers (1/2/3/4) manually we can distinguish the difference in size. However, since I can't manually write decimal numbers, I have to use the geometry tools slider to change the size when i want small lines thickness. Otherwise it is not recognized.

Try using the cursor of your tools to change the size in combination with the right and left directional arrows to gain precision on smaller sizes for your second problem.

Can you manually write decimal numbers with geometry and brush tools ?

**Comment by SophieChieko** [comment]
Thank you for your answer! 

Opentoonz doesn't recognize the point of my keyboard. First with the cursor of the tool I select the 0.96 value. Then I put my cursor of my mouse after the decimal number and I erase with the touch <= only the numbers, not the point. 

"Try using the cursor of your tools to change the size in combination with the right and left directional arrows to gain precision on smaller sizes for your second problem."
-> It only works for the geometric tools, not for the brush tool... And that's weird :/

**Comment by openanim** [comment]
Unfortunately, I have the same problems, I have no other solutions than these. 

For the brush , If you have a large screen, you can try moving the cursor down by moving the mouse very slowly to change the values.  Or after drawing with the brush, use the selection tool or pump tool to readjust the thickness of your line to the desired value. Do you have a French keyboard too? I tried to switch to qwerty mode but no results.

**Comment by SophieChieko** [comment]
Yes, I think I will use the pump tool, it's a very good idea!
Thank you very much!
