### ISSUE TITLE
[Feature Request] Improve Startup box: Scene association with projects

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#1553]
Consider that I've used OpenToonz for more than one project now, I actually realized that (due to my own bad habits when it comes to naming things) when I try to name scenes according to shot numberig in a storyboard for any given project, there are likely to be two different scenes with the same names for different projects. Trying to figure out which comes from which project can can be difficult, unless we just close the box and opened the scenes the old fashioned way. 

I was wondering if it's possible to improve this dialogue box so as to allow users to easily distinguish which scene belongs to which project? 

One idea may be to change the scenes shown in "Open Scene" depending on which scene is selected in "Choose Project", at least until a "Show All" checkbox is clicked. 

Another idea may be to simply "show" either besides or below each scene which projects they might belong to. 

This feature request may not be a priority, so it's okay to keep this in the back-burner and implement it when deciding on a larger, more necessary design / feature that may be discussed in the future when it comes to the startup box. I just thought I'd put this idea here either way, because I thought it may be helpful. 

Till then, I'm fine with myself just using better naming conventions. 

![selection_849](https://user-images.githubusercontent.com/5314015/32377217-ec47eba0-c0cc-11e7-9d01-88c5b1c6c5a4.png)

**Comment by artisteacher** [comment]
I agree that it would be helpful to see which project the scenes belong to. I would probably just place the project name next to the scene name - perhaps in italics with a less contrasting color.

**Comment by tushantin** [comment]
Yeah! I wouldn't mind that either. That's a pretty simple and forward solution.

**Comment by DarrenTea** [comment]
I agree. This shouldn't be too hard to do either. If I could understand the developer setup instructions I'd be tempted to do this myself. (I looked at them earlier as I'd like to try to fix some some problems), I think a list showing something like this would be really easy to read:

In the jungle: 4-1
In the jungle: 4-2
In the jungle: 4-3
Over the hill: 2
Over the hill: 2-2
Over the hill: 2-3

**Comment by turtletooth** [comment]
There is already a tool tip if you hover over the recent scenes.  That said- I just made this feature.

**Comment by DarrenTea** [comment]
While this is still open, it'd be handy to show the project name next to the scene name in the title bar of OpenToonz once opened.

**Comment by RodneyBaker** [comment]
Thanks much for this addition.  It helps in reminding us what scenes belong to what Projects at a quick glance and that helps a lot!  

I also like that if a scene-project listing that appears is not located where it says it should be the list is updated and the entry removed after clicking.  I probably shouldn't like that... as it removes items that could have only temporarily moved... that reside on a USB, removable harddrive, etc. but I love that it tries to keep the list up to date with only those scenes still active.  If this should ever become a problem (and I'm not sure that it will) those items could perhaps instead move to the bottom of the list rather than be removed altogether.  Then an option might be made to (Right Click) and remove the item from the listing.  Or perhaps a missing file in the listing would turn dark red to indicate it was missing (ala missing levels in an xsheet).  BUT like I said, I love how it works now and if a file is really needed on that list all the user has to do is open the scene again and the list will be repopulated with that scene on the top.  Nice.

**Comment by blackwarthog** [comment]
In Synfig Studio we already have solution to represent different short paths for files with identical names:

https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/mainwindow.cpp#L231

**Comment by blackwarthog** [comment]
How it's work for files:

~/Documents/morevna/synfig/mem/123/fillrect.sifz
~/Documents/morevna/fillrect.sifz
~/Documents/morevna/synfig/123/fillrect.sifz
~/Documents/morevna/synfig/fillrect.sifz

![screen](https://user-images.githubusercontent.com/5143743/40802698-9a9cc46a-6540-11e8-9e5a-e61bef221793.png)

**Comment by RodneyBaker** [comment]
Closing this pending reopening of the associated PR which was closed or the creation of a new PR to implement the feature.
