### ISSUE TITLE
Running Opentoonz in a restricted school environment

### ISSUE THREAD

**Issue by asm-farmors** [opentoonz/opentoonz#1578]
Hi

I'd really like to use OpenToonz with our school animation club. But it won't run for our limited student accounts. I can run it with an administrator account, but if I try to use a student one it closes as soon as the loading screen appears.

Student accounts do not have the ability to access the C drive directly, though they can read files and execute applications. Does OpenToonz attempt to write to a file location on drive C when a user opens it as that would stop it?

Best wishes
andy

**Comment by RodneyBaker** [comment]
Assuming Windows here...

You could use the portable version and each student could have their own copy of OpenToonz and their files would be saved in the stuff folder accompanying their copy.  

Perhaps your school might not allow USB sticks but that would be an option.

Any installation of OpenToonz can be made portable by creating a portable stuff directory (so if that is an option folks here would be glad to walk you through that process... or you can just download and duplicate the most recent portable release.  This is to say the entire program and supporting files can be saved to a specific location so... while overkill... each student can have their own copy of OpenToonz in a directory of their own or on a USB stick.

The USB stick approach does have one downside in that it can take a little longer to save files but other than that there isn't much of a difference.

It would be a bit of work but you could also set up directories for each student that only they (and admin) have access to.  Initially, place copies of the working/tested portable OpenToonz in each.

If desiring to allow the students access to additional image formats that can only be accessed via FFMPEG then your initial setup should specify where OpenToonz will be able to locate the FFMPEG\bin directory.  There is a portable FFMPEG release as well so that also can be placed on a USB.

I will guess the reason for the shutdown with student accounts is due to the OpenToonz stuff folder being installed on the root of C:Drive where students won't have write access.  A portable OpenToonz dropped into the students documents directory will resolve this as the stuff folder will be in a subdirectory they have access to.

**Comment by asm-farmors** [comment]
Thanks Rodney, that's a great help.

I'll do some experimenting and let you know how I get on :-)

**Comment by manongjohn** [comment]
I think the problem here is by default, OT installs the stuff folder to the C drive. When OT opens it reads and updates user settings in the Stuff folder. In this case it is failing to get access since C is locked down.

For scenarios like this, the OpenToonz 1.x Stuff folder should be installed to a different drive when prompted. This way you don't need to give everyone portable versions.

Granted using a portable version is probably ideal in this situation so they can continue work from home or anywhere but may have some performance issues running off USB.

**Comment by RodneyBaker** [comment]
I took a course several years ago and used a USB fairly extensively.  The schools computers would reset to a default install each time they were restarted and we were told to restart the computer at the end of every class.  This is why I can envision how OpenToonz might work well using a USB as the transfer system.

BUT...  as @manongjohn suggests I would not suggest that students actual run OpenToonz from the USB but rather to copy the OpenToonz folder (which you would provide them at the start of the course) and they would then copy that folder to the desktop of the computer to run the program from.  At the end of the class the student would then make two copies of the folder by dragging it once to the USB and once (optionally) to a network drive as backup and where the instructor could review the days work (as required).   Or something like that.   The USB could be the optional part if the student will not use it at home although even then I would think it desireable as a backup.

The only real issue with the transfer would be that upon drag/drop to the USB the user would be prompted as to whether they should overwrite the previous files.  I would suggest they do not but rather copy the folder to a new folder appended with the date (and time if necessary).  Again, variations can be used as required.

This would also be an effective way to distribute the initial OpenToonz (portable) setup as the following step can be used to make the 'pure' copy of OpenToonz and then that copy can be placed where necessary (even zipped up) and placed on a network drive or in one of the common university software programs that allow assignments and required resources to be downloaded.  The basic steps to setup of the 'purer' portable:

(This will need to be done on a computer that allows installation and use of C:Drive)
- Download desired release of OpenToonz
- Install accepting all defaults
- Go to C:\Drive (C:\OpenToonz\version stuff) and rename the stuff folder as 'portable stuff'.
- Copy or move the portable stuff folder inside the OpenToonz directory where it was installed (this should be C:\Program Files\OpenToonz versionnumber)

Note:  We now have a 'pure' portable copy of the latest release of OpenToonz that should NOT run because a portable release likely will not run from the Program Files location.

- Copy/Move/zip that OpenToonz folder to appropriate location for sharing.

In order to check their work the instructor could have a local directory on their computer where they simply rename the OpenToonz portable with the name and/or Student ID of the student.
They then can not only check on the work of the student but can assist with any customization of the program because... they have an exact copy of the program AND the files the student most currently used.

Hope all of this makes sense.

**Comment by RodneyBaker** [comment]
I'll add this as well.  It's the very short code of a batch file that can be ran to automatically generate the 'pure' portable after an OpenToonz installation.  Run the batchfile immediately after install and then distribute the OpenToonz directory that contains the program and stuff directory.

----------------------------------
Begin MakePortable.bat content (file must have the .bat extension in order to be run from the command line)
----------------------------------
@echo off
mkdir E:\OpenToonz
mddir E:\OpenToonz\portablestuff

xcopy "C:\Program Files\OpenToonz 1.2\*.*" E:\OpenToonz
xcopy "C:\OpenToonz 1.2 stuff\*.*" E:\OpenToonz\portablestuff
---------------

The above will copy the contents of the installed OpenToonz program and the stuff directory to a directory named OpenToonz on the E:Drive (which might be the location of a USB drive)  Change the drive letter as required or adjust the batch file to allow for a variable that allows the target location to be specified.

This can be used as a method of backup as well although I personally would want to append the date to the end of the directory for easy identification.

**Comment by RodneyBaker** [comment]
Any updates on this @asm-farmors ?
The last status update was one year ago.
Recommend closing as applicable.
