### ISSUE TITLE
Renumbering issue

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1581]
To recreate- 
- Create a level with a handful of frames:

![preinsert](https://user-images.githubusercontent.com/4576381/32972373-5182365a-cbaf-11e7-8584-c9553861a225.PNG)
- Save
- Close OpenToonz (This is important)
- Reopen the scene
Insert a blank frame in the middle somewhere, a frame is lost:
![inserted](https://user-images.githubusercontent.com/4576381/32972460-b6d98224-cbaf-11e7-8e2c-664aeb2deb48.PNG)

I have tried to look into this but can't quite figure out what is going on.

**Comment by manongjohn** [comment]
@turtletooth I'll take a look at it when I am done fixing my PR. I spent a lot of time looking at renumbering and loading when I fixed a renumber crash a few months ago.

Likely when the frame was inserted, the level frameid lust didnt update correctly. Or iy is using old level frame id lust when it should be using the cache because it was changed.
