### ISSUE TITLE
[Feature Request] Motion FX nodes or modifiers, such as Camera Shake / Noise

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#1606]
Recently I've been working on a shot where much of the drawings are static, except for pebbles and camera which needed to shake slightly to depict some kind of an imminent earthquake. In Blender I could do this easily by simply creating one keyframe on the camera and applying the Noise Modifier in the Graph Editor. 

Unfortunately, I realized that such a feature does not seem to exist in OpenToonz, which is a shame because I needed to render from OT, import in Blender and apply the camera motion, then re-render from there again. It would save a lot of time if it was possible to directly do this in OT instead. 

I don't know how it could be implemented, but an idea would be to have a "Motions" category in the FX schematic, where one could simply add a node for any level (such as the camera or stone) to pass through. Not only could we have "Noise" as a Motion category, but also any other potential Motion modifier such as Path-Follow, Duplicate or something (people can get pretty creative with this). 

If not nodes, we could even have something that changes the values in the Animation tab / Function Editor, perhaps, but I'm not entirely sure how that may work. 

EDIT: Very sorry, I did not know about the policy-change about Feature Requests before posting this. https://github.com/opentoonz/opentoonz/issues/1207 Feel free to close this or take it to somewhere more appropriate, if it's convenient.

**Comment by shun-iwasawa** [comment]
@tushantin 
You can create shaking movement by applying the expression `random(min,max)` to the `ew` and `ns` parameters of the current camera. `random_s(seed,min,max)` works like `random` , but allows you to specify the random seed so that you can obtain different patterns of values for each direction.

![image](https://user-images.githubusercontent.com/17974955/33240652-e8195ea0-d2fc-11e7-8adb-ac006a47d56c.png)

Please refer to [here](http://opentoonz.readthedocs.io/en/latest/editing_curves_and_numerical_columns.html?highlight=expression#using-interpolations-based-on-expressions) for details of expressions.
