### ISSUE TITLE
My Paint + Plastic Tool (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1620]
![ezgif-4-825684761c](https://user-images.githubusercontent.com/25724133/33402775-5cf4988c-d566-11e7-937b-a21de7398164.gif)

Applying the Plastic Tool to the MyPaint raster strokes, you can create amazing visual effects, clouds, smoke, cosmic nebulae and much more. Unfortunately, when you switch the Plastic Tool to Animate mode, there are cross-shaped artifacts.

**Comment by beeheemooth** [comment]
![ezgif-4-f3e0837618](https://user-images.githubusercontent.com/25724133/33405378-c344933a-d570-11e7-9891-270ca752dd92.gif)

Another interesting fact is that switching the Preview change the position of crossed artifacts lines.

**Comment by artisteacher** [comment]
I’m seeing the same thing in OS X. It’s interesting, going back to build skeleton hides the grid lines but they continue to display in preview. Changing the active tool or hiding the mesh has no impact. The plastic tool has so much potential but it needs the display reworked - particularly for Linux and OS X which also have the background transparency issue.

**Comment by artisteacher** [comment]
Yes, this also appears in the final render.

**Comment by beeheemooth** [comment]
This thing also appears when the color transparency changes
![ezgif-3-3c2f316a15](https://user-images.githubusercontent.com/25724133/34073818-0e37d2f2-e2ab-11e7-8581-b7131b8a7e30.gif)

**Comment by shun-iwasawa** [comment]
Found that the unwanted line artifacts is due to the border of texture tiles used for plastic deformation.
Changing the maximum available tile size set [here](https://github.com/opentoonz/opentoonz/blob/792dc2b6b402d622292efe815bfaa2635c43eeb9/toonz/sources/tnzext/meshtexturizer.cpp#L249-L251) from 512 to larger number (let's say, 2048) will reduce the tile amount to 1 in most cases and will resolve the problem.
