### ISSUE TITLE
 Tell me how to edit .qss

### ISSUE THREAD

**Issue by DoomDesigner** [opentoonz/opentoonz#1634]
Tell me how to edit .qss if it is written in one line. 
![image](https://user-images.githubusercontent.com/32999433/33513372-686270e8-d752-11e7-9afe-14070c0eb574.png)

**Comment by konero** [comment]
@DoomDesigner It's written in [Less](http://lesscss.org/).

> Less is a CSS pre-processor, meaning that it extends the CSS language, adding features that allow variables, mixins, functions and many other techniques that allow you to make CSS that is more maintainable, themeable and extendable.

I suggest installing [VSCode](https://code.visualstudio.com/) and the [Easy Less](https://marketplace.visualstudio.com/items?itemName=mrcrowl.easy-less) and [Less IntelliSense](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-less) extensions, which will allow you to compile on save (by saving the theme files in the `themes` folder) and see a list of variables when typing.

Why build it this way? There are four theme colors, so instead of maintaining each theme separately they're all linked to a base layout, then variables are used to change the colors of that layout.

Open the `qss/Default/less` folder in VSCode to load the project.

**Comment by DoomDesigner** [comment]
Thank you, now it's better. But it still looks like porridge. Previously, these files worked better. It was all structured. But now everything works badly.
![image](https://user-images.githubusercontent.com/32999433/33514773-d4fc2eb6-d76a-11e7-98f0-106f5078865e.png)

**Comment by DoomDesigner** [comment]
Previously, this is how it worked.
![image](https://user-images.githubusercontent.com/32999433/33515002-f4af2f8a-d76d-11e7-8aa3-37790be1f235.png)

**Comment by manongjohn** [comment]
You should be updating the .less files, not the .qss files directly.  If you updated the .qss files directly, they may be lost if someone recompiles the .less file later.

**Comment by Agnyy** [comment]
But is not the basic setting in the .qss located? but if someone wants to completely develop a new theme? Previously, you could just remake everything in .qss.

**Comment by manongjohn** [comment]
If you are constructing brand new themes outside the stock themes that are provided with release, you can probably just make .qss files. Just need to make sure you have everything OT needs. The stock themes should only be modified via .less files that are there otherwise those changes risk getting lost.

**Comment by turtletooth** [comment]
If someone wants to develop a new theme, technically they could just make a qss file.  However, there is already a established theme system using less files compiled down to qss files.  I think working within the already established setup is a much preferable option.

**Comment by RodneyBaker** [comment]
Also, see instructions for editing Style Sheets:

https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_stylesheet.md
