### ISSUE TITLE
(Discussion) Icons

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#1637]
I know that many do not like standard icons. I think that it will be useful to discuss the icons here and suggest to enter or change them.

**Comment by Agnyy** [comment]
Icon "selection tool"  It's just an option, it just seems more logical.
![selection tool](https://user-images.githubusercontent.com/25137502/33519235-285f2e98-d7b4-11e7-98fe-2d93db2af1ac.jpeg)
![selection tool 1](https://user-images.githubusercontent.com/25137502/33519236-2889377e-d7b4-11e7-8998-b721df499a3f.jpeg)


[Selection tool (SVG).zip](https://github.com/opentoonz/opentoonz/files/1524100/Selection.tool.SVG.zip)

**Comment by Orphanlast** [comment]
I think the Control Point Editor needs to look different from the selection tool. It shoudd be a black cursor icon. In fact, the cursor itself should be black.

It sucks when you forget you're on the control point editor. You go to make a selection and it's not working right (because it's the wrong tool). 

Sometimes this slows your workflow down by 5 seconds. This may not sound like much, but in the course of an hour, that can possibly add up to 10 minutes. That's potentially 80 minutes lost in an 8 hour day of animating.

**Comment by Agnyy** [comment]
Icon for "Edit Tool" or "Animate tool"
![image](https://user-images.githubusercontent.com/25137502/33519428-4b56fee6-d7b7-11e7-927e-0afe49f9d426.png) 

[Animate tool (SVG).zip](https://github.com/opentoonz/opentoonz/files/1524117/Animate.tool.SVG.zip)

**Comment by turtletooth** [comment]
I think the selection tool icon is fine.  It is the same icon as is used in most other programs - a simple arrow for selecting things.

**Comment by DoomDesigner** [comment]
I propose to make an icon for the COLLAPSE function as in After Effects Pre-compose.
![design](https://user-images.githubusercontent.com/32999433/33524309-dc50e8f2-d82b-11e7-8558-2bd7b8fb7ac4.jpeg)
[Collapse.zip](https://github.com/opentoonz/opentoonz/files/1524648/Collapse.zip)

**Comment by DoomDesigner** [comment]
I suggest making the icon "COLLAPSE" as the "Pre-compose" icon in the After Effects. 
![design](https://user-images.githubusercontent.com/32999433/33524567-a4a5a1a4-d830-11e7-9cdc-a60622e7fe60.jpeg)
[Collapse.zip](https://github.com/opentoonz/opentoonz/files/1524672/Collapse.zip)

**Comment by DoomDesigner** [comment]
It would be logical to re-name "Collapse" in "Sub-xsheet".

**Comment by DoomDesigner** [comment]
#1630 "Clone" icon
![clone sub-xsheet](https://user-images.githubusercontent.com/32999433/33524872-77efde68-d835-11e7-8123-8096f0632d30.jpeg)

[Clone Sub-Xsheet.zip](https://github.com/opentoonz/opentoonz/files/1524692/Clone.Sub-Xsheet.zip)

**Comment by DoomDesigner** [comment]
"preferences" Icon #1630

![preferences](https://user-images.githubusercontent.com/32999433/33525053-75beb652-d838-11e7-884a-cfaba7fc99ab.jpeg)
[preferences.zip](https://github.com/opentoonz/opentoonz/files/1524707/preferences.zip)

**Comment by artisteacher** [comment]
I agree with @Orphanlast that the equivalent of the control point editor is black in most programs. It does look a bit different than the selection tool, but I’ve also forgotten which tool I was using and tried to select with the wrong tool active. 

As far as the collapse name goes, I feel like collapse is more easily understood  in terms of expectations from the etymology of the two terms. I always think of making a sub-xsheet as sort of consolidating columns to take up less space & to allow more flexibility for animating. Pre-compose just makes me think of a draft stage for writing or some other sort of planning stage. Perhaps it’s because I haven’t used After Effects, but I think the current icon is just fine and better compliments the enter/exit icons. I do like the preferences icon though.

**Comment by RodneyBaker** [comment]
Will close this report given that all the icons for Opentoonz have recently been updated/refreshed.
It may be that the next iteration of Icon development might move toward a method where icon sets can be easily changed.

@Agnyy Please feel free to continue the discussion here (or in a new report) and as we continue the UI Scrub moving toward the release of v1.5 and beyond.
