### ISSUE TITLE
Incorrect usage of seconds abbreviation

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#1664]
@shun-iwasawa 
in the Xsheet, when you select "Sec Frame" option, each frame in the xsheet is identified with a pair of numbers in the format:
nn' mm"  (i.e.  02' 23")
...intending to mean  nn seconds + mm frames.
But it's confusing as the symbol to abbreviate seconds is in fact ", and the one for minutes is '. So a user would normally interpret  nn minutes + mm seconds from reading that.

for reference, you can look here:
http://www.abbreviations.com/abbreviation/Second
http://www.abbreviations.com/abbreviation/minute

I think the correct way of displaying it would be:
nn" mmf  (i.e.  02" 23f)

**Comment by RodneyBaker** [comment]
@gab3d 
I think that is a reference to feet and frames in the traditional animation jargon.
Feet = '
Frames = "

If we were to use 02" that would read to me as 2 inches.
Unless I'm missing something... following the way you suggest... 2 Feet 23 frames would translate to 2' 23f.

I'm pretty sure I'm right on this because look what happens at the transition frame 24 to 25.
At frame 24 it's still 00 for seconds but at frame 25 it reads 01 (i.e. one foot or second of animation)

Now the problem here would then be that 'feet' may not be familar to many people.
The important part of it however is that 'feet' is a unit of 1 second... regardless of how many frames that may be.  (It started/settled as 16 frames before the advent of sound and then changed to 24 frames to get a better sync with sound.)

To complicate matters even more 'minutes' is also something different in rotations...

I guess what I'm saying is that I don't think the notation is incorrect, just difficult to interpret depending on the background and experience of the animator.  As this software was/is tailored to paper based animation I'd say we may be experiencing the use of 'feet and frames' in this particular situation.

What you may want to do is open a feature request for another standard way of notation.

**Comment by gab3d** [comment]
@RodneyBaker 
Thank you for the background info on this topic, honestly I didn't have idea of the feet=seconds equivalence.

Still, I think some things are wrong with that:
- we cannot pretend everyone to get lectured about the history of animation films (a decadent medium by the way), and on why that kind of units (feet) had any meaning at all when trying to mean seconds.
- the " symbol used as a way to represent "a frame" is something no other software, that I know of, uses, so in this respect we can hardly expect a normal (young) could decode that " as seconds. The most probable case would be that the user interpreted 02' 23" as 2 feet 23 inches, what undoubtly will have no sense.
- if it is decided that the current way of displaying the units stays unchanged, then I think at least the option should be renames to "Feet Frames", because currently the option is named "Sec Frames" and the symbol ' is by no means the one for seconds, nor " the one for frames (at least here is the first time I saw it used in that way). So at leat if the option is called "Feet Frames" one of the two symbols will make sense to anyone uneducated in hardcore film industry history.

Anyways, to me it still makes more sense to just change the symbols to  02" 23f   or  02s 23f   to avoid any type of confusion.

**Comment by jpturcotte** [comment]
I think 02" 23f would be confusing to both groups, and so I definitely back the second option of 02s 23f.

**Comment by gab3d** [comment]
@jpturcotte 
sorry, I've just spotted it, it was a typo.
I mean 02' 23f  or  02s 23f.

**Comment by jpturcotte** [comment]
@gab3d I did not even notice! I think I am tired. My point stands: mixing marks and letters is weird. If ' is feet, then what is f, etc. 02s 23f seems unmistakable.

**Comment by gab3d** [comment]
@jpturcotte 
yep, I was just clarifying my own error; your point was valid and clear anyways! ;)

**Comment by RodneyBaker** [comment]
I think we need to have an expert familiar with the Japanese animation industry weigh in on this.
I can't really speak to that.


---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
Useless typing follows.   Read only if you are bored and need additional entertainment. 
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------

BLUFF:  In a perfect (sanitized) world I suppose all annotations would be dropped and only the numbers would remain. This is what most other software does.   Although it doesn't quite meet all expectations. ** To match general (classic) storyboarding methodology the seconds/feet might be underlined and/or the seconds and frames separated by a dash.

2 - 7 (2 Seconds and 7 Frames)
2 - 00 (usually with the 00 underlined  = 2 seconds)

This then could be used to further develop useful tools that track frame and frame sequence lengths to include simply typing in the desired length and seeing it appear in the xsheet.   Another user was exploring this idea in the OT forum so that is why I add the thought here.  The interesting thing here would be more useful in that it would be a means to read (at a glance) how long each frame segment is and immediate change it if it didn't match expectations.  I must assume this would not be trivial to implement but to imagine success one would only need to look at the current timecode in the xsheet and imagine that clicking on it would allow input from the user.  

**Also, I am a little concerned with artists/animators that cannot figure out that any of these various combinations (past, current or anticipated) equate to seconds and frames.  If they struggle with this they are in for a word of hurt when it comes to basic animation timing.  But that is why they call it learning...


> we cannot pretend everyone to get lectured about the history of animation films (a decadent medium by the way), and on why that kind of units (feet) had any meaning at all when trying to mean seconds.

Understood but hardly an argument in favor of abandoning the way animation has been created for the better part of a century.  Assuming that to actually be the case.

> the " symbol used as a way to represent "a frame" is something no other software, that I know of, uses, 

That'd be an argument in favor of keeping it!
Just because everyone else gets it wrong doesn't mean OpenToonz should as well.  ;)
It's great to see new things coming into OpenToonz but it'll be a sad day if it looks and functions just like programs that weren't designed with animation in mind from the outset. 

I guess what I"m saying is that change can be good but it shouldn't be at the cost of suggesting the classic method is incorrect.  Other software often gets things wrong because they didn't understand animation so forged ahead creating new ways that worked and made sense.  More power to them I say!

Hope that makes sense.

**Comment by RodneyBaker** [comment]
Closing pending reason to reopen.
Feel free to continue the discussion in the closed topic.
