### ISSUE TITLE
TLV Merge doesn't maintain Color Style

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1670]
When you merge two Toonz Raster Levels drawn only with the Paint Brush Tool, the key animation merges entirely (1), but in frame-by-frame animation - only the first frame (2).

1
![ezgif-3-c966df6ad2](https://user-images.githubusercontent.com/25724133/33797546-bd747f3e-dd12-11e7-98bb-bdf74e1c996e.gif)

2
![ezgif-3-17c6ac0c38](https://user-images.githubusercontent.com/25724133/33797549-d0d740e8-dd12-11e7-824e-6c8ef2591eee.gif)

**Comment by manongjohn** [comment]
What happens if you did all 3 at once? I'm wondering if its multiple merges in a row that is the problem.

**Comment by beeheemooth** [comment]
Same. I tried to swap the last two levels, but the result does not change.

**Comment by manongjohn** [comment]
Unfortunately, I am unable to duplicate this using a recently nightly (Dec 6th) on Win7.

Could you provide the scene you made above so I can see if I can duplicate it using your stuff?

**Comment by beeheemooth** [comment]
@manongjohn Are you using only the Paint Brush Tool? (not the Brush Tool)

**Comment by manongjohn** [comment]
Ok, I am able to reproduce what you are seeing, though it doesn't have to do with the type of brush being used.  It happens with both Paint Brush and Brush Tools.

What I found was the color palette wasn't merging correctly for the 3rd column, changing the color of the strokes to black for everything but the 1st frame in Col3.  

Since your Col1 has a solid black background, and frames 2-n in Col3 have their strokes changed to black, it appears to not be merging images properly but it actually is.

Will take a look to see why that is happening when I get the chance, unless someone beats me to it.

**Comment by beeheemooth** [comment]
![ezgif-3-25e8ce1815](https://user-images.githubusercontent.com/25724133/33806628-c1e7e670-ddd3-11e7-9a9f-7c38a8a19e43.gif)

I think I understand. In order for the merge to succeed, I should not use the default # 1 style. I made a different style, and it worked out! 

I'm sorry for taking your time.

**Comment by manongjohn** [comment]
@beeheemooth 
I'm reopening this. You helped uncover a merge bug that needs to be fixed. It should be keeping the style.

**Comment by RodneyBaker** [comment]
No update since Dec 2017.
Recommend reviewing this issue to determine if there is still related problems.
