### ISSUE TITLE
MP4 rendering relies on single-core PNG rendering

### ISSUE THREAD

**Issue by jpturcotte** [opentoonz/opentoonz#1672]
According to a discussion I had with @turtletooth on the Discord server, rendering to MP4 through FFmpeg currently relies on first creating a PNG sequence through OpenToonz. While this process can normally be done on multiple CPU cores with the Dedicated CPUs option in Output Settings, this option is disabled when picking MP4 as the target format. This essentially means that rendering to MP4 currently relies on an intermediate step that could be but is not running on multiple cores. The process is thus slowed down artificially, which can considerably lengthen the rendering process of longer scenes. This problem does not exist if you render to PNG from OpenToonz, and then use FFmpeg separately to render the image sequence to MP4.

**Comment by artisteacher** [comment]
It looks like gif rendering has the same issue. Is there something with FFMPEG that prevents multiple cores from being enabled? Anything that speeds up rendering time sounds like a good idea to me.

**Comment by RodneyBaker** [comment]
The primary issue there is that FFMPEG is not a renderer in that it can be shoehorned into OpenToonz for the purpose of rendering.  FFMPEG just takes data that exists already and manipulates it in useful ways.

We can still look at ways that processes can be optimized. 
I've been a subscriber to the FFMPEG mailing list for quite awhile and they are constantly addressing issues of optimization as the number of variables users of FFMPEG can face is nearly infinite.
Utimately when one looks deeper they begin to realize that OpenToonz itself isn't the answer to every problem so it's good to extend OpenToonz by other methodologies.  For instance, using OpenToonz render farm (with standalone computer or with more than one).

My thought here is that whatever process FFMPEG is currently using should be opened to the user so they can adjust it manually.  Then should they have a better instruction they could use that instead of the default.  Of course, to keep us users from breaking the default the default itself should be recoverable at any time.  But the point here is that there is no way OpenToonz developers can keep up with FFMPEG developers nor should they be required to.  We simply need to be able to adjust the FFMPEG code.  Note that we can currently do that manually through FFMPEG but the desire would be to be able to automate that to the greatest extent possible via OpenToonz.

FFMPEG should have a flag for use of all available processors:  -threads 0

REF:  https://trac.ffmpeg.org/wiki/Creating%20multiple%20outputs

**Comment by turtletooth** [comment]
When I built the ffmpeg feature, rendering with multiple cores would sometimes cause a crash, so I disabled multi-core rendering for ffmpeg formats  It doesn't always crash, but enough that I had to disable it.

**Comment by RodneyBaker** [comment]
It will be good to review the use of ffmpeg with Opentoonz in the 2020 development cycle.
Some things to consider:

- [ ] Can we supply a path to ffmpeg in Properties and/or have Opentoonz search for and locate the proper path so users do not have to supply it?
- [ ] Can we add text or link to ffmpeg website (via Preferences tab) to assist user with download?
- [ ] Can we expose the command line used to drive ffmpeg so that users can resolve their own issues by editing/adjusting the code?  Note:  This would not remove the default code but rather replace the code if the customized code is present.  In this way the user could easily revert back to the default code if/when they use code that does not work.
- [ ] Can we allow options for the user to -risk- bad results by opting to run experimental code (i.e. use of multiple cores)?
- [ ] Can we add a mechanism to allow post processing of images by running ffmpeg scripts after completion of a rendering?
- [ ] Can we supply a document containing useful examples of ffmpeg code so users will better understand how they can leverage ffmpeg independently of Opentoonz to achieve their goals?
etc.

**Comment by RodneyBaker** [comment]
Closing as I believe this issue is now resolved via latest nightly releases.
REF:  #4205

There may be some issue still outstanding with regard to ffmpeg and multi-core rendering and where that is the case it will be good to document the issues so they can be addressed.
