### ISSUE TITLE
Skeleton bone-rigging

### ISSUE THREAD

**Issue by nuub1** [opentoonz/opentoonz#1681]
Not really an issue, but...with blender there's a bone-rigging add on for 2d called rigify. It takes minutes to setup and it's very good. It would be nice if open toonz could create something like this for those not doing frame by frame animation.

**Comment by falls2lawrence** [comment]
Opentoonz
the plastic tool in opentoonz is close enough to 2d blender rigging and typically has you setup and animating in no time, fractions of the time it would take to setup a rigify metarig. there is also the skeleton tool for rigging but is more like rigging in something like flash/animatecc.

blender
rigify is a simple way of generating pre-made complex rig setups that would otherwise take hours to do from scratch most of which is wasted on a 2d rig in blender. if you're using rigify for 2d animation in blender, may I recommend looking into COA tools add-on ( cutout animation tools). 
https://youtu.be/lRVnk1PMDTs
it was a game changer for me. very handy for 2d rigging but also handy for quick and dirty 3d rigging.

**Comment by turtletooth** [comment]
Closing.  Feature requests can be made on the Google Group.
