### ISSUE TITLE
Pen pressure not working

### ISSUE THREAD

**Issue by LizardLaw974** [opentoonz/opentoonz#1685]
Hello! I just downloaded the new update for OpenToonz and, while I had backed everything up from the past folder, I forgot to take note of what my brush settings were. So, in the process of trying to get my brushes back, I've been finding that for the vector brushes, I can't get the sensitivity back to what I originally had. The pressure is there, and the pressure box is selected, but I can't get the lines to thin out like I could before, they just end with a round end as opposed to a thin pen end. I tried updating again and I even updated my tablet drivers and restarted my computer but nothing has worked. Is there something I'm missing?

Below are pictures of the line examples. The line on the left is what I'm trying to achieve and the line on the right is what I am getting as a result while tampering with the settings. I use Windows 10, a Cintiq 22HD, and the newest update of OpenToonz

![untitled](https://user-images.githubusercontent.com/31202174/33976985-8cc5c788-e066-11e7-8776-fab499043d61.png)

**Comment by turtletooth** [comment]
Could you try the 12-5-17 version of OTX and tell us if you are getting the same result?
https://gum.co/TZmmM

**Comment by LizardLaw974** [comment]
I just downloaded it, but do I place the files anywhere specific in order to get them to work in the program? When I open them, they take me to the Local Data files and then the Temp files folder.

**Comment by turtletooth** [comment]
You just need to unzip the folder and run the OpenToonz executable file inside.

**Comment by LizardLaw974** [comment]
Okay, thank you!
I did so, and yeah its still giving me the result with the round end, as opposed to it tapering off like the brush stroke on the left, even with running the file and playing around with the settings

**Comment by LizardLaw974** [comment]
Hey there! I'm so sorry for my absence, I tried to run the .exe file again to see if I did anything wrong the first time, and unfortunately, its not running because I have 1.2 installed, and I would have to reinstall the entire program. and anything else I have tried to fix in the brush settings hasn't made any difference or change at all. I'm not entirely sure what to do, if there's something that I'm missing. At the end of the day, its not program breaking, its a personal preference for my art

**Comment by RodneyBaker** [comment]
its not running because I have 1.2 installed, and I would have to reinstall the entire program.

The OTX release doesn't require any install or reinstall.
It is just downloaded, opened/unzipped and ran from whatever directory it is unzipped into.
I run a copy from a USB stick and an exact copy of that from my desktop.  I have v1.2 installed as well.

The fact that you have a Cintiq may be the primary issue as there were reports of problems on certain Cintiqs but... I was under the impression most of those problems were resolved.  Concerning the OTX release the latest has a 'modified' version and a regular version and the 'modified' is more likely to work for most people because it removes some code that was a bit too far forward leaning for some computers.  Of course, nothing says you cannot download both OTX release and run both to see which works better.

**Comment by LizardLaw974** [comment]
Unfortunately, running it isn't working either. I get these error messages with the mention of reinstalling the program. 
![untitled](https://user-images.githubusercontent.com/31202174/35025583-4ad0bf40-fb14-11e7-80a2-0e29b8241b68.png)
![untitled1](https://user-images.githubusercontent.com/31202174/35025584-4ae190f4-fb14-11e7-9119-f43ec88435c0.png)
![untitled2](https://user-images.githubusercontent.com/31202174/35025585-4af0b8d6-fb14-11e7-9f44-cb86de5291df.png)
![untitled3](https://user-images.githubusercontent.com/31202174/35025586-4afee8b6-fb14-11e7-88a4-5c9bf6263e87.png)

**Comment by RodneyBaker** [comment]
It looks to me like you are attempting to run an older release of the program.
Although it may be the one Jeremy (turtletooth) mentioned above there are newer releases available. 

ALSO... it looks to me like you are attempting to run the program while it is still inside the compressed/zipped file which would cause it not to find needed files because they are not uncompressed.
What you need to do is locate the zip file that you download, Right Click and look for an option to unzip or uncompress the file into a directory.  On my computer Right Clicking on the file gives me an option to unzip the contents into a folder with the name of the zipfile.  At any rate, once the contents of the folder are successfully placed into a folder you then can go into that folder, locate the OpenToonz.exe file and run that.  Because everything will have been uncompressed the required files can then be located and ran by the program.  Just clicking on the file (as you appear to have done) has just given you a view into the contents of that zip file.  It hasn't extracted them... yet.   Do that first and then run the .exe. file.

Hope that makes sense.

**Comment by LizardLaw974** [comment]
Yeah I had realized that right after I had sent the pictures, I'm sorry about that! ^^; I did redo the process with the updated files, and I redownloaded the program just in case my meddling had messed with it, however, even with the updated files, and with the proper extraction of the files, it runs, and with some strokes i get the end result, but the rest of the time the lines end in a rounded end. Is it something with the pen pressure or the way I'm putting pressure on the pen that may be affecting this?

**Comment by RodneyBaker** [comment]
Now that we've got the main part of the running of the program going we can focus fully on the problem.

The three specific areas to troubleshoot would be your Cintiq settings themselves, the Windows pen settings and then OpenToonz settings (in that order I would say).  

I can't help much with the Cintiq side of things because I don't have one but the standard rules would apply with regard to making sure drivers are up to date and settings are set appropriately.  It is my understanding that you should be able to specify specific settings per application and if that is the case you can specify OpenToonz and then work to optimize those settings.  There should be some other topics in the OpenToonz forum where others post their suggestions for troubleshooting issues with Cintiq.

Regarding Windows... one thing I would check would be to make sure Windows 10 'Ink' settings aren't interfering.  I turned off Windows Ink because I sensed it interfered with optimized settings.  That may or may not be the case but it was one less variable to worry about.  I also spent a little time testing the pen settings and found what appeared to work best.

In OpenToonz I set Accuracy and Smoothness high and the minimum size of vector brush to 4... maximum... I change that depending on the thickness of line I want.  For some reason I like the look of 4.  

This could be something Cintiq specific but my sense is that it's mostly about finding the optimum settings.

**Comment by NichaKrisa** [comment]
i HATE opentoonz my pressher wont work eather D:

**Comment by RodneyBaker** [comment]
This problem should be fixed for many in recent releases and  good news...  an addition that allows users to leverage Windows Ink on the PC platform is pending... mostly waiting on a licensing tweak that will allow the code to be used with OpenToonz.

**Comment by manongjohn** [comment]
@NichaKrisa What tablet are you using? You might need to disable Windows Ink in your Tablet properties so you can get pen pressure to work in OT now or wait untio we get the Windows Ink patch into OT and then you'll need to download the nightly it is in.

**Comment by RodneyBaker** [comment]
@LizardLaw974 @NichaKrisa Are you still experiencing this issue?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
