### ISSUE TITLE
marker interval is not sync when timeline is zoom out

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1688]
Thank you first of all @manongjohn 

Marker Interval is not sync with bold number, When timeline is zoom out.
win7, OT 1.2

![marker_interval](https://user-images.githubusercontent.com/16509592/34049383-1d99e91c-e1af-11e7-8b4b-07dc8eedec12.jpg)

**Comment by manongjohn** [comment]
The marker interval only currently applies to the blue line. It does not control the frame numbers when zoomed out.

Currently when using "Frames" it will only show every 5. If using other options, it will show every 5 or 6 depending on frame rate.

I choose 5 since most timelines typically denote every 5. For other frame designations, I chose 5 or 6 because of how the seconds designator was being displayed.

If there is a good reason for it and/or enough people think this should match interval marker, it can be easily changed.

I'd treat this as a feature request rather than a bug.

**Comment by 2dvision** [comment]
Personally, I think current style is confusing. If the blue line and the bold number are syncs together, we have a clean timeline.

I think timeline don't need 2 markers.
