### ISSUE TITLE
Level strip dont has white background, but why does this animator have white background in his level strip??

### ISSUE THREAD

**Issue by scribbloid** [opentoonz/opentoonz#1694]
It seems that there is no White Background when clicking on the Level Strip, you have to click on the xsheet to get a White Background.

This issue was already discussed:
https://github.com/opentoonz/opentoonz/issues/889

But this youtuber has a White Background by Default in his Level Strip (or at least it seems so):
https://www.youtube.com/watch?v=ra_QRc2o9rM&t=1616s

Now I am confused, I thought it is impossible to have a White Background in the Level Strip?

I took a screenshot from my opentoonz:
https://imgur.com/a/wudRX

Thank you for your advice

**Comment by manongjohn** [comment]
When clicking on Level Strip, the white background appears on Toonz Raster levels which the youtuber was using. It does not appear for Toonz Vector or regular Raster types. Based on your screen shot, you were using regular Raster.

Please keep usage questions in google groups and only open issues for bugs.  Thanks.

**Comment by gab3d** [comment]
...in fact you can change the background color for the Strip Level view (indirectly) by changing the Viewer Background Color.
It's not the nicest way of obtaining a white background for the Strip Level view because all of the camera stand view background gets white too, of course, but it's better than none.

**Comment by RodneyBaker** [comment]
@gab3d  

I wonder if THAT might not be a good fix to this issue that repeatedly seems to plague (mostly new) users.

Could the default in Preferences>Color>Viewer Background Color have the RBG set to something like 200,200,200 by default to avoid this issue?   This gives a consistent look across all level types (raster, Toonz Raster and Vector.   Note that I would not go with a whiter scheme such as 255,255,255 because that is blindingly bright.

I must assume that a reason the background dims to a gray is to prevent eye strain on the part of people who mostly use that room/view.

At any rate, I may experiment with the color and make that my regular default.  It gives works quite well and moving back and forth between various level types can (at times) almost be unnoticeable when brushes are set similarly enough (a very good thing).
