### ISSUE TITLE
OpenToonz_1.2.exe - Application Error The aplication was unable to start correctly (0x000007b).

### ISSUE THREAD

**Issue by Gode1234** [opentoonz/opentoonz#1720]
Hello, I installed OpenToonz (windows 7 64 bit version) on my windows 7 64 bit, but can't run the program (Error apear that message: OpenToonz_1.2.exe - Application Error The aplication was unable to start correctly (0x000007b)). To fix this I have installed and update next applications: DirectX, Net framework (4.5) and Microsoft Visual C++ Redistributable Package 2015.
Today I found a lot of solutions none of them works for me. Please advise what to do.

<a href="https://imgur.com/HsZllz6"><img src="https://i.imgur.com/HsZllz6.png" title="source: imgur.com" /></a>

**Comment by jpturcotte** [comment]
As reported by @Gode1234 on Facebook: "Yesterday I reinstalled windows 7 64 bit, after installing System Error had next content: "program can't stand because api-ms-win-crt-runtime-l1-1-0.dll is missing from my computer". I installed version recomended by u [@morevnaproject] (OpenToonz-1.2.0.2-morevna-18.01.07-win64) it's works, great. Konstantin thanks a lot."
Recommend close.
