### ISSUE TITLE
Eraser tool alters reference files?!?

### ISSUE THREAD

**Issue by GiannisGG** [opentoonz/opentoonz#1724]
I am making a cut-out animation, importing several .png files in OpenToonz's levels.

At some point, I used the eraser tool on one of them and *I couldn't undo the action.*

Checking the actual file that the layer references to, I realised that **the eraser had actually changed the .png file itself!**

So Open Toonz is not simply referencing the imported image files, but can actually **destroy** them? Or is there some settings box that I need to tick?

**Comment by gab3d** [comment]
@GiannisGG 
If you use the Save All command to save your work (or its shortcut "Ctrl + s") you are instructing OpenToonz to save the changes done in the levels to disk. So, in fact, in this case you'll be overwriting them. 
If you don't want OT to change your origina files, I'd recommend you to use duplicates of these files when opening them in OT.

To resume, the commands "Save All", "Save All Levels" and "Save Level" will ovewrite the corresponding disk files to represent the changes done to them with the painting tools of OpenToonz.

The OT scene file only saves level/camera/pegbar hierarchy and animation, fx nodes used and their animation, as well as scene/camera/preview/output options. 

I hope this helps you understand the program.

**Comment by RodneyBaker** [comment]
In addition to what @gab3d said...

When ingesting an image into OT we are given two options; import and load, where load references the original file and import makes a copy of the file, places that file in the Project's specific file structure and uses (or refers to) that copy.

It is normal operation for OT to edit the referenced file (whether imported or loaded) but it would NOT be if the original file that is no longer referenced is altered.  When importing (as opposed to 'loading') OT should no longer reference that original.  Where that happens that would be a bug.

Because OT's behavior can be changed via Preferences to where OT does not prompt the user to import or load (copy or use the original) the important part of this understand that any referenced image can be altered unless somehow locked.  This can be achieved in a variety of ways such as by placing the referenced file in a 'read only' directory BUT (as @gab3d suggeststs) standard operating procedure would be to use a copy.

**Comment by GiannisGG** [comment]
I have already started my new habit of duplicating any reference image files, before fiddling with them in OT and it is working out fine. Thank you for explaining all this!
