### ISSUE TITLE
Audio missing in Preview window

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1725]
This came up in the [Google Group](https://groups.google.com/forum/m/#!category-topic/opentoonz_en/BxjJd16JWPA): in OS X, no sound will play in the preview window (cmd-r). The audio toggle is missing from the controls.

**Comment by RodneyBaker** [comment]
This would appear to be a bug/omission on the Mac platform.

Steps to reproduce
On a Mac platform
Import audio
Use blank frames (as preferred)
Attempt to Preview via File > Preview
Note that audio doesn't play 
Note that the Music icon is not present on the bottom menu

Assumption:  The default for audio appears to be 'off' (even on windows).  Therefore one possible fix without resorting to adding the icon into the Preview window would be to change the default (on all platforms) to 'on'.  As the Preview may be desired to run without audio this default may not be ideal but it can be turned off via the music icon in Windows (confirmed) and Linux (untested).  Because the music icon is missing on Mac platform it cannot be toggled on or off.

Potential rememdies and interim fixes (best case first):  
1. Revert/restore music icon to Preview window.

2. Change default audio to 'on' and provide a means to change that default in Preferences.

3. Change default audio to 'on' for Preview window. (requires users to toggle music icon off manually and leaves Mac users unable to turn audio off in Preview.

All of the above solutions will resolve this particular issue.  Option 3 proposes an easier, immediate but  partial fix.

**Comment by artisteacher** [comment]
I discovered that the button was deliberately disabled on Macs in flipconsole.cpp (there’s a comment about sound playback being broken on macOS). Removing lines 675 - 677 bring the button back & it works as well as the viewer does. Which means with slight distortion (due to incorrect frame rate?), but definitely usable. I’ll add a pull request this weekend with the fix.
