### ISSUE TITLE
Instead of "My Documents" there should be a shortcut to the user folder in Browser

### ISSUE THREAD

**Issue by m93a** [opentoonz/opentoonz#1756]
Most often when you use the Browser, you want to add images or sound to the scene. And those can be mostly found in `%homepath%\Pictures`, `%homepath%\Music` and `%homepath\Downloads`. But in the left column, there is only a shortcut to `%homepath%\Documents`. In order to get to the folders you want, you have to navigate through the whole path `My Computer\C:\Users\username`. I think there should definitely be a link to the user's home folder.

**Comment by artisteacher** [comment]
Personally I use the Documents folder instead of the Pictures or Music. However, I do agree that a path to the user's home folder would be much more flexible. It is always a process to access anything in Downloads!

As this is really a feature request and not an actual bug, this should be opened in [the forum](https://groups.google.com/forum/#!categories/opentoonz_en) for discussion instead.

**Comment by m93a** [comment]
Cool, [I reposted it there](https://groups.google.com/d/msg/opentoonz_en/vaRCJdQD150/siQpERXgBQAJ). I'll reopen this when/if you decide to implement it 🙂
