### ISSUE TITLE
Brush and eraser do different things on an extended frame

### ISSUE THREAD

**Issue by DarrenTea** [opentoonz/opentoonz#1764]
If you draw on a frame, say frame 1, then extend it to frame 2. Now you can see the drawing whether you look at frame 1 or 2. If you then go on to frame 2 and erase part of the drawing, it erases ok. Now if you draw something, a new frame is created!

Firstly, doing both actions, drawing and erasing, should have the same outcome.
Secondly, creating a new frame seems totally the wrong thing to do as we're looking at the drawing on frame 1, so we should be editing that.

This is only important for me when I'm flipping between frames that are drawn on 2s, sometimes after flipping I land on a drawing, sometimes on the extended frame. When you're watching the motion in the animation, it takes you out of the moment to check if you're on an actual numbered drawing or an extention.

**Comment by manongjohn** [comment]
That behavior sounds like you have Autocreation preference set to Use Xsheet as Animation Sheet, and that is intended.

**Comment by DarrenTea** [comment]
I read that that tickbox was to allow you to draw on an empty frame (where there are no drawings) to start a new drawing. In my case, I've extended a drawing to that frame and expect to draw on the same drawing.

**Comment by DarrenTea** [comment]
And yes, btw, I do have that preference ticked.

**Comment by shun-iwasawa** [comment]
According to the [manual](http://opentoonz.readthedocs.io/en/latest/drawing_animation_levels.html#using-the-xsheet-as-animation-sheet);
> If the currently selected cell is empty and belongs to an empty column, a new level will be automatically created and named with the first available letter of the alphabet; if the currently selected cell is below a cell containing a level drawing, a new drawing will be added to the level.

Your case seems to be the latter case. I think the current specification is intended to make it easy to draw inbetween (e.g. draw # 1, # 5 and then # 3) , as it does not need to erase existing cell before drawing.

**Comment by DarrenTea** [comment]
ok. Thanks my friend. I've just had a play with that setting and for me, now I now about this part of the feature, I'll use Enabled instead. However, It does mean that another repeatable bug I've reported (https://github.com/opentoonz/opentoonz/issues/1693) is even more important for me. With that bug, I can't create inbetweens and trust they'll be saved. I've lost drawings because of it. If you could have a glance at my repeatable steps in that bug, I'd appreciate it.

**Comment by DarrenTea** [comment]
(It is quite confusing to new users though, that the eraser and brush do different things. One works on the current drawing and the other creates a new drawing)

**Comment by RodneyBaker** [comment]
> (It is quite confusing to new users though, that the eraser and brush do different things. One works on the current drawing and the other creates a new drawing)

Not too confusing.  We may need more detail of what you are experiencing.
We wouldn't expect to erase from a new drawing.
We would expect to erase from the current drawing.
We might expect to be able to draw on the current drawing.
We certainly might expect to draw as we simultaneously begin a new drawing.

Perhaps you can elaborate more on how the current process can confuse others.

Somewhat related:  I do sometimes when using this option via Preferences (which overall I love!) I find myself wishing there was a Shift + draw addition that would allow me to maintain the current frame and draw on that frame rather than create a new one.  There is a quick moment when I run into this that my mind races to consider whether I should go back into Preferences and turn that auto-syncing of xsheet frames off.  The workarounds are plentiful enough however so I just fix the cell to the desired state and move on.

**Comment by DarrenTea** [comment]
We wouldn't expect to erase from a new drawing - Agreed
We would expect to erase from the current drawing - Agreed
We might expect to be able to draw on the current drawing - That's my point. I do expect this. It's not hard to tap the INSERT key to make a space and draw in a blank area, starting a new drawing.

You asked for more details. I don't think I've really got any. It's just when I'm using the cursor keys to move between frames and without looking up at the timeline, I erase part of the drawing, which work, and then start drawing the replacement line and suddenly the page goes white and I'm drawing in a new drawing! If you couldn't erase on the extended drawing, this wouldn't show itself, but you can. That's what I was finding frustrating. But I've turned the preference off now, so I'll manage my own drawings on the timeline.

**Comment by RodneyBaker** [comment]
I'd want to look more deeply at what you are outlining because there is definitely something there that needs massaging.  I *usually* prefer the sync of level strip to xsheet that this feature allows.  It's those odd moments when we are in the creative flow when you suddenly realize something has gone wrong that brings us back to reality.  

I would recommend closing this because what we are experiencing is part of the feature (which can be turned off) and diving deeply into a discussion on the forum where videos of the current process can be shared and explanations of desired workflow can be recommended.

**Comment by DarrenTea** [comment]
Sure. I'm happy to close this now that I fully understand the feature. And if anyone comes across this issue in the future, I think there's enough in the comments to describe alternatives.

**Comment by gab3d** [comment]
@RodneyBaker 
"...I find myself wishing there was a Shift + draw addition that would allow me to maintain the current frame..."
I could agree with that option! 👍

**Comment by Orphanlast** [comment]
I second the Shift+draw option
