### ISSUE TITLE
Vectors are not precise; Does not detect, or wrongly detects, overlap sometimes. 

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#1773]
This is a pretty common issue that I'm sure everybody already knows about, but not entirely sure if it's been mentioned before or if it's already being worked on. If a thread mentioning this already exists, please either merge or delete this one. 

I like the fact that vectors don't have to be closed, and merely need to overlap to put Fill colors in, coz it allows you to draw fast and work fast. However, there are times that the overlapping is so imprecise that it actually ends up slowing you down, hence why I either have to resort to turning vectors into raster just to color or manually mess with the vectors until they're "just right" and do it blindly because I can't predict how the algorithm detects closedness. 

Generally, sometimes the vectors detect something to be closed _even if_ nothing is overlapping, and sometimes when vectors are overlapping it still doesn't detect them as being closed. As a result, sometimes I can't seem to paint into the closed are, and sometimes OT assumes that this area is part of an adjacent closed region. 

These issues sometimes get resolved when I simply save and re-open the scene file, but more often than not I have to manually mess with the lines and try to clean them up (at worse having to zoom in and use the tape-tool to definitively close vectors to color on, risking strokes where I don't want). 

The reason I like working with vectors is because it seems pretty intuitive to believe vectors to be precise, especially for coloring, leaving no gaps or spots uncolored like it happens in pixels — plus, I could take advantage of the auto-inbetweening tools. 

If we can find a way to fix this, it can save a lot of time working.

**Comment by RodneyBaker** [comment]
Yes, this is a duplicated issue and known problem.

In drawing just now I couldn't get an area not to fill at all no matter what I did.
It can help to capture specific instances that way there is a specific area to focus on.

If I remember correctly a common issue with many programs is that when one line intersects itself multiple times filling inside the line can be difficult because technically only one 'inside' of that line and therefore that area just outside that filled area (created by overlapping the same line) is 'outside' and therefore recognized as outside the shape.

Fills for me have not been a problem since the maximum gap feature was added so perhaps you can crank that setting up and confirm what happens.  If you aren't using a high setting on that you'll want to add that to your workflow.  That feature mainly deals with gaps so... shouldn't particularly care about overlaid lines but... for what it's worth.

If precision is required you might want to draw in Toonz raster and then immediately convert to vector.  I added 'Convert to Vector' just above the xsheet as a command in the xsheet toolbar for that purpose.  If your lines are just quickly drawn black lines that can be a great timesaver.  The only downside of that methodology is that we still need to delete the original Toonz raster level so it'd be nice if there was a Shift + launching option that would delete the original immediately after the conversion.  On the plus side, if anything were to go wrong we can go back to the original and try again.

Although this is a duplicate, recommend keeping open long enough to better define the problem.  A quick search didn't turn up the duplicate report.

**Comment by jpturcotte** [comment]
Is the "maximum gap" feature available in the official v1.2.0 or just in OTX?

**Comment by RodneyBaker** [comment]
I DO NOT see the feature in the v1.2.0 release.
It most definitely needs to be added

**Comment by artisteacher** [comment]
I’ve found that using the “replace vectors with simplified vectors” command resolves fill issues the majority of the time. The only problem is that it can impact how well the inbetweener function Works . I also discovered recently that in certain circumstances, using the iron tool can fix the problem (ie. If there’s a very slight overlap of the endpoints or size disparity in the endpoints causing the fill to fail). 

I am really looking forward to the maximum gap feature being merged!

**Comment by tushantin** [comment]
Hmm, thanks for referring to the original thread, I did not find it earlier. And yes, I'll give the simplified vectors feature a chance for a possible work-around. And while I believe the Maximum Gap feature could potentially be a great workaround for this too (and I'm really grateful for everything that Shin and Turtletooth are doing) but I think there may be an algorithmic error deep in OT's code itself in the way it manages vectors. Otherwise overlapping should have considered regions to be closed anyway.

**Comment by jpturcotte** [comment]
@tushantin Do you still have this problem in the latest nightly?

**Comment by artisteacher** [comment]
The maximum gap feature makes a huge difference! It would be great though if OT could remember the maximum gap size after switching between levels.

**Comment by tushantin** [comment]
@jpturcotte Hmm, how do I try the Nightly on Ubuntu?
