### ISSUE TITLE
Loss of drawings when using Vector Brush with Frame Range (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1778]
When Vector Brush with Frame Range creates a new cell ("Use Xsheet as Animation Sheet" is on), undo leads to loss of drawings.
![ezgif-3-e7f312b2f2](https://user-images.githubusercontent.com/25724133/35599761-04e421dc-0633-11e8-88d2-bd4e219e35d7.gif)

**Comment by RodneyBaker** [comment]
This may be related to an undo bug that (I believe) has been reported.

The problem there is that Undo is skipping the first undo and then undoing the previous action.
So (if related in your case) it would be skipping the first action and undoing the second which is that of removing/undoing the drawing.

You case looks a little more complicated than that but Undo is certainly a common factor.
I'd be curious to see if your case still prevails after the Undo problem is fixed.

**Comment by RodneyBaker** [comment]
This problem is still valid as of v1.4RC although there are workarounds.

The primary workaround is to ensure we are drawing on actual frames (empty or otherwise) so that undoing doesn't delete the level which then is lost as a xsheet reference.The new feature that allows users to add frames (via Alt +D shortcut) can make short work of creating empty frames to draw on.

It seems to me that any process where Undo triggers the deletion or removal of a level/file should be accompanied with a popup query/warning 'Do you really want to remove this level from your Scene?'.  Then the user can learn not to use Undo in those cases.

**Comment by RodneyBaker** [comment]
This issue is now being tracked via #3070.
Thanks @manongjohn
