### ISSUE TITLE
Crash loading scene

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#1779]
That's kinda scary bug. It seems I can't open my scene anymore. Luckily I can access to my frames via Load Level. I am saving as another scene and same thing happens again when I try to load the new scene. This happened on 2 scenes so far. Other scenes are working fine.

I m on macosx. Using the latest opentoonz version. (tried nightly version, and morevna edition as well)

Thanks

**Comment by norrinra** [comment]
I tried loading the scene from first splash screen, via browser and from load scene option. None of these worked. 

It only opens the scene by  "Open recent scene file". That's a strange bug.

**Comment by shun-iwasawa** [comment]
> It only opens the scene by "Open recent scene file".

You means that the scene file itself seems not to be corrupted, right?
If so, can you please post the full file path of the scene? I'd like to try reproducing the same situation.

**Comment by norrinra** [comment]
Nope, scene files seems fine I guess, the other scene which has the same error also can be opened by "Open recent file".

Full file path is : Applications/OpenToonz/OpenToonz_1.2_stuff/sandbox/scenes/cx.tnz

Thank you.

**Comment by norrinra** [comment]
You can find the crash report below if it can help to understand what is going on.

[treport.docx](https://github.com/opentoonz/opentoonz/files/1680318/treport.docx)

**Comment by shun-iwasawa** [comment]
Thank you for sharing the information.
According to the crash report, it seems that OT crashes when trying to load MP4 level in the scene by using ffmpeg...

**Comment by norrinra** [comment]
Yeah, I opened the scene file from "recent". Then removed the mp4. Everything goes back to normal. Thank you so much.

**Comment by ReaperSykko** [comment]
Hello im having the same problem… i figured that its because i saved the scene with a mp4 in it, recently i did other project with mp4 saved in them and they still loaded with no problem...so i thought they fixed that , but today i forgot to remove a mp4 layer from the project i was working on and i saved , and now i cant open it anymore….. please dont tell me my work is lost , is ther a way to retreive it? or to fix this?

**Comment by norrinra** [comment]
@ReaperSykko you can just remove ffmpeg plugin temporarily and open your project.Your work is not lost :)

**Comment by ReaperSykko** [comment]
@norrinra oooh thank you so much… ill try this first thing in the Morning , been kinda bumed about all this lol , hope it works ty.

**Comment by ReaperSykko** [comment]
thank you , i found my work , ill remember to remove the mp4 before saving, you think they ever gona fix that so that you can fave with an mp4 Inside or thats just how the program is? also when i want to render how do i put the ffmpeg path back? do i have to redownload ffmpeg? i did not right now its path…

**Comment by norrinra** [comment]
No problem, you can note the path before deleting it. Then you can re add to there. You don't have to re-download ffmpeg. I am not sure about the fix, it doesn't happen to me since long time so I thought it fixed. You can try to download latest nightly release from here if you're using older version..
 
https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by ReaperSykko** [comment]
oh so ther is a new version , i did not know , thanks  , if i download this version will my work be saved and ill be able to continue working on it on the new version? sorry im super new to all this

**Comment by manongjohn** [comment]
I have a scene that has an mp4 in it and never had any saving and loading problems because of it. I also have an older version of FFmpeg running.

Perhaps there is some bug in the version of FFmpeg that you have?

See if you can find and install an older version of FFmpeg to see if that's why its crashing.

**Comment by ReaperSykko** [comment]
i think im gona have to re download ffmpeg anyways since i lost the path , do you have a link to the latest version? also somthing wierd hapened i cant add mp3 music to my scene anymore.

**Comment by turtletooth** [comment]
mp3 relies on ffmpeg also.  So if you removed the ffmpeg path, OpenToonz can longer use mp3, mp4, gif or webm.

**Comment by ReaperSykko** [comment]
lol i see thanks.

**Comment by artisteacher** [comment]
I have a relatively recent version of ffmpeg and I’m not having any issues saving scenes with mp4s.  I would check & make sure that your ffmpeg directory has both ffmpeg and ffprobe when you add it back. 

As a workaround, you could merge the video onto an empty Raster level with the same number of frames. Then you could remove the video permanently. As audio from an mp4 isn’t used in OT, using an image sequence instead doesn’t lose any functionality.

**Comment by RodneyBaker** [comment]
This issue appears to be resolved.
@norrinra @ReaperSykko Please let us know if this is not the case.

**Comment by Happydays11** [comment]
this scene crashed while I was drawing. When I try to open it, opentoonz immediately just shuts down. All other scenes open fine. Can anyone please help.
