### ISSUE TITLE
Can create vector & raster brushes while on the wrong level type, then can't use them

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#1783]
If you create a vector level, you can still see the raster MyPaint brushes. You can set one up, but then can't use it. If a level palette is just for that level, you would never want this.

The raster tab should disappear when looking at a vector level and the vector tab should disappear when looking at a raster level. The Texture tab appears to be used for both level types.

Also, when you select on a vector level frame called background, the header on the palette says, "Level Palette: Background". If you select on a raster level called background, the header says, "Level Palette: Raster Drawing Palette" and the palette appears to be shared between all raster levels in the current project.

**Comment by gab3d** [comment]
yes, I agree.
it is confusing, and it doesn't make any sense (any use case?) to be able to create style-types that don't match the current level type.
I think it'd be good to filter the displayed style types to the ones matching the current level type.

**Comment by RodneyBaker** [comment]
> when you select on a vector level frame called background, the header on the palette says, "Level Palette: Background". If you select on a raster level called background, the header says, "Level Palette: Raster Drawing Palette" and the palette appears to be shared between all raster levels in the current project.

You''ll want to split that off into a separate issue.

Regarding the vector level with MyPaint brushes showing... I don't quite follow you there.
Id'd be good to have some more information.  
Perhaps a video walkthrough of what you are experiencing.

In my experience the raster palette disappears and is replaced by a vector palette when I select a Vector level.  In rereading your post (especially the second paragraph) and playing with the settings in OT I perceive you are specifically talking about the tabs.  There has been some other discussion related to that in particular thoughts that lead to the current organization which was done to get us most of the way to what you desire (context sensitivity).  

To some degree we will likely always run into issues related to the differences between the three level types and I would suggest a discussion related to that be taken up in the OpenToonz forum where that can be pit can be dug down deeply.  It very well could be that every object (in the code) might have a assignment that allows all other objects and processes to know where it is 1) compatible 2) needed.  This very likely already exists but needs to be tweaked.

There is some internal logic that suggests where things can be translated for use with rasters, some with Toonz raster and some with vectors and the same goes for moving the other way.  

One solution might be to designate equivalents in similar fashion to styles 0 and 1 on every palette.  If vector is active then the equivalent brush in a Toonz raster palette will be...?

I guess what I'm saying is that at the root of the issue is the differences between the three level types. Having brushes appear or not appear doesn't necessarily take us to the underlying processes and constraints.

There is an approach in programming that suggests any problem be fixed twice; once for the current problem experienced by the user (your consideration) and then again for the underlying issue that caused that problem in the first place.  It is that second 'fix' that intrigues me because it will lead to a better experience in other cases for everybody.

While it would be useful to have only the correct tabs appear for the specific level types it can also be seen as a means to teach users the difference between those level types... what works with one... what works with another... etc. all while seeing the same tabs in the style editor for a common UI... one that doesn't constantly change.   Hey, I just created a brush... where did it go?  Query:  What Level type are you using?   Huh?  Level Type?  I'm just drawing and my brush freakin' disappeared!  Can you select some other cells in your xsheet and tell me if your brush returns while selecting them?  Right.  Oh, it's back but now my other brushes have disappeared.   Etc. Etc.

All this for what it is worth.
I'm probing the idea to better understand it.
I am definitely a fan of context sensitive menus.

**Comment by DarrenTAnims** [comment]
Regarding your last paragraph, I think having tabs grey out when you can't use them would teach them what they can do. It makes no sense to show raster brushes and to allow the user to create and edit them when you're working only with vectors and vice versa. Plus it leads to new users constantly asking the same question about why things don't work. I understand that the program is evolving, so it wasn't designed to be the way it is and it'll change in the future, but this seems like an obvious change that needs to happen for a professional piece of software.

**Comment by gab3d** [comment]
@DarrenTAnims 
Agreed.
For example, the fact that you can select and edit a Style of type "Raster" (MyPaint) inside a Vector level Pallette, without a single warning, is not a good practice, to say the least.

**Comment by RodneyBaker** [comment]
I"m not a programmer but am trying to imagine what success might look like in the code.

Following the line of thinking that tabs could grey out (rather than disappear) I will imagine that each of the tabs would need to test to see if they were active (i.e. not gray) with gray (inactive) being the default state.  I will further postulate there needs to be a means to update the state of all tabs (i.e. the Style Editor window) if/when the user changes the focus from one level to another.  I will therefore conclude that an active state needs to be continuously monitored to determined one of four (or five) level states the user will be in at any given time.  The first state (zero) is reserved but can be used as a transitional state from which to read and write the others or to temporarily hold the last state (for undo purposes?).  State 1 would be the current state.  State 2 would be red (vector), State three would be green (Toonz raster) and State 3 would be blue (raster).  So this state could be captured and traced via x,y,z style matrix or via r,g,b equivalent.

That may seem to be overkill for just having tabs appear active or inactive but I'm trying to think deeper to where that same basic scheme might apply to other aspects of working with vector, toonz raster and raster (level) types.  For someone trying to debug complex relationships between those three having a graphical representation of what any given state looks like might be helpful.

**Comment by DarrenTAnims** [comment]
It's more standard to grey them out, rather than making them disappear with you being able to switch between layers quickly. Disabling and enabling tabs when you change "columns" isn't normally a hard thing to do, codewise, but I know that the code in OT is very old, so it might take some effort. But regardless, it's what the user would expect, so makes for a bad experience atm.

**Comment by gab3d** [comment]
I agree to grey them out is also a good practice.

But even if they stay the same as now (active at all times), at least OT should warn you when you select a style type that does not match the palette type you are in. That shouldn't be too hard to do, as MyPaint brushes can only be used with Raster type levels, and that level type have only a single common palette, so if this common raster palette is not active, then the user should be alerted when trying to use MyPaint brushes.

**Comment by RodneyBaker** [comment]
I'll throw this into the mix as general information.

To any user that doesn't use specialized brushes these level related incompatibilities will not be a problem. 
 The standard palettes and color swatches work in any level.
It is only when we move into the specialized brushes that problems are experienced.

It is somewhat unfortunate that gaining MyPaint brushes has brought this problem to the surface.
MyPaint brushes are awesome.

**Comment by artisteacher** [comment]
I’m all for context sensitivity - the toolbar could really use it too. This was actually an issue before the mypaint brushes due to the texture and custom styles. @turtletooth’s consolidation of the tabs already really helps. 

In terms of the style editor, I think there was a concern about loading palettes from other levels and not being able to change the brush type if the style editor was made completely context sensitive. If this is a concern, maybe the style editor needs a setting to “reset style to level default” (without changing the color). Then making the tabs inaccessible for other level types should be fine.

The style editor already seems to have the basis in place. When an empty column is active in the Xsheet, the style editor does not display all of the tabs. Whatever happens, you should not be able to create a new raster style for a vector or toonz raster level (or vice versa).

**Comment by RodneyBaker** [comment]
As a lower priority workflow enhancement this is slipping to 2019 development cycle.
