### ISSUE TITLE
FX Schematic hangs, freezes and crashes very often OSX

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1803]
I'm using the 1.2 OT version and find working with the FX Schematic very unstable. Most of the times it crashes or hangs/freezes when applying an effect and/or particles. For example, I can apply a simple blur and start working and adjusting parameters, but it quickly becomes unstable. It also happens when I try to use the preview icon with effects applied (most of the times the rainbow spinning wheel appears and I have no solution to force quit). 
When I try to render to RAM, many times nothing shows.  

Hope this description helps. Thanks!!

**Comment by artisteacher** [comment]
@DotSilva if you have any reproducible steps to get a crash, or crash reports, those could be helpful for the developers.

I definitely get occasional crashes when using fx in OSX. The crashes are often not reproducible on demand. Saving before previewing or before/after making changes to the fx, sometimes seems to make crashing less likely.

Playing/scrubbing an animation that uses particles, with preview on in the viewer does really regularly result in a crash.
[particle_play_preview.txt](https://github.com/opentoonz/opentoonz/files/1724589/particle_play_preview.txt)

**Comment by DotSilva** [comment]
Ok, so here it goes:

Particles:
- Create a Level with a Drawing;
- Create a Particle System (Rain, for e.g.);
- Attach the Drawing/Level to the Texture of the Particle System;
- Click on the Preview Icon
- It takes a considerable amount of time to preview just one frame (when it even shows a preview) and when clicking the play or loop button. When I try to render to RAM, I get a blank preview.

Applying an Effect (Blur, for e.g.):
- Unfortunately cannot always reproduce the exact steps. But it happened some times when, after applying an effect and pressing the play/loop button, toggling the preview on and off. 
- It also happens when I try to render to RAM. It freezes and the rainbow spinning wheel appears and I have to force quit.

**Comment by DotSilva** [comment]
An important update.
I've been testing working with particles a little more and found out that they became much more unstable when using a Raster Layer as the Texture.
In opposition, using a Vector Layer as a Texture is way more stable (although it still crashes without apparent reproducible steps). I can, however, preview the animations without much problems.

Thanks a lot for your attention!

**Comment by DotSilva** [comment]
In the latest build, using Raster Layers as Textures doesn't crash or hang as in previous builds. However, it takes forever to render/preview the result as opposed to using Vector Layers (that works as expected). Hope it helps! Thanks!

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
Original reporter has deleted their github account.
Original reporter also added that latest build (circa March 2018 no longer crashed or hung as in previoius builds.
