### ISSUE TITLE
Bokeh Iwa FX hangs/freezes when previewing animation OSX

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1854]
On the latest nightly build, the Bokeh Fx is working but when I assign keyframes to make an animation with the effect and try to preview it, Open Toonz hangs (spinning rainbow circle)  and I have always to force quit.

Thanks!

**Comment by RodneyBaker** [comment]
Can someone on OSX confirm this preview hang/freeze?

**Comment by artisteacher** [comment]
I'm not getting a hang or freeze - at least with 10.11.6. I can try on High Sierra this weekend. It definitely is processing heavy, because it does cause #902.

**Comment by RodneyBaker** [comment]
Recommend review for possible closing as covered by other reports.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and as an abandoned issue.
Original reporter has deleted their github account.

It should be noted that previewing of any scene with intensive FX will slow processing dramatically.
In order to improve this for specific instances recommend users provide a project file that can be tested and benchmarked for the purpose of discovering bottlenecks and for implementing optimization.
