### ISSUE TITLE
Levels moving on their own without me moving them.

### ISSUE THREAD

**Issue by Squidney3000** [opentoonz/opentoonz#1858]
I'm trying to make a cutout animation, however I'm coming across several issues. For starters, the arm of my robot begins to levitate in the air for seemingly no reason. It was staying put for most part, but then all of a sudden it starts to do this. I try deleting keyframes, but to no avail. Has anyone had this issue before, are there any solutions or ways to prevent it?

(left picture is frame 1, the second is frame 75
![image](https://user-images.githubusercontent.com/27929761/37228306-c73dde00-23a5-11e8-8763-2f71122a2d90.png)

![image](https://user-images.githubusercontent.com/27929761/37228337-de0e56fa-23a5-11e8-858e-be17d3a358a5.png)

**Comment by RodneyBaker** [comment]
NIce work!

You should post issues like this in the OpenToonz forum where they can be investigated and resolved.  It's unlikely this is a bug.



I will guess that this a rotation but that the center of the level isn't placed where you need it to be.
Alternatively it could be an interpolation issue but we'd need to know more about your setup.
Getting a good look at your Function Editor and the keyframes of that particular drawing/level would help considerably.

**Comment by Squidney3000** [comment]
This is embarrassing, I've never used the function editor. I've just been going off of what ever tutorials I could scrape up. I never understood what the function editor was for so I never bothered with it. 

As for the key frames, I can send you some pictures of that. I'm having even more issues with parts moving. 

![image](https://user-images.githubusercontent.com/27929761/37235288-1e61155e-23c3-11e8-984d-3bae420a2266.png)

Heres this frame, the torso is nice and striaght, however

![image](https://user-images.githubusercontent.com/27929761/37235319-4a2d0922-23c3-11e8-9461-d3a6472ef30d.png)

theres no key frame here and yet the torso is tilting, even though the frame after that also has a rotation of 0 degrees.

![image](https://user-images.githubusercontent.com/27929761/37235335-6a528e48-23c3-11e8-813e-bd78e188ee44.png)

**Comment by RodneyBaker** [comment]
Thanks for providing more information.
Unless something is very amiss drawings won't move so I'm confident we can sort your problem and get you where you need to be.

As for thing moving where there are no keyframes...
Drawings will move between keyframes based on the interpolation set between those keys (linear, ease in/ease out, etc.) so that would account for movement on frame where no keys are set.

The default interpolation between frames should be linear so I still suspect the center of your drawing is not placed where you want the arm (or any other object to rotate or move).  We'd be able to tell this in an image like you have posted above except that you have a different level/image selected in the xsheet so it is showing the center point for that (as opposed to the arm).

If you can share the .tnz file I can probably look at that even without images and determine if my theory here is true.  My email is:  rodney.baker@gmail.com or... you can zip it and upload it here (as github won't let you upload .tnz files).

**Comment by RodneyBaker** [comment]
If you look at your first posted images and see where that pink circle and registration marks (the Center point) are you can see that it is in a very different location than the images in your second second post.  This tells me that your arm has been moved upward from where it would normally be and that the default rotation is there at that point (that pink center symbol).  

We need to resolve that center point positioning.

**Comment by RodneyBaker** [comment]
I looked at the file for this and don't see anything worthy of a bug report.
It appears to be an interpolation between keyframes.

Recommend closing this although we can add more info to the topic as we discover more.
I'm working with Squidney to and will stick with it until resolved.

The discussion can also continue in the OpenToonz Forum.

**Comment by Squidney3000** [comment]
I think the problem is solved, I started the project over again and did what you said, I haven't had any issues so far. Thank you so much for your help! I really appreciate it!

**Comment by Orphanlast** [comment]
@Squidney3000 I have tutorials on the function editor.

https://www.youtube.com/watch?v=QxmX0CV-WrQ

https://www.youtube.com/watch?v=EUq8rvnREAI&t=9s

Now, I could focus more on it. But I'll have a crowd funding project that will revamp the user interface for opentoonz and I'm going to be remaking all these videos later on when that gets introduced into opentoonz
