### ISSUE TITLE
(Discussion) Slow Performance Issues

### ISSUE THREAD

**Issue by adamearle** [opentoonz/opentoonz#1864]
OpenToonz slow right down in vector and raster after less than ten drawings. Its so slow in fact I am thinking about switching back to paper because I can draw and animate way faster

How can we bring this viewer into the future?
How can we make it ready by the middle of the year?
What is it going to take?
How much is it going to cost?

Can we have a very real conversation about this instead of its alot of work and dismissing it. 
Perhaps we can make this a github Kanban so we can really start to nut this out and make it happen

Thanks guys 

Ad  :D

**Comment by artisteacher** [comment]
Maybe if we can narrow down what is causing the lagginess, it will help the developers resolve the issue. 

What release are you using?
What dimensions/resolution are your levels?
Do you have the same issue with Toonz Raster levels?
Could you share an example of a typical vector level that slows things down?

Personally, I experience OT slowing down the most when I am working with loaded or imported video. The videos are usually just Quicktime screencaptures that I make into animated gifs for student tutorials. It would be amazing to not have this painful level of lag!

**Comment by RodneyBaker** [comment]
I just went through Preferences and adjusted a lot of things with speed and optimation in mind.  I posted some of the results to that in the OpenToonz discord.  OT can work very fast so it's important to get into specifics and those will often rely on the settings on the local machine.  For other optimizations to work those should be sorted also.

@artisteacher has the right idea with detailing specific information about OS, OT release, resolutions etc.

I'd love to have an actual Scene file/Project that folks claim to have lagging.
Simplicity is the ultimate optimization and it's amazing how quickly simple projects can get out of hand.

**Comment by adamearle** [comment]
You can see what I am looking at on the discord under "keyframing"

https://discord.gg/pCgQeET

**Comment by adamearle** [comment]
also guys I am some answer
MP Raster and Vector are drawn at an A4 resolution 120 Dpi

What release are you using? at the moment I am testing the new OTX from turtle tooth and everything seems to be running swimmingly for now with a project rebuild operating at A5 resolution and about 120 DPI
I have changed the preview setting resample Balance to "Mitchelle" only because of thats what I use when I am rending in Maya

I have also checked "Apply to Shrink to Main Viewer" I am not too sure what this does but I am no am wrong to "assume" that it is reducing memory overhead while animating if the viewer is small on screen,

Do you have the same issue with Toonz Raster levels? I haven't trialed OT raster level and to be honest am not really interested in it.

I am also working with 20 layers and to be honest that is not a lot really.

I have to say that if Hayao Miyazaki was using this software at his studio and it was actually optimized to perform I think we would be seeing very different animations on screen and I think Miyazaki would give up on his purist argument + we would probably have more films from him as well.

I have studied drawing since I was little and didn't take it seriously enough till I was 28 when I fell madly in love with the power of the line in animation. I am very familiar with how important the line is when it comes to drawing. 

Though when we have tools like My Paint integrated into OT and we can't operate those tools to see them in the glory that they have been created in, then we may as well be drawing with Microsoft paint.

**Comment by adamearle** [comment]
after we work out what direction we need to travel in I am going I am thinking about putting together a Kickstarter that will push everywhere so we can get stuuuuuuuf done. My intention will be to target the big boys and get done,

**Comment by adamearle** [comment]
So the software that i have running when i am using OT is
 - Chrome
 - OT
 - Thunderbird

**Comment by adamearle** [comment]
My Computer specs are not that great but this what OT has been tested on

Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz (I know its old)

Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz

Surface Pro Computer specs:
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor:  Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz

Surface Pro 4 Computer specs:
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor:  Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by manongjohn** [comment]
Have you verified that OT is using the GPU on your graphics cards while you are drawing, especially on the 1st 2 machines?  

Have you always had this problem, even with the previous releases? Could it be something that was introduced in 1.2 that is now affecting you where it might not have before? If so, perhaps we can try and track a nightly where it started happening.

**Comment by adamearle** [comment]
I am just wondering if had a chance system in place like Natron Kdenlive or Blender if we could get better playback?

**Comment by adamearle** [comment]
the problem has always there.
This going to sound super dumb but, "How can I tell if my GPU is being accessed".
I have plenty of ram and disk space I know that the motherboard is a bit old?

Am I asking to much of OT?

**Comment by adamearle** [comment]
oh also on the previous release of there was this problem.

I will be testing the OTX version tomorrow with our Storyboarding setup.

Ad

**Comment by manongjohn** [comment]
@adamearle Your 2 machines have NVIDIA graphics cards, and OT usually does not trigger GPU usage on those types. You may be using straight CPU which could explain the lag and why you've had this problem even with prior releases.

In order for GPU to be used on NVIDIA cards, it normaly needs to detect that software is using openGL. When it can't, the other way is to create a 3D profile in the NVIDIA's card settings for the given application and set it to maximum. You will likely need to create a profile for OT.

There are some freeware GPU monitors you can download to verify GPU usage.

You can also try going to the NVIDIA site and dowoad the NVIDIA Control Panel and NVIDIA System Monitor unless you know its been installed on your machines already.

The monitor will check GPU usage and the control panel will get you access to the card's setting so you can set up a profile for OT which fixed my lag issue.

Please try that and see if that helps any.

**Comment by konero** [comment]
Windows 10 can show GPU usage in task manager since the 1709 update.

Toonz has always used the GPU even when I have multiple GPUs, it will render on whichever GPU the display is plugged into. But was OpenToonz optimized specifically for Quadro drivers I wonder?

OpenToonz doesn't lag for me except when drawing, which gives me the same as #1816. So we do all our drawing in Clip Studio Paint, Krita and of course on paper and then paint the images with Toonz.

**Comment by adamearle** [comment]
Hey guys thanks for the heads up.

I am just about to head to bed and I saw this. All I can say is that sounds like the that could be it. Oh, my goodness dare I say I am looking forward to testing OT out tomorrow.

So as for storyboarding in the studio, we use A5 and I am guessing that there will be a sweet spot between 120 Dpi and 300 Dpi.

I am curious to know though if there what kinda machine I should be getting for running OT Now and I am kinda thinking that there really should be something inside of OT that at least suggest for you to do some tweaking like this.

God knows I would never have thought of it.

What can we do to prevent there from being more Adam's out there with this experience?

Slumberland for me. Night guys and you thanks, I will check it out tomorrow at work.

Oh yeah, any ideas on how to make levels a different formate other than .tiff because I would rather be working with .png. The file sizes in a rough dodgy test seem to be about half the size.

I think that this will help with a speed up as well.

night

Ad ;D

**Comment by adamearle** [comment]
Ok boys I have the whole afternoon to play and see if this is going to work. Yeah haaaa.

So a quick 5-minute test and things are looking pretty good and then speed up has been massive.
So I think NVidia card setting was the thing slowing OT down on the machines.

I asked artist do some other test as well and I am getting the same feedback. so it all seems to be positive.

OT maybe our new Storyboarding software of choice. Good by Storybaord Pro.

So that was the quick test, 

Now I will spend the whole afternoon drawing and see how it turns outs.

**Comment by shun-iwasawa** [comment]
I've investigated the cause of slowness and here is an interim report - it seems to involve a mix of factors such as listed as follows:

### 1. Slowness due to QOpenGLWidget
**Description**
- From OT V1.2.0 all OpenGL widgets are moved from deprecated `QGLWidget` to `QOpenGLWidget`.
- According to [this](http://doc.qt.io/qt-5/qopenglwidget.html#differences-to-qglwidget) and [this](https://bugreports.qt.io/browse/QTBUG-49620) `QOpenGLWidget` is backed by a framebuffer object. On the other hand `QGLWidget` uses a native window and surface. It may be a cause of slowness in some devices but I'm not sure.

**A span of influence** 
- Not sure but probably the larger the Viewer is, the slower it gets.

**Possible solution**  
- [This](http://blog.qt.io/blog/2014/11/20/qt-weekly-20-completing-the-offering-qopenglwindow-and-qrasterwindow/) and [this](https://image.slidesharecdn.com/modernopenglandqt-160128220040/95/convert-your-legacy-opengl-code-to-modern-opengl-with-qt-9-638.jpg?cb=1454018635) offers `QOpenGLWindow` as an alternative, which is not backed by a framebuffer object (by default) and with better performance. Since `QOpenGLWindow` does not inherit `QWidget` you need to write some codes to make the same functionality as `QOpenGLWidget`.
- According to [this](http://doc.qt.io/qt-5/qopenglwidget.html#relation-to-qglwidget): 
> Most applications do not need incremental rendering because they will render everything in the view on every paint call. In this case it is important to call `glClear()` as early as possible in paintGL(). 

### 2. Slowness due to calling glDrawPixels
**Description**
- In [here](https://github.com/opentoonz/opentoonz/blob/00105e36cd1ce805aef04e90b5509b5cd6154379/toonz/sources/toonzlib/stagevisitor.cpp#L639-L640) the viewer calls `glDrawPixels` for rendering raster images, which is said to be quite slow.

**A span of influence** 
- When using Toonz Raster or Raster levels. The larger size on screen the raster level is displayed, the slower it gets.

**Possible solution**  
- Using textures or PixelBufferObject instead of glDrawPixels may enhance the speed.

### 3. Slowness due to smooth sampling in Toonz Raster Brush
**Description**
- I found that when drawing with the toonz raster brush mouse positions are interpolated [here](https://github.com/opentoonz/opentoonz/blob/975eb1fa6fad3476ebbbafadf86814d4fea7dc05/toonz/sources/tnztools/brushtool.cpp#L750-L786). This function adds 8 extra samples to make smoother lines by consuming some amount of computation time.
- Note that this smoothing process is NOT related to `Smooth` property of the brush tool.
- **This interpolation seems to be a main cause of the jagged corners reported in #1816 .**

**A span of influence** 
- When using Toonz Raster Brush.

**Possible solution** 
- IMO we can just skip this interpolation. I think it would better to reduce the computation time and get more raw samples than to compute lines by interpolation of small amount of raw samples. To obtain smoother result, we already have the `Smooth` property in Toonz Raster Brush.

### 4. Slowness in Toonz Vector Brush
**Description**
- Drawing on the vector level which already has large amount of control points causes slowness in response. It can be easily reproduced by applying the custom vector brush as it will replace strokes by a brush shape with fairly large amount of control points. 

**A span of influence** 
- When using Toonz Vector Brush.

**Possible solution** 
- Not yet investigated.

**Comment by norrinra** [comment]
@shun-iwasawa Thank you so so much. I hope it's not that hard to apply possible solutions. Can't wait to test it.

**Comment by shun-iwasawa** [comment]
!! I found another measure to improve the response.

**Comment by RodneyBaker** [comment]
@adamearle how is the response in OpenToonz now.
Are you still experiencing any lags and if so can you identify where and when those happen?

**Comment by manongjohn** [comment]
I was recently looking into a rendering issue a user was having. I had requested the entire scene to attempt to duplicate the problem so I can see what the problem was.  Though I could not reproduce the problem with the scene, I did find a **huge** performance issue.

The scene comprised mostly of 6 standard Rasters, 1 Toonz Raster with a Mesh for each.  When I played it back normally in OT 1.2.x, it played at 2 FPS!  This was on both an older Win 7 and a newer Win 10 machine.

What I found even more surprising was when I played the same scene back in 1.1.3 on the same Win7 machine. It played at 24 FPS!

I know we've had a number of complaints about slowness which we've attributed to how rasters are rendered to the screen. As I tend to work primarily in Vectors, I don't see it as much so I never really understood how bad this was. This type of performance is a killer and frankly unacceptable.

Something really needs to be done about this.

**Comment by shun-iwasawa** [comment]
@manongjohn Thank you for the investigation.

> The scene comprised mostly of 6 standard Rasters, 1 Toonz Raster with a Mesh for each. When I played it back normally in OT 1.2.x, it played at 2 FPS!

Which do you think that the slowness is solely due to rasters, or ones in combination with meshes?
It would be helpful if you can share the problematic scene data.

**Comment by manongjohn** [comment]
@shun-iwasawa I took out all the meshes and it played at 24 FPS. However, without the meshes, i just have mostly single frames held with no movement so rendering wouldn't be as intensive. Even zooming timeline in/out is significantly lagged until I take the meshes out. It is similar behavior to #2016. 

As this is isn't my scene, I'll need to get permission from the user to give the project to you for investigation. I'm sure he'd prefer I send to you privately. Let me see if I can get permission first.

**Comment by shun-iwasawa** [comment]
> Even zooming timeline in/out is significantly lagged until I take the meshes out. 

Sorry for the late notice, but the slowness when zooming timeline seems to be because you are calling `notifyXsheetChanged()` in `XsheetViewer::zoomOnFrame()` [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/xsheetviewer.cpp#L1750).
`notifyXsheetChanged()` will emit a signal which invokes the viewer redraw. I think you don't need to call this function since it doesn't change the xsheet contents itself.

> As this is isn't my scene, I'll need to get permission from the user to give the project to you for investigation. I'm sure he'd prefer I send to you privately. Let me see if I can get permission first.

Understood. Thank you for your cooperation!

**Comment by turtletooth** [comment]
With all the slowness issues, do you think the switch to qopengl was the right call? It seems all of this happened after the switch.

**Comment by shun-iwasawa** [comment]
IMO switching to QOpenGL was somewhat inevitable for future improvement & maintenance exploiting non-legacy OpenGL features.
I believe that the performance is getting better compared to the moment of the transition. I think we can find some solution for the slowness with meshes reported by @manongjohn as well.

**Comment by manongjohn** [comment]
@shun-iwasawa I have permission to share project with you. Please let me know how to send to you privately.

**Comment by shun-iwasawa** [comment]
@manongjohn  
Thanks. You can find my e-mail address somewhere in `git log` - It's shun_iwasawa@dwango.co.jp .

**Comment by adamearle** [comment]
Sorry guys I have been placed on a 3D project and I am not working with OT right now. Fingers crossed to be back on it again soon

**Comment by bobbybutterfly** [comment]
Status OT 1.3 build May 7: no playback enhancement after update to QT 5.12.3

**Comment by shun-iwasawa** [comment]
@bobbybutterfly Sorry for any confusion but the PR #2608 only updated Qt version for Travis CI. Qt version for the nightly builds remains unchanged.

**Comment by bobbybutterfly** [comment]
@shun-iwasawa thanks for the info:)

**Comment by RodneyBaker** [comment]
This report has seen a  lot of activity over the past two years and it would be good to take stock in what issues currently cause bottlenecks.

I've an eye to close this report and open a new fresh 'Slow Performance Issues' discussion moving into 2020 with the release of v1.4.  Of course along with that would be an assessment of issues raised here so any still needing to be addressed can be moved into the new report.

We could keep this report going but it is not easy to see what the status of the various performance issues raised is and I'd prefer not to minimize/hide comments.

What say you all?

**Comment by RodneyBaker** [comment]
Closing with a goal to reopen a report on Slow Performance Issues verified using Opentoonz v1.4 and above.

**Comment by adamearle** [comment]
Vectors seem to work really well now compared to a few years back. The only issue that really remains now is more so getting OpenToonz to meet modern expected vector standards. Pretty sure the following comments need could be added somewhere else.
