### ISSUE TITLE
Selection Tool problem when applying 3DLUT  

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1873]
When 3DLUT is applied, select, copy and paste the toonz raster image with the selection tool on the same frame of the same level causes the viewer to turn black.

**Comment by RodneyBaker** [comment]
Given that the 3DLUT feature is present in the latest official release this bug may need some more attention.  I had forgotten about the problem but after recommending the 3DLUT feature to others ran into viewer turning black when using the Selection Tool after 3DLUT applied.  I haven't been able to recommending using it any more because of this.

**Comment by RodneyBaker** [comment]
This is still an active issue with same result as described in original report.
