### ISSUE TITLE
zoom factor not present in combo viewer

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#1879]
![2018-03-19_21-26-00](https://user-images.githubusercontent.com/36406840/37630160-b1b8f50a-2bc1-11e8-8a43-f708d6672b4e.png)
the image says it all.

should it be like that?

**Comment by RodneyBaker** [comment]
This can happen sometimes for instance when ingesting SVG images.
But I think you can guess that this is not normal.

If you Right Click and select Fit to WIndow that should put you back in business.
We'd have to know more about your specific setup and workflow to know how to delve more deeply into the issue.

**Comment by age3rcm** [comment]
![2018-03-19_23-15-44](https://user-images.githubusercontent.com/36406840/37632132-6f73097e-2bcb-11e8-98c1-30505f4c2547.png)
i have opened a completely blank project and tried it again.

zoom factor still not showing in combo viewer

**Comment by age3rcm** [comment]
what do you mean by specific setup?

opentoonz version? hardware? OS?

ways to achieve the issue?
i just opened a new project and opened a window of combo viewer

**Comment by RodneyBaker** [comment]
Any information you can provide will help us understand your problem better.

**Comment by shun-iwasawa** [comment]
@age3rcm 
You means that the zoom factor ( % ) does not shown in the combo viewer title bar?
If yes, I think this is related to #1645 .

For now OpenToonz does not show the zoom factor in the title bar under the scene editing mode in most cases (*1) because in the camera stand view mode all the columns are placed in real-scale-based (such as inch / cm / mm) considering their dpi (*2) and therefore pixel-based zoom factor has no meaning.

*1 If you set `Enable Actual Pixel View on Scene Editing Mode` in the preferences, you can see the zoom factor based on the current raster level.
*2 For now you can choose "pixel" as a current unit. In such case the images will be put in pixel-based, regardless of their dpi.

I think #1645 will take care of your problem, showing the current zoom factor based on the current output camera size.
