### ISSUE TITLE
Possible v1.2.1 release

### ISSUE THREAD

**Issue by jpturcotte** [opentoonz/opentoonz#1892]
Hi everyone,
Since the two big issues with the 1.2 release, the blank viewer and brush lag, have now been fixed, I suggest releasing a patch version so that new users can have the best experience without resorting to the lesser-known nightlies. It seems that big changes are coming with the next PRs too, so I think now is the time. I wanted to have the maintainers' opinion on this proposal. Thank you for your time!

**Comment by gab3d** [comment]
If/when a new release is made, please don't forget to update for new strings and warn the translators so they can update them in time for the release.
Thanks!

**Comment by artisteacher** [comment]
It would be great to get the MacOS alias crash fix in for the next release - and if possible the audio toggle for Mac flip books too.

**Comment by shun-iwasawa** [comment]
Thank you @jpturcotte for the suggestion of releasing the next version.
Yes, I agree it's about time to release.

However, for my very very personal reasons I'll be quite busy until mid-April.
(My wife is on schedule to give birth to the second child soon.)
So I would like to set a target date for the release on May.

An estimated scedule would be like;

- The end of April : Feature freezing

- Two weeks for bug tracking & translation update

- Mid-May : Release of a "Release candidate" version (v1.2.1 RC)

- Two weeks for urgent bug fix

- The end of May : Release of v1.2.1

Please note that I newly added a schedule for the RC version release in order to test the software thoroughly.
During the RC period, the installer can be downloaded from OpenToonz website but it will not be notified to users on launch of the software. (i.e. keeping https://opentoonz.github.io/opentoonz-version.txt unchanged from `1.2.0` .)

I would appreciate any comments or suggestions. Thank you for your understanding and patience.

**Comment by jpturcotte** [comment]
おめでとうございます。Of course, I think everyone can agree this can be delayed a bit. Also, I am happy to hear the suggestion to make use of RCs has been accepted. If the contributors can help speed things up and relieve you of some work, please tell us!

**Comment by gab3d** [comment]
@shun-iwasawa 
Congrats man! 🐰

**Comment by shun-iwasawa** [comment]
@jpturcotte I'm sorry to say, yes.

I'm planning to include the following PRs into v1.2.1 if they seems to be OK after reviewing:

### BUG FIXES
#1141
#1609
#1749
#1912
#1927 s
#1930 s
#1943
#1947
#1953 s
#1958
#1961
#1963 s
#1971 s
#1973
#1976

### OTHER CHANGES, NEW FEATURES & OPTIONS
#1622
#1645
#1801
#1907 s
#1931 s
#1959 s
#1960
#1970
#1972 

Please let me know if I miss something.
I'm happy if anyone in the community will help testing the above items.
Especially for the items with a letter `s` in the above list are posted by me and desirable to be reviewed by another developer. 

From now, PRs posted in the future will not be included to v1.2.1 unless they are bug fixes or translation updates. They will be reviewed after releasing of v1.2.1. Thank you for your understanding.

**Comment by gab3d** [comment]
I don't know exactly about how we're using version numbers in OT but,
if each of the numbers in X.Y.Z  (i.e. 1.1.3) represent the nature of the changes in reference to the previous version of the program in the following manner:
X - major new features (and bug fixes)
Y - minor new features (and bug fixes)
Z - bug fixes

I think that, as the next version will have in it some interesting new features (albeit minor ones), a v1.3.0 would not be a bad name for it (and for sure a simpler one). ;)

**Comment by shun-iwasawa** [comment]
@gab3d I understand your suggestion. But this time I would like to set the version to v1.2.1 .

It's mainly because of a name of staff folder including minor version number.
For now updating the minor version will force users the transition of user settings, which is quite troublesome especially for animation studios in production period.
For the above reason, for now the version number (X.Y.Z) is set like : 
X - Huge changes ( like altering file format ).
Y - A significant new features or big changes in user settings.
Z - Other updates.

I know it's uncommon, so I'm thinking of removing the minor version from the name of staff folder - after releasing the next version v1.2.1 .

**Comment by gab3d** [comment]
@shun-iwasawa
I understand what you say, and it seems reasonable to me.
Thank you.

**Comment by manongjohn** [comment]
@shun-iwasawa Can we remove version number from installation folder and exe also? The reason I ask is if people have to force GPU usage for OT by adding OT to the list, every time the version changes, we have to do it again. Also, at least on my Wacom, I have to readd my wacom shortcuts for the new exe. I believe someone on the Mac side was requesting the version drop on the exe as well.

**Comment by manongjohn** [comment]
@shun-iwasawa If it's not too much trouble, can you include PR #1980 ?

**Comment by jpturcotte** [comment]
@shun-iwasawa Sorry for bugging you. What about including PR #1906 as well? Thank you! cc @turtletooth

**Comment by shun-iwasawa** [comment]
Updated the list.

**Comment by shun-iwasawa** [comment]
Reviewed and merged all listed items. Thank you all for your cooperation!
Now, features for v1.2.1 is frozen.
I'll post another PR for translation update soon.

**Comment by jpturcotte** [comment]
#1990 is only a UI fix, and it would be ultra nice for timeline users if this could be included.

**Comment by RodneyBaker** [comment]
This requires a review to ensure nothing was inadvertently missed in the v1.2.1 release at which point this can be closed.

**Comment by RodneyBaker** [comment]
Closing this as cursory review did not turn up any obvious omissions.
