### ISSUE TITLE
allot of data refuses to save.

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#1902]
files: https://file.io/fpMtlN

Hello. I have a scene that refuses to save allot of data.

Open "scene1_v04" you will see that the second head drawing is missing as well as some other things. Look at the last rendered output to see what the scene looked like before I saved. When I reopened the file several things were missing.

missing Items and progress:
second head drawing
background orientation and gradient
second head drawing orientation
ponytail orientation
frosting stream first drawing
entire drawing sequence for expanding frosting.

the animation date seems to be in place. The main issue seems to be with the drawings and styles. They just were not saved. Please fix this problem with future versions of Open Toonz. If you know how to repair my scene please let me know.

This is the second time that I have opened the file to find missing data. The first time this happened I just rebuilt the missing data. I will likley do that again. But I don't want to keep doing that every time I open a file and things are missing. Please fix.

**Comment by manongjohn** [comment]
I would actually like to know how you are naming your files.  If you're naming files like xxxx.yyy.zzz or xxxx_yyy.zzz this might actually be a known issue with the OT having problems recognizing, or falsely recognizing sequenced files.  This results in broken links because it may think it is a sequenced file, remove what it thinks is a sequence for certain internal processes and then can't find it.

There is an actual fix (#1833) for that particular issue which hasn't been merged yet.  If this is the case, then for now I would suggest not including "_" (underscores) or extraneous "." in filenames.

**Comment by oladitan** [comment]
The project was in a folder synced with OneDrive
I moved the project to a folder on my HD not synced with OneDrive
Things seem to be saving better.

OneDrive must interfere with Open Toonz ability to access and save files some how.

i'll post an update later.

**Comment by oladitan** [comment]
Ok. The scene is working much better now. I have saved an reopened and did not notice anything missing. Thanks.
