### ISSUE TITLE
Glitch or not? (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1941]
In Raster Level, when the cursor is not over the canvas, switching between frames is not updated.

![ezgif-2-f3ec6debea](https://user-images.githubusercontent.com/25724133/39445205-fcdcb180-4cc2-11e8-8633-33a4f15aeeae.gif)

**Comment by RodneyBaker** [comment]
I can confirm this with the latest nightly release.

It's odd that I haven't noticed it before because I often use the mouse to move from one frame to the other via xsheet.  Perhaps that suggests the problem has only recently been introduced.

**Comment by beeheemooth** [comment]
@RodneyBaker  Perhaps. This is probably due to the improvement for Brush Tool.

![ezgif-2-98f5965ef2](https://user-images.githubusercontent.com/25724133/39445901-3ea2041a-4cc5-11e8-9b4d-9abe4f3c2c2e.gif)

**Comment by artisteacher** [comment]
I don’t have this problem when using a tablet & the arrow keys in MacOs. Without the tablet, just using the touchpad and/or arrow keys I can reproduce.

**Comment by shun-iwasawa** [comment]
I think this will be fixed with #1921

**Comment by RodneyBaker** [comment]
#1921 was merged

Is this still an issue?

**Comment by beeheemooth** [comment]
This thing is still relevant in the latest nightly builds, but I'm already used to it, for me it's not critical. :) Simply, it can confuse other users, who will scroll through the frames with the mouse cursor. 
Can I close this issue or not?

**Comment by manongjohn** [comment]
It needs to be fixed. Need to confirm if it was actually fixed.

**Comment by RodneyBaker** [comment]
I can confirm a minor update glitch but not necessarily the full one described.
What occasionally happens for me is as follows:

(Set Preferences so that raster is default level type)
Select cell in xsheet
Select brush tool
Draw frame
Move down one frame in xsheet and...
Draw another frame
Move mouse from second frame/cell to first and click in cell
Note that canvas does not update
click in second frame/cell
Note that canvas does update
click back in first frame/cell
Note that NOW the canvas does update

I get this same result using scrubbing with the Timeline indicator.

So it seems that the initial click doesn't get through to update the canvas but subsequent movement to the frame does.

That's what I see as of this moment.
I can confirm it is still an issue.

Recommend keeping open even though minor.
Then if reported we can at least acknowledge it as a known issue.

**Comment by artisteacher** [comment]
I’m pretty sure I’m not getting this anymore in OS X.

**Comment by shun-iwasawa** [comment]
@RodneyBaker Thank you for reporting it, I could reproduce the problem.

**Comment by RodneyBaker** [comment]
Thanks Shun!  That was a quick turnaround.

**Comment by RodneyBaker** [comment]
I confirm this has fixed the glitch I was seeing.

Thanks much!

**Comment by RodneyBaker** [comment]
@beeheemooth can you confirm this fixes the issue you were experiencing?

**Comment by beeheemooth** [comment]
It looks like the problem is still not completely solved, but this time it touches the Brush tool with Frame Range feature.

![ezgif-2-153897ec18](https://user-images.githubusercontent.com/25724133/40580430-8b65c580-6146-11e8-8062-45289ec79b23.gif)

**Comment by beeheemooth** [comment]
The problem I mentioned above is no longer there. I close this issue.
