### ISSUE TITLE
OpenToonz 1.2 About 20% of my vector strokes disappear or do not register immediately after drawing them.

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#1944]
I am using opentoonz 1.2. on a windows 10.

when I draw a stroke on a toonz vector level there is only an 80% chance that the stroke will remain on the canvas.

some vector strokes disappear as soon as I lift my pen off the drawing tablet. 

Fills are unreliable for enclosed vector areas as well.

what setting can i adjust to fix this? 

Thank you.

[Example of this problem](https://www.youtube.com/watch?v=Pi5i6l0RoOM)

**Comment by manongjohn** [comment]
@oladitan Can't view the video.

**Comment by oladitan** [comment]
@manongjohn please try again.

**Comment by manongjohn** [comment]
Hmm.  Interesting. 

Are you using the OTX, a nightly or the official 1.2 release?

**Comment by artisteacher** [comment]
I haven't run into this myself, but I did have a student who described the same thing happening yesterday. This was using a nightly build from the end of January (the 30th or 31st) with OS X 10.11.6 and a wacom bamboo tablet. I updated that computer to the latest nightly build & at least today there were no complaints.

@oladitan were you using a stylus on the surface when you had the same issue? If so, this is probably tablet or stylus specific.  

Also, if you haven't tried updating to a [nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly), it's worth a try. There have been a few tablet fixes & also a really helpful adjustable gap size option for vector filling. Otherwise, the snapping added to the vector brush & simplify vector command added in 1.2 are also really helpful to minimize fill issues.

**Comment by shun-iwasawa** [comment]
This problem seems to be the similar to #1683 and fixed with #1753

**Comment by RodneyBaker** [comment]
@oladitan can you confirmthat this is fixed?
If so, recommend closing.

**Comment by RodneyBaker** [comment]
Closing based on comments by @oladitan and @shun-iwasawa 
Please feel free to reopen/comment as necessary.
