### ISSUE TITLE
Is there a way to duplicate a level?

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#1946]
I have a level with drawings and styles.

I want to duplicate the level and its drawings. 

I want the duplicated level to have styles that are independent from the original level so i can fill using different styles without affecting the original level.

**Comment by RodneyBaker** [comment]
If you aren't familiar with the OpenToonz Forum that's a great place for questions like this. Here's a link:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/opentoonz_en/1MK5FpSOfxA/7wPrN7dbAwAJ

Since we are here...
The standard way to get a duplicate level that isn't linked to the original is via cloning.
To clone a level (or frames of a level) select what you wish to duplicate and then on the menu select Cells > Clone.   This will create a new column/level that is a duplicate as of the time of cloning but one that will not update automatically as if it were the original.

Of course where we want the duplicate to update along with the original but have different styles applied to it we can simply copy/paste into a new column and apply the styles individually to each column.  The underling image then will be the same even though the style fx is different.  As an example, a color fx can be assigned to a duplicated level that that changes the style/color of that level for that specific column/exposure.

**Comment by artisteacher** [comment]
Just for clarification, cloning works only on selected cells in the Xsheet. Make sure all the cells that you want to copy are selected before using the clone command.

Recommend closing since this is not related to a bug.

**Comment by oladitan** [comment]
Thank You. I will try this next time.

**Comment by RodneyBaker** [comment]
Recommend closing.
