### ISSUE TITLE
Everything Wrong With Sub-Xsheets

### ISSUE THREAD

**Issue by Orphanlast** [opentoonz/opentoonz#1966]
Trying to explain the problem through text or verbally doesn't work. I've tried multiple times and I've gotten confused reactions. So I've provided a link to a video that will explain the problem that I have with Sub-Xsheets. It starts out slow, with information that's pretty common sense, but eventually builds up to describing what the problem is:

https://www.youtube.com/watch?v=8dpPts8-tEY

Okay, so if you're reading this, you either clicked the link or your didn't. So I'll spend this time explaining what the problem is.

Sub-Xsheets will only display numerical frames. Exposed frames that have been extended (frames with a line going through them) have no effect on Sub-Xsheets. Once you get rid of numerical frames, there's no way to get the numerical frames back unless you explode the Sub-Xsheet and then Collapse it again. It's a real pain in the butt.

**Comment by RodneyBaker** [comment]
One parts of the workflow you are running into is that of the column number that changes each time you establish a new sub xsheet and it appears to me that what you want to rename is your Level not the Column.  The Column should not necessarily be named the same as the Level because it will more often than not contain multiple Levels.   So rename your levels so the Level name will appear in the xsheet.   

When we name a Column that has nested levels it's not clear what name it should inherit.   Most approaches would just insert 'untitled' followed by a number pending a manual naming by the user. 
As an aside, this is an equivalent of Named Groups in a way but not for strokes and shapes but for Levels that contain those (and raster images).

That's the main point I want to address... I haven't yet fan through some of the other concerns you've raised.  I did find myself wondering if any of the things you ran into are different in the xsheet view so when troubleshooting it's good to run through the same workflow in the xsheet to verify that the issue appears in both.  The reason for this is that the Timeline is still very much a work in progress and may therefore not always mirror the xsheet.  If a problem only appears in the Timeline it will be much easier to address.

**Comment by gab3d** [comment]
@Orphanlast currently you have two options to regain access to the subxsheet cells:
1. In he Timeline, position yoursefl in the first empty cell, after the sub-xsheet level, and press "W" shortcut twice, then press the righ cursor key to go to the next empty cell and repeat the procedure until you've recovered all the cells you want.
2. Select the whole column containing the Sub-Xsheet and use the "Resequence" function (RMB menu or Xsheet menu). The entire sub-xsheet reappears.

In spite of that, I agree there should be a simpler way of cutting/extending levels in OT. Probably by Shift-dragging or Alt-dragging the level's last cell tab, or something like that...

**Comment by shun-iwasawa** [comment]
> Once you get rid of numerical frames, there's no way to get the numerical frames back

Please try selecting frames 24 & 25 then dragging the smart fill handle.
[The smart fill handle](http://opentoonz.readthedocs.io/en/latest/working_in_xsheet.html#using-the-smart-fill-handle) will check the selected cells. If there is a regularity (like arithmetic progression) found in the frame number, it will extend frames with keeping it. 
Please note that it will check ONLY inside of the range of selected cells. Selecting & dragging a single frame will extend only the same frame number. There is no difference between subxsheet levels and other level types regarding this behavior.

![smart_fill](https://user-images.githubusercontent.com/17974955/39974072-119a01ba-5761-11e8-80a4-213f6172bfb0.gif)

**Comment by Orphanlast** [comment]
@RodneyBaker I'm just saying that when I drop a column into the Xsheet -- in the part your mentioning -- It feels like dropping it into a file or, yeah, a group, but instead it's more like having an envelope and a piece of paper and then placing the envelope and piece of paper into a new unlabeled Envelope.

That seems weird to me.

@gab3d I understand that now. But the idea I have about the Numbered Level Strip would make it easier for new users when dealing with numeric frames on sub-xsheets. It's more visual for them. Like, I understand, NOW, that you can select the last two frames of a sub-xsheet and then extend it to get numeric frames... but that's not immediately intuitive. We should keep that functionality, there's nothing wrong with it. Because once you learn about it, it's the easiest method. But every time I ran into that problem, I was looking at the level strip, in vain, wishing I could click and drag numeric frames. Because a similar workflow exists for normal columns. 

I've had a few people, elsewhere, politely accuse me of wanting to have redundancy in the program. But there really isn't anything wrong with having two to three ways of doing a task. Take photoshop for example. Half the tools I used when I first used that program, I would never EVER use again, because of a few reasons. There's more than one way to do the same thing, there's better ways of doing the same thing, and because it's none destructive another way, or what have you. The list of reasons are endless depending on the task or tool. Having more than one way to do something is good. Especially if one way is visual for newbies, and another way that's less obvious but actually easier to use for those that learn more about the program.

However, CTRL+Click+Dragging I think should do something different for the Xsheet and Timeline. 

Suppose I have ten frames. 5 of them are on frames 1,2,3,4,5 and I have another 5 of them on 11,12,13,14,15.

Suppose I want to extend frame 5 for 5 frames. Once I do that, the frames that were on 11,12,13,14,15 are now on 16,17,18, and 19.... I just think a CTRL+Click+Drag should keep those frames on 11,12,13,14, and 15 stationary. And supposing I'd like to expose frame 5 to frame 20, those frames on 11,12,13,14, and 15 would follow the second I'd drag from 11 to 20 and wind up at 21,22,23,24, and 25.

@shun-iwasawa Thank you, DarrenT also told me about this techique soon after releasing the video. But for some reason no one understood the problem when wrote it out in text. So I made this video. I still think that new behavior for the level strip on a Sub-Xsheet would be helpful to new users, but I'll be using that technique from here on out.

**Comment by DarrenTAnims** [comment]
So now that we've seen your video and understood your problems, it seems like all that's left is a feature request to extend the Level Strip to also show thumbnails of each frame of sub-xsheets, to help users, so they have another way to drag new sub-xsheet frames into the timeline. Is that right?
To the ocd in me, that'd be quite a change as it's only there to show a single level's frames, but as a pragmatic user, I think that'd be a great help to people.

**Comment by Orphanlast** [comment]
@DarrenTAnims I don't think showing an image of the thumbnails inside the sub-xsheet's a good idea, because it might communicate that you're able to draw inside the sub-xsheet while you're outside of it. 

I want the level strip to behave differently for sub-xsheets. I think that the level strip should litterally have a red number inside of each thumbnail box of the level strip. So that you can pull 1-100 numeric frames from the level strip onto the sub-xsheet. Blank numeric frames. Whatever is or isn't inside the sub-xsheet will either fill up what's there or not. Suppose you need a full 600 frames filled. It's possibly faster to grab 100 frames from the level strip and drag them onto the timeline 6 times rather than clicking and dragging for the whole 600 frames. While clicking and dragging would be faster for 40-100 frames, not so much for 600-1,000

I do think this would help new users. I say this because I kept looking at the level strip wishing I could pull from it, like I do from a normal level. But it wasn't an option. 

I think having multiple ways of doing one task is a good thing. Because there's multiple ways of getting unstuck, multiple ways to troubleshoot, multiple workflows, and the options on the table makes it so that you're not forced into just working in ONE way. Which can feel restrictive. And having multiple ways of doing thingr can give you a faster workflow in one context, and not in another.

**Comment by DarrenTAnims** [comment]
I agree about having multiple ways to perform a task and using different styles too, so I like for example:
having keyboard shortcuts AND
a context menu AND
a drag/drop AND
a main menu AND
toolbar buttons.

I was just thinking of the thumbnails, to help see what you can drag, but that wouldn't be essential. As you say, if that's a place users might look to do it, then we probably should.

But what I was also asking was, is this the main improvement that you'd like to see. From watching your video, I think so.

**Comment by Orphanlast** [comment]
Yes, I would like to see numbers on the level strip thumbnails when selecting a sub-xsheet. That's the main take away from this. 

Yes in a way I was asking how can you get numeric frames in there, but the main take away is a GUI improvement. 

I can understand if no one wants to take this on, but I think it'd be an improvement

**Comment by gab3d** [comment]
@shun-iwasawa
Perhaps it'd be a good (and simple) idea to improve the Smart Fill handle Tooltip text to inform about this possibility?

Currently the functionality is somewhat 'hidden' from view, and the program documentation is not the easiest to browse either.

**Comment by artisteacher** [comment]
I think that the idea of the sub-Xsheet icons displaying in the level strip isn’t necessarily a bad idea - there just needs to be a clear visual cue as part of the icon that the level strip is displaying sub-Xsheet frames. Perhaps a watermark sort of look:
<img width="269" alt="e59cd7c0-ce88-4180-b99b-4c9485412b63" src="https://user-images.githubusercontent.com/21159116/40026976-b8541452-57a5-11e8-9cfd-eb4f5bc2f1f0.png">
Then the disabled tool cursor would need to display in the viewer if the level strip was active for a sub-Xsheet. The smart fill handle is super helpful but drag & drop is probably more expected.

**Comment by Orphanlast** [comment]
I'm not thinking of images on the sub-xsheet's level strip. There comes a point to where you might want more numeric frames than there are images inside the sub-xsheet. And unlike a normal level, just making more drawings wont give you more to throw in. 

I was just litterally thinking numbers in the boxes would told you everything you'd need to know about the sub-xsheet's leved strip.

https://cdn.discordapp.com/attachments/313658315970445315/445334815152013333/Capture.PNG

**Comment by Orphanlast** [comment]
I'm not thinking of images on the sub-xsheet's level strip. There comes a point to where you might want more numeric frames than there are images inside the sub-xsheet. And unlike a normal level, just making more drawings wont give you more to throw in. 

I was just litterally thinking numbers in the boxes would told you everything you'd need to know about the sub-xsheet's leved strip.

https://cdn.discordapp.com/attachments/313658315970445315/445334815152013333/Capture.PNG

**Comment by manongjohn** [comment]
I think this largely depends on how you use sub-xsheets.  Consider you can time the contents on the sub-xsheets on 1s, but on the main xsheet, you'll time the sub-xsheet on 2s or 3s or however you need to.  You may not even use every frame from the sub-xsheet or may need to do other things with that sequence like maybe reversing it at some point or even repeat all or part of the sequence over and over again.  In this sense you are treating the sub-xsheets as any normal layer where 1 frame = 1 drawing.

For this reason it makes more sense to have an image in the Level Strip at that frame.  Then, if you need to reuse a specific frame from the sub-xsheet, you know easily which one to drag/drop from the Level strip into the main xsheet (well, if it were allowed).  A number will not tell you anything about the image at that frame number.

If, however, you're using sub-xsheets as a way to organize your layers so you don't have a messy sheet then yeah, you'll have issues if you need to adjust timing just like if they were in the main xsheet.  The Edit in Place would at least allow you to enter the sub-xsheet and adjust the timing as needed.

The bad part about having images in the Level strip for sub-xsheets in this scenario is you may have multiple frames that look exactly the same.  Consider you have several drawings on sub-xsheet frame 1 and hold all to frame 3.  From the main xsheet, the Level strip would show identical icons for frames 1-3.

I would prefer to see an image in the Level strip because that is more meaningful to me than a number.

Just my 2 cents.

**Comment by artisteacher** [comment]
Images are much more intuitive for me than numbers so I'd also prefer to see thumbnail images. I'm pretty sure I would constantly be dragging & dropping the wrong thing if this was completely numbers based...

**Comment by DarrenTAnims** [comment]
I agree with having thumbnails (if we show sub-xsheets in the Level Strip, which I'm still not sure we need). Likely most will look the same, but some won't and that is what that control shows for actual "levels", so is what I'd expect to see.

**Comment by DarrenTAnims** [comment]
I tell you what would be useful, would be when you choose to collapse some columns into a sub-xsheet and you get the popup asking if you want to collapse pegs, etc, it'd be handy to have a textbox that you can type in the name for the column that the sub-xsheet will be shown in.

**Comment by RodneyBaker** [comment]
This seems to be a very broad discussion that may be better suited to the OpenToonz forum.

Recommend at the minimum closing this issue and reopening one with a focus for repairing a processes that isn't working.  Remember to reference this issue.
