### ISSUE TITLE
Edit In Place doesn't show main if the sub-xsheet's frame is not exposed in the main

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#1975]
I'm submitting this issue on behalf of @Orphanlast who encountered this problem while working on one of his presentations.

Basically when working in a sub-xsheet with Edit In Place toggled ON, if you go to a frame that the sub-xsheet is not exposed on in the main, you stop seeing what's in the main.

Example to recreate:
1) Create 3 empty columns
2) On Col1-frame 1, draw something and extend to frame 10
3) On Col2 and Col3 - frame 1, draw something and extend to frame 5
4) Collapse Col2 and Col3 to create a sub-xsheet
5) Open the sub-xsheet and toggle Edit In Place to ON
6) Click on frame 5 - You can still see the drawing from Col1
7) Click on frame 6 - The drawing from Col1 disappears

This also happens if there is a gap in the exposed sub-xsheet frames in the main:
1) Close sub-xsheet to return to main xsheet
2) Delete the exposed sub-xsheet's frame 2
3) Open the sub-xsheet again
4) Click on frame 1 - You can still see the drawing from Col1
5) Click on frame 2 - The drawing from Col1 disappears
6) Click on frame 3 - You can see the drawing from Col1 again

We would expect if Edit In Place is on, we should still be able to see the main from inside the sub-xsheet, regardless if the sub-xsheet's corresponding frame is exposed in the main or not.

**Comment by gab3d** [comment]
I think the frame from main displayed is the one the current subxsheet cell appears in. So this makes me wonder a couple of things:
- What frame from main to display when you are in an unexposed cell?
- What happens when the current subxsheet frame is exposed in multiple frames of main?

**Comment by beeheemooth** [comment]
In my opinion this is the obvious behavior of sub-xsheet. If the window in the room is closed, it will not be possible to look either outside or into the room. The disappearance of visibility in places where sub-xheet frames are deleted can be useful for internal sub-xsheet animation, since it indicates the places where sub-xsheet does not have frames on the main (Xsheet)

**Comment by manongjohn** [comment]
@gab3d Hmm, good point.  That could explain why the main disappears because it has no frame of reference from which to build an image.

I guess then it matters how you are using the sub-xsheet. If you assume the frames from the main and the sub-xsheet are in sync, then Edit In Place as described above would make sense.  However, that is not a requirement for using sub-xsheets since it can start anywhere in the main and the frames can be used like any normal level so it can be held, reordered, skipped.

@beeheemooth I guess.  Sometimes it would be useful when in an sub-xsheet to adjust timings or other things relative to what's happening in the main, even if the sub-xsheet frame hasn't been exposed yet.  Saves having to flip in and out just to expose the sub-xsheet further on the main.

Not sure this is resolvable other than understanding better how Edit In Place works and how it should be used.

**Comment by manongjohn** [comment]
I think this goes back to the assumption that the frame #1 in the main are the same frames in the sub-xsheet.  If that were always the case, then yeah that would be a valid request. A general open sub-xsheet wouldn't know where to put you otherwise.

Perhaps we need a right-click option specific sub-xsheets that would open the sub-xsheet at that selected exposed frame (Open Sub-xsheet At Frame?).  This would accomplish what you are looking for.

**Comment by beeheemooth** [comment]
Unlike time slider, markers remain in the right places at the entrance to sub-xsheet, only using them you can quickly position the time slider in the right place. It is obvious that the user, using markers and working with the selected time interval, in no way wants the time slider to jump to the very beginning of the entire animation.

In other words, if the markers are active, then the "Open Sub-xsheet At Frame" option you are talking about should also be active, since the user's attention is focused on the area inside the markers (on Xsheet and sub-xsheet). If the markers are not active, then the option is disabled.

**Comment by gab3d** [comment]
@manongjohn 
Perhaps the following behaviour would be useful when Opening sub-xsheets:
- If at the current xsheet frame, the sub-xsheet IS exposed, then take the user to the sub-xsheet cell exposed at the curret xsheet frame.
- If at the current xsheet frame, the sub-xsheet is NOT exposed, then take the user to the beginning frame of the sub-xsheet.

**Comment by manongjohn** [comment]
@gab3d I like that idea for a cell's right-click menu option, but not the existing general Open Sub-xsheet command.

The reason I say that is because the current label doesn't suggest that will happen. To a new/unaware user, it will look like it is opening to a random frame in the sub-xsheet.

**Comment by gab3d** [comment]
I use Maya and 3ds Max (yeah, I know, 3D not 2D, but bear with me...) 
When you have acomplex scene, and you want to concentrate on a specific object, it's not uncommon to isolate that object from the scene, to be able to access it from any different angle, without other object potentially blocking your view, etc.
When you go to isolate object in those two programs, each one have a different approach to it.
- 3ds Max take you to a completely independent universe, where the isolated object is located at the center of the universe.
- Maya just hides avery other object, maintaining the object where it was, previous to the isolation command.

Personally I've always found Maya's way of doing it the most useful one, because:
1. you don't have to suddenly adjust your eyes to catch the isolated object in the new centered position.
2. when tis object is interacting with other ones, it is important to preserve the real object position/orientation to be able to make the necessary adjustments.
(I know Edit In Place takes care of all this in OT)

What none of them does is jumping you in time to the beginning of the animation, when you isolate an object. And this is what OT does hen you enter a sub-xsheet :)

Coming back to 2D program examples... in After Effects (another program I've used a lot), when you enter a Pre-Composition (their somewhat equivalent to our Sub-Xsheets) the time you are drop into in the PreComp is the time when the current frame being shown in the main Comp is shown in the Pre Comp.
And that is, naturally, because it's usually the most useful place where the user would want to edit something in the PreComp.


I respect the argument that maintaining the status quo for existing users is generally a good thing. in spite of that, in this case, I wonder how often would users (new or old) want to enter a long sub-xsheet to edit something that they are not currently seeing at the current xsheet, at that point in time.
So, if the answer is "in very few occasions", then maintaining a currently defective behaviour doesn't seem to be a very good thing either.

All in all, even maintaining the current behaviour, but having an option for the other behaviour also would be better that what we have now. So I'd be happy. ;)
(Perhaps, Ctrl + clicking the Open Sub-xsheet button could trigger it).

**Comment by manongjohn** [comment]
@beeheemooth The markers in the sub-xsheet are not linked to the main's markers in any way. 

Consider this: the main markers are at 6, 12. If your sub-xsheet-frame 1 is exposed at main-frame 3, when you open the sub-xsheet, the markers are still at 6,12...it won't be moved to 3, 9 to stay in sync with the main.

I essentially view the "time" in sub-xsheets as just final frame numbers instead of actual  time. When you close a sub-xsheet, you expose and hold frame numbers, like regular levels in the main.

**Comment by manongjohn** [comment]
@gab3d It appears the Open Sub-xsheet command actually requires selecting an exposed cell to open. Can't just open it when on an empty cell in that column.

Conversely, when closing a sub-xsheet,  It seems to remember the frame you were at and return you there.

Based on that, I think we can argue that the default behaviour should just open to the selected exposed frame in the sub-xsheet.

Will look more into it when I have time. 😊

**Comment by DarrenTAnims** [comment]
I agree with the comments about the markers. That's a real frustration.

In regard to the Edit in Place. All you need to do is to expose the frames before you go into the sub-xsheet. You can expose frames not yet created by dragging the exposure handle out (the numbers show in red, but they're there and ready), so the sub-xsheet knows which frame from the main xsheet to show. I understand that it can be confusing or annoying while you're adding frames inside a sub-xsheet, but it's just another thing to get used to while using them.

**Comment by gab3d** [comment]
@manongjohn 
agreed.

**Comment by manongjohn** [comment]
Closing this as I guess it's not really a bug, but more of a lack of understanding of this feature as it is currently coded.

However, it would be nice that when editing inside a sub-xsheet that you can opt to see the contents of the main xsheet at that the given timeframe.  This assumes the timeframe  in the main and sub-xsheet are in sync regardless of sub-xsheet exposure.  Probably should be a feature request or something.
