### ISSUE TITLE
[Proposal] Taller Tool Options Bar?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#1977]
That's just a question that keeps coming to my mind:
Could it be possible to make the Tool Options Bar dynamically adjust to a two row layout, when there is an excess of required space to show all of the selected tool's options?

For example, currently the Animate tool (when in All mode) has so many options that even in a 1920 wide monitor, there are still some options that end off screen.

Also, thinking of people using OT in some notebooks which resolution is even less than that, I imagine that other tools' (like Brush or Select) options would, too, be facing the same problem.

I'm thinking of an option in Preferences to allow this behaviour or not.

**Comment by artisteacher** [comment]
@gab3d you are completely right about notebooks with lower resolutions.

While 2 rows could be a step in the right direction, I would rather see the responsiveness expand to as many rows as are necessary to display as many options as are possible in the given space. I'd love to see this for the toolbar and command bar as well.

An alternative, partial solution could be to make those windows all scrollable instead of relying on only a button press to display hidden options/tools/commands. In Blender, the property buttons scroll from side to side without a visible scrollbar when the panel is too small to display all of the options. In OT, in the Style Editor's color tab, the content also scrolls without a visible scrollbar when it is cut off. I really prefer that behavior over the existing - though completely responsive would be best.

**Comment by artisteacher** [comment]
On a related note, I found that scrolling is actually turned off in the tool option bar - which is really problematic on small screens. @shun-iwasawa, is there a reason for this? 

I sometimes have to use a small MacBook Pro & sometimes certain options display without their labels because there is not enough room. As a first step in getting more responsive, can scrolling be turned back on?  The relevant line is in tooloptions.h, line 112.

**Comment by shun-iwasawa** [comment]
@artisteacher 

> I found that scrolling is actually turned off in the tool option bar - which is really problematic on small screens. @shun-iwasawa, is there a reason for this?

In Toonz Harlequin the tool option bar was scroll-able and all widgets (including sliders) had fixed width. On relatively-small screen the widgets located in the right side of the tool options bar were hidden and users needed to scroll to access them. 
Therefore, when I made Toonz Ghibli edition I decided to make the tool option bar basically not scroll-able in order to make sliders stretch-able so that all options are always displayed. As far as i could see, "scroll" and "stretch" are trade-off. I couldn't have a good idea to make the both properties to coexist.

**Comment by artisteacher** [comment]
Interesting. That is a tricky decision. What about enabling the scrolling just for the combo viewer for now? Unless the combo viewer is fullscreen, it’s almost impossible to use a lot of the options on a small screen.

 It looks like with scrolling on, the tool options remain responsive (stretching/shrinking) until clipping would normally begin, which triggers the arrows. There are 2 places that end up having visual glitches - the “pick screen” mode of the rgb picker gets cut off, and the plastic tool options behave strangely. If those 2 issues could be resolved, I think that at least in the comboviewer, this could be really beneficial.

**Comment by Orphanlast** [comment]
Sounds good to me.
