### ISSUE TITLE
ffmpeg:  APNG Support

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#1978]
APNG (animated PNG) is available in all modern browsers now, excepting IE and Edge, Since Turtletooth already implemented GIFanim export via FFMPEG, and FFMPEG supports APNG as well, it should be trivial to add APNG export in OpenToonz too.

For those who are unaware of the APNG format: it supports full colour and full transparency as opposed to GIF animations which are limited to 256 colours and only 1bit transparency. 

It would be a great addition for animators who want to publish their work on the web.

I might be able to work on this myself, time allowing, and depending on the existing code for the FFMPEG gifanim export.

**Comment by artisteacher** [comment]
This would be fantastic!

**Comment by blurymind** [comment]
Yes please. Lets help this format grow on the internet

**Comment by RodneyBaker** [comment]
If you do add a feature request into the forum related to FFMPEG one option that might be very useful would be to allow entry of FFMPEG code itself... rather than hard coding new FFMPEG features individually such as conversion/export to APNG.  The reason being that users could then quickly alter that code to gain additional custom results as opposed to one specific outcome.  This would be the equivalent of things we can already do now of course with FFMPEG via the command line but we'd be able to store it in an OT dialog.

Recommend closing this topic pending active development and opening the feature request via OpenToonz forum.

**Comment by RodneyBaker** [comment]
Added:
The issue with APNG and FFMPEG will likely be that FFMPEG only has an APNG demuxer.

https://www.ffmpeg.org/ffmpeg-formats.html#toc-apng

It may be better to use another dedicated program or utility to achieve this conversion.

**Comment by jpturcotte** [comment]
I agree with @RodneyBaker that adding command line options would be more useful in the long term. However, as he pointed out, FFMPEG cannot create APNG files for now. APNG Assembler seems to be the tool for that: https://sourceforge.net/projects/apngasm/.

Recommend close as well.

**Comment by RodneyBaker** [comment]
As far as I can tell FFMPEG still hasn't gained the APNG capability required to move this forward.   Perhaps we'll see some better opportunity for integration of APNG as well as other formats in 2019.

Alternatives
As users we should be able to chart a good pipeline or two to get from any other image sequence into APNG format.  Those with a good working knowledge of APNG are encouraged to give us some direction in how best to get that done.

**Comment by RodneyBaker** [comment]
Thanks @konero I'll check it out.
Has anyone been using that in the wild successfully.
I ask because I've seen contradicting statements online.

In the meantime... this is easy enough to test and will as I get the opportunity.

**Comment by RodneyBaker** [comment]
This needs a little more time to develop and implement but appear very doable.
This seems likely to be incorporated into an update of ffmpeg integration in Opentoonz.
Slipping to 2019 Development cycle.

**Comment by RodneyBaker** [comment]
It will be good to investigate this.
I did a quick test converting a 122kb MP4 file into APNG and the size of the APNG was over 6MB.
So, with that and other quesitons on the horizon such as... support for transparency etc... I hope others will join in and experiment as well to make sure if we add direct support of APNG (via ffmpeg or otherwise) that it is the absolute best implementation possible.

@Rayek  You've requested APNG.  Do you have any specifications for what you see as absolute requirements and necessities?

**Comment by RodneyBaker** [comment]
It will be good to add APNG and other output formats even if only via a readme.txt document and or batch file scripts (for WIndows).  Perhaps we can collect some of these ffmpeg scripts here in this topic.

**Comment by RodneyBaker** [comment]
A note for ffmpeg review in 2020 development cycle
Allowing the user to specify output via ffmpeg script (post processing) or other means can add a number of image and video formats to include APNG.  Alternatively, posting examples of how users can leverage ffmpeg independently of Opentoonz can accomplish similar results.

Question:  What ffmpeg command line arguments must be used to obtain optimal size and quality for APNG (and other) formats?

**Comment by RodneyBaker** [comment]
Returning to this report to mention how Opentoonz currently can import APNG files...as well as a host of other formats via an interesting ffmpeg workaround.  Pursuing something like this programatically would enable Opentoonz to have an option to TRY to import a given format.

The 'trick' is to rename the file extension something that Opentoonz will recognize as a legitimate file format.
From that point ffmpeg does its magic, recognizes the format and processes it accordingly.

So for example an APNG image sequence named 'coolstuff.apng' just needs to be renamed 'coolstuff.gif' for it to be importable in Opentoonz.   

Why not rename the extension .png?
Because PNG is a single image format and we want a sequence.

Other examples?
Have a .MOV file that you want to load into Opentoonz but can't remember the process required to get MOV files as a legitimate format?  Temporarily rename the file with an MP4 extension and import it!   

Don't want to waste time bringing the file into Opentoonz?
Right Click on the renamed file in Opentoonz Browser and use Convert.

Disclaimer:  Renaming a file extension is not recommended because you will forget what file format it really is and then won't be able to use it as originally intended.  So... don't.  Unless of course you need to.

Reopening this issue as there is no reason why APNG can't be supported through ffmpeg.

**Comment by RodneyBaker** [comment]
Update:  I have just rendered out to APNG format from a fork of Opentoonz.
APNG (and more formats) coming to Opentoonz in the near term is quite likely.

**Comment by RodneyBaker** [comment]
@Rayek You'll be pleased to know the APNG format can now be loaded/imported and rendered to in Opentoonz.
Thanks @justburner for implementation!
