### ISSUE TITLE
Adding Clarity to Timeline View

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#1985]
Big fan of the timeline, but personally it's very difficult to use effectively due to the sheer amount of noise generated from the abundance of information held by each level. On and off for a couple months I've been looking at a re-design, but now I definitely won't have time to do it, so I'm posting my findings and assets here in-case somebody else looks into it.

Here's what I came up with:

![timeline_design](https://user-images.githubusercontent.com/19820721/40268179-f754dd1c-5b60-11e8-9d43-8e0dcace88c5.png)

Put this image into PaintDotNet or any editor with a pixel grid to determine the sizes for each area.

- Invert white text to black.
- The 'shift trace' and 'onion frames' indicators get a visual helper with a separator line.
- The interval blue marker is shortened to the time area.
- Remove the hold line, a hold will be obvious by the break line between two frames.
- Reduce vertical cel separator lines to small markers on the cel color blocks.
- New key icon to represent what is probably the industry standard for such.

Usually I would build in Python and then port to C++, I'm just not the biggest Qt fan so I didn't get very far, so no real code to share. Here's how I constructed the cel block style.

- **Each cel is 10x20 pixels at the smallest zoom factor.**
Here's how cels sit and how they're separated.

![xsh_cel](https://user-images.githubusercontent.com/19820721/40268354-a60bd098-5b63-11e8-847b-bce7d744764e.JPG)

Each cel has a 1 pixel black border on the bottom and on the right which are aligned with the separator dividing lines on the timeline grid.

Each cel also has 1 pixel white (15% alpha) on the top and on the left side which is what helps to distinguish each cel area from another with the outdent effect.

![xsh_cel2](https://user-images.githubusercontent.com/19820721/40268414-c4742890-5b64-11e8-9ef4-cadba55e970d.JPG)

And that's pretty much it visual wise. The only icon is the loop key icon, the key icon itself can be drawn easily in Qt as a square and rotated, etc.

**Comment by manongjohn** [comment]
@konero I agree, it is quite noisy, especially when zoomed all the way out.

I agree with almost all of your suggestions and can implement them as I am familiar with the xsheet code. 

Not sure I would change the interval markers and for now I'd leave the onion indicator stuff alone. Iffy about the timeline indicator change.

I like the keyframe replacement idea, though may make it a little harder to target. On the flip side, it will be easier to select the cell and not the keyframe since it currently takes up most of the cell. When zoomed in, i'd probably show the normal icon, about the same time the texts starts showing again.

We'll see how others feel.

**Comment by artisteacher** [comment]
I actually really like the separator line for shift trace/onionskin - it would be helpful in the Xsheet too. At least on OS X, hover effects don’t work with a tablet, so it can be tricky lining up the stylus at the right spot on the first try. I prefer a thinner red frame indicator line. 

About the interval markers, If the cell separator lines are gone, the current interval markers could look strange. At the same time, with cel animation, if you have a large number of levels, they can be a helpful indicator. On a related note, I wonder if the frame numbers should be in multiples of 6 instead of 5 for the zoomed out view. If the frame numbers in the zoomed out view lined up with the interval markers, only the cells themselves would need the blue line. When the timeline is zoomed in enough for all frame numbers to display, the existing line display of the line works much better visually. 

I like the idea of the simplified key icon when the timeline is zoomed out.

**Comment by konero** [comment]
All good points, thanks for looking into it even though this should probably be treated as very low priority.

I was a user of Adobe Flash for many years, even when it went back to being owned by Macromedia, so in this concept it's what I was borrowing heavily from while at the same time trying to incorporate Toonz specific things. Even today it's still the clearest, easiest to read timeline UI I've worked with.

![flabig](https://user-images.githubusercontent.com/19820721/40278201-bdc93056-5c24-11e8-8793-0ae676d81ee4.JPG)

**Comment by manongjohn** [comment]
Low priority? Umm...this is what I've done so far :)

![image](https://user-images.githubusercontent.com/19245851/40279228-ab34308e-5c0c-11e8-9e1c-ee637a6f4781.png)

Definitely easier on the eyes to read without all those extra lines, though it will take me some time to get used to the dark dots. 

- I let the marker show only if it was between 2 different frames as I find it an easier way to tell if I've hit the marker.
- Normally dot color follows text color so it follows theme if they wanted a different color scheme. Currently forcing to black, for now.
- Zoomed in view looks the same with the exception of the keyframe icon.  The normal keyframe icon appears when zoomed in 51% or more.
- Probably need to change the selected keyframe color.  Hard to see now that the icon is so much smaller.

**Comment by artisteacher** [comment]
Looking good! I do think the black dot looks slightly too big & too similar to the keyframe shape. Maybe try a slightly smaller square or circle?

**Comment by manongjohn** [comment]
@artisteacher Yeah, I noticed the size was larger than I intended.  I've already reduced the size of that dot.  Currently working on cleaning up the frame header and then will submit a PR with everything I've done so far. :)
