### ISSUE TITLE
New Basics horizontal Room? (Called "Timeline"?)

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2003]
With all the new improvements made lately to the Timeline, I think we should provide a good starting point for users wishing to use it.

Following is a variant of the Basics Room, tuned for use with the Timeline, instead of the Xsheet.

![basicsroom horiz](https://user-images.githubusercontent.com/18104091/40494132-854a1ea6-5f4a-11e8-9854-69a821525b7d.png)

**Comment by RodneyBaker** [comment]
@Gad3D I know your thought here would be more toward adjusting the deafults but I want to suggest another approach.  That approach can immediately be implemented and may also result in eventual updates to the defaults.  In short...

Can you share your room settings here or in the OpenToonz forum so that others may benefit?

The beautiful thing about the rooms and preferences is that they are easily shared and customizable.
Perhaps the best place to share those and to test them out in the real world is via a topic in the OpenToonz forum.  That's a great place to really push the limits of user led development and to even encourage more.

There are many adjustments I'd like to make myself.

**Comment by gab3d** [comment]
The new room wouldn't be named "Basics (horizontal)" anyway, because it's too long for a name, perhaps "Basics (T)" would suffice, or something along these lines...
I just titled the issue that way, but I don't consider it important.

**Comment by gab3d** [comment]
I'm not trying to reinvent anything here, but just having a Basics room equivalent for users who are inclined to work with the Timeline instead of the Xsheet. 
The other thing that I was trying to achieve here is to take the chance of the next release to incorporate this things, if we go the full route of a Forum discussion, you know it can take months before any change is actually made.

**Comment by RodneyBaker** [comment]
It's a great idea that just needs some work before classifying it as an issue.
I am confident the end result will be outstanding.

Since we are here discussing...
I'm guessing that because we will likely already have many users clamoring for a Timeline-centric room that your proposed room might just be called "Timeline" and be optimized for work with the Timeline.  So I'll make that an official request  (as official as such things are)... I nominate a new room be named "Timeline".

**Comment by gab3d** [comment]
Let's call it Timeline, it's sounds good too! 👍

**Comment by RodneyBaker** [comment]
Can you share your room files so others can try them out and see how they work?
Most won't bother to rebuild yours from scratch.

If you don't mind sharing your personal settings that might be as easy as zipping up your profile folder and sharing that.  If that's too personal to go public my personal email address is:  rodney.baker@gmail.com

**Comment by gab3d** [comment]
here are my personal settings.

[personal.zip](https://github.com/opentoonz/opentoonz/files/2037246/personal.zip)

**Comment by RodneyBaker** [comment]
Thanks @gad3D I'll do some exploring.

**Comment by manongjohn** [comment]
If (well when really) I finish up the curve animation PR, a timeline room will become more important since it will only work with timeline. 😊

So yeah..."TImeline" would be a good name for the room.

**Comment by RodneyBaker** [comment]
There are enough room/UI related issues that I'm having doubts as to whether a Timeline room will be vetted in time for inclusion in the v1.2.1 release.  It would be nice to get it in just so people could play with the Timeline itself and vet it thoroughly before the next full release.

As this isn't a feature/enhancement tagged on the official list of things to include in v1.2.1 it would be good if others could weigh in on whether the timing is right for inclusion.  Especially @manongjohn who is doing the heavy lifting.  As he mentioned... curve animation isn't yet ready but it still might be good for users not to have to search out the Timeline in order to explore it.   (I say this as someone who prefers the xsheet view) My gut feel at this exact moment is that the release of a Timeline room should likely coincide with the announcement of curve animation in the Timeline after that has been given additional time to be explored, tested and refined.

There are several ways forward and one doesn't necessarily preclude having the best of all worlds.  If the Timeline room doesn't make the cut then it's a fairly trivial thing to point someone to a download that contains a Timeline room.   The issue there is what that room should optimally look like.  It makes good sense that the canvas would be high and left (for right handed users) and that the Timeline would display across the bottom.  When we get to the additional windows... things get a bit murkier as those will depend any given user's workflow.  I think a common ground can be found but it will take time to discuss.    In the short term I favor a set of room layouts be shared and users can download, experience and offer their feedback.  As UIs are a never ending source of conflicting opinion at least then users would have useful options to choose from.

**Comment by manongjohn** [comment]
If we don't get it in for this release, then we definitely should create it when Curve Animation goes in to help highlight the new feature and its use.

If we're doing layout ideas, this is the layout I normally use (I'm left-handed, flip for righties): 

![image](https://user-images.githubusercontent.com/19245851/40550452-209210e0-6008-11e8-93ec-2ba3e1ccd779.png)

**Comment by RodneyBaker** [comment]
I like that.  Nice.  Simple.  Direct.

You mentioned you are left handed.    Is there something in OT that currently deals with that left/right handedness thing?  

Although you might see that as primarily useful for a left handed user that layout works well for me as right handed too.

**Comment by manongjohn** [comment]
@RodneyBaker Aside from the introduction of flipping the drawing icons for left-handed users in my Timeline Display Update PR, there really isn't anything for left-handed people in OT that I'm aware of. 

Not really an issue for me since we can move panes around how we want to, thankfully.  I"m used to dealing with most things being right-handed anyway, but it's nice when an app thinks of us lefties.

**Comment by gab3d** [comment]
Guys, my thoughts regarding this is as follows: "The sooner the better".

1. I know from my precious experience in OSS development (Blender, Kdenlive, Tux Paint) that the bulk of users really start to test things out when those are included in oficial versions, until that point features are really tested by a small core of users (mostly those who are in a way or another already involved in the development process).
So the real way of "knowing" what users would think of something is making them use that feature.

2. This is not something that could make the software fail in any way, so it can be considered "safe" to let mainstream users try it.

3. If we include the Timeline room in this very next release, by the time of the next version (when curve animation gets included) we should have a pretty solid idea of what users have been saying about the Timeline room initially featured, so we could make the right adjustments to it to make it ultimately "perfect". ;)
On the ither hand, if we don't include it now, we will be really limiting that discussion and triage period to what 4 or 5 people think about it ...for months.

So... all in all I find it much more useful to include some kind of Timeline room now and use the months to come to see what people actualy think about it and be able to further imorove that concept in time for the curve animation release of OT.
I don' t mind if the included room is the one I proposed, @manongjohn's one, or another variant...
It's better to get something out the doors and see what people start saying about it.

**Comment by artisteacher** [comment]
I think we definitely need a room that’s optimized for timeline use, though I personally think there are already more rooms than is necessary in the default room set.  I think agreeing on a timeline layout is the easy part. Both suggestions could work well. However, if a new room is added, we really should make sure the entire set of rooms makes sense. 

This might be too off topic, but new learners really benefit from a smaller selection of rooms. The current defaults probably work well for pros/in a studio setting but are often overwhelming otherwise. I ended up giving my students a custom set of rooms to simplify things for them. All we need is a drawing optimized room (what we use is pretty similar to @gab3d’s timeline room), an animation focused room(a bit reorganized from the default), a history room (so it’s obvious where to go to undo/redo something) and the Browser room. I haven’t kept the cleanup room since it crashes way too much in OS X & we’re not setup to use a render farm.

**Comment by RodneyBaker** [comment]
@artisteacher Your thoughts further demonstrate why this is a big issue to tackle but you also provide a very interesting tangent in that pretty much no matter what the official UI is that is distributed you will always customize it to meet your specific requirements.  That's a very important track.

I've noticed there are at least four other basic tracks users can pursue in the course of getting access to OpenToonz and interfacing with its tools.  To my knowledge they are:

0 Ghibli default   This is the default that OT will install even if all the UI files are missing (delete them and you'll find out)

1 Ghibli default (backup)  This is the one that can be selected by the user when customizing the rooms

2 General default   This is the one that the UI will default back to when users select Windows > Reset to Default Rooms

3 User Room Customization  When the user changes Room settings to include menus this will be saved and will open each time OT is launched

4 The distributed Rooms/UI that studios, teachers and other use to overwrite all the defaults.

I mention these mainly so we have a good view of the foundation under which we are seeking to enhance the UI in meaningful ways.
