### ISSUE TITLE
Github Issue:  Release date of Nightly on official release page is hardcoded 2016 date

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2009]
@shun-iwasawa 

Someone with admin access to the OT github will have to fix this one.
It's caused considerable confusion and requires recurring explaination to those seeing the incorrect date and not wanting to download because of it.

This is likely a setting/personalization in the github preferences but it places the date Nov, 16, 2016 in place of what should likely be a variable that links to the date of the release.  

The fix could be to remove that hard coded date or to locate the correct variable.

Here's where the date appears in a quick look at the html from that page:

BEGIN HTML

```
<div class="release-body commit open float-left">
--
  | <div class="release-header">
  |  
 | <h1 class="release-title text-normal">
   | <a href="/opentoonz/opentoonz/releases/tag/nightly">nightly build</a>
   | </h1>
   | <p class="f5 text-gray mt-1 mb-4">
   | <img class="avatar" src="https://avatars1.githubusercontent.com/u/17974955?s=40&amp;v=4" width="20" height="20" alt="@shun-iwasawa" />
   | <a href="/shun-iwasawa" class="text-bold text-gray">shun-iwasawa</a>
   | released this
>   | <relative-time datetime="2016-11-16T09:53:18Z">Nov 16, 2016</relative-time>
   |  
   | &middot;
   |  
   | <a href="/opentoonz/opentoonz/compare/nightly...master">
   | 1 commit</a>
   | to master
   | since this release
   | </p>
   | </div>
 
```

END HTML

![wrongdate](https://user-images.githubusercontent.com/2576432/40522301-d734db34-5f95-11e8-8a3d-b2faa3f00cdd.png)

**Comment by shun-iwasawa** [comment]
Such time stamp `Nov 16, 2016` is linked to `nightly` tag and is not updated since we reuse the tag for releasing nightly builds. 
Deleting and creating `nightly` tag again will update the time stamp but unfortunately it is difficult to do so because the nightly build will be asynchronously updated by two Jenkins CI - for Windows and OSX.

So, as a quick solution, I put a release date in the title of nightly build.
I hope this will make it easier for users to find that it is released most recently.

![image](https://user-images.githubusercontent.com/17974955/40526952-b27bc71e-6024-11e8-9f7e-f17be97e3ea9.png)

Thank you @RodneyBaker for the suggestion!

**Comment by RodneyBaker** [comment]
Thanks @shun-iwasawa 
That should surely help folks navigate through any possible confusion.
