### ISSUE TITLE
Performance issues with Vector levels

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2016]
### --Issue Summary--

I've recently discovered that I  wasn't having any lag while drawing on a vector level like I did in older versions if all I had were vector levels.

However, I was still getting a lot of lag whenever there was also a Toonz Raster or a regular Raster level in my xsheet.

The performance is significantly bad only where the Toonz Raster/Raster has been exposed in the xsheet

### --Video or Image Reference--
![toonz_raster_perf](https://user-images.githubusercontent.com/19245851/40595949-c8d48716-6205-11e8-8b7a-75ca496e48ca.gif)

### --Steps to reproduce--

1. Opened new scene and a Toonz Vector level extended to frame 20
2. Draw something on frame 1 of Toonz Vector = no delay
3. Add Toonz Raster level and extend to 10
4. Draw something on any frame of Toonz Raster = no delay
5. Draw on frame 1 - 10 of Toonz Vector now and I see significant delay
6. Draw on frame 11 - 20 of Toonz Vector  = no delay
7. Play back frames 1-20 and I see the frame rate drop to single digits between 1-10 and jump up to 24 between 11-20.

Repeated same steps with regular Raster and got the same results.

### --System Information--
+ OpenToonz Version: 1.2 Nightly 5/28/2018, though I verified I see the same behavior in 1.1.3.
+ Operating System: Windows 7 Pro - 64-bit - i7 CPU
+ RAM Size: 8GB

---

**Comment by manongjohn** [comment]
Ah. Ok, that makes sense.   I guess that also explains why OT itself is also slow for me when there is a raster level.  Doing things like playing back the animation, moving around the xsheet over exposed raster frames, resizing panes appears to be causing a complete redraw as well.

Guess until I get a better machine I'll continue to force OT to use my graphics card.

**Comment by jpturcotte** [comment]
It seems `glDrawPixels()` has been deprecated. You can find many hits on Google. Here is one: [https://stackoverflow.com/questions/36534933/gldrawpixels-vs-textures-to-draw-a-2d-buffer-in-opengl](url). Using `glTexSubImage2D()` seems to be the most common replacement.

**Comment by konero** [comment]
Oh, I haven't seen `glDrawPixels` since 2003, @jpturcotte might have a point.

It's been awhile, but I remember Harlequin had this feature '**Minimize Raster Memory Fragmentation**' which was (struggling to remember) actually to do with vector. Does that not help in this case? It reserves a space for raster, is that right? Sorry, I'm probably thinking of something else here.

**Comment by shun-iwasawa** [comment]
@jpturcotte 
Well, I don't think that the simple replacement to using the texture can noticeably improve the performance, because in this case the image drawn with `glDrawPixels()` is not static. When you change current frame, draw on the raster level, or zoom/pan in the viewer, OT updates contents to be drawn.

I once tried (and  suspended in the middle) to fundamentally shift it to "modern" OpenGL way (Texture + VBO + GLSL). You can take a look the [branch](https://github.com/shun-iwasawa/opentoonz/tree/new_viewer) in my remote repo.

@konero 
As far as I see, with the preference option `Minimize Raster Memory Fragmentation` OT allocates some amount of memory on launch in order to handle the raster memory arrangement by itself.
However, the size of allocation is [limited to 1.8GB](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/tsystem/tbigmemorymanager.cpp#L135-L138) regardless of the free memory size. I think this option would become effective when running 32bit version of OT.

**Comment by jpturcotte** [comment]
@shun-iwasawa I remember reading about your doubts on moving to OpenGL 3.3+ because of some drivers' implementations that might make it slower. Of course, you are the expert here, and I defer to your judgment. However, my independent research seems to imply otherwise. Even with the drivers' makers unorthodox implementations, performance gains seem to be expected (source: https://books.google.ca/books?id=Nwo0CgAAQBAJ&pg=PT68&lpg=PT68&dq=is+opengl+core+profile+faster&source=bl&ots=LpPNVmMqm3&sig=0mH8CnOdMaGjVMBs7gtr4Qqcx6Y&hl=fr&sa=X&ved=0ahUKEwjx-Mjo9ezZAhUK84MKHU6wBy8Q6AEIXzAF#v=onepage&q=is%20opengl%20core%20profile%20faster&f=false). Considering that Macs have notoriously bad support for OpenGL, if we take them as a baseline, every Mac from Mid 2007 onwards support OpenGL 3.3 (source: https://support.apple.com/en-ca/HT202823). I think we can safely assume that anyone with a 10 year-old machine can benefit from a move to the modern standard, even if negligible. Of course, newer machines _will_ see benefits. As for `glDrawPixels()`, sources seem ambivalent, but I found at least one who supported such a move: https://books.google.ca/books?id=ckpNmNlLE_sC&pg=PA128&dq=glDrawPixels&hl=fr&sa=X&ved=0ahUKEwjp2LDmvqnbAhWGjlkKHcqNBasQ6AEIKDAA#v=onepage&q=glDrawPixels&f=false. Also, using texture mapping would potentially become the preferred way in light of a move to OpenGL 3.3+. I have consulted other sources that dismissed the argument of the new profile actually being slower due to how the graphic drivers work, and stressing the benefits of switching to the new development paradigm for newer and older machines alike. Now, there is continued support from many in this community for such a move. Knowing that you will not accept bounty money, and that the odds of finding a willing developer with knowledge of both modern OpenGL and this code base on par with yours are close to zero, how could we find a way forward all together?

**Comment by shun-iwasawa** [comment]
@jpturcotte 
Thank you for the motivated suggestion.
I understand that the transition to core profile is recommended and inevitable in the future.
I suspended the transition because I found that it needs quite a huge amount of time for me ( I'm more of "conventional" OpenGL guy and very new to the modern way! ) and OTOH I could not estimate how beneficial the result of transition will be. Therefore, I decided to give high priority to resolve the demands from Japanese animation industry at this moment.
As you suggested, I would much appreciate and will be lavish with technical support if some developer in the community will tackle with this. Opening a new issue for this would be helpful.
