### ISSUE TITLE
Preview unresponsive on scrubbing, selection and load

### ISSUE THREAD

**Issue by JoBoernicke** [opentoonz/opentoonz#2042]
Hey,

# current project

in my current project i got a problem with previewing. OT gets unresponsive on scrubbing, selecting or just waiting for "linear loading".

# Specs:
windows 10 x64
ot nightly build 02-06-18
12GB RAM
AMD Phenom XII BE 3.4GB, 4 cores
AMD Radeon HD 6800

camera resolution: UHD, 30 fps

# Reproduction steps:

okey so this error seems to be somewhat specific, since i didnt find a way to reproduce this error reliably.

- create 12 individual raster-level  frames with 4k UHD camera. 
- copy them via drag&drop to a 2nd column
- circle through different preview modes (viewer preview, preview window)

Results: 

sometimes OT crashes after closing and reopening the previewer multiple times.

sometimes OT crashes when turning on "prievew"-option in the viewer , while opening the previewer.

sometimes OT does not crash (and stays responsive), but turns unable to load rendered frames in the previewer, viewer (preview mode), and is unable to render via output options.

<details> <summary> mostly its a combination.
</summary>

![20180612_091050](https://user-images.githubusercontent.com/15629389/41276500-b1c65dbc-6e24-11e8-9b86-3b56ac331bc0.gif)

</details>

Is there an option to change allocated memory ? maybe this is the issue my pc RAM / GPU is running into.

**Comment by artisteacher** [comment]
It can take a while for the entire preview to load. If you wait a few minutes for the red bar to turn green before trying to play or scrub, does it make any difference?

**Comment by konero** [comment]
Your specs are oldish, I don't think UHD is appropriate for it, can you even play UHD video back smoothly?

There are some things you can do.

Open **File > Preview Settings** and look for **Shrink**.

**Shrink** reduces the resolution when previewing, if the value is **two** it will render one pixel for every two, halving the resolution, so HD 1920x1080 will become 960x540, if the value is **three** then it will become 640x360 when previewing.

Sometimes you only want to preview a specific length of the scene at one time, you can determine the preview length starting and ending frames.

Sometimes you only want to preview a specific area of the screen at one time, for that you can use the sub-camera selection tool located in the console bar, select it and then drag a selection in the viewer. You can find an option called **Use Sub-Camera** which will use your sub-camera selection (and **Shrink** settings) in-place of the Output Camera.

![sub-prev](https://user-images.githubusercontent.com/19820721/41290628-5ff8e024-6e45-11e8-9b41-461231bd3062.png)

Ticking **Apply Shrink to Main Viewer** means the settings will apply to the main Viewer and ComboViewer windows too but you'll have to zoom out manually when using these windows, I only use the main Preview window (**File > Preview**) which allows you to right-click in the viewer and **Reset View** so I leave this off. Using the Preview mode in the main Viewer or ComboViewer is great for previewing single frames.

You can also try different Render Tiles (Small, Medium or Large), try Large.

Alternatively you can create a new low resolution Camera for previewing purposes or rendering out low resolution play blast clips, it's the same thing as **Shrink** does except you have slightly more control.
- Open Schematic (**Windows > Schematic**), create new Camera (**right-click > New Camera**)
- Double click it to open settings, set it to a low resolution (480p, 720p etc)
- I recommend giving it a descriptive name like **PreviewCamera**
- Go to **File > Preview Settings** and change **Output Camera** to **PreviewCamera**

Now when you open the Preview window (**File > Preview**) it will render a lower resolution preview.

These settings also apply to the FX Preview Windows.

I'm pretty sure this stuff is in the manual, though it'd be nice if there was a video created specifically for what preview is as I couldn't seem to find one, what it's used for, how, when and why to use it. Maybe @orphanlast, @DarrenTAnims, NobleFrugal Studio or somebody else can give it a go sometime.

Because depending on what you're doing, it's not as simple as just hitting Preview.

**Comment by artisteacher** [comment]
About the crashing you've experienced - I used to have crashes with Preview all the time. After I started saving all before using preview, the crashing stopped. I don't think I still need to do so but now saving first is an ingrained habit.

**Comment by DarrenTAnims** [comment]
I did put together a short video a while back about using a lower resolution camera to speed up previews. You can find it here: https://youtu.be/Nrm5IuL-_Vk

**Comment by RodneyBaker** [comment]
@JoBoernicke  I haven't read all the responses here in depth so apologies if this has been previously suggested:

From the documentation:
> If the computer performance worsens during the preview process of raster animation levels, try activating the Minimize Raster Image Fragmentation option in the Preferences > General dialog (see Optimizing the Memory Usage ).

Ref:  https://opentoonz.readthedocs.io/en/latest/rendering_the_animation.html?highlight=fragmentation#previewing-the-animation

**Comment by RodneyBaker** [comment]
And just in case... in Preferences there is a "chunk" size that sometimes people change.
The docs have something to say about that as well:

> If you are not using the OpenToonz render farm, dividing the task in chunks not only is useless, but it slows down the rendering process as well. For this reason it is suggested to use a very high Render Task Chunk Size value in the Preferences (e.g. 1000)

.

**Comment by artisteacher** [comment]
My students have run into Preview being especially unresponsive and slow while working with particles. We’ve tried adding a preview camera and it definitely helps. I wish that this could be added by default. 

The current scene camera could be named output camera & a secondary preview camera would also be created automatically  & be set in the preview settings. A preference could allow the output camera to override the preview camera (off by default), for people with a more powerful setup. Or perhaps that would be a scene setting that could be checked or unchecked when creating a new scene.

**Comment by RodneyBaker** [comment]
There have been a few improvements which might alleviate this issue to include having Opentoonz cache information now stored in Windows directory rather than in the stuff directory.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abaondoned
@JoBoernicke please let us know if you are still experiencing this issue.
