### ISSUE TITLE
UX ToolBar

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#2108]
It's just an idea. I want to listen to your opinion. I have long wanted to make icons for our panel and now I was able to make some of the icons. It could look better. 
![untitled-1](https://user-images.githubusercontent.com/25137502/41997288-35f15488-7a60-11e8-82d6-ce46c9d06e67.jpg)
This is how it looks when the tool is active.
![image](https://user-images.githubusercontent.com/25137502/41997323-4fa869ca-7a60-11e8-8672-fd5f2d78b244.png)

Icons are made in vector, if interested, I can send.

**Comment by manongjohn** [comment]
You might want to test these against the light theme. Without the dark outline on your images,  they may blend in too much.

Something to note: currently when buttons become disabled,  they tend to flatten out and have no outlines (see disabled Collapsed button on xsheet toolbar). Because of that, these kind of read to me as disabled.

I do like some icons over others. 

Oh. Also note that some tool pointers match the icon in toolbar. Should those change too?

**Comment by openanim** [comment]
it's funny, I was thinking of opening a discussion about the bar command and its missing icons that would be very beneficial, especially on small screens (maybe you'll be interested ?). Overall, i like your icons, although I sometimes think that some of them are more telling for what they do. For example pinch tool , in my opinion the current icon speaks for itself. This is also the icon found in most of the software I know who does this. Same for me about paint brush tool. What are the icons below as a square ? Is this in anticipation of Krita assistants ?

**Comment by artisteacher** [comment]
In some ways, several of your icons may be more readable, at least on the dark themes. I think the animate tool looks great. The paint roller reads particularly well. On the other hand, many of the existing icons communicate the purpose of the tools a little more clearly. For example, a tape dispenser reads more clearly as tape than a roll of tape does. If I didn’t know where/what the pump tool is, I’m not sure I would identify your icon as a pump. With icons of this size, it’s always such a challenge to balance simplicity and readability with enough detail to clearly communicate.

**Comment by Agnyy** [comment]
@openanim yes, this is  Krita assistants.


Of course, I agree with the majority opinion. I just made a sketch. Ideally, I would like to change a few items in the current panel.

1) Simplify the icons. (This is a more relevant style)
2) Remove the stroke (This will look cooler.)
3) Dedicated tool to highlight blue (This is visually better able to emphasize it and personally for me it has more comfort and increases the mood for work.)

![image](https://user-images.githubusercontent.com/25137502/42019700-77e6755e-7abe-11e8-93ba-3c0790dff9fe.png)

Well, as always, I took all these ideas from the Adobe products.

@konero And what do you think?

**Comment by areckx** [comment]
This gives me further reason to work out a custom icon loader of sorts for OT. Users should be able to load their own icons in on the fly, import/export their custom set right there, and always have the option to load the defaults.

**Comment by openanim** [comment]
This probably raises a design question. I think you should open a topic of discussion on this issue because it seems important to me before you start. Because is it beneficial for Opentoonz to see icons from one user to another that can be theoretically so different? Is it an advantage or a disadvantage? In fact, this may be both but since opentoonz is opensource it is likely to think about it.

**Comment by RodneyBaker** [comment]
Closing this but discussion of potential UI enhancements is always good.
The discussion can continue here or in the OpenToonz forum.  (recommended)

One thing we might do is conduct an annual review of the UI and entertain proposals.
Keep in mind that where it comes to interfaces it might be best to fork OpenToonz and demonstrate the proposal.
