### ISSUE TITLE
layers problem

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2127]
When I made animation I put hand layer in front of the body layer what can I do if I want to put hand behind the body in the same scene. 
Windows 10

**Comment by RodneyBaker** [comment]
You should ask these questions in the OpenToonz forum as this (github site) is for bug reporting and development.

That forum can be found here:

https://groups.google.com/forum/#!forum/opentoonz_en

Since we are here... there are several methods you can use to push and pull a drawing/object forward and back in depth.  One popular very useful one is Sort Order.

(Recommend closing this Issue)

**Comment by animating-dino** [comment]
Thank you
