### ISSUE TITLE
Snap brush issue display

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2130]
### Issue Summary

When enabled  the brush snap will create a trail of multiple images
### Steps to Reproduce
 i created a vector level with brush snap enabled 

![snap cursor brush issue](https://user-images.githubusercontent.com/29790512/42216087-e0f21c3c-7ec0-11e8-8976-054e8060638a.png)
### Expected Results
No trail

### System Information
w10 last OT cintiq companion hd graphics 5100

**Comment by artisteacher** [comment]
I haven’t seen this. What are the tool options for your brush?

**Comment by RodneyBaker** [comment]
This looks a lot like the issue I combined with another one which @shun-iwasawa resolved a short while ago.  See:  https://github.com/opentoonz/opentoonz/issues/2066   

 Although for me at that time the artifacts were red and I don't think I have seen the artifacts since then.
It certainly looks like the same problem.

If we can determine this is related to that I'll close that issue and this one can proceed forward.

**Comment by artisteacher** [comment]
I can't reproduce. Unless I'm missing a step, this might be windows or cintiq specific.

**Comment by manongjohn** [comment]
I can't reproduce this but it appears the green might be coming from the snap indicator circle. Do you get that with snap turned off? Not sure why the snap indicator circle would be doing this since you aren't close to other lines.

My guess is this is kind of related to what @RodneyBaker experienced. His was red, probably because of the red brush size indicator.

**Comment by shun-iwasawa** [comment]
I could reproduce the issue. 
The snap indicator artifacts do not appear while drawing but when moving the cursor over the existing strokes. Also note that the problem tends to occur when the maximum thickness is small (as shown in @openanim 's screen shot) and viewer is zoomed out.
