### ISSUE TITLE
[Feature Request] Option to use GPU for rendering

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#2136]
I tried to search for this feature request, but couldn't find it anywhere, so thought I'd make a new one. 

My GPU is actually more powerful than my CPU, and even Blender I'm able to render anything pretty fast with the help of Cycles -- which is boon, because my CPU tends to heat up and shut down if there is too much load on it. This is generally why I'm limited to setting the "Dedicated CPUs" to "Single" every time I need to render something from OpenToonz. It essentially sacrifices speed in exchange for actually completing a render, which I don't believe is ideal. 

However, I think a GPU rendering can change that, not only for me, but any computer that is low-end but possesses a decent graphics card. The upside to this is that the rendering would be significantly faster in a good graphics card compared to even the best CPUs out there.

**Comment by RodneyBaker** [comment]
Feature requests are no longer posted to github but rather are posted to the OpenToonz forum.  That may be the reason you didn't find the feature request here.

GPU rendering is a known target that OpenToonz developers desire to hit in the future so your request will eventually be granted it just needs a few knowledgeable champions (programmers) to devote their valuable time and effort.  This is no small challenge as a great deal of the underlying code of OpenToonz will need to be rewritten.

Recommend closing this request and continuing the discussion in the OpenToonz forum unless developers working on the issue desire to use this topic to describe the challenges and requirements ahead.

I'll add that while somewhat troubling Apple dropping support for OpenGL and OpenCL and moving to Metal may provide a path forward in that QT will be updating their code to provide support.  As such older methodologies will automatically be jettisoned in the process of adopting that path.  But this is a way of saying that in order to see GPU rendering move forward one key element is going to be that of waiting for Apple to make it's move and then for QT to react.  This can be observed/charted by anyone... no programmer needed so much of the GPU rendering worflow and development at this stage can be accomplished at the user level through research and of learning what lies ahead.

**Comment by tushantin** [comment]
I see... Okay, cool. Please link me to forum I may frequent. I'll close the issue until then.

**Comment by RodneyBaker** [comment]
@tushantin  Here's the link to the official OpenToonz forum.  It's the same forum where OpenToonz launched back in 2016:

https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by age3rcm** [comment]
bumping this,
has gpu rendering been considered after this thread?

**Comment by RodneyBaker** [comment]
Yes, however it requires commitment to development that currently doesn't have a dedicated developer attached to it.  As such progress toward such is incremental.

In some ways this may be the wisest approach because of changes to use of OpenGL... movement to Metal (for MacOs) etc.

It would be good to look to Qt's progress toward support of current standards in GPU rendering as what is encompassed therein can more easily be applied to Opentoonz.

**Comment by Abel032** [comment]
It can definitely speed up the rendering, but it would not be a small task and would require a lot of engagement.
