### ISSUE TITLE
what do you think about the export panel.

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#2150]
I propose to add an alternative export and the function of saving projects. For beginners, this will be a more convenient system. 

Project and Data

![export1](https://user-images.githubusercontent.com/25137502/42423941-c9e59470-830b-11e8-99a8-dbfa3f350542.jpeg)

Image

![export2](https://user-images.githubusercontent.com/25137502/42423946-e91e0962-830b-11e8-97f5-2921ff71f843.jpeg)

Video

![export3](https://user-images.githubusercontent.com/25137502/42423949-ef40c85c-830b-11e8-8499-b52d816cbf59.jpeg)

I think this is a very convenient system, especially if we decide to add other project formats, for example tupi or Pencil2D. It's only a thought, but I think it can be very useful.

**Comment by artisteacher** [comment]
I like the organization though I would probably reorder the tabs so that image was first and project placed last. 

It would probably be a lot of work but the project tab would really benefit from a zipped/compressed format to include both scenes and other assets. I know there are a lot of people that would appreciate being able to easily export an entire project - or sometimes a single scene with all its assets. In those cases, a collect assets checkbox would also be beneficial.
