### ISSUE TITLE
Full Screen View 

### ISSUE THREAD

**Issue by loris16148** [opentoonz/opentoonz#2160]
### Issue Summary
When I switch to full screen mode I am able to draw as I normally would. The advantage of the full screen is that it presents a large working space without the clutter of the window, and all the tabs that simply cannot be removed. I have placed shortcuts for the xsheet, and style editor and other toolbars that I can call upon when I need them to show up on the screen. When I switch to fullscreen mode I am unable to do so. The fullscreen mode allow me to use shortcuts to switch between tools like pencil or eraser or line tools or selector, but i cannot open up any other windows while I am in this mode. Please make this a feature. It will allow for less clutter and more workspace, especially for those on smaller tablets. 

### Steps to Reproduce
Set a shortcut for x sheet, or style editor or any window that you can set a shortcut to. Enter fullscreen mode (default shortcut Alt F). Once in fullsceen mode ( you will know because you can only see the white screen on which to draw and nothing else) press the shortcut you assigned for xsheet or style editor, it does not show.  

### System Information
1.21
Windows 8.1
i7
8 gig
intel intergrated
wacom cintiq 13hd

**Comment by openanim** [comment]
This is a known problem.

Even if it's not full screen mode, you can use the almost full screen mode which allows you to use your tab shortcut. Use the shortcut for the "Toggle maximize panel" command.

The default shortcut on my French keyboard is not recognized. If this is your case too, you can assign another shortcut for this purpose for the command, from custom shortcut panel.

**Comment by loris16148** [comment]
Thank you that helped! i did a small search to see if this was a known problem but couldnt find anything. Do you know if they are progressing with solving the issue.

**Comment by turtletooth** [comment]
This is more of a feature request than a bug.

**Comment by artisteacher** [comment]
If you do open another window (ie. Flipbook) while in fullscreen mode, it doesn’t display until you try to exit full screen mode. Then that new window displays in fullscreen until you close out of it. Yet that’s not a state you can get to otherwise (as far as I know). Personally I don’t open new windows whilst in fullscreen mode but I do think that’s a strange behavior...
<img width="300" alt="619af3dd-902e-4821-8df2-9d2f46e92747" src="https://user-images.githubusercontent.com/21159116/42738412-47bf7f9c-8851-11e8-8f02-416545c9ea45.png">
<img width="300" alt="4899461d-4418-49c5-ab4b-73ca83ae7314" src="https://user-images.githubusercontent.com/21159116/42738413-47def2e6-8851-11e8-8fd8-3a9bf4bd656b.png">

**Comment by RodneyBaker** [comment]
Closing as a feature request slipping to the 2019 development cycle.

**Comment by RodneyBaker** [comment]
@loris16148 
Reviewing this issue in light of recent changes and in particular fixes allowing Full Screen operations without adverse effect such as black screens.

If there are shortcuts that still do not work in Full Screen mode it will be good to re-validate as still being an issue.
