### ISSUE TITLE
Need clarifications Palette/style commands

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2176]
Need clarification about two commands:

1) Adjust current level to this palette.

The way I understand the command is that it is possible to put a value that will serve to match the colors. If it is at 0 there should be no change in principle?

When I use the command, I have a lot of misunderstanding. I do not know if it's buggy or I do not understand.

For example, in case I set the value to 0.
The studio palette loads in the current level but when you write on the canvas until you finish your line, the color matches the style displayed. But once your line is finished, the color is different as if it matched the RGB correspondence made. But in this case, why the style is not updated, too?

When you have a lot of style far from the adjustment value, you end up with the color "red signifying the loss of a style" in the rendering of the lines, for most styles, furthermore styles will continue to display their color of departure without updates, which is very disturbing.

Can someone explain to me how was it supposed to work?

2) Delete unused styles

How and when to operate this command? When I use it it refers me to style number 1 and nothing happens even if the present styles are not used yet.

Is there a bug?

**Comment by RodneyBaker** [comment]
@openanim  
Perhaps you want to discuss in in the OpenToonz forum where we can explore and find out.   ;)

Since we are here though...

Item 2.  Delete Unused Styles
This appears to work for me.
There are occasions where it takes two times for this to take effect.
Note that I am doing this via a shortcut key I assigned to the Delete Unused Styles process.  I assigned (Alt + D)

There is an oddity in using Delete Unused Styles in that if the level is empty even color swatch #1 will be removed which I didn't think was possible.  I hesitate to suggest this is a bug because I think having color swatch #1 isappear might be very useful.  So... don't fix that part yet even if it is a bug!   ;)

I don't quite follow everything you mentioned in Item 1
I'm interested... my brain just isn't ready to work through all of that at the moment.
There are some confusing things about palettes so I'd like to learn more about them too.

**Comment by openanim** [comment]
Well, I continue on the forum, I leave the issue open for now, in case there are unexplained quirks.

**Comment by openanim** [comment]
Ok, I'm waiting for your explanation on the forum

**Comment by openanim** [comment]
Rodney, You were right, it works on vector levels. But it seems that it is a little buggy, it sometimes looks random.

The problem is that quite easily we are wrong, thinking that it does not work.

Here are the two cases that I met. Even if in both cases, it sometimes seemed to work and not work. But overall, I can distinguish the two behaviors. Try if it works for you. I use the last NB.

Case 1: It works

If I first create additional styles before drawing them. The command seems to work every time.

Case 2: It does not work

If I draw before and then I create a new color, I redraw, I create a new style ... etc.. the unused styles are still there and I am returned to style 1.

About raster level, the command delete almost all styles regardless of whether they are used or not. I guess it's because indexes are not counted on this level. In any case we can not really say that it works.
