### ISSUE TITLE
Insert or extract node with alt does not work properly.

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2181]
### Issue Summary

I open a specific issue for this bug.

normally  to insert a node into a link we can do Alt click and drag it into the  link, and to extract a node from a link, Alt click and drag it away from  the link. But the behavior no longer works, to put the link correclty.  However, as long as we have not permanently dropped the node, the  behavior still seems to be there. Is it possible to bring it back ? it  looks like a bug.
### Screenshot or Video Reference

![alt_node don t works](https://user-images.githubusercontent.com/29790512/43050525-5ecd973c-8e0a-11e8-9cd6-23850f45ade8.gif)

### Steps to Reproduce

hold the alt key and try to incorporate the nodes automatically, it does not work.

### System Information
* **OpenToonz Version**: 1.21
* **Operating System**: w10

**Comment by manongjohn** [comment]
When was the last time this worked?  I went back to OT 1.1.3 and it wasn't working back then either.

The code that handles removing it from the link (and presumably relinking it) hasn't changed since OT was released, as far as i can tell. It's possible something else in the FX schematic viewer change that was unrelated to this feature had a bad side effect.

**Comment by openanim** [comment]
Oh, I'm sorry, for this extra work, useless! I just understood ... it's Harlequin that does it.

I also went up to 1.0, because I was convinced that it did but I confused with both, sorry I am I was wrong. I close the problem.

**Comment by gab3d** [comment]
Toonz 7.1 does it, so shouldn't OT also do it? 
At least I understand OT is based on that version.

Another thing Toonz 7.1 does is automatically displace the right part of the node tree, when inserting an FX node to a column node. That could also be great to have back again.

**Comment by manongjohn** [comment]
I wonder if it was broken at the time OT went open source and they fixed the issue in Harlequin afterwards. I kind of consider it a bug since the code appears to support this behavior but isn't currently working.

I think I partially know why its not working, but would need time to see if i can easily fix it

**Comment by gab3d** [comment]
@manongjohn 
I don't think so. 
The Toonz 7.1 version I've got is from 2014 and it works ok.

**Comment by openanim** [comment]
I re open the problem, in this case.

**Comment by manongjohn** [comment]
@gab3d I don't recall what version OT branched from Toonz Harlequin. At any rate, I just installed OpenToonz 1.0, the original release when it went open source. (Wow has the look of OT changed...and for the better!) Unless I'm doing something wrong, this feature has been broken in OT since day 1.

**Comment by openanim** [comment]
At the very bottom of the link, Shun iwasawa said that this is the 7.1 version of Harlequin.

**Comment by shun-iwasawa** [comment]
The feature may be unintentionally dropped off when I developed Toonz Ghibli Edition based on Harlequin 7.1. I'll investigate on this.

**Comment by shun-iwasawa** [comment]
OK, I found why this feature is disabled.
It is because the connection lines between nodes are placed behind the nodes in OT, whereas the lines are placed on top of the nodes in Toonz Harlequin. 
While dragging, the function [QGraphicsScene::itemAt()](http://doc.qt.io/qt-5/qgraphicsscene.html#itemAt) fails to pickup the connection line ( which is to be an insertion target ), because the dragging node itself is always on top of the lines.
I'll try to modify this, by swapping the stacking order of the nodes and the lines only when Alt key is pressed.
