### ISSUE TITLE
Tape tool issue display in rectangle mode (Bounty $50)

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2190]
### Issue Summary

When you open OT the first time and try to use tape tool in rectangle mode, you will not see the rectange.

### Steps to Reproduce

Create a level and try to use the tape tool, you need severals tests to see the rectange displayed.

W10 cintiq companion 2 HD graphics 5100 OT 1.2.1

**Comment by RodneyBaker** [comment]
@openanim  With the current updates/fixes to the Tape Tool it would be good to review this issue.
Is this still a problem?

**Comment by openanim** [comment]
@RodneyBaker  the problem is always present. He is also in harlequin. The problem is easily visible when trying the tape tool after opening OT, in my environment. It disappears when my cursor touches the borders of the other panels in red on the image. But it comes back at times, for some reason I do not know.

![tape tool issue display](https://user-images.githubusercontent.com/29790512/47998412-82c48680-e0ff-11e8-8356-a510bd9f0ead.gif)

![sans titre](https://user-images.githubusercontent.com/29790512/47998954-37ab7300-e101-11e8-95c2-5542ad33968b.png)

**Comment by manongjohn** [comment]
@openanim It looks like you used a shortcut to switch to Tape Tool. Do you get this same issue when selecting from tool bar directly or only when using shortcut?

**Comment by artisteacher** [comment]
Maybe this is part of #1216? I can't see rectangular select/fill/erase or etc. on my high resolution monitor because the lines of the rectangle are so narrow. It's been an ongoing issue.

**Comment by openanim** [comment]
@manongjohn Yes, the problem appears when I use a shortcut. I did not notice a problem if I use the tool panel. However, if I use the shortcut again the problem may reappear at any time. But it looks random.

**Comment by shun-iwasawa** [comment]
The probable cause of this bug seems to be as follows:

- `VectorTapeTool::draw()` is interrupted if `bool VectorTapeTool::m_draw` is false. ( [here](https://github.com/opentoonz/opentoonz/blob/ed7dcd58739dd496bfa75b974981bde60230d47f/toonz/sources/tnztools/vectortapetool.cpp#L279) in the source )

- `m_draw` is set to true only in `VectorTapeTool::onEnter()` ( [here](https://github.com/opentoonz/opentoonz/blob/ed7dcd58739dd496bfa75b974981bde60230d47f/toonz/sources/tnztools/vectortapetool.cpp#L736) in the source ), which is called when the cursor enters the viewer.

So, when you toggle the tool via shortcut while the cursor already in the viewer, `m_draw` remains false and the `VectorTapeTool::draw()` is interrupted before drawing the rectangle.

`m_draw` has been introduced from Toonz Harlequin source and I'm not sure what was the original intent... According to [the Italian comments in the source](https://github.com/opentoonz/opentoonz/blob/ed7dcd58739dd496bfa75b974981bde60230d47f/toonz/sources/tnztools/vectortapetool.cpp#L328-L330) , they might try to solve some tablet-related problem with it:

```
    // BUTTA e rimetti (Dava problemi con la penna)  --- Throw away and put back ( Facing problems with pen )
    if (!m_draw) return;  // Questa riga potrebbe non essere messa --- This line may not be put
    // m_draw=true;   //Perche'??? Non basta dargli true in onEnter?? --- Why??? It is not enough to give it true in onEnter??
```

**Comment by jpturcotte** [comment]
I have just posted a $50 bounty: https://www.bountysource.com/issues/61285413-tape-tool-issue-display-in-rectangle-mode.

@RodneyBaker Could you update the title of the issue and add a tag, please? Thank you!
