### ISSUE TITLE
Problem with hidden column after deletion of frames on that column

### ISSUE THREAD

**Issue by loris16148** [opentoonz/opentoonz#2202]
### Issue Summary
Every time I create a new raster level (has not been tested with other levels) and then I make the column that contains that raster level invisible, then delete it. I cannot use the column again. I have to delete it and start over. Not a big issue but maybe a bug. 

### Screenshot or Video Reference

![opentoonz 1](https://user-images.githubusercontent.com/6901805/43354643-0212187a-9205-11e8-8ed4-db1833b0f1ee.gif)

### Steps to Reproduce
Create a new raster level in any column. Write something on the raster level. With the raster level still there, make the column preview disabled and make the camera view invisible by clicking the eyeball and the camera icons in the column header. Delete the raster level. Try to create a raster level again on the same column...unable. 

The raster level CAN be created by right clicking and using create raster level function. This does not work for auto-creation function when you touch the screen with the pen-tip. 

### System Information
* **OpenToonz Version**:  1.2.1   july 28 2018 build
* **Operating System**: Windows 8.1
* **CPU**: i7
* **Memory**: 8 Gig
* **Graphics Card**: intel intergrated
* **Graphics Tablet**: Wacom Cintiq 13

**Comment by beeheemooth** [comment]
You deleted the frame, but not the level. He's still present and the column is still busy. Look in Scene Cast and select Expose in Xsheet, then turn on visibility.
If you want then delete the level, and it will be deleted along with the column.

![ezgif-3-98835cc423](https://user-images.githubusercontent.com/25724133/43355392-07d0646a-9264-11e8-9525-dc74533d15f3.gif)

**Comment by RodneyBaker** [comment]
Loris,
The entirety of the xsheet is for exposing levels/images (and audio,notes, etc).
The term xsheet is short for 'exposure sheet'.
The columns are just ways of organizing those exposures in ways that make managing and manipulating the easier.

As a community we could do more to educate people about this because there are a lot of misconceptions because people's experience is from other programs that don't have the same capabilities or workflow under the hood.

Unless I'm misunderstanding, the header of the column can't disappear... it's just an empty container waiting for something to be placed inside it.  It's like a row or column in the spreadsheet program Excel... that is always there but not used until data is entered into a cell.  Columns can be folded and/or Collapsed though if they get in the way.  Then they can be unfolded/opened a necessary.  So that's one way we might 'disappear' unwanted columns.  When collapsing columns into a subxsheet that subxsheet can then have a new descriptive name that describes its contents.

**Comment by loris16148** [comment]
Ok fair enough. The premise is that the header of the column cant disappear. When I talk about the header of the column, im specifically referring to the place where the name of the column, the icons for visibility toggle of the column, and the opacity settings are contained. When you remove the frame this area visually does disappear (as it should because there is no data in it - see the video). As beeheemooth demonstrated, when an exposure/frame is deleted from it, it is still not quite "deleted", one must go to this "expose in Xsheet setting" and delete it from there. 

my issue with this whole thing is that once that exposure is deleted, with the column settings in invisible mode i cant create a new frame on it using the autocreate-with-touch-of pen-tip-function. If I cant explain this adequately enough for it to be well understood, please replicate the steps in the order I mentioned. Note I am using the wacom cintiq pen. If you are a raster level user this should be immediately apparent as a glitch of sorts! I cant see a logical reason why it should behave this way.

**Comment by manongjohn** [comment]
This is a bug. The column was deleted (no header) but the properties of the column itself was retained from before and shouldn't.

**Comment by RodneyBaker** [comment]
Agreed.  The only place that data should be stored upon deletion is in history for the purpose of Undo.
