### ISSUE TITLE
Crash upon Render

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2206]
### Issue Summary
This is something of a one off crash but it hints at something much deeper that I'm confident can be addressed.

### Background
In this case I was working on a short animation and had saved everything about half way through and had rendered out a sequence... looked at it and determined I needed to adjust the timing slightly. 
 At this point I should have thought to Save but I did not and pressed on.  I adjusted something minor such as the FPS in Output Settings (changing most likely from 50 to 100 to double the sequence time) and didn't bother changing the target file, choosing to overwrite the previously rendered file.
OpenToonz then crashed and all changes back to the prior save were lost and perhaps worse in my estimation... the render failed and in the process it removed the previously rendered file.

So... user error on several fronts.
I'll try to do better next time.

I do want to use this report to suggest we review the Save process because I'm confident we can reduce the loss of files significantly and I have some experience to back up this claim.  I recommended the following addition to another (3D animation) program and it was initially added as an option and later made a default.  Most importantly the loss of files largely ceased to be a problem.... at the initiation of a critical process... rendering to file.  I know this falls under Feature Requests but it specifically is suggested in order to address crashes and lost files and as such I hope it will be accepted as such.

### Suggestion
Because rendering is such a critical process and any failure during that long event can lead to lost of data an option to automatically Save before the render process continues may prove to be optimal.  I do recognize there are times when renders are desired and the user doesn't not want to save so the option to Save before Render should be optional.  If files are saved before render not not only will the files be secrure but any excess memory being held will be freed so that can be used by the renderer.

A more complete review of the entire Save process from beginning to end should be conducted but it is probable that a focus the moment just prior to rendering will lead to resolution of a majority of crashes and lost files and increase over all stability.

Thanks!

As for my recent crash:
### System Information
* **Latest Nightly build as of 20180731**: 
* **Win10**: 
* **16GB (roughly 12 available)**: 
* **Intel Graphics*: 
* **Wacom**:

**Comment by DarrenTAnims** [comment]
I couldn't agree more. I've been hit by this and I consider myself pretty methodical to saving regularly and saving before large processes like rendering, but I sometimes forget, so a forced save would be great.

**Comment by loris16148** [comment]
I have my autosave set to 5 min, and i also save religiously..in spite of all that it happens to me too, anything can wreck this software because its so temperamental. Also since were on the topic of autosave (well since im on the topic) id like to recommend that we move it to the back, so i dont get this prompt popping up and interrupting my workflow each time. Sometimes when it pops up, it crashes OT if im entering the preview mode or doing something CPU intensive. I have had so many things cause crashes in the last two weeks that I can write a novel about them....

**Comment by RodneyBaker** [comment]
I have had so many things cause crashes in the last two weeks that I can write a novel about them....

Please do.  That way we can get them fixed.  :)

Crashing for me is pretty rare and I often get a sense it's about to happen just beforehand because I'm trying to do too many things at once.  OpenToonz is trying to keep up but it takes time to process everything so it's good to Save before every major event.   That's why I'm suggesting a Save on Render would be useful.  Of note, When using the (local) Farm to render @DarrenTAnims noted a significant speed up and... noteworthy... the Farm works with Scenes that are already saved.  So, that's a proof case.

I'll go out on a limb and suggest that Autosave set to 5 minute increments is a major factor in your current crashings.  This is easily testable but I don't suggest testing that while in the middle of a production deadline.

**Comment by animating-dino** [comment]
I always copy the project file itself because I try to do save all in my projects and it corrupt all my animation.

**Comment by loris16148** [comment]
so basically ive been using all the workarounds that i can....i dont render preview in OT because once it renders maybe 40 frames it crashes. this number is completely random, sometimes it 200 frames. what i do is just preview the one frame to see how my effects are working...if I do this too many times, preview the one frame....it crashes at a random point during my project.

 I have gotten into the habit of using CtrlS...but its not enough. I can set the autosave to 15 min but i risk losing too much of my work, 15 min of work is a lot!!! I dont see how autosave is causing crashes...and how is it different from me pressing ctlrS every 5 min. 

so far in the last month or so of work....(im working on a large project), OT has crashed multiple times on the most ludicrous things, i posted the events that cause consistent crashes, but about 80% of those crashes i cant reproduce again so i cant catch them to record them. Sometimes ill lay down a single pen stroke and it will crash. sometimes its when i automate an fx change or something like that. Its not like there is a lot going on. Most of my work is in raster or toonz raster images. 

now my project is all one project, so i thought that may be it, but so far i have not seen that extending the length of the project causes an increase in frequency of crashes, it has been the same since scene 1 to scene 7....just random acts of terrorism on my project...

anyway it is what it is.
