### ISSUE TITLE
Full Screen: Black combo viewer

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2215]
### Issue Summary
when I am using opentoonz, I goes to fullscreen then viewer go black

### Expected Results
 I expected it to be normal

### Actual Results
 program's viewer goes black

### System Information
* **OpenToonz Version**: 1.2 and 1.2.1 and lastest relases
* **Operating System**: win 10
* **CPU**: quad i5 core
* **Memory**: 6 gp
* **Graphics Card**:intel 4000
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
Did you post the correct screen shot.? 
There's no time in the process shown where any screen turns black.

**Comment by animating-dino** [comment]
I dont know but gif ca't record because I went fullscreen.

**Comment by animating-dino** [comment]
here is the screenshot
![opentoonz 1 2 1 04_08_2018 03_01_28](https://user-images.githubusercontent.com/39278532/43670983-e88c5fa8-9792-11e8-857a-3a38dd691e29.png)

**Comment by RodneyBaker** [comment]
I ran into something similar a few days back.
The only thing I can think that possibly fixed the issue was a running a clean install.
I was doing that clean install for other reasons and it just happened to make the problem go away.
So the first thing I would recommend is using the accompanying uninstall program that come with OpenToonz and then also renaming your OpenToonz stuff directory, which forces the installer to create new files.  What I often do is just append the stuff folder with the current date and then place that renamed stuff directory into a holding directory so that any project I might need to find I can search for by date.

If this is similar to other issues that produce a black screen it likely relates to OpenToonz not being able so find/read some of the interface files found in the QSS directory of the stuff folder.

If you are interested in using Teamviewer or similar program to allow others access to your system in order to assist I am willing to do that.  I just ask that you back up any important OpenToonz files before you do.

**Comment by animating-dino** [comment]
It didn't work but in #1638 problem
when turtle tooth do the modified build 5.9 IT fixed my problem 
but it's old 1.2 version.

**Comment by manongjohn** [comment]
That's not an issue with missing QSS config. 

As you are on Win10, if Win10 updated anything recently, I would strongly suggest updating your video card drivers. It seems Win10 has been known to do something to mess them up for a number of users. I've seen reports of Win10 update issues happening on other drawing software also, all usually surrounding display/video adaptors.

For now, if you have another video card on your machine, i would switch to that and make sure you set it for High Performance (NVIDIA) or equivalent. That was the only way I was able to fix the blank viewer issue when 1.2.0 was initially released.

**Comment by animating-dino** [comment]
If I have intel only should I down grade to win 7

**Comment by animating-dino** [comment]
I upgraded my graphic card twice to test.
but in problem #1638 I think the problem in it is causing the lag.

**Comment by animating-dino** [comment]
if I try my nvidia card and go fullscreen and exit the resolution became weird and nothing work.
since i upgraded to 1.2

**Comment by RodneyBaker** [comment]
Can you post the link to the download for v1.2 that you are using?
I ask because 1.2 is not the most recent release of OpenToonz and it would be good know know which specific release you are using.

**Comment by animating-dino** [comment]
the one the have no problem turtle tooth build in #1638 https://drive.google.com/file/d/1fx6ZEzraweA1m3XxZZFY4Grem6gDRO01/view?usp=sharing
and that don't work all the other

**Comment by openanim** [comment]
Is this similar to this problem? It may be necessary to leave the full screen mode if this is the case.

**Comment by animating-dino** [comment]
Yes it's similar.

**Comment by animating-dino** [comment]
So how the build of turtletooth work. 
 https://drive.google.com/file/d/1fx6ZEzraweA1m3XxZZFY4Grem6gDRO01/view?usp=sharing

**Comment by RodneyBaker** [comment]
There are several Full Screen and Black screen reports still outstanding and most relate to OpenGL in some form or fashion.  Going forward we'll try to make sense of them all and see where additional patterns turn up.

Ref:  #1692

**Comment by GabrielCambe** [comment]
I just got a similar error on linux mint. The default rooms are blacked out except for Browser and Farm

**Comment by manongjohn** [comment]
This appears to be the same issue as #2796

@GabrielCambe Do you also have problems putting just the viewer in Full Screen mode (Alt+F)?

**Comment by GabrielCambe** [comment]
In full screen i got a black screen as well. I was working on an environment where i had a memory quota so i deleted the .config directory and rebooted Opentoonz and all returned to normal

**Comment by GabrielCambe** [comment]
A curious thing that happened is that, when i positioned the mouse on the rooms selection bar, the elements started appearing and when i changed the room to the farm room the other windows on the views appeared as well. But when i returned to the main room it all went to black again. Unfortunately i cannot reproduce it since i had to basically reinstall it, I'm sorry.

**Comment by RodneyBaker** [comment]
@GabrielCambe  Glad to hear you got your issue resolved.

Yours is a good example of how replacing the Opentoonz Stuff directory from time to time can resolve issues.  Consider that when we remove/backup the Stuff directory and install a fresh one that the config directory is GUARANTEED to be updated.  This is important.

When dealing with serious problems, especially those that slow down production it is important that we consider cleaning out the cobwebs of older settings.  Then we can better focus on the actual issues and our pressing production needs.
