### ISSUE TITLE
opentoonz glitches

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2217]
I am having problems with opentoonz and many glitches
I upgraded my graphic card two times 

### Issue Summary
 I have many problems and gltch

### Screenshot or Video Reference

![bwehqq](https://user-images.githubusercontent.com/39278532/43691345-5d8a5236-991b-11e8-9f88-827d202e835d.gif)

### System Information
* **OpenToonz Version**:  latest
* **Operating System**: win 10
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by shun-iwasawa** [comment]
The Style Editor shrinking behavior seems to be the similar to #1954 .
Can you please list the problems and glitches other than that?

Also please let us know which graphics card you are using.

**Comment by animating-dino** [comment]
my style editor when switching to vector,raster and texture will be glitchy
toggle  full screen and exit it will glitchy .
nvidia geforce 630m in a laptop
intel 4000 
latest drivers.

**Comment by RodneyBaker** [comment]
We need to take a hard look at the Nvidia part of this equation (although other system variables factor in as well)

The fact you are experiencing so many problems while others experience relatively few is a clue that we should hone in on.  Namely, what is different in the system you are using versus other users?

**Comment by RodneyBaker** [comment]
Do you have a friend that has a computer you could test on?

You could use a portable release so it doesn't even need to be installed on their computer.

The important thing is you need to be able to see OpenToonz working as it should so that you can compare that to your current problems.  It seems to me you are chasing your tail a lot here.

You've stated several times you have updated drivers and that usually fixes these types of issues.
It may be that you need to back off a driver release or two.

As you have two cards on the same laptop perhaps the one is interfering with the other?

More stabs in the dark:  In other software in the past that had similar issues I turned back the OpenGL settings so they weren't the lastest and greatest and that got me going again until the proper drivers were released and things could get back to normal.

**Comment by RodneyBaker** [comment]
That is an option.
I can only tell you what I would do if I were in your position.

The very first thing I would do is update my drivers to the most current available which you've stated you have done.  That usually fixes any issues although occasionally it does not.
In a  few very rare instances I have had to back off drivers to an earlier state and that helped in the short term.

Was it you that said a particular release was working for you?

There are still a lot of variables that haven't been ruled out.
I don't have anything against NVidia but I've had few graphics glitches since I stopped using them many years ago.  As a disclaimer, it wasn't my intention to stop using NVidia cards, I just started buying computers that didn't have NVidia cards in them.

**Comment by animating-dino** [comment]
yes and because my nvidia graphic card it old.
maybe they put they intention in new graphic cards.
ok I will try.

**Comment by RodneyBaker** [comment]
Good luck.

I will note that your other issues all appear to be fully related to this same issue (#2217):

For those trying to keep track, those other two issues are :  #2204 and #2215

**Comment by RodneyBaker** [comment]
Another question.

When was the last time you did a clean install of OpenToonz where you have uninstalled OpenToonz using the uninstall utility that comes with OpenToonz (found in the install directory) and then also removing the Opentoonz stuff folder so that the installer is forced to install everything new?

A clean install is highly recommended if you have not done this.

**Comment by animating-dino** [comment]
I do it once not work.

**Comment by manongjohn** [comment]
Are you using multiple monitors? What is your display resolution? What is the refresh rate on your monitor?

Searching on-line, i found a number of win 10 users that have similar problems with other games/applications that show black or oddly drawn screens when in full screen mode, but normal otherwise. However, i have yet to see a definitive way to fix it.

Aside from driver updates, some suggest fix resolution. Some say fix your display's refresh rate. Might want to search online and try out some suggestions that are out there.

**Comment by animating-dino** [comment]
I am using laptop one monitar
