### ISSUE TITLE
RGB picker tool create offset

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2238]
### Issue Summary

RGB picker tool create offset

- create a vector level.

- apply  a vector style

- use the rgb picker tool on one of your styles. You will notice a shift as you use it.

### Expected Results

No shift

### System Information
w10
* **OpenToonz Version**: Last NB
Cintiq companion 8 g

**Comment by RodneyBaker** [comment]
Thanks not a bug... it's a feature.  :)
(I've always wanted to say that!)

I do want to thank you because you've pointed out a very useful feature of the RBG Color Pick Tool that I had not considered.

First, Right Click on a color swatch and open the Palette Gizmo.
Look at the bottom for the Fade setting.

I believe this is the offset you speak of and each time we select the stroke with the RBG tool it will apply this Fade.  Keep selecting it repeatedly and it will begin to fade away entirely.

If this is not what you are talking about.... still... a really cool feature.  :)
Please disregard.

**Comment by openanim** [comment]
Sorry, I was not precise enough. This is a decal on the viewer. In addition, if you use your mouse wheel zooming in or out, when you use the rg tool, it will behave like a magnifying glass tool. Which is very weird.

To reproduce:

create a vector level
with several styles

Apply a vector style (trail / custom or brush vector ...)

Use your rgb to change a color of one of your modified vector styles

you will see the problem.

**Comment by openanim** [comment]
![problem_offset rgb picker](https://user-images.githubusercontent.com/29790512/44068164-0794d61c-9f79-11e8-92a4-1d0f36c6b05a.gif)

Yes, here is a mini gif to visualize the problem

**Comment by openanim** [comment]
The problem also exists with the raster level but I can not reproduce it.

**Comment by openanim** [comment]
close for duplicate sorry #1717
