### ISSUE TITLE
OT lipsync workflow unusable

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#2258]
Opentoonz lipsync workflow via different mouthshapes as frames in one column via sceleton tool and "animate" is unsuable or let me say a real pain.

It is nearly impossible to move a frame backward without first deleting the frames before or moving it forward without moving all following frames with it.

The common lipsync behavior (ToonBoom Harmony, Moho, Flash, Maya and many others) is that you can move a the key for your phonems freely around without destroying the keys bevor and after.

And if you change a phonem it should change the whole range till the next phonem, not only one frame.

Opentoonz is about animating, but it seems, that the focus these days is more about drawing and brushes

This is a serious issue

**Comment by RodneyBaker** [comment]
Lipsync is very useable in OpenToonz.
Perhaps you can share a video of your specific workflow and suggestions can be made to improve that workflow.

Short of more information I will recommend using the Q and W keys to quickly move through the phoneme shapes in your lipsync images/level.  That is a very fast process.

Start a topic in a topic in the OpenToonz forum and shed some light on what you'd like to see for lipsync going forward.  One of the reasons brushes recently got attention is because the subject of brushes was being discussed there in the forum.  :)

https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by bobbybutterfly** [comment]
imagine frame 1 is "A"
frame 10 is "B"
frame 20 is "C"
frame 30 is "D"
now change "B" to "D" result: "D" is on 10 and "C" is on 11(!)

but the idea was "D" on 10 until 19 and "C" stays on 20

**Comment by RodneyBaker** [comment]
Select the frames you want to change and and hit the Q or W keys to change them.
For instance...

Select all the frame you want to change from B to D and press the W key twice.
The first press will change the frames to C... the second press will change them to D.

Do the same for any other changes needed.

**Comment by beeheemooth** [comment]
@bobbybutterfly You need to select ALL frames before the next phoneme, and apply "Drawing Substitution ..."
![ezgif-4-5b96863385](https://user-images.githubusercontent.com/25724133/44628702-d8392600-a94d-11e8-8fb9-1d360ad791a3.gif)

**Comment by bobbybutterfly** [comment]
@RodneyBaker @beeheemooth 
thank you very much for your quick response

Q + W in connection with "drawing substitution forward" and especially "similar drawing substitution forward" solved my problem to change "D" for all 10 frames at once:)


I am happy now and i think we should delete this issue or transfer it to the OT Forum instead
