### ISSUE TITLE
cant make a right clic in the timeline between 2 keyframe

### ISSUE THREAD

**Issue by z-uo** [opentoonz/opentoonz#2261]
### Issue Summary
In the timeline, I can't make a right clic in the cell between 2 keyframe (with the tiny white line) except on the upper part of the cell (watch the red zone on the screenshot below)
in the xsheet the forbiden zone is only around the white line ( which is less a problem)

### Screenshot or Video Reference
![capturerc](https://user-images.githubusercontent.com/652668/44657122-12f99780-a9fc-11e8-9651-1a733f2a3964.PNG)

**Comment by manongjohn** [comment]
I'll see if I can address this with #2262.

The issue here is the context menu for the keyframe line takes precedence over the cell's context menu.  When zoomed out that much, the area of keyframe context menu activation takes up most of the cell.

I might need to combine context menus to make it easier to access either the cell or the keyframes.

**Comment by z-uo** [comment]
But there are no context menu for the keyframe line? 
And yes with the timeline zoomed in there is only a little space that is not clickable.
