### ISSUE TITLE
Toonz Raster level antialiasing issues

### ISSUE THREAD

**Issue by Wolfinabowl** [opentoonz/opentoonz#2270]
### Issue Summary
I am unable to use any of OT's antialiasing methods on Toonz Raster levels without filled areas bleeding through lines. This includes both the antialising setting in the Level Settings dialog box and the Apply Antialias setting in the Level drop down.

For the time being I use PSOFT's antialiasing plugin for After Effects, but this means that I cannot use many of OpenToonz's effects -namely any that blur- as they cause issues with it.

### Screenshot or Video Reference
Example of the artifacting using high-contrast colors; here you can see the red area overlapping with the green area, also note the green area bleeding through the black line on the right. This occurs on any softness value over 1.
![anti aliasing issue](https://user-images.githubusercontent.com/42905003/44952814-942bb100-ae78-11e8-9bfe-5361090fb174.PNG)!
This is the transparent view; here you can see that the artifacting occurs where the line is present.
![anti aliasing issue 2](https://user-images.githubusercontent.com/42905003/44952845-38155c80-ae79-11e8-94f8-a97cf0e8d45c.PNG)!

### Steps to Reproduce
Apply antialiasing to any Toonz Raster level that has filled areas and using a softness value over 1.

### System Information
* **OpenToonz Version**:  1.2.1
* **Operating System**:  Windows 10
* **CPU**:  Intel I7 5820k
* **Memory**:  16gb DDR4
* **Graphics Card**:  GTX 980
* **Graphics Tablet**:  XP-PEN Star 06

**Comment by noccu** [comment]
Having the same issue on both latest stable and nightly. With and without autopaint lines.
It's obvious even with much less contrasting colours.
Strangely it seems to go away when adding the Color Blending node in the fx scheme, set to an unrelated index. (Removing the indexes entirely seems to remove all lines, making them transparent. That's not an intended effect either, is it?)

Source, autopaint on the right:
![source](https://user-images.githubusercontent.com/37862870/47612266-9163cb80-da77-11e8-85cd-f8da6f851442.png)
Issue:
![issue](https://user-images.githubusercontent.com/37862870/47612265-9163cb80-da77-11e8-89d5-76d87f6fa62c.png)
Adding the fx node:
![fx node fix](https://user-images.githubusercontent.com/37862870/47612264-9163cb80-da77-11e8-9f8d-7806b6b6aa32.png)

**Comment by shun-iwasawa** [comment]
Antialiasing set from the level settings is actually applied [here](https://github.com/opentoonz/opentoonz/blob/25d3db05fd57aed51d666455ac8dbc44067a4cea/toonz/sources/toonzlib/tcolumnfx.cpp#L1161-L1166) in the source.
The problem is that when processing the toonz raster level (cmapped raster), the antialised result of `TRop::antialias()` is also cmapped raster, which is fundamentally impossible to get the proper antialiased result.

I think we can fix the issue by converting cmapped raster to full color raster just before applying antialiasing. It seems that `Toonz_Level` type fxs ( like `Palette Filter fx` ) are applied before this process so I think it will (hopefully) not cause any bad side effect.

**Comment by jpturcotte** [comment]
cc @blackwarthog & @morevnaproject

**Comment by noccu** [comment]
@shun-iwasawa Sorry to venture outside the scope of github a little but in the hopes of contextualizing this bug report somewhat...

I stumbled upon this issue in my search of antialiasing options for painted binary/mono-trace toonz raster levels within OT (i.e. "finished" cels). This AA setting being the only one I could find, but it does not appear standard practice and obviously suffers some bugs.
With this aliased workflow apparently the standard in the Japanese industry and generally referred to in OT docs/tuts as well (and GTS outputting it), the (re-)antialiasing/smoothing required afterwards is not straightforward with little info available. Does OT even intend for this to be done inside it or be used this way?

Could you provide some insight into this process and OT's usage of AA in various places?  I presume others may be interested as well in better understanding the intent and capability of program features.
 I had a look at the sample project provided but that eventually made me none the wiser, perhaps it followed a different process in the first place, preferred for OT?

**Comment by shun-iwasawa** [comment]
@noccu 
As you pointed, it is true that the aliased image is used in Retas PaintMan and is de facto standard in Japanese animation production workflow. The AA settings can be used to adapt OT to such standard workflow, especially on using OT for composition in place of AfterEffects. However, in such case, the AA operation is applied to the raster level (TGA images painted with PaintMan) and it works with no problem.

If you use OT in whole workflow (i.e. scanning with GTS, ink&painting and compositing with OT), antialiasing would be applied usually when cleaning-up the scanned images.

I think this bug is somewhat urgent, but had not came to the front for above reason.

**Comment by gab3d** [comment]
@shun-iwasawa 
I also see this as very important. 
We are starting to base all our main workflow around OT and being able to add antialiasing to Toonz raster levels is key for that to work. 
I suppose what you've proposed of converting toonz raster to raster just before applying the antialiasing would be the right way to achieve it. ✌️  and if that occured at the very end of the column processing stack it'd be the best.

Thank you for all your efforts!
