### ISSUE TITLE
Can't draw on a plastic mesh-deformed drawing on the xsheet, but you can from the level strip

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#2300]
### Issue Summary
If I've drawn something, then apply a plastic mesh on it, then want to edit the drawing (not to change its size, just to edit the look of it) I can't. But I can using the level strip, which feels like a workaround.

### Screenshot or Video Reference
![screencapture](https://user-images.githubusercontent.com/28575907/45819485-52a25f00-bcdc-11e8-8d0d-ca78846213b7.gif)

### Steps to Reproduce
Create a level (in my video above, I created a vector level
Draw something
Using the plastic tool, create a mesh
select the drawing on the xsheet, try and draw something on it
The dialog pops up: "The current tool cannot be used on a mesh-deformed level"
But you can then select the drawing in the level strip and draw on it and it'll deform just as well!

### Expected Results
I'd expect to be able to draw as much as I like on the drawing after selecting the drawing column on the xsheet (but only the area originally covered by the mesh would be deformed). This means I can draw relative to the other columns on screen, instead of drawing in isolation.

### Actual Results
When trying to draw, I get the popup.

### System Information
I'm on Windows 10

* **OpenToonz Version**: 
I'm using the latest OTX version, but have also tried it with the nightly build from 2018-09-12 02:00:12 UTC:
https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_98926de9b60802499ab899617149d6ffe527b3d8

**Comment by artisteacher** [comment]
I'm seeing the same thing in MacOS. Similarly if the vector level has been compressed into a sub-xsheet (the Mac workaround for the wrong mesh shape #406), you can draw on the vector level when the sub-Xsheet is open.

**Comment by beeheemooth** [comment]
@DarrenTAnims You can insert a drawing from the Level Strip into another column, for example.
![ezgif-1-ef45c1e939](https://user-images.githubusercontent.com/25724133/45838215-d9c1f800-bd19-11e8-9f99-adf6a28aaae3.gif)

**Comment by RodneyBaker** [comment]
Another means of accessing drawings quickly if the keyframe/deformation isn't an issue is to drag the frame sequence down 1 frame so that it is not controlled by the plastic mesh then edit the drawing on that 'free' frame.

I haven't used the method often but in some situations it'd work to simple remove the mesh exposure from one row in the xsheet then you'll be able to edit the image after selecting the drawing.  Afterwards just replace the exposure for that frame again.

**Comment by DarrenTAnims** [comment]
Thanks @beeheemooth. That's a really useful tip until this is fixed.

**Comment by artisteacher** [comment]
It is surprising that there are so many ways to add to a plastic-modified drawing! Interestingly, if I draw outside of the mesh area using one of the previously mentioned workarounds, the additions are not visible (in mesh-modified level) - unless the level strip is active or the sub-xsheet is open. So these workarounds are only helpful to make changes inside the existing drawing.

**Comment by DarrenTAnims** [comment]
Correct @artisteacher. The mesh shape and size has already been created, so that can't be changed. But often you find that you want to add more detail or notice a line doesn't look right after animation, so it's handy to be able to edit it. It's just a shame that you can't just draw directly on the drawing on the xsheet.

**Comment by artisteacher** [comment]
It's definitely handy to be able to add or fix details in the drawing. I think that drawing was probably disabled from the Xsheet because new or inexperienced users might expect all additions to the drawing to be visible - even ones outside of the mesh area. Leaving out the level strip could have been a deliberate choice or it might have been overlooked. 

If the Xsheet is changed to behave like the level strip, there should probably be a warning in the "Create Mesh" dialog, that additional drawing to the selected frames will only display in the mesh area.

**Comment by DarrenTAnims** [comment]
Yeah, I think it should be available on the xsheet. I think it's something to learn that once you've created a mesh, if you draw outside of it, of course the smaller mesh won't affect your new drawing. I don't mind there being a warning in the mesh creation dialog if that's thought necessary.
