### ISSUE TITLE
Pli custom styles cause crash on switch to vector tab

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2303]
### Issue Summary

I'm getting a regular crash when switching to the vector tab in the style editor if it is the **first time** switching to the vector tab **and a raster brush** is selected in the level palette. 
### Screenshot or Video Reference

[vector_tab_crash.txt](https://github.com/opentoonz/opentoonz/files/2421187/vector_tab_crash.txt)

### Steps to Reproduce

1. Open OpenToonz and  open a scene with at least one raster or toonz raster level
2. Select a raster (or toonz raster) frame in the Xsheet or Timeline
3. With the brush active, select a raster (mypaint) brush style in the level palette (create one if needed)
4. With a raster brush and raster (or toonz raster level) still active, switch the style editor to the vector tab = crash

### Expected Results

No crash when switching tabs.
### Actual Results

A crash if the vector tab has not been opened already. If a non-mypaint brush is active in the level palette there is no crash. If the vector tab has already been open there is no crash.
### System Information
* **OpenToonz Version**: Nightly build & ongoing for some time
* **Operating System**: MacOS 10.13.5 & 10.14
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
The crash is sometimes harder to trigger with 10.14. It is most consistent if the selected raster style is changed to a different raster brush before switching to the vector tab.

**Comment by artisteacher** [comment]
I’m still trying to narrow this down but think it is likely related to a problem .pli in the custom styles folder - similar to #201.

**Comment by artisteacher** [comment]
If I temporarily remove all of the png files from the custom styles folder, it’s easier to trigger this crash on demand, though it is still not an every time thing. 

Steps to reproduce:
1. Remove png files from custom styles folder 
2. Create a new project & scene (I’m using an alternate project location - Documents)
3. Create a Raster level & set the brush to the charcoal brush on the raster tab
4. Draw with the brush & save scene 
5. Switch to the vector tab
6. If there is no crash, close & reopen OT & the scene
7. Click on the raster style in the level palette & then select the vector tab
8. Repeat steps 6 & 7 as necessary 
In case it makes a difference, I’m using a touchpad, not a mouse.

Sometimes the crash happens without needing to repeat the last steps, sometimes it happens every other time, sometimes it happens several times in a row. At the very best, after 7 times or so, there is always a crash.

Leaving a single pli (ie. clou.pli or curl.pli) in the custom styles directory seems to result in a crash every time (following the above steps 6 & 7). It will take some time to go through and see if there are any pli custom styles that do not cause a crash in this case. @manongjohn, @turtletooth - can either of you reproduce this, or is it just a MacOS problem?

**Comment by manongjohn** [comment]
I cannot duplicate, unfortunately.

Looking in your crash report, it seems to crash in QTGui, if I am reading this right.  I've had issues recently on my Windows machine with it randomly crashing supposedly in QTGui.dll.  Like you, there is no exact path to recreating the crash and it almost seems quite random. Me trying to catch the crash in debug mode hasn't help identify the root cause either.

**Comment by artisteacher** [comment]
@manongjohn  - thanks for checking. This is probably MacOS specific. 

@RodneyBaker - I used to think it was connected to the Mypaint brushes, but I now think there’s an underlying problem with some vector styles or something else that the Mypaint brushes make more obvious. This isn’t a problem anyone is likely to run into regularly if they are using styles properly - I only discovered it because my students at the beginning of the term, like many new users, kept trying to use the wrong combination of style and level types. 

After playing around with the custom styles folder, I can trigger the crash on demand - no matter what level type or style is active, just by going to the vector tab.  Limiting the number of styles in the folder - like leaving the first 15 files but removing the rest, is all it takes. Removing  all of the pli files and adding all of the png files back, allows the vector tab to be accessed without crashing. Typically there are 180 files in the folder, with more png than pli. Perhaps the large number of png act as some kind of buffer that minimize the likelihood of a crash, except in certain circumstances. 

Maybe @shun-iwasawa might have an idea?

**Comment by artisteacher** [comment]
Interestingly if you remove all of the brushes from the custom styles folder, any pli files added in cause a crash when switching to the vector tab. I tried moving a brush from the vector brush folder & that pli caused a crash when changing to the vector tab. Creating a new pli & placing it in the custom style folder also caused a crash when switching to the vector tab. So it doesn’t look like there’s a problem with the pli files themselves, rather how pli’s are accessed as a custom style.

**Comment by yehjaemin** [comment]
I actually replicated this bug for some other conditions too (OSX 10.14.2, local build up to date with current OT repo)
- new toonz vector level -> switch to vector tab -> crash
- new toonz raster level -> switch to vector tab -> crash
- new raster level -> switch to vector tab -> crash
- new scan level -> switch to vector tab -> crash

These conditions all reproduced the crash, and I repeated them to make sure.

I didn't have to add any custom styles either, although it also crashes when I include those. I'm going to look through the files that have to do with the vector tab, since I think that's the main source of the problem (there was no crash when switching to the other tabs).

**Comment by artisteacher** [comment]
Yes, when building yourself there always seems to be a crash switching to the vector tab. Otherwise the crash happens frequently but doesn't necessarily happen every time. I'm assuming it's the same problem...

The vector tab adds access to vector brushes, trail styles (previously called custom styles - still referred to that way in the code) and also generated styles (previously called special styles). Removing all of the custom styles allows me to switch to the vector tab on a local build without crashing, so the problem is likely there. Also, the crash report shows that the crash happens at:

> CustomStyleManager::StyleLoaderTask::run()

So it seems to be some sort of problem with how the custom styles are loaded/accessed.

**Comment by yehjaemin** [comment]
After spending some time trying to debug CustomStyleManager::StyleLoaderTask::run(), I think I may have found the problem.

When you start a new level, the application outputs "Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures." Creating any type of new level actually triggered my C++ exception breakpoints in Qt.

After researching some more, I think that on later versions of OSX, creating new windows outside of the main thread will raise an NSException, which causes the entire application to crash. This is the application output log around the time of switching to the vector tab:
```
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.20.108/AppKit.subproj/NSView.m, line 14143.
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
The program has unexpectedly finished.
```

@artisteacher can you share your crash report? I couldn't get mine to actually say where the crash originated from in terms of files/functions.

**Comment by artisteacher** [comment]
I've definitely seen a lot of crashes with QOffscreenSurface. Here's my crash report. Thanks for looking into this!
[vector_tab_crash.txt](https://github.com/opentoonz/opentoonz/files/2820056/vector_tab_crash.txt)

**Comment by yehjaemin** [comment]
I think that the problem is coming from a multithreading deadlock, where the secondary thread started by creating a new level is stalling the main gui thread. This is mostly guesswork though - I was reading tthread.h and tthread.cpp, which provide abstractions for QThreads, and they seem to implement Workers to deal with the signals/slots to work around the deadlock problems.

However, I can't find any implementations of Worker in stylemanager.cpp. Instead, a custom patternAdded() signal is used in the onFinished process.

I also found that CustomStyleManager::StyleLoaderTask::run() and CustomStyleManager::StyleLoaderTask::onFinished() functions both execute multiple times before the application crashes, and that the code itself isn't producing the bug outright, which makes me pretty sure that the problem has to do with a multithreading error.

I'm still learning the multithreading system used by OpenToonz, Qt, and multithreading in general, so while I do feel like I'm getting closer to a fix, I'd be grateful for any help from someone with more knowledge on this subject.

**Comment by artisteacher** [comment]
What about when a new level isn't created? I always get a crash on any local build when switching to the vector tab - even without creating a new level.

**Comment by yehjaemin** [comment]
@artisteacher Sorry if this sounds silly, is there another way to switch to vectors that I didn't know? Without creating a level, the style manager only displays the tabs "color" and "settings".

**Comment by yehjaemin** [comment]
Update: After commenting out different combinations of code blocks, I got the crash to go away - OT no longer crashes on switching to the vector tab. However, I don't know exactly how much functionality my deletes took out. I did notice that the Trail and Vector Brush presets no longer show up. The Generated presets still showed up and seemed to work when I tested them out.

**Comment by artisteacher** [comment]
@yehjaemin - If you open an existing scene that already has levels, you don't need to create a level for the other tabs in the Style Editor to appear. Just switch which level is selected, then the tabs appear #2385. They really should be visible on open without switching levels if there is already a level created. I also think they should be visible on open anyways if auto creation is enabled or set to use the Sheet as an animation sheet...

What do you mean by the trail/brush presets?

**Comment by yehjaemin** [comment]
I have some screenshots of the crash fix

Here's the vector window - the Trail and Vector Brush toggles, when selected, showed some more presets in OpenToonz 1.2.
<img width="453" alt="screen shot 2019-02-06 at 4 57 23 pm" src="https://user-images.githubusercontent.com/41862298/52384030-9c43da00-2a30-11e9-86e0-9d117a224e32.png">

Here's one of the vector styles being applied
<img width="1440" alt="screen shot 2019-02-06 at 4 58 23 pm" src="https://user-images.githubusercontent.com/41862298/52384032-9e0d9d80-2a30-11e9-8310-6c0f9c96980e.png">

And a couple of the styles make the brush strokes go invisible, which I can't really figure out. I was hoping this bug might be something wrong with the style itself or something wrong with only my settings.
<img width="1440" alt="screen shot 2019-02-06 at 4 59 12 pm" src="https://user-images.githubusercontent.com/41862298/52384036-a06ff780-2a30-11e9-9cae-c62e7f6859ae.png">


I'll submit a PR so that other people can test out the changes.

**Comment by artisteacher** [comment]
So there are actually 2 types of generated styles - those that apply to the stroke/outline and those that apply to filled areas. The fill styles all take up the entire square icon. At some point, I hope more clarity can be added in this area #2200 - it's definitely not an obvious difference.

**Comment by artisteacher** [comment]
Thanks to @manongjohn and #2600, I've been able to run OT in debug mode! 

When switching to the vector tab, this is the error message:

> GL_INVALID_FRAMEBUFFER_OPERATION: framebuffer:36053
create context:0x600000e19548 [thread:0x78eb000]
create context:0x600000dfc5b8 [thread:0x1d435c0]
libpng warning: Application built with libpng-1.4.12 but running with 1.6.37
Assertion failed: (!"unsupported type for custom styles!"), function run, file...stylemanager.cpp, line 135.

The invalid frame buffer is probably from switching to a different room before clicking on the vector tab. The first time a room is open, that error displays.

I'm a little confused - I don't know why Xcode thinks that OT was built with libpng 1.4.12 - I updated libpng to the latest version using homebrew before going through the build process. 1.6.37 is the version I have. A search for 1.4.12 doesn't show any directories. That warning message seems to display a lot - it also displays when an existing scene is opened. It repeats a bunch when switching to the raster tab (where the icons are missing).

**Comment by manongjohn** [comment]
Oddly, i get a different error concerning the switching of the context to a different thread. I'll post it when i can.

**Comment by manongjohn** [comment]
This is what I get for an error:
```
GL_INVALID_FRAMEBUFFER_OPERATION: framebuffer:36053
2019-04-23 01:06:39.206711-0400 OpenToonz[13257:80357] nw_path_close_fd Failed to close guarded necp fd 16 [9: Bad file descriptor]
2019-04-23 01:06:39.621813-0400 OpenToonz[13258:80360] nw_path_close_fd Failed to close guarded necp fd 16 [9: Bad file descriptor]
2019-04-23 01:06:40.139287-0400 OpenToonz[13259:80363] nw_path_close_fd Failed to close guarded necp fd 16 [9: Bad file descriptor]
2019-04-23 01:06:40.455249-0400 OpenToonz[13260:80365] nw_path_close_fd Failed to close guarded necp fd 16 [9: Bad file descriptor]
create context:0x600000f4aa48 [thread:0xf22b000]
create context:0x600000f465c8 [thread:0x1d4b5c0]
create context:0x600000f5d128 [thread:0xf331000]
2019-04-23 01:06:51.106733-0400 OpenToonz[13251:80380] QObject::moveToThread: Current thread (0x600001a3dec0) is not the object's thread (0x6000019fef00).
Cannot move to target thread (0x600001a3dec0)
2019-04-23 01:06:51.106921-0400 OpenToonz[13251:80380] You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
2019-04-23 01:06:51.176223-0400 OpenToonz[13251:80380] Cannot make QOpenGLContext current in a different thread
```

This matches the thread crash from your log in the original post.

I found, for me at least, if it's slow to display the styles on the Vector tab, it doesn't throw this error. If. it's quick, it crashes.  It's like the threads are competing with each other.
