### ISSUE TITLE
Possible ffmpeg issue?

### ISSUE THREAD

**Issue by Orphanlast** [opentoonz/opentoonz#2305]
Okay, so while making my latest video, I ran into something that I found frustrating, but there is an existing work-around, I suppose.

Suppose I need a video reference for 1 second of animation and my scene is set at 24 frames. Now suppose I'm using a smartphone to record the footage. Now... there's not too many options on smart phones, especially when it comes to fps. So you can either record 30 fps or 60 fps.

Now, Opentoonz doesn't interpolate the 30-60 fps down to 24 frames. Regardless of of if you only have one second recorded, it'll dump the whole 30 or 60 frames in. So... you're essentially watching your video reference in slow motion.

I thought that if I did it this way, I could get my timing down really quickly. But... not if the Opentoonz is slightly playing the video reference in slow motion. 

Now, regardless of if Opentoonz was designed to automatically interpolate a 30-60 fps video file down to 14-24 fps, I don't necessarily think I'd be alone in saying that... some end users will assume it does, and might find that their timing is all wrong after long hours of animating. 

I'd more so like to hear your thoughts rather than make a full on feature request.

Like said, there's a work-around. You can plop your video reference into Opentoonz and render to a lower fps and then plop the new lower fps version of your video reference into your desired scene. But that DOES take multiple time consuming steps.

Now, additionally, as a side note, sometimes it can take a little while for a video reference to load up into opentoonz. And if you click on the interface a couple of times, it can actually crash opentoonz entirely. It's like you just opened Opentoonz's rib cage and just clicking on the interface is like slapping its beating heart around. Maybe a loading screen pop up would tell people to hold off for a bit. Because every time I do this, and there's no loading screen pop up, I feel like the video reference should already be on the screen. What's the hold up? Click click click...  shit... the program crashed. Lol.

If you guys would like to see how severe this issue with the recorded fps not interpolating to the scene's fps feed free to watch the first few minutes of my latest video:

https://youtu.be/m8G1_FRZ8k0

**Comment by artisteacher** [comment]
It would definitely be helpful to have more options when importing video. For rotoscoping purposes or animated gifs, it would be helpful to choose to import every nth frame for example.

**Comment by RodneyBaker** [comment]
A related change that might allow for some of those things mentioned here and a whole lot more would be to expose the ffmpeg code so that it can be edited/customized.  This might be a tall order but ffmpeg itself is highly customizable and can do thousands upon thousands of different processes from the command line.  The issue of course is that few OpenToonz users care to work with ffmpeg from the command line.

The most logical places to expose the ffmpeg code would be in Preferences and/or via Farm Room where rendering code can already be seen... just not edited easily.  For those familiar with use of the Farm you should know what I'm referring to where the code used with tcomposer.exe is presented (and able to be copied and placed in a batch file and run outside of OT.

Example:
`tcomposer.exe  "\\Computername\Users\FirstNameLastName\Documents\testtest.tnz" -o "C:\OpenToonz 1.2 stuff\sandbox\outputs\testtest.gif" -range 1 1 -step 1 -shrink 1 -multimedia 0 -nthreads all -maxtilesize none`

At any rate, if ffmpeg code could be customized then users could just query other OT users (or the ffmpeg mailing list) to determine what code is needed to achieve the desired results and enter it into the custom ffmpeg field.

Disclaimer:  I do realize that because OpenToonz and FFMPEG are not integrated at a high level this might not currently be a reasonable suggestion.  It does seem to me that championing use of ffmpeg to achieve these various 'features' is ideal.  Short of using one of the various GUIs that work with ffmpeg I'm not sure what to suggest.  Learning the ins and outs of the ffmpeg command line would resolve much of desires of users with multitudinous needs.

Development-wise what we need is someone that knows ffmpeg really well and can chart a course toward enhanced integration even if only via external ffmpeg interfaces that can be made to integrate more fully with OpenToonz.

I've been a subscriber to the ffmpeg mailing list pretty much ever since I discovered it and it's pretty impressive what can be done via ffmpeg and the command line (and via GUIs designed for use with ffmpeg).  It is readily apparent that the OpenToonz development team cannot compete with ffmpeg development nor should it endeavor to do that because that'd be like trying to reinvent the wheel.  Development of OpenToonz needs to take into account the development of other complimentary systems.

**Comment by RodneyBaker** [comment]
Another thought relating to this is how we very likely need to chart out (at a minimum) what processes fall within the realms of ingest, output and internal processing in OpenToonz.  This to make it easier to drill into specific areas of interest and adjust them to maximize user customization and productivity.

Users will never be satisfied with what is present in the program.. that's the nature of the beast.... so how to best allow changes to be made at the user level without resorting to changes to core code structure and systems?  

Regarding the topic at hand.. there is much OpenToonz can do regarding FPS so I'll try to dig more deeply into that.  Some of this relates to education more than it does to specific features in OpenToonz itself.  One thing to keep in mind is that OpenToonz is fairly FPS agnostic... it doesn't particularly care what the FPS is... it just needs the user to pick set one.  The issue then relates more to adjusting media with different numbers of frames to the desired FPS while considering what will be done in order to get the difference FPS to match.  The key in my estimation is to always remember that one second is one second no matter what the FPS is.   Then you just have to decide how many frames to expose in that second.  If we have 60 frames that was presented in one second but now we want to only present 24 frames... we are going to have to do something with those other 36 frames.  Automated methods often don't take into account the best frames... only humans can effectively do that as of this date... but... we could begin by considering duplicate frames as they are often good candidates for dropping.    

This issue of frame rate change has been around for a long time.  For a little background on a method used to convert from film rate (24FPS) to video rate (30FPS) you might read up on 3:2 pull down:

https://en.wikipedia.org/wiki/Three-two_pull_down

In the end, remember that regardless of framerate the number of frames per second must all add up to 1... as in 1 whole second.  When we set the FPS we are simply dividing that 1 into segments much like we do with animation itself where we start with one sequence and break it down into useful components that convey what is happening on the screen.  We want to set our key frames so that all action flows through them and we want to make sure we don't accidentally drop those specific frames if we adjust the timing of our sequence because those are the storytelling images of our scene and something critical will likely be lost without those frames.  What is inbetween however can be removed based on available space and desired speed/timing.

I have doubts that most automated conversions of FPS can effectively leave critical frames alone and only remove frames that are unnecessary.   Rendering can be a little different in that interpolations between movement of shapes can kick in and create additional imagery that previously wasn't there.  This is why it is often ideal to do as much as possible either in the same program for as much as possible or at least at the same target frame rate.

**Comment by Orphanlast** [comment]
Oops accidentally closed then opened the issue...

Okay, so here's my thoughts. Picture this -- you drag and drop your video reference into the program. A dialogue box pops up. It states the scenes fps vs the fps of the video reference. And it asks what fps woul. You want this video file to show up as on the xsheet/timeline. You type that in. And press ok.

Then another dialogue box appears. It asks what are your keyframes? And you're able to scrub through your animation (just like with the viewer or a quick render) and you're able to select which frames in your video reference is your keyframes.

So now opentoonz knows not to delete those frames.

At this point you press "ok"

Then it asks if you want to ease in or out inbetween each keyframe. And you're able to play the video in order to see how the video will look with your selected easing. 

Maybe this is asking a lot. But there DOES seem to be the question of what Opentoonz will do with the excess frames. Ultimately, I think it'll just copy the video file, put it in the browser and subtract and delete frames. 

 I suppose the end user could skip that part of the dialogue box and let Opentoonz do an auto interpolation (keeping the keyframes you selected).

Some of these ideas, I understand, may just be pie in the sky. But they're ideas.

Then the loading popup would appear.

**Comment by RodneyBaker** [comment]
As this doesn't relate to a bug you'll likely want to close this and open a topic in the OpenToonz forum tagged with the Feature Request category.

**Comment by Orphanlast** [comment]
The only tags are code, issues, pull requests, projects, wiki, and pulse. I'm not seeing a forum. 

So, I'm confused.

**Comment by RodneyBaker** [comment]
The OpenToonz forum is the Google Group designated for feature requests... and is the official forum for all things OpenToonz.  

https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
@artisteacher  OpenToonz does have the ability to ingest sequences based on a step and increment value.  So your example of importing every 9th frame of a sequence can be accomplished in that way.

How you do that... (one way):

- Right click on a cell in the xsheet and select Load Level.
- At the bottom right note the Arrangement in Xsheet option
- Change the Inc (Increment) option to 8 to get every 9th frame (OT's frame index starts with zero so I assume that's why the number is one off here)
- Make sure the Step option is set to 1.  If left on Auto OpenToonz will pad the sequence in order to maintain the original length of the sequence... duplicating each imported frame the required number to achieve that.

Experiment with the various settings there to get different results.

![arrangemet in xsheet](https://user-images.githubusercontent.com/2576432/46255438-90348400-c462-11e8-8c38-d8f9922796a1.png)

**Comment by artisteacher** [comment]
@RodneyBaker, I’ve never noticed the arrangement options before. Thanks!

**Comment by DarrenTAnims** [comment]
That's a great tip. I'd never noticed those options either.

**Comment by Orphanlast** [comment]
Well, it was suggested that I post this topic on Github. And I've done that. Now I guess if someone wants to post on google plus about this, then I guess that's cool.

But I guess I'm supposed to close this issue. I've just been coving this topic for a while now, and I think the majority of people that should know about it do know about it.

**Comment by DarrenTAnims** [comment]
Why would someone post on Google Plus? Is there a secret OpenToonz group there I've not heard about?
