### ISSUE TITLE
Suggested change to Timeline room

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#2339]
@manongjohn What would be your thought about moving the toolbar in the timeline room to the far left so more tools are visible?  With it in the middle, it is hard to get to all the tools because half the toolbar is cut off.

**Comment by DarrenTAnims** [comment]
I don't use any of the default rooms (apart from the farm). I've adjusted all of them to have just the controls I need in them.

**Comment by manongjohn** [comment]
@turtletooth I don't have any particular issue with it being moved to the edge. I placed it there only because it was quicker for me to get to it without having to move my hand past the style editor whenever switching tools. 

It's not too difficult to move it ourselves, but if it makes better sense to have it start on the edge for new users, then I'm good with the idea.

**Comment by gab3d** [comment]
I agree with @turtletooth about this one.
I also see what led @manongjohn to put the toolbar there though... 
To me the real problem is that the palette and style editor panes should be to the right of the viewer, but I also understand why at first "it looks better" to have the viewer at the center of the screen.
So, this is a tough decission, either route we choose.

**Comment by artisteacher** [comment]
On a related note, I think that we could really use some adjustment to the current room set - or an additional set of simplified rooms to include in OT. People can always customize their own, but if they end up too overwhelmed before they learn that skill, they may just choose to move on to other software.  9 rooms is a lot and there is plenty of overlap between them.

**Comment by RodneyBaker** [comment]
Closing as a feature request still under consideration.
@turtletooth @manongjohn   Reopen as you see fit!
