### ISSUE TITLE
Bug to painting freehand layer vector

### ISSUE THREAD

**Issue by zarco1794** [opentoonz/opentoonz#2357]
### Issue Summary
bug to try paintig  freehand option in vector layer
### Screenshot or Video Reference
https://media.giphy.com/media/8cda3sqWXNG8dCrcEp/giphy.gif

### Steps to Reproduce
you have painted section external and section internal, the section middle no cant paint to freehand

### Expected Results
painting to normal option work well, but it would be good if the freehand option will work this situation

### System Information
1.2.1 built oct 29 2018 10:18:31
windows 7 64bits
intel g2030
8 ram
amd rodeon r7 200
genius i405x

**Comment by artisteacher** [comment]
I’m experiencing this on MacOS as well. Polyline fill has the same problem. It looks like both fill modes are incapable of filling an interior region on a vector level. Normal & rectangular modes both work without issue.

**Comment by RodneyBaker** [comment]
If this is with vector levels, which it appears to be, does grouping the shape.. .or collection of shapes... help with more accurate filling?

**Comment by RodneyBaker** [comment]
According to Opentoonz documentation Fill will only be applied to objects within the same Group.
Check to see if any troublesome shapes are assigned to the same Group.

**Comment by RodneyBaker** [comment]
Closing this as more of a troubleshooting/workflow issue and a troubleshooting issue not active since 2018.  Please feel free to continue the discussion here or in the Opentoonz Troubleshooting forum. LINK:  https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting

One thing that can help in resolving some group/fill related issues is to use 'Simply Vectors'... if that is an option... as that tends to resolve conflicts where Opentoonz doesn't know inside from outside of a shape or groups of shapes.

Note:  There are known issues with vector fills that need to be addressed.  Please don't hesitate to post information, project files and additional feedback on workflow to help in resolving fill related issues.
