### ISSUE TITLE
Onion skin:  Targeting area too small

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#2371]
On trying to turn on or off a 'relative' onion skin, it's easy to click to the right of it, which changes the current frame. The click area to turn on/off the onion skin should go to the edge of the grey area that butts up to the frame number area.

### Screenshot or Video Reference
![screencapture](https://user-images.githubusercontent.com/28575907/48208940-de934780-e36b-11e8-845b-418f68b2b2d6.gif)

I've drawn a red box over where I think the hit area should be. Although I noticed when I zoomed in that the blue and green onion skin circles overlap slightly
![hit area](https://user-images.githubusercontent.com/28575907/48209471-2f577000-e36d-11e8-9a76-aa7154b1fa7d.png)

**Comment by artisteacher** [comment]
I’ve definitely run into that myself. I think that since the absolute onionskin markers have a boundary as a guide, they are a lot easier to hit readily. The relative marker on the other hand, could definitely benefit from a larger hit area.

 On a similar note, I’d love to see a “clear onionskin” or “reset onionskin” command added to the onionskin context menu. I know you can click & drag to quickly remove onionskin markers, but that is sometimes difficult to target and may require dragging through huge numbers of frames. A quick reset would be fantastic.

**Comment by DarrenTAnims** [comment]
Good suggestion @artisteacher. A context menu item (next to the Deactivate Onion Skin option) to "Turn off all selected onion skins" when you have some selected would be really handy.
