### ISSUE TITLE
Crash when trying to load a scene contianing a plastic mesh as a sub XSheet

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#238]
When I try to Bring a scene containing a plastic mesh into another scene as a Sub-Xsheet Opentoonz crashes.

**Comment by Rayek** [comment]
Yes, confirmed. This worked in one of the previous builds for me. It no longer does. It just crashes without any warning.

Win7 64bit 48gb, Nvidia 590GTX

**Comment by Rayek** [comment]
Still not resolved in the latest build. Instant crash!

**Comment by BrundleThwaite** [comment]
To be fair, At the time i posted it most people in Japan would have been asleep and it will probably take a day or two to fix.

But it is a little frustrating I chose not to do any tutorials on plastic because of the issues is had and as soon as they were fixed I find other even more serious problems.

**Comment by blurymind** [comment]
I myself feel that the plastic tool needs a little bit more work in order to be usable on a complete rig.
So far I just play with OT to see if I can trigger a bug to report. I havent used it to actually draw, just learn it. Drawing in it is highly risky, as until recently it couldn't even save my progress properly.

**Comment by blurymind** [comment]
@BrundleThwaite has this bug been fixed in 1.0.2 ?

**Comment by BrundleThwaite** [comment]
I am closing this issue as it is fixed now.

**Comment by blurymind** [comment]
Thank you
