### ISSUE TITLE
Project breaks if parentfolder (project root folder) renamed

### ISSUE THREAD

**Issue by Ayyyg** [opentoonz/opentoonz#2384]
We have animation class and my teacher is really frustrated that many projects sent by student is broken, It will show "not possible to load scene because it does not belong to any project." error message when trying to load it

after I mess around a while I found that if your folder name is not same as _otprj.xml prefix, the project will be broken and you can't open any scene in this project

so the issue is if a user renamed the project folder after he created project, the scenes can't be load and will show "not possible to load scene because it does not belong to any project."

I think this is really a bad design because no one will expect project can be broken when you renamed project folder name, we have some many student don't realize this and this made my teacher considering to switch software

**Comment by artisteacher** [comment]
I’ve run into this too. I avoid renaming in general- whether it is a level or project since it always causes path issues. 

OpenToonz should recognize when you try to load a project where the project name doesn’t match the directory name. This should prompt a warning dialog “project name does not match the project directory - do you want to replace the project name with the current directory name?” 

On a somewhat related note about renaming levels, when renaming in the Browser, it would be really helpful to have the option to update the level’s path/name in the active scene so that they use the new name.

**Comment by DarrenTAnims** [comment]
I was hit by this originally, until I realised that you just need to rename the project's xml file. Now it's not a big deal to me. I rename projects all the time. It's just a shame that these need to be in sync and I can't (from an external point of view) see why they need to be named the same.
