### ISSUE TITLE
Corrupted Files after Crash

### ISSUE THREAD

**Issue by Horificius** [opentoonz/opentoonz#2387]
### Issue Summary

See title
### Screenshot or Video Reference

https://www.youtube.com/watch?v=mjQr19Usys8&feature=youtu.be
### Steps to Reproduce

loading or saving anything
### Expected Results

load and save things
### Actual Results

crash (white screen/ not responding)
### System Information
* **OpenToonz Version**: 1.2
* **Operating System**: Windows 10
* **CPU**: Intel Core i5-8300H
* **Memory**: 8192 MB of RAM
* **Graphics Card**: Intel Core UHD Graphics 630 
* **Graphics Tablet**:

**Comment by Horificius** [comment]
> @Horificius, information about your system would definitely be helpful. I’m wondering if there’s an issue with a corrupt/unreadable file where you are saving to/loading from.
> 
> If you make a rename the stuff folder, and reinstall the latest nightly release, and use a new project, do you still have an issue? If everything works as expected, you can go through your original project folder & use a process of elimination to find the problem file.

I'm not sure what you mean by this.

**Comment by Horificius** [comment]
its not discriminating against which file that i upload. but literally yesterday it was working perfectly fine.

**Comment by Horificius** [comment]
https://www.youtube.com/watch?v=mjQr19Usys8&feature=youtu.be

**Comment by Horificius** [comment]
i cant load anything in the latest nightly release.

**Comment by Horificius** [comment]
or save anything

**Comment by RodneyBaker** [comment]
If it was working yesterday you make me wonder what you changed in your operating system since yesterday.  Or if you installed/reinstalled OpenToonz which release you installed.

**Comment by RodneyBaker** [comment]
The error shown initially that states your Project is missing files is something I would focus on.

Can you create a New empty scene and work in that without any problems?

**Comment by Horificius** [comment]
I can work in it, but i cannot save it without a crash

**Comment by Horificius** [comment]
I've updated my first comment with the computer specs

**Comment by RodneyBaker** [comment]
Thanks for posting your specs.

Please install the latest nightly release to determine if that will resolve the problem:
Here's a direct link to the latest nightly release:

https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_7846407b395ce47efa18c0094b448216d93868e1/OpenToonzSetup.exe

**Comment by Horificius** [comment]
i did install that. I said that

**Comment by Horificius** [comment]
no change

**Comment by RodneyBaker** [comment]
Check your antivirus software settings and permissions if using external drive.
Something is preventing you from saving to harddrive etc.
As it's not an issue with OpenToonz it has to be local.

**Comment by RodneyBaker** [comment]
You may want to visit one of the OpenToonz discord chats where others can assist you.
Github reports aren't the best place for this form of troubleshooting:

Link:  https://discord.gg/XtqTS5A

**Comment by Horificius** [comment]
These files have been corrupted...can somebody please look into them? 
[charactesr_gg_mattscream.zip](https://github.com/opentoonz/opentoonz/files/2609756/charactesr_gg_mattscream.zip)
[Mattscreams.zip](https://github.com/opentoonz/opentoonz/files/2609759/Mattscreams.zip)

**Comment by RodneyBaker** [comment]
The files @Horificius has posted above are an example of what was wrong with his local files.
He's back to working again with OpenToonz but lost those files and (as I recall) approx 5 files in total.

He did specifically state it but he was/is hoping perhaps some data from the files could be recovered.

**Comment by RodneyBaker** [comment]
Closing with recommendation to explore recovery of the files as others are able to assist.
The root issue appears to be with instability with standard raster files and much of that instability can be resolved by using current nightly releases.  

When doing so consider replacing the default stuff directory in the process.  For instance, users might rename the stuff directory "Opentoonz stuff (Holding)" and then they can still access older projects.  Later if the need to create a new/fresh copy of the stuff directory arrives the directory can be renamed "Opentoonz stuff (20181210)" and drag/dropped into the holding file.  Then a new stuff directory will be created upon installation of OpenToonz.  Other methods work well also.  The point being that every so often it's good to clean up and reorganize.

During installation it is also possible to name the stuff directory so that we know when we created it.  So with each installation we can remind ourselves of when we started a new production.  Then later when we look at our root directory we might folders like:

Opentoonz stuff 20181001
OpenToonz stuff 20181108
OpenToonz stuff Experimental (Do not use in production)
portablestuff

Note that that last one is useful in making any Opentoonz installation on windows a portable version so that Opentoonz can easily be transferred to another computer.... and even ran from a USB stick.
