### ISSUE TITLE
I want to make a new Theme "Harlequin" in OpenToonz. 

### ISSUE THREAD

**Issue by 711GM** [opentoonz/opentoonz#2404]
I want to remake the interface as in Harlequin. Tell me how to do this? 
![image](https://user-images.githubusercontent.com/40460266/49576342-facbd980-f955-11e8-81ce-3f4b44e25906.png) 
![image](https://user-images.githubusercontent.com/40460266/49576350-04554180-f956-11e8-9075-1df835e03f56.png)

**Comment by artisteacher** [comment]
If you mean that you want to make a theme, the directions are [here](
https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_stylesheet.md).

**Comment by 711GM** [comment]
And no video instructions? I'm afraid to mess up something. For example, how to round off?

**Comment by artisteacher** [comment]
This is really the domain of @konero - I haven't used LESS before. I believe the output is QSS which is very similar to CSS. In CSS you get rounded corners using the property border-radius. There are definitely videos and other tutorials out there if you google that explain how to use LESS in general.

**Comment by 711GM** [comment]
I am not a programmer, I would like to understand what possibilities this approach has? What can be changed in this way and what cannot? Interface size can be fixed? Can I change the icons? And instead of ticks or pictures you can use the Gif format? https://www.youtube.com/watch?v=_YUDOshaFUM  Here are beautifully used animated elements. 
![image](https://user-images.githubusercontent.com/40460266/49590431-f4048d00-f97c-11e8-8da6-150770a1fc8f.png) 
![image](https://user-images.githubusercontent.com/40460266/49590462-05e63000-f97d-11e8-81a6-b0e5abdcf05a.png) 
![image](https://user-images.githubusercontent.com/40460266/49590511-20b8a480-f97d-11e8-9f22-00c7ffd08415.png)

**Comment by RodneyBaker** [comment]
Step 1:  Download Harlequin trial
Step 2:  Copy theme from Harlequin stuff directory to OpenToonz stuff directory.
If you wish to have the menus in Japanese that option is in Preferences.

Done.  :)

Closing as this is more of a discussion for the OpenToonz forum or discord chats.

**Comment by 711GM** [comment]
I did this first thing and it does not work. Because it does not work, I write here.

**Comment by RodneyBaker** [comment]
Let me see if I can upload a copy of the theme for you.

**Comment by 711GM** [comment]
If you can run this theme on OpenToonz then let me know. I would also like to understand whether it is possible to add animated parts to the interface.

**Comment by RodneyBaker** [comment]
> I would also like to understand whether it is possible to add animated parts to the interface.

Sure it's possible.  Not sure exactly how though.
That's a good area for research and development.

**Comment by 711GM** [comment]
I would be glad if they help me with this. So far my experiments have failed. I do not understand how to add animation. Gif does not work, but prsoto stands as a picture. May need a different format? Like Json?

**Comment by RodneyBaker** [comment]
Investigate Qt coding... and LESS and QSS...
If it can be done with that... it can be added to OpenToonz.

**Comment by RodneyBaker** [comment]
You should join one of the OpenToonz discords where you can test out your ideas, explore resources and... have fun.  There might even be the occasional good advice. :)

**Comment by RodneyBaker** [comment]
I would encourage you to share in your exploration.  Two minds are better than one.  Hundreds are useful also.  It can help to pick a specific thing you wish to implement... refine and simplify it to the best of your ability... and then drive forward to achieve that goal... taking note of what is learned along the way.  Documenting the journey is one of the best ways to learn as when we look back we can actually see what we have learned.

**Comment by artisteacher** [comment]
@RodneyBaker has some great advice! 

I do want to mention that there have been several changes to the themes for OT since the original release that will likely cause display issues with the actual Harlequin theme. Many of the images were moved to the style sheet and some colors were moved to the style sheet too.

**Comment by RodneyBaker** [comment]
@artisteacher is right about incompatibilities.
I think it was the 'Production' theme from Toonz Premium that I tested.
I'll add it here although I haven't tested it recently.

The main reason I wouldn't use it is because it is entirely too bright.
Kind of tough on the eyes.  But... for those that want such...

[production.zip](https://github.com/opentoonz/opentoonz/files/2654407/production.zip)

**Comment by RodneyBaker** [comment]
![brightproduction](https://user-images.githubusercontent.com/2576432/49609114-353a7400-f960-11e8-87f9-cbf57a6025a3.png)

**Comment by 711GM** [comment]
I do not know how to comment on this correctly. As I said, this topic does not work here, if you take a closer look, you will see that you have downloaded a downed topic. Here all colors are wrong and so on. It looks like any broken topic. If you do not believe me then try to edit this topic, it does not change.

**Comment by 711GM** [comment]
A better demonstration is to try to customize this theme and try changing colors. Then it will be immediately clear to you that it does not work, and the fact that this standard method of the program was loaded did not give an error.

**Comment by 711GM** [comment]
Better to open the discussion thread again. Let at least a week people also think about how this can be done.

**Comment by RodneyBaker** [comment]
The developers opted to refer feature requests to the OpenToonz forum and reserve this github for bug reports and actively developed projects.

Please open a discussion in the OpenToonz forum and you can explore your thoughts on updating themes.  You may even find a few champions that will assist in the effort:

https://groups.google.com/forum/#!categories/opentoonz_en/general-discussion

**Comment by artisteacher** [comment]
> A better demonstration is to try to customize this theme and try changing colors. Then it will be immediately clear to you that it does not work, and the fact that this standard method of the program was loaded did not give an error.

That is expected in old versions of the themes. Again, there are several areas where things that were hardcoded have been moved to the stylesheet.  Since they are not expected to update or display properly, they are no longer included and are no longer supported. Since users can create/modify themes and add them directly to the theme folder to make them available, I don't know how helpful/possible a warning will be. I believe the release notes do warn users about theme changes that make old themes incompatible.

Honestly, everything that was moved to the stylesheet should have really been there from the beginning. You could go through the old PR's and see what was moved and adjust the Harlequin theme but that would be really time consuming. 

Personally, I think you might be better off making a new theme based on the existing light theme - adjusting the colors to be even lighter would be fairly easy but would take a little time. You'd still have to figure out the rounded corners - if it's not something that's hardcoded, I do think the property might be border-radius. The tricky thing will be finding the correct selector.

**Comment by 711GM** [comment]
I try to edit. If you change the "Less" files then there is nothing that does not change. Changes if you edit only "QSS".

**Comment by artisteacher** [comment]
I believe that Less outputs the QSS but I don't really know anything about the process.

**Comment by RodneyBaker** [comment]
Here's a very old topic in the Opentoonz forum where someone posts their experience creating their own theme (and why they suggest not doing it... i.e. hints at some of the obstacles):

https://groups.google.com/forum/#!topic/opentoonz_en/ixCJgbvXeqc

**Comment by konero** [comment]
@711GM Like @artisteacher explains LESS is a preprocessor language that outputs to QSS. Study what is outlined [here](https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_stylesheet.md#recommended-setup) and follow the three steps under recommended setup. It's very easy to do, takes a minute or two and can be done on any platform.
