### ISSUE TITLE
Crash with Remove Vector Overflow (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2526]
### Screenshot or Video Reference

![ezgif-1-d528686fa912](https://user-images.githubusercontent.com/25724133/52955226-d009f280-3394-11e9-8098-dc7b580dbd5f.gif)

### Steps to Reproduce

"Do it like Simon says..."

1. Create new Vector level.
2. Make sure the Brush Smooth option is similar to mine (it seems that it plays some role in reproducing crash, I think).
3. Draw letter "H" in order like i do.
4. Use Eraser Tool Type: Normal to erase the middle parts. (Turn on Fill Check and Gap Check)
5. Select all lines and choose Ramove Vector Overflow
6. Undo this (think: "damn, I forgot to erase the top and bottom!")
7. Redo this (think: "nevermind.. I'll erase it manually")
8. Try to erase or edit with Control Point Editor.
9. Crash.

### System Information
* **OpenToonz Version**:  v1.3
* **Operating System**:  Windows 8.1

**Comment by beeheemooth** [comment]
It is possible that one of the reasons for the crash could be this:
![ezgif-1-c9a784fb4a6e](https://user-images.githubusercontent.com/25724133/52965614-e8d2d200-33ad-11e9-97aa-783596dec557.gif)

**Comment by manongjohn** [comment]
Following your exact steps from the description and even the video, I am unable to reproduce this crash or that strange extra loop when drawing.

**Comment by manongjohn** [comment]
After raising smooth to over 30 (I used 45+) at @beeheemooth 's suggestion and drawing lines quickly, I was able to reproduce the extra loop as well as the crash.

Seems related to bad intersection data.  Looking further into it.

**Comment by RodneyBaker** [comment]
Somewhat related:
I note that the extra control points (extra loop on the end of a spline/path) tends to get created when using the Magnet Tool in some situations.  Perhaps some form of 'IsFlat' query can be used to reduce the number of control points for lines that approach being less than a specific increase.  For instance, a straight line should only require two control points because a recursive 'IsFlat' query would result in 'true' for all segments, thereby iterating through a process of control point reduction until arriving at two control points (for the straight line case).

**Comment by RodneyBaker** [comment]
This should hopefully be resolved.
@beeheemooth can you confirm?
Thanks

**Comment by beeheemooth** [comment]
Confirmed.
