### ISSUE TITLE
Finger Tool: Is it Broken?

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#2539]
### Issue Summary
In PaintMan one of the best tools is the Finger (Extender) Tool. How it works is if there are small unfilled areas the Finger Tool allows you to automatically select the style color to be filled by clicking and dragging the color into the unfilled region and it will only fill to a specified size.

However OpenToonz, although it will let me drag a color just as I described, it will only automatically select a style color if it's a **line style**, not an **_area style_**. It works with area styles, but they need to be selected manually which is a pain.

Was this always the intended function of the Finger Tool in Toonz?

### Screenshot or Video Reference
![optnz_finger](https://user-images.githubusercontent.com/19820721/53653142-7fbb4c00-3c42-11e9-86b6-2a1401ac858a.gif)

### Expected Results
Automatically select **_area styles_** by clicking and dragging using the **Finger Tool**.

**Comment by beeheemooth** [comment]
The pixels that the Finger Tool covers are becoming part of the line, but not the area.

**Comment by gab3d** [comment]
@beeheemooth 
That seems to be the case, it also doesn't make any use of antialiasing. 

Also, as that feature was not present in Toonz 7.1 there is no documentation about it either.
Perhaps @shun-iwasawa could shed some light of its intended use and inner workings?

**Comment by gab3d** [comment]
...BTW 
I went though some confusion back when I was learning OT about the terms **Ink** and **Paint**, I mean, the concept was always easily understandable, but the fact that throughout the rest of the program the terms always used to refer to the same concepts are **Lines** and **Areas**, never helped me at that point in time. 
I was always wondering myself if they were exactly the same, or similar but different concepts...

I'd like to know what others think about unifying the use of this terms in either way... 🤔

**Comment by konero** [comment]
Oh I see, thanks for the info, I did check my old Harlequin manuals for 6 and 7 but I couldn't find it there, just assumed it was copying what PaintMan does since they look identical.

If I were to guess, then this Finger Tool is meant to close the gaps between line breaks?

**Comment by shun-iwasawa** [comment]
@konero
I originally developed Finger Tool in response to requests from Ghibli staffs.

Since they draw animation on papers and scan them with high dpi (400dpi), it is often that the lines have holes and spiny artifacts in faint parts.

![image](https://user-images.githubusercontent.com/17974955/53683420-f3914d80-3d43-11e9-9637-52d9dfcec373.png)

Finger Tool is for mending such holes and artifacts in order to make cleaner lines which are suitable for filling.

So yes, your guess is almost right, except that they work on anti-aliased lines, not binarized ones.

They usually use the rectangular option of Fill Tool for small unfilled areas.
I agree that the Finger Tool having "Areas" mode would be useful as an alternative way with no need to switch styles.

**Comment by gab3d** [comment]
@shun-iwasawa 
great to know, thanks!
and what does the Invert mode does?
I've tried to figure it out to no avail.
