### ISSUE TITLE
Every frame freezes on gif export [gif]

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#2560]
![untitled7](https://user-images.githubusercontent.com/30438394/54229371-2c37e080-4515-11e9-8d5f-09541c970ec8.gif)

All other export settings working fine.

### System Information
* **OpenToonz Version**: Latest Nightly
* **Operating System**: MacOsx Sierra
* **CPU**: i3
* **Memory**: 8gb
* **Graphics Card**: Ati Radeon
* **Graphics Tablet**: Wacom Intuos

**Comment by artisteacher** [comment]
@norrinra - do you know when this started happening? It looks like a redraw issue, but I'm not having that problem in Mojave. I'll check at school and see if this occurs with High Sierra. This used to happen with the plastic tool and certain graphics cards.

**Comment by RodneyBaker** [comment]
This is the old way gif animation use to render with transparency prior to v1.3.
It might be that the fix/feature that resolved that issue (for Windows) didn't get fully ported for Mac.
This also may relate to why MOV format isn't currently rendering with transparency which has a fix pending in #2544

**Comment by artisteacher** [comment]
@norrinra have you changed any other output settings? If so, could you share a screenshot of what they look like? I’m not getting the same results, but there do seem to be issues with some of the settings.

**Comment by artisteacher** [comment]
Update: I am getting different results which each Mac I try and they all have different graphics cards. That makes me think currently there might be a compatibility issue specifically with older graphics cards. The first troubleshooting step with that would be to update the drivers. That's not possible in this case since driver updates are part of the OS updates. These computers are too old to update to Mojave.

- 2011 MacBook Pro - ghosting
Intel HD Graphics 3000
High Sierra 
 
- 2011 iMac - black background
AMD Radeon HD 6750M
High Sierra

- 2017 MacBook Pro - no issues
Intel HD Graphics 530 and Radeon Pro 460
Mojave

**Comment by norrinra** [comment]
My output settings. 

![Screen Shot 2019-03-13 at 7 34 16 PM](https://user-images.githubusercontent.com/30438394/54297088-2a2e5a00-45c7-11e9-962b-d75c0b21fff4.jpg)

**Comment by norrinra** [comment]
Can ffmpeg might be the reason ?  Because I feel like it started doing this after I update ffmpeg. I m not sure though. I will try to install previous ffmpeg.

**Comment by artisteacher** [comment]
It never hurts to try, but I doubt that is the problem since I haven't updated recently.

**Comment by RodneyBaker** [comment]
Just to check/validate...

Adjust your Alpha channel setting to make the background of the scene completely opaque.
That is done via menu at Xsheet > Scene Settings (See attached image):

![Alpha Channel set to 255 Fully opaque](https://user-images.githubusercontent.com/2576432/54311810-99d62200-4592-11e9-9573-837b3c8adb0b.jpg)

**Comment by artisteacher** [comment]
That should definitely work, assuming you don’t need a transparent gif.

**Comment by norrinra** [comment]
@RodneyBaker @artisteacher  Yes, it totally fixed the problem. Thanks a lot !
Should I close the issue ?

**Comment by artisteacher** [comment]
I think it should stay open, since transparent gifs should work and sometimes do.

**Comment by RodneyBaker** [comment]
I agree that it should remain open as this issue suggests Mac (and Linux?) doesn't have the full fix.

Aside:  Transparency working with gif on Windows was a surprise to me when #2418 was introduced.  Back then the best I could get on Windows was what you are experiencing now... because fully animated gif transparency wasn't possible yet.  My concern was that we might lose the basic capability that existed via a workaround but then the introduction of #2418 allowed for full transparency almost as if by accident.

**Comment by RodneyBaker** [comment]
Can anyone record their session on a Mac so we can narrow down the scope of this one?

**Comment by artisteacher** [comment]
Do you mean a screencapture video?

**Comment by RodneyBaker** [comment]
> screencapture video?
Yes, anything that captures the process being used with as much pertinent detail as possible.

I'll close this issue pending the start up of a new one relating the issue you outline.
