### ISSUE TITLE
Broken slider behavior

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2570]
Repro Steps:
1. Create a new FourPoints, RadialGradient, Checkerboard, Particles (Color tab) or other node with multiple separate Colors.
2. Click on Color 1's square.
3. Click on Color 2's square.
4. Try to adjust any of Color 1's values.

What happens:
Color 1's values will be copied into Color 2.
Color 1's sliders will adjust Color 2 or will not do anything at all.

Clicking on additional squares will put them into the broken state too.

It seems that only the currently selected color can be adjusted and will copy the values of any other color that is being tweaked.

![Four Points issue](https://user-images.githubusercontent.com/42905003/54729282-9df9d500-4b7a-11e9-903b-3cdf1a94811c.gif)

Closing and reopening the FX Settings will stop the described issue until one of the color squares are clicked again.

**Comment by artisteacher** [comment]
I can reproduce on macOS.

**Comment by martinvanzijl** [comment]
I started trying to fix this. I got it working most of the time - but the bug still happens about 1 in 20 times when you move the slider.

Here is a video demo (zipped):
[slider-fix-wip-demo.zip](https://github.com/opentoonz/opentoonz/files/3474337/slider-fix-wip-demo.zip)

The bug happens near the end of the video. You can corrected this with "Undo", but it is still a pain.

Here is my branch:
https://github.com/martinvanzijl/opentoonz/tree/issue-2570-fix-broken-slider-behaviour

I would like to get it working 100% before making a Pull Request.

Note for developers: The problem seems to happen when you change the slider for one color, but "sliderReleased()" is not called, then you change the slider for another color. I guess "sliderReleased()" has to be called to finish the editing for the first color.

**Comment by martinvanzijl** [comment]
Actually, it looks like this is working 100% in the latest version, so I will close my branch.

**Comment by WolfInABowl** [comment]
Have there been any updates in regards to this? It is still reproducible in the latest nightly.

**Comment by RodneyBaker** [comment]
Anyone reading this report might have gotten the impression it was fixed.
Thanks for letting us know that isn't the case @WolfInABowl

**Comment by shun-iwasawa** [comment]
I could reproduce the problem. I'll take a look.
