### ISSUE TITLE
Opentoonz won't play in animate room

### ISSUE THREAD

**Issue by qwert234** [opentoonz/opentoonz#2573]
I have created an opentoonz animation and am hitting the "P" button to play it but the playback isn't working. I have sound and two levels in my animation both with multiple layers.
Nothing happens when I click the p button

this is the newest version of opentoonz on mac

**Comment by artisteacher** [comment]
I'm not having trouble triggering playback in the Animate room with macOS. Both the play button
and the shortcut "P" are working on macOS as far as I can tell. 

@qwert234 - do you have preview turned on? Sometimes it can be a really, really long wait for the preview to finish calculating and start playing. I've been running into that recently with particles.

Since you have levels with multiple layers, I assume you are working with vector levels. I'm not sure how complex your drawings are, but something to be aware of is that vector levels keep track of a high number of control points which can slow things down if there is too much data to keep track of. For that reason, sketchy styles and painting in fills with the brush are really not techniques that are compatible with the vector levels. If you prefer a sketchy style or to use the brush for your fill areas, you'd be better off with Toonz Raster levels. If your issue is just too much vector data, using the "Vectors to Toonz Raster" command in the Level menu would resolve the problem - though you would lose the layers.

**Comment by qwert234** [comment]
Thank you for your reply @artisteacher ! I think I have preview turned on and when I press play the image flashes but does not move as I had animated it to do. I waited quite a long while and it still won't play. I am using vector levels and my image is not too complex or sketchy with only the fill tool used to fill in the spaces. I hope this helps. Thank you!

**Comment by artisteacher** [comment]
In that case, this is probably a related specifically to Preview. In case it's not, can you play normally with preview on in the other rooms? Can you play successfully in the Animate room without preview on? What about using the preview window (CMD-R)? Does the size of the viewer make any difference?  Do you have any specific FX enabled?

Personally, I haven't had a lot of success playing with preview on directly in the viewer - whatever the room. Any large or complex scenes seem to require too much processing. If I'm patient enough to wait, the frame rate is always crazy low. Then if I want to play again right away, it starts calculating from the beginning - so another really long wait. Right now I'm using FX with my students and even turning preview on for a single frame (without trying to play) can be such a long wait that it's hard to tell if anything is happening or if it's hanging. Of course, our Macs are super old, so the problem may be old hardware just as much as anything specific to OT. This is definitely an area with room for improvement!

**Comment by turtletooth** [comment]
Do you have the playback markers set to only play one frame?

**Comment by qwert234** [comment]
@artisteacher I can't play it even without preview on or in other rooms without or with preview in other rooms. I tried opening another scene and it worked fine. 
![Screen Shot 2019-03-22 at 6 33 01 PM](https://user-images.githubusercontent.com/48817507/54856480-268a8980-4cd1-11e9-9067-7da633c02309.png)
This is what I see:

**Comment by artisteacher** [comment]
@turtletooth’s suggestion looks like the problem. Right-click in the frame number area of the Xsheet and select “Remove Markers”.

**Comment by qwert234** [comment]
IT WORKED!!! THANK YOU SO MUCH @artisteacher and @turtletooth !!!!

**Comment by qwert234** [comment]
I have another question I'm hoping you guys could help with please! How do I get the music to play at normal speed when I decrease the frame rate for the rest of the levels?

**Comment by turtletooth** [comment]
You need to change the frame rate in the scene settings in the xsheet menu for the audio to play at the correct speed.  The slider on the viewer is for temporary frame rate changes.

**Comment by qwert234** [comment]
Ok thank you so much!

**Comment by qwert234** [comment]
Sorry to bother you guys with so many questions, but I'm new to this and still learning:

How to I attach the keyframes to their respective frames so the keys move when I move the frames in the Xsheet?

**Comment by artisteacher** [comment]
If you hold down on command when selecting the frames you want to move, the keyframes should be selected too (they'll turn blue) and move at the same time.

**Comment by phillycheese007** [comment]
@artisteacher 
when i do the command click drag...i get a duplicate of the keyframe...how to avoid this?

**Comment by hem2073** [comment]
can anyone please help me!
iam unable to see my animations as well as any of the drawings that i have made .
though they are showing in level sheet.
![Screenshot (8)](https://user-images.githubusercontent.com/66516810/83942791-8574e980-a816-11ea-9a16-bc7ccb0ca21e.png)
