### ISSUE TITLE
Render Crash (Vector)

### ISSUE THREAD

**Issue by DustyShinigami** [opentoonz/opentoonz#2579]
### Issue Summary
OpenToonz will randomly crash when I try to render out an animation. It's usually a sign when the progress bar stops and does nothing for a second or two. The program just crashes to the desktop.

### Screenshot or Video Reference

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28167573/54884820-4a82d200-4e6d-11e9-96b9-6cc8d4620c7f.gif)

### Steps to Reproduce

Go to File > Output Settings... > change the file type (png, jpg etc) > hit Render.

It's also done it by simply going to File > Render.

### Expected Results

The progress bar stops during the process for a second or two before crashing to the desktop.

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**: Windows 10 Home 64-bit
* **CPU**: Intel Core i7 7700HQ 2.80GHz
* **Memory**: 8GB DDR4 RAM
* **Graphics Card**: MSI GTX 1060
* **Graphics Tablet**: Wacom Intuos

**Comment by artisteacher** [comment]
I’ve gotten a fair amount of crashing during rendering and preview myself on macOS. It definitely seems more likely to happen if I’m using FX or if I’m using the plastic or skeleton tool. I’m usually using sub-xsheets in combination with the plastic tool or skeleton tool, but I have no idea if that makes a difference.

@DustyShinigami - have you found any repeatable steps that always trigger a crash? Do you have the same problem with other level types? The more information we can give the developers, the more likely they are to find a fix.

**Comment by manongjohn** [comment]
@DustyShinigami For the scene you are trying to render, does it crash repeatedly on a specific frame?

What happens when you turn on Preview and try to play it back? Does it crash when it gets to a certain point.

There could be any number of issues, usually something wrong with a particular frame in one of the levels, an issue with Fx on a particular frame.
Another thing to rule out is making sure you are using the GPU on your graphics card. At least on NVIDIA cards, it sometimes helps to create a 3D profile for OpenToonz.exe configured for high performance.  Also, if you are rendering through ffmpeg, increase the timeout.

**Comment by DustyShinigami** [comment]
It appears to be random and on a random frame. One minute it crashed on frame 58, the next it was frame 59, but it had rendered out 110 frames in the output folder. And on another occasion it got up to 63/64 frames and rendered out 89. As far as I'm aware, I don't have any Fx on a particular frame. Unless I'm misunderstanding what they are and when/where they're used. All the animations are vector and I only used the selection tool and the control point editor to adjust the frames. I'll try setting up a 3D profile in the Nvidia Control Panel though. The Previewer is fine.

**Comment by phillycheese007** [comment]
@manongjohn 

when you say "usually something wrong with a particular frame in one of the levels, an issue with Fx on a particular frame"
is there a particular most common culprit?

@DustyShinigami
haha i was getting lots of frame58 crashes too.  all of mine except for that seem to be related to reaching some memory limit or something...(my tiny scenes can reneder several hundred frames befroe crashing)

one thing im really glad to have found is the ability to save my previewed frames.  the other day i had a project (mesh character w like 3-4 meshes and several hundred frames(not big rite :)?)     the thing would not even render one frame b4 crashing....i tried like 10 times.....and as i started to cry....i rememebered glancing and reading that icon a while back and ...VOILA! it worked no problem. 
It is frustrating that it worked that much better than "ouput setting" path to rendering.

(all this is png images)

**Comment by synk-a-dynka** [comment]
I also often get render crashes.
If I render a scene I've been working with it almost always crashes. If I restart OT and start rendering from a freshly opened scene it happens less often.
The crashes almost always happen at the precomputing stage.
The crashes are segfaults so there seems to be some kind of memory issue.

WORKAROUND:
Batch render in tasks does not crash. I can line up 15 scenes without any render crash (did that yesterday).
Right-click scenes in the OT file browser and add to render. Then run the task list.

I haven't tried CLI render yet but the issue seems to be with the UI.

Ubuntu 18.04.1, OT 1.3.0 Morevna 190202

**Comment by artisteacher** [comment]
I just tried batch rendering and it failed...but no crash.

**Comment by RodneyBaker** [comment]
Just to be sure... makes sure ffmpeg is downloaded and all three required files are in their proper location.

Aside:  If batch rendering fails to run for specific image formats this also can relate to ffmpeg not being connected in Preferences.

**Comment by RodneyBaker** [comment]
I've recently had first hand reports of the new ffmpeg timeout default of 600 working well.
For those experiencing render crashes please try a current nightly release as that very well could resolve the issue.

@DustyShinigami @animationista Are you seeing similar issues with current releases?

**Comment by artisteacher** [comment]
My students still get a good deal of crashing when trying to render. It happens more frequently when using fx, skeleton tool, plastic tool and/or sub-xsheets. If they render an image sequence first (using the default tif format), instead of fast render or rendering directly to a gif, there is often still crashing. So I wouldn't say that this is necessarily related to ffmpeg. 

This is generally what happens:
When rendering an image sequence, the first crash might happen at any frame number - let's say frame 34. We'll render again, starting at frame 34. It might render a ways and then crash again - lets say at frame 179. Rendering again starting from 179 might always crash immediately. If we skip frame 179, and render from frame 180, we might run into another crash later on, or might successfully render the end of the sequence. For some reason rendering the problem frame by itself (with the frame start and end as 179), renders without issue. Loading the rendered sequence into a new scene renders to mp4 or gif successfully.

**Comment by artisteacher** [comment]
It seems that animating the camera also causes a render crash #3179. Perhaps the crashing is related in part to keyframes?

**Comment by RodneyBaker** [comment]
@DustyShinigami Any better luck with v1.4?

**Comment by matitanimata** [comment]
(using a recent nightly build of OT 1.4 but this is a problem I always had with mac osX and win 10 both) When the scenes are a bit long and heavy (several plastic rigged character, nested subxsheet) the rendering doesn't work and OT crashes afeter a bit, also using the render farm. The workaround is to export several short mp4 or export an image sequence with the render farm, a few frames at a time (about 100 or less) to avoid crashes.  IMHO this is a severe obstacle to use OT in a real production.

**Comment by ErwinBr** [comment]
I'm having crashes as well on Mac OS (Catalina) and my animations are typically cycles of 10 frames without the use of FX, plastic, etc... Did a fresh install yesterday, went OK for a while, but now it's back.

**Comment by jozsefk9** [comment]
I got crashing while rendering too. On Linux it reaches the frame 20 approx and crashes. I tried Half of the CPUs and Medium Tiles but no changes. Is there a way to do the render from CLI?
On Windows 10 (virtual) it reached frame 80 then crashed. Second time I tried Half CPUs and then it worked.
I got OT 1.4 AppImage on Linux. Nividia and CUDA installed.

**Comment by BrianIdeally** [comment]
Hi there,
I have same problem with AMD system.
When I check my RAM, I have 16GB DDR4, I start rendering MP4 1000 frames, it crashes between frame 300 and 500 always.
I used OT 1.4 and 1.4 nightly build 09-09-2020.
It still crashing at mp4, avi .....all ! 
What I figured out:
My RAm is going up to.....4 gb....5gb...at frame 350 it is 10gb full..........at frame 597 it is at 15,6gb/16gb full.
I can not set 3D profile at radeon graphic card.
Workaround: Only rendering until 500 frames or buying mor 16gb ram =32gb then I could at least render 1000 frames at once :(
But good software, sadly rendering is so important :'(((

**Comment by jozsefk9** [comment]
I figured out what was the problem in my case. I used the plastic tool on two overlapping layers. But on one I had a keyframe on every frame, on other later, keyframes were on every other frame (means there was an empty frame (without keyframe) in between of two frames with keyframe). And that caused OT to crash on Linux.

**Comment by BrianIdeally** [comment]
Hi together i know **HOW TO REPRODUCE** !!!!
@jozsefk9 , this was not my case of crash but thanks...

Please read all other as follow, how to reproduce crash:

I found out the problem is the MESH PLASTIK tool --> BUILT SKELETON. Version 1.3, 1.4 + 1.4 nightly. Win10.

It is **not** keyframe, it is **not** animation of mesh. Create mesh is OK. RAM is ok. Maybe I will check if layers could harm the skeleton mesh but anyway.

Only when I **CREATE** MESH SKELETON "1,2,3..." -> DDR RAM going full --> CRASH !
It is not important to create specific bones, it is sufficient **ONLY TO CLICK "CREATE SKELETON"** = Crash !

Sorry for big letters.
I hope this helps developers!

See also **picture**.

![20200928_220432](https://user-images.githubusercontent.com/71042824/94487680-ab693400-01e1-11eb-93ea-87c44a6e58f4.jpg)

**Comment by mannyc928** [comment]
I'm using 1.5 and getting this error when trying to render also has anyone found a decent workable render? I've tried changing the page size stuff and still get this .

**Comment by RodneyBaker** [comment]
@mannyc928  If you haven't investigated batch rendering (task rendering) that has proven to work well for many users.
Basically, right click on the scene file (.tnz file) in the browser or other appropriate location and add the scene as a Task to Render.  Then in the Farm room (renamed as 'Tasks' in v1.5) you can adjust settings and render all or some of the frames... depending on chunk size.   

Task rendering is also useful for rendering specific frames and finding out where troublesome frames are located... which can then be isolated, reviewed and rendered out separately.

Also, if not rendering out to image sequences... but rather to MP4, AVI, MOV... that can be problematic for some systems.
It is usually best to render out to image sequence first (for a number of reasons) and then later recompile them into the movie/video format.

**Comment by mannyc928** [comment]
> @mannyc928 If you haven't investigated batch rendering (task rendering) that has proven to work well for many users.
> Basically, right click on the scene file (.tnz file) in the browser or other appropriate location and add the scene as a Task to Render. Then in the Farm room (renamed as 'Tasks' in v1.5) you can adjust settings and render all or some of the frames... depending on chunk size.
> 
> Task rendering is also useful for rendering specific frames and finding out where troublesome frames are located... which can then be isolated, reviewed and rendered out separately.
> 
> Also, if not rendering out to image sequences... but rather to MP4, AVI, MOV... that can be problematic for some systems.
> It is usually best to render out to image sequence first (for a number of reasons) and then later recompile them into the movie/video format.

You're amazing, I guess I was just not looking hard enough 🤣 finally getting the scene to render thank youu

**Comment by RodneyBaker** [comment]
For those experiencing problems rendering it will be good to test again with the latest nightly as of this date (11 Jan 2022).
Updates hopefully will have resolved the problem for some cases although perhaps not for specific cases related to Plastic Tool... although that would be good to confirm as still having issues.

**Comment by matitanimata** [comment]
thank you @RodneyBaker , I've given it a try just now, but unfortunately had still a crash while rendering an mp4 (several plastic elements, about 400 frames, on my mac).

**Comment by RodneyBaker** [comment]
I know in the comments use of Plastic Tool was a recurring theme but wanted to capture the original reporter's specific situation.  As such I've added "(Vector)" to the title.  There are several open reports that should include use of Plastic Tool in the process.

**Comment by RodneyBaker** [comment]
The main solution for most rendering crashes appears to be use of batch/task rendering to image sequence as that will free up memory.

For those still experiencing this issue please consider opening a new report with specific details and perhaps project file that can be tested against.

We should try to reference this and other similar reports in those new reports as well.
