### ISSUE TITLE
Raster brush overlapping issue

### ISSUE THREAD

**Issue by Nudders** [opentoonz/opentoonz#2602]
### Issue Summary
Whenever i try to combine two brush strokes that are from a different style (which are both raster brushes) theres this issue that i am not sure how to describe in words, so i'll give a screenshot. I am using a Toonz Raster layer

### Screenshot or Video Reference
![Capture1231](https://user-images.githubusercontent.com/35895238/56541565-0403be80-6564-11e9-95c5-370fcb5c5d25.PNG)

### Expected Results
I was expecting the colours to just blkend in together, but it doesnt.
![image](https://user-images.githubusercontent.com/35895238/56541656-40371f00-6564-11e9-8d04-7e1008d59708.png)

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**: Windows 10
* **Graphics Card**: AMD Ryzen
* **Graphics Tablet**: Ugee M708

**Comment by artisteacher** [comment]
I think this is a known issue when using raster (MyPaint) brushes on toonz raster levels. Currently, they don't blend - likely due to how the styles can be updated. It's worse when you are using translucent styles. For now, when you need actual blending, you might want to do those areas on raster levels. Also, using multiple toonz raster levels could help too.

**Comment by Nudders** [comment]
Ah.. That makes sense then.

Yeah i have been making multiple toonz raster levels, though i may change to raster levels for my backgrounds.

Thanks, i'll be closing this since this issue has already been brought up then.
