### ISSUE TITLE
Transparent gif render issues

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2628]
### Issue Summary

Scenes with transparent backgrounds render inconsistently to the gif format.  On some computers, the transparent gif is always perfect. On some computers, the gif renders with a black background #2623. On some computers, the gif is transparent, but there is ghosting from the previous frames #2560. 
### Screenshot or Video Reference

Black background:
![transparent](https://user-images.githubusercontent.com/21159116/58493248-8291e400-8140-11e9-8e3a-dc7df9a8f0ac.gif)

Ghosting:
![transparent 2](https://user-images.githubusercontent.com/21159116/58495491-a73c8a80-8145-11e9-97df-83837e746023.gif)

Setup:
Both scenes and levels use the default settings.  44 frames, vector levels, no plastic or skeleton tools, no special fx.
![Screen Shot 2019-05-28 at 12 04 03 PM](https://user-images.githubusercontent.com/21159116/58493378-d00e5100-8140-11e9-91a8-1649acf45dbf.png)
![Screen Shot 2019-05-28 at 12 03 53 PM](https://user-images.githubusercontent.com/21159116/58493382-d1d81480-8140-11e9-91e8-69c235bff240.png)
### Steps to Reproduce

1. In a new scene, leave the default scene settings (transparent camera background)
2. Create a simple animation without any background
3. In Output settings, change the render format to gif
4. Render
### Expected Results

No ghosting, no black background. 
### Actual Results

It depends on the computer - on an old iMac, the gif has a black background (also reported on Windows in #2623). On an old MacBook Pro, the gif has ghosting. On fairly recent MacBook Pro running Mojave, the gif is transparent with no issues.
### System Information
* **OpenToonz Version**: 1.3, latest nightly build
* **Operating System**: macOS 10.13.6, MacOS 10.12, Windows 8,1
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
I love the new capability to render transparent gifs! 

If it's not feasible to get the same performance on old devices, it might be helpful to give gifs a white background by default (the old behavior). I would only recommend this if an "enable transparency" checkbox was added into the gif output settings. Or perhaps there could be a preference to enable/disable gif transparency.

**Comment by RodneyBaker** [comment]
An issue here is that GIF transparency was never added to Opentoonz.
It, thankfully, appeared as a side-effect of another change (accounting for image formats that don't have alpha channels).  While it sounds odd to say it, GIF transparency still technically needs to be added as a feature in Opentoonz... even though we currently have it!  As such I'll tag this as a feature request/enhancement.  We'll keep it open for the present because it's in that grey area between bug and enhancement.

Several workarounds exist for those on older Macs and with older releases of Opentoonz (on windows as well.  For those experiencing the issue we can explore those in greater depth.

@turtletooth As you are familiar with the code integrating ffmpeg with OT and where it left off relative to GIF transparency you'll have some insight into this that we lack.

cc @shun-iwasawa (as the author of the PR dealing with RGB images lacking alpha channel.

**Comment by artisteacher** [comment]
I updated to macOS Catalina & there is often ghosting from the first frame. Depending on the placement, it can last a while. Unfortunately, duplicating the first frame & delaying the render as mentioned by @RodneyBaker doesn't make a difference.

**Comment by artisteacher** [comment]
Still an issue...
