### ISSUE TITLE
"Forced squared pixel" can not turn off

### ISSUE THREAD

**Issue by CallofAS** [opentoonz/opentoonz#2633]
Hello~ Sorry that my English is not very well.
I got the problem while I working with some pixel pictures. 
In **Level Settings**_**DPI&Resolution**, the **Forced Squared Pixel** option has something wrong. Even if I didn't check it. the DPI values are also automatically converted to the same value.

This is really hurt when I work with some pixel animation. 
When you used the Animation tool changed some parameters of the pixel picture. the pixel looks like have Anti-aliasing. 
Please, fix the Dpi option bug.

opentoonz version: 1.3 (built Jan 30 2019)

**Comment by Lovewyrm** [comment]
This is probably related to this, and not the fault of "forced square pixel" settings.
https://github.com/opentoonz/opentoonz/issues/1782

Instead it's very likely the animate tool generating pixel positions with fractions, aka x:150.467 , instead of a whole pixel position like 151, or 150.
If a fractional position is generated, opentoons will interpolate the raster object by using the method for sampling set the output settings.
Choosing nearest neighbor will help, but it might cause some distortion depending on how fine the movement is, and how much fractional movement is generated by the animate tools keyframes.

**Comment by CallofAS** [comment]
> This is probably related to this, and not the fault of "forced square pixel" settings.
> #1782
> 
> Instead it's very likely the animate tool generating pixel positions with fractions, aka x:150.467 , instead of a whole pixel position like 151, or 150.
> If a fractional position is generated, opentoons will interpolate the raster object by using the method for sampling set the output settings.
> Choosing nearest neighbor will help, but it might cause some distortion depending on how fine the movement is, and how much fractional movement is generated by the animate tools keyframes.

Thank you, 
I remembered that I imported images but there are fractions in their DPI values. 
I will try the Resample Balance option.
