### ISSUE TITLE
(Discussion) Color Index + 1?

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#2642]
@shun-iwasawa What do you think about changing the color index numbering to visually start at 1?  This would make the palette commands easier to use and make the colors make a little more sense to non-programmers since most people don't start counting at 0?

**Comment by RodneyBaker** [comment]
An issue with this color indexing is users confuse the color index 0 (zero) as white when in fact it is simply a transparency.   This surely relates to the Japanese animation industry using white for transparency.  I'm not sure how to best address this issue as I like the use of 0 and 1 as current but constantly create a new color white... trying to ignore the color zero to best of my ability outside of specialized usage.   

I'm not sure if this would address the issue but a random thought:
In Preferences an option could be created to hide the first zero swatch thereby starting (visually) with 1 but then also add in a second color 2 that is fully opaque white.

**Comment by beeheemooth** [comment]
For drawing in OpenToonz, I have a separate keyboard, on which there are more buttons than on a regular one (this is for using macros). It must sound funny, but, among other things, I picked out all the buttons of the numbers on it and rearranged them in places, so that 0 was at the beginning. :)

**Comment by gab3d** [comment]
My problem with Styles numbering is not with the current index system (I see the fact of the "null" color being "zero" to be a good match), but mainly due to the keyboard shortcuts used to select those colors being shifted by 1, with respect to the displayed index numbers. That is counter-intuitive...

**Comment by RodneyBaker** [comment]
@gab3d  I agree. 
So is the solution to have an option (presumably in Preferences) to decrement the index shortcut(s) by one?
If that is the case then... I'm all in.  :)

**Comment by gab3d** [comment]
Perhaps, if color_0 could be shown in a way that makes clearer to the user that is a "non-color", and not just white. I mean, it's clear that at the bottom of the color_0 swatch there is a checker indicating that it is transparent, but perhaps that is not enough, and it could be made visually more clear, by having the checker dominate the swatch space, or something like that...

**Comment by artisteacher** [comment]
> In Preferences an option could be created to hide the first zero swatch thereby starting (visually) with 1 but then also add in a second color 2 that is fully opaque white.

I wouldn't hide the transparent swatch. Instead I would rather see 3 default styles. Transparent, black, and a third style for white. The transparency grid at the bottom of the icon could be a lot more clear (for any color with low alpha). Having a second row (like the largest icons) and perhaps using some grey, could make it more obvious.

**Comment by gab3d** [comment]
@RodneyBaker 

> So is the solution to have an option (presumably in Preferences) to decrement the color index shortcut(s) by one? If that is the case then... I'm all in. :)

It certainly would for me too.

> That does present an issue with shortcut for the current zero index (as that would then be -1) so another shortcut would need to be specified to allow for that.

That won't be necessary, 0 would be the shortcut for color_0, I think that's no real problem.

In the past I've proposed this to @shun-iwasawa but he was reluctant to change the shortcuts because of  studios using the shortcuts from the main keyboard (and not the numerical one), and saying that in the main keyboard the 0 key was at the other end of the key layout, so it would be impractical to use (as color_0 is an often selected Style). 
But I think having the option in Preferences wouldn't hurt, and for sure it could make other users fit better.

**Comment by melieconiek** [comment]
I'd personally prefer that hardcoded bindings like this be eliminated. I use the number keys for other bindings so I can't use palette shortcuts at all--they're disabled.

Is there any reason that these can't be rebindable?

**Comment by shun-iwasawa** [comment]
I was considering (but not yet started to tackle with) adjusting the palette layout.
In particular, moving the color_0 chip out from the chip array of other "normal" styles.
It will make color_1 to the upper-left corner of the palette and will assign 1 key for it.

**Comment by shun-iwasawa** [comment]
@melieconiek

> Is there any reason that these can't be rebindable?

I understand your demand for setting any keys for the style selection feature.

I made this to be hardcoded for some reasons as follows:

- The shortcut key for style selection was originally introduced in order to gain consistency with Retas PaintMan, a de facto standard Ink&Paint software in Japanese animation industry. They all are familiar with using numkeys, so it is more useful for them to enable all numkeys at once by just checking the preference option, than to enable any shortcut keys for selecting any style.

- Making the keys rebind-able means 10 extra commands will be added to the shortcut popup (i.e. `Select the 1st style` , `Select the 2nd style` , and so on) . I thought it will become too messy for just one functionality.

**Comment by gab3d** [comment]
@shun-iwasawa 

> I was considering (but not yet started to tackle with) adjusting the palette layout.

That sounds great to me!
I mean, in general the palette is functional, but I think some usability/clarity issues could be addressed.
Some things I would like impreved:
- A more clear way of adding a new style. The current **New Style** button is camouflaged between several other alike ones, that is not immediately evident how to add a new style. Perhaps a shortcut to add a new style could be handy for advanced users also.
- Currently, style Page tabs compete for screen space with the buttons; that is especially evident when there are several Pages and the Room layout is so that the space reserved for the Palette is a thin one (like in Drawing or Timeline ones). Perhaps:
    - Tabs and buttons could be in different rows, at the cost of some vertical space.
    - Tabs could be in a vertical layout, at the cost of some horizontal space.

Another possible way to alleviate both of these problems could be to change the Add buttons by **+** signs in the appropriate places:
- for style Pages, at the right of the last Page.
- for styles, at the right of the last Style.

![palette](https://user-images.githubusercontent.com/18104091/59537873-47c4d580-8ece-11e9-8912-e5eb8c8afd42.png)

**Comment by artisteacher** [comment]
I think that the plus icon next to the last style swatch is a really great idea. New users often miss the new swatch icon. 

I don't feel like it looks as cohesive for the new tab though. What about adding the button directly to the first or last tab? Of course if the tab is out of view, that would be an issue. Though you can always use the context menu.
<img width="705" alt="Screen Shot 2019-06-14 at 11 16 22 PM" src="https://user-images.githubusercontent.com/21159116/59546402-ca638a00-8efa-11e9-8521-87b85453ea67.png">

**Comment by konero** [comment]
Space management could be solved by allowing the option to move the toolbar to the bottom of the window for those that want to use multiple pages.

@shun-iwasawa It would be neat if there was an additional layout similar to the grid view in PaintMan where color chips are shown in groups of 10. Since a lot of manual positioning is done to separate colors by lightness, that way you can tab into different lightness groups. So skin is always '1' no matter which group you're in, hair is '2' (or whatever), which is just one way to do it.

PaintMan panel:

![ret2](https://user-images.githubusercontent.com/19820721/59549417-15aa8680-8f55-11e9-9d7b-b4761ae0f880.png)

Mockup _(including other users suggestions above, but the grid view is what I'm suggesting)_:

![OTRET1](https://user-images.githubusercontent.com/19820721/59549668-e6961400-8f58-11e9-9f55-84e1ac17641a.png)

Since the layout is saved per room, it's possible to have the full large chip size in PltEdit and the smaller grid view in an InknPaint workspace with the navigator panel open.

**Chip Size:** 15x15
**Selected Chip Border Size:** 2 (white in image, placed inside grid)
**Group Selector Size:** 2 (gray in image, placed outside grid)
**Grid Margin from Panel Border:** 3

![chip](https://user-images.githubusercontent.com/19820721/59549568-8c488380-8f57-11e9-9f74-06be822f06c0.png)

**Comment by DarrenTAnims** [comment]
Hi all.

I agree with the original posts suggestion of moving the colour indexes by 1. When I've got 3 colours and they have the numbers, 0, 1 & 2 written on them. It makes no sense to press 1, 2 or 3 to access them. That's really bad design, whatever the reason. Especially for newbies. If you press 1, 2 or 3 and they have numbers written on them and you can't remap the keys to press, then they should have numbers 1, 2 & 3 written on them.

Also, as the conversation has moved on to some more general UI suggestions for the palette: 

I've proposed the idea of having a plus next to the tab to add a new tab, in the same way you have a plus next to the tab in Google Chrome. It's where people expect to see it. I don't think it needs an extra button.

And having a blank colour swatch with a plus in it is a great idea to show adding a new colour.

I know screen estate is important to everyone, but it'd be super useful to have the tabs on a separate row to the buttons, so that you still have space for some of them both when you reduce the width of the panel.

Finally, I don't think the save buttons are used that often, so perhaps these are best left in the context and popup menus. And the widget to the left of them doesn't really do anything. It just seem overly cluttered when most people want to add new colours & tabs more often than anything else.

**Comment by artisteacher** [comment]
I like the new tab option from @konero. The plus without a button style works well. The menu at the bottom is more readable, though it does sacrifice some vertical space. The issue with the grid view is that the level palette displays styles (ie. brush/texture + color) - not just colors. The squares in the more standard grid view would be perfectly fine if the palette dealt with color separately from brushes/texture. As it is, there might not be enough room to see the brush too.

The major downside I see to the proposed new style/new tab buttons is that depending on window width and number of styles, they may not always be visible. Ie. with a large number of styles, if the new/empty style button is always last, it may not be visible when the scene is loaded, without scrolling. Of course, the same can be said of the current buttons now, if the width of the window is too narrow. I do think that the added clarity would be worth it.

What about something like this? + for new tab. Empty style with + for new style. Save options moved to hamburger menu and/or context menu. Remaining menu items moved to window header, next to the power? button. No vertical space is lost on small screens - though palette name is more likely to be cut off on narrow windows.
<img width="510" alt="Screen Shot 2019-06-15 at 11 37 25 PM" src="https://user-images.githubusercontent.com/21159116/59558719-a40b2080-8fc6-11e9-9acf-0183e40bb556.png">


As far as the color indexes, I agree that adjusting them by one makes sense. I'm curious about where color_0 would display if it were moved.
> In particular, moving the color_0 chip out from the chip array of other "normal" styles.

**Comment by beeheemooth** [comment]
@DarrenTAnims , @artisteacher Wooow! This idea with pluses instead of buttons is just super amazing!!! I love it!

**Comment by RodneyBaker** [comment]
This issue reminds me that it would be good to have the third color swatch be a full white by default.
I know this is something of a potential issue with Japanese industry where white is used for transparency but any system that doesn't forces users to create a white color swatch.

While looking at adjusting the default palette it might be worth considering expanding it at least two more to include the red and blue used for linework indicating shadow and highlight.

And... if the default palette is updated to have Transparent, Black, White, Red and Blue... perhaps a consideration of other colors too.

Just following the general trail of logic but also the constant need to create new color when drawing digitally.  A workaround for this obviously would be a standard workflow such as immediately going to the Master palette window, right clicking on a palette there and 'Apply colors to current palette'.

I suppose a question that might be asked is... besides simplicity... what are the core benefits of having only the transparent and black colors in the default palette?

Regarding this Issue/Request from @turtletooth... it seems to me that if we were to add a white color swatch immediately after the transparent color swatch we might be able to resolve the underlying issue.  A toggle in Preferences then would allow the user to choose between transparency and white for the color assigned to zero.  This would have the added benefit a helping users realise that the first color swatch is not white but in fact transparent.

**Comment by RodneyBaker** [comment]
Will close this as a question asked and answered.
Those interested in seeing color indexing are welcome to continue the discussion or open a new report as necessary.
