### ISSUE TITLE
ArtContour + Particles crash

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2663]
Repro steps:

1. Create a new level of any type and draw something on it so it is not blank
2. Create the following setup in the FX Schematic
![image](https://user-images.githubusercontent.com/42905003/60747901-7f301a80-9f80-11e9-8d07-cd59df17985c.png)
3. Attempt to render - crash

**Comment by RodneyBaker** [comment]
This makes me think there needs to be a interim render node where the results from one or more nodes gets rendered first before the flow continuing.  Programs such as Blackmagic Fusion have a node such as that where a bitmap is created and then subsequent nodes work from that.

This is a bit like Baking... so I'll suggest such a node could be of that nomenclature.
I believe this would of course constitute a new feature as I don't think there is any node that could be shoehorned into that at present.  I'll be happy to be wrong.

As for this crash specifically I'll guess there needs to be a mechanism to allow for the particles to completely render before the Art Contour gets handed the data.  (presumably this would be true of other simulations)

**Comment by RodneyBaker** [comment]
Follow up thoughts on this report...

Possible way forward

Short term
Add test to determine if input into a port is from a particle node.  Provide error message

Longer term
Develop render node to allow for particles to pre-render in order to continue down the flow into other input ports.

Basic Logic
If input is particles
If particles are not suitably pre-rendered
Display error message
Else continue with processing of flow

**Comment by RodneyBaker** [comment]
Relates to #1330 also
