### ISSUE TITLE
idea: save project to a single toonz archive file (command), open toonz archive (command)

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#269]
Opentoonz right now has project scattered in levels, scenes and other files in a folder structure. That makes work slightly more difficult when sharing between users on the web.

What if we were able with a single command to save the whole project with all of it's files to a single archive file - compressed in zip or 7zip - named with a projectname.ota instead of projectname.zip suffix.

Lets say you have an example scene, you want to send to a friend. That kind of a thing thing will make it so easy to quickly upload it to somewhere and for them to open it with a single command. You will save space because the project is archived, they will download it faster too.

**Comment by blurymind** [comment]
Tvpaint uses archive type files. They are easy to send to a client too. Very useful when you do freelance work.

**Comment by walkerka** [comment]
I like the idea to an exporter option which packs separate files into one. But It's very risky to use single file based format, especially for binary format. Unless your app never crashes, or the file format has transcation support (like sqlite).
I heard about some users got corrupt TVP file when saving. And they lost months of work because of no backup.

**Comment by blurymind** [comment]
@walkerka unfortunately the corrupt tvpaint file bug has happened to me
once. You are right - it should be just an easy option to exchange projects
- not a default saving format!

**Comment by blurymind** [comment]
Perhaps if OT saves the project to a single file, without applying any compression - that would be safer?

@walkerka what do you think ? :) 
I believe that is how construct2 saves a project to a single capx file.

**Comment by walkerka** [comment]
Uncompressed format is safer but still corrupts for saving crashes. At least it's easier to recover remained data, especially for text based formats.
Sqlite is safe from crashes because write operation can be protected by transaction. Then the operation is either done completely or not at all, no intermediate state.
https://sqlite.org/transactional.html

**Comment by RodneyBaker** [comment]
Thanks for the reference @blurymind 
I should have investigated this request (#269) instead of opening a new request.  
I like the (new) title of #669 mostly because it specifically states what success looks like; Consolidate All Project Resources to Compressed Zip File.  Otherwise mine could be closed or merged with #269.

Aside:  Perhaps we should investigate OpenToonz Subversion (SVN) option before delving too deeply into this request.  My thought here is that all things considered it is better to have access to every change made to a project than to have access to just the current project.  The primary benefit of a .zip file over standard use of SVN would be that of having all project files (however many) all inside one file (the zip file).  Even here however the SVN option is the greater of the two because the zip file could be used within SVN thereby gaining the benefits of both the iterative/nondestructive production workflow as well as the consolidation (of many assets into a single file/location).   

I will likely close my request with a comment pointing to this request unless someone suggests keeping that one open.  Perhaps we can differentiate the two requests so they focus on different but related aspects.

Thanks guys!

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
