### ISSUE TITLE
Double toolbar in fullscreen (osx 10.11.4)

### ISSUE THREAD

**Issue by aars** [opentoonz/opentoonz#271]
The room switching toolbar is drawn twice when going into osx-native fullscreen mode.

![screenshot](http://i.imgur.com/N0Bd2Cq.jpg)

I see this in both the downloaded pkg installed version and the homebrew installed version (not sure if they differ, both 1.0)

**Comment by artisteacher** [comment]
This is still a problem on OS X 10.11.6 (El Capitan) in both 1.1.1 and in the latest nightly build. The Tool option bar actually disappears in fullscreen - perhaps as it is being overridden by the room menu. When using the combo viewer instead of the default setup, the tool option menu is still available in fullscreen.
![screen shot 2016-10-20 at 11 07 41 am](https://cloud.githubusercontent.com/assets/21159116/19598256/eca4eac4-9767-11e6-8b7f-ccbd891d7809.png)

**Comment by artisteacher** [comment]
Toggling "show tab bar" from the view menu (when in fullscreen) removes the extra room menu from view.  Switching back does not result in the second menu displaying. Toggling it outside of fullscreen makes the second room menu visible, instead of just showing/hiding the original room menu.

**Comment by artisteacher** [comment]
This is fixed in the latest nightly build.

**Comment by artisteacher** [comment]
In 1.2 the double toolbar is gone - I think this can be closed.
