### ISSUE TITLE
Vector Fill Tool does not detect areas between geometric shapes

### ISSUE THREAD

**Issue by mosujiba** [opentoonz/opentoonz#2726]
### Screenshot or Video Reference
![ot_bug](https://user-images.githubusercontent.com/5388020/63631943-ec187600-c5fb-11e9-8ed5-ddaf1122f574.gif)

### Steps to Reproduce
In a vector level, use the Geometric Tool to create two shapes. Close the space between them. The area is unfillable.
This issue does not occur if the shapes are drawn with the Brush Tool.

### System Information
* **OpenToonz Version**: 1.3 
* **Operating System**: Windows 10

**Comment by RodneyBaker** [comment]
There is an option under Level in the menu... Replace Vectors with Simplified Vectors**.
Try that and that should resolve 99% of your fill issues with vector, or at least those that aren't due to drawing lines too far apart.

**That names is hard to type and tell people about so I often call it just 'Simply Vectors'.

**Comment by beeheemooth** [comment]
@mosujiba This happened because you had the "Auto Group" option for the Geometric Tool turned on. Ungroup the circles and fill will be possible.

**Comment by gab3d** [comment]
what @beeheemooth said.

**Comment by mosujiba** [comment]
Thank you @beeheemooth . Ungrouping solves the problem.
