### ISSUE TITLE
Viewport Error

### ISSUE THREAD

**Issue by Raburigaron** [opentoonz/opentoonz#2728]
[https://imgur.com/4OtsCiF](url)
[https://imgur.com/JT1UiFy](url)

### Steps to Reproduce
This issue happens when the aplication is open always

### Expected Results
For the viewport to display the drawing space

### Actual Results
the viewport fails to render and causes a glitched view

### System Information
* **Opentoonz 1.3**: 
* **Windows 10**: 
* **Intel i1-6700HQ 2.60GHz**: 
* **8gb**: 
* **Intel R HD Graphics 530**: 
* **Wacom Cintiq 13**:

**Comment by RodneyBaker** [comment]
Your imgur links appear not to work.

I'll suggest investigating your Wacom Cintiq as a probable source of the issue.
It could be drivers, similar resolutions on multiple monitors (if present), order of connection... etc.

**Comment by manongjohn** [comment]
Since you are on Win10, can you see if it helps to force OT to use GPU:


1) Open Settings
2) Search for: Graphic settings
3) Click on Browse button
4) Find and Select: C:\Program Files\OpenToonz\OpenToonz.exe
It should add OpenToonz to the Graphics settings window.
5) Click the Options button for OpenToonz
6) Select: High Performance
7) Save

**Comment by Raburigaron** [comment]
> Since you are on Win10, can you see if it helps to force OT to use GPU:
> 
> 1. Open Settings
> 2. Search for: Graphic settings
> 3. Click on Browse button
> 4. Find and Select: C:\Program Files\OpenToonz\OpenToonz.exe
>    It should add OpenToonz to the Graphics settings window.
> 5. Click the Options button for OpenToonz
> 6. Select: High Performance
> 7. Save

Thanks you, this fixed the problem!
