### ISSUE TITLE
Windows 10 massive slowdown

### ISSUE THREAD

**Issue by OpentoonzTester** [opentoonz/opentoonz#2733]
### Issue Summary

Opening the program takes at least a minute, and saving any file is massively laggy.  It is causing crashes as I, for example, move a frame from one column to a new one, as the system takes so long to save each file or image, that it crashes if more than one save takes place within a short time.
### Steps to Reproduce

Just anything to do with disk writes.
### System Information
* **OpenToonz Version**: latest as at a24_08_2019
* **Operating System**:  Win 10
* **CPU**:  I7
* **Memory**: 16G
* **Graphics Card**: Quadro/Intel - (laptop with Quadro card - P3200
* **Graphics Tablet**: Relevant?  Yiynova MVP22 +U

**Comment by RodneyBaker** [comment]
@OpentoonzTester I'll close this pending new information that helps hone in on the problem.
In the meantime feel free to also ask in the Opentoonz Forum which has a Troubleshooting category:

https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting

If you haven't done so I will recommend backing up/renaming your Opentoonz stuff directory located at C:\Opentoonz Stuff.  You didn't mention a specific version of Opentoonz so that is important information also.  Older releases of OT will have created stuff directories with different names.

One useful troubleshooting method is to try out the latest nightly release to see if that resolves the problem.  Nightly releases can be found and downloaded here:  

https://github.com/opentoonz/opentoonz_nightlies/releases
