### ISSUE TITLE
Problem while using PerspectiveDistort_Iwa

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2745]
@shun-iwasawa 
The source column (toonz vector) dissapeared when previewing (both in viewer and in fx settings panel).

Then this message appeared when navigating fx settings preview:
![Sin título](https://user-images.githubusercontent.com/18104091/64035802-0e445380-cb28-11e9-809c-71990f79c544.png)

nightly from Jul 18 2019
Windows 10 notebook, i7, 16GB RAM, Geforce GT 650M (2GB dedicated RAM)

**Comment by RodneyBaker** [comment]
I was able to reproduce the 'Run out of contiguous memory' error via the PerspectiveDistort_Iwa node's  Previewwindow.

Steps to Reproduce:
- Create a level with vector imagery (I created three circles as in @gab3d image).
- Duplicate that frame in the same level
Note:  I'm not sure this step has anything specifically to do with the error but it's what I did to reproduce it.  I haven't tested all the various variables that could be tested here.
- Add a PerspectiveDistortIwa FX node in the Schematic piped from the column containing the vector level
- open the PerspectiveDistortIwa FX node
- open the Preview window of the node
Here I initially only saw a grey/blank preview
- click on the preview/eye icon in order to display the previewed image
- Note the error popup stating 'Run out of contiguous memory..."
