### ISSUE TITLE
Brush Tool - Last used settings not saved on preset selection.

### ISSUE THREAD

**Issue by melieconiek** [opentoonz/opentoonz#2757]
### Issue Summary
The last used brush settings are not saved when updated by selecting a brush preset--only when the brush setting controls are manipulated. Affects all three level types.

### Steps to Reproduce
Manipulate one of the controls on the brush tool's option bar. Select a brush preset from the dropdown on the tool option bar (something that will load different settings.) Restart OpenToonz.

### Expected Results
The brush tool should retain the brush settings that were loaded from the preset.

### Actual Results
The brush tool settings revert to the last time the brush settings controls were manipulated on the tool option bar.

### System Information
* **OpenToonz Version**: Latest Nightly 
* **Operating System**: Windows

**Comment by RodneyBaker** [comment]
@melieconiek initial testing appears to show this working as designed.
If we want to transfer the preset to the default settings of the brush tool so that the settings will still be there when we reopen we have to use File > Project Management > Save Default Settings*
This can be given a shortcut such as Ctrl + Shift + D for easier access to locking down those presets as default settings.

*Note for those looking in:  This is view the current menu organization in latest nightly releases.

Aside:  I want to thank you for posting this because I haven't used brush presets in the past and I should be using them.  I will be using them!

**Comment by melieconiek** [comment]
You can change the global default simply by manipulating the controls, there's no need to keybind anything. Why would changing the settings via a preset selection be any different from changing them by moving a slider? The work around I had for this was moving something on the tool option bar to make sure it had saved the change I had made.

The expected behavior would be for all tools, not just the brush tool, to retain whatever settings were last used--the brush tool isn't doing this properly. I seriously doubt this is working as intended.

**Comment by RodneyBaker** [comment]
I agree that it should be an easy update/enhancement.
I'll tag as UX enhancement and leave it open for further testing and validation.
I can see cases where a user would not want the presets to update the defaults so I'm not sure how that would be dealt with.
