### ISSUE TITLE
Camera1 cannot be deleted when the camera column is visible

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#2784]
### Steps to Reproduce

1. Show camera column
1. In Schematic, create a new camera (Camera2)
1. Switch the active camera to Camera2
1. Delete Camera1
1. Create a new camera again

### Expected Results

A new camera should be Camera1

### Actual Results

Camera1 and Camera3 are unexpectedly created.

This happens only when the camera column is visible.

### System Information
* **OpenToonz Version**:  latest

**Comment by manongjohn** [comment]
Actually, I discovered this bug exists in the official release while working on the camera column PR.

When you delete Camera1, Camera2 is never switched to Camera1 due to internal id assignments to each camera. When you closed OT and then reopened it or performed certain actions related to the camera, Camera1 would be recreated. This was due to how it would test for camera by iterating through a number sequence which was used to calculate the internal id and would create it automatically as it was testing for it.

I recall trying to fix it by changing the internal id of the remaining cameras when a camera was deleted, but was unsuccessful in resolving it. Will revisit the issue again.
