### ISSUE TITLE
Brush lag on vector layers.

### ISSUE THREAD

**Issue by ca3games** [opentoonz/opentoonz#2813]
OS : Lubuntu 19.10
Graphics Tablet : Parblo A609
GPU : Geforce 210

There's a lag of several seconds whenever I try to do any drawing.

**Comment by manongjohn** [comment]
Have you tried creating a 3D high performence profile for OpenToonz in your Geforce 210 settings? That can sometimes help with the lag because OT doesn't always trigger GPU usage.

**Comment by artisteacher** [comment]
Is there always lag on vector layers - even in a new scene? 

This may not be the problem, but using a really sketchy style with vector levels or "painting in" a solid area with vector strokes, often causes lag due to too many control points. When working in that way, a Toonz raster level is probably a better option. With vector levels, it is best to fill in a closed outline with the fill tool and to work in a more precise way to avoid extra control points.

**Comment by RodneyBaker** [comment]
Will close this as likely(?) resolved and or abandoned.
It is Linux related so some specific optiomizations are likely recommended.

I'll attach this (generic) audio tip for reducing lag in general:

https://github.com/opentoonz/opentoonz/assets/2576432/783e91b8-4dde-4a81-b62e-887bbe503ebd

(Sorry, need to add imagery!)
