### ISSUE TITLE
"Enable Actual Pixel View on Scene Editing Mode" option...

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2822]
@shun-iwasawa 
Could you please describe what the aforementioned option does?
I'd like to add an entry for it in the manual, but I really have no clue... 🤔 

Thanks!

**Comment by RodneyBaker** [comment]
While waiting for a response, here's some related commentary from Shun in #1879.

**Comment by gab3d** [comment]
Thanks @Rodney I tried searching any reference but evidently I didn't do a good job on that.
Anyways I would appreciate a good phrase for describing it, as I still don't know if I can say exactly what the function does with detail and accuracy.

**Comment by artisteacher** [comment]
> Added: I'm not entirely sure what 'Scene Editing Mode' is...

I assume that 'scene editing mode' is when the XSheet/Timeline is active (instead of the level strip).

**Comment by shun-iwasawa** [comment]
As you already know, OpenToonz can handle images in "real scale" (i.e. with unit of inch, cm or mm).
That is to say you can put images and composite them just like the camera table in the real world. 
To achieve that, dpi of each level is taken into account and used for the pixel-inch conversion.

There may come up with a one question - when you show images and zoom up/down in the viewer, 
how can OT define the magnification percentage?

If you are showing images in the pixel-based environment, it is obvious that when one image pixel is shown in one monitor pixel OT can tell it is 100%.
However, in the real-scale-based environment OT cannot define any meaningful value because AFAIK there is no way to know the physical dpi of the current monitor.

So, as a resonable solution, currently OT defines the magnification percentage based on the current camera dpi, i.e. when the camera frame with 800 x 600 pixels is shown as the same pixel size in the monitor, OT defines it is 100%.

This solution causes another problem.
When putting the raster / toonz raster levels in the scene with different dpi from the current camera, it causes twitchy artifact due to the quick resampling algorithm.
In order to eliminate the artifact, you need to show in specific magnification factors (100%, 50%, 33%, 25%, 200%, 300%, 400%...) based on the level dpi, instead of the camera dpi.

The preference option "Enable Actual Pixel View on Scen Editing Mode" will take care such problem.
If you set the option to ON, the magnification percentage of the viewer will be calcurated based on the current level's dpi. You can use Zoom In / Out command to set the magnification percentage to the good values so that the viewer displays the current level without the artifacts.

----------

As you may noticed, this option works in not all situations.
Here are some exceptions:

- **Vector levels** have no dpi. This option doesn't work when the current level is the vector level.
- **It works only when the Scene Editing Mode.** As @artisteacher pointed, the scene editing mode is when a frame in the Xsheet/Timeline is selected. In the scene editing mode all the visible levels in the scene are displayed in the viewer. OTOH, the "Level Editing Mode" is when a frame in the Level Strip is selected. In the level editing mode only the current level will be displayed in the viewer and the  magnification percentage of the viewer will be always based on the current level's dpi regardless of the option.
- **In the Pixel unit environment** all levels will be put in the same dpi as the current camera.

Hope this helps!

**Comment by gab3d** [comment]
@shun-iwasawa 
Thank you for the thorough explanation, with that I have enough. 👍

**Comment by RodneyBaker** [comment]
Recommend closing.
