### ISSUE TITLE
Bug while drawing.

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#2840]
### Issue Summary
A glitch occurs during drawing.
This glitch appeared not long ago, after I tested another version.
https://ci.appveyor.com/api/buildjobs/eie8rp5ypv9kq0g3/artifacts/toonz%2Fx64%2FOpenToonz.zip

### Screenshot or Video Reference

![image](https://user-images.githubusercontent.com/25137502/66980832-b7381500-f0ba-11e9-99e3-980b2daf6c37.png)
![image](https://user-images.githubusercontent.com/25137502/66980847-bef7b980-f0ba-11e9-9084-fe1a9dab4fc3.png)

### System Information
* **OpenToonz Version  - nightly build 
* **Operating System - Windows 10
* **CPU - i7 - 6700hq
* **Memory - 16 
* **Graphics Card - GTX 970M

**Comment by Agnyy** [comment]
https://youtu.be/xtV-maqAR7A 

Video

**Comment by manongjohn** [comment]
Can you please explain the glitch? You are doing so much so quickly in the video that I'm not sure what I am supposed to be seeing.

I do notice in the video that you appear to be in full screen mode and your docked viewer is black or rather somehow displaced?

**Comment by Agnyy** [comment]
When I start drawing, a glitch occurs immediately and it spreads to several rooms. And the whole OT starts to fail.

**Comment by manongjohn** [comment]
Sorry, still not sure what the glitch actually is, though I do see your viewer is in the wrong place.  Whatever you are experiencing might be related to the fact that your viewer seems to be messed up, but not sure what could be causing that.  Only room that doesn't appear messed up was the Cleanup room?

Have you tried resetting all rooms? Can you do a clean install to see if it fixes it?

We'd need to know which nightly it started in to see what might have caused that.

**Comment by Agnyy** [comment]
It started after installing this version - https://ci.appveyor.com/api/buildjobs/eie8rp5ypv9kq0g3/artifacts/toonz%2Fx64%2FOpenToonz.zip

I even completely reinstalled the program, but that too helped. So once again I recorded the video how it works. -  https://youtu.be/Ct1x_gs_ydo

**Comment by Agnyy** [comment]
I did not enter the program for a very long time, so this glitch was detected only not long ago. And even a complete reinstallation of the program did not solve the problem.

**Comment by manongjohn** [comment]
The .zip file you give as an example is directly from AppVeyor so it's from a PR. Which PR did you get this from? 

You should install a nightly from here https://github.com/opentoonz/opentoonz_nightly/releases and see if the problem continues.

**Comment by manongjohn** [comment]
It looks like you are using the artifact from the Curve Animation PR. We don't open issues against unmerged PRs. You should add a comment in the PR if you found an issue with the artifact.

I will close this unless you can show it is happening on a nightly.

If I had to guess, your stuff folder may be too outdated to be able to test that PR since the artifact doesn't have a testable stuff folder included. I cannot force the PR to rebuild it because of the conflicts that need to be resolved.

Since you haven't used OT in a while, I suggest doing this:
1) Uninstall OpenToonz completely and also remove your stuff folder (back it up first in case you need something from it)
2) Download and install official 1.3 release
3) Verify no problems. 
4) Download and install the latest nightly from the page link I provided
5) Check to see if you have the problem still.
6) If there are no problems then try testing the artifact again. If there is an issue with the artifact, put a comment in the PR.

**Comment by RodneyBaker** [comment]
@Agnyy The appveyor build likely does not include the Full Screen fix from the other PR that addresses that issue.  When testing the appveyor builds for something such as the PR with Curve Animation the timing of the build is important and a rebuild might resolve the issue. 

If I recall correctly the Curve Animation PR was triggered to rebuild recently but it may not have been after the Full Screen fix was allowed to settle in.

Also (importantly) and this may be the primary issue in your case...
It is recommended that you use the appveyor builds (zip downloads) as portables.
You *can* replace your root stuff directory also however.
The problem you are experiencing suggests to me that you are using your old stuff directory and NOT the new one provided by the appveyor build.  As such it is even more likely that you would be experiencing problems.

How to correct/test?
Rename your stuff directory at C:\Opentoonz Stuff
(I recommend naming it "Opentoonz Stuff (20191917)" so that you know the date you archived the data inside that directory)
Then copy the Opentoonz stuff directory from the downloaded zip file (this is from the appveyor build) so that it is now your new new stuff directory at C:\Opentoonz Stuff.

The previous will allow you to run Opentoonz using the updated data.
BUT...
Disclaimer:  Any other Opentoonz installation will now use that data from the stuff directory and it is not ideal to use testing data in this way.  The preferred approach would be to make that appveyor build/download a portable so that it can work independently and isolated from the C:\Opentoonz Stuff directory.

To do this after downloading an appveyor artifact/test build:
1) Unzip the Opentoonz.zip file and note if there is an Opentoonz Stuff directory already there.
If not there then the build was created prior to a recent update that packages the stuff directory into the build.
2) Rename the Opentoonz Stuff directory "portablestuff".
3) Drag/Drop the portablestuff directory into the Opentoonz directory that is in the same folder as the one just renamed.
4) Enter the Opentoonz directory and run Opentoonz.exe
Your (appveyor) test build should now run using the portablestuff directory to store data.

This process is actually a lot easier than it seems and it takes longer to type up the directions that to perform it.

I do think that if you are not using the Curve Animation build as a portable it is a very likely candidate for the issue you are experiencing.

An alternative to the above (that of setting up your own portable copy) is to get a copy that is set up from someone else.  It will consist of a zip file of about 40MB.

**Comment by Agnyy** [comment]
I tried many different versions, and why that such a glitch appeared even in very old versions. This has never happened before.

![image](https://user-images.githubusercontent.com/25137502/67047341-d24a6980-f13a-11e9-811f-aae65fc8acd6.png)

**Comment by Agnyy** [comment]
Maybe this is somehow connected with Windows?

**Comment by manongjohn** [comment]
Update your display drivers?

**Comment by Agnyy** [comment]
Hello! I could not answer because I was very busy. I reinstalled everything and the video driver too, but the problem remained.

**Comment by martynk666** [comment]
I have same problem and not sure what to do. It looks like bug with graphic card? Resolution of all controls get's f*** up. I'm trying to reinstall my drivers now. (I'm using Open Toonz 1.4 version, freshly installed)

**Comment by manongjohn** [comment]
This has been resolved a few different ways. What graphics card(s) do you have?
