### ISSUE TITLE
(Discussion) How to preserve Vector lines thickness?

### ISSUE THREAD

**Issue by eduraf1968** [opentoonz/opentoonz#2841]
Given the example below, I am trying to maintain Vector line thickness when using the Animate tool to zoom in.
I am using Camera 1 "scale" option to zoom in on a subject, but as the Camera zooms in, the (vector) lines become thicker and thicker like in the example I have attached.
Is there a way / workaround  in OT to preserve line thickness when zooming in and out ?

https://drive.google.com/file/d/11knU0VItbRxP-Rnph9gwHOJrjXiOmTvK/view?usp=sharing

**Comment by gab3d** [comment]
Certainly it'd be great to have such an option, either through an option in the Scene Settings dialog, or through an effect.
To my knowledge there isn't currently an automatic way to do this.

Of course, you can globally increase/decrease the thickness of any stroke using the Select tool. But that doesn't allow for a visible progressive zooming.

![imagen](https://user-images.githubusercontent.com/18104091/67104411-44539a80-f19d-11e9-8996-40b5f2463cb7.png)

Also beware that once you've decreased the thickness to the point the thinnest parts of a stroke have gone to zero, then when you increase it back the original relation between the different thicknesses will be lost.

![imagen](https://user-images.githubusercontent.com/18104091/67104670-be841f00-f19d-11e9-8f09-35071e80ff1b.png)

![imagen](https://user-images.githubusercontent.com/18104091/67104729-d9569380-f19d-11e9-8b7a-77114348bc06.png)

**Comment by eduraf1968** [comment]
I have read that there is a "Preserve thickness" option when using the "Select icon", but don't know if that is available only when selecting an object (not when zooming)...

**Comment by gab3d** [comment]
Yes, indeed, sorry! I was away from my computer and didn't recall that option. 🙈 

You can use that when scaling a selection, but as you mention, that still leaves you without a solution when doing close-up planes by zooming or dollying the camera.

**Comment by RodneyBaker** [comment]
Closing as a discussion also in two additional topics in the Opentoonz forum.
Feel free to continue the discussion here as well.

**Comment by eduraf1968** [comment]
May I ask why you closed this thread Rodney ?

**Comment by RodneyBaker** [comment]
Certainly.
There are several reasons.

Github isn't the designated place for asking general Opentoonz questions.  These questions are usually discussed in the Opentoonz forum (Google Groups).  

There are two other topics in the Opentoonz forum asking the same question.
I believe you are the author of those other topics as well?

Discussions not suited for github are closed and referred to the Opentoonz Forum but can continue here if there is interest.  

Often a github topic can be reworded so that it is not just a general discussion or troubleshooting topic better suited to the OT Forum.
Bugs with repeatable steps to reproduce are perfect topics to post here on github.
