### ISSUE TITLE
[Proposal] Update new level icons

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2846]
I'm thinking that New Level buttons icons could be more clear than what they actually are.
I mean, currently they are different from one another, yes, but there's nothing in its content or shape that gives the user a good clue about which type of level each one will create.

![imagen](https://user-images.githubusercontent.com/18104091/67148242-d928c780-f273-11e9-803b-12c2789c543a.png)

Wouldn't they be more distinctive if they just included the respective letter for that kind of level?
TV  /  TR  /  R
or
V  /  TR  /  R

**Comment by beeheemooth** [comment]
Absolutely agree. I once set up the panel and accidentally mixed up the shortcuts. The current icons are not entirely clear. I agree that the TV / TR / R option would be better

**Comment by RodneyBaker** [comment]
Agree, when starting to read your posting my mind raced to using R, TR and V.  
Note that I would place those in that icon order from left to right however.

I confess that I don't know what those icons mean instinctively so I remember them more positionally.

Rationale for left to right positioning:
(Middle position) Toonz Raster TR is the bridge (and default) between raster and vector so it sits nicely between the two.
A raster image that is convert/cleaned up for use in Opentoonz is easily set to copy/paste upward or downward into raster or vector.  

(Left) Standard raster more often than not must be converted in some way in order to be useful in Opentoonz.  It is still very powerful and it is the default level type of any user that brings external images into Opentoonz.  If looking at a pipeline flow from left to right standard raster would be at the far left because we cannot simply copy paste into the other two level types... standard raster levels must be brought into the system (as Toonz raster or vector).

(Right) Vector is often considered the more modern and advanced image type and while it can easily move to toonz raster or standard raster those level types cannot as easily convert to vector.  

_Aside:   One thing that is often confusing... even to me after years... is seeing the TLV designation on Toonz raster images.  My brain immediately sees the V and things vector!  Of course I do an immediate correction because I know what they really are.  There isn't much we can do about that except perhaps add something to the UI that also clarifies that more when using OT's browser.  Things are complicated a little more by vector levels having the extension PLI... without any V in the designation._  

If the icons were colored blue, green and yellowish... that's easily convey which icon is which and teach users what those colors mean in the xsheet/timeline too.

**Comment by konero** [comment]
> @RodneyBaker If the icons were colored blue, green and yellowish...

I think I posted that before.

![tnzIcoSetB](https://user-images.githubusercontent.com/19820721/67150619-b3baae80-f2b1-11e9-8ebb-daa040507e86.png)

**Comment by gab3d** [comment]
I consider color to be a good clue, nevertheless I'd like it not to be the only clue about the level type.

**Comment by artisteacher** [comment]
The original thought behind the icons is that vector resize without loss of quality & raster levels are pixel based. That said, they could definitely be more clear. Color coding would be fantastic - the problem is that the light theme has different colors. To deal with the different theme colors, the color should really be added in the style sheet. I believe @konero shared some info about doing so, but no one has seemed interested in getting that to work so far. 

Just using the first letter of each name might be more clear in English. However in other languages, the words for raster and vector may start with different letters.  Are there specific qualities that could be visualized for each level type that would be more understandable?

**Comment by DarrenTAnims** [comment]
I really think the buttons should change. Like everyone else, the images don't mean anything to me. However, I should say that we can't really use TV / TR / R. They're only suitable for English speaking users. Ideally, the images would be clearer, somehow. And using the same colours as the xsheet would be ideal.

**Comment by RodneyBaker** [comment]
An interim fix might be to leave the icons as is and add the color.
Then as someone devises better icons they can be updated.

**Comment by gab3d** [comment]
@DarrenTAnims 
> I should say that we can't really use TV / TR / R. They're only suitable for English speaking users.

I myself am a Spanish speaking user, but even though I know what you are saying is correct, I would still find the letters so much easier to memorize that it'd be an improvement over the current icons. 😉

**Comment by artisteacher** [comment]
Maybe something simple like this for now? The colors are between the light & dark themes.
<img width="138" alt="Screen Shot 2019-10-21 at 4 28 40 PM" src="https://user-images.githubusercontent.com/21159116/67240657-e84c7880-f41f-11e9-88d4-041054ca5f22.png">

**Comment by gab3d** [comment]
I prefer that, to trying to decipher the message that the current icons imply.
At least that way, "the color is the message", and is related to the color of each type of level.

**Comment by artisteacher** [comment]
The down side to hard-coding the color as part of the image, is that if anyone changes the level colors in a theme, the icons will no longer correspond correctly. So at some point, colors really do need to move to the style sheet. I would do it myself, if I knew enough C++/QSS to do so. 

It might be less imperative coding the colors in the QSS if there was also another visual cue. However it's a pretty small space to express some complex information. Part of the problem is that there is a lot of overlap between what each level can do. What visual indicator clearly says raster vs toonz raster? It is easier and also probably a cleaner look to stick with just the color cue.

**Comment by beeheemooth** [comment]
<img width="86" alt="2019-10-22_002949" src="https://user-images.githubusercontent.com/25724133/67247208-51a4a980-f469-11e9-82fe-ba4e6a04dbb0.png">
I love minimalism and concreteness

**Comment by gab3d** [comment]
video tape recorder 😺 

> I love minimalism and concreteness

the minimalism part is great, but the problem with the **T** is that the possible meaning for that letter is **Toonz**, which applies both to Toonz Vector and Toonz Raster level types.
I'm afraid the same would happen with the letter **R** that is shared in Toonz Raster and Raster level types.

**Comment by artisteacher** [comment]
The minimalism is great - but I do really think we should avoid letters when possible due to different languages and interpretations.

**Comment by RodneyBaker** [comment]
Thought to try a color test to see how the icons might look in primary colors.
I was a bit much so I tried the same in grayscale.

![primarycolortest](https://user-images.githubusercontent.com/2576432/67507010-bc193d80-f653-11e9-8012-70156248affe.png)

**Comment by gab3d** [comment]
Personally, I think if the icons have colored backgrounds, they should be the same ones used in the Xsheet for the cells of each level type.
That's the way users could easily make the connection between each color and what it means; on the other hand, if we change those to be different (although maintaining their main hues), we will be weakening the clue the color should provide the user.

**Comment by RodneyBaker** [comment]
I agree @gab3d 
My use of bright yellow was something of a way of winking at the current color of vector levels that is often referred to as yellow.  I usually refer to it when assisting users as 'yellowish'.  ;)

The colors in my examples are notional.  
They should match whatever color the level types are in the cells..

**Comment by DarrenTAnims** [comment]
I thought I'd have a go at the icons too. The normal OT colours are quite dull, so adding colour possibly makes them stand out too much. What d'you all think?

![New level icons before](https://user-images.githubusercontent.com/28575907/67518195-2c4bb180-f69c-11e9-8bab-97308c927285.png)
![New level icons after](https://user-images.githubusercontent.com/28575907/67518196-2c4bb180-f69c-11e9-981e-183986859f2e.png)

**Comment by RodneyBaker** [comment]
I like it @DarrenTAnims!  A little splash of color but in no way distracting. 
I've gotten use to ignoring those icons largely because they are all the same basic dull gray which to my subconscious mind signals 'inactive'.

**Comment by gab3d** [comment]
This is my personal opinion, but I'm not sure about the icons drawings are meaning something recognizable at all (of course the author would assign to each a meaning, but still).

Knowing it's not easy to come up, in such a limited space, with something that identifies each level type in an undoubtedly manner, perhaps a good route to explore could be that each button had basically the same icon (this time representing a **New Level**) and that the color alone be the element pointing to the different level types to create.
Dunno, just an idea. 🤔

**Comment by RodneyBaker** [comment]
@gab3d Is that not the approach @artisteacher presented above?

Here again for our viewing pleasure:
https://user-images.githubusercontent.com/21159116/67240657-e84c7880-f41f-11e9-88d4-041054ca5f22.png

**Comment by gab3d** [comment]
@RodneyBaker yep, I know. 
I'm not saying that this particular design was not suitable, just that under the same general idea several other icon designs could be also possible (for that very reason I included the word "explore" when saying that, in my last message).

**Comment by RodneyBaker** [comment]
At this point I think we've determined that:

1.  Letters on the icons won't be ideal.
2.  Adding color would help.
3. Current icons don't quite convey their intended meaning.

As this is your topic feel free to guide the exploration.  :)

**Comment by artisteacher** [comment]
@DarrenTAnims I like that direction, though the level of contrast makes the level background colors blend in too much with the background.

As far as exploring options for the icons focused on color alone, keep in mind that other icons might need a redesign too. Ie. "load level" and "merge levels" are based on the same "level" icon shape.

**Comment by konero** [comment]
Here's mine fused with @DarrenTAnims style I guess. Couldn't think of what represents Toonz Raster, so I went with a palette to indicate palette support.

![image](https://user-images.githubusercontent.com/19820721/67586942-b7838080-f74a-11e9-8517-000e51d9fafb.png)

**Comment by artisteacher** [comment]
I wonder if the palette might be more appropriate for the raster level - since they are best for a painterly approach/look?

**Comment by RodneyBaker** [comment]
`I wonder if the palette might be more appropriate for the raster level - since they are best for a painterly approach/look?`

When toonz raster finally get the remainder of the options for mypaint brushes (erasers and blurs) then we might be tempted to change it back.  ;)

**Comment by gab3d** [comment]
@konero 
I really like the icons, but to me the question remains:
Does a painter's palette, a checkerboard and a curved line with three dots convey the groupal idea of the different level types? Honestly, to me the answer is no.

Why a checkerboard would translate in the mind of an uninstructed person to make him/her think of a raster level or even an image, either by itself or by contraposition to the others?
Why a painter's palette would translate to a toonz raster level, either by itself or by contraposition to the others?
Of the three, the curved line with the dots is the one that by itself could more easily be associated with a vector curve, but again, if the remainder two icons don't have drawings that make the user differentiate them "from that curve" i.e. by making the same curve look pixelated and without the dots, then the curve itself could be associated with another thing, like a geometric shape, a tool that lets edit vertex points or something else.

This is an example of a super simple way to indicate the difference between something vectorial or raster:
![example](https://user-images.githubusercontent.com/18104091/67598536-1e516b80-f744-11e9-8f97-e949038596ac.png)

In this case vector is represented by a well defined line or curve, whilst the raster could be the same shape, but "pixelated" to indicate its raster nature.
...of course this way of resolving it still leaves unresolved the issue of differentiating between "raster" and "toonz raster" level types which, since they are both raster they should also show the same pixelated shape, but with some accessory graphic element in one of them, to indicate that it is not the same nature as the other one.

**Comment by konero** [comment]
> @gab3d Why a checkerboard would translate in the mind of an uninstructed person to make him/her think of a raster level or even an image, either by itself or by contraposition to the others?

It's used by Affinity. Besides, raster is a dot matrix grid (pixel based).

![image](https://user-images.githubusercontent.com/19820721/67609522-241b7100-f785-11e9-8518-278a62f5e1be.png)


> Why a painter's palette would translate to a toonz raster level, either by itself or by contraposition to the others?

Toonz Raster supports color models and trace lines for InknPaint. You can modify colors during post-production and it supports a myriad of FX that can manipulate the palette colors. I couldn't think of what else separates them other than one has palette support and one doesn't.

Personally we could remove the palette icon and simply use Toonz Raster as the default level type. Then the small icons (the vertices, the matrix grid) will easily suggest they are different level types.

![image](https://user-images.githubusercontent.com/19820721/67610215-21bb1600-f789-11e9-9f46-19498c706ad4.png)

I'm fine with anything.

**Comment by gab3d** [comment]
@konero 

> It's used by Affinity. Besides, raster is a dot matrix grid

I'm only saying that when I see this I think: "checkerboard", "transparent layer", "chess"... not "raster image", not "image" either.

> Toonz Raster supports color models and trace lines for InknPaint. 

But that is also the case of vector levels, so it does not uniquely identifies that type of level. If we use a palette icon for toonz raster, then the palette should also be present in the icon for toonz vector levels... 🤔 

It's clear that there will always be a characteristic that will be shared between two of the level types:
- being "raster".
- being "palette linked".
So I'd see it logical to repeat the graphic representing one of these in two of the three icons, but with some element that allows for differentiation between them.

**Comment by RodneyBaker** [comment]
Just a thought as I've been rummaging through the various enhancement/feature requests:

As icons can easily be replaced locally this (and other similar localizations) might be best served by a customization package outside of the normal core release.  Then as developers see fit they can include those customizations deemed optimal and universal in the core release.

In particular I'm talking about customization and processes that can be accomplished by non-programmers... mere mortals so to speak.  An example of this might be files for use by new users (scenes, specialized documentation, brush packs, etc.)  See also:  [Issues/Reports tagged 'Resource'](https://github.com/opentoonz/opentoonz/issues?q=pack+label%3AResource)

A related question might be how to best proceed in a way that allows users to select their own resources in a meaningful way and store personal but customized preferences so they don't get overwritten easily via subsequent updates to the core Opentoonz release.

**Comment by artisteacher** [comment]
It's a good idea, since toonz raster is now the default, to let the generic level icon represent it without any other additions. Vector levels have enough unique capabilities - they are easiest to differentiate visually. The vertices work well to hint at vector levels.  So the question becomes, despite overlapping areas of capability, are there any features that do clearly stand out as being associated with raster levels over toonz raster levels?

The problem with focusing on the pixel nature of raster levels, is that toonz rasters are also pixel based. The icon should really show what makes raster levels themselves different from the default toonz raster. The direct and smooth blending of colors is what I strongly associate with standard raster levels. 

How likely is it that the mypaint blending brushes will be enabled for toonz raster levels? If that is truly on the drawing board, what will continue to uniquely distinguish standard raster from toonz raster levels?

**Comment by RodneyBaker** [comment]
The uniqueness of the toonz raster format amongst other raster formats is how it can be used to distinguish between lines and areas.  This is considerably different than standard raster.

In my icons I attempted to use raster squares without borders to represent standard raster but borders around areas for toonz raster.  This may seem a trivial distinction but toonz raster ability to paint on/out lines, areas or both lines and areas is its main claim to fame... powerful stuff.  This is also the main reasons why standard raster images both drawn in raster levels inside Opentoonz and imported into Opentoonz must be "cleaned up" or converted to TLV/toonz raster format before gaining that capability. 

As for how likely toonz raster levels are to gain full support of blending, blurring and erasing with mypaint brushes... that is hard to say.   No one was expecting mypaint brushes to work with toonz raster at all and then one day Shun announced it as a feature.  The difficulties in adding the erasure and blending/blurring is surely considerable because those functions have to be ported over to the specialized toonz raster format which was not designed for such processing. I expect to see something unexpected from Shun every day.  I think he likes to keep us guessing.  ;)

**Comment by konero** [comment]
Maybe the mountain picture used to represent raster file types? I think Darren used it in his example although it's difficult to see.

![image](https://user-images.githubusercontent.com/19820721/67630135-8e620d80-f87a-11e9-9655-d94e4b2ac516.png)

**Comment by gab3d** [comment]
I analyse the graphics in this last example and the messages they send:
- the three level types has an ACME punctured blank sheet of paper, reminiscent of a hand drawn animation image (at least to those who know what an ACME puncture is).
- in addition to it, one of them has an icon of a scenery, reminiscent of an image.
- in addition to it, one of them has shape of an arc with three dots, reminiscent of a vector curve.

**Comment by manongjohn** [comment]
For whatever my opinion is worth...

I like the black&white versions. They are easier to read. Plus, all our icons are not colored unless they are in an ON state.

**Comment by gab3d** [comment]
I agree that it'd be "out of style" to have colored icons for these commands, if all other icons in OT are B&W.

**Comment by konero** [comment]
I had to check the size of the toolbar (18x18), mine were a bit bigger so I had to constrain them, here is what they now look like and the assets to download. Feel free to edit them etc.

![image](https://user-images.githubusercontent.com/19820721/67638671-1da10c80-f8df-11e9-8630-769b9bb77570.png)

**Download:** [TzIcoLvl.zip](https://github.com/opentoonz/opentoonz/files/3776187/TzIcoLvl.zip)

**Comment by RodneyBaker** [comment]
At the risk of starting the discussion anew...

Did we arrive at any consensus here?
Should we table investigating 'New Level' button icons until 2020 development cycle?

On the plus side we do now have the shortcut key for creating empty drawings (Alt + D).
That works great as long as the user is okay with creating the currently assigned default level type.

**Comment by RodneyBaker** [comment]
Tagging as 'Hiatus' as there does not appear to be sufficient consensus at this time in moving forward especially given that the current icons work well.
Adding to the 2020 UI scrub project so we don't forget to consider the proposal moving into v1.5

**Comment by adamearle** [comment]
what about just 
V ector 
R aster
P aint

That pretty much what they do

**Comment by artisteacher** [comment]
Letters are not universal enough - the equivalent words in other languages may not share the same first letter. Also, changing the terminology from Toonz raster to paint seems confusing.

**Comment by gab3d** [comment]
I agree that letters are not the best answer to this problem.
I agree also that calling "Paint levels" to "Raster" or "Toonz Raster" levels (I'm not really sure what has been proposed) won't improve the situation either.

I could agree on a departure from Toonz references for things inside OT, though. But, having said that, I don't think it in terms of solving this issue, but in a more general manner. I think it's unnecessarily confusing for users having this strange Toonz words here and there (they should not know what Toonz really is/was, besides being a part of the OpenToonz name...
But, of course that would be a thing for discussing into another issue.

**Comment by RodneyBaker** [comment]
Closing for purpose of general housekeeping.
Let's review icons, to include level icons in light of recent icon updates (for v1.5) and the 2022 development cycle.
