### ISSUE TITLE
Merge levels disabled with multiple levels in a column

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2853]
### Issue Summary

"Merge Levels" and "Merge TLV Levels" are both kept disabled if trying to merge two columns where one of the columns has multiple levels.
### Steps to Reproduce

1. Create a vector level with 20 frames - keep the drawings empty
2. Add two more vector levels to the next column (to the right in the Xsheet) so that one level comes after the other level in the same column
3. Click and drag across the column headers to select them
4. Try to merge through the menu - the commands are disabled
### Expected Results

I expected to be able to merge.
### Actual Results

The merge commands are disabled.  If the levels are split into multiple columns they do merge as expected.
### System Information
* **OpenToonz Version**: latest nightly 
* **Operating System**: macOS 10.14.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by melieconiek** [comment]
I was just looking at this the other day. I believe it checks specifically for this case. Even if you were able to execute the command, the `Merge Levels` command at least, also has a check and error message for this case. 

> "It is not possible to perform a merging involving more than one level per column."

I'm not sure what the reason for this check it though.

**Comment by artisteacher** [comment]
Maybe it is in case the other levels are different types?

**Comment by melieconiek** [comment]
I'm curious--I will take a look later today. It may well be a catch-all for that case--but it might cause an issue with how the levels are merged.

**Comment by melieconiek** [comment]
Skimming, it looks like all of these commands can only handle two levels at a time. They're done a two columns at a time which is why moving each level into it's own column makes it work. This is related to what causes the nested group issue with merging vector levels, too.

If I'm understanding this correctly, the way these commands work would need to be redone in order to fix this. Sorry that isn't more helpful--was just looking at this for the merge without groups PR and thought I might be able to give some insight.

**Comment by RodneyBaker** [comment]
The golden rule of merging appears to be:
`It is not possible to merge columns if more than one level is exposed in any of them.`

This from the Tip in the Opentoonz documentation:  
 https://opentoonz.readthedocs.io/en/latest/editing_animation_levels.html#merging-animation-levels

An interesting workaround to the restriction is what I call the 'one level to rule them all' approach where if we use only one level for our drawings but then expose the frames both vertically and horizontally in the xsheet we can merge in ways that otherwise we could not.

This would suggest the larger 'fix' to merging columns containing multiple levels of both same and different type.  We simply have to create a interim common level first and then copy/convert all the other layers/frames into that working level.  Obviously someone would have to program it.

We can test a working example of this process now.
- Create a level of at least three frames containing content
- Expose the frames both horizontally over columns as well as vertically over frames.
- Select columns and merge
Note how the exposures on frame 1 all merged into one while the other frames remained the same.

To resolve the problem of different types of levels being merged we just have to copy/convert all frames from their original level into the working level for the purpose of merger.

**Comment by RodneyBaker** [comment]
Closing as outlining a standard process documented as such in the Opentoonz (and Toonz) manuals.
Perhaps this can be enhanced in the future to resolve the current restriction.

**Comment by RodneyBaker** [comment]
Somewhat related:
Something to also keep in mind (and something @melieconiek pointed out to me in an earlier discussion is that Merge can also be prohibited (i.e. option grayed out) if there is nothing present in the target level.  For instance there must be at least one spline/brushstroke in the frame for vector columns to be merged.

**Comment by artisteacher** [comment]
@melieconiek - thanks for looking!

I understand that according to the manual, this is the intended behavior. I don't think that is what is expected, based on the command name.
