### ISSUE TITLE
The best export quality

### ISSUE THREAD

**Issue by zallo88** [opentoonz/opentoonz#2865]
Hi,
i animated a character drawn with photoshop (PSD), using toonz and the plastic tool and after the export I realized that the quality of the video (mp4) or of the images (if I export in jpeg or tga) is very different and more poor compared to the toonz preview (both colors and sharpness). Do you know the best way to export a scene without losing the quality of the drawings?

![TOONZSCREEN](https://user-images.githubusercontent.com/57186035/67872737-ae235b00-fb32-11e9-8344-0f306dbc44d8.jpg)
![MP4](https://user-images.githubusercontent.com/57186035/67872739-ae235b00-fb32-11e9-9302-68b13fad3a2d.jpg)
![JPEGEXPORT](https://user-images.githubusercontent.com/57186035/67872742-aebbf180-fb32-11e9-993b-0e4ac2d3dd30.jpg)

### System Information
* **OpenToonz Version**: Last
* **Operating System**: macOS Sierra IMac
* **CPU**: 
* **Memory**: 8gb
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
There are a few output settings for rendering that help achieve specific quality related to amount of antialiasing or not having any at all.  It's been a little while since I looked at those but I think for those disiring the cleaner non-antialised look you might use the setting that allows for pixel to render to the 'nearest neighbor'.  Assuming that is your goal what that does is force the pixels to have a definitely cutoff of value and not blend between two (or more) colors.

Also, consider the image format you are rendering to as some will be more appropriate to achieving specific looks even if they are only used as interim images which will be compiled later into other formats.  The example I would use here is that of a format I rarerly use... BMP... which is a format that doesn't support alpha channel transparency.  As such it removes any output effect that would otherwise fact in alpha channels/transparency.    (Disclaimer here however:  I am not advocating use of BMP format for most cases... just using it as an example).

**Comment by zallo88** [comment]
> There are a few output settings for rendering that help achieve specific quality related to amount of antialiasing or not having any at all. It's been a little while since I looked at those but I think for those disiring the cleaner non-antialised look you might use the setting that allows for pixel to render to the 'nearest neighbor'. Assuming that is your goal what that does is force the pixels to have a definitely cutoff of value and not blend between two (or more) colors.
> 
> Also, consider the image format you are rendering to as some will be more appropriate to achieving specific looks even if they are only used as interim images which will be compiled later into other formats. The example I would use here is that of a format I rarerly use... BMP... which is a format that doesn't support alpha channel transparency. As such it removes any output effect that would otherwise fact in alpha channels/transparency. (Disclaimer here however: I am not advocating use of BMP format for most cases... just using it as an example).
> 
> In general I would stay clear of JPG format because of the compression most JPGs will be subjected to and the loss of data likely to occur in conversion. TGA is a good format but in most cases TIF would be better especially where higher bit counts are needed. TGA is 24bit but some of that is used for alpha channel even if that alpha channel isn't being used. TIF likewise but you have options for 32bit 48bit and 64bit output.
> 
> As Macs with retina etc. can by default display higher resolution that is also something to consider. People with lesser monitors might not be able to view the higher resolutions or even open the file without converting the image. I don't think you have much to be concerned with here as your final product is MP4.

Thanks Rodney, I've seen that exporting images in tif is much better. I will try to export all the frames in tif as a sequence of images and use another editing program to get a good mp4.

**Comment by RodneyBaker** [comment]
Good luck!
