### ISSUE TITLE
How OpenToonz kills uploaded files (video attached)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2870]
### Issue Summary

OpenToonz deletes uploaded files (bitmaps and gifs) without warning after saving if they have been modified. Also, along with them, auxiliary files are deleted regarding deleted images - xml with tracking data.

### Screenshot or Video Reference

![ezgif-1-46cce27093dc](https://user-images.githubusercontent.com/25724133/68554155-3953f900-042f-11ea-9242-2b1a7ba734bd.gif)

### Steps to Reproduce

1. Load one or more images (or gif) into the scene. They automatically fall into the "extras" folder. Watch the file in the folder.
2. Use the raster brush or eraser to make any changes to the image.
3. Save the scene.
4. The file from the "extras" folder will be deleted.

### System Information
* **OpenToonz Version**: latest
* **Operating System**: windows 8.1

**Comment by manongjohn** [comment]
Issue confirmed.  This is specific to gif images.  I checked bmp and jpg files and those saved without issue.

When saving certain file types, a temp file is normally created with the changes, the old file deleted and the temp file renamed.  In the case of gif files, the temp file is never created.  No error is thrown when using "Save All", but an error is thrown when using "Save Level". Problem is the original file is already lost by the time it gets to that message.

I noted if after you failed to save the gif, if you try to save the level again, it will save properly however any changes you made are lost even though you can still see them in OT.

**Comment by manongjohn** [comment]
Although I know what is causing this and can prevent file loss, I have a question.

Should levels loaded through ffmpeg (GIF, MP4, WEBM) be editable or should they be read-only like PSD files?

I say this because of a few reasons I found while testing the ability to update GIF files:
- When reading into OT, held frames are read in and created as duplicated frames.
- When writing the file back out through ffmpeg, the individual/duplicated frames are written out because of how it is read in. The frame rate information will be altered as a result, though it may not be noticeable under some scenarios.
- Adding new frames to the file may cause multiple duplicate frames to be created which will change what is exposed in the xsheet.

The Level strip normally doesn't allow you to add/create frames on GIF/MP4 based levels, yet there is a way to create it and probably should be blocked.  Drawing tools also allow you to modify these images, and I'm wondering if that should be blocked also.

I'm leaning towards making loaded GIF/MP4/WEBM files read only.  If it is decided we want to make it editable, I will submit a PR to only prevent the file loss, but I will not fix the issues cause by editing these file types.

**Comment by gab3d** [comment]
I think it is safer for the time being to load them as read only.

**Comment by shun-iwasawa** [comment]
Thank you @manongjohn for investigating this. I agree with you for making them read-only.

**Comment by beeheemooth** [comment]
Sorry, but...

2019-11-13 23:11:15 UTC
![ezgif-1-073aeb0b7645](https://user-images.githubusercontent.com/25724133/68849963-c28f5800-06db-11ea-8e18-872a49f576b0.gif)

2019-11-14 07:43:51 UTC
![ezgif-1-800153943d78](https://user-images.githubusercontent.com/25724133/68850015-de92f980-06db-11ea-936b-dcc58edfec42.gif)
