### ISSUE TITLE
[Discussion] Level Edit backgrounds

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2877]
Currently when you switch to Level Edit mode (click frame in Level Strip), the background for all levels goes gray but the Raster has a white bounding box, and Toonz Raster goes a has filled white box.

Is there a particular reason why they are like this? Do we want it to stay this way?  Should Raster show the filled white box or should Toonz Raster show only the white bounding box? 

As the Vector one just shows gray and Raster also going gray with just the bounding box, I would lean towards Toonz Raster only showing just a white bounding box so it's obvious you've switched to Level Edit mode.

I know this has been somewhat discussed before and we've all just been like "that's how it is and you just need to know the differences", but I think it should be changed to avoid the confusion this causes to new users.

Thoughts?

**Comment by hayoko** [comment]
I don't remember it being that way in Harlequin, are you suggesting the same thing as: #1061?

I would very much like the Toonz Raster levels to have the option of displaying no canvas color, I know tons of people that refuse to paint levels anymore on white canvases because of the eye-strain.

**Comment by artisteacher** [comment]
In case anyone is interested, this has also been discussed in #2327, #1694, and #889. Studio Ghibli requested the white background for Toonz Raster levels.

My students always find the background color change confusing when they are first using OT. While the grey backgrounds make it very clear that something has changed, it is very unclear what has changed. We do need a visual indicator that the viewer is in the "level editing mode" instead of the "scene editing mode", but it would be nice to have it a little more obvious and consistent.

Having a preference to control the background color for all of the levels in one or both modes could be helpful. In that case the mode might become less obvious so it might be necessary to have an additional indicator of the editing mode. What if the viewer itself had tabs or buttons in an obvious place? They could act as an indicator and also be an additional way to change between the two modes.

**Comment by manongjohn** [comment]
@hayoko Apparently yes.  Thanks for pointing me to that request, I didn't know it was there since I don't normally look at Closed issues. Another reason NOT to close Feature Requests.

My intention was to A) make it consistent to either show a box or a bounding box in both (we all know how I like consistency!) and B) Add Preference option to change the color if people really wanted a white box, but I'd want to apply that to both Raster and Toonz Raster levels.

So looking for some direction before I start making changes.

**Comment by beeheemooth** [comment]
Based on the OpenToonz logic, what we see in Level Strip is a picture on a transparent celluloid sheet separate from the background and other details, so in this case the background should be checkered, this is a texture that in all graphics programs means full transparency. (but, honestly, I hate checkers)

**Comment by manongjohn** [comment]
@artisteacher Thanks for identifying other reported issues regarding this. Just illustrates more why this needs to change.

The viewer's title bar does change when in Scene editing mode vs Level editing mode.  It is something that is easily overlooked as nothing really stands out.  Perhaps it can be made a bit more obvious. Currently it shows `Scene: xyz :: ...` and `Level: A.1 :: ...`.  Perhaps change it to be `[SCENE]: xyz :: ...` and `[LEVEL]: A.1 :: ...`?  It's in line with the Style Editor where it shows `[LEVEL] Palette` or `[CLEANUP] Palette`.

@beeheemooth The checkers would drive me crazy.

Since Studio Ghibli requested the white background, I'm proposing this:

1) Add filled white box to Raster Level to be consistent with Toonz Raster Level
2) Add Preferences -> Color -> Level Edit Raster BG Color.
   - This would drive the box color for Raster and Toonz Raster levels
   - Default color will be set to use the same Viewer BG Color default
3) Update Viewer's title bar to show `[SCENE]: ` and `[LEVEL]: ` to make mode obvious.

@shun-iwasawa  As this will impact Studio Ghibli's original request, somewhat, please ensure this is okay with them.  After upgrade, they'd need to change the color back to white, once, and should be fine going forward since it will be in preference settings.

**Comment by artisteacher** [comment]
Sounds good to me! Making the header scene/level info stand out more would be helpful. 

It's probably out of scope, but I'd also love to have a shortcut to more quickly switch in/out of level/scene edit modes.

**Comment by gab3d** [comment]
@manongjohn 
I think what we need, for consistency's sake, is to have a **Level Edit BG Color**, applicable to the Viewer background, only when in Level edit mode of any level type.
If anyone wants to put this to be White, then that's OK, but the important thing to preserve here is a way to know for sure when something in the drawing is transparent, and that's what the background color helps with... (a checkered BG option would be good to have also, perhaps enabling the checkered button in the Viewer when in Level mode?).

Then, for levels that have a defined size (i.e. toonz raster and raster types), it'd also be good to have a frame guide indicating its size.

***One detail regarding the current BG color of the Viewer is that it is also used for the Table color in Camstand View; I think that they should be decoupled, because when you change it that view type gets awkward .

**Comment by gab3d** [comment]
I've checked Toonz, and the color was always white while in Level Edit mode.
The BG color couldn't be changed either, as in OT.

**Comment by manongjohn** [comment]
@gab3d I'm good with that suggestion also. The `Level Editor BG Color` would be the entire area for all 3 level types, not just in the box. The Raster/Toonz Raster would have the bounding box so you know where you are allowed to draw.

I'll see about a checkered background option, but no promises. 🙂

I'll let others weigh in.

**Comment by shun-iwasawa** [comment]
@manongjohn 

> 1. Add filled white box to Raster Level to be consistent with Toonz Raster Level
> 1. Add Preferences -> Color -> Level Edit Raster BG Color.
>    - This would drive the box color for Raster and Toonz Raster levels
>    - Default color will be set to use the same Viewer BG Color default
> 1. Update Viewer's title bar to show [SCENE]: and [LEVEL]: to make mode obvious.
>
> @shun-iwasawa As this will impact Studio Ghibli's original request, somewhat, please ensure this is okay with them. After upgrade, they'd need to change the color back to white, once, and should be fine going forward since it will be in preference settings.

Thank you for the suggestion, it's totally fine with us to make the color adjustable. I can change the color back to white in our preferences.
Ghibli stuffs originally demanded to have white BG because it was the same as Toonz 4.6 Ink&Paint module. Other studios may need a color which is easier to the eyes.

**Comment by gab3d** [comment]
@manongjohn 
Hi John, I've just been able to test this a moment ago, and on Vector levels I expected to also be able to see the **Level Editor BG Color** behind the drawings, but it seems it isn't the case.
As I see it here, for Vector levels we still stand the same as in previous versions (with the standard "Table" color as background), was that a conscious decision? 🤔

**Comment by manongjohn** [comment]
Per the discussion in the merged PR, the change was made to only affected the Level Edit box of the raster and toonz raster levels.

It was left it open to future discussion if we wanted a box for Vector levels to behave similarly.

**Comment by gab3d** [comment]
That I understand, what I'm saying is not to add "the box" to vector levels (because they have no limits, of course). But I do think that vector levels should better also use that same color as its background color.

The convenience of that (vs using the Viewer BG color) is that the Viewer BG is the color used by the Table, so changing it to be white (the most common choice when editing a level) would ruin the UI color scheme, turning the Camstand View in an uncomfortable overly-contrasted view, that most people wouldn't want to use.  🤔
