### ISSUE TITLE
Note level malfunction when "Use Xsheet as Animation Sheet" option on.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2893]
When the "Use Xsheet as Animation Sheet" option is on, and you create a Note level. 
The first cell is automatically created, and you can double click on it to input text, but you can't create new cells in that column, while the aforementioned option remains active.

Considering that now "Use Xsheet as Animation Sheet" option is the default mode, I think this should be fixed before 1.4 release.

Thanks!!

**Comment by artisteacher** [comment]
On a somewhat related note, I'm not sure why we can't type in frame numbers to reveal unexposed drawings from a level when "Use Xsheet as Animation Sheet" is active. Is there any benefit?

**Comment by manongjohn** [comment]
Current work around is to extend the last note to where you need one (or extend 1 frame and drag the new one to position) and then you can type in it to create the new note.

I agree, it should be fixed, for note levels at least since there isn't another way to create it like you can when drawing on a blank frame.
