### ISSUE TITLE
Pasting with one button and Text Tool.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2899]
### Issue Summary

It may seem strange to you, but I don’t use Ctrl + V but the M key for pasting. I rarely use the Type Tool (or maybe I rarely write English words containing the letter M), but in the English keyboard layout when I press the letter M, not the letter "M" appears but "TCellData". Here I wanted to write "Notre Dame"

### Screenshot or Video Reference

![ezgif-1-f29869c626fc](https://user-images.githubusercontent.com/25724133/69465307-8027e400-0d89-11ea-9c5b-bbf0416a9823.gif)

### Steps to Reproduce

1.Assign the "M" button (or some other) to the "Paste Insert" operation

2.With the Type tool, write a word containing this letter, "TCellData" appears instead of "M" (or the letter that you assigned).

### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by RodneyBaker** [comment]
Perhaps a popup could query:

"Hi Beeheemooth.  Would you prefer to paste a letter here?"
"Press the same key again to paste the letter or number"
"Please select cancel if you wish to paste your last copied selection from the clipboard instead."

:)

**Comment by gab3d** [comment]
😄 
yes, arguably it's not a very common situation, nonetheless it's weird that the program inserts that code in the middle of a text, and certainly it should not happen.

**Comment by RodneyBaker** [comment]
The 'TcellData' response should likely be another separate report as an element of copy/pasting.
Opentoonz has it's own copy/paste buffers outside of the operating system and data doesn't translate across the buffers.  If it did however we might just see other data paste into the current selection.

It would be an interesting test but I imagine that if the last thing copied prior to using the shortcut key was a single letter M out of a compatible buffer (i.e. notelevel text) we would see the resulting paste deliver a letter 'M' instead of 'TcellData'.  As beeheemooth likely was copy/pasting xsheet data prior to this copy/pasting process the paste buffer is currently filled with that incompatible data which  is translated as 'TcellData'.

It would be ideal to address the underlying problem of copy/pasting rather than to come up with a superficial fix that just tests for presence of incompatible data.

What we see here is a deeper issue that starts with users ability to assign single letters and numbers as shortcut keys.  It is unlikely that users will want to abandon this workflow although that would resolve the problem.  Preventing the user from assigning single letters and numbers as shortcuts would also resolve the problem.

Other superficial solutions could be invoked such as ignoring all shortcut keys except those specifically allowed while in text mode in various locations in the application.

None of these quite get at the underlying issue of incompatible data entering the copy/paste buffer.
However, if this incompatibility were addressed directly there would still potentially be the issue of unwanted data from the clipboard/paste buffer being pasted into the location rather than the letter (or number) pressed on the keyboard.

A similar issue in other application occurred where they had a chat system and they had to escape all the various letters (basically turn off shortcut keys) while users were in the chat window.  This then allowed the user to type characters as they normally would if they hadn't opted to use single letters for shortcuts.

**Comment by manongjohn** [comment]
TCellData isn't really an issue. It is what happened to be in the clipboard buffer, probably from copying a cell in the xsheet.  TCellData is the text associated with what's in the buffer.

The issue is because as you are typing OT is trying to determine if you are pasting into the "text box" (it's not a true text box) by also checking OT shortcuts for Paste command, in your case 'M'.  Since it's matching your Paste shortcut it executes the paste command because that's what it thinks you are trying to do.  So if you are overriding the Ctrl-V with a single letter, then this will happen.  

This only happens with the paste command.

I will try and fix this to not check against OT shortcuts.

**Comment by RodneyBaker** [comment]
> I will try and fix this to not check against OT shortcuts.

@manongjohn I may be overly concerned here.

In your fix can you please not remove the ability to paste into the Type Tool via the normal Control + v shortcut.    It would be a shame to lose that feature/capability.
