### ISSUE TITLE
"Select + Copy" from PSD images or convert to Toonz Raster level?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2901]
@shun-iwasawa @manongjohn 
this is not a bug report, but a quick question and possibly an idea about a current limitation of OT.

While helping in migrating a project that some artists had previously started using Photoshop (where they had drawn several level frames as layers) we imported the PSD layers as frames into a single Xsheet column, so far so good, but then they tried to actually use that drawings to edit them and paint them. Naturally PSD is a read-only format, so I suggested copying and pasting or converting the whole level to Toonz Raster, to achieve it, but then found out neither of the two options are currently really possible.

1. As selecting in a read only drawing is disabled, we could not attempt to select and copy the PSD content to later paste it into a new TR level.

2. Converting that whole column into a TR level isn't available either, which could've been massively useful too. I've did manage to convert the drawings into a vector level and then from there to a TR level, but in the process the drawings were altered (as expected), so it wasn't a viable path either...

So the question being: Is there a real issue in converting read only PSD levels into Toonz Raster or standard Raster levels? or is it just an absent feature that could be added in a relatively easy way?

Thank you for listening!!

**Comment by manongjohn** [comment]
I can't speak much to the PSD files as I believe that may require libraries we do not have access to, but these questions now also applies to GIF/MP4/WEMB files because we made ffmpeg loaded levels Read-Only.  There are a number of operations which require the level to be editable and I question if that is really necessary for some of them.

- Copy command - all or partial image
- Hook Tool
- Are there others that should be considered?

As far as the hook tool goes, that information is part of level information so if we can't "edit" a level, then I can understand why the hook tool is impacted.  I don't believe the hook tool does anything with the image, itself, so I think if anything, operations that are part of a level but don't actually modify the image should still be able to be saved. 

Perhaps @shun-iwasawa can elaborate more on how the hook tool impacts the image and why hook tool should or shouldn't be allowed to save on a read-only level.

**Comment by manongjohn** [comment]
FYI, working on a change to allow Selection tool to allow only copying selections from PSD/GIF/MP4/WEBM files. Selection cutting/pasting/deforming/moving will be blocked.

**Comment by artisteacher** [comment]
For now, to get an editable copy of a read-only level, place an empty raster level to the left of the PSD/GIF/MP4 and use the "Merge Levels" command.
