### ISSUE TITLE
(Discussion) Autocreation modes

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#2905]
Currently the preferences option `Drawing > Autocreation` has been changed to `Use Xsheet as Animation Sheet` by default.
There are users feeling inconvenient with it, especially that a new drawing is unexpectedly created (with suffixed number) when renumbering the cell:
https://groups.google.com/forum/#!msg/opentoonz_en/M3W27jxGvj4/cbRtLPkfAgAJ

I'm concern about bigger confusion when the next version will be released. 
IMO I'd like to modify the option more ideal, or at least to revert the default to `Enabled` .

Please let me know your thought. Don't you feel any inconvenience with the current option of `Use Xsheet as Animation Sheet` ?

I discussed with an animator in our studio about an ideal numbering method and conceived of the following:

```
When creating a new drawing in some vacant cell,
search the previous cells in the current column and take the maximum drawing number.
The new drawing will be with the number of (maximum + 1).
The following frames will be automatically renumbered with incremented numbers as needed.
(i.e. the drawing will be inserted keeping ascending order in the column)
```

If time permits, I'll try to introduce the above as an alternative behavior of `Autocreation = Enabled` when `Sync Level Strip Drawing Number Changes with the Xsheet = ON` .

**Comment by beeheemooth** [comment]
I remember the time when there was "Enabled" mode. 80% of questions from users were "how to create a new frame on Xsheet?". There was no timeline then, and users could easily get used to the idea that Xsheet is a table. But now there are users who draw in the timeline and do not even suspect the existence of Level Strip (they have this window turned off as unnecessary). And they draw (most often in the raster) duplicating frames and deleting them right on the timeline, not suspecting the intricacies of Autocreation.

However, in order not to argue about who is comfortable with which Autocreation mode, it may be worth looking at the problem from the other side. I have come across many times that different tasks require different Autocreation modes. Most often, I go to Preferences in order to change the "Autocreation" and "Enable auto-stretch frame" modes. Maybe there is still the opportunity to transfer these options to the Xsheet Toolbar, or at least make them available as operations?
 
Here's the topic on the Google forum regarding the above :https://groups.google.com/forum/#!category-topic/opentoonz_en/feature-requests/w3oz6Fxdxbc

**Comment by manongjohn** [comment]
The only reason I changed the default to `Use Xsheet as Animation Sheet` was because in other software the prior frame was essentially automatically held to he next new frame that was added. It did not require users to manually extend the prior frame every time a new frame was added. That setting mimiced this behavior.

The intent of the change was to help users make transition from other software to OT less of a learning curve by making OT behave similarly to what they are use to and what they might be expecting.

 Would it just make more sense to allow the `Enable auto-stretch frame` to work with `Enabled` setting? This might make `Use Xsheet as Animation Sheet` rather obsolete if that happens.

**Comment by manongjohn** [comment]
Oh. Personally. From a cell input behavior, i actually prefer the `Enabled` setting as well as modifying a frame from an extended exposure.  However, from a new drawing standpoint, I like `Use Xsheet as Animation Sheet` more because of the auto extention of the prior frame.

So if we change the default back to `Enabled` then I suggest `Enable auto-stretch frame` be allowed to work with it and have it turned on by default.

**Comment by artisteacher** [comment]
I also prefer "Use Xsheet as Animation Sheet" from a drawing standpoint. It's helpful that new levels are not created while drawing. On the other hand, I prefer to be able to type the frame number to expose other frames in the level, rather than it creating a frame # like 2a or having that feature completely disabled.

**Comment by artisteacher** [comment]
Ideally, I'd love to see "Use Xsheet as Animation Sheet" have an option to "expose existing frames by inputting frame numbers" anywhere in the column. If that wasn't possible, "Enabled" could have something like "disable automatically creating additional levels" so that drawing new frames continues adding to a single level.

**Comment by manongjohn** [comment]
Oh yeah, that's right.  I'm so used to Xsheet as Animation Sheet that I forgot about the other behaviors of Enabled. `Enabled`  was causing confusion with new users because the drawings they were making were all on different levels when they drew further down on the column.  Plus, when switching columns with different level types, adding a new frame this always created a frame in your default type, which may not match what is already in the column.

So I take back just making the auto-stretch allowed for Enabled and changing the default unless with auto-stretch turned on also makes it add to the existing level instead of a brand new level.

**Comment by gab3d** [comment]
I like the Use Xsheet as Animation Sheet mode, the two issues I find in it are:
 - not being able to expose an already existent drawing by double clicking a cell and typing a number.
 - the fact that if I draw on a frame *and* there already is a frame in the level with that number, the program doesn't warn me about it and created a new frame with a letter suffix.

For the fist issue, I don't envision what is the technical problem in allowing the direct input (I assume there is one).

For the second one, I'd like the program to open a dialog warning me that I'm about to create a new drawing in a frame for which there already exists a drawing in the level, and let me:
 - **Create** a new suffixed drawing.
 - **Replace** the existent drawing with the new one.
 - **Expose** the existent drawing, so I could draw on it.

**Comment by shun-iwasawa** [comment]
Thank you all. There seems to be a good guidance for modifying them.
Based on the opinions, there could be at least the following modifications;

- **Enabled** mode 
  - "One level for one column" basis - Expose the same level even when drawing on the cell further down from exiting level on the column.
  - Enable `Enable auto-stretch frame` option

-  **Use Xsheet as Animation Sheet** mode
   - When typing numbers on the cell, if the drawing exists, expose it instead of creating the new drawing with suffix.

I think the both options can be more consistent, and basically they can come down to the difference of numbering systems like as follows:

![numbering](https://user-images.githubusercontent.com/17974955/69592710-2568e380-103a-11ea-97b6-9861125e804b.png)

The left one is `"Enabled"` style, numbering the drawings being incremented by one. Japanese productions follow this.
The right one is `"Use Xsheet as Animation Sheet"` style, using the scene frame numbers for the drawings. It is also introduced as "the Best Numbering System" in the Animator's Survival Kit by Richard Williams.
I think other options like `auto-stretch` can be shared from the both modes.

**Comment by manongjohn** [comment]
Sorry to take this discussion on a slight tangent, but it is related to the topic...

In reference to the feature request for adding actions to command/xsheet bar for changing Autocreation mode and setting/unsetting auto-stretch, to my knowledge, we can only add button types to those bars. It currently does not support dropdowns or checkboxes , though I suppose we could make individual buttons for each autocreation entry which would just set you to that mode. It's not ideal to me.

As there aren't many places we can put a drop down and checkbox on the xsheet/timeline, I was wondering what people's thoughts were about putting the buttons in the title bar, similar to how there are buttons in the Viewer title bars.

It could look something like this:
![image](https://user-images.githubusercontent.com/19245851/69680494-076ea380-1079-11ea-89ed-9157071e8e88.png)

Button order: Autocreation Disabled, Autocreation Enabled, Autocreation As Animation Sheet, Auto-stretch Frame

Icon and Hints can be changed.

**Comment by gab3d** [comment]
I personally have no problem with icons like these to be in the title bar, but they could also be in the Xsheet Toolbar, so they could be hidden if user wants to.

**Comment by beeheemooth** [comment]
It’s a good idea, but can’t you put them before “Scene: Untitled” because the panel is sliding apart and the buttons will not be visible?

**Comment by shun-iwasawa** [comment]
Having these options more accessible would be helpful.
Since some users may not use the buttons in their workflow, I personally agree with @gab3d 's opinion that putting them in the xsheet toolbar if possible, or would like them to be hideable from the title bar.

**Comment by manongjohn** [comment]
*sighs* I can make them so they can be added to xsheet/command toolbars.  It won't be there by default, users will need to add them when they want them. Will allow them to have shortcuts too since I have to make them commands.  No complaints about the long button names taking too much space on the toolbars, then.

**Comment by gab3d** [comment]
@manongjohn 
I think we're envisioning them like 'icons' (not text), and placed in the Xsheet Toolbar by default.
(anyone, please correct me if you see some other better configuration).

Do you have objections to that?

**Comment by manongjohn** [comment]
If someone wants to provide icons for them, great, i'll use them. I was going to ask for someone to provide with the titlebar implementation.  However, as it's the toolbar implementation we're settling for, icons are not required so I'm not planning on adding icons for them unless someone wants to provide them.

**Comment by hayoko** [comment]
Why not just add a menu to the window like you find in Adobe and Clip etc. and put all the options for stuff in that? What is the reason for placing everything on the UI? This would be useful to have in many windows. You can put that timeline/xsheet layout switch button in there and much of the preferences stuff so it's quick to switch things.

This is what Harmony and most of the big apps do, it's very tidy.

![image](https://user-images.githubusercontent.com/36535462/69723258-0be69b00-1111-11ea-9e55-d43fccb7b2b7.png)

**Comment by manongjohn** [comment]
Reasons for UI: Ease of access, not so much clicking. Actual visibility into the mode you are currently using for quick reference but you can see which one is on/off. Trying to improve the workflows of users who switch modes and turn off auto-stretch a number of times as part of their workflow. 

Why are people are afraid of new UI buttons? 🙂 if you don't use it..ignore it? How many people just ignore the 1 and only button on the Palette window's titlebar? Is it used a lot in everyone's workflow? Can we hide it? Why is it even there? Not sure what it is even used for since I never use it.

Anyway, it's far less coding for adding to xsheet/command bars so I'm good. 

As for your suggestion, it did cross my mind originally to replace that button with a Settings dropdown menu button. Another option is to make right-click context menu entries (cell, header or both?). Whatever is agreed upon.

**Comment by gab3d** [comment]
@hayoko 
well, I have to admit this could be a good solution, not only for this particular issue, but for many others too.

I understand this would take a lot more than "adding 4 buttons to something", but perhaps in the mid-term it could be a good thing for saving screen space in other panels too.
What others think?

**Comment by gab3d** [comment]
@manongjohn 
From the Manual: 😄 
> By default the Palette editor is *active*, that means that it automatically displays the styles of the current animation level, but it can be made *inactive* in order not to be updated when you select a different level. In this way, by opening more than one Palette editor it will be possible to compare and edit several palettes referring to different animation levels, at the same time.

With respect to you reasons, I agree with them. I also value a lot the "less clicks as possible" philosophy (and keyboard shortcuts), and there is also a good point in being able to see the status of the option with just a quick gaze. 
I suppose both of them could be achieved by using Xsheet Toolbar buttons? 🤔

**Comment by manongjohn** [comment]
@gab3d 
Interesting. Have not found myself in a situation that I needed to use that but now I know what it's for. Thanks.

I should really go read the manual to familiarize myself with what's in it. 😄

The xsheet/command toolbar buttons currently do not support any particular status display. They are simply 1x push action buttons.

**Comment by gab3d** [comment]
@manongjohn 
hehe  yeah, it's all in there! 😄 
plus, it has one "super feature" and that is that is searchable, that makes it super handy when you need to know something quickly
![imagen](https://user-images.githubusercontent.com/18104091/69741974-c0d18580-111a-11ea-9ec4-1b4e4df31dce.png)

**Comment by gab3d** [comment]
@manongjohn
> The xsheet/command toolbar buttons currently do not support any particular status display. They are simply 1x push action buttons.

mmm... I was in doubt about this one. that's a shame. 😒

**Comment by artisteacher** [comment]
Maybe the behavior should be like the bottom of the viewer, where the menu icon allows you to enable/disable the different view buttons/controls. In the Xsheet version, we might add the xsheet toolbar visibility to the same menu.
![buttons](https://user-images.githubusercontent.com/21159116/69779468-1edf8680-1176-11ea-8410-3acbe139b84d.png)
Though I didn't list it above, I would add the camera column visibility to the menu too.

**Comment by snapai** [comment]
@manongjohn 
> The xsheet/command toolbar buttons currently do not support any particular status display. They are simply 1x push action buttons.

The "Edit in Place" button does seem to display its current status with a highlight, even when toggled from a menu command. Might have been written custom for that though, did you write that one?

**Comment by manongjohn** [comment]
@snapai Thanks for pointing that out. Must have been specially coded to do that. I didn't write that one.

**Comment by RodneyBaker** [comment]
Minor update to discussion...

#2907 was recently merged which improves the workflow of creating new (blank) drawings in conjunctions with autocreation modes.

@shun-iwasawa Is your take still that the default should be 'Enabled' for Autocreation rather than 'Use Xsheet as Animation sheet'?  
Are we getting close to answering the question(s) you've raised?  
What (if anything) still needs to be done?

**Comment by shun-iwasawa** [comment]
I'm planning to implement the following modifications (hopefully) by the feature freeze.

> - Enabled mode
>   - "One level for one column" basis - Expose the same level even when drawing on the cell further down from exiting level on the column.
>   - Enable `Enable auto-stretch frame` option
> 
> - Use Xsheet as Animation Sheet mode
>   - When typing numbers on the cell, if the drawing exists, expose it instead of creating the new drawing with suffix.

As the second step I'm also thinking introducing another preference option like `Autorenumber drawings`, which will renumber the following frames in the column to be straightforward (i.e. incremental as possible in the column and without suffix) on inserting the drawing.
I'm not sure if I could work on this in time for the next version.

**Comment by RodneyBaker** [comment]
Based on the merger of #2943 back in 2018 I believe this report can be closed.
It looks like we just overlooked closing.
