### ISSUE TITLE
(Discussion) Nikon D5300 support

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [opentoonz/opentoonz#2917]
I need to work on a stopmotion film, but I cannot make OpenToonz detect my camera, a Nikon D5300, while it is working on all other programs other than this one in this computer.

![image](https://user-images.githubusercontent.com/47691365/70181651-3a004800-16da-11ea-9ef9-c5df8cb49f6a.png)

System Information
OpenToonz 1.3
Windows 7
Ryzen 7 2700
16GB RAM 
GeForce GTX 770
UGEE HK1560

**Comment by artisteacher** [comment]
Unfortunately, DSLR's are not currently supported. If #2635 is merged, then Canon DSLRs will be recognized. Hopefully additional cameras will follow.

Right now, I believe just webcams are supported. I don't have an external webcam, but the internal camera on my MacBook does work with OpenToonz.

**Comment by ThePortuguesePlayer** [comment]
Well... Although that does not help my case right now, at least now I know why it was not opening.
Thanks.
Does anyone know of a walkaround method or an alternative program for doing stopmotion/pixelation?
The feature I need the most is the live view with onion skins (or just being able to toggle between frames). I've been doing it "blind", with the camera alone and a remote shutter, but as the animations get more complex that method is starting to become too time consuming for the rate I have to get these done at.

**Comment by RodneyBaker** [comment]
If you are on Windows and are willing to set up a portable version of Opentoonz this might work for you:

https://ci.appveyor.com/api/buildjobs/9oj4u6vtvwnhhvg0/artifacts/toonz%2Fx64%2FOpenToonz.zip

What you have to do to make the contents of the above zip file into a working portable for Opentoonz is:

- Download the zipfile from the link above (or alternatively grab it from same location via PR #2635 (the appveyor artifact)
Note:  When downloading I would name the download "Opentoonz (DSLR)" or appropriate name so that when you unzip the file it will be in a directory with a useful name.
- Unzip the file to a known location
Two directories will be created:  Opentoonz and Opentoonz stuff
- Rename "Opentoonz stuff" as "portablestuff"
- Drag and drop the newly named portablestuff directory into the Opentoonz directory
If you've done all of the above successfully you now have a portable copy of Opentoonz with the DSLR feature.

Disclaimer:  I do not know if this will work with your camera but the above is a good way to find out short of building Opentoonz yourself with the DSLR feature.  The zip file you download and unzip is an automated build that occurs for every Opentoonz PR via github and instructions for getting to the artifact/zip file are located here if you prefer not to use my instructions above:   [LINK](https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_test_prs.md)

Note:  Any windows Opentoonz release can be made portable by placing a valid 'portablestuff' directory into the root directory of the Opentoonz executable.  The exe will still run without being portable BUT will not have important updates such as updated menus for the DSLR feature.  This is why you need to use the stuff directory from the zip file.

If you have any questions or concerns please let me know!  :)

I am a little concerned about use of Windows 7 but...

**Comment by hayoko** [comment]
If you need a free option, you can give [digiCamControl](http://digicamcontrol.com/) a try. It supports "onion skinning", in live view windows, go to overlay tab, check the activate and the use last captured and set the transparency.

If you're willing to buy software just get [DragonFrame](https://www.dragonframe.com/store/) ($295 with USB controller) and don't look back, it was used to capture the stills for Coraline, Kubo and the Two Strings and other films, etc. and when I produced stop-motion assets for a project awhile back DragonFrame reduced the time it took by orders of magnitude more than anything else.

Give the trial a go, they list your camera as supported (as far as I know every camera is supported) but make sure before buying.

Trial: https://www.dragonframe.com/downloads/

![image](https://user-images.githubusercontent.com/36535462/70197625-6335ce00-1704-11ea-9fe3-0eb899569db2.png)

**Comment by shun-iwasawa** [comment]
FYI I once tried [Sparkocam](https://sparkosoft.com/sparkocam) ($49.95 per license with Nikon DSLR support) and confirmed that a DSLR camera was recognized as webcam and enabled to use on Qt application.

**Comment by RodneyBaker** [comment]
Thanks @shun-iwasawa   I was trying to recall the name of that program.
Sparkocam reportedly supports:

> Canon Rebel XS, Canon Rebel XSi, Canon Rebel Kiss X2, Canon Kiss F, Canon Kiss X3, Canon Kiss X4, Canon Kiss X5, Canon Kiss X6i, Canon Kiss X7i, Canon Kiss X7, Canon Kiss F, Canon Kiss X50, Canon 8000D, Canon Kiss X8i, Canon Kiss X80, Canon Kiss X9i, Canon 9000D, Canon Kiss X9, Canon Kiss X90, Canon Kiss X10
> 
> Canon T1i, Canon T2i, Canon T3, Canon T3i, Canon T4i, Canon T5, Canon T5i, Canon SL1, Canon T6, Canon T6i, Canon T6s, Canon T7i, Canon T7, Canon T100, Canon M50
> 
> Canon 1D Mark II, Canon 1Ds Mark II, Canon 1D Mark II N, Canon 1D Mark III, Canon 1Ds Mark III, Canon 5D Mark II, Canon 5D Mark III, Canon 1D Mark IV, Canon 1D X, Canon 1D X Mark II, Canon 5D Mark IV, Canon 6D Mark II
> 
> Canon 1000D, Canon 1100D, Canon 1200D, Canon 1300D, Canon 450D, Canon 500D, Canon 550D, Canon 600D, Canon 650D, Canon 700D, Canon 40D, Canon 50D, Canon 60D, Canon 6D, Canon 7D, Canon 1D C, Canon 1D Mark IV, Canon 100D, Canon 70D, Canon 80D, Canon 7D Mark II, Canon 750D, Canon 760D, Canon 5DS, Canon 5DS R, Canon 800D, Canon 77D, Canon SL2, Canon SL3, Canon 200D, Canon 2000D, Canon 4000D, Canon EOS R, Canon EOS RP, Canon 250D, Canon 200D II
> 
> Nikon D5500, Nikon D750, Nikon D7100, Nikon D7000, Nikon D5300, Nikon D5200, Nikon D5100, Nikon D5000, Nikon D90, Nikon D800, Nikon D810, Nikon D800E, Nikon D600, Nikon D610, Nikon D700, Nikon D4, Nikon Df, Nikon D4s, Nikon D300, Nikon D300s, Nikon D3, Nikon D3s, Nikon D3X, Nikon D7200, Nikon D810A, Nikon 1 V3, Nikon D500, Nikon D5, Nikon D5600, Nikon D7500, Nikon Z6, Nikon Z7

**Comment by ThePortuguesePlayer** [comment]
I will try that with digiCamControl (I already had it and it's working, I just didn't know you could have an overlay picture), but Sparkocam is actually looking like a great option too! A sort of fake driver was what I was getting at with the workaround, so, that worked well. I will also explore some options with Blender as I saw somewhere it had some stopmotion related addons available for it.
I'm doing this as no profit for now, so, I still cannot afford something like Dragonframe, unfortunately.
Thanks for all the help!

**Comment by RodneyBaker** [comment]
Closing but the discussion can continue until that inevitable day when support is added to Opentoonz.  :)

**Comment by ThePortuguesePlayer** [comment]
LOL.
I've been trying DigiCamControl and I've noticed it had some sort of fake web cam plugin, but I haven't been able to get it working. It doesn't show up in all programs and when it does it just shows black with the camera connected. Then I saw that there was an update available that had fixes regarding the WebServer so I went and updated the program, but now, everytime I open this updated DigiCamControl it soft-locks my PC on loading. Completely freezes, I gotta press the reset button at that point. Tried to downgrade, but I think it just keeps the same version. I am uninstalling right now to see if I can get the previous version back.
