### ISSUE TITLE
Levels with two character alpha numeric filename fail

### ISSUE THREAD

**Issue by mosujiba** [opentoonz/opentoonz#2945]
### Issue Summary
When loading a level from a file, the program cannot parse its name if it begins with a number.  If you select such a file in the Load Level dialog or drag and drop it onto the program, the filename will simply show up blank (except for its extension). If you manually enter the filename, it will go missing when the program asks if you want to import it or load it.

### Screenshot or Video Reference
![opentoonz_error](https://user-images.githubusercontent.com/5388020/70960115-1c24d280-204c-11ea-97b5-95be2f3bd4a3.png)

### System Information
* **OpenToonz Version**:  1.3
* **Operating System**:  Windows 10

**Comment by artisteacher** [comment]
I'm seeing the same in macOS.

**Comment by gab3d** [comment]
It's described in the Manual as an invalid file type: [here](https://opentoonz.readthedocs.io/en/latest/working_in_xsheet.html#loading-levels).

**Comment by mosujiba** [comment]
In that case, the program should display an error message when it detects an invalid file type. It should not fail silently.

**Comment by gab3d** [comment]
I can certainly agree with that.

**Comment by RodneyBaker** [comment]
I agree in part although even better would be that Opentoonz be able to accept that particular filenaming as well.

The good news is that over the past year a number of filename related issues have been resolved and this is one of the remaining issue.  This particular one is of interest because the filenaming convention might actually be the same as filenaming used in the xsheet;  as a standard animation ordering of levels/frames might include such designations as 2A, 2B, etc.  

What is perhaps most perplexing to me is how we can (via Preferences) set different file formatting syntax (via Regular Expression and yet that appears to be ignored entirely. It is hoped that in the coming 2020 development cycle we'll be able to close in on the remaining filenaming issues and resolve them as well.

Thanks @mosujiba for your report as it suggests there is still some work to be done with filenaming conventions.

**Comment by gab3d** [comment]
Agreed; meanwhile a simple warning to the user would avoid lots of confusion.

**Comment by RodneyBaker** [comment]
> ...a simple warning to the user would avoid lots of confusion.

Yes, here are a few more thoughts toward that end:

Opentoonz should catch the exceptions to the rule and let the user know a particular file formatting is not supported.  I'd suggest some additional things here but I'm not entirely sure the user set RegEx via Preferences even works at present.  If it did then I'd say the simple warning would inform the user that their particular filenaming requirement that isn't supported could be supported if they assign it via RegEx in Preferences.

In short, it is my understanding that every filenaming convention should be useable as long as it has been set.  The heirarchy being:

- Filenaming expressly prohibited (an example of this was a recent change where filenames using AUX, PORT, etc reserved for Windows usage throw an exception and informs the user of the prohibition)

- Preferred filenaming format (this for optimal efficiency and workflow)

- Expressly allowed filenaming (this for customization... example:  Digital Videos StoryPlanner default file formatting not being recognized)

- User extended filenaming conventions via RegEx in Preferences

- Error message to catch exceptions to any of the above

**Comment by RodneyBaker** [comment]
I will add also;

Make sure to use a recent nightly release in order to gain the latest improvements in filenaming.
Much has been improved in this since the release of v1.4 back in January.
