### ISSUE TITLE
(Discussion) Add a room for Stop-Motion?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2981]
There are some default rooms that I hardly ever used (i.e. Xsheet or Palette), should we replace some of them with a new room dedicated to stop-motion work?

In such a case, what panels should it include?
@turtletooth 

To start from somewhere, I've figured out something along these lines:
![imagen](https://user-images.githubusercontent.com/18104091/71786695-2738a600-2fed-11ea-9b86-1c97fcb97994.png)

What do you think...?

**Comment by RodneyBaker** [comment]
I wouldn't might seeing a Camera Capture or Stopmotion tab being added to the Default room set but I'm not a fan of dropping the Xsheet and Palette room tabs from the Default set.  Both of these are pretty important although likely not used as much by one person 'studios'.

Whether adding a new tab or not I'd say where the emphasis for workflow would benefit the most would be in adding a new set or two to the current Default and Studio Ghibli options.  I recently added a "Sketching" set for testing purposes to see what a UI focusing on Sketching might look like.

![Room Sets](https://user-images.githubusercontent.com/2576432/71787204-abcdf900-2fda-11ea-9374-b08365942d8f.png)


Aside:  In case its not clear, I use the term 'Room sets' here to distinguish between the rooms we can choose from in Preferences  > Interface versus the rooms we can select via tabs inside each of those.

**Comment by beeheemooth** [comment]
I often use the "Xsheet" room. I don’t think we need to delete anything. By the way, do not forget that switching between rooms leads to a glitch with the render window.

**Comment by gab3d** [comment]
In most situations there's enough space where Room tabs are located, so I really see no problem in adding one extra there.

**Comment by artisteacher** [comment]
I think it would be a good idea to have a few room sets optimized for different workflows. The default room set has a lot of rooms - not all of which are currently helpful. On macOS, I can't use the Cleanup room due to too much crashing and the Farm room is pointless while batch rendering fails. I'd love to see a simplified room set optimized for new learners. 

Once stop motion has been expanded for other OS, it would be helpful to have a stop motion dedicated room or a room set. I wouldn't add one while it is only available on Windows.

**Comment by RodneyBaker** [comment]
> I wouldn't add one while it is only available on Windows.

I agree it is a little premature to add a new stopmotion room _given the feature isn't now available on Mac/Linux_.  This is exactly the time however where such a design and implementation should be explored however.

One thing we might investigate is how we can best proceed with design, approval and implementation of new rooms new features requiring them are introduced.  At present the process looks to be:

- Someone creates a new room set (tagged in some way as experimental) and shares it with the OT development community
- Others test the effort and provide feedback
- Developers iterate through improvements 
- PR is generated allowing wider testing
- Feedback/Review cycle
- Implementation in nightly followed by improvements where necessary
- Incorporation into full release

I'd say we are at the first step where an initial offering (or two) of new room set for stopmotion should be shared with goal of getting it into the hands of users that will use the room and be motivated to provide feedback to further improve it.  In this way those that don't want to wait for a full release can download and use it or use it to guide creation of their own.

Many don't have the cameras reportedly required for use of the feature so there is a need for documentation and general workflow as well.  

Finally, it would be good to state as a target the release where such proposed additions would be included.  Example:   v1.5 release (circa June 2020)
This specifically (for this addition) because it is unrealistic to include in v1.4 but we are hopeful there will be a mid year release in June.  This also to better measure progress toward the stated goal(s).

**Comment by RodneyBaker** [comment]
Review/update:  There is currently a standalone Stopmotion room in the Tahoma release of Opentoonz.
This not only may satisfy the requirements of this feature request/discussion but also provides the underlying files/data needed to mirror a similar room in Opentoonz.
