### ISSUE TITLE
[DRAFT] Posting Guidelines (1st time posters, please read!) [DRAFT]

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2989]
_This is a draft of a notice targeting 1st time posters. This issue is just to discuss suggestions and revisions.  Any feedback is welcome. When ready, I will submit a new Issue that will be Pinned and locked for comments._

### Guidelines for Posting Issues
----
- Please use this site for posting software issues, bugs and crashes only.

- Posts of the following nature should be redirected to the appropriate category in the official [OpenToonz Google Group](https://groups.google.com/forum/#!forum/opentoonz_en)

	- Feature and Enhancement requests 
	- How-to questions
	- General questions about OpenToonz

- Before posting an Issue:

	- Search Issues to see if someone has already submitted the problem or something like it.  If you have additional information, feel free to add to the discussion or just let us know you're having the same issue too.
	- Make sure you are running the latest Official version or the most recent Nightly version of OpenToonz.
		- If you are using an OpenToonz variant (Morevna, OTX, other), download the most recent Nightly and see if it can be duplicated there because the issue you are experiencing may be specific to that variant.
	- Gather as much information as you can regarding the bug/issue.  Examples of things you can provide:
		- Tell us what version of OpenToonz you are on especially it isn't the current official one.
		- Tell us what Operating System you are on and whether you are using a tablet, using a pen or a mouse, etc
		- Reliable steps to reproduce.
		- Any system logs related to a crash. (Windows Event logs, macOS crash logs, etc.)
		- Screenshots.
		- Animated jpg/gifs or links to videos showing the problem.
		- A sample scene, level file or project illustrating the problem, if possible.

- General conversion

	- Try and be constructive in feedback in Issues and Pull Requests.
	- Don't be rude.

Thanks,
OpenToonz Community

**Comment by RodneyBaker** [comment]
Looks good.
One piddly thing...
Perhaps you mean 'conversation' instead of 'conversion' in that last bullet point?

**Comment by hayoko** [comment]
I reworded your post a little to sound more formal and compacted some info to make it a lot quicker to read. Feel free to use, edit or discard. I think you can grab the post layout by quote replying.

_(Although I personally dislike disallowing feature requests here.)_

---

# Posting Guidelines
Only bug or crash reports are accepted here.

The following kinds of posts should be made in the official [OpenToonz Forum](https://groups.google.com/forum/#!forum/opentoonz_en).
- Feature requests
- How-to
- General discussion

## Before You Post
### Use the search function to check if your issue has already been resolved
- If the issue already exists and has been closed/resolved but the solution has not worked for you, then please add to the existing discussion as contributors may be notified and may be able to help you.
- When you create a new issue report, please fill out the information requested included in the post body as this will help us reproduce your issue.

### Make sure you are running the most up to date version of OpenToonz
- If you are running the official stable build, you can install the latest nightly build to check if it resolves your problem first.
- If you are running an edition of OpenToonz maintained by a third-party, please install and run the latest official build before posting and check if you can reproduce your issue, otherwise we may not be able to help you.

| Official Builds | 🔽  |
| --- | --- |
| Stable | **[Download](https://opentoonz.github.io/e/download/opentoonz.htm)** |
| Nightly | **[Download](https://github.com/opentoonz/opentoonz/releases/tag/nightly)** |

----
Regards,
OpenToonz Community

**Comment by RodneyBaker** [comment]
To cover the topic of Feature Requests we likely need a page dedicated to the subject which can be created in the future separate from this.  

Perhaps we could add a line (to @hayoko 's update) stating:

Note: Feature Requests posted to github without attached developer will be closed pending assignment of developer.  Closed issues can still be discussed and developed.

At least then all parties would understand the process.
In the interim, I have begun tagging feature requests with an assigned developer as 'roadmap' to allow easier understanding of why some feature requests are open while others are closed.

**Comment by hayoko** [comment]
> To cover the topic of Feature Requests we likely need a page dedicated to the subject which can be created in the future separate from this.

Well, all the guidelines should go into the front page wiki, really all you need is a paragraph, something like this (taken from xamarin) for this though...

**_Feature requests are welcomed. Before opening a feature request, please take a moment to find out whether your idea fits with the scope and goals of the project. It’s up to you to make a strong case to convince the project maintainers the merits of the feature. Please provide as much detail and context as possible._**

> Note: Feature Requests posted to github without attached developer will be closed pending assignment of developer. Closed issues can still be discussed and developed. At least then all parties would understand the process.

I don't think people will appreciate being asked to (potentially) pitch to an empty void, you should only close something when you've come to a definitive conclusion on the matter.

A feature request is a pitch to the maintainers, usually by somebody who lacks the skills or access to contribute it directly, working with a developer is neither here nor there.

**Comment by RodneyBaker** [comment]
I don't want to go off on a tangent concerning Feature Requests but the subject keeps returning.
I personally will adjust to whatever the policy is... and will do my best to adhere to the current policy (i.e. closing feature requests not assigned to a developer).  I don't prefer that... I just press on.

I am not sure if it would work BUT... personally I would like to open to flood gates for feature requests and even further encourage submission of feature requests.  What I propose would be:

- Create an official branch/fork of Opentoonz (that no one will submit PRs to).
- The entire purpose of the branch will be to mirror the master branch and...
- Collect all manner of Feature and enhancement requests.
-- Each will then have a 'ticket' assigned via the Issue number (as well and the date submitted).
-- A ticket can then be tracked via sorting (in github) by date and issue number

Anticipated Pros
- We should collect a ton of requests
- Everyone can track their favorite requests

Anticipated Cons
- Someone would need to keep the fork synced with master
- Not everyone will want to open a github account in order to open a feature request

To offset the cons
- Determine the optimum way to keep forks in sync with masters
- Maintain the Opentoonz Forum's Feature Request category for general discussion on features and enhancements

This to keep noise to a minimum on the master and to fully encourage and engage users desiring to provide feedback.

**Comment by RodneyBaker** [comment]
I believe this has been addressed via #3006 and #3244.
@manongjohn please advise if this is not the case.
