### ISSUE TITLE
Font colors in the default UI theme.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3020]
![2020-01-13_112314](https://user-images.githubusercontent.com/25724133/72386880-ecd8b280-372a-11ea-90ec-52c22e73852a.jpg)
![2020-01-13_112435](https://user-images.githubusercontent.com/25724133/72386886-efd3a300-372a-11ea-9d0f-b7257375c5ad.jpg)

**Comment by konero** [comment]
I took a look, it's due to hard-coded colors for Export Scene and Plastic Tool. Although Export Scene uses `QTreeView` which is now handled by stylesheets, the text and selected item `background-color` is being overridden.

In Function Panel the Plastic Tool doesn't appear to be using the properties set for this, which I think are `m_textColor` and `m_selectedColor`.

There's so much styling though, and there may be good reasons, so I'm not sure what I'm looking at, I don't think I've seen some of this stuff actually open in the program to know what it does, maybe @shun-iwasawa can have a look sometime. 🙏

**Comment by konero** [comment]
I found another occurrence of the text issue, if you try to drag a palette from the Studio Palette window over a folder the text turns and stays black.

![drag2](https://user-images.githubusercontent.com/19820721/72416322-56c67b80-376e-11ea-9b84-5f5355c1e233.gif)
