### ISSUE TITLE
(Proposal) Have vector levels created on disk consistent with the other level types

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#3036]
### Issue Summary
At the point you create a Toonz Raster or Raster level, a file is created on disk. When you create a Toonz Vector level it isn't until you hit save.

In the attached recording you can see that I have to press Save All to create the files on disk for the vector level. This inconsistency is confusing to users and could potentially result in users losing data.

### Screenshot or Video Reference
![ScreenCapture](https://user-images.githubusercontent.com/28575907/72544835-fc1d4480-387f-11ea-9cf1-7fba261a440b.gif)

### System Information
* **OpenToonz Version**: V1.3 Built Oct 5 2019 10:17:51
* **Operating System**: Windows 10

**Comment by openanim** [comment]
I also mentioned this problem in the forum in the past, but personally I find that it is the behavior of the vector level which is in the most logical. I don't want a file to be saved until I choose to do it. Or opted for automatic backup in the opposite case. And indeed, it creates a lot of confusion that the other levels react differently.

**Comment by DarrenTAnims** [comment]
I'd be more than happy for none of the drawings levels to be created until you hit save. Consistency is more important, And other applications that handles different files don't tend to save them until you hit save.

**Comment by manongjohn** [comment]
I also agree files should not save unless you specifically chose to.

**Comment by melieconiek** [comment]
Chiming in myself here. I'll sometimes create a new vector level only to decide I don't need it--clear it from the project before I save.

In the very least I wouldn't want this behavior the change for vector levels.

**Comment by RodneyBaker** [comment]
Rather than leave this open indefinitely I've retitled as a proposal.
At some point a decision can therefore be made on whether to implement, table or set aside.

Given the feedback thus far it would seem if implemented it should be an option (presumably accessed via Preferences).

At any rate, this proposal is unlikely to be implemented in v1.5 so we'll punt the decision making into 2021 development cycle...

**Comment by RodneyBaker** [comment]
@DarrenTAnims Just conducting a review of open issues.
It's not clear what if anything might have changed since this proposal was first opened.
Consensus is that vector levels should not gain the process that is currently present with raster and toonz raster levels where they are created on disk.

My thought/concern regarding vectors is that of all the level types vector tends to be the least stable.
I therefore find it curious that it is the one level type not saved to disc upon creation.
It is not clear to me where the data is stored pending save of the level but I must assume it is stored in cache.
Then when the user saves the level or scene and level (via Save All) the .pli level is written to disk.

I do not recommend raster and toonz raster levels loose their current abilty to reside on disc immediately upon creation.

So, to the proposal of consistency we are still at a dilemma.
Recommend reviewing with eye for deeper optimization and consistency after the next release.

**Comment by RodneyBaker** [comment]
Closing as part of general housekeeping.
Let's reconsider the best way forward relative to this proposal in the 2022 development cycle.
