### ISSUE TITLE
Windows Messed Up

### ISSUE THREAD

**Issue by rivercats** [opentoonz/opentoonz#3039]
Has anyone else had this issue? in all my searching I can't seem to find anything.

### Issue Summary
A while ago when I opened Opentoonz I drew a stroke and all the windows became messed up (see video below). I updated Opentoonz, deleted all the program files and reinstalled, but the issue does not go away. I use a Windows 10 computer.

### Screenshot or Video Reference
https://youtu.be/FnYE7GqJS1k

### Steps to Reproduce
Open program > draw stroke with brush tool or move scene window

### Expected Results
stroke is drawn, window moves

### Actual Results
other features zoom in and deform

### System Information
Opentoonz 1.3
Wacom Mobilestudio Pro 13

**Comment by manongjohn** [comment]
This is the same problem as #2965.

A number of Windows users have been reporting this lately.  It is due to some issue in certain versions Intel Graphics Driver versions.  

Verify you have an Intel Graphics display adapter in Windows Device Manager.  If you do, you most likely need to manually download and install the latest version 26.20.100.7584.  Here is the installer for that version: https://downloadmirror.intel.com/29274/a08/igfx_win10_100.7584.exe

**Comment by rivercats** [comment]
Ahh thank you so much!! This worked!
