### ISSUE TITLE
Inbetweening keyboard shortcuts only work when 'Vector Guided Drawing Controls' window is open.

### ISSUE THREAD

**Issue by melieconiek** [opentoonz/opentoonz#3040]
### Issue Summary
Auto inbeetweening keyboard shortcuts (Tween Selected Guide Strokes, Flip Guide Stroke, etc) only work when the 'Vector Guided Drawing Controls' window is open.

### Steps to Reproduce
- Close the 'Vector Guided Drawing Controls' window.
- Assign a keyboard shortcut to 'Select Previous Frame Guide Stroke.'
- Try to execute the command via the keyboard shortcut.

### Expected Results
The 'Select Previous Frame Guide Stroke' command is executed.

### Actual Results
Nothing.

### System Information
* **OpenToonz Version**: Latest nightly.
* **Operating System**: Windows 10

**Comment by shun-iwasawa** [comment]
@manongjohn 
The actions seem to be needed to be added to some visible widget in order to trigger it from the shortcut key.
For now the auto inbetweening actions are [defined](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/mainwindow.cpp#L2212-L2229) as `Misc` command type, which will not be added to any widget on definition and will be only effective when the `Vector Guided Drawing Controls` window is visible.

If it is not intended, how about defining actions as `Tool Modifier` command type (by calling `createToolOptionsAction` instead of `createMiscAction` ) as they [will be added to the main window](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/mainwindow.cpp#L1515) thus they can be triggered via shortcut keys any time?

**Comment by manongjohn** [comment]
@shun-iwasawa Yes. Thanks for the suggestion.  I was looking at how to do that after I realized the command wasn't tied to an active widget and wasn't sure how I was going to handle that.  I had though about adding it to the SceneViewer logic where the Viewer Zoom/Reset shortcuts are handled but wasn't entirely thrilled by that logic.

I currently have a fix for the Undo guided drawing issue that was reported but I uncovered a strange undo scenario which I am trying to resolve but currently having trouble with.  Once I fix that, I will also address this issue in the same PR.
