### ISSUE TITLE
[Proposal] Set default background color for scene settings

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#3066]
### Issue Summary
It'd be a big help if the alpha on the background colour for the scene settings was set to show the white background colour. I've had so many people ask why their animation is all black when they've drawn in black, seen a white background on screen, then exported and the exported background is transparent, but their player puts in a black background, so they can't see their animation.

This puts off so many people to OpenToonz when they first use it and it'd just be a big help. A user can always set the alpha back to zero if they want to, but I think these users and the uses are in the minority and most users want a background and on screen, so having a white default background would be a huge help and shouldn't be a big change to make.

**Comment by shun-iwasawa** [comment]
In which format did they rendered? If it happens in the current version, it may be a bug rather than a matter of the default settings.

From v1.3 I modified the rendering process to insert a solid background when user renders in  non-alpha enabled formats. ( #2418 )
The only exception is QuickTime movie file (.mov). It was difficult for me to identify the current settings (either w/ alpha or  w/o alpha) so I made it always NOT to insert the solid background (i.e. alpha channel set in the scene settings is used). ( #2544 )

**Comment by gab3d** [comment]
It's not exactly the same, but I think it could contribute to alleviate the same problem:

Perhaps while previewing, the Viewer background could be automatically made to display the checkered background behind the camera background color. So when the latter is transparent, users would always be conscious about its transparency status.

**Comment by RodneyBaker** [comment]
@DarrenTAnims You may wish to read #388 as it covers similar territory.

**Comment by RodneyBaker** [comment]
As this proposal is over two years old and has not gained traction will close it for now with the expectation to consider it again for the 2022 development cycle.
