### ISSUE TITLE
windows get disorganized

### ISSUE THREAD

**Issue by cakri99** [opentoonz/opentoonz#3078]
### **Issue Summary**
Every time I use a tool like the brush or geometry, the windows pick up and get disorganized.

### **Screenshot or Video Reference**
https://gfycat.com/afraidhappyeastrussiancoursinghounds

### **Steps to Reproduce**
Uninstall and delete cache from the program and reinstall it
### **Expected Results**
That didn't work, it's the same

### **Actual Results**
Any result...

### **System Information**

* **OpenToonz version 1.3 and 1.4RC**: 
* **Windows 10**: 
* **Intel i7-6500U**: 
* **16GB**: 
* **Intel HD Graphics**: 
* **I don't have a graphic tablet**:

**Comment by shun-iwasawa** [comment]
Please see #3039 and try updating the Intel graphics driver.

**Comment by artisteacher** [comment]
If the windows are being pulled out of the docked position, it might help to toggle on "Lock Room Panes" in the "Windows -> Workspace" menu.
<img width="546" alt="Screen Shot 2020-01-31 at 1 14 05 PM" src="https://user-images.githubusercontent.com/21159116/73563977-9ce93380-442c-11ea-90e8-8038ae8cb7c8.png">

**Comment by cakri99** [comment]
> Please see #3039 and try updating the Intel graphics driver.

I have the latest drivers for my controller and nothing

**Comment by cakri99** [comment]
> If the windows are being pulled out of the docked position, it might help to toggle on "Lock Room Panes" in the "Windows -> Workspace" menu.
> <img alt="Screen Shot 2020-01-31 at 1 14 05 PM" width="546" src="https://user-images.githubusercontent.com/21159116/73563977-9ce93380-442c-11ea-90e8-8038ae8cb7c8.png">

I did that and still the problem

**Comment by manongjohn** [comment]
@cakri99 Just to be clear, you verified you have at least driver version 26.20.100.7584?  Don't just try to do a Driver Update because it won't detect and download this version automatically.  You need to manually pull down this driver update and install it yourself.

Do you have any other graphics drivers installed like NVIDIA?  Another user fixed this same issue by going into the NVIDIA Control Panel and created a 3D profile for OpenToonz.exe configured, presumably, to use the Higher Performance GPU on their graphics card. Another way to potentially fix this is going to Window's Graphics Settings and creating a profile for OpenToonz.exe and configure for High Performance GPU usage.  "Graphics Settings" in Windows Settings is available on recent versions of Win10, so if you can't find it, you may need to update that as well.

**Comment by cakri99** [comment]
I could already solve the problem as follows:

Since I saw that many said it was for the drivers or the drivers recommended that I update the drivers but I already had them updated to the latest version. How to solve the problem, then investigating and investigating discovered that to go to configurations - system - screen, slide down clicks on the option that says configuration of graphic elements. In this option it gives you the option to choose with which graphic card you want this application to run, as in my case I have 2 graphic cards, Intel and AMD because I chose that operation I would run with the AMD since the problem was with the intel.

Thank you all for your help, because thanks to that I was able to reach the solution, thank you very much.
![image](https://user-images.githubusercontent.com/60473289/73974432-baba0b00-48fa-11ea-817b-81a5924d703e.png)

**Comment by RodneyBaker** [comment]
Glad to hear you found a solution @cakri99 
If you are running two monitors (i.e. one for each graphics card) then you might check to see that they are both running the same resolution.  It has been reported that maintaining same resolutions across monitors resolves some conflicts.
