### ISSUE TITLE
Geometric Tool Shapes should have individually mappable keyboard shortcuts

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3137]
As I was working on the new Adobe Animate keyboard shortcut preset, I noticed that interestingly OpenToonz has a mappable keyboard shortcut to switch to the Geometric Tool (Tools > Geometric Tool in the keyboard shortcuts window), and one to rotate between the shape the tool'll create (Tool Modifiers > Geometric Shape), but you can't as far as I can tell have individual mappings for individual shapes, ie. Rectangle or Polyline. It would be great to have those shortcuts available to save some time when animating and make the presets more accurate. I'm thinking in the Tool Modifiers section, instead of Geometric Shape, maybe we could expand that into:

Geometric Tool Shape (what Geometric Shape does now, no dash to indicate it's different than the others)
Geometric Tool - Rectangle
Geometric Tool - Circle
Geometric Tool - Ellipse
Geometric Tool - Line
Geometric Tool - Polyline
Geometric Tool - Arc
Geometric Tool - Polygon

**Comment by artisteacher** [comment]
In case you are not aware, you can use the shortcut for the geometric shape to cycle through the different shapes - as long as in Preferences -> Tools, you select "Cycle through the available options" in the dropdown shortcuts option.

Personally, rather than having individual shortcuts for each shape, I'd love to be able to use the Geometric tool's shortcut to cycle through the shape options. Pressing G the first time would make the geometric tool active. Pressing G when the geometric tool is active would cycle through the shapes. Just one shortcut to remember and no additional shortcuts would need to be set. It could be handy for other tools as well.

**Comment by MrBlockCat** [comment]
Yeah, I’d noticed the Geometric Shape shortcut and that it cycles shapes. I like the idea of merging that shortcut with the one to switch to the Geometric Tool how you said! I think as an option, though, it would be nice to also be able to switch shapes using their own keyboard shortcuts, to save time instead of having to cycle if you prefer that (as I personally would). To combine the best of both ideas, maybe we could have:

In Tool Modifiers:
Geometric Tool - Rectangle
Geometric Tool - Circle
Geometric Tool - Ellipse
Geometric Tool - Line
Geometric Tool - Polyline
Geometric Tool - Arc
Geometric Tool - Polygon

And in Tools:
Geometric Tool (Switches to Geometric Tool when pressed once, if pressed and you’re already in Geometric Tool it starts cycling shapes)

And the Tool Modifiers > Geometric Shape shortcut could be removed since it’s merged with Tools > Geometric Tool

**Comment by RodneyBaker** [comment]
A slight contrarian aside... and going off topic...

While I'm all for processes having the capability of being assigned to a hotkey I wouldn't want these particular options (that of each Geo shape having a hotkey) to have an assigned hotkey combination by default.  Hotkey combinations are in short supply as it is and this type of assignment should be customizable but not take on a priority of hotkeys over other processes.

Hopefully in the coming year we can find a champion (or two or three) that is able/willing to do a deep dive into how OT assigns hotkeys and recommend a path forward.  A primary obstacle being that new processes arrive ever day with new development but there is a limit to the number of hotkeys that can be assigned.  There are many directions we could take to include allowing hotkey assignments to be more context aware (ex:  allowing hotkey ini data to be exchanged on the fly) to activation of levels of refinement by invoking one hotkey in order to get to a deeper set of hotkey assignments.  Personally I like the idea of some form of context awareness where the tools are smart enough to do different things depending on the tool/workflow context.  To dive more deeply here we'd likely need to research best practices and then propose and trial recommendations.  A related question however; how to get it done without creating a monster.

One thing seems fairly clear going forward; to the greatest extent possible processes should be exposed so that hotkey assignments can be assigned to them.  Then perhaps the focus an shift to the user who can use whatever they have at their disposal to propagate their desired assignments.

**Comment by MrBlockCat** [comment]
Closing with #3213, thanks again @pojienie!
