### ISSUE TITLE
Multi-frame create blank drawing glitch

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3208]
I hope Rodney finds this a better name for this issue. 

### Screenshot or Video Reference

![ezgif-2-2597570430f0](https://user-images.githubusercontent.com/25724133/78240197-588b1a00-74e7-11ea-82c1-0792055b8bd5.gif)

![ezgif-2-44fe33d82b9c](https://user-images.githubusercontent.com/25724133/78240203-5c1ea100-74e7-11ea-8f37-9c04f91a6bad.gif)

### System Information
* **OpenToonz Version**: latest
* **Operating System**:  win 8.1

**Comment by artisteacher** [comment]
What about "Multi-frame create blank drawing glitch"

**Comment by RodneyBaker** [comment]
I'll use this as an opportunity to suggest how users can help others resolve their issues from my perspective.  I can't speak for others in this regard.  Seasoned reporters like @beeheemooth already know the value of a good report.  :)

I'm not as concerned with title as I am with the actual report although the title is important especially when trying to locate it later via a search.  If the title includes the primary issue at hand it will also be better categorized.

Video is a great way to demonstrate a problem or display an approach/workflow.
Vidoe that clearly demonstrates the problem is even better.
Some users are not as skilled as others in this regard and the video may play too fast or too slow and therefore not clearly communicate the issue.
A good pace for a video is one where a voice might walk us through the steps so we don't miss anything important.
If watching the video reminds us of a race or requires frame by frame to see what is deemed most important then it will likely be overlooked.
Frame by framing of a video is usually done to catch something the presenter didn't know... little evidences hidden by the user that hint at the causes that effected the outcome.

In the end... the onus in on the reporter to clearly title and demonstrate the issue.
Failing that the report may be harder to understand and will take longer to resolve.

The old adage applies, "Help me, help you."  :)

A fun exercise might be to examine submitted reports of the past and determine how they were presented and how they were resolved.  Were the reports clear and concise?  Did they demonstrate the problem in a way that invited others to examine the problem? Were those trying to resolve the issue given good tools to understand the problem?  Did they use those tools?

Here is a link to @beeheemooth's reports (both open and closed).  Examine them for clarity, directness and to see how they were designed to be resolved,  In what ways do they communicate clearly?  In what ways might they be improved?  How can we better help each other in our effort to improve Opentoonz allowing for the fact that the process will never be perfect?

@beeheemooth's reports:  https://github.com/opentoonz/opentoonz/issues/created_by/beeheemooth

**Comment by RattusaurusRex** [comment]
Similar experience - the white drawings appeared after I used 'Insert', 'D' to create a new frame.  Opentoonz was very laggy while the white drawings were displayed on screen, but returned to normal when they weren't visible.

![whiteframes](https://user-images.githubusercontent.com/60277069/80894503-55bf4880-8c90-11ea-8e13-0f206c2780f7.gif)

**Comment by openanim** [comment]
That seems to be fixed.

**Comment by beeheemooth** [comment]
Indeed, I just checked - it's fixed. But I didn't understand which PR the bug was fixed in. Is this a bug fix from Tahoma?
My first test resulted in a crash, but no matter how much I tried to reproduce it again, I failed. If I succeed, I will open a new issue. I think this issue can be closed.

Thanks for the great job!
