### ISSUE TITLE
Difficulty Selecting Camera with Animate Tool

### ISSUE THREAD

**Issue by KaseyFarron** [opentoonz/opentoonz#3228]
### Issue Summary
It's difficult to select the camera from the drop down box when I'm using the animate tool, I had two cameras, trying to select one it instead changes to 'Col 1', I have to select it twice to make it selected.

### Screenshot or Video Reference
![selectCam](https://user-images.githubusercontent.com/55353161/79068141-9bee4100-7cbc-11ea-92b7-43134d70966c.gif)

### Steps to Reproduce
1. Make a new level
2. Add a new camera
3. Change to Animate Tool
4. Select the table from the drop down
5. Now try to select camera 2... it changes to col 1 instead

### System Information
* **OpenToonz Version**: 1.4
* **Operating System**: Win
* **CPU**: i7-6700
* **Memory**: 16GB
* **Graphics Card**: Intel HD 530 iGPU

**Comment by RodneyBaker** [comment]
Can you share the information on the specific release of v1.4 found via Help menu > About Opentoonz?   That will bring up a popup menu like this:

![Help About Opentoonz](https://user-images.githubusercontent.com/2576432/79071289-95ea6700-7ca0-11ea-8141-184c26d2e7c1.png)

**Comment by KaseyFarron** [comment]
It's the release ver: ![image](https://user-images.githubusercontent.com/55353161/79071832-af59d600-7cd5-11ea-9a22-b2a96b6d5263.png)

**Comment by artisteacher** [comment]
I can't reproduce on macOS.

**Comment by RodneyBaker** [comment]
I cannot reproduce on Win 10 either.

A few thoughts/recommendations:
1)  Consider updating to a current nightly release as that may resolve the issue (Link:  https://github.com/opentoonz/opentoonz_nightlies/releases)

2) If using a pen double/triple check drivers and settings.
Drivers because the latest usually is the best.
Settings because the sensitivity could cause mis-clicks

3) A known issue with displays which could allow for missed clicks in target areas... and you have Intel Graphics which is known to be remedied by an available driver that is not recognized via the automated driver update... but is available via the driver download page (LINK:  https://www.intel.com/content/www/us/en/support/detect.html )

**Comment by KaseyFarron** [comment]
Sorry I can't use nightly builds as it takes ages for Windows to not see them as a security risk (until enough people download it) and I don't like doing it personally. I'm already using latest drivers and just using mouse for demonstration.

I can reproduce on another system, but with this spec.

**CPU:** AMD R9 3900X
**Memory:** 32GB
**GPU:** NVIDIA RTX 2070 S

It uses the same release ver. To reproduce make a new level, then in the schematic make a new camera, select animate tool and try select the cameras, I have to click them twice.

It's fine with just one camera.

**Comment by artisteacher** [comment]
Interesting - normally I just use 1 camera. I can reproduce with 2 cameras on macOS.

**Comment by jrhyme** [comment]
@KaseyFarron I have not heard such nonsense for a long time. Either I did not understand you, or turn off the antivirus while downloading. He can swear at everything, an old problem.

**Comment by pojienie** [comment]
I can reproduce this problem on Ubuntu 18.04. Nightly version f49503f713d2942e4afa418c2e1f3b56085ddd78

**Comment by WolfInABowl** [comment]
@KaseyFarron 
Do you have the same issue when selecting a camera via the camera column? If not, that would be somewhat of a workaround in the meantime.

**Comment by DarrenTAnims** [comment]
> Sorry I can't use nightly builds as it takes ages for Windows to not see them as a security risk (until enough people download it)

Just FYI, when you run the program for the first time, there's a link to click that tells it that you're happy with the download and you can then run it straight away without waiting.

**Comment by RodneyBaker** [comment]
I definitely recommend getting past the resistance to nightlies as it can be a year (or at least 6 months) between updates.  That's a long time to wait for a fix.

For those that can't get past the idea of using nightlies... there are other options that incorporate the same (or similar) updates as the nightlies.   For example, OTX:

https://github.com/manongjohn/OTX/releases

The short of it is... you want to resolve the issue and updating is a direct path to accomplishing this.

**Comment by jrhyme** [comment]
@RodneyBaker Just do not forget that nightly builds will still be more stable. I can give you a lot of examples. + manongjohn retired

**Comment by RodneyBaker** [comment]
@jrhyme Yes, the nightlies are by and large more stable than 'official' releases.**
There is no one that encourages use of the nightlies as stable releases more than me.
I'm thinking of making a rubber stamp so I can stamp that onto all the troubleshooting responses I create.  :)

**The one  exception to use of the nightlies as 'stable releases'is that as we approach an annual/semi annual release there is more of a chance for instability as things may slip through the cracks in the rush to solidify the release.  The good news there... if/when identified those problems tend to get quickly fixed and are immediately added into a nightly release.  In my estimation, the period of time where nighties are more vulnerable to instability is December and (if there is a mid term release) June.

**Comment by manongjohn** [comment]
Off topic...but...I'd be careful touting the nightles are _by and large more stable than official releases_.  That is not the norm. It might have been true in OT's early days since it was VERY unstable, but at some point, that will be reversed. 

Typically nightlies aren't more stable since any new code has the potential to introduce more bugs and crashes that are not easily revealed with our limited testing. Honestly, I crash just as much with nightlies as I do official.

The nightlies are good to use if there is something you are experiencing that is hindering your progress and it's fixed with a nightly, but you potentially have to deal with more bugs that were not there before. 

I think we should have separate release branches that we work against and merge into the master branch after a release. The master branch would stay untouched until the next release. This way we can create hotfixes for the official releases if we need to create an emergency fix for something that isn't discovered right away. Right now, if we had to do that, we'd be forced to include all new stuff that could potentially cause more problems for users.

FYI, I still release OTX monthly.

**Comment by konero** [comment]
☝️

**Comment by RodneyBaker** [comment]
Agree @manongjohn
Much doesn't need to be said and yet I find myself having to explain such minutia over and over again.  For fixes it is often the old 'you can lead a user to the fix but it doesn't mean they'll use it' chestnut.  Updating of drivers is a prime example of that.

Careful about promoting nightlies?  Certainly.
I tend to recommend what works and avoid what doesn't.
As do other users.

We could discuss the merits of how much more stable OTX is over the regular releases and the nightlies and that would be a useful datapoint to stress.  It is likely that I personally would call OTX my third option because I like to reduce variation to maximum degree possible.

The good news is that Opentoonz users have a number of ways forward to meet their needs. 

For the record while I do talk up use of OTX (and even other releases such as Morevna) I do so largely within the context of the users current need.   If the annual release works... if the nightlies... if OTX... etc. etc.   

In the end we want users that can think for themselves.
They can only do that if carefully considering the options available.

**Comment by jrhyme** [comment]
It was about night versions and OTX, or am I not understanding something?!!OTX- Not an official version.

**Comment by artisteacher** [comment]
OTX usually gets new fixes/features before the nightly builds so it's expected that it's a bit less stable.

Getting back on topic, when multiple cameras exist, you have to click twice to select them in the animate tool options.

**Comment by jrhyme** [comment]
@artisteacher At least someone understands me)

**Comment by gab3d** [comment]
I can also confirm the problem on Windows 10 laptop, Intel CPU, Radeon GPU.

**Comment by RodneyBaker** [comment]
This issue should be reviewed in light of current UI adjustments.
I'm still not getting able to replicate the problem but I must assume others still can.

**Comment by KaseyFarron** [comment]
The bug still remains in the latest nightly build.

Make a new level, add a new camera, select animate tool, select the table, now try to select camera 2, it changes to col 1.

**Comment by RodneyBaker** [comment]
Yes, I can get this to occur.
Selecting a second time appears to be the current workaround.

Very curious why it fails on the first attempt but succeeds on the second...

**Comment by flurick** [comment]
Could it be that this is not a bug, but a feature?
This way you can switch the active camera (in the xsheet) and keep animating the same column..

toonz/sources/tnztools/tooloptions.cpp:983 (introduced in #2574)
