### ISSUE TITLE
(Discussion) Recommendations for OpenToonz new users

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3253]
Recently, I have seen an increase in user interest in OpenToonz. 
However, along with this, many new questions arise regarding the stability of the program. Most often, users cannot determine for what reason their program crashes or lags. It does not make sense to classify such questions since their nature can be completely different. Therefore, I want to propose the opposite approach, namely:

let's designate for users those conditions or factors under which OpenToonz will work stably with a high degree of probability, in other words, recommendations for using the program.

1. In which OS does the program work best?
2. In which version of this OS
3. Parameters of the video card, processor, memory
4. Drivers, which versions
5. Which tablet is best used
6. Things related to graphic performance (monitors, OpenGL, etc.)
7. Actions or processes in which there is a high probability of a program crash or drawings disappearing
8. What formats of import files are preferable for stable operation.
9. Technical recommendations for maintaining stable operation during the session.
10. Observations from personal experience.

(you can supplement the list with your items)

**Comment by MrBlockCat** [comment]
https://opentoonz.github.io/e/ Maybe that could involve an update/expansion to the “requirements to use it comfortably” (sounds like recommendations, I think?)

**Comment by RodneyBaker** [comment]
If this is going to move forward perhaps we could start simply by collecting data on what interested users are using for hardware etc.

@beeheemooth  Can you answer the questions you have listed to get things started?

**Comment by RodneyBaker** [comment]
Much of the following are elements of standard documentation:

- [ ] **In which OS does the program work best?**
The answer to this will largely depend on what OS the user is most familiar with and/or is currently using.  In order to maximize usefulness of data collected some form of benchmarking would be needed and ideally the benchmarking would be automated to the greated extent possible.

Perhaps a different way to ask this question would be:   How can Opentoonz operate most effectively on any given OS?

Then the follow up question becomes:
- [ ] In which version of each OS does Opentoonz perform the best?

The answer to this question should generally be "the latest release" although with some exception of added time to allow for new releases to have bugs squashed and optimizations implemented.

Perhaps here the value of knowing what OS and what OS version users are currently working with Opentoonz on would answer the question.  The assumption being that the user will gravitate toward the operating system and the specific release of that operating system that works best.
 
- [ ] **Parameters of the video card, processor, memory**
Similar to the above, the underlying question is a survey type question.  Namely, "What video card, processor and memory are currently in use.

- [ ] **Drivers, which versions**
In most (but not all) cases the latest driver is preferred so this is primarily a data point to remove variation in cases where users have failed to keep their drivers current.  Because the average user cannot be expected to know the importance of drivers nor how to update them collection of this data point is mostly useful for developers who can address driver issues downstream (in Opentoonz) and documentation/training where users can be pointed to various fixes and optimizations.

- [ ] **Which tablet is best used**
Here the underlying question is, "Which tablets are currently being used?"
The assumption being that the most successful tablet users will gravitate toward the tablet(s) that work best.Things related to graphic performance (monitors, OpenGL, etc.)

- [ ] **Actions or processes in which there is a high probability of a program crash or drawings disappearing**
This seems to be a question that can largely be answered by examining three types of workflow; 1) Optimized workflow 2) Normative Workflow 3) Suboptimal workflow
In the case of #2 this primarily follows the process of options being used 'as is' with no change from default settings.  This level of activity relates also to benchmarking in that much of the process being tested can be automated or done 'blindly'; that is to say without a specific target that drives customization and user led optimization.

Aside:  In general there are two types of actons/processes that will have a high probability of resulting in a crash and/or loss of data:  ingest and output operations.  In order to identify those for determination/probability of stable operations it would perhaps be ideal to identify all input and output operations and the forms (i.e. file formats) represented.

- [ ] **What formats of import files are preferable for stable operation.**
See above
In general it is good to reduce variation.
The preferred formats will largely depend on the user or studio and each format has it's pros and cons.  It has been stated that the TIF format is the preferred format for raster images as that is used internally.  The primary internal formats for Opentoonz are TLV (toonz raster) and PLI (vector).  When these three formats (TIF, TLV and PLI) are utilized users should expect the most stable operation.

Note that the above (TIF, TLV and PLI) are the primary operational formats.  While they also may be best for storage (on disk) they represent the middle ground between ingest and output operations where other formats are encountered.  The most likely format encountered for ingest operations would appear to be PNG and that is also the most likely to be output although personal preferences (and delivery constraints) will dictate.  

Aside:  I personally use the GIF format a lot because it is a self contained file that can be easily shared on the internet.  It is an example of a sub-optimal file format becomes optimal because it specifically targets a requirement; ability to _immediately_ share online with others.

- [ ] Technical recommendations for maintaining stable operation during the session.
I can't speak to 'technical recommendations' here as much as perhaps good workflow and habits.  These can run the gamut but also fall into the territory of personal preference.  For instance, some users don't like to rely on auto-save for a number of reasons to include increase of session performance, limiting distraction, control over saving of files, etc.  For others not relying on auto-save would not be an option.

Here a primary recommendation would again be to reduce variation and to set one's session up for maximum success.  Example:  Limit distractions by not opening other programs, browsing the internet and scheduling operating system upgrades during work sessions.


- [ ] Observations from personal experience.
The above are my primary observations from personal experience.

**Comment by RodneyBaker** [comment]
Not a lot of discussion on this subject thus far.
Will close but those interested are encouraged to share their information.

**Comment by artisteacher** [comment]
As far as image formats go - anything vector based is the least stable. SVG import has a lot of issues due to the convert process to PLI. Vector levels have historically had a larger tendency to cause crashes than the other level types. Users unfamiliar with vector approaches try to use sketchy styles or "paint in" fill areas with the brush. This leads to excessive number of control points which on computers with poor processing can have a major negative impact on performance.
