### ISSUE TITLE
How to zoom out of xsheet/timeline

### ISSUE THREAD

**Issue by PantherTeaLord** [opentoonz/opentoonz#3287]
Simply is there a way to zoom out of the xsheet. Like in a editing software when you put a long video in it and you zoom out to see the whole video in timeline and zoom in to edit small bits. 
Can i do this for the xsheet? 
Like right now i have a song in it and i want to be able to view the whole song throughout it instead of scrolling for ages or using the scroll handle.
I'm on 12 fps btw.

Idk if i can ask another small question but i struggle finding a direct answer to this one. Is there a way to add a frame on a column without it making a new level or it being attached to another frame on the same column.

**Comment by RodneyBaker** [comment]
> Is there a way to add a frame on a column without it making a new level or it being attached to another frame on the same column.

Easiest way I know is to expose the new frame in the original column and then simply drag it over into the desired column.  In this way the exposure will still be part of the original level but can be an additional layer over or under the other(s).  

Think of it in this way... we can create a really complex animation with layers, background, characters and effects all using images from the same level.

**Comment by artisteacher** [comment]
You can add a tiny bit of space vertically into the Xsheet by setting the column header layout to "Compact" instead of "Classic-Revised" in the Preferences under "Xsheet". The change updates the next time OT opens.

Otherwise, as @RodneyBaker said, the Timeline view is the way to go if you want to zoom in/out.
Depending on the length, it may not show the entire layer, but it should be improved.
<img width="131" alt="Screen Shot 2020-05-15 at 6 57 58 PM" src="https://user-images.githubusercontent.com/21159116/82102622-19530a00-96de-11ea-8ae5-7b86e56a6719.png">

> Is there a way to add a frame on a column without it making a new level or it being attached to another frame on the same column.

You should try turning off "Enable Auto-Stretch Frame" in Preferences under "Drawing".

**Comment by RodneyBaker** [comment]
Closing as the question(s) have been answered but please feel free to continue to discuss as necessary.

**Comment by PantherTeaLord** [comment]
Thank you! I didn't know about the timeline thing and that i can still draw in there, that helps me out alot!
Also turning off the auto stretch frame thing IS A LIFE SAVER OH MY GOD. 
THANK YOU. That was so annoying to draw a frame and have everything be filled in in between. 

(I commented this in another issue of mine but sorry for not closing sooner! I keep forgetting to check this website still cause i am smart. Thank you for the help, with my experience so far everyone has been really helpful and kind.)
