### ISSUE TITLE
Tape tool : segment eraser and freehand type 

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3367]
**Is your feature request related to a problem? Please describe**

I'm wondering if we could add the following options for the tape tool to help while close gaps and repair the strokes :

1. Eraser segment
2. Freehand type

Request to improve the workflow when the smooth option is used on small strokes segments. This sometimes gives the impression of using the segment eraser tool while playing with the value of the distance option.

the problem with the smooth option is that the workflow is limited to (very) small strokes and the smooth effect that can result on the lines is not always desirable.

And a freehand type similar to the available rectangular type will speed up the workflow with flexibility.

Tape tool is very usefull to repair strokes and closes gaps before coloration process and this request will allow to have a multi-purpose tape tool to quickly add / repair and delete strokes on the fly regardless of the size of the strokes.

**Describe the solution you'd like**

Segment option will give better result than smooth effect.
Freehand type more flexibility

![tape tool add segment  option](https://user-images.githubusercontent.com/29790512/85765048-09cfd380-b716-11ea-8dea-34a440882796.gif)

**Comment by RodneyBaker** [comment]
Although this request is better documented than most...
Tagging with 'Needs Info' mostly to chart a clear path forward.

At the risk of diluting this request I will recommend this might be a good place for a complete review of the Tape Tool to view this request with the broader scope of the entire tool set.  If the requested segment eraser and freehand type were added what else would be lacking in the Tape Tool?  What are it's current best practices and uses?  Is the Tape Tool easy to understand and use? 

Within the scope of this review we can then ensure the specifically requested features are considered.

Note:  The proposed review need not be added to this request but his is my suggestion to aid in moving it forward.

**Comment by openanim** [comment]
To make a point on this request...It's a request that is close to the cacani cleanup tool. With the aim of bringing together in one tool the combination of the eraser segment tool from OT and the tape tool when using it to add strokes (in end to line mode) so that the strokes that are overflowing are erased with the segment tool and the strokes that are not touching are applied with the tape tool in end to line mode, in order to make them touch the line they are meeting and then close gaps. Add a freehand mode for more flexibility and convenience.

Unfortunately the remove vector overflow command is not very reliable and does not add a line. I found it especially useful when I did cleanups with cacani on drawings with a lot of perspective lines.

I think it's a good idea to take a broader look at the OT features, for a more global and consistent use. Personally, I find the tape tool and in general the vector tools in OT to be powerful and easy to use compared to other software but that may be subjective. 

>  If the requested segment eraser and freehand type were added what else would be lacking in the Tape Tool?

Personally I think OT needs more editing tools that cross levels/columns in order to greatly speed up this kind of process. And ditto for the tape tool. In cacani there are some individual mode like only segment erase or only close gaps. In this side, i found Cacani is a great source of inspiration for many OT tools as many seem to be extensions, improved and sharing the same essence, same nature.
