### ISSUE TITLE
Software crashes when loading mesh from another scene

### ISSUE THREAD

**Issue by Inhumanity96** [opentoonz/opentoonz#3393]
**Describe the bug**
Whenever opentoonz file are sent to a new computer, and I'm trying to correct file path in the browser tab, the software always crashes when loading in a new mesh

**To Reproduce**
List steps to reproduce the behavior.
1. Create an opentoonz animation with mesh
2. Change the file paths of the original files
3. Try and correct this file paths in the Browser/ Levels settings, and change rooms to Basic room

**Expected behavior**
The app will crash

**Screenshots**

**Device Information:**
 - OS: Windows 7
 - OpenToonz Version: 1.3
 - GPU: intel
 - GPU Driver Version:

**Comment by RodneyBaker** [comment]
I see you are running Opentoonz version 1.3.
That's a pretty ancient release in comparison to newer releases.

If you can, download and try one of the many alternative releases, for example OTX... it's a portable release that doesn't even have to be installed.   Just download, extract the files and run.

https://github.com/manongjohn/OTX/releases

There have been so many fixes since v1.3 that I'm confident you'll see better results.

**Comment by Inhumanity96** [comment]
Thanks. I downloaded OTX 1.4 Windows 64 Bit. It works like a charm. But i would suggest a file scanning feature to correct broken links. It took me a while to make filepath adjustments manually
