### ISSUE TITLE
Stylus Jitter

### ISSUE THREAD

**Issue by KaonashiV** [opentoonz/opentoonz#3399]
**Describe the bug**
Pen location jitter after a minute or so of usage. My lines start stylus cursor jumps to a different location than where I am drawing.

**To Reproduce**
List steps to reproduce the behavior.
1. Open new scene
2. New Rastor level
3. Begin drawing
4. After a minute, cursor jumps to the left and back of current location while drawing

**Expected behavior**
Line should be straight and cursor should not jump to a different location than where the stylus is

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: 1.4
 - GPU: Nvidia GTX 1080
 - GPU Driver Version: 451.67

**Comment by RodneyBaker** [comment]
Any update on status @KaonashiV?
Are you still experiencing the problem with your stylus?

If so, it reads to me as similar to other issues that were resolved by updating drivers.
In your case I would double check both your graphics card and... especially... the drivers for the stylus.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@KaonashiV Please let us know if you are still experiencing this issue.

Also, if you are using more than one monitor/screen there is a known problem in some cases that is resolved by having the screens be duplicates of each other rather than extensions.  This might also be addressed via updated graphics drivers.
