### ISSUE TITLE
Rare glitch where one of the frames are shortened/missing

### ISSUE THREAD

**Issue by Cherryrin** [opentoonz/opentoonz#3416]
![Screen Shot 2020-07-25 at 22 14 22](https://user-images.githubusercontent.com/67905605/88466445-3b2df180-cec4-11ea-8024-c52752c38df5.png)
This bug report is probably the last of the trio, and this only happened to me once-with a huge project I was about to work on that includes audio.this glitch happened when I wanted to insert another frame between two and when I played back the animation, it seemed to not link up with the audio(Oh yeah, after I inserted that frame, thats when the draft didn't line up).Another thing to add is when I fill empty cells a line appears on the canvas
![Screen Shot 2020-07-25 at 22 18 21](https://user-images.githubusercontent.com/67905605/88466500-c60eec00-cec4-11ea-83a8-f8e90406c81c.png)
I deleted it but ou can see that it only lasts one frame which is where I right-clicked.I have thought of what could be doing this but I honestly think there could be something wrong with the/my right-clicking mechanic on opentoonz.Sometimes it works normally and sometimes I get unessasary lines.Maybe this will stop when I get a drawing tablet as Opentoonz is not used too 'mice'.(Opentoonz 1.4,MacOSs Sierra 10.13.6,I use a bluetooth mouse)

**Comment by Cherryrin** [comment]
Oh yeah, after I inserted that frame, thats when the draft didn't line up

**Comment by artisteacher** [comment]
I'm not sure exactly what the problem is here. You inserted a new frame, changed your mind, deleted it, and a missing (red) frame was left behind?

Did you delete the frame from the Level Strip by chance? The Level Strip displays all of the images in a level - whether or not they are all exposed in the scene. Deleting from the Level Strip changes the image sequence/level but doesn't actually remove the frame from the Timeline or Xsheet. The exposure is still there but the drawing is missing(deleted) and so the number displays as red.

If something else is going on, we'll need more information about your process. When submitting a bug report, try to be as clear and concise as possible. If there are specific steps that always result in the same issue, list them. If something just happened one time and you can't reproduce it, it's hard to fix.

> I honestly think there could be something wrong with the/my right-clicking mechanic on opentoonz.Sometimes it works normally and sometimes I get unessasary lines.

That's actually worse on a tablet in macOS! It's improved from a few years ago though. I do occasionally get an unnecessary line (on Catalina & Mojave) but it's not too frequent.

**Comment by Cherryrin** [comment]
Sorry for not being clear enough, since this is the first time it happened.What I meant to say was that when I inserted a frame between two I maybe made that frame longer so it messed up everything else,I am trying to fix it so this could just be me not understanding the basics of this program well enough.
