### ISSUE TITLE
Taking into account key frames with the inbetween command.

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3470]
**Is your feature request related to a problem? Please describe**

It would be a big step for the inbetweener to differentiate frames between them. 
It would allow several "sections" of a row of frames to be inbetweened at once and a better way to  identify the timings from the level strip. Time saving and convenience of use.

**Describe the solution you'd like**
A sugestion could be to be able to tint or mark the frames you want to use as keys and that the inbetween command interpret it as the start or end of a frame range.

![Inbetweener_keys](https://user-images.githubusercontent.com/29790512/92326798-1a28f680-f055-11ea-8c9f-861ac3d397c7.png)

**Comment by beeheemooth** [comment]
Good proposition! I constantly use memos of different colors in order to indicate in which frames which interpolations were applied (for me: yellow - linear, orange - Ease In e.t.c.) But when you change the timing on Xsheet, the memos do not move along with the frames, they need to be rearranged manually. You can also use Note Level, or the usual empty keys (Animate Tool), but this is also not ideal. 
The ability to mark frames in the Level Strip would be useful not only for inbetweens, but also for quickly finding the frames you want to place from the Level Strip on the Xsheet.

**Comment by openanim** [comment]
I close it as it's also covered by#4466.
