### ISSUE TITLE
ffmpeg not found

### ISSUE THREAD

**Issue by salma-999** [opentoonz/opentoonz#3521]
**Describe the bug**
opentoonz cant find the the ffmpeg so I cant save my vid into mb4 what can I do ??

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
ubuntu 18.04 Opentoonz morevna ver. 1.4.0

**Comment by manongjohn** [comment]
If you are using a snap version, it will not work due to snap security and so far there is no way to fix that.

Either
1. Compile from source
2. Download and install OT from Morevna site.
3. Download and use OTX (it's an AppImage)
4. Download and use Tahoma2D (it's an AppImage that ships with ffmpeg)

**Comment by ibrahimalici** [comment]
Hi. I have same problem on windows... I download many versions both of "builds from gyan.dev" and "builds by BtbN". Directory path ok but result Ffmpeg not found... Windows 10, Amd Ryzen 5 3600 cpu...

**Comment by RodneyBaker** [comment]
Please reference:  #3688
