### ISSUE TITLE
undo fails on rasters levels

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3571]
**Describe the bug**
If you cut/copy a part of canvas on a raster level or toonz raster level, and you past it directly on a empty cell and paste again for the image, undo will fail for the session.

**To Reproduce**
List steps to reproduce the behavior.
1.import or create a raster image by using new level command (both levels failed)
2.cut or copy a part of raster canvas
3.paste on empty cell to create a cell
4.paste again to insert the image
5.undo

**Comment by RattusaurusRex** [comment]
This works fine for me with the latest nightly.  What version of OpenToonz are you using?

**Comment by openanim** [comment]
@RattusaurusRex thanks for checking i am using the 10/22 version so this may be fixed. I'll check back as soon as I can install the last NB.

**Comment by openanim** [comment]
It seems that the problem is still there with the last NB (10/27). However, sometimes the steps with the raster level does not always occur. But with the raster toonz level it seems to happen every time.

![undo fails rasters levels](https://user-images.githubusercontent.com/29790512/97467851-e7a8c500-1944-11eb-9de7-62b0589a90d4.gif)

**Comment by RattusaurusRex** [comment]
Okay, so in order to reproduce this, you need to use the New Level commands: 
![undo2](https://user-images.githubusercontent.com/60277069/97491366-49eecf00-191f-11eb-890c-801b6f071fa7.gif)

It doesn't do this if you create a level through auto-creation:
![undo](https://user-images.githubusercontent.com/60277069/97489820-45c1b200-191d-11eb-85f6-d9a357c9a79b.gif)

**Comment by openanim** [comment]
Thanks for the catch. I updated the steps about that.
