### ISSUE TITLE
Hey, I accidentally deleted my canvas on basics and don't know what to do.

### ISSUE THREAD

**Issue by CanIHaveHelp** [opentoonz/opentoonz#3580]
I was working on my project, and accidentally dragged the box that the canvas was in. Ok, I thought. Easy fix, right? I thought if I saved my project and left OpenToonz it would go back to normal. No beans. So, I deleted the thing and thought that would fix it. It disappeared, then I saved and left. I got back into it with no canvas. That's where I am right now not knowing what to do.

**Comment by artisteacher** [comment]
You can add a "Viewer" back in from the Windows menu. You can also reset the default rooms (Windows -> Workspace -> Reset to Default Rooms"). After restarting OT, your workspace will be back to normal. You might want to lock the workspace afterwards, so that you don't accidentally pull the windows out (Window -> Workspace -> Lock Room Panes).

**Comment by CanIHaveHelp** [comment]
Thank you!
