### ISSUE TITLE
error: Plastic tool don't work after rendering

### ISSUE THREAD

**Issue by bosko2020** [opentoonz/opentoonz#3598]
after using Plastic tool the program crashes during rendering

**Comment by RodneyBaker** [comment]
Do you have a project file you can share that displays the problem?

**Comment by bosko2020** [comment]
> Do you have a project file you can share that displays the problem?
> 
> There are a number of issues related to Plastic Tool that still must be addressed.
> Not a lot of development has occurred with Plastic Tool as of yet but perhaps in 2021 someone will take on that task.
> 
> https://github.com/opentoonz/opentoonz/issues?q=plastic
> 
> This is likely a duplicate report of some of those other rendering/crash reports but we'll keep it open for now pending additional investigation. All the more reason to share project files for testing for those that can.


I don't know how to send a tnz file here, so I changed its name to zip. To view it, change the name back to tnz
[Human animation.zip](https://github.com/opentoonz/opentoonz/files/5579312/Human.animation.zip)

**Comment by bosko2020** [comment]
> Do you have a project file you can share that displays the problem?
> 
> There are a number of issues related to Plastic Tool that still must be addressed.
> Not a lot of development has occurred with Plastic Tool as of yet but perhaps in 2021 someone will take on that task.
> 
> https://github.com/opentoonz/opentoonz/issues?q=plastic
> 
> This is likely a duplicate report of some of those other rendering/crash reports but we'll keep it open for now pending additional investigation. All the more reason to share project files for testing for those that can.

This tool may have a frame limitation. It can't handle more than 110-150 frames

**Comment by RodneyBaker** [comment]
> This tool may have a frame limitation. It can't handle more than 110-150 frames

Your plastic mesh is only exposed until frame 150,
I'm not sure if that is intentional.

The mesh and images are missing from the tnz file but perhaps not necessary to examine what is going on here.
I'll give the scene file a look and see if anything appears out of order.

**Comment by bosko2020** [comment]
> > This tool may have a frame limitation. It can't handle more than 110-150 frames
> 
> Your plastic mesh is only exposed until frame 150,
> I'm not sure if that is intentional.
> 
> The mesh and images are missing from the tnz file but perhaps not necessary to examine what is going on here.
> I'll give the scene file a look and see if anything appears out of order.

Yes, the image mesh is missing for some reason. In the settings, I removed the limitation in frames, so the problem is in the Plastic tool

**Comment by RodneyBaker** [comment]
When I replace your image and mesh I don't have any issue except a (seemingly unrelated) ffmpeg timeout.
When not using ffmpeg I can then render out the animation... using your plastic rig.

I think we need to consider what release of Opentoonz you are using (and while not essential right now knowing your system specs would be useful).

I currently cannot open my 'fixed' copy of your scene because when I went to remove your image column it crashed the program.  As such it would be good to know if you are using vector or raster images there.

Also, can you describe the process by which you are rendering?

**Comment by RodneyBaker** [comment]
The only real error I get currently is (during render):

![image](https://user-images.githubusercontent.com/2576432/99902479-c016f500-2c83-11eb-9805-4161a4069f19.png)

**Comment by bosko2020** [comment]
> The only real error I get currently is (during render):
> 
> ![image](https://user-images.githubusercontent.com/2576432/99902479-c016f500-2c83-11eb-9805-4161a4069f19.png)

My version is Opentoonz 1.4 (Feb 1, 2020)
My OS: Windows 10
My Gpu: amd radeion r9 series 200
GPU Driver Version: No new drivers have been released for several years
1.Used a plastic tool in the painted picture
2.after finishing the work I pressed rendering in (mp4, avi, pdf, jpg)
3. the program crashed.

**Comment by bosko2020** [comment]
> The only real error I get currently is (during render):
> 
> ![image](https://user-images.githubusercontent.com/2576432/99902479-c016f500-2c83-11eb-9805-4161a4069f19.png)

You can get this error yourself. Use Plastic Tool on any picture up to 150 frames and the program will crash

**Comment by bosko2020** [comment]
You need to expose any movement of the object up to 150 frames and the program crashed

I first noticed this on Opentoonz 1.3, so I installed Opentoonz 1.4, but nothing changed.

**Comment by RodneyBaker** [comment]
> You can get this error yourself. Use Plastic Tool on any picture up to 150 frames and the program will crash

 That is rather the problem here in troubleshooting because that doesn't occur for me.
Also, after repairing, I extended your scene to 201 frames and it rendered to gif animation etc. without problem.

The very first thing you should do is update to the latest nightly as:
- You are dealing with keyframes and there is a nasty bug in the January 2020 release that was fixed in May timeframe (with additional fixes later still)
- Plastic mesh should still likely be troublesome but at least you won't have additional problems to deal with

You can find the nightly releases here:   https://github.com/opentoonz/opentoonz_nightlies/releases

Aside:  After updating my local copy of ffmpeg I no longer get the timeout so I will recommend updating your ffmpeg as well... especially as the distributor of ffmpeg builds has changed recently.  While other builds might work fine also I'm currently testing this one:  https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2020-11-21-12-29/ffmpeg-N-99959-g09f1d15ae8-win64-gpl.zip

(Note:   The Tahoma2D fork of Opentoonz comes with its own build version of ffmpeg if that is an option)

**Comment by RodneyBaker** [comment]
![RigCheck2](https://user-images.githubusercontent.com/2576432/99903453-299a0200-2c8a-11eb-8c68-3afab31ac81c.gif)

I took a screen cap of your rig and applied that back to the motion and rendered.
This was the result.

**Comment by RodneyBaker** [comment]
Interestingly, in continuing to investigate I keep running into a problem with Plastic meshes and Pegs.
Not sure if/how that might relate to this.

**Comment by bosko2020** [comment]
> Aside: After updating my local copy of ffmpeg I no longer get the timeout so I will recommend updating your ffmpeg as well... especially as the distributor of ffmpeg builds has changed recently. While other builds might work fine also I'm currently testing this one

Ok, thank you very much. I'll upgrade to nightly version and try change ffmpeg build.
Hope it helps.

**Comment by bosko2020** [comment]
> > You can get this error yourself. Use Plastic Tool on any picture up to 150 frames and the program will crash
> 
> That is rather the problem here in troubleshooting because that doesn't occur for me.
> Also, after repairing, I extended your scene to 201 frames and it rendered to gif animation etc. without problem.
> 
> The very first thing you should do is update to the latest nightly as:
> 
> * You are dealing with keyframes and there is a nasty bug in the January 2020 release that was fixed in May timeframe (with additional fixes later still)
> * Plastic mesh should still likely be troublesome but at least you won't have additional problems to deal with
> 
> You can find the nightly releases here: https://github.com/opentoonz/opentoonz_nightlies/releases
> 
> Aside: After updating my local copy of ffmpeg I no longer get the timeout so I will recommend updating your ffmpeg as well... especially as the distributor of ffmpeg builds has changed recently. While other builds might work fine also I'm currently testing this one: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2020-11-21-12-29/ffmpeg-N-99959-g09f1d15ae8-win64-gpl.zip
> 
> (Note: The Tahoma2D fork of Opentoonz comes with its own build version of ffmpeg if that is an option)

I installed nightly version and changed ffmpeg build. It didn't help, nothing changed

**Comment by bosko2020** [comment]
> Interestingly, in continuing to investigate I keep running into a problem with Plastic meshes and Pegs.
> Not sure if/how that might relate to this.

This tool will not work now. But I hope that I was able to help solve the problem. See you

**Comment by bosko2020** [comment]
Installed tahoma2d there is the same error

**Comment by artisteacher** [comment]
OpenToonz rendering has been unstable for a long time with more processing heavy scenes. So using the plastic tool, skeleton tool, FX, and maybe even sub-xsheets can make a scene more likely to crash when rendering. I think this is hard to fix since something that crashes every time during render on one device, could render without issue on another with better specs.

What I do as a workaround when I run into this issue is render as an image sequence first (png or tiff or etc.). Then, when there is a crash, I reopen the scene, change the start frame in output settings, and start rendering again from wherever the image sequence left off. Sometimes there'll be specific frames that always crashes. I'll skip them, render the remaining sequence, and then render those problem frames individually. Once the entire sequence has rendered, I'll load it into a new scene and render to mp4 or gif without issue.

**Comment by bosko2020** [comment]
> OpenToonz rendering has been unstable for a long time with more processing heavy scenes. So using the plastic tool, skeleton tool, FX, and maybe even sub-xsheets can make a scene more likely to crash when rendering. I think this is hard to fix since something that crashes every time during render on one device, could render without issue on another with better specs.
> 
> What I do as a workaround when I run into this issue is render as an image sequence first (png or tiff or etc.). Then, when there is a crash, I reopen the scene, change the start frame in output settings, and start rendering again from wherever the image sequence left off. Sometimes there'll be specific frames that always crashes. I'll skip them, render the remaining sequence, and then render those problem frames individually. Once the entire sequence has rendered, I'll load it into a new scene and render to mp4 or gif without issue.

This is interesting, this method might help. Gotta try, thanks

**Comment by bosko2020** [comment]
> Interestingly, in continuing to investigate I keep running into a problem with Plastic meshes and Pegs.
> Not sure if/how that might relate to this.

Hello, I found a solution to the problem. Opentoonz can render the Plastic tool in tif format, but cannot render in mp4 and avi format. You can first render in tif, and then load them into the program in the form of pictures and render to mp4. In principle, it is not so difficult and gives unlimited possibilities to use the Plastic tool

**Comment by Didpk** [comment]
I had this problem as well. Somehow by just adding a few keyframes it needed 29 gb of ram. Thats how much I increased virtual memory and still barely made it. Before i added those keyframes it needed 10x less ram. 
Try looking in Task manager's Performance tab while it is rendering.

**Comment by RodneyBaker** [comment]
@bosko2020  Will close this report as it is now a year old and largely resolved.
There are some known issues with Plastic tool and vectors which many users have resolved by resorting to Task Rendering.
Please let us know if you are still encountering problems.
