### ISSUE TITLE
Red Frames After Crash

### ISSUE THREAD

**Issue by roamingsonder** [opentoonz/opentoonz#3602]
When I clicked 'Save All' my Opentoonz crashed, when I reopened it one of my columns was red, but only the level labelled C. Nothing I've done has been able to fix the issue, because in the folder labelled drawings it is still there. When I imported into a new scene, they were no longer red but they were still blank, unnumbered and I was unable to draw on them, despite them being a raster level. 

My OS build is 19041.630
Windows 10. 

I know my way around Windows decently, but I am at a loss as to what to do. Is there a way to recover my levels?

**Comment by RodneyBaker** [comment]
Closing as this is a known issue related to v1.4 that was fixed.
Discussion can continue here on the specific issue and how to navigate the problem.
The short answer being to make sure to use a recent nightly release in order to avoid the related keyframe problem that corrupts scene files.

Nightly releases can be located here:  
https://github.com/opentoonz/opentoonz_nightlies/releases

@roamingsonder The problem with missing references may persist until the scene file is either fixed or recreated.
