### ISSUE TITLE
Crash (and freezing) when creating new Frame 

### ISSUE THREAD

**Issue by idkte23** [opentoonz/opentoonz#3613]
**Describe the bug**
OpenToonz starts freezing and then crashes, when drawing the inbetween onto a new Frame

**To Reproduce**

_1.Create a new Level_
_2.Draw 2 Keyframes on 2 seperate frames (every keyframe lasts 2 frames)_
![image](https://user-images.githubusercontent.com/75330995/100783852-9cd01080-340e-11eb-9fc0-220e984cd8b4.png)
![image](https://user-images.githubusercontent.com/75330995/100783883-a6597880-340e-11eb-914b-fb4261c1def5.png)

_3. Draw the inbetween on Frame 2 ( which overwrites the copy of Frame 1), and also use Ctrl+Z_
![image](https://user-images.githubusercontent.com/75330995/100783996-d0129f80-340e-11eb-80d5-9c3eabb1786a.png)
![image](https://user-images.githubusercontent.com/75330995/100784040-db65cb00-340e-11eb-80ef-73af536ebb60.png)

_5. Watch as the Program freezes for a moment and then crash without any Messages or notifications_

**Expected behavior**
Inbetween Frame should be drawn as often as needed whilst also using Ctrl+Z/Undo, without the program Crashing

**Device Information:**
 - OS: Windows 10 Pro 1909
 - OpenToonz Version: Nightly Dec 1 2020 10:18:55 as well as the last Release (Feb 1)
 - GPU: GTX 1050Ti
 - CPU: Ryzen 7 3700x
 - RAM: 16GB

**Comment by RodneyBaker** [comment]
I'm unable to reproduce the problem (either freeze or crash) here.
There may be something I'm missing though.
I do note you mention using Control Z and that your screenshot displays a field guide.
Attempting to use those doesn't appear to make a difference here.
The Control Z is (to me) a suspect worth investigating because of other issues occasionally reported with Undo.

The only other thing from your report that stands out is the Ryzen 7 3700x... something I don't have so cannot use in testing/verification of the problem.

The steps you outline are common enough that I would think others would have the problem too so perhaps others may be able to verify.

**Comment by idkte23** [comment]
Hmm maybe it has sth to do with my Hardware, ive also had the same problem in other scenes before

I've tried to upload a Video of the things i did, but i can't upload it here on git 

**So heres a link to the steps i did to get the crash and freeze**
https://streamable.com/0yypqw

**Comment by RodneyBaker** [comment]
Good news! (I think)
I am able to produce a crash after much drawing and undoing where it seems that I finally do an undo and a draw at the same time.  I really have to work at it though.
There are three things I specifically noted that I was initially unsure of in that your video helped to validate as far as setup... which may or may not relate to the problem:

1.  Field Guide is on
2.  Viewer is zoomed in
3.  There are two onion skin markers before the active frame and one after (this therefore makes the first onion skin marker move out of xsheet before frame 1)
4.  Multiple undos and draws in fairly quick succession

It is only this last one that seems to make a difference for me although I do note that just drawing and undoing quickly/simultaneously without field guide... zoomed in... and with onion skin does not produce a problem.

**Comment by idkte23** [comment]
You're welcome :)

The bug definetly has something to do with drawing on an existing Frame and thus overwriting it like so: 
![image](https://user-images.githubusercontent.com/75330995/100991516-5f28d000-3553-11eb-9e60-0c5ec4c887be.png)
![image](https://user-images.githubusercontent.com/75330995/100992106-102f6a80-3554-11eb-8eb4-d3efc56b5ebb.png)


In my experience the bug tends to occur less if i create a new Frame by clicking on the black and then draw:
![image](https://user-images.githubusercontent.com/75330995/100991972-e6764380-3553-11eb-894b-9dd50ed5c0b2.png)
![image](https://user-images.githubusercontent.com/75330995/100992016-f726b980-3553-11eb-87d5-43de8437098f.png)

**Comment by Jose-Moreno** [comment]
@RodneyBaker @idkte23 I managed to reproduce this fairly quickly under Windows 10 with both vector and raster levels. A few considerations.

1. The field guide is unnecessary
2. The 1st key to this issue is in the undo. It doesn't matter undoing many strokes, but rather the creation of the new drawing cel in the level
3. The 2nd key is in the onion skin, once I enabled that I got it to crash easily.

**Device Information**

**OS**: Windows 10 Pro 1909 (same as OP) // OS Build: 18363.1256
**OpenToonz Version**: Opentoonz 1.4(built on Jan 10 2021 10:16:59) https://github.com/opentoonz/opentoonz_nightlies/commit/fea3b63487f2f339b3cbcfa90776a59ec7d392c3
**GPU**: GTX 1050Ti (same as OP)
**CPU**: AMD FX-6300 (6 cores)
**RAM**: 16GB (same as OP)
