### ISSUE TITLE
Where is option to change bone pinned center?!

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#3616]
I was using an older version of OT and I decide to download nightly build just to check what is new. I was surprised to discover that option to change skeleton pinned center is gone! Only temporary pinned center is available! Guys am I crazy, is this just a bad dream or someone seriously took away this option from IK? Long time ago I even asked Mr. Iwasawa to create indicator in xsheet, to see on which keyframe pinned center is changed (visible as a blue square in xsheet, next to keyframe number). And of course he did it, because it sounded as a logical thing to have, and that option is right now useless cuz it's impossible to change pinned center.

Please tell me that I am wrong and that there is still an option to change pinned center for bones in IK mode.

**Comment by RodneyBaker** [comment]
Perhaps this is the report you opened before?

https://github.com/opentoonz/opentoonz/issues/2368

**Comment by psychoanima** [comment]
Hi Rodney,

Yes, my report was related to issue with pinned center, as described in my video, but now the situation is even more serious cuz someone completely removed the option to change pinned center. I just don't understand why it was removed completely? I understand if someone couldn't make it to work properly, but... Blah, I am disappointed.

**Comment by Efenstor** [comment]
Don't want to open a new issue as it's basically the same bug. In Linux, in the latest master I cannot change the pinned center. From the documentation it's supposed to be easily switched to any other object just by clicking on any orange circle in the Inverse Kinematics mode. I do click but nothing happens. And there is no "Reset Pinned Center" option in the context menu.

**Comment by gab3d** [comment]
When one of the developers removed the feature, some months ago, I instantly thought that would not be good because it was just hiding a problem, not solving it. But since I'm not personally using OT to animate with IK, I completely forgot about it.
Now, this issue seems to confirm that the "solution" of completely hiding/disabling that feature wasn't a clever one.

Also, something similar happened when I raised a malfunction in the Reset Center #2708 in path animation in OT (compared to the way in which the original Toonz feature worked), at that time someone suggested that as it wasn't working in the same way as the manual described it, the manual should be wrong, rather than trying to understand what the tool was planned for.
To this day that problem remains unsolved...

I bring this to the table, because I think sometimes (as developers) we should take more time to assure ourselves we really understand an existent feature, before making substantial changes, or completely remove it from the software.
In general, I think we should first target to fully restore the original feature functionality, if it isn't working as the manual says, and then if we have a better, more modern or powerful solution implement it. 🤔 

Just my 2 cents on this..

**Comment by psychoanima** [comment]
@Efenstor @gab3d I did some stress tests on IK + pinned center and I was able to find out what is happening and how to "prevent" bug with pinned center. You can see it in more details here https://github.com/opentoonz/opentoonz/issues/3617 However, you can't apply this method since pinned center is removed from latest version.

Based on test and errors I pointed in that video, I think that someone should dive into code and try to solve this issue.

**Comment by rabe01** [comment]
Hi,
without wanting to complain - but the topic is already a few months old - will there still be a solution?
That would be great.
