### ISSUE TITLE
How to prevent pinned center bone bug (Inverse Kinematics)

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#3617]
After many hours of experimenting and crashing things I found a solution, how to prevent well known bug with Inverse Kinematics and Pinned center

Please take a look:

https://1drv.ms/v/s!AtMv1SrHrjT3gZt3ZWF9IRoSE7GMRg?e=CzrWVr

**Comment by beeheemooth** [comment]
@psychoanima An interesting observation. But what if you want to change the pinned center again? I got a problem just when I tried to make a new pinned center - the previous keys stopped working adequately. By the way, which version are you using here?

**Comment by psychoanima** [comment]
@beeheemooth you can continue with the same technique as I described, it will work, but, two problems, at least on my rig:

1. at some point if you decide to pin again root bone in this chain, that bone will change pivot center and it will not rotate around pin, but around something, I have no idea what.

2. probably the biggest problem to me, if you decide to re-time animation, pinned center keyframes (blue squares) are not changing position accordingly with moved keyframes. They are staying in place. I am seeing 2 solutions for this:
- programmers to allow pinned center keyframes (blue squares in x-sheet) to be moved manually with mouse cursor, like with regular keyframes
- programmers to link frame position of pinned center with dedicated bone keyframe, so by moving bone keyframe pinned center keyframe will follow.

**Comment by RodneyBaker** [comment]
@psychoanima By way of review... and thanking you for the video description I'm uploading your MP4 to test githubs new  support for MP4 and MOV videos in reports.  Yay!

https://user-images.githubusercontent.com/2576432/103025679-e85e7180-4517-11eb-92bc-674e2c5b0372.mp4

**Comment by psychoanima** [comment]
Thanks @RodneyBaker I hope someone will take a look into solving this bug.

**Comment by rabe01** [comment]
Hi,
this thread is almost a year old - and unfortunately it seems, that IK and Pinned Center don't to work anymore. In any case, I can't change the Pinned Center any more - a shame.
Is there any positive development? It would be great.
Best regards

**Comment by rabe01** [comment]
Now the topic has had its "birthday" for a long time - no answer – and I still can't find a solution.
It is also described in the manual, "To set the skeleton Pinned Center: Click the center: it turns from an orange circle to a blue square to indicate it is pinned. ..."
I think this function is important – other tools can do that too.
So can we forget that – or maybe there will still be a big surprise?
Is there any information as to whether OpenToonz is still being developed?
It would be very nice.

**Comment by psychoanima** [comment]
I am also surprised that this option is disabled and now fully ignored by devs. Literally the most valuable option for ik animation in OT is disabled because it was giving some errors (in original Toonz if I remember works fine). Maybe more ppl need to stress out how important this is for ik animation and then someone might look at it again.

Shun Iwasawa even add an option for pinned bones in 2016, their kerframes to be visible on a timeline https://github.com/opentoonz/opentoonz/pull/369
Next step was supposed to be an option to move those pinned bones ketframes on a timeline, to get absolute control over them, but, as we know so far, instead of working on this someone decide to remove it completely.

**Comment by rabe01** [comment]
I've just read that version 1.6 is being worked on intensively (https://github.com/opentoonz/opentoonz/issues/4081) - and once again registered my wish for IK. Maybe that will help?
In any case, the development seems to be progressing further.
I hope for the best.

**Comment by psychoanima** [comment]
I have my doubts to be honest, but fingers crossed 🤞

**Comment by RodneyBaker** [comment]
It'd be great to see additional developers join the cause.
By developers I mean of all walks of life and all levels of experience and expertise.
As has been mentioned many fixes and enhancements might exist in Tahoma2D but without people interested in porting that code over to Opentoonz we have to take the slow road of waiting and learning.

I've personally looked at porting a few features and bug fixes and each time I've ran into some issue that has sent me back to the drawing board.  In time that will smooth out and I'll feel more comfortable personally porting things.

With regard to this specific issue... that of pinned center for inverse kinematics (as well as the motion path center) I agree those need to get reverted back to their original capability.  I'll guess the issue just haven't caught the attention of a developer   at this time or else it'd already be remedied.

Often things get fixed because someone just happens to be in the code in that area of interest and the subject of a bug or enhancement is fresh because others have shown interest.  That's a good reason to keep the discussion going... things that get used tend to get more development attention.

Stepping back for a moment to the subject of all levels of developers... we as users can do a lot to help those that will program the features and fixes we need.  Thoroughly documenting the problems/desired usage... posting repeatable steps/examples... identifying specific areas of code that have changed.  This last one perhaps is one of the most useful in my personal estimation as there is a lot of code to consider.

This does not mean that every user should be a programming developer but it might suggest that every user/studio needs to have a developer close at hand...  Someone to represent their requirements and give them feedback... even if that feedback is "Sorry, this isn't a high enough priority at this time but thanks for posting the issue."  At least then the end user will know the current status and can focus on workarounds to meet more immediate needs.

Regarding the number of developers available... I'm confident we'll see more rise to the challenge... and as a community I'd say we are slowing growing a few as they become more knowledgeable of the software and the source code beneath.  Other developers drop in as time and interest allow and we are always glad to see them.

One of the primary strengths of Opentoonz above and beyond many other similar programs is that it is opensource.  As a community we don't leverage that nearly enough.  

Concerning the doubts...  ;)
If we are imagining the future we might as well imagine positive outcomes right?
Don't pick the path where things break down and you end up defeated.
I'm not suggesting we lose all sense of reality here but rather to envision what success will look like and over time compare what we'd like to see to that of current reality.  That'll help give everyone a roadmap to follow with reasonable expectations and solutions to problems will follow that we all need.

One additional thing to consider...
Here where I live it's the dead of winter.  
Daily outlook tends toward cold and bleak.
But from what I hear... soon comes the spring.
Sometimes with older code there can be issues encountered that cannot be overcome in the short term given a longer term view of where that feature set needs to be.  Sometimes those short term fixes must be set aside for a season.
In general programmers are warned not to commit short term fixes that will only need to be changed yet again later.
Much has been said over the past few years about Opentoonz's need for better rigging options and that seems relevant.
A developer by nature will often go for the full fix and avoid incremental change that doesn't meet long term need.
Given that we still might be able to implement a short term fix/revert that restores previous capability.
Here we mostly just need to point out what specifically in the code needs to be changed.
This is where github itself helps us as a community leverage changes.

For those interested in this particular area of interest... let's dive deep.
When this problem gets fixed then we can move on to other things.  :)
