### ISSUE TITLE
Crash on Undo

### ISSUE THREAD

**Issue by Zeta-Buhler** [opentoonz/opentoonz#3618]
**Describe the bug**
While drawing and then undoing (Ctrl+Z) the program will randomly just close, no error dialog, no program not responding.

**To Reproduce**
List steps to reproduce the behavior.
1. Ctrl-Z multiple times, happens randomly

**Expected behavior**
Undo and don't close

**Device Information:**
 - OS:  Windows 10
 - OpenToonz Version: 1.4 Built Feb 2 2020
 - GPU: Nvidia GTX 1060 6GB
 - GPU Driver Version: 27.21.14.15167

**Comment by RodneyBaker** [comment]
@Zeta-Buhler Any information you can provide regarding your issue will help in resolving it.
At present there is not enough information to investigate the problem.

Repeatedly Undoing does not generally crash Opentoonz so we need to know what is different about your specific setup than others.

Thanks for any and all information you can provide.

**Comment by RodneyBaker** [comment]
I do note that you report using the v1.4 release from Feb 2020 which is almost a year old.
Many bug fixes, features and enhancements have been added to Opentoonz since then which makes installing... or at least testing with the nightly releases highly recommended.

Nightlies link:
https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by RodneyBaker** [comment]
Closing as likely resolved.
@Zeta-Buhler Please let us know if that is not the case.
