### ISSUE TITLE
Opentoonz Not saving

### ISSUE THREAD

**Issue by Godday1** [opentoonz/opentoonz#3664]
Hello, I installed opentoonz, but it does not save what do  I do
Below is what I get when I try to save a scene
![20201229_224403](https://user-images.githubusercontent.com/76754575/103317750-634ded80-4a2c-11eb-9695-0372ecea85f2.jpg)

**Comment by DarrenTAnims** [comment]
Firstly, it's trying to save the scene in your sandbox in: C:\opennew.  The sandbox is in your OpenToonz Stuff folder, which is normally at: C:\OpenToonz stuff
So I'm guessing you don't have the folder hierarchy for it to save the scene into.

Secondly, I'd strongly recommend creating a new project for each scene and to not use the sandbox. Just click the New Project button on the startup popup, enter a name, then create a scene and save it.

**Comment by Godday1** [comment]
DarrentTanims, I am one of your youtube subscriber,  thanks for replying, I tried doing this but still showing the same thing, I even Tried re installing it, still showing couldn't save, please I need help,  I really want to use this software 
![Uploading 1609317308616974743839305711879.jpg…]()

**Comment by RodneyBaker** [comment]
As Darren suggests...
The location you are set to save to ("c:\opennew") is not a standard location for a stuff file .
This suggests:
1) You didn't accept the defaults when Opentoonz is being installed. (With the default install you will get a stuff directory located at C:\Opentoonz stuff\)

2) You likely don't have full access to that directory location in order to be able to write files to it.
Check the permissions on the stuff directory and make sure it isn't set to read only (wherever you decide to locate it).
It is also possible... although seems a bit of a stretch... that your antivirus software is protecting that location.
I would expect you would see a different error message however (or simply none at all).

Until such a time as you resolve your conflicts you should accept the default settings.
Then branch out and customize.

Aside:  Darren is adverse to using the sandbox directory but I have never had any issues with that location and use it often.  Creating a project is however an excellent way to organize.

**Comment by DarrenTAnims** [comment]
"I tried doing this but still showing the same thing"
What exactly did you try. I suggested 2 things. Can you share your steps? And can you share a screenshot of your folder structure of where you're saving your scene?

**Comment by Godday1** [comment]
I just re installed living it in the original folder, then creating a new project, but still saying couldnt save,
Screen shot
![Uploading 20201230_212516.jpg…]()

**Comment by Godday1** [comment]
I am just confuse right now, Darren is there any way I could reach u on whatsapp, so I do show you what am passing through, please, I really like opentoonz, I have been learning from your channel, just wanted to try creating animation and saving them, but its not working, please

**Comment by DarrenTAnims** [comment]
Unfortunately, that's not a screenshot you shared. You can contact me easier on my Discord. The link is in most of my videos. There you can share screen shots, video recordings and chat.

**Comment by RodneyBaker** [comment]
Closing as this does not appear to be an issue directly related to Opentoonz.
Please feel free to continue troubleshooting here as necessary.

@Godday1 Hang in there.   We'll find the solution eventually!  
Please keep us posted.

**Comment by RodneyBaker** [comment]
It is possible this issue could be related to #3657 although there are some major differences in the details reported there.

**Comment by RodneyBaker** [comment]
Reopening as this appears to be a different issue.

**Comment by ErwinBr** [comment]
I'm having the save issue as well on 1.5 RC1.

![image](https://user-images.githubusercontent.com/46350573/113352730-f99bf300-933c-11eb-9577-86b293e76ba5.png)

Some remarks:
1. Saving new projects works, I'm only having the issue with already existing projects coming over from 1.4.
2. I'm on Mac OS 10.15 (Catalina)
3. Clearing Cache folder does not work

**Comment by RodneyBaker** [comment]
@Godday1 Are you still experiencing any save issues with current releases... especially the nightly releases?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
