### ISSUE TITLE
Imported images get cut upon being moved from where they spawn. Why?

### ISSUE THREAD

**Issue by Yogi861** [opentoonz/opentoonz#3666]
So when I drag and drop an image (PNG), it spawns inside a rectangle with the image's dimensions. If I move the image, the part that is outside said rectangle gets cut. Why does it do this? I cant animate like this.

Thank you to  anyone who answers! 

![bug 1](https://user-images.githubusercontent.com/67271571/103440795-54945000-4c51-11eb-82fe-294eea1e1f62.png)
![Bug2](https://user-images.githubusercontent.com/67271571/103440796-55c57d00-4c51-11eb-9879-cb3efc41e1ce.png)

**Comment by RodneyBaker** [comment]
When using the Selector Tool we are moving the pixels of the raster image.
In your case, you are moving the drawn image out of the image frame.
This is the nature of raster images in any program.

There are several things that we can do to avoid this cutting;
1) Increase the Canvas size
2) Use vector images instead of raster as they don't have that constraint
3) Use the Animate/Edit Tool to move the image rather than the Selection Tool.

#3 is what most would likely do in your case because the shape of your vehicle/tank is complete.
Now you just want to animate it across the scene.
#1 would be used if you wanted to add some additional detail to your tank that you might not have planned for in the first place.  Via Right Click menu there is an option to Adjust Canvas size.
#2 IS an option as well but even there we would want to animate the drawing using the Animate Tool rather than the Selection Tool in most cases.

The Animate Tool is the icon directly above the Selection Tool.

Take a little time to learn the tools available and you'll master the process in no time.

**Comment by Yogi861** [comment]
Thank you!
I actually watched 2 tutorials about it but they didn't have the issue I am having. I can't actually find the Adjust Canvas Size option, when I right click or anywhere else.
To get rid of the image frame should I convert it to vector? Or will it just not show in the animation itself?

**Comment by RodneyBaker** [comment]
Lots of folks prefer vector because of the benefits in resizing with a image format that is resolution independent.
I'd say use both raster and vector wherever you find them to be most useful.
(I'd solve your issue with raster first though so that you don't shy away from using raster format in the future)

The option to change canvas size appears when an image is exposed in the Xsheet/Timeline and then the user Right Clicks on the exposed cell.

![image](https://user-images.githubusercontent.com/2576432/103441756-97d0cd80-4c15-11eb-9309-0768a6be6596.png)

If you drew the image in another program and imported it then you might have some extra white around the vehicle that needs to be gotten rid of.  That can either be erased... or can be discarded if/when the image is converted to vector.

Note that converting to vector is not a precise process so your nice detail on the vehicle will likely need to be redrawn... the converter has no way of knowing that detail is suppose to be circles for instance so those likely will convert poorly.
If using vector I would suggest drawing the vehicle again to gain benefit from such tools as Geometry Tool.
Vector would be preferred in many cases.

**Comment by RodneyBaker** [comment]
Closing this report but please feel free to continue the discussion as necessary.
