### ISSUE TITLE
Corrupted scene 

### ISSUE THREAD

**Issue by madisomlok** [opentoonz/opentoonz#3753]
Hello, I don't know how to fix it when I try to open a certain scene there's an error message saying "There were problems loading the scene [scene name] Some files may be missing.
I really want to get back my project can anyone help?
i am using Nvidia GeForce and AMD Radeon RX
[clinicinsideroom.zip](https://github.com/opentoonz/opentoonz/files/6095624/clinicinsideroom.zip)

**Comment by RodneyBaker** [comment]
Sorry for your problems.
You have a corrupted scene file.
Here is a fixed version of your file that should remove the bad key frame entries in the file:


[clinicinsideroomFIX.zip](https://github.com/opentoonz/opentoonz/files/6095979/clinicinsideroomFIX.zip)

In order to prevent this bug from happening again it is important to use a version of Opentoonz that has the fix.
Link to nightly releases:  https://github.com/opentoonz/opentoonz_nightlies/releases

Closing as a duplicate.

**Comment by madisomlok** [comment]
Thank you so much
