### ISSUE TITLE
1.5rc Opentoonz fails to start

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#3799]
**Describe the bug**
the window shows loading process
then it does not lauch. maybe it closes itself?

**To Reproduce**
click the executable

**Device Information:**
 - OS: windows 10
 - OpenToonz Version: 1.5rc
 - GPU: amd radeon 550
 - GPU Driver Version: 20.1

**Comment by RodneyBaker** [comment]
Cannot reproduce a non-starting OT v1.5RC here.
Perhaps you got a bad installation/installer.

If you are able perhaps rename the Opentoonz stuff directory so the installer will place a new one with all new data.
Keep your old directory of course so that you can still know where your previous project files are located.

@shun-iwasawa Just a mostly unrelated note.  We may want to provide a provision for backing up the current stuff directory prior to installation as that will ensure only new data is used on a new installation.  The option could be off by default if there is concern that users won't realize where their old data was moved.  I personally think the backup stuff directory could be located inside the new Opentoonz stuff directory.  In this way this would nest older 'stuffs' inside one another so all files could still be found in the primary Opentooonz stuff directory.  This might take the form of a directory structure such as:

C:\Opentoonz stuff
C:\Opentoonz stuff\archives

**Comment by KaseyFarron** [comment]
Isn't there already an option for overwriting stuff folder settings without overwriting user settings in the installer? 🤔

**Comment by shun-iwasawa** [comment]
@age3rcm 
Did you uninstall the old version before installing V1.5RC?
If not, uninstall them and try installing again. The old version's binaries remaining in the executable folder may causes problem. You may need to remove the folder `C:\Program Files\OpenToonz` manually if the uninstaller fails to remove old version's binaries.

**Comment by age3rcm** [comment]
> @age3rcm
> Did you uninstall the old version before installing V1.5RC?
no, i just clicked the installer and installed

**Comment by RodneyBaker** [comment]
@KaseyFarron wrote:

> Isn't there already an option for overwriting stuff folder settings without overwriting user settings in the installer? 🤔

There are two related options but no direct route specifically that a user would take to get a 'clean install' that includes a fresh stuff directory.  The first option is a prompt of where to place the stuff directory.  This defaults to C:\Opentoonz stuff (for Windows users.   The second is an option to preserve personal settings.

These *almost* get the job done but don't quite go far enough when the ideal result is a clean install.
Users are more likely to accept the defaults than change them until they become more accustomed to the process.

It would not be sufficient to install the default stuff installation directory to a subdirectory archive would suffice BUT then the original data would still be in the default location and drive any copy of Opentoonz that referenced that default location (example:  Any portable copy of Opentoonz that doesn't have a portablestuff directory uses that default location)

Experience teaches us that users will not initially customize these locations and often won't later down the line either.
They'll just accept the defaults and expect that to be the proper optimization.

**Comment by age3rcm** [comment]
update:
unistalled opentoonz with "wise uninstaller" 
installed the 1.5rc and it launches the application

**Comment by shun-iwasawa** [comment]
I'll see if the installer can uninstall the old versions before installing.

**Comment by RodneyBaker** [comment]
Keeping this open, tagged as 'known issue' so that other users that experience the problem can find the solution.

**Comment by KaseyFarron** [comment]
I'm confused then, I was under the impression that the option in the installer preserves user data, and only overwrites things like default room layouts, help docs etc.

So projects data and profile data is not safe when updating? If that's the case shouldn't project root be in a different location? 😕

**Comment by RodneyBaker** [comment]
>  shouldn't project root be in a different location? 

There has been much talk of reorganizing preferences/user options.
Tahoma2D will likely implement that before OT so that should serve as a good proving ground.
In fact, I believe this is pending for the next release of T2D.
Other organizations of the stuff directory have been proposed as well.
