### ISSUE TITLE
Wacom Tablet Issues due to Qt 5.15 using Windows Ink

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#3817]
**Describe the bug**
Recent issues related to the tablet behavior (like #3812, #3813 and #3814) seems to be related.
Qt seems to have started to support Windows Ink [from 5.12](https://bugreports.qt.io/browse/QTBUG-60437).
Unlike WinTab API used in Qt 5.9 the tablet behaviors are different  and are (at least, from our viewpoint,) problematic:

- `mousePressEvent()` is not called when the stylus touches the tablet, but when it hover from the tablet.
- Every time you press modifier keys like Shift, Ctrl and Alt , a tooltip with the name of key appears next to the cursor. (annoying)

I'm planning to try some measures to resolve the problem.

1. The problem had already been [reported](https://bugreports.qt.io/browse/QTBUG-83218) and Qt [provided](https://codereview.qt-project.org/c/qt/qtbase/+/295623) a way to switch APIs between WinTab and Windows Ink from Qt v6.0. I'm try to see if I can build customized Qt 5.15 including this feature.
2. Try to add some event filter to correct the timing of event to behave the same as WinTab.
3. Or, go back to good-old Qt 5.9.x 

The change may need RC2 trial period for verification.
OT v1.5 release will be postponed until this problem will be resolved.

**Device Information:**
 - OS: Win10
 - OpenToonz Version: V1.5RC
 - Tablet : Wacom Intuos 5

**Comment by manongjohn** [comment]
I know 5.12 introduced some issues for Linux builds when I tried to use it in OTX. I was forced to drop it back to 5.9 which I knew worked fine but never went back to see if later versions fixed it.

It might be ok to leave 5.15 for macOS builds since that version seems to fix some macOS issues that have been lingering for a while now.

I would strongly suggest that instead of rushing a Windows fix/workaround which may open up many new issues, drop just the Windows version back to 5.9 and then work on switching to it early for 1.6 release. That will give yourself more time deal with any other 5.15 bugs and fixes that pop up while people are testing it.  Dropping back to 5.9 may require some minor adjustments for the icon spacing fixes that were put in.

My 2 cents.

**Comment by shun-iwasawa** [comment]
I tried building the [customized Qt5.15.2](https://github.com/shun-iwasawa/qtbase/releases/tag/v5.15.2_wintab) with cherry-picking the WinTab feature.
It seems to work nicely so far. I'll ask my colleagues for dogfooding and will also release the test version once it is prepared.

@manongjohn 
Thank you for the suggestion. It's a difficult decision that which version of Qt to use.
The support for Qt 5.9 LTS was already ended on May 2020 and prebuilt components for MSVC 2019 is not provided. 
I fully understand your concern that the self-customized Qt 5.15 may contain potential problems but I think it is worth a try in the RC period.
