### ISSUE TITLE
Geometry tool (Arc, MultiArc) graphic tablet - Linux

### ISSUE THREAD

**Issue by andeon** [opentoonz/opentoonz#3826]
**Describe the bug**

The arc and multiarc doesn't work correctly when drawing the lines and trying to adjust the angle with graphics tablet. I checked https://github.com/opentoonz/opentoonz/pull/3823 I also tried versions **Opentoonz 1.5RC**, **Opentoonz 1.4** and **Tahoma2d 1.1** and the bug was there, apparently recurring but nobody reported it.

_In versions 1.3 and 1.4 Morevna editions, the arc tool works, but these versions don't have multiarc no idea which builds Morevna is based on._

**To Reproduce**

1.With the graphics tablet just try to draw a line with Arc or MultiArc 

**Screenshots**

https://user-images.githubusercontent.com/11843239/112687574-6f442280-8e56-11eb-96b2-a4ac4148d27f.mp4

**Device Information:**
 - OS: Linux 64 bits (KDE Neon)
 - OpenToonz Version: https://github.com/opentoonz/opentoonz/pull/3823, Opentoonz 1.5RC, Opentoonz 1.4
 - GPU: Nvidia Geoforce 940MX
 - GPU Driver Version: 450.102.04
 - Graphics Tablet: Wacom Intuos Draw CTL490DW, Genius MousePen 8x6 (UC-Logic Tablet WP8060U)

**Comment by pojienie** [comment]
Can confirm: Also happens to me.
OS: Arch Linux
Opentoonz version: latest as of now (5198e682888e1e0a52e637a2d87b92546c61d573)
graphics tablet: wacom intuos basic CTL-4100

The reason was that the geometric tool (Arc and MultiArc, at least) only receives leftButtonUp event and not mouseMove event when using graphics tablet even if you visibly see the cursor move. When using a mouse, it would correctly receive mouseMove event and thus the tool works correctly.

**Comment by josepablo-espinoza** [comment]
Can confirm: Also happens to me.
OS: SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
Opentoonz version: 1.5
graphics tablet: Wacom Intuos PT S

**Comment by andeon** [comment]
Finally fixed with this https://github.com/opentoonz/opentoonz/pull/4860, thx!
