### ISSUE TITLE
In version 1.5, the "What news ..." link leads to the OpenToonz V1.4 page 

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3854]
In version 1.5, the "What news ..." link leads to the OpenToonz V1.4 page 
https://github.com/opentoonz/opentoonz/releases/tag/v1.4.0

**Comment by shun-iwasawa** [comment]
The menu is linked to [https://github.com/opentoonz/opentoonz/releases/latest](https://github.com/opentoonz/opentoonz/releases/latest) .
Since V1.5RC is `pre-release` , the link still leads to V1.4.0, the latest release.

**Comment by beeheemooth** [comment]
Сlear

**Comment by RodneyBaker** [comment]
I'm tempted to suggest that link should point here instead:
https://github.com/opentoonz/opentoonz/releases

In this way users could at least get a hint that the nightlies are out there and the nightlies might solve some of their issues.
Because it links the release notes theoretically users are still downloading the release from Jan 2020 which has some very serious known issues.

I do see a potential concern with 'What's new' pointing to information that can be a year old.

**Comment by beeheemooth** [comment]
hmm ... also true

**Comment by RodneyBaker** [comment]
Let's leave this open for now so that we still have our eye on that v1.4 original release still having a direct link from the Opentoonz help menu.

**Comment by shun-iwasawa** [comment]
As a quick patch I made the V1.5RC2 release to be `latest-release` so that the `What's New` command will link to the V1.5RC2 Release Note. Thank you!

**Comment by RodneyBaker** [comment]
Thanks @shun-iwasawa!
Will close this as that should at least give users the ability to move past v1.4 if they should click the What's New link.
Much appreciated.
