### ISSUE TITLE
customize room menu bar - missing a few items

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#387]
next frame, previous frame, first frame, last frame are available on the left side of the room menu editor window

![capture](https://cloud.githubusercontent.com/assets/6495061/15716653/151e1da2-281b-11e6-9759-b58918149630.PNG)

But they are not available on the right side (menu items that can be added). So if you remove them, you can not add them back.

**Comment by blurymind** [comment]
![missing](https://cloud.githubusercontent.com/assets/6495061/15740821/9a515dfc-28ae-11e6-8525-42e8b12add25.PNG)

Here is a better screenshot to illustrate.
Perhaps this is one for @shun-iwasawa  :)

**Comment by shun-iwasawa** [comment]
The menu items in the default menu bar were arranged based on Toonz Ghibli Edition.
When Studio Ghibli decided to transit the software to Ghibli Edition, I tried to make UI similar to the existing tool (Toonz ver. 4.6) as much as I can in order to increase consistency .

For the menus "Next/Previous/First/Last Frame", I included them in the menu bar as they were also included in the InknPaint module of Toonz4.6.
However, to be honest, these commands are usually triggered from shortcut keys or console's VCR buttons. I think there is no reason to leave them in the menu bar any more.

I would like to know if there is a demand for using these commands by "clicking the menu" or they can be removed from the default menu bar.

**Comment by blurymind** [comment]
I personally use the keyboard shortcuts always - as it is quicker. New users will of course not know about the shortcut right away, they will find the buttons to do these commands at the bottom of the viewer.

When you hover over them in the viewer, you don't see in the hint what shortcut is assigned to the command. When you see the commands under the edit menu - you see what the keyboard shortcut is.
The advantage of having it in the edit menu would only be to teach the user what keyboard shortcut is assigned to next/prev frame commands and teach the user that he/she can assign a shortcut.

If hovering over the viewer buttons to do the same thing also showed what keyboard shortcut is assigned to each- then i guess it would be on par with having them in the menu.

**Comment by blurymind** [comment]
Next and previous drawings commands for example are not available in the viewer as buttons, nor are they available in any menus. As a result they are difficult to discover by new users. The only way to discover them is via the keyboard shortcuts window.

https://github.com/opentoonz/opentoonz/issues/393

**Comment by AyameLee** [comment]
Good point by @blurymind; updating the tool tips to include shortcut keys.

I would recommend removing the menus in either case and instead giving these functions a new set of default shortcut keys that could perhaps be more self explanatory.

For example, Toon Boom makes sense with these:

> Next Drawing: **(G)**
> Previous Drawing: **(F)**
> 
> Next Frame: period **(.)**
> Previous Frame: comma **(,)**
> 
> Last Frame: **(>)**
> First Frame: **(<)**
>
> http://docs.toonboom.com/download/harmony/12/HAR12_Keyboard_Shortcuts.pdf

In Toon Boom Harmony for Previous/Next Drawing however I personally use K and L since they sit right above < and > and next to the J key so **very** easy to find them, this way all six functions are available in the same position.

**Comment by blurymind** [comment]
I like these to be easily accessible to the left hand side of the keyboard,
as most times when using them my right hand is holding a stylus. So
anything you can easily reach with your left hand is actually better. Thus
why they are this way atm. Try using what you suggest while also holding a
stylus

**Comment by blurymind** [comment]
I vote to have these also available in the menu - so as to teach the user they exist and their shortcut. Changing the shortcut wont teach the user. Also next and previous drawing are not available as buttons or in any menus and are quite important. That is why i would vote to have them available in the edit or xsheet menu as well.

**Comment by AyameLee** [comment]
Sure, it's just these shortcuts seem to be standard with many video editors, Toon Boom, Synfig and Adobe Flash it may have been worth considering for simplicity's sake; it may be obvious to new users what keys they can use to navigate without a learning curve if they've used any similar software in the past.

> Try using what you suggest while also holding a stylus

I do. ;-)

**Comment by blurymind** [comment]
I think they are that way more because of the symbol on the keyboard button
rather than the button's placement. This is a good point. I actually
suggested earlier using toonboom's layout, but later realized that in
toonboom and tvp i have changed my layout settings to make those keys
easier to reach by the left hand.
Blender for example has its own layout, but lets the uset load a custom one
made to suit them if they come from maya or max. Eventually most people
just learn blender's as it is best designed to suit the design and actually
solves issues that the others have. Blender is very heavily reliant on
keyboard shortcuts, but has a spacebar search command menu that brings up
all commands that you search for and also shows their keyboard shortcut. In
that regard blender devs have made it very strong

**Comment by blurymind** [comment]
Another point worth noting is that most video editors and other animation software does have these commands available in the menus for the same reason :)

**Comment by turtletooth** [comment]
#677 Should take care of this.
