### ISSUE TITLE
next and previous drawing commands (next/prev frame without holds) hard to discover

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#393]
Right now when you use the next/previous frame commands, OT moves the timeline to the next and previous frame (jumps marked In red)
![nextprevframe](https://cloud.githubusercontent.com/assets/6495061/15745395/8a53f62e-28c9-11e6-9ea9-b210e4d29305.PNG)

If you have a frame hold for more than one frame, you have to hit the next/prev command a few times to get to the next/previous key drawing.

It would  be useful to have a next drawing and previous drawing command that jumps between drawings in the xsheet without the holds (jumps marked in yellow).
It should take the currently active level for reference of course.

**Comment by blurymind** [comment]
Ah sorry, OT already has this command, but it is not available as a button in the viewer or any of the menus. The only way to discover it is via the keyboard shortcuts.

**Comment by blurymind** [comment]
I remember setting them up to shift+z and shift+x actually. I suppose the point to make here is that they are not easy to discover by new users.

**Comment by turtletooth** [comment]
Do you think having an option in preferences to enable a next and previous drawing button in the scene viewer would help?

**Comment by blurymind** [comment]
@turtletooth it might help :) to be honest that is already overcrowded at the moment

**Comment by blurymind** [comment]
Perhaps it would be more useful to have the option to set the default behavior for next/prev frame be set to next/prev drawing instead. I certainly use it much more often than next previous frame commands. If you look at other animation software's playback buttons you will see they do too

**Comment by konero** [comment]
No, those buttons would be for composite checks, you would most likely have a dozen levels that don't share the same exposure, the functions you're talking about only apply to a single level, so those buttons would skip passed other levels.

Why not just use the standard used by everyone else? F/G keys (Flash and Harmony). I've noticed right-handed people use F/G and left-handed people use J/K because of the key bumps and so the rest of the keys remain on the inside of their hand rather than the outside; which is the natural way to use a keyboard. Since 90% of people or so are right-handed the standard would be F/G.

Whether it's a setup you or I would use is irreverent when considering the bigger picture. For anyone wanting alternate shortcuts then they can do so, but standards are used for preventing confusion and for making migration from other software a breeze, Toon Boom understood that well. :+1:
