### ISSUE TITLE
Can't run Opentoonz on school laptop

### ISSUE THREAD

**Issue by Animation1029** [opentoonz/opentoonz#3957]
Hey!
I was wondering if you guys had a portable versionn of opentoonz. I really wanted to have a portable version because it just comes in handy and another personal reason. 
If there is no portable version could you guys please make it?

With kind regards
Sketch Emperor

**Comment by RodneyBaker** [comment]
You are in luck.
Every release of Opentoonz can be made portable.
As such it's easy to solve your own requirement.

Let us knnw if you are interested in the steps to do this.

**Comment by Animation1029** [comment]
yes I am, how could I get a portable version?

**Comment by RodneyBaker** [comment]
Perhaps the easiest way would be to download the automated github builds but...
We'll assume here that you wish to make your current copy of Opentoonz a portable version.

Note that some of the following steps are optional and depend on things such as where you want to place your portable.
I will use the Desktop but substitute 'USB stick', 'My Documents' or wherever appropriate.
Not all the steps need to be done in the specified order below.
This does assume you have installed Opentoonz and have the files available to get it as a portable.

Step 1  Location:  Create a folder/directory for your portable version of Opentoonz on your Desktop (to make it easy to find).  Name the folder something appropriate such as 'Opentoonz portable'.

Step 2  Copy the Program Files:  Copy the contents of "C:\Program Files\Opentoonz\" into your new directory on the Destop
Step 3 Copy  the 'stuff' (config files):  Copy the contents of "C:\Opentoonz stuff\" into your new directory on the Desktop
Step 3a (which can be done as part of step 3) Rename the Opentoonz stuff directory inside the portable folder on the Desktop as "portablestuff".   Note that this exact name is required for Opentoonz to recognize that it is now a portable application.  If Opentoonz does not see the "portablestuff" contents it will either not work or will use the current stuff directxory located at C:\Opentoonz stuff

You now have a portable copy of Opentoonz that you can move and run from any location you desire.


Another way to get a portable but in this case one generated from Github is to download the builds generated by Github Actions.  Those builds are portable by default.   Here is a link to the latest build of that:  https://github.com/opentoonz/opentoonz/suites/2796607740/artifacts/62139304

**Comment by RodneyBaker** [comment]
Note that the first time you do this it may take a little time just because the process is not familiar.
After using the process a few times you'll find it takes approx. 2 minutes to create a portable from any installation of Opentoonz.

**Comment by Animation1029** [comment]
Hey again!
![image](https://user-images.githubusercontent.com/84682783/119276893-dbf05900-bc1c-11eb-993b-607943b1af82.png)

I get this every time I open it. And then it just closes.

**Comment by Animation1029** [comment]
And is there a way to not have this running as a administrator? If you know Krita it just opens in the portable file. I am asking for this due some personal reasons.

**Comment by RodneyBaker** [comment]
Not sure why the portable isn't running for you.
Generally if a portable application doesn't run it is because a runtime file the program requires is missing.
You aren't getting a error popup though so that doesn't seem to be the case.

You should just be able to run the program... no admin requirement.
Make sure you don't have the program somewhere where Windows doesn't allow you to run the program... such as inside of Program Files.  That location is generally reserved for applications that use the windows registry (and not localized config files).

I'll doube check to see if something has changed recently on the Opentoonz side.

**Comment by RodneyBaker** [comment]
Everything checks out here.
I suspect your antivirus settings are preventing the program from running on your end.

**Comment by Animation1029** [comment]
Euhm, this won't work. The thing is that there is a firewall or something and because of windows firewall defender(idk the exact name) I can't launch the app. I can't give acces to the app because I have a laptop from school. That is also why I asked for a protable version, because I only can download portable apps and apps from the microsoft store. I wanted to aks you now, is there a way to get rid of that screen where it asks access for local wifi or something??

**Comment by RodneyBaker** [comment]
Even the portable versions of Opentoonz and various forks have the check for updates, although that can be toggled off in Preferences.

This isn't your problem however.  It appears your local restrictions are too strict and thusly will prevent even OT portable applications from running.   

Try the Tahoma fork of Opentoonz... as it is portable.
If you can run that then life will be good and you can press on.
Otherwise you'll need to study your local settings and find a way to allow access. (which can be done... you just have to discover how)

Here is the link to Tahoma2D (which again... is a portable):  https://tahoma2d.org/posts/2021/05/03/12release/

**Comment by manongjohn** [comment]
The portable OTX is still available as well, if you want more of the OT experience. Can get it [here](https://github.com/manongjohn/otx/releases

**Comment by Animation1029** [comment]
Hey!
This is actually a dumb request, but can you guys launch opentoonz on the microsoft store? That is the only way I can download it now. I really want to animate, it has been my dream since I was a kid.

Regards,
Sketch emperor

**Comment by RodneyBaker** [comment]
It is not likely that Opentoonz will meet the requitements for the microsoft store.
But an interesting request never-the-less.

If you cannot download a zip file I'd say your problems are a little more complex than only being able to launch programs from the microsoft store.

Recommend you contact your school computer administrator and ask them how to proceed with installing Opentoonz.  They should be able to help you out.
