### ISSUE TITLE
Documentation for developing vector brushes?

### ISSUE THREAD

**Issue by MikeTysonsPidgeon** [opentoonz/opentoonz#3973]
Does any documentation for how vector brushes are formatted/developed for Opentoonz? It seems that if photoshop brushes are ever going to be integrated into Opentoonz it's not going to be any time soon and I feel like the vector brushes offer a lot of the photoshop-esque features that mypaint brushes lack. I know there are a few vector brush packs available for download, so I know someone must be making them. My question is "how?"

**Comment by beeheemooth** [comment]
The basics of this are pretty simple:
1. Create a Vector Level and draw the brush shape you want.
2. Save the level (not the scene) as MyCustomBrush.pli (or any other name)
3. Find the saved pli-file, cut it and paste it into the c: \ OpenToonz stuff \ library \ vector brushes \ folder
4. Restart the program.
You will find your custom style in the Style Editor under the Vector section.

**Comment by MikeTysonsPidgeon** [comment]
That does sound pretty simple. Are there any additional options besides that? When I look at the vector brushes that are already available in the program, they show a lot of really complex styles with scattering and stuff like that.

**Comment by beeheemooth** [comment]
If you use several different styles in a custom style, then you can change their color separately.
Unfortunately, vector styles can only be made from vectors. I would like to be able to add texture and blur to strokes, like in CSP, but at this point this is not possible.
Another interesting nuance is that a PLI file can contain many different stroke patterns and there must be some mechanism that will allow you to use this to animate a texture or stroke shape, but for now this is just a theory.

**Comment by MikeTysonsPidgeon** [comment]
This all sounds really interesting. Is it cool if I ask where you learned all this? I'd really like to have something to reference for making custom vector brushes for Opentoonz. 

I'd like to use brushes to add certain details to characters that would be a pain to draw in individually by hand, in particularly body hair. If you've ever seen an anime character with body hair, you've probably noticed that it's ... not very well done most of the time. I'd prefer if I could get results that look similar to the Gaston scene, but they were only able to do that effect for ONE scene in the movie because they drew each hair individually. I think that using brushes with the functionality of photoshop brushes would be a good workaround, but the mypaint brushes don't have all the necessary features to pull that off. That's why I'm trying to figure out the ins and outs of building opentoonz vector brushes. They seem like they'd be able to do what the mypaint brushes can't.
![EyXv0wGWEAAtU-T](https://user-images.githubusercontent.com/78436628/121414255-70a0c980-c934-11eb-8b4c-c8c4fa86bb34.jpg)
![EyXv0wFWUAkZw1x](https://user-images.githubusercontent.com/78436628/121414267-75657d80-c934-11eb-8f2d-1edad7c8b617.jpg)

**Comment by beeheemooth** [comment]
Things like hair, unshaven chin, I do not with custom vector styles, but with groups of vectors. Create one or more hair patterns, group them and save them in a separate level (like in a library). You can copy these groups from the level and use where you want. Groups can be edited, deformed, and the most used group variations can be saved to the instance level, complementing it. You can load this level into different scenes.
 Custom styles have their drawbacks in this regard: they look bad if the line bends a lot, many custom styles slow down the Style Editor window, in the Fill Check mode they look like a solid black line.

**Comment by MikeTysonsPidgeon** [comment]
That's not a terrible idea either, though it will take me a bit to figure out how I would set those vector groups up for my purposes. 

I still kind of wish we could import photoshop brushes because that would make things a lot easier for me. I already have a set of brushes made for this exact purpose. I think that's a big part of why I want to try and make vector brushes for this purpose, because it's closer to the method I already use and just feels more natural that way.

**Comment by RodneyBaker** [comment]
The way I learned how to create custom vector brushes was:

- I noticed the custom vector brushes in the Opentoonz Library directory were all .PLI files (this is the file format for vector files in Opentoonz)
- I opened a file in Opentoonz and examined the image
- I adjusted the image and saved it back into the LIbary under a new name
- I restarted Opentoonz (because the brush didn't automatically appear in the Libary), selected the brush/file and drew with it
- I adjusted it more and examined how my changes effected the brush strokes
- I noticed that I don't always have to restart Opentoonz to have the brush appear... it can be sufficient to start a new scene etc. but it's a good idea to restart Opentoonz anyway to avoid any issues.
- I adjusted the .pli brush until things broke and I had to step back to an earlier file that worked (this is now more easy because a backup file (.bak) of the brush file is created when it is saved)

I would say the thing that helped the most is simply opening the current brush files  and using them as a starting point.

If you can share examples of your photoshop brushes we should be able to adapt them for use with Opentoonz although the brush engine differences themselves may not allow for some capabiliities.

**Comment by MikeTysonsPidgeon** [comment]
Ah. I didn't realize the pli files could be opened in Opentoonz that way. That makes a lot of sense and makes this a lot easier to figure out. Thanks for the info.

**Comment by RodneyBaker** [comment]
While both @beeheemooth mention restarting OT in this process my memory is that somewhere around v1.4 this changed and the restart is not strictly necessary although likely still ideal.   

I tend to keep the brush I'm working on open in Opentoonz (in one column) while testing the use that same brush in another column... drawing to see the effect... saving the level of the brush with each change.... then saving the scene... THEN... reopening the scene via the recently used scenes listing.   

This seems to work quite well and allows for speedy fixes and testing.  This does likely cause some occassional issue with the Library updating but those are usually of the sort where the .pli file needs to be removed entirely anyway because it didn't get properly created.

All this to say that live updating and testing of a brush we are creating is possible although Opentoonz is not designed or optimized to do that so expect some instability and don't use original brushes in the process.   Backup often and save.  :)

**Comment by MikeTysonsPidgeon** [comment]
That test definitely looks promising. I'll be working on my own attempts based on this method. Thanks for all the help you guys.

**Comment by RodneyBaker** [comment]
Will close this report but feel free to continue discussion and exploration of vector brushes and... please let us know what you come up with for custom bector brushes @MikeTysonsPidgeon!
