### ISSUE TITLE
There are many issues, here's what I have...

### ISSUE THREAD

**Issue by EddatronicsTV** [opentoonz/opentoonz#3975]
Many issues are present. many different recipes for crashing, and general problems that make the program harder (and some times impossible) to use.
I apologize in advance if you have fixed these problems, or if I come off as rude, I am trying my best to be helpful...

The first issue is saving. Just saving the project as a whole tends to crash the program, autosaving crashes it, and 90% of the time it doesn't actually save it, just makes a file that has the name (but is blank). I also find it odd that I cant save rooms. I don't actually know if this is a non-existent feature or a bug, but something worth noting. 

Continuing off the topic of rooms, I cant actually create new rooms. This is absolutely a bug, and when I go to create a new room, the program crashes. I can rearrange pre-existing rooms, but I cant make new ones.

When a scene/project is "saved" or you cancel saving, everything goes blank. It looks like all the frames are completely empty. However, upon drawing on them, an area of effect happens, and your drawing is revealed. But its kind of time consuming and irritating when you have to through hundreds of frames drawing just a dot on them just to undo it so you can see what you've done. 

Oh yeah, and you should have a note somewhere saying that if your software refuses to start, to "run as administrator". I had that problem, and it fixed it right up. that's a suggestion.

List steps to reproduce the behavior.
I described how and why these things happened pretty well above. I hope I'm not breaking any rules already...

**Screenshots**
I'm afraid I lack screenshots... I'm sorry there...

**Device Information:**
 - OS: I use windows 10
 - OpenToonz Version: it says OpenToonz 1.5 in the window... I thinks that's right?
 - GPU: NVIDIA GEFORCE GTX (i think this is what you're asking for...)
 - GPU Driver Version: I have no clue... sorry. I'm not a tech guy, just a dude who wants to draw silly characters to make people laugh... sorry again...

Again, I'm not a tech guru, and I'm no big brained fella, I'm just saying what I see. I'm not expecting this to "be fixed now, or suffer the consequences". I'm just trying to help you guys improve your software by saying what's wrong. I hope this was helpful, and that I didn't break any guidelines. this is also my first time on GitHub, so even more stuff I'm unfamiliar with. 

I hope you guys find this helpful, and that I haven't made anyone upset.

**Comment by RodneyBaker** [comment]
Because of the number of issue you are having I will guess a few things here.  Please adjust as necessary to fit your actual case.

1.  If you had a previous release of Opentoonz installed it is very important to uninstall the previous release first before installing v1.5.  There are some significant changes that will not like working with left over files from previous installations.

2.  As you are a self confessed non-techy is seems reasonable that you are not using the current nightly release that resolves some/many of the issues you outline.  The exe file for windows for the latest nightly release can be found here:

https://github.com/opentoonz/opentoonz/releases/tag/nightly

(Note:  Even for the tech-savy... the nightly release page itself is not updating properly and so therefore is not showing all appropriate updates.  The link above *should* have the latest.

For what it is worth we are all upset that you are having these problems.  ;)
Let's help you (and others) get past them as soon as possible.

**Comment by manongjohn** [comment]
I would check that you have the proper permissions to the OpenToonz stuff folder as a lot of what you are experiencing appears to be related.  Sometimes the stuff folder doesn't get the right permissions when installing and can lead to these issues.

Here are instructions to check/fix the issue as follows:
1. Open Windows Explorer and go to the `C:\OpenToonz stuff` folder
2. Right-click `OpenToonz stuff` folder and select `Properties`
3. Click on the `Security` tab
4. Look in the `Group or user names` box for your username.
5. If you do not see it, click on the `Edit` button
6. Click on the `Add` button
7. Enter your username in the bottom box and click on `Check Names`.  
8. After it finds/verifies your username, click 'OK'
9. Click on your newly added username in the top box
10. In the bottom box, check `Full control` under the `Allow` column
11. Click `OK` until you close the Properties dialogbox.
12. Try restarting OT normally.

**Comment by EddatronicsTV** [comment]
So, I took the advice given to me, and Opentoonz appears to be working just fine now. Thank you for your assistance in this, I greatly appreciate the help! again, thank you.

**Comment by RodneyBaker** [comment]
Glad to hear you've got things working.
Will close this report but please let us know if you experience additional problems.
