### ISSUE TITLE
Mirror Fx

### ISSUE THREAD

**Issue by FerrLui** [opentoonz/opentoonz#3997]
**New fx**
Hi. Im using Opentoonz  long time and every time i need  some fx that can mirror my characters.  Now for that im copy and pasting character in new frame. With new "Mirror fx" it will be much more faster. And i think it will be graet fx not only for me.

**Comment by beeheemooth** [comment]
Alik, you can use the effects Tile, Tile Iwa, Kaleido for this (maybe there are other effects that can mirror) 
![Screen_0243](https://user-images.githubusercontent.com/25724133/124381103-5ce54a80-dcc9-11eb-872e-673d383c62c9.jpg)

**Comment by RodneyBaker** [comment]
There a a number of FX that will produce mirrored images... @beeheemooth mentions Tile FX and that perhaps is the best one.   We can also duplicate a column in the xsheet and then simply scale it -100% horizontally, vertically or both in order to flip/mirror the image... I tend to like that approach for a number of reasons but perhaps mostly because of how simple the process is.

If you need more complex mirroring the Cast Shadow FX (under Lighting) allows for not only mirroring but distortion based on perspective projection etc.

![image](https://user-images.githubusercontent.com/2576432/124407555-d69d2880-dd09-11eb-84d0-aaacce7d6d40.png)

**Comment by FerrLui** [comment]
> There a a number of FX that will produce mirrored images... @beeheemooth mentions Tile FX and that perhaps is the best one.
> 
> We can also duplicate a column in the xsheet and then simply scale it -100% horizontally, vertically or both in order to flip/mirror the image... I tend to like that approach for a number of reasons but perhaps mostly because of how simple the process is.
> 
> If you need more complex mirroring the Cast Shadow FX (under Lighting) allows for not only mirroring but distortion based on perspective projection etc.
> 
> ![image](https://user-images.githubusercontent.com/2576432/124407555-d69d2880-dd09-11eb-84d0-aaacce7d6d40.png)

Yes, this are great, but what to do, if i want  simply to turn left or right my character. Example-  my character is standing and looking right and i want that in next frame he look left.

**Comment by RodneyBaker** [comment]
what to do, if i want simply to turn left or right my character. Example- my character is standing and looking right and i want that in next frame he look left.  This fx are dublicate it, not exactly what we need.

Cast Shadow FX can do the job although it takes a while to get comfortable with the controls.
There is basically a frame controller for the original image and one for the mirrored image and both can be manipulated in a variety of ways to meet whatever mirroring is required.  It just uses the source as is so one must consider potential conflicts.  Here's an quick example of flipping the source and then manipulating the position of the mirrored image.
There are some additional options for fading and blurring that can be quite useful to sell the effect of mirroring as well as ways to adjust color whether from the source or from the FX dialogue.

![Cast Shadow FX](https://user-images.githubusercontent.com/2576432/124426181-4eca1500-dd2f-11eb-9e47-1d89308c37ef.png)

As always, the scene will dictate what approach works best and there is often many ways to acoomplish a goal.
I will say that almost any FX is overkill in my estimation if we can accomplish the same thing without using any FX at all.
This is why I tend to prefer duplication and manipulation of the columns themselves as that keeps things really simple.

**Comment by RodneyBaker** [comment]
Rather than close this feature request as something already implemented @FerrLui, it would be good to know what (if anything) of the currently available mirrioring options does not meet your specific needs.

I suppose one thing would be to simply have an FX such as currently exists but one that is named Mirror FX (to make it easier to find by users!) and perhaps even simplified a little to achieve basic mirroring tasks such as reflections in a mirror on the water, etc.

If there is a shortfall in one of the current approaches that will be very welcome information.

**Comment by FerrLui** [comment]
@RodneyBaker  . 
 I think we need simple version. If we need to flip character or show only 1 character  on screen, now we need original scene and mirrored version. But with new fx we can use on scene it and done. For slow computers it will be great. And for new users it willl be useful.

**Comment by FerrLui** [comment]
Sorry for my english))

**Comment by beeheemooth** [comment]
Hmm, I thought you meant the reflection in the mirror.
If you mirror one level so that the character is looking in the other direction, then it is better to do this without resorting to FX, since the FX action can only be seen with "Preview" enabled. It will be very difficult to edit the animation in this way. I in such cases put the level in the sub-xsheet and scale it vertically -100.

**Comment by RodneyBaker** [comment]
Yes, and if actually picturing a mirrored reflection the image in the mirror and the source of that reflection is rarely going to be exact duplication of the source.  Instead we are more likely to need to use two images in the first place.  Thusly:

![mirroring` and reflections 0001](https://user-images.githubusercontent.com/2576432/124520955-998d7080-ddb3-11eb-8203-dda67a2e9506.png)

There really is no FX that can do this type of more realistic mirroring which is why many would resort to 3D reflections with mirrored surfaces that capture different angles of a model in front of that reflecting surface.

**Comment by RodneyBaker** [comment]
Closing this request as a stale report but...

@FerrLui Please feel free to add additional information or (perhaps better yet) open a new report that restates the requirements needed for mirror effects that are lacking in other features and approaches.  Workarounds currently being used should be documented so that workflow can be fully exaimined to determine the best way forward.  Please reference this report in any new request as well as it captures some of that information.
