### ISSUE TITLE
Load 2 animations

### ISSUE THREAD

**Issue by SPH404** [opentoonz/opentoonz#4015]
Let's imagine that we have 2 animation files. Can we load one of them after the other with an OT command?
If so, where is it in the menu?

Big thanks !

**Comment by artisteacher** [comment]
You should try the load level command. It can load either individual levels/files or an entire scene. If you choose "Apply" instead of load, you can add the next scene or level without closing the pop-up window.

Where they load is based on what cell is active in the Xsheet. You can always drag/drop to a new location if they don't end up placed correctly.

**Comment by RodneyBaker** [comment]
@SPH404 Since you are new to Opentoonz I recommend joining an Opentoonz discord where you can recieve assistance in real time while learning.

Adam Earl's Opentoonz discord:
https://discord.gg/yTMyNkM

The Tahoma2D fork's discord:
https://discord.gg/Sy3nDPe9Fc

There are other places of course to discuss Opentoonz and related forks.

I will close this report but please feel free to continue the discussion here in the closed topic for as long as desired.
