### ISSUE TITLE
"There were problems loading the scene. Some files may be missing"

### ISSUE THREAD

**Issue by milank90** [opentoonz/opentoonz#4035]
**Bug Description**
I had my project opened while I was saving an image that is included in one of my levels. Power went out, when I tried to open my scene afterwords i got the error "There were problems loading the scene. Some files may be missing".
Tried loading the backup - still the same error.
I also found all my settings in Open Toonz turned to default.
I am guessing the level that had the image is gone but is there any way to open the scene without that level, otherwise i will lose several days worth of work. I saw that a similar issue had been reported but if i could do something else other than loading the levels and starting from scratch, it would be greatly appreciated.

**To Reproduce**
List steps to reproduce the behavior.
1.Open a scene in OpenToonz
2.Use external software to save over an image that is used in a level in open toonz
3.Cut power while image is saving.
4.Notice that the scene cannot be loaded.

**Device Information:**
 - OS: [Windows 8.1]
 - OpenToonz Version: [1.5 (2021-04-10)]
 - GPU: [e.g. NVIDIA GTX 1080 Ti]
 - GPU Driver Version: [466.63]

[Logo.zip](https://github.com/opentoonz/opentoonz/files/6940674/Logo.zip)

**Comment by RodneyBaker** [comment]
@milank90 The scene file you attached appears to be completely corrupt.
It will likely be easier to recreate the scene... hopefully... using the levels/images from the previous scene.

If you aren't currently a member of one of the discords dedicated to Opentoonz and its forks I will recommend joining as there is always someone able to assist with such troubleshooting as welul as guide in how to prevent the problem from occurring again.

**Comment by RodneyBaker** [comment]
I believe we can close this report and establish it as a known issue where:

Known Issue
If power to a system is lost during use of Opentoonz the open scene file may become corrupt.

Recommendation to avoid file corruption due to power loss include:
- Establish backup power to allow system to remain on long enough to save files

Methods of recovery from lost or corrupt files include:
- Restoring files from most recent backup 
- Recreating scene file using available resources that were not lost or corrupt
 
Approaches to mitigate the potential loss of files are many but include:
- Establish backup power and file strategies
- Determine optimal approach to using current tools available to recover from lost or corrupt files (especially due to sudden and unexpected power loss)
-- Use a three teir approach to backing up current work:  Personal, Application and Operating System/third party

Please feel free to continue the discussion and investigate this particular incident of power loss corruption of scene files here.
