### ISSUE TITLE
Add Palette Gizmo Button back to Level Palette.

### ISSUE THREAD

**Issue by JPUser1** [opentoonz/opentoonz#4083]
I was wondering if you could include the Palette Gizmo Button to the Level Palette next to the Freeze Button?  Because I use it a whole lot in my coloring and also the original Toonz has it there too, many people do not know it exist at current and those who do usually forget because its so well hidden I think it would be a good idea to bring it out of hiding for V1.6 maybe even a way to show or hide it like the Style button has?

**Comment by gab3d** [comment]
@JPUser1 
I like the idea of Palette Gizmo having a button, as is quite hidden currently, and it offers good style editing options that make the Palette more powerful.

In general 'm not a big fan of placing buttons in panels' title bars, but perhaps it could find a home in the Toolbar, together with the other Palette buttons?

**Comment by beeheemooth** [comment]
The button for Palette Gizmo is needed not only for the convenience of calling this panel, but also for bypassing one small glitch. Since Palette Gizmo works with several selected styles, calling the panel window from the context menu of the Palette window (it seems that this is the only place from where you can call Palette Gizmo) by right-clicking the mouse resets the highlighting from the selected styles, and after the Palette Gizmo window appears, you need to re-selected them.

**Comment by gab3d** [comment]
certainly that's one good reason too!
