### ISSUE TITLE
regression: FX schematic node visibility toggle button disappears when node disabled

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#411]
This is a GUI usability bug imo, but it should confuse some users. When you toggle off the visibility of a node- the toggle button disappears. To reenable a node, the user has to click on an invinsible pixel area where the button used to be.
![fxviewicon](https://cloud.githubusercontent.com/assets/6495061/15822583/8ce9b9b4-2bee-11e6-8181-9b224a3cd75b.PNG)

this is a regression in the design - as this wasnt the case in harlequin.

@shun-iwasawa might know why the removed the icon when the node is disabled

**Comment by shun-iwasawa** [comment]
The yellow eye icon is used both in the Xsheet column head and the Schematic nodes.
The look and usage of them are the same - when it is displayed, which means the column/node is visible on rendering, and vice versa.
The behavior you pointed is what I intended. The yellow eye must be hidden because the Fx node is disabled.

To make it more accessible, one idea is to show some "disabled eye" button when it is disabled...
However I think the current (rather simple) design makes not so much confusion for users, because all Fx nodes are activated when created, so having disabled Fx means users already know where to click to toggle.

**Comment by blurymind** [comment]
I think it should show a disabled button, so the user doesnt get confused. Having a button become invinsible is generally bad design imo. I had a friend ask me how to reenable a node - granted they were new to the software :)

Btw why is there a 'link' button that doesnt do anything when clicked? What does it do?

**Comment by blurymind** [comment]
If it can be clicked - dont hide it. If it doesnt serve a function- remove it

**Comment by blurymind** [comment]
Here it is in Harlequin:
![buttonvisibilityregression](https://cloud.githubusercontent.com/assets/6495061/15949786/fbd94f50-2ea1-11e6-9a34-2bffd813a51f.PNG)
As you can see the toggle button is always visible - in both enabled and disabled states.
Thus why I am calling it a regression in design :)

**Comment by artisteacher** [comment]
I find my students definitely benefit from a visual cue in cases like this. For consistency, the icons should probably be moved to the stylesheet & use the same icons as the viewer & Xsheet/Timeline.

**Comment by jpturcotte** [comment]
Maybe @konero could have a look at this?

**Comment by manongjohn** [comment]
There should be disabled icon states. This goes back to old argument that without a disabled state icon, it looks like something is missing or not available.

These icons should be updated to match the rest of the interface.

With how small these icons are, i think they would benefit from a different disabled state icon, like a red X over the enabled state icon because a grey'd out version that we used on xsheet may not be obvious.

**Comment by manongjohn** [comment]
Actually, might be ok. Just need to change code to behave similar to xsheet mode in terms of filling background colors on/off and use the current xsheet stylesheet settings as @artisteacher suggests.

**Comment by artisteacher** [comment]
This has been fixed in the both the stage and fx schematic. 
![screen shot 2018-12-03 at 8 30 28 am](https://user-images.githubusercontent.com/21159116/49376614-c0540980-f6d5-11e8-8671-9b2f90bbfe88.png)
