### ISSUE TITLE
regression bug: FX - inserting any shaders crashes OT

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#413]
to reproduce:
1. create a vector level
2. In schematic view- FX, right click on the level, insert FX> shaders> wavy

OT will crash.

The same will happen for all the other shaders.

I know you are not supposed to insert them, but OT should not crash entirely when that mistake is made.

**Comment by blurymind** [comment]
toonz harlequin had a way to deal with this automatically and elegantly:
![capture](https://cloud.githubusercontent.com/assets/6495061/15823550/0c302ba0-2bf3-11e6-9da2-b21e336f1e16.PNG)
no crash

**Comment by turtletooth** [comment]
Do shaders work at all?  I can't use them on any type of level without a crash.

**Comment by artisteacher** [comment]
I can use shaders on OS X but only if I add them. Adding a shader and trying to connect it directly to another level eventually results in a crash. Adding a shader and inserting other FX to it works just fine. I can connect a shader and another level to a layer blending FX without issue. Inserting the shader always causes a crash.

**Comment by turtletooth** [comment]
@artisteacher Does previewing in the viewer crash?  I can preview (File->Preview) fine, but previewing in the viewer crashes.

**Comment by turtletooth** [comment]
![shaders](https://cloud.githubusercontent.com/assets/4576381/26412736/f9203f30-4066-11e7-82df-ea112805495c.PNG)
I can preview in the viewer if I previously did file->preview, but any subsequent change crashes it.

**Comment by artisteacher** [comment]
With Sierra, I'm not getting a crash from either form of previewing. This is probably unrelated but the caustic shader can preview easily in the viewer but was very distorted with file -> preview - similar to some of the plastic preview/render issues. It loads ok now but the loading process is very, very slow and shows no visual cues that the preview is loading. 

I am likely to get a crash when working with the Toonz color blending fx node but that seems to result from opening up the settings, not from preview.

**Comment by OpentoonzTester** [comment]
My thread on this is closed.  Original post here:

Instant crash when using caustics, glitter, fireball etc. Works fine on ToonzPremium, but not on OpenToonz.

I have conformed the two settings (Opentoonz and ToonzPremium) so that they are roughly equal.

Sometimes Opentoonz will crash on render, but sometimes it will let me render, then will display the FX. Other times rendering is fine, and it will then display the FX, but will crash if I alter any parameter within the FX in display mode.

Any help with this issue? Side-by side image for reference. On Toonz Premium no problem. If I preview in OT, it will crash instantly with no warning. Gone.

Edit: Win7 64 Bit on Boot Camp
https://cloud.githubusercontent.com/assets/26611773/24224808/2ba1262e-0f55-11e7-8e72-1410e6293c73.jpg
