### ISSUE TITLE
Scrolling with the mouse wheel in the output settings should not change any settings

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#4131]
When you scroll down the output settings using your mouse wheel, if your pointer goes above any dropdown boxes, it can change it accidentally. I've seen lots of users asking why their output appears as separate files and that's because their pointer was accidentally over the Multiple Rendering dropdown box. Unless you click on the dropdown it shouldn't select it. This is causing lots of confusion and annoyance with the program.

**Comment by WolfInABowl** [comment]
I wholeheartedly agree with this, it is absolutely too easy to accidentally change something without meaning to. Having the mouse wheel be responsible for both navigation and interaction makes an issue like this inevitable.
I'd think that the current behaviour could be locked behind a modifier key e.g. ctrl, letting the scroll wheel only be responsible for navigation unless the user chooses otherwise.

**Comment by DarrenTAnims** [comment]
This would be a great fix to get into the next version @shun-iwasawa (I realise we're getting to that time of the year when the next version's features/fixes start to come together).

**Comment by gab3d** [comment]
I agree it is annoying and, potentially, a cause of inadvertent errors.

I've tested several programs installed in this PC and indeed some of them do behave like OT (that's not to say it's less annoying, just facts) :wink: 

**Like OT**
Krita
Premiere Pro
LibreOffice
Kdenlive
OBS Studio

**As Proposed**
Photohsop
After Effects
Blender
Maya
Mudbox
Audacity
ProTools
Firefox
Poedit
