### ISSUE TITLE
Display pegbars on the timeline

### ISSUE THREAD

**Issue by crispyi2** [opentoonz/opentoonz#4161]
**Is your feature request related to a problem? Please describe**

I have recently started the downsides and benefits of animating with a combination of frame by frame and tweening with the animation tool instead of just frame by frame. While trying out pegbars feature I found it frustrating to add new keys as I had to do it through the function editor (due to the absence of a refrence to the pegbar on the timeline)

**Describe the solution you'd like**

I think a good way to fix this issue is to straight up just... display pegbars on the timeline
(plz let me know if I could be more concise)

**Comment by Bracket-H** [comment]
Is the following what you want?
1.) Have a bunch of stuff connected to a pegbar
2.) Use animate tool to move keyframe pegbar so the stuff connected to it moves with it
3.) To make doing this easier, have the pegbar as a column/row (on the timeline) to click on and move around
?

Cause if that's the case then OT already has something similar that does it.
1.) Click on animate tool or use its shortcut to activate it
2.) Look at its tool options toolbar that appears in the main view
3.) There are two dropdown menus with things like Table or Camera or Column, and the second one has Position, Rotation, etc
4.) Choose the pegbar there
5.) Look at the main viewer, a purple crosshair thing will appear with the name of the thing you're animating, including a pegbar if you select it
6.) Animate it to your wishes and set keyframes like you'd do with a column/level

**Comment by DarrenTAnims** [comment]
Sorry if you're aware of this, but you didn't mention it in your question, so just in case: You can just animate the column directly, without using a peg.
However, it can be handy to split up your animation keys, so that one type of animation is on one peg and another type on another peg, but by doing this you can't see the keys on the timeline. In this instance, you can create or copy a single drawing to another column. Parent that to your actual drawing column and use this dummy column to apply animation keys to. This will move your drawing column AND have your keys on the timeline.

**Comment by crispyi2** [comment]
> Sorry if you're aware of this, but you didn't mention it in your question, so just in case: You can just animate the column directly, without using a peg. However, it can be handy to split up your animation keys, so that one type of animation is on one peg and another type on another peg, but by doing this you can't see the keys on the timeline. In this instance, you can create or copy a single drawing to another column. Parent that to your actual drawing column and use this dummy column to apply animation keys to. This will move your drawing column AND have your keys on the timeline.

I think this is a good solution I'll close this issue for now
