### ISSUE TITLE
Another UI Scaling Bug

### ISSUE THREAD

**Issue by the-mantis-shrimp** [opentoonz/opentoonz#4166]
Hello,
I've done some research into similar issues, none of which reported an identical problem or solution which solved my issue. 

Hardware:
GPU - RTX 3050 Ti Laptop
Tablet - Wacom Cintiq Pro 24 UHD

Software:
OpenToonz (nightly build downloaded 11/30/21)
Windows 10
Standard Wacom Drivers

Issue:
Scaling the tablet's display past 100% in windows display settings causes opentoonz to have trouble following the pen input. With raster, the strokes are located way off to the side and do not display until the drawing pane is moved. With vector, the strokes appear in the correct locations, but they do not appear until after a stroke has been completed. With both, the "cursor size outline" does not follow the stroke. Everything works fine if the tablet is scaled at 100%, however the opentoonz GUI is too small to work with on the UHD screen. Let me know if you need more information. @RodneyBaker seems to have found solutions to similar issues. I would greatly appreciate assistance.

**Comment by shun-iwasawa** [comment]
Are you connecting Cintiq to laptop? If yes, please try the following:
- Set the Cintiq's display to be the primary monitor.
- Set the laptop's display scale to be the same as Cintiq's.
- Make display settings to show things on Cintiq's display only, or to show the same thing on both displays.

One of the above may resolve the problem since the problem seems to be due to multi monitor environment with different device-pixel ratio.

**Comment by the-mantis-shrimp** [comment]
Setting the Cintiq as the primary worked perfectly. Pretty snazzy fix, thank you very much. For others who encounter this problem, I did have to restart opentoonz for the change to take effect.
