### ISSUE TITLE
making custom (vector) brushes

### ISSUE THREAD

**Issue by Carpyboi** [opentoonz/opentoonz#4226]
**Question**
Ask a question related to OpenToonz.
I want to make custom vector brushes for opentoonz, specifically with pencil textures, but I can't seem to find any information on how to make one. I made some pencil brushes for csp, but I'm not sure if these work...

**Comment by RodneyBaker** [comment]
@Carpyboi  We can definitely create custom vector brushes.
Creating vector brushes that look like pencil might be a little difficult but should be possible too.

Can you share the pencil brushes or at least images of how they look so we can get a clear example of the target you wish to hit?

As for creating the brushes... I'll follow up this post with another with specific steps.  (note... it's really easy but does have some pitfalls to watch out for)

**Comment by RodneyBaker** [comment]
Here's a quick fail.  ;)

![image](https://user-images.githubusercontent.com/2576432/150240809-04977e8c-7e5f-4dcf-a796-1a47b99a332d.png)

**Comment by RodneyBaker** [comment]
Slightly better...

![image](https://user-images.githubusercontent.com/2576432/150243861-1af1c56e-19c0-4845-b33f-a34b33d270e6.png)

I've attached this brush.
If you drop it into your Library folder inside the vector brushes directory it should be available as a vector brush.
[pencilish3.zip](https://github.com/opentoonz/opentoonz/files/7901480/pencilish3.zip)


And that is the main tip:
- Create a vector image that will be your brush
- Save the vector level via menu:  Level > Save Level As
- place the vector level (a .pli file) inside the vector brushes directory in the Library folder
- If the custom brush you've created is not corrupt... which will crash Opentoonz... you will be able to use the vector image as a brush

**Comment by Carpyboi** [comment]
These are the strokes I wish to turn into vector brushes. Sorry it took so long to reply:
![img](https://user-images.githubusercontent.com/98064801/150246278-f530aba1-c0d4-461d-a691-607a1a1186b0.png)

**Comment by Carpyboi** [comment]
Here's a better one in case the last one got you trouble:
![img0002](https://user-images.githubusercontent.com/98064801/150248272-1b290a9a-2f6f-4293-9dc8-9cd4bf635bff.png)

**Comment by RodneyBaker** [comment]
Do your brushes have to be vector?
The type you seem to be after lean more toward raster and of those many are already part of the mypaint brush collection in opentoonz (or otherwise available).  Mypaint also has the option of custom brushes although those would likely be best created in MyPaint itself or Krita... which I understand has new MyPaint brush creation capability in the 5.0 release.

At any rate... it's often best to start with a raster base and then emulate and optimize that for use with vectors.

As for color, the color is easily adjusted on the fly and even animateable due to the nature of Opentoonz color styles and keyframing.

**Comment by Carpyboi** [comment]
What about the brushes I made with clip studio paint? and how to I optimize a raster brush for use with vectors?

**Comment by Carpyboi** [comment]
What about the brushes I made with clip studio paint? and how to I optimize a raster brush for use with vectors?

**Comment by RodneyBaker** [comment]
We'd have to know more about the brushes from Clip Studio Paint.
We don't have access to those unless you post them.

As for optimizing a raster brush.
I assume you know how to convert a raster image to vector in Opentoonz.  If not we'll have to back up a little.
Take your raster brush image and Convert to Vector.
There are two methods of conversion and I'll guess that Centerline will work best for brushes but that may not be the case depending on the detail of the brush.
After conversion to vector is when we have to optimize because the simpler the vectors the better performance we'll get from the brush image.

I didn't mention before and I think I may have failed to do this in the Pencilish3 brush I posted...
I always try to avoid using the colors from color swatch 0 and 1 when making brushes.
I'm not sure why and perhaps it's just superstition on my part but I get better results when the colors of the brush/image use additional colors other than the default first two.  Those color can then be changed in the Style Editor Settings to allow for what ever color necessary.

As for how to optimize a raster image... it's likely best to use tools to adjust contrast and brightness or better yet.. binarize... which will make the raster image black and white.  Then the conversion to vector has a better chance of being optimized because it only has to deal with the color black.

**Comment by RodneyBaker** [comment]
Here's an attempt at one of your brushes from the lower left corner of your example sheet:

![image](https://user-images.githubusercontent.com/2576432/150270935-cfb822ad-69c9-4a70-848c-cde26a8e6ab3.png)

**Comment by Carpyboi** [comment]
how do i crop to the line?

**Comment by Carpyboi** [comment]
by the way, the brushes I used for csp are all .sut files, not sure if they're useful to you.

**Comment by RodneyBaker** [comment]
For fast cropping I use a program called Irfanview.  It can be done in Opentoonz but I have my standby programs to do basic tasks.  One easy way to crop an image in OT is to just select the part of the image you want and copy.  Then paste that into a new blank raster level.  Done.   You don't have to be picky about the crop as it is just needed to get to the conversion process.

Here's an attempt at one of the more dangerous brushes (due to the detail and number of vectors that can end up in the brush prior to optimizing):

![image](https://user-images.githubusercontent.com/2576432/150274955-ae4f8708-8e14-4e77-81df-3c44ddffa673.png)

I crashed while trying to create this one but this helps me refine the process.  ;)
I was actually please with how well the dry brush worked as I didn't think it would convert well.

**Comment by Carpyboi** [comment]
Ok. loaded the brush shape I want onto opentoons, but now I can't convert it to vector due to current selection being invalid. I cropped to the brush with clip studio paint. What am i doing wrong?
![o](https://user-images.githubusercontent.com/98064801/150276925-c6f498dd-af79-41d1-bf4a-c098184319be.png)

**Comment by RodneyBaker** [comment]
You probably don't have  your raster level (the blue cell in the xsheet) selected.

**Comment by Carpyboi** [comment]
which setting works best, centerfield or outline?
![ye](https://user-images.githubusercontent.com/98064801/150280949-a3343720-05c7-4a4f-937a-651b4ba263ad.png)

**Comment by RodneyBaker** [comment]
Flip a coin or...

Consider that more detailed and noisy images will produce more complex vectors.
Consider that if choosing Outline you'll want to preserve the fills... and fill those.
Consider that if choosing Centerline the shape might not make a lot of sense and be harder to edit.

There is an option in menu:  Level > Optimize > Simplify Vectors that you'll like want to run (perhaps even multiple time on the resulting vectors to reduce their complexity.  It is easy to make a duplicate of the vector (using D key) to test on before adjusting further.

You may wish to join the Opentoonz discord (chat) to get more timely response and more immediate back and forth.
Especially as github is more for bug reporting.  If you have problems finding the discord just let us know.

**Comment by Carpyboi** [comment]
ok.

**Comment by Carpyboi** [comment]
Where can I find the discord?

**Comment by RodneyBaker** [comment]
There are several Opentoonz related discords, none of them technically the offical Opentoonz discord but all are well attended and have very helpful folks hanging out, chatting, solving problems, drawing/animating and generally having a good time.
I don't mean to leave any discords out here but the three most active (to my knowledge) are:

Opentoonz discord:  https://discord.gg/UQxvYBKW5U

Tahoma2D discord (official discord for the T2D fork of Opentoonz):  https://discord.gg/3S4Arr2HyY

DarrenT discord: https://discord.gg/bFEucKzHFa

As I say there are more but those are the ones that I visit often.
