### ISSUE TITLE
Saving scene with audio causes opentoonz to close

### ISSUE THREAD

**Issue by superninjakiwi** [opentoonz/opentoonz#4237]
**Describe the bug**
When saving a particular scene, it saves the scene (no work is lost) and then closes the program. Other, similar scenes (similar length of 5000-6000 frames, and with a similar audio file) do not cause the issue.

**To Reproduce**
1. Open the problematic scene
2. ctrl-s, or file/save all
3. The program saves, then closes.

**Expected behavior**
The program should not close after saving. 

**Screenshots**
https://i.gyazo.com/8889ca5bd91c95d2641b2496034282a6.mp4

**Device Information:**
 - OS: Windows
 - OpenToonz Version: Nightly (Jan 28 2022) (Updated specifically to see if the new version would fix it, it did not.)
 - GPU: NVIDIA GeForce GTX 1080
 - GPU Driver Version: 27.21.14.5671

**Comment by RodneyBaker** [comment]
@superninjakiwi  Is there any way you can zip up the problematic scene and share it?
That would likely assist in understanding what specifically is going on with your scene.

Barring that you might just have a corrupted scene in which we'd either have to repair the scene or replace it using the levels you still have available.

**Comment by superninjakiwi** [comment]
Sure, I've done almost nothing in it, here it is. [Watching Me.zip](https://github.com/opentoonz/opentoonz/files/8007547/Watching.Me.zip)

I fit my frame count to the audio file I'm using, a song. I'm not familiar with animation yet, so I figured I would just plan the whole thing out, and figure out how the actual scene stuff works later. I didn't really know any other way to match each frame to the desired part of the audio file, so if one of those actually exists for me to have different scenes in a project use certain parts of the audio file, that would be a huge help.

**Comment by RodneyBaker** [comment]
Thanks for sharing that.  Much appreciated.

An initial cursory look suggests:
- I too get the project to save and then Opentoonz crashes
- I suspect the audio file has something to do with the problem but need to run more test.

**Comment by RodneyBaker** [comment]
If I attempt to recreate the scene... loading the original audio** and creating new columns of drawings...
The problem goes away.

It seems the scene file itself may have a corruption because even after removing the audio file from the original I still see instances of audio levels in the scene file.

**I did rename the audio file to simply "audio.mp3" as a test to avoid the special characters.
In general it is good to avoid any special characters and a file named "High Maintenance & Mediks - Watching Me (Ft. Georgina Upton).mp3" is asking for trouble.

Because you are so early in the process I'll recommend starting a new scene and (after renaming the MP3 file) loading that.  You should be able to load your levels also but might find that just as easy to create from scratch also.

**Comment by superninjakiwi** [comment]
Alright, thanks for the help. I'll leave the issue open in case it seems like something that can be resolved, but if the issue seems too difficult to reproduce from scratch and the cause of corruption isn't obvious, feel free to close it.

**Comment by shun-iwasawa** [comment]
Crash occurs due to an unused palette level named `Effects outline` in the scene cast.
Removing it seems to resolve the crash. I will investigate further why the missing file causes such problem.
