### ISSUE TITLE
Playback slow with Xsheet

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#4253]
I'm noticing inconsistent playback slowness issues that I've traced back to PR #4197.

- Case 1:
I loaded an older scene I had done that was at 30FPS (11 vector columns + 2 meshes).  In both Timeline/Xsheet, it plays back 17-19 FPS. In the original release and in the 12/24/2021 nightly prior to Enhanced Flipbook playback was merged, it plays at 29-30 FPS.

- Case 2:
I loaded another older scene at 24FPS (14 vector columns + 4 sub-xsheets).  On the Timeline, it played more consistently at 24 FPS, but in Xsheet, it flips quite a bit between 22-25 FPS.  In the original release and in the 12/24/2021 nightly, it plays consistently at 24FPS in either.

- Case 3:
I was using a 1/27 nightly playing back a 24FPS scene (various types of columns). It would play back anywhere between 12-15 FPS when using an Xsheet.   Switching the Xsheet to Timeline mode, the playback was a bit faster, but still slower (20-22 FPS) than expected.  

It seemed the more columns/rows that are visible in the Xsheet the slower it got.  This does not appear true for Timeline which seems odd considering it's the same code.

Another oddness about this case is it suddenly started playing back relatively normal. As I was testing this issue out trying to see what conditions might be impacting it, the problem was consistent for a least an hour or more, no matter how many times I restarted OT or reloaded the scene.  Then all of a sudden it was fine.  

No idea what  I might have done to correct the problem but couldn't reproduce this specific scenario again with the same scene.  However, similar to other scenes, Timeline played back more consistently at 24 FPS, but in Xsheet it would vary quite a bit between 21-23 FPS

**Comment by shun-iwasawa** [comment]
I believe that the viewer before #4197 did not show proper FPS and irregularly dropped frames on playing.
When I worked on #4197 , I found that calling `QOpenGLWidget::repaint()` does NOT repaint the frame immediately unlike other widgets.
Therefore, redraw timing cued by `PlaybackExecutor` and the actual execution of redraw in `SceneViewer` had been asynchronous, i.e. sometimes `paintGL()` was called twice between the cues and sometimes no `paintGL()` was called. Such behavior made the calculation of FPS incorrect and caused irregular playback.

The speed difference between Xsheet and Timeline would be a separate issue... I need further investigation, but it may be because Xsheet shows more cells than Timeline in the visible region which needs more time to repaint.

**Comment by melieconiek** [comment]
This issue causes playback to be noticeably slower compared to previous versions. If the scene contains audio it causes the audio to crackle because it's not running at the proper framerate. This issue is dramatically worse on high resolution monitors.

**Comment by melieconiek** [comment]
It's also worth mentioning that the playback issue is not present if there is no timeline or xhseet open in the current layout.

**Comment by justburner** [comment]
Timeline/Xsheet isn't hardware accelerated and viewer playback is causing a repaint per frame... of course things will be slow when there's several hundreds of little square cells with fancy decoration, lines, text, etc.

One temporary suggestion is a checked button in both viewer and timeline/Xsheet that can enable/disable synchronization to prevent 24 repaints per second when the user just want to playback the preview smoothly.

**Comment by RodneyBaker** [comment]
I've added this to the Bug Hunt not so much as a bug but definitely as a showstopper as users are reporting thhe slowdown is considerable and troublesome.

**Comment by shun-iwasawa** [comment]
I think it would be worth trying that reverting the playback behavior for the Viewer / Combo Viewer.
Because the main purpose of the modification #4197 was for improving Flipbook and as @justburner pointed, calling `qApp->processEvents();`  in the Viewer panel causes redrawing all other updated panels such as Xsheet / Timeline which seems to be time-consuming.
