### ISSUE TITLE
Crash when undoing a collapsed scene

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4266]
As in last Tahoma 2D built, Opentoonz crashes when I collapse and undo the action.

To reproduce, select some nodes in a scene, then go to Scene -> collapse, and press ctrl + z to undo the action.

This one is the built 2022-02-17 08:04:12 UTC

**Comment by RodneyBaker** [comment]
I'm unable to reproduce the issue but that might be because I get lost when you say "then go to Scene -> collapse..."
It isn't entirely clear where you are going in order to get to a this.

**Comment by F-Burning** [comment]
This happened to me on Tahoma and Opentoonz yesterday.

What I did was this:

Select the nodes with the rectangular selection...

![oo](https://user-images.githubusercontent.com/74098734/155013909-b31947db-0d09-4795-86e6-cc0bef1ba6fd.jpg)

...and then collapse them.

![56](https://user-images.githubusercontent.com/74098734/155013986-4b33403c-5481-4ea3-910a-70cf2f551aa1.jpg)

Perhaps by having many nodes (not too many), and then collapsing them, the program crashed.

**Comment by RodneyBaker** [comment]
Tagging with crash although as of yet no one is able to reproduce.
Perhaps that will get some additional eyes on the problem.

**Comment by gab3d** [comment]
I just tried it to all the extents I could imagine, with no unusual resultts. I've collapsed, grouped, grouped and then collapsed the group with some ungrouped nodes...  🤷🏻‍♂️
sorry

**Comment by F-Burning** [comment]
Now crash simply adding effects.

![10](https://user-images.githubusercontent.com/74098734/156071431-5f521deb-8614-49ab-b809-feb56d152c2b.jpg)

Maybe the bug is in the gradient, or in the blending nodes.

**Comment by RodneyBaker** [comment]
It will be good to get your computer specs and operating system information to include any peripherals, multi-monitors etc.   If  you are building your own program from source that is also useful to know.  In short, we would like to recreate your current variables to the best ability to best investigate the problem.**

Tahoma2D has additional crash reporting options so if the problem is present there you should be able to submit that crash report to @manongjohn and that data will help in better understanding the problem.


**For users who often report bugs/crashes that don't want to constantly post their computer specs it may be advantageous to post that online somewhere and then link to that information in the report.

**Comment by RodneyBaker** [comment]
Tested again and still cannot reproduce this with Opentoonz.

**Comment by RodneyBaker** [comment]
Will close as @F-Burning has stated that the crash is no longer occurring (as of Feb 2022).
@F-Burning Please let us know if the problem returns.
