### ISSUE TITLE
Project Settings 1,2,3,5 ?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#4274]
Is it correct that the options of this drop-down are: 1, 2, 3, and 5 ?  🤔 

![imagen](https://user-images.githubusercontent.com/18104091/155217284-43d897a5-4d22-4be8-ad7f-e273c83787aa.png)

**Comment by artisteacher** [comment]
Good catch. I see this in T2D too.

**Comment by shun-iwasawa** [comment]
~~It's because "4" is a sort of taboo number in Japan as it pronounce ("shi") as the same as the word "death".~~ 
:-)

Well, I just thought that users won't care so much if they can choose `5` or `Unlimited` even if they mainly use 4 letters suffix. If you particularly would like to have `4` , I'll add it!

**Comment by gab3d** [comment]
👻 no problem for me. 
it's just peculiar, but I think most users will never use it anyways. thanks for the honest explanation 😁

**Comment by RodneyBaker** [comment]
Closing as this question is answered.
I do get a sense this UI related tweak might return so we should keep it in mind for the next UI scrub.
