### ISSUE TITLE
Memory could not be read

### ISSUE THREAD

**Issue by Snevetz74** [opentoonz/opentoonz#4294]
**Describe the bug**
Memory could not be read. Happened while rendering

**To Reproduce**
List steps to reproduce the behavior.
1. Rendered in Opentoonz 1.5
2. At 16% rendering point frame, the following "Application Error" occurred: Referenced memory could not be read.
3. Attempted to render 3 times. no success

**Expected behavior**
Expected behaviour is the scene is supposed to render. I'm guessing this is a 'memory leak' in the plastic tool.

**Screenshots**

**Device Information:**
 - OS: Windows 10
 - Processor: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
 - System: 64-bit operating system, x64-based processor
 - OpenToonz Version: 1.5

Screenshot (below)
![Opentoonz Error](https://user-images.githubusercontent.com/69117986/156560985-277a52b5-69fb-4d6b-93c9-a4fe4841e66f.jpg)
![Opentoonz Error](https://user-images.githubusercontent.com/69117986/156561023-b5cf5f86-4472-4402-b23b-5276a98e326b.jpg)

**Comment by RodneyBaker** [comment]
With the number of frames you have and the know issues encountered with plastic tool with many frames...

Recommend rendering via Task Render (batch rendering) and if you aren't doing so rendering to sequential images rather than a video format.  Then later the sequential image can be collected into the video format where use of plastic tool won't be a factor.

If you haven't used Task Rendering before perhaps the easiest way to do that initially is to use the browser to find your .tnz scene file, Right Click and Add to Task Rendering.  Then go to the Tasks room and launch your render.  If a specific frame or frames fails you'll know exactly where and can then will only need to rerender those frames.

**Comment by Snevetz74** [comment]
Thanks. I actually deleted the old mesh level and created a new mesh level.
It took awhile, but rendered fine without crashing.

**Comment by RodneyBaker** [comment]
Glad to hear you got your frames rendered.
Will close this as other similar reports open related the memory issue and plastic tool.
Will try to remember to include a referral to this report in those when reviewing.
