### ISSUE TITLE
problems with rooms in v1.5

### ISSUE THREAD

**Issue by Q210108** [opentoonz/opentoonz#4305]
there are many problems with rooms : 
- when creating room, and reopen the project, the room i created disapear, there is no room saving.
- when creating room, sometimes when i lock rooms, the software shut down
- THERE IS NO BASICS ROOM THAT WAS IN PREVIUS VERSIONS.

**Comment by DarrenTAnims** [comment]
The rooms were changed for V1.5 and the Basics room was taken out. The Drawing room is almost the same, but you can change the rooms to any layout you like.
If your rooms aren't saving then it's likely to do with your virus checker not allowing files to be created in your OpenToonz Stuff folder (where all the settings are stored).
I've been using V1.5 since it came out and it saves my rooms, so the problem will be something to do with your file system.
Good luck.
