### ISSUE TITLE
Excessively slow to open

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#4307]
**Describe the bug**
Opening OT takes at least 77s - it feels so, so slow. It seems to be stuck on "Creating Main Window" for most of that time, before OT actually opens. 

Some users have had crashing or hanging on open [in the google group](https://groups.google.com/g/opentoonz_en/c/s2i-sgUcHXA) - they haven't specified their system, but it could be related.

I didn't have this problem on my last mac running Catalina. I wonder if it's related to either macOS Monterey or using an M1 mac. 

**To Reproduce**
List steps to reproduce the behavior.
1. Install OT
2. Open OT

**Expected behavior**
I expect OT to open much faster - similar to T2D which opens in around 4s.

**Device Information:**
 - OS: macOS Monterey 12.2.1
 - OpenToonz Version: recent nightly builds, recent action builds, 1.5, 1.3
 - GPU: M1 Max

**Comment by RattusaurusRex** [comment]
Both finish loading in 13 seconds for me on Windows, although it does depend on how recently I've had the program open.  I haven't opened Tahoma in a while, so it took 44 seconds on the first try.

**Comment by artisteacher** [comment]
Yeah, I'm pretty sure it's a Mac thing. I don't have this issue with Intel based Macs running Catalina -  though I'm not sure if it's the OS version or the Rosetta 2 emulator for M1 chips that makes the difference. I can't update the school computers to find out.

Unfortunately it's not just a problem on the first open. Every open is at least that slow. The length of time between makes no discernible difference.

My Mac is nearly maxed out as far as the specs go - it's fast. Nothing else takes me anywhere near that long to open. I'm concerned that the opening time might be slower or even fail completely for similar setups but with lower specs.  This could turn off new users before they even get started.

**Comment by artisteacher** [comment]
We should also look at what's different in the build environments for T2D and OT. Being portable doesn't seem to be the difference because the artifact builds for PRs open just as slowly.

**Comment by artisteacher** [comment]
I am getting faster opens today for whatever reason - but still on the slow side at 34s. T2D is the same as before, just under 4s.

**Comment by RodneyBaker** [comment]
@artisteacher Still excessively slow opening on your Mac systems?

**Comment by artisteacher** [comment]
Seems to be better now in the nightly builds.

**Comment by RodneyBaker** [comment]
Thanks @artisteacher 
Please feel free to either reopen or (better yet) create a new report if you note similar sluggishness in the  future.

Opentoonz generally loads faster than most programs I use and we need to keep it that way.
Where possible I hope we can get OT to load even faster.

What I've seen is that the number one reason for slow opening of the program is the number and types of plugins prepped to launch.  In my estimation it would be good to find a way to delay activation of plugins until after the program has opened and more dynamically.  A short form workaround on the users end would be to place unneeded effects/plugins in an "inactive" directory and move them into the main directory as needed.

This isolation approach is also a way to determine what (if any) plugins are problematic and that shouldn't be loaded at all.
Different plugins also use different support files such as OpenCV DLLs and those get updated from time to time.
Something to check regarding the T2D plugins is to make sure the OpenCV DLL that accompanies those plugins is also available in the Opentoonz directory.  I do think that if the support file is outright missing Opentoonz will stop and launch an error message so that problem should be obvious.

General sluggishness... will always be something we need to be on the watch for and plan to remedy wherever possible.
