### ISSUE TITLE
Shift and trace options doesn't work with F1, F2, F3 and F4 shortcuts

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4347]
If I use these keyboard shortcuts, none of the shift and trace functions work normally.

I'm using the last Opentoonz built in Windows 10.

**Comment by shun-iwasawa** [comment]
You mean that you tried to assign F1, F2 or F3 key to `Shift and Trace` or `Edit Shift` command?

When the `Shift and Trace` mode is active, pressing F1, F2 or F3 key in the Viewer will be overridden by "flipping" feature: i.e. holding F1 / F2 / F3 key will display only the previous / current / following drawing respectively.

Since they are reserved, please assign other keys for the `Shift and Trace` -related commands.

**Comment by F-Burning** [comment]
Now I understand why the strange behavior, I will change the keyboard shortcuts. I'll close the issue now it has been solved, so thank you very much for the clarification and sorry for the inconvenience!
