### ISSUE TITLE
Viewer vs. comboviewer

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#4359]
**Question**
Is there a reason or a benefit to using the viewer over the comboviewer? The comboviewer just seems much more flexible since it has the same capability but can toggle display of the horizontal toolbar and tool options on/off.

**Comment by RodneyBaker** [comment]
As I understand it, that is the main difference... and benefit... that of the toolbars.

The 'combo' in Combo Viewer refers combining the Viewer with the Toolbars.
The toolbars can be hidden so the Combo Viewer looks and acts much like that of a regular viewer.

Using the Combo Viewer the user can remove the toolbars from their rooms and still have access to the toolbars via the Combo Viewer.  The reason some users might prefer the Viewer over Combo Viewer is where they just want the viewer.

If memory serves correctly, the Combo Viewer gained the ability to have the toolbar and options bar hidden.
Prior to that it was always visible. 

For further information you may be interested in #873
There Jeremy updates viewers to be more similar and Shun explains why the combo viewer got more attention and the regular viewer did not.  Jeremy's PR brought them back more into alignment.  I'm sure there are some other PRs that address differences as well.

**Comment by artisteacher** [comment]
If there's no difference in performance, I'm just wondering what the point is of having and maintaining both? 

Wouldn't it make more sense to just have comboviewers, but to keep the tools/tool options off by default in most cases? It would be more flexible. We could even keep the two menu items, but the standard viewer would be a comboviewer with the controls turned off. 

Unless there is some actual benefit to the standalone viewer...

**Comment by RodneyBaker** [comment]
I sensed the deeper consideration of potential deprecation in your original query.
It's a certainly a valid question.

It would be good to examine the code behind each and determine cost vs benefits etc. of maintenance and potential for user confusion between the two.  Here for instance, we have you (@artisteacher) not sure about the differences and if someone as well versed in Opentoonz doesn't particularly know we can hardly expect a new user to know.

I'd say before removal of the standard viewer it might be good to take a broader view of all of the various 'viewers' present in Opentoonz.  This way we can see a bit more of the field of interest before us.  For instance, the Flipbook and Schematic viewer. Examining the differences therein will surely help.

Off hand I'll speculate that having the two different viewers actually with different code can have a benefit development-wise in that one can be used more for testing, experimention and optimization while the other remains the standard go to viewer that productions routinely rely on.  This then can trade back and forth as users find themselves relying more on one than the other and usage reaches a critical mass.  The new secondary viewer then becomes the test ground for the next iteration.

As Shun pointed out in the related PR, development of the standard viewer stopped because Studio Ghibli was using and focused on the Combo Viewer.  One could argue that to a degree that interest has shifted to live camera view, flipbook and schematic viewer as those lean into optimizations for realtime processing.

All this to suggest that Opentoonz has a wealth of viewers and where possible and reasonable the code should be shared between them all.  This doesn't however mean that viewers used less often don't also have room for usage and development.  They may in fact be prime areas of interest for additional development.

For consistencies sake it would be good to focus on workflow intended for specific viewers specifically with regard to interaction from the user.  As such...

This query seems ideal for asking of @manongjohn whose fork might benefit the most from having one less viewer given it's new user ease-of-use orientation.  He also will likely know a lot about the differences in code between these two viewers as well as the other viewers in the program.

**Comment by RodneyBaker** [comment]
Closing but feel free to continue discussion of the merits of viewers in Opentoonz.
