### ISSUE TITLE
(Tahoma2D port) Draw order for vector brush

### ISSUE THREAD

**Issue by FerrLui** [opentoonz/opentoonz#4370]
We sadly dont have "draw order" function  for vector brush .
 In Tahoma 2D we have this feature  a long time. For  vector brush tool we have 3 options:
  1 Under all
  2 Over all
  3 Pallete order
 This is very handy, so why we dont have it in opentoonz yet? I think its a very important part of brush tool.

**Comment by gab3d** [comment]
I think you are slightly confused with the Toonz Raster (Smart Raster) level options for the Brush tool in Tahoma2D.
What it offers for Vector levels is a "Draw Under" option. Indeed very helpful.

**Comment by FerrLui** [comment]
@gab3d  Oh, your right. I think even Draw under function will be very halpfull.

**Comment by F-Burning** [comment]
Yes, even in Raster levels this option would be helpful when work with external drawings.

**Comment by RodneyBaker** [comment]
Marked as roadmap as it is likely we'll see this feature either ported or brought online along with other vector drawing options in the (not too distant) future.

My own personal take is that many of the current vector drawing options should probably be given a shortkey assist so that in using say a shift key we shift from drawing on top to drawing underneath.  Ther is of course then also the matter of all strokes inbetween the nearest and farthest.  For that we would need some methodology to draw under a currently selected stroke, object or group.  This latter part will take considerably more effort to incorporate but porting of current Draw Under capability from Tahoma is certainly a logical next step.

**Comment by RodneyBaker** [comment]
For purpose of discussion I'll add here that we do currently have (in OT, T2D and all the forks) an Over All capability.
That is the regular placement of vector strokes on the canvas.

Something not quite as well understood or conceptualized in the UI is the ablity to enter a group and then draw Over All inside that group.

It seems clear that at some point we'll get groups and strokes exposed via heirarchical listing so that:

1) We can see where our strokes are in relationship to groups and shapes
2) We can reorder those strokes via drag/drop
3) We can move strokes into and out of groups (and name those groups for management and search)
4) We can select a stroke or group in the heirarchy and immediately draw on top of that selected object
5) To greatest extent possible the maintenance of these groupings will be automated**

**For more on this grouping automation please see the Graphical User Interfaces section of the free course from Takeo Igarashi
  of Tokyo University via Coursera Link: https://www.coursera.org/learn/interactive-computer-graphics
Note here that while the lesson relates to desktop icons the idea would be to use this grouping approach for the automated management of vector strokes in drawings.

**Comment by RodneyBaker** [comment]
This is somewhat of a duplicate feature request although this request is slightly more broad in nature from the previous request that concentrates on palette order.  REF:  #3549
