### ISSUE TITLE
Level Strip causes OpenToonz to crash when cutting nothing

### ISSUE THREAD

**Issue by Mondaley99** [opentoonz/opentoonz#4392]
Since the Delete button removes just the content of the frame and not itself, I have to cut it (this isn't intuitive at all). That being said, It's normal that I press Ctrl+X more than I intend. So in some of the cases in which I "delete" them all, I press Ctrl+X once more (not on purpose) while the level strip is empty and then the program crashes.

Reproducing the bug:
1. Select a random Level from the XSheet you have dtawn
2. Select all frames from the Level Strip and press Ctrl+X twice 

Expected behavior:
It shouldn't crash.

Device Information:
 - Windows 10
 - OpenToonz Version: 1.6
 - GPU: AMD Radeon(TM) Graphycs
 - GPU Driver Version: 26.20.14040.0

**Comment by DarrenTAnims** [comment]
Firstly, I agree that pressing Delete on the level strip should actually delete the drawing (frame). It's wrong it removes the lines and fills and not the actual drawing. And that you have to use Cut to remove it. That really is unintuitive and NO ONE knows that this is what it should do. So Ideally, the delete option would change to actually delete the drawing.
That being said, this bug should be fixed as soon as is practical.

**Comment by Mondaley99** [comment]
> Firstly, I agree that pressing Delete on the level strip should actually delete the drawing (frame). It's wrong it removes the lines and fills and not the actual drawing. And that you have to use Cut to remove it. That really is unintuitive and NO ONE knows that this is what it should do. So Ideally, the delete option would change to actually delete the drawing. That being said, this bug should be fixed as soon as is practical.

I think the ideal solution for this is to add four different options:
1. Cut Content
2. Cut frame
3. Delete Content
4. Delete frame
The paste option has already got such features via ”Paste Insert” and ”Paste Into”

**Comment by openanim** [comment]
Personally, I'm not in favor of this unless it's optional because it impacts my workflow a lot. Personally, I use the eraser tool very little and use the "delete" shortcut on my stylus in the softwares to delete something. But this also deletes the content in the level strip dans OT. And for me, It is a convenience to use the same key.

**Comment by gab3d** [comment]
Perhaps "Ctrl + Del" could just be added to delete selected frames in Level Strip.
This would not impact current workflows, but at the same time it would give a more intuitive approach for deleting frames for new users.

**Comment by Mondaley99** [comment]
> Perhaps "Ctrl + Del" could just be added to delete selected frames in Level Strip. This would not impact current workflows, but at the same time it would give a more intuitive approach for deleting frames for new users.

Ok, I agree that overcomplicating the interface is not the greatest solution. I think, your idea of introducing Ctrl+Del is a better alternative than mine. Despite all of that, I have looked through other problems related to the level strip and found out that this kind of workflow we are used to is actually the way devs want OT to work.  As a result, I believe we won't see any chances for this topic any time soon.

**Comment by DarrenTAnims** [comment]
I still don't think adding Ctrl+Delete would help. No one would think to hold Ctrl to delete a drawing. This would be yet another hidden feature. If a change was to be made, changing to a situation that is used in other software, that is discoverable and is obvious would be the best thing: Selecting a drawing in the Level Strip and pressing Delete to delete the drawing really is what you would expect to happen and is the only thing you'd expect to happen.
If deleting all of the lines is a required 2nd feature, then by all means, add a Ctrl+Delete for that. But otherwise, there are more options for this in the viewer, where the actual lines are:

- In a vector level, you can select all of the lines and press delete
- Use the selection tool to draw a large rectangle (or other shape) then press delete
- Use the eraser tool in rectangle/freehand mode (no delete necessary)

**Comment by Bracket-H** [comment]
I kind of like that it deletes the content of the drawing, myself, but I also find that using cutting the image to remove it strange.

Backspace seems to be free by default.

**Comment by gab3d** [comment]
I can see that what "users should expect" when pressing the delete key is debatable, as it'll always depend on each user 's previous experiencees.

In any case, I think perhaps the current Del behavior could be renamed to "Clear Drawing", to distinguish it from "Delete Frame" (Ctrl+ Del). 
Then, which one of these commands is asigned to what shortcut key combination, I think is secondary.
As, if both commands are shown in the right click menu, together with their correspondent shortcuts, they will be discoverable by users wanting to do those things.

**Comment by artisteacher** [comment]
> I kind of like that it deletes the content of the drawing, myself, but I also find that using cutting the image to remove it strange.

I completely agree. Using the clear command is faster than using the selection/eraser methods. Technically it is behaving just the same as the Xsheet. Delete empties the frames. Cut removes them. Now it makes sense to me and I prefer it, but as a new user I was definitely confused.

Backspace could actually be problematic too. On mac standard keyboards, our only delete key is the equivalent of backspace on a PC. There's a modifier key that can make it behave as a forwards delete, but it's not something every mac user knows.  Honestly, I forget to use the modifier 95% of the time and get irritated when things don't delete. Or I just use cut instead, since cut always works. I usually don't bother changing the shortcut itself since I update too frequently. Anyways, delete is such a basic function, it should just work without any remapping required.

If clear was changed to backspace, some users would be surprised their delete key suddenly works in just the one context and still end up wondering why their delete key doesn't actually remove the frame.

Personally I really wish that either backspace/delete were mapped the same, or that backspace was set as the default delete shortcut on macOS builds, or that multiple shortcuts could be set for a single command so that both delete and backspace could be the default for delete by default, but either one could be remapped to a different command if a user preferred to.  The last option is probably preferable since it could also help with zoom commands not working (and not being standard) on the mac standard, non-extended keyboard.

Pretty much all of those would rule out backspace as a default clear shortcut though.  I would never even think to try ctrl+del, unless I specifically noticed it in the menu. It's not a bad option though, since clearing isn't a standard behavior either. Though it would ruin the continuity between Xsheet/level strip delete behaviors.

**Comment by Bracket-H** [comment]
I see. Never used a Mac, yeah, that would not be very friendly to the users.

**Comment by RodneyBaker** [comment]
There is something of a feature request here and that should certainly be discussed further but I've specifically tagged this report with 'crash' to make sure we get the proper attention on that.

Thanks @Mondaley99 for the report.

**Comment by RodneyBaker** [comment]
Crash report from my system:

[Level Strip Control X twice.txt](https://github.com/opentoonz/opentoonz/files/9314366/Level.Strip.Control.X.twice.txt)

**Comment by RodneyBaker** [comment]
Just a note to suggest that reassigning shortcut keys might be an option for those that have problems with Cut vs Delete in the Level Strip.  I'm currently reassigning Delete to Delete key and Cut to Control X to test this out and see what adverse effects it might have on my own personal workflow.

**Comment by RodneyBaker** [comment]
@Mondaley99
You are prehaps the most likely to suggest #4588 meets the requirements of your request.
If you are able to test the github artifacts and give feedback that will be much appreciated.

cc:  Everyone else contributing to this discussion.  :)

**Comment by RodneyBaker** [comment]
@Mondaley99
You are prehaps the most likely to suggest #4588 meets the requirements of your request.
If you are able to test the github artifacts and give feedback that will be much appreciated.

cc:  Everyone else contributing to this discussion.  :)
