### ISSUE TITLE
can't save the file——help me please！！

### ISSUE THREAD

**Issue by Jate-1** [opentoonz/opentoonz#4399]
I use the opentoonz for Mac
When I use it normally, suddenly there is a prompt that the file cannot be saved

[https://docs.qq.com/doc/DTHpvdnBUWExQd2N1](url)

When I open the software again, it prompts me
“A prior save of Scene /scenes/004.tnz' was critically interrupted.
A partial save file was generated and changes may be manually salvaged from 'scenes/004.tnz.tmp'
Do you wish to continue loading the last good save or stop and try to salvage the prior save?“

But I don't know how to get it back，I can‘t open the “004.tnz.tmp“

could you help me how to fix this file please！
Looking forward to your reply！

**Comment by RodneyBaker** [comment]
If you can zip up the file and share it here we might be able to at least determine if it is salvageable.

If you previously saved the scene there should be files in your directory with a .bak extension (example:  myscene.tnz.bak).  These are backups created at the time the scene was saved.  Removing the .bak extension (so that it is named something like 'myscene.tnz' again may restore your scene to that point. 

Note that if you have a current scene with the same name as the backup you will have to temporarily rename that in order to rename the backup file with that name.

**Comment by Jate-1** [comment]
@RodneyBaker thanks for your reply ,i have tried this way ，but it doesn't work
I am already zip up the file, please download it here 
https://drive.google.com/file/d/1LHwlizF3tFA_psSfcWixnaj0ZS0JdsaK/view?usp=sharing

**Comment by RodneyBaker** [comment]
Have you tried just continuing the loading process?
I'm not sure what changes you might have made beyond what that restores.

Here's what I get if I turn on the background and move the start mark to frame 1:

https://user-images.githubusercontent.com/2576432/164980137-375cd63c-fa37-41be-ae4c-e3e1f9b81b6f.mp4

Nice work BTW!

**Comment by Jate-1** [comment]
When I open the file, I can continue to work, but still cannot save. Anyway, thanks for your help！！！Although Opentoonz still has some little bugs, it is still a very good software!

 I am making an original animation short film, this is my first time learning and using Opentoonz，if you don't mind,  I can send it to you when I am done it.

**Comment by RodneyBaker** [comment]
Since you are on a Mac we may need to get a Mac user to confirm some things.
You definitely should be able to save but perhaps some security feature is causing issues.
I must assume you've tried to save under a new name and in a different location.

I didn't have any problem saving your project on my end.
Double check and make sure you are attempting to save to a allowable location.

**Comment by Jate-1** [comment]
I have tried various ways, I don't know if there is something wrong with my operation? please see my recording
https://drive.google.com/file/d/14Hx76dZgIBUPRE0T7QULWod5YUL4dbek/view?usp=sharing

**Comment by artisteacher** [comment]
I haven't run into this specific saving issue on macOS myself.

I would remove any unused levels from the scene - this can help with certain saving issues. In the Browser room, right-click in the scene cast and choose "Remove All Unused Levels":
<img width="757" alt="Screen Shot 2022-04-28 at 4 49 54 PM" src="https://user-images.githubusercontent.com/21159116/165843538-69d4fa49-f865-4d86-bacf-4feb98753747.png">

If removing unused levels doesn't help, I would try exporting the scene to a new project in a different location. In general, I recommend making your own projects, rather than using the sandbox. Using a different location makes updating easier in the future. Using a different location might also prevent permissions issues.

You can choose your own location in Preferences -> General:
<img width="213" alt="Screen Shot 2022-04-28 at 4 45 29 PM" src="https://user-images.githubusercontent.com/21159116/165842766-1afc623f-5a78-44bc-b7ee-2f80d8a93841.png">
I think you might need to restart after enabling a different project location. 

Once you have the new location enabled, export the scene to a new project in that location:
1. Right-click on the scene in the Browser and choose "Export Scene"
2. Select "Create New Project" 
3. Choose the 2nd project root 
4. Type a name & then export
<img width="211" alt="Screen Shot 2022-04-28 at 4 53 50 PM" src="https://user-images.githubusercontent.com/21159116/165844310-302e2ed0-a1c5-40da-9813-7529cc33f8ac.png"><img width="262" alt="Screen Shot 2022-04-28 at 4 54 22 PM" src="https://user-images.githubusercontent.com/21159116/165844017-13a66ed1-e0a6-4834-b2a8-719d145d577e.png">

**Comment by Jate-1** [comment]
Thanks for your reply, it's a good suggestion！thanks a lot！

**Comment by RodneyBaker** [comment]
Closing as partially resolved.
@Jate-1 If there is something else we can assist with please let us know.
