### ISSUE TITLE
"There were problems loading the scene ... Some files may be missing."

### ISSUE THREAD

**Issue by badcircumstance** [opentoonz/opentoonz#4457]
### Ask a question related to OpenToonz

I'm unable to open a project in Opentoonz that I've been working on for a short bit.
![hatredinmyevilheart](https://user-images.githubusercontent.com/106214026/170166746-41b7ca9b-d614-4f4d-8cee-523359a37365.PNG)
Every time I try to open the file, it does this?
I use Opentoonz 1.4, version 71.0, and Windows 10. The .bak file doesn't seem to open up either. I was using keyframes in my animation. This is the .txt file for my animation. The .txt for the .bak file is completely empty.  If this is an issue with how old my version is, than I might need some instructions on how to carry over my data from my current version to a newer one.
[newscened.txt](https://github.com/opentoonz/opentoonz/files/8767481/newscened.txt)  It seems that I'm missing quite a lot.

Thank you in advance. 

Edit:
I am aware that this is an old issue, and in my search for answers I have found nothing that helps me out. I still wish for some assistance on this, but I know it might not necessarily be possible. This animation was for a map part, and if I cannot get any word on the state of this animation, I'll probably have to tell the map creator I can't finish it. I still really, really want there to be some way that my stuff can be recovered. I'm getting a bit desperate here. I don't mean to rush or upset, but I've been kind of stalling and I want to be able to either finish my work, or give up and move on with the knowledge that at least there was nothing I could do.

Thank you.

**Comment by badcircumstance** [comment]
> There's lots of bugs been fixed since V1.4 (released 2 years ago), including a specific bug that broke scenes like this, because of incorrectly added keyframes (from the animate tool). You should upgrade to the latest version as soon as you can before starting a new project. I can't remember exactly how to fix it, but it is possible. Hopefully someone will remember and list it in these comments.

I've now updated to V1.6, which I'm sure is the latest official version. The issue still persists, which is expected but annoying! Thank you for your response. :-]

**Comment by RodneyBaker** [comment]
Will close this issue as one similar to other reports posted.
As for this specific report... perhaps the best way to troubleshot the issue would  be to share the project file with someone so they can dive in and determine what can be done (if anything).

In short, the problem needs more information and ideally the files involved.
It might be optimal to join an Opentoonz discord where members can address the issue in real time and... more importantly... help meet any pending deadlines.  As this report hasn't been updted since May 27 it's hard to know current status.

@badcircumstance Please let us know if we can be of further assistance.
