### ISSUE TITLE
Project pallette for cutout rig bases bug

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#4510]
### Description

if you make a cut-out rig base and try to make different color versions for different characters, the pallette used is still the same from the last cutout rig base project

![out](https://user-images.githubusercontent.com/36406840/186034890-7a6f940a-a46f-4b0d-806a-189c6ae2d395.gif)
[Nova pasta (2).zip](https://github.com/opentoonz/opentoonz/files/9398165/Nova.pasta.2.zip)

### Steps to Reproduce

explained in .gif

### Expected Behavior

each project pallette is used from its own folder

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

**Comment by age3rcm** [comment]
huh? how come there is no attention for this issue?

**Comment by RodneyBaker** [comment]
Just needs more information to better understand the issue and be able to move forward.
Especially as the problem is a bit niche and doesn't apply to many workflows common to active users that would otherwise have interest.  

Combine this with the lack of developers who might champion the idea along with the fact the report is only 20 days old and that will likely suggest why you haven't seen a high degree of interest.

The fact that palettes are level based and not project based likely also factors into the equation.

**Comment by age3rcm** [comment]
> the problem is a bit niche and doesn't apply to many workflows
this would be a core necessity of cut-out rigs as there will be reuse cases of character bases but with different acessories and needing to have colors edited for the body
> palettes are level based and not project based
in the gif its demonstrated it happens with projects, as to fix it just do a rename of the project folder
>Just needs more information
this is probably the config file referencing another pallete from a different project right?
what kind of information should be added?
i did try doing this on a same project, copy-pasting a swatch from a project pallete to another project pallete on the same project and this also gives this glitch

**Comment by RodneyBaker** [comment]
While not a necessity... What I will do in cases where I want to use the same palette across different characters is actually use the same level... just spread that level accross columns so that the images contained therein all composite together.

To test this particular approach think in terms of a project that only has one level where everything is contained in that level.

I'm not suggesting this is the ideal approach but it is a demonstrable way to ensure full control of palettes because all imagery is guaranteed to use the same palette.

The extension of this appraoch then is to duplicate the level for each unique character.
The down side of this is that the palette is in fact unique to that level and so any changes will cause differences between the palettes that might need to be accounted for.

One approach to keeping the differing palettes the same is to periodically update the palettes using some other palette that never changes (for example a studio palette) where that palette is pushed into the target palette periodically to keep them in sync.

I don't know enough about Linked Palettes to really suggest that as a solution but that would appear to be an ideal approach to your specific workflow.

Here is the documenation for Studio Palettes and linking (for those interested in following along the discussion):  https://opentoonz.readthedocs.io/en/latest/managing_palettes_and_styles.html#using-the-studio-palette-1

**Comment by RodneyBaker** [comment]
In looking into this I do see a refresh issue where a project needs to be reloaded in order for colors to catch up to the updated palette (when updated such as with a Studio Palette).

**Comment by RodneyBaker** [comment]
Relates to #4451

**Comment by age3rcm** [comment]
for the conversation on discord related to this bug, it seems to be something related to the "pallete path.ini" file. deleting them on both projects fixes the issue with wrong palletes colors being the same.
but after making alterations again, it have to delete the pallete paths again to work

could be there a way for the pallete code to look for a specific palette name or something?
are the styles on each level still looking for a pallete that does not exist or the pallete still has the old name or ID?

**Comment by age3rcm** [comment]
it still has the same ID regardless of name?
