### ISSUE TITLE
Images/videos not showing

### ISSUE THREAD

**Issue by AnIdiotWaffle** [opentoonz/opentoonz#4515]
### Description

When I try to import a level with the file being a png, mp4, etc. basically anything that has any sort of amount of pixels just doesn't show up, the only file format that actually works is jpeg/jpg but even then it sometimes crashes. I do have ffmpeg installed and i'm not sure what i'm doing wrong

### Expected Behavior

images/videos to actually show up

### Screenshots, Video & Crash Logs

https://drive.google.com/drive/folders/1Er6JhOoACuLsh2xnGiiTYo6O-5CnhwYx?usp=sharing

### OpenToonz Version

1.6

### OpenToonz Version Information

built march 31st 2022

### Operating System

macOS

### GPU

Other

**Comment by artisteacher** [comment]
Do you actually have ffmpeg setup properly? The folder that contains the ffmpeg executable also needs the ffprobe executable. 

On later versions of macOS, due to a security setting, you need to run both executables before OT will be able to use them.  If you right-click on each executable and choose "Open With --> Terminal", it should override the security setting and allow you to use them in other apps.

Or you could give the fork Tahoma2D a try - it comes packaged with FFMPEG so there's no additional setup.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and a common issue when settng up ffmpeg for use with formats such as gif and mp4.
@AnIdiotWaffle If still having issues troubleshooting the problem I'll recommend joining one of the Opentoonz discords where you can get assistance in real time.
