### ISSUE TITLE
Issue with ToonScript - img.save() not respecting filename?

### ISSUE THREAD

**Issue by ohsnapitsjoel** [opentoonz/opentoonz#4521]
Hi! Long story short, I'm writing a script to render my drawings only on the frames that they occur, and not render the held exposures.  I'm trying to name and number them according to their level name and frame number, so that I can go back and forth between other animation softwares.  

It's pretty slapped together, but I'm using
```
imgName = level.name + "_" + frameNumber + ".png";
imgPath = new FilePath(fPath + "\\outputs\\rendered\\" + imgName);
img.save(imgPath);
```
to try to save the files with names like "K_1.png", "K_25.png", but the only file that actually gets written to disk is called "K_0001.png", and rather than creating a new image for each frame with img.save(), it keeps overwriting "K_0001.png" with the new drawing. Is this an issue with img.save(), or am I using it incorrectly? I'm printing imgPath to the console while saving, and I can confirm it's correct.

If this functionality exists elsewhere in OT, I'd love to know about it and not keep spending my time on this script :)

**Comment by RodneyBaker** [comment]
The new Export to OCA feature will only render/export unique frames (and not their following exposures).
It won't take any keyframe animation into account however... only actual image frames.

**Comment by ohsnapitsjoel** [comment]
@RodneyBaker  Ahh, interesting! I just did some digging and read up on the OCA commits.  Learning more about it right now.  I actually have been using the nightly builds as of about a week ago, but I'm not sure where to find the option to export to OCA. I don't see it as an option in File > Export... is it located somewhere else?

**Comment by RodneyBaker** [comment]
As it has new UI elements you may need to do a clean install to get those menu items to appear.
Either that or you grabbed a nightly prior ot the feature being included.

![image](https://user-images.githubusercontent.com/2576432/187695233-fe1d1209-d0bf-4c92-9475-2e4ad8fc922a.png)

**Comment by ohsnapitsjoel** [comment]
Awesome, thank you!  Actually clean install by itself didn't work per se since I left everything in my OpenToonz stuff directory intact.  I realized that what I needed to do was delete the old "roomX_menubar.xml" files in OpenToonz stuff > profiles > layouts > personal.  That fixed it.  

But YES, this is EXACTLY the functionality I was looking for. Thank you so much to the devs for contributing this!  <3<3  I just used the DuIO script to import the result into After Effects and this pipeline works perfectly.

**Comment by gab3d** [comment]
@RodneyBaker 
I think an option to do a real clean install (renaming old stuff directory) should be included in the installer, for users to be able to eliminate these kind of problems in a simple manner.

Years go by and users repeatedly continue to report problems whose solution is doing a clean install, so perhaps it's time to consider giving that option as part of the standard install procedure, 
OR 
having a command inside OpenToonz menus that completely resets all config parameters to default status, without having to deinstall and reinstall.
With the pertinent warning of course.

**Comment by RodneyBaker** [comment]
@gab3d  Thanks for the thoughts on that.

That need for a clean install has been discussed... there may even be an open request for it open.
We tend to run into the problem a bit more at the annual update where it becomes more of an imperative because of the number of changes users who have not updated to any nightlies encounter the changes from the past year all at once.

There also may be more effective ways to refresh the UI so that clean installs are not required but... there are some issue there that need to be addressed such as customizations by users that they want to maintain to the best of their ability even across major updates.  

Some of the efforts with Tahoma2D have been successful with regard to bringing user preferences forward into a new installation and this especially for users who heavily customize will be of importance moving forward.

In a way though, it's a bit like that old saying of 'do you want your pain all at once or stretched out over a long time'.  ;)
Change can be difficult regardless but we can certainly plan better for it.

There are some other approaches that might be in order but we might not be quite ready for that.
For instance, the vast majority of files never change from one installation to the next and yet with every download and install all of those files get included.  An Updater that only updated files that have changed would take considerably less time to install but would take more time being prepared; basically a comparison of current versus new files would be made and then an installer created just for those files that have changed would be distributed.  The larger benefit would likely be that of having a clearer view on what exactly is changing whereas currently most changes are done in isolation of the larger view of Opentoonz and of optimization.

The good news is that we are getting there slowly but surely.  :)
