### ISSUE TITLE
How to move over 9 with the styles ?

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#4546]
### Ask a question related to OpenToonz

I noticed recently that we can assign numpad as shortcut. But if we dont and still use it for the styles how we can selected the styles 10, 11, 12 etc ? In the previous version,the  tab key can do it, but now that seems not working anymore ?

**Comment by RodneyBaker** [comment]
It seems...

The cursor/pen/mouse needs to be over the viewer/canvas for the Tab option to work.
And of course the option needs to be on in Preferences as well.

There was a request to extend the Tab functionality to also include when the cursor is over the palette window but that apparently never was added.  For more information, please see https://github.com/opentoonz/opentoonz/pull/804.

Thanks for asking the question because I haven't used that capability much in the past and should be using it.
I do confirm that it still works for me when the cursor is over the viewer/canvas.

**Comment by openanim** [comment]
Thanks @RodneyBaker ! Indeed, it works well with the cursor on the viewer in the current version and not anymore from the palette. For version 1.4 I confirm that the functionality worked from the palette. The link you gave me also indicates that the functionality from the palette was implemented at some point. 

Checking version 1.5 this is no longer the case, no idea when it stopped working with the palette. but this seems to coincide with the change in the look of the shortcut assignment. That being said, I checked with OTX versions, I don't have desktop installers for the older N.B official versions anymore.

> Added: According to the discussion in https://github.com/opentoonz/opentoonz/pull/804 when the option is on to use Numpad with the palette the use of Numpad with other shortcuts is turned off. I haven't confirmed that is still the case but it appears to be.

I guess it has been updated (maybe since version 1.5), because currently when I assign a number as a shortcut to another feature than styles, it disables their use with styles for a while. Removing the assignment, makes it go back to the usual use with styles. But the possibility to do it seems available since 1.5
