### ISSUE TITLE
Lack of Documentation on Export Color Space

### ISSUE THREAD

**Issue by TACarp** [opentoonz/opentoonz#4565]
### Ask a question related to OpenToonz

I can't seem to find any documentation on what the rendered image color space is. From my own testing I think it is sRGB linear. Is this correct? If not what is the color space? Have you considered including this in the documentation?

**Comment by shun-iwasawa** [comment]
Currently all rendered images are in sRGB (i.e. nonlinear) color space.
The documentation may not cover such information, because rendering in linear color space was quite advanced feature and totally absent from the software until recently.

I'm preparing to post a new PR which enables OT to render EXR images in linear color space with high dynamic range support.

**Comment by RodneyBaker** [comment]
@TACarp Will close as the question being answered.  Thanks @shun-iwasawa
 
As Opentoonz color space is still evolving will need to revisit documentation as updates related to color space (and EXR image format) occur.
