### ISSUE TITLE
Swatches viewers synchronized when changing settings.

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#4583]
### Is your feature request related to a problem? Please describe

Also allow the Swatches viewers to be synchronized when changing settings.

Currently the editing of settings is already synchronized between the different windows (although sometimes it seems doesn't update) but not the viewing. This would be a good thing if we want to use 2 windows of Fx settings, one to change settings and the other for a larger view.

![swatch viewer no synch](https://user-images.githubusercontent.com/29790512/198899950-2e634261-72d2-4dd6-8dc8-44f109a771fc.gif)

### Describe the solution you'd like

Perhaps an activation button on the FX settings window would be an adequate solution if it would affect any workflow.

**Comment by RodneyBaker** [comment]
This isn't quite your request but I observe...

If we have two or more copies of the same FX node (or linked copies) open at the same time** and we adjust the onscreen gizmos/gnomons assigned to that FX --on the main canvas-- all the duplicate swatches update together.  If not we often need to select the node of the particular FX to get the result in the swatch to update.

I note that it can be useful to not have these update in sync as we can set up before and after 'shots' to gauge the differences in what we've changed.  I'm not sure how that will factor into your request.

The downside of the autoupdating capbility described above is that no all FX have those UI elements set for the user to manipulate on the canvas.


**Aside:  I note that it can be very difficult to open more than one copy of the same FX node unless/until we dock a copy.  Then subsequent instances of the same node can be opened.

**Comment by openanim** [comment]
I understand your reservations, I remember when @manongjohn  had brought back and improved some missing features of the FX panel and swatch viewers that we had to wait for a validation from some studios. Also, the reason I brought up the idea of using a sync button (somewhere in the fx setting window) in case it would eventually avoid to cause problems in the current workflow for some people.

If you enable the sync button the watches viewers are also synced if you disable it things would work as they do now. Or any other form that would allow this state, like a preference for example). Even if I say it in a simplistic way, I don't assume that it would be something easy to implement, though.

But from my point of view, the way to get the maximum potential out of the swatch viewer would be to be able to synchronize them as we saw in the examples you posted. Especially since for the settings it's already  the case, it would be consistent. This would open a lot of doors for optimal use of the effects viewer. As would adding the playback elements requested in another place.

![sv_sync](https://user-images.githubusercontent.com/29790512/198907306-bdae02f8-1c77-43bf-9eb0-d83e5d745be3.png)

**Comment by RodneyBaker** [comment]
@openanim 
I'm tagging with 'Needs Info' not due to lack of information from you but more because I personally lack the vision necessary to see a clear path ahead.  Developer willing to take on this request likely won't have that problem as it may seem obvious to them.

Additional information should help however so this is an invitation to achieve that.
It may just be a matter of sharing various efficiencies and workflows that focus on the benefits of swatch viewer synchronicity.

**Comment by RodneyBaker** [comment]
Closing this as the originator of the report has ghosted themselves.
As a feature request it may be appropriate to transfer this report to Opentoonz-Docs for further consideration.
