### ISSUE TITLE
Crashing on Windows 10 due to lvcod64.dll

### ISSUE THREAD

**Issue by falconmick** [opentoonz/opentoonz#46]
as allot of people are reporting https://groups.google.com/forum/#!topic/opentoonz_en/H8CDe_Uko6E I too cannot get this app to run either via my compilation or the installer. I keep getting this: [link to exception message](https://lh3.googleusercontent.com/-AB3t9ccT_mM/VvYTybZ8MsI/AAAAAAAABOg/hb_P9NSeVQUSmtIkoHk2ORWw_i_oSn1jA/s1600/Capture.PNG) inside lvcod64.dll

When I attached my debugger I was able to see the line of code responsible but it really pissed me off (spent quite allot of time trying to get it running) so I deleted the source + qt + boost so I can't reproduce and connect debugger, unless you guys respond and ask me to re-do everything again (which I can)

I just don't know how responsive you will be so I don't want to spend another hr and have nobody reply to this bug.

EDIT:
I only have 1 screen plugged in

**Comment by retsyo** [comment]
crash for my win7 64 bits too.

**Comment by yondoloki** [comment]
Crash on Win 8.1 64 bit also as soon as I open the program

**Comment by AmEv7Fam** [comment]
Ditto. Instantly crashes on my Win10 x64 machine.

Based on the responses, it seems to be 64-bit machines that are affected.

**Comment by 3Rton** [comment]
Same
Renaming lvcod64.dll immediately allows the software to run normally. Anyone got clues how to fix this?

**Comment by AmEv7Fam** [comment]
OK. Apparently, lvcod64.dll is part of Logitech Webcam software.

Uhm, I've got a Logitech web right under my monitor. Oh...

Those of you who are experiencing crashes, who has Logitech webcams, or have at least had them hooked up at one time!

(It appears OpenToonz is trying to access the webcam as an image capture device.)

**Comment by danielgett** [comment]
I'm having the same problem.  I can't even open the program.  Any advice?

**Comment by rioforce** [comment]
Non tech-savy workaround for the time being:

1. Visit `C:/Windows/System32`
2. Find `lvcod64.dll`
3. Rename the DLL to something easy to find (for example `RENAMED-lvcod64.dll`). Remember that the Logitech software or Logitech camera might not work without the DLL.
4. Open OpenToonz (I ran it as admin if that helps)

On startup, it might show something like this (at least, it did for me, strangely. It didn't on my other computer where I didn't have Logitech issues though.):

![opentoonzfix](https://cloud.githubusercontent.com/assets/3674297/14068999/df8ac160-f460-11e5-8e7c-9d0c24924733.png)

Now, the software is running on my laptop. Hopefully we can figure this out so it won't stumble on the dll in the future. ;)

Hope this helps.

**Comment by yondoloki** [comment]
I tryed renaming the .dll, I got to choose a different Video Device, the internal camera of my laptop(Lenovo Y5070) but immidiately crashed again afterwords.

**Comment by odysseywestra** [comment]
Is this problem still happening on the latest version?

https://github.com/opentoonz/opentoonz/releases/tag/v1.0.1

**Comment by yondoloki** [comment]
The program opens now yes! Thanks a ton!

**Comment by falconmick** [comment]
Wikid, will give it a go.

**Comment by falconmick** [comment]
removing the dll fixed it... but I kinda need my webcam. Did the merge above fix this?

**Comment by 3Rton** [comment]
@falconmick Did you try the 1.0.1 build already? It fixed the logitech .dll for me and many others.

**Comment by AmEv7Fam** [comment]
Can confirm it fixed the Logitech issue for me as well.

**Comment by falconmick** [comment]
@3Rton I deleted boost and qt after I thought that the issue was my ability to read the JP install instructions wrong and just used the installer.. then I found out that I did compile it correct and it was this bug... Maybe later I will spend the year it took to download QT again!

**Comment by madskillz89** [comment]
I used Window's built-in compatibility mode called "Run programs made for previous versions of Windows" and that made it work for me.

**Comment by bigbooteh** [comment]
I've been getting the crash at start up with the install of Toonz 1.0.1
Like most the first launch worked but then the next time I opened it up it would fail.

All the .dll fixes out there didn't work for me nor could I find any of the suggested .dll's to remove.
I also tried the suggested upgrade of video card but that didn't help either.

Here's what I found has worked for me.
I'm running Windows 10 64bit with a 2 monitor setup. My secondary monitor is a Cintiq.
When I launched the program the first time I moved it to my Cintiq monitor (because I want to draw)
Then I closed it and attempting to relaunch I'd get the crash at start.
What seems to happen is that it doesn't like to relaunch from a secondary monitor if that's where you closed it from. It remembers that and will fail on relaunching.

So here's my workaround:
- Launch Toonz from primary monitor
- Drag Toonz to Cintiq to work if I want to draw.
- DO NOT CLOSE TOONZ FROM CINTIQ MONITOR
- Drag Toonz back to primary monitor and exit
So far this is working (pain in the ass but working)

If you do forget and close on a Cintiq or secondary monitor simply delete the mainwindow.ini file
that's found here:
C:\OpenToonz 1.0 stuff\profiles\layouts\OpenToonz.(youcomputersname)
This will relaunch Toonz on the primary monitor again but retain your setup of menus I believe.

Seems like a relatively simple fix.
Hope this helps someone.

**Comment by AmEv7Fam** [comment]
Well, the monitors issue is different than the DLL issue, and it sounds like the DLL issue has been resoved, but the monitor issue hasn't been fixed (as of yet).

Could we close this issue, as all new posts seem to not be related to the DLL issue?

**Comment by RodneyBaker** [comment]
I want to report that this old fix still resolves problems in 2022.

Renaming the lvcod64.dll file fixes several crashes encountered to include startup and rendering to AV! format.

**Comment by RodneyBaker** [comment]
Returning to this report.
I have been experiencing two crashes at startup that point to presence/use of lvode64.dll being present in Windows/System32/ directory.  Apparently the DLL files were reinstalled again somehow after having renamed the file before.  Renaming again cures the crashing.

Here are some related reports in case they aren't linked above:
https://github.com/opentoonz/opentoonz/search?q=lvcod64&type=issues

**Comment by RodneyBaker** [comment]
This crash is has returned for many Opentoonz users in 2023.
Removal of the problematic diver resolves the issue for the majority of users.
