### ISSUE TITLE
Something I don't understand about gradients

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4620]
### Ask a question related to OpenToonz

Why are gradients created in separated columns, and not inbetween nodes?

I ask this because to apply a gradient to a silhouette, you have to create a matte and...wouldn't it be better if the gradient had the option to apply alpha as the blending nodes?

**Comment by RodneyBaker** [comment]
There is part of this that I almost understand but am not confident enough to suggest.
(More research required until I can talk intelligently about that but in general my thoughts apply to nodes that generate data versus manipulate data and zerary FX in general)

But...
According to the documentation:

> Effects that create computer generated images, such as the Radial Gradient, that are exposed in Xsheet columns (and Timeline layers) and therefore are similar to columns; they are displayed with an orange node with only an output port on the right. These effect nodes have to be connected to the Xsheet node to be rendered, or can be connected to other effect nodes.

There are some advantages to having these nodes exposed to the xsheet/timeline as well, such as ability to animate the transforms of generator as if it were a regular column.  If it was not then the node would require specific code be added to allow such manipulation.

The key takeaway I get is that these particular nodes have to be connected to the xsheet node in order to render.
It achieves this by actually being exposed in the xsheet.  As such we technically do not have to actually attached the node to the xsheet node (which seems to contridict the documentation no?).  So this gradient FX will render even though it bypasses the actual xsheet node.   The below for instance will render just fine:

![image](https://user-images.githubusercontent.com/2576432/204366923-e8949902-b388-4a67-b1c0-192e6d711c57.png)

**Comment by F-Burning** [comment]
I think I have more or less understood you (my language skills are limited), but I understand that there is an important reason behind it.

I wish there was also the possibility of a gradient node, even if it is more limited, but I understand that it is not that simple.

Thank you @RodneyBaker  for the reply 👍

**Comment by RodneyBaker** [comment]
I was going to suggest that we could create a gradient Shader but those are of the same type of node that is generative and thus begin at the start of a schematic flow.

As for how to proceed now... don't limit yourself to not being able to have these particular FX nodes be at the beginning of schematic flow... we can push them down into the flow where they can act as typical nodes.  Here for instance I use a Cross Dissolve and an Invert node to allow two different ways of switching on/off a gradient.  If the Invert node is turned on (active) we get white on left, black on right but if we turn it off we get the reverse.

![image](https://user-images.githubusercontent.com/2576432/204638864-3def6200-dd65-4ce8-a921-b8652ba1f5a9.png)

The real trick however is just in piping the gradient (or other generative node) into another node... even if it is a dummy node turned off so that we can use the resulting flow down stream with other nodes.

**Comment by RodneyBaker** [comment]
Closing this as a question answered.
