### ISSUE TITLE
About Cleanup (Solved)

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4689]
### Ask a question related to OpenToonz

When I check on the "Preview Cleanup", the image becomes small, no matter what setting you touch

https://user-images.githubusercontent.com/74098734/210180545-5042dc39-7ebd-4b59-b6b2-91ab8369d4da.mp4

I would like to keep the size, but I can't. Maybe is this a bug?

**Comment by oliver-dreamwalker** [comment]
Have you try to change the Clean-up Camera size ? at 0:19 . is the dpi of the **Clean-up Camera** and the Level the same ?

**Comment by F-Burning** [comment]
At 0:09 I use the "Use current level settings", but nothing changes. 

>Is the dpi of the **Clean-up Camera** and the Level the same ?

Could you show me where I find it? I was looking for that option.

**Comment by oliver-dreamwalker** [comment]
At (0:19 - 0:23) try manually match the red rectangle outline with the white Level outline (It should match) or "Use current level settings" at that part.
If that does not work it is probably a bug.

**Comment by F-Burning** [comment]
Yes, I did move the cleanup camera manually too, but the issue continues. 

If @RodneyBaker can determinate if this could be a bug, I would like to change the label if it's possible.

**Comment by RodneyBaker** [comment]
We need to investigate as I can't reproduce the problem.
Granted, I have only done a few quick tests so need to do more testing.

We need an option to zip up both the project file and the program (as a portable) for testing of these types of issues as then others would be able to know they are using EXACTLY the same files, settings and version.   ;)

Is this with all sizes of image?
Can you share one of the images you are cleaning up?

**Comment by F-Burning** [comment]
I tried all, even I did change the camera settings to the level. Also I did use another imagen with a diferent resolution, and it becames small too.

This is the PNG that I'm using:

![PNG_A_08](https://user-images.githubusercontent.com/74098734/210189017-5eb9f8b0-a0e4-421c-aa19-0bbe923ddc70.png)

**Comment by RodneyBaker** [comment]
I just now did get the preview to change size and I think it was by making the image (not your image) smaller than the canvas and the camera.  Need to verify however.

**Comment by RodneyBaker** [comment]
When I grab one of the smaller sizes from the custom drop down menu in Cleanup Settings I can turn get the resizing and cropping to turn back on. Otherwise I can't get the image to resize/crop while using the 'Use Current Level Settings' option.

**Comment by RodneyBaker** [comment]
I'm learning something new here...
I hadn't realized that we could have Cleanup Preview on and change the resolution (via dropdown in Cleanup Settings) and we can see the changes in size/cropping etc. live update in the preview.

I always thought we had to click the preview option again.

**Comment by F-Burning** [comment]
So, it works for you? I've seen tutorials on Youtube, but this issue doesn't appears.

I'm using the last nightly of Opentoonz, but this happens too in Tahoma to me.

**Comment by RodneyBaker** [comment]
Yes, latest nightly here as well.
Perhaps someone will happen along that has similar results as yours.
Perhaps someone on the T2D side can confirm as well.

In the past the Cleanup process has been a bit too odd for me to use regularly but I have slowly been learning to like it as I get more familiar with it.  It does help to use black and white linework (with only the basic color hold lines) and when starting out with OT I tended to use full color images a lot.

**Comment by konero** [comment]
@F-Burning Your image is 192dpi whereas the camera is 120dpi by default if you have pixel unit selected, that's why the image appears smaller in Cleanup Preview.

You can solve this by changing the image to 120dpi using another software, or by navigating to the file in OpenToonz file browser and right-click > convert and use these settings.

![image](https://user-images.githubusercontent.com/19820721/210361482-8c3074f5-7ced-4223-9c1f-cfc854b8fa9f.png)

As you can see at the bottom we can choose dpi for conversion.

![dpi1](https://user-images.githubusercontent.com/19820721/210359639-bccc3e0b-3918-45f3-a9ae-a4750f1b3360.gif)

Now what I observed, **if pixel unit is selected** the cleanup (the normal cleanup, not the convert) will handle the image as it is displayed in Cleanup Preview and change it to 120dpi, here's a before and after.

|Original Image|After Cleanup (Pixel Units)|
|---|---|
| ![image](https://user-images.githubusercontent.com/19820721/210362116-e3cfe55e-8262-4bfd-912a-71d690a3322c.png) | ![image](https://user-images.githubusercontent.com/19820721/210362168-0e9efd1c-9f9d-45ac-951f-a9f7e3414b19.png) |

I would have to change the image to 80dpi for it to match camera size now, with a drastic loss in detail.

This does not happen if any other unit is selected such as mm, the cleanup image retains its original 192dpi value and I can change it to match camera 120dpi with no loss in detail.

So I don't know if this is a bug (cleanup is meant to Cleanup Preview with 120dpi set for images) or we probably need a new dpi option box somewhere in Cleanup Settings? 🤔 

Some of this could be wrong, I think pixel unit in OpenToonz is difficult to understand, I personally use mm and if you're going to be using cleanup for work I recommend you do too.

**Comment by F-Burning** [comment]
Thank you @konero!

I will try it!

**Comment by RodneyBaker** [comment]
Did you discover anything here @F-Burning?
Inquiring minds want to know.

**Comment by F-Burning** [comment]
Sorry, I forget to update it 😅

I did try as @konero said, and it works perfectly now. The issue was the diferent DPI from the image, and was necessary to change it manually with another software. In Opentoonz you only can do that if you convert it to .tlv. A fast way to do it, if someone find this useful, is with Photopea, an online image editor like Photoshop, but  free.

Just load the image, go to -> Image -> Image size:

![image](https://user-images.githubusercontent.com/74098734/213317311-74d8ded8-f6b7-46ce-a352-4a82b4159e5f.png)

Here change the DPI to the camera DPI...

![image](https://user-images.githubusercontent.com/74098734/213317503-3e63a8a8-02b7-4a7e-9225-54fd903a87bb.png)

...and the resolution will change too:

![image](https://user-images.githubusercontent.com/74098734/213317641-84f30ed8-8524-401a-8470-34793b9b10ad.png)

The only you have to do is put the original resolution again, and the DPI will keep:

![image](https://user-images.githubusercontent.com/74098734/213317734-94e965e6-38aa-4744-9606-1c5765ce3610.png)

Finally go to -> File -> Export as, and choose the format:

![image](https://user-images.githubusercontent.com/74098734/213317854-1d6ae4a2-474c-4446-a910-1d5a70555d68.png)

**Comment by RodneyBaker** [comment]
Glad to hear you got it worked out.
We should be able to adjust the DPI directly in Opentoonz via Level Settings but... I haven't fully tracked all the elments collected in this report.                               DPI in images is an interesting topic.
