### ISSUE TITLE
Filenaming:  Crash with range of drawings starting with 0000

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#469]
I use Krita to export animations as a PNG numbered file sequence: name.XXXX.png. Krita saves the first frame as name.0000.png.

When I import these frames into my project's drawing folder, the instant I use the file browser in OpenTOonz to open the drawings folder, OT crashes. If the file browser happens to be pointing to the drawings folder while I place such a range in the drawings folder, OT crashes.

To work around this issue, I have to either manually delete the first frame (file), or rename the entire range. This is a bit frustrating.

OT cannot handle a numbered range of images starting with 0000. 

It would be great if OT would accept both options: image ranges beginning with either 0000 or 0001 would be accepted as a valid animation sequence.

At the very least it ought not to crash instantly when encountering a sequence of images starting with 0000.

**Comment by MisterABK** [comment]
In addition to the problem with frame sequences beginning 0000, Opentoonz also ignores frame sequences which have too many leading zeroes (eg. "imgseq_00001.tif") and treats them as separate images. It also doesn't seem to accept sequences where the number is not separated by an underscore (eg. "imgseq0001.tif").

**Comment by artisteacher** [comment]
OT does recognize sequences with a period (i.e. imgseq.0001.tif). This causes a problem with some of the my paint brush icons not being recognized #1382. My camera automatically saves images with the name.0001.jpg format, so that ends up working really well. 

Just like how the load/import preference can be set, it would be helpful to have a preference to choose between loading a selection of images as an image sequence or as separate levels.

**Comment by RodneyBaker** [comment]
A problem related to this is that a way some programs know to render out to an image sequence and to a specific format is to specify the output in the form "image000.png" where 'image' is the filename, the zeros related the padding for digits desired and ".png" relates the desired format.  This is a great timesaver because it saves the user from having to navigate anywhere to specify the number of trailing digits or the filename.  

The problem of course is that OT sees that filename (even with added periods generated from the other program) as malformed.

Ideally OpenToonz would recognize any of these common filenaming conventions as legitimate sequences:

image0.png

thisonealso00.tga

andthistoo.tif

The filename and the extension aren't problematic in any way but the numerical sequencing is even before any attempt to bring the file into OT.  The example of this can be seen occassionally where OT encounters what it deems as a malformed file (or more likely a sequence of files) and throws an error or crashes.  

I posted elsewhere an issue with webm files that apparently isn't related to the sequence numbering.  As near as I can tell that has something to do with reading of the webm file.  In that case just the presence of the file in a directory can cause OT to crash in just the attempt to open the directory containing the file.  This is before even selecting it in anticipation of importing or loading it into OT.  This suggests a problem very early in the process but one that may also relate to file numbering.

**Comment by artisteacher** [comment]
Something else to consider is we don't want to mess up how levels created directly in OT load into a scene. I sometimes name levels with name1.pli, name2.pli & etc. or name1.tif, name2.tif & etc. It would be frustrating if those levels loaded into a new/different scene as a single sequence.

**Comment by artisteacher** [comment]
I just experienced an interesting and related glitch. I dragged and dropped a properly named image sequence of 25 images from Finder (Mac OS) into a scene and the sequence ended up loading into 25 columns. In each column all the images displayed...

**Comment by manongjohn** [comment]
Yeah, I just noticed that yesterday also. Probably should be its own issue.

**Comment by RodneyBaker** [comment]
The crash with trailing zeros should no longer be a problem but there is still the issue of that particular  filenaming convention which will result in an error dialogue notifying the user of a malformed file sequence.

**Comment by RodneyBaker** [comment]
As the PR hasn't been merged this is still a problem.

An additional aspect of the issue with sequences starting with a trailing zero is that say out of a 30 frame sequences if the error pops up in OpenToonz and the user renames the file to correct the problem the error dialogue has to be dismissed for     each and every frame in the sequence.   If the sequence has hundreds of frames that could be a lot of clicking.

**Comment by RodneyBaker** [comment]
I'm pretty sure this is addressed by #2607 but if someone else can review before closing that will be appreciated.

**Comment by RodneyBaker** [comment]
This issue should be resolved.
Closing this pending any new reports of the problem.
