### ISSUE TITLE
Crash Upon Loading (Vector) Project

### ISSUE THREAD

**Issue by Obicubed** [opentoonz/opentoonz#4699]
### Description

OpenToonz keeps crashing. It says the reason is EXCEPTION_ACCESS_VIOLATION

### Steps to Reproduce

1. 
2. 

### Expected Behavior

I had just loaded it.

### Screenshots, Video & Crash Logs

![Opentoonz crash](https://user-images.githubusercontent.com/122272451/211293384-054fd4e9-82e1-4121-a598-1129a410b444.png)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by artisteacher** [comment]
If the scene crashes directly upon loading, there's probably something that got corrupted. When I've run into this in the past, I temporarily moved all the levels out of the drawings folder and gradually added them back in - to identify what file was the problem. It's been a long time since I've had to do that!

**Comment by RodneyBaker** [comment]
Closing as not information to assess the problem.
