### ISSUE TITLE
insert frame between two frame in level strip, change every frame in xsheet

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#471]
I'm confused. When insert frame between frame 0001 and 0002 in level strip, new frame number change to 0002 and change every frame number and drawing in xsheet.

what do you think? Is this good or bad?

![number frame](https://cloud.githubusercontent.com/assets/16509592/16172433/34324cd2-359e-11e6-950a-42fcb1e8a122.gif)

**Comment by Rayek** [comment]
This is expected wanted behaviour: suppose the animator wants to add inbetweens - in that case this makes a lot of sense.

So, very good indeed.

**Comment by blurymind** [comment]
I think that this is not good design, because some times you would like to insert new drawings between the ones you have.
@Rayek precisely because you might want to add inbetweens the current design is a problem.
You add a new inbetween in your flipbook and suddenly all of your xsheet drawings change unexpectedly.

A better design would be toonboom's and tvpaint's approach. Each drawing has a unique ID that is not affected by the order that it has in the flipbook. The x-sheet uses the unique id of the frame instead of it's order number.

**Comment by blurymind** [comment]
or wait.. i need to investigate this. It might be beneficial in some cases.

**Comment by blurymind** [comment]
in my case it is a bit of a nuisance because it makes me reorder frames in the x-sheet.

**Comment by blurymind** [comment]
With this design you discourage the user from inserting any inbetween frames in the flip book. I tried it on a simple animation and I have to say that it creates needless work for the artist with no benefits!

The workflow is usually:
1. draw key poses in flipbook
2. drop them onto the xsheet and adjust their timing (hold some longer than others)
3. insert breakdowns (flipbook, then drag to xsheet)
4. insert inbetweens (flipboox and then drag to xsheet)

from step 3 - immediately all the timing that I have set for myself in step 2 becomes worthless - as all of the drawings are not at the right place. So now I have to redo step 2

Please implement (as an option if some are against it) the ability for drawings to have a unique ID variable  under the hood (each time a drawing is created, it gets a unique ID) and for the xsheet to use their Unique ID variable instead of their order in xsheet variable.

**Comment by blurymind** [comment]
Actually one advantage of having the current design is numbering clarity in the xsheet. Inbetween drawings and key drawings become very obvious - as this forces you to have sequences like this:

1,4,5,6,2,7,8,9,3

4,5,6 is an inbetween
7,8,9 is an inbetween
and 1,2,3 are keys.

the inbetweens are consecutive numbers

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by turtletooth** [comment]
I'm reopening this.  I think that valid arguments can be made for both points. Personally, when I insert a frame in the level strip, I don't want it messing up things I have already placed in the XSheet.  I already have a fix started for this, and will make it optional.

What do folks think should be the default?  I already know where those above stand, but I would like to hear feedback from others.

**Comment by turtletooth** [comment]
BTW- my implementation does not add a unique identifier for each drawing.  I think that would be overkill.  I simply am updating the xsheet to reflect when the drawing number is changed in the level strip.

**Comment by shun-iwasawa** [comment]
If you would like to add such option, IMO it should not be the default. Since the level may not used only in the current scene, modifying only the current sheet automatically by default will cause confusion.

**Comment by turtletooth** [comment]
That makes sense.  There is no way to update unopened scenes.  I do have it set to catch used of the level in subxsheets though.

**Comment by blurymind** [comment]
You could have the x-sheet properly show the frame ID numbers after a new one has been inserted in the level strip. 

That would at least clearly communicate to the user what OT has done when they inserted the frame
Have it as an option for the x-sheet
![showframeids](https://user-images.githubusercontent.com/6495061/30201157-9f4c370c-9471-11e7-93e0-83f27322d5ae.png)

**Comment by gab3d** [comment]
@turtletooth, thanks for tackling this one!

And srry to arrive late to this discussion.
Some thoughts on this:

1. To me it seems the idea of drawings ID is the more robust one, and automatically deals with unopened scenes too. If under the hood xsheets expose drawings by their IDs, then even if new ones had been inserted inbetween, the xsheets (in opened or closed scenes) will consistently maintain the original exposure.

2. It'd be useful for the user to keep track of this by having a mode button available and visible in  the Level Strip panel top section.

**Comment by turtletooth** [comment]
@gab3d Right now I don't have the time to tackle something that huge- and it would huge.  The way that OT references frames right now is used in so many commands - it would take reprogramming large chunks of code.  Yes, it would be nice to not break unopened scenes, but that would take making sure that nothing was broken in all these places: https://github.com/opentoonz/opentoonz/search?utf8=%E2%9C%93&q=tframeid&type=

My implementation doesn't break the current system or prevent someone else from coming along and adding a unique identifier, but it does at least allow opened xsheets and subxsheets to sync with level strip changes.

**Comment by gab3d** [comment]
@turtletooth, I completely understand Jeremy, and I am very grateful for all your work and dedication!
Please always take my comments just as wishes. :)

Besides that, your current implementation is a huge step forward IMHO and I am, for sure, very happy with it!

**Comment by turtletooth** [comment]
@gab3d I understand your points and that they were hopeful suggestions.  No offense taken.   Thanks for the kind words.

**Comment by Orphanlast** [comment]
I think it's bad design. Because the workflow is usuallt on the viewer and xsheet, not the level strip

**Comment by artisteacher** [comment]
I think it really depends on the workflow. If you consider that the Xsheet displays/exposes the frames from each level that are active in the animation, it does make sense to add new frames in the level strip instead. I do agree that it would be helpful to add additional frames through the Xsheet as well (beyond drawing on the next frame).
