### ISSUE TITLE
What is the best way to make a character and in what sequence?

### ISSUE THREAD

**Issue by Dineeeyd** [opentoonz/opentoonz#4748]
### Ask a question related to OpenToonz

Hi all, I have a question again, what is the best way to do the character together with the bones and whether it will be possible to then transfer it to other scenes? If you know then explain please)))

**Comment by DarrenTAnims** [comment]
That's a huge question. And something that you need to figure out for yourself and for your workflow.
It sounds like you want to create a puppet. It depends if you want to use the plastic tool or just connect the columns. But for both, I'd start with sketching your character on 1 column, then drawing the different parts on other columns, leaving some overlap between parts, so that, for instance, when you rotate the arm, there's still some shoulder being shown.
To use a puppet in another scene, it's best to save your puppet in its own scene, then load your puppet scene into your other project using the menu item, File > Load as subxsheet.
Be aware that if you load it into the same project OR load it into another project and DON'T use the IMPORT option, then any edits will affect anywhere the puppet is used.

**Comment by RodneyBaker** [comment]
Hi @Dineeeyd 
As Darren suggests, your question is a pretty involved one and not particularly suited for github.
You may find feedback from one of the Opentoonz discords more appropriate.
@DarrenTAnims has a discord channel dedicated to Opentoonz and there are other discords as well as other online venues.
While I will close this report... Please feel free to continue the discussion here of course as you see fit.

**Comment by Dineeeyd** [comment]
@RodneyBaker Well, can I know how to make several poses of a character in one scene, because I can't figure it out.

**Comment by RodneyBaker** [comment]
> @RodneyBaker Well, can I know how to make several poses of a character in one scene, because I can't figure it out.

I suppose the most direct answer would be that we draw them (the poses that is).
There are a number of different ways to pose a character but I'd say each approach relies on what we have available in the character to pose.

Do you have an example of a character you would like to pose?

**Comment by Dineeeyd** [comment]
@RodneyBaker do you want to see the character himself?

**Comment by RodneyBaker** [comment]
We have to start somewhere.
Without knowing more I'd just start guessing.
For instance, we might think of a pose as just a set of facial expressions.

![BasicSetup](https://user-images.githubusercontent.com/2576432/219877512-a5517dc9-d701-4512-8f9b-cb80964fe80e.png)

Project File:
[BasicSetup.zip](https://github.com/opentoonz/opentoonz/files/10774750/BasicSetup.zip)

**Comment by Dineeeyd** [comment]
@RodneyBaker I need to make poses for this character

![Снимок экрана (1009)](https://user-images.githubusercontent.com/125077296/219878137-f23cd3d8-5f5d-4617-90fd-bd5baf0dcd2c.png)

**Comment by RodneyBaker** [comment]
Because of the simplicity of the character you can probably get away with just having each part of the character in a separate column of the xsheet.  I presume you might already be doing this.

Because of the very simple arms and legs I personally would consider making those a custom vector brush.
Then you can simply adjust a single stroke/line to get them to bend as you see fit.
That would also allow you to simly draw the arms and legs into place.
Of course the explanation of that setup might be a bit more complicated than this back and forth via github can easily support.

But for starters, do you currently have the different parts of the character in separate columns or are they all in the same drawing?

**Comment by RodneyBaker** [comment]
I'll guess most will usually keep separate partso of a character on different levels but I like to keep them in the same leel where pssible.  In this way we can store them all in one file (a single TLV toonz raster level).
There are benefits to keeping parts in separate files as well.

Here is a friend for your character to illustrate the basic idea:
![image](https://user-images.githubusercontent.com/2576432/219883783-8cc4608c-b8a0-435a-b16d-ce80792aa70f.png)

**Comment by RodneyBaker** [comment]
Posing has a lot to do with the environment the character is in... but you know that already.

![image](https://user-images.githubusercontent.com/2576432/219884484-414ede08-b02c-4873-a057-6d8ac3b1fbca.png)

**Comment by Dineeeyd** [comment]
@RodneyBaker I made a skeleton for the character and this is what it looks like

![Снимок экрана (988)](https://user-images.githubusercontent.com/125077296/219938046-c8cf413e-0544-40cc-afd9-17d5bc65253b.png)

**Comment by Dineeeyd** [comment]
@RodneyBaker another question, how do I import a character to another scene? when I drag him to another scene, he cannot be manipulated and the skeleton disappears... what to do?

**Comment by RodneyBaker** [comment]
Probably the easiest way to bring a character into a scene:

1) Save your character by itself as a Scene
2) Import the (character) Scene into the new Scene you wish to have your character occupy... as a subxsheet.

![image](https://user-images.githubusercontent.com/2576432/219944339-166c1d6c-e3bc-4db9-bd97-0f2cd24e707f.png)

We can then either adjust the frames of that subxsheet or open the subxsheet and edit the character further.

**Comment by Dineeeyd** [comment]
@RodneyBaker I still can't interact with the character.
![Снимок экрана (1018)](https://user-images.githubusercontent.com/125077296/219947520-a0825b23-865b-4208-b7e2-a6502f8833be.png)

**Comment by RodneyBaker** [comment]
You must Right Click on the Character column (which is a subxsheet that contains all of  the potential/parts for your character poses) and select Open Sub-Xsheet.  You can then adjust the character as needed.  

Note that you may  wish to explode the subxsheet so that there is no longer a subxsheet and your entire character is now 'present' in the current scene.  This especially if the scene is fairly simple... such as a single background...

If the above is the case then you might just wish to import the scene into the current scene... no need to use a subxsheet.

The subxsheet is particularly useful when it contains all of the poses you will need to use in the scene.
Then we can just use the Q and W keys to move through the frame of the subxsheet to pose our character.
Entering the subxsheet therefore wouldn't need interaction unless for specific reasons... which we want to avoid because that will also change those poses for other scenes the character/subxsheet is in.

When using a subxsheet it's important to remember to close it and return to the outer scene.
Otherwise we can easily forget that we aren't in our main scene and start to change things in that subsce

When explosing a subxsheet (i.e. pulling all the columns/levels out of a subxsheet into the current scene... Opentoonz will ask if we wish to keep the current parent/child relationships.  Generally we DO want to keep those relationships as we don't want to lose those connections in the Schematic.

I will recommend NOT using your current project while you experiment with this.
Build something temporary so you aren't afraid of breaking things... and then experiment... break things.  :)

**Comment by Dineeeyd** [comment]
@RodneyBaker And can you please show me from the screenshots?

**Comment by RodneyBaker** [comment]
> @RodneyBaker And can you please show me from the screenshots?

Can you join the Opentoonz discord?
This back and forth via github might take a few years to walk you through these processes.

Opentoonz discord (invite):  https://discord.gg/UQxvYBKW5U

**Comment by RodneyBaker** [comment]
Transferring this to Opentoonz Docs
