### ISSUE TITLE
Additional features(Improve Transparency Check) for Japanese animation industry

### ISSUE THREAD

**Issue by Kumotate** [opentoonz/opentoonz#4760]
### Is your feature request related to a problem? Please describe

はじめまして。くもたてと申します。
仕上げ工程にOpenToonzを使用している方と少しOpenToonzの仕上げ機能について議論して、追加されればPaintManを仕上げに使っている方がOpenToonzに移行しやすくなるような機能が分かったのでお伝えできればと思い、投稿させていただきました。
問題はいくつかあるのですが、特に改善されて欲しいのが色トレス線の塗り残しのチェックのための機能です。
現状でも透明度チェックと線チェックを併用すればそれを見つけることはできるのですが、線チェックは一つの色しか赤く表示させることができないので、一度に一色の色トレス線しかチェックすることができません。個人でのアニメ制作においてはこれでも十分だと思うのですが、スピードが求められ、色トレス線を3色以上使用するのがスタンダートの日本のアニメ制作の現場には現状ではやや不十分ではないかと思います。
そこで、以下の機能を実装していただきたいです。

(The following text was created using a translation tool. Sorry, I am Japanese and my English is not good enough.)
Nice to meet you! My name is Kumotate.
I have been using this wonderful software.
In the process, I have discussed with some OpenToonz users to find out what features they would like to see in OpenToonz that would make it more desirable for Japanese animation production.
I would like to share with you some of the features that I think OpenToonz needs to improve in order for it to be used, especially in the painting section.
The OpenToonz paint function is excellent, but it is a bit tedious to find the leftover paint in the color-tressed lines.
Therefore, we would like the following features to be implemented.

### Describe the solution you'd like

https://user-images.githubusercontent.com/126930364/222871277-8e4b83e6-0235-4501-9307-6851268ed5e8.mov

・透明度チェックで# ０以外のスタイルでも完全に透明(またはRBGall255)ならペイントされていても表示しないようにする。
（透明度チェックは線か塗りの情報を持っている部分が色付きで表示されるので）
実装されればPaintManにかなり近い形になるので、日本のアニメ業界にも受け入れられやすいと思います。
（PaintManの”彩色表示チェック”というものとほぼ同じ機能になれば非常に良いかと思います。）
この問題が既に開発の方々で議論されていたらすみません。
改善をよろしくお願いします。

(In English)
When using Transparency Check If a style other than #0 is completely transparent (or RBGall255), it should not be displayed even if it is painted.
If this is done, OpenToonz will become more acceptable software for Japanese animationindustry.
Sorry if this issue has already been discussed.
Please help us improve it.

**Comment by shun-iwasawa** [comment]
ご要望有難うございます。考えてみたのですが、例えば以下のような改良ではいかがでしょうか：

【改良案①】
線チェック機能を拡張し、「現在のスタイル」ではなく「選択されているスタイル」で描かれた線が全て赤色になる。
色トレス線を複数選択することで、それらの線の色が全て変わる。

【改良案②】
透明度チェックを有効にしたときも「含め塗り」のチェックがONになっているスタイルで描かれた部分は、そのスタイル本来の色で表示される。
例えば、基本の色トレス線として赤、青、緑のスタイルがあり、それらにだけ「含め塗り」が有効になっていれば、その色で描かれた線（塗り残しの線）は「透明度チェック」時にそのまま赤青緑で表示されるようになります。

- - - - - - 
As an alternative, how about the following?

1. Enhance the Ink Check feature so that all lines drawn in the "selected styles" instead of the "current style" will become red.　By selecting multiple styles of color-trace lines, the color of all lines drawn in those styles will change to red.
1. Even when the transparency check is enabled, lines and areas drawn in styles with the "Autopaint" check turned on will be displayed in the original color of that style. For example, if there are red, blue, and green styles as basic color-trace lines, and "Autopaint" is enabled only for those styles, lines drawn in those colors (i.e. lines left unpainted) will be displayed in red, blue, and green when "Transparency Check" is enabled.

**Comment by Kumotate** [comment]
ご回答ありがとうございます。
改良案2が非常に良いと思います！
（改良案1も良いと思いますが、誤って気づかずにスタイルの複数選択を解除してしまう可能性も考えられるかと思いますので）
実装のご検討のほどよろしくお願いします。


Thank you for your response.
I think improvement 2 is very good!
(I think improvement 1 is also good, but I think there is a possibility that we might accidentally deselect multiple selections)
Please consider implementing it.
