### ISSUE TITLE
style editor

### ISSUE THREAD

**Issue by Meister3** [opentoonz/opentoonz#4764]
### Description

every time i click on a color a style editor pops up on my other screen and now i have 10 and i cant remove them.

### Steps to Reproduce

1. click on a color.
2. have a style editor pop up on another screen.
3. be mad because they cant be removed.

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by Meister3** [comment]
it can be the case but how do i remove them

**Comment by gab3d** [comment]
Can't you just close them with the standard 'X' all windows have?
![imagen](https://user-images.githubusercontent.com/18104091/223553694-c8701c72-e69f-4274-94f2-d6d3cd17b693.png)

**Comment by Meister3** [comment]
no because the top part is above my screen

**Comment by shun-iwasawa** [comment]
If you temporarily turn off the monitor on which the problematic StyleEditor panels are displayed, the panels may "jump" to the remaining monitor and move to a position where you can press the close button.

**Comment by RodneyBaker** [comment]
Will close as likely resolved.
In current nightly releases some panels/windows now close when selecting a second time from menu or shortcut.  The Style Editor is not one of these because users may wish to have multiple style editors open at the same time.  In cases where the rule of 'either off or on' does not apply perhaps is is possible for the aforementioned process to open x number of panels before invoking starts to close them.  

@Meister3 Please let us know if you still cannot close your Style Editor window.
