### ISSUE TITLE
Can u add the Navigation Tags Edit function to Scene Settings please?

### ISSUE THREAD

**Issue by JParks123** [opentoonz/opentoonz#4811]
### Is your feature request related to a problem? Please describe

In the scene settings u added the Edit Cell marks and Edit Column color filters but u left out the Edit Navigation Tags. 

![image](https://user-images.githubusercontent.com/121512756/230375136-87b1e362-34ee-47eb-8b8c-3807ae08a6b4.png)

### Describe the solution you'd like

Can u please add the Edit Navigation Tags also to the Scene Settings Panel list so that we can change the default Tag colors?

**Comment by RodneyBaker** [comment]
Not sure who this "u" guy/gal is but we should put them to work on development most definitely.  ;)

I believe the navigation tag feature was ported in at your request and as such has a separate menuing process that was built into that in Tahoma2D.  As it is completely separate from the other features (cell mark and column color tinting) it isn't directly related to either as of yet.  Unifying the various tagging/navigation features and making their controls more unified would certainly be something worthy of targeting in the future.  It certainly wasn't forgotten in the implementation of column color customization.  It's just a separate feature entirely.

In case it isn't obvious, the way editing of navigation tag colors is currently designed is via Right Click on the xsheet/timeline and choosing Edit Tags.   This will then open the Edit Tag dialogue where colors can be changed.

Since we are here we might as well put in a request for those Nav Tags to not be constrained to limited number of colors such as is currently implemented.  Unifying tags and color selection capabilities will help across the board in this manner.

**Comment by JParks123** [comment]
sorry about the "u" thing I meant this to be a feature request but its no big deal really just thought it was something of use to some people I can wait in add it later on also my apologies if I came off as rude I was not intending it to be.
