### ISSUE TITLE
My frames are gone. What could i do to get them back

### ISSUE THREAD

**Issue by Agatha7Shokuko** [opentoonz/opentoonz#4857]
### Description

So, i was animating a project of mine for some hours. After i've finished my project, i clicked save scenen for guarantee in case it crashes like other times during an render. However, i clicked to preview my render and the program crashed, when open, it doesn't show my frames/drawings. (PLEASE, HELP ME GET THESE FRAMES BACK. LITERALLY MY FIRST ANIMATION THAT ACTUALLY WENT RIGHT BRO. If you got any idea of how to get them back, i would gladly hear it.)

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![Captura de tela 2023-04-27 022432](https://user-images.githubusercontent.com/131943362/234767650-2c30e3e2-0109-481b-a040-4f4112f7bade.png)
![Captura de tela 2023-04-27 023035](https://user-images.githubusercontent.com/131943362/234768019-b593f06d-1de6-4c8c-949f-9a5ee029e3ca.png)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

GAOMON

**Comment by RodneyBaker** [comment]
Sorry to hear of your problems.
Hopefully you can recover all your drawings.

Save Scene will only save the Scene... not the Drawings.
You should use Save All.

If you look into your stuff directory hopefully there are some files in your Drawings directory.
Those would be the 'frames' you are seeking.

As these are TLV (toonz raster) levels it's possible they are in the TLV drawing files but those particular frames are just not exposed.

**Comment by RodneyBaker** [comment]
If you did save your frames at any given time there should be some files in the drawings directory with a .bak extension.
Rename those to remove the .bak (leaving the .tlv extension) and load those into Opentoonz.  That might restore some or all of your drawings up to the point of that last save/backup.

**Comment by Agatha7Shokuko** [comment]
> 

So, i've opened my folder of drawings here, there's the levels of my drawing(S,E,L,F). However, these are in .tpl; .tlv and  others not important in .tlv.bak. If the files are not exposed, how can i expose them and find them? There's S.tlv/.tpl;E.tlv/tpl; L .tlv/tpl and etc

**Comment by Agatha7Shokuko** [comment]
> If you did save your frames at any given time there should be some files in the drawings directory with a .bak extension. Rename those to remove the .bak (leaving the .tlv extension) and load those into Opentoonz. That might restore some or all of your drawings up to the point of that last save/backup.

The levels that i need S,F,L and E aren't in .bak(even that others are, they're not the important ones) so what can i do?

**Comment by Agatha7Shokuko** [comment]
> Sorry to hear of your problems. Hopefully you can recover all your drawings.
> 
> Save Scene will only save the Scene... not the Drawings. You should use Save All.
> 
> If you look into your stuff directory hopefully there are some files in your Drawings directory. Those would be the 'frames' you are seeking.
> 
> As these are TLV (toonz raster) levels it's possible they are in the TLV drawing files but those particular frames are just not exposed.
> 
> Added: If you are crashing during a render then that is another problem (and I think a very important one) we need to resolve.

My Opentoonz also crashes oftenly, but i would like to solve the drawings problem first and then the crash

**Comment by RodneyBaker** [comment]
If the files are gone the only thing you can do is redraw them.

Something you can do is export the scene and either post it here or send it so that it can be inspected.
Without additional information it is guess work here.

What I personally would do if it was my project is examine the files and links to files thoroughly to see if something was moved or they are in another location.  For instance, you say you are looking for .TLV files with specific names.   Are there any other files on your computer with that name?

If using a fairly current release of Opentoonz you will see an export option in File > Export menu.
That's an ideal way to share the scene so it might be examined in more detail.

There are many of us that hang out in various Opentoonz venues such as Opentoonz discord.
If you share the file there we will do our best to guide you to where any lost files are most likely to be.
If not in the location stated via Level Settings then... short of someone examining your computer... which we can also do but few care to have strange people rummaging through their computer remotely... drawing the frames again will take a lot less time.

This is unfortunate but an important process to learn in order to avoid similar loss in the future.
Its a different discussion but we can talk at length about various ways to backup work and store copies to prevent loss.

Perhaps others can give additional advice that can assist in tracking down a copy of your file(s) but if they were never saved then there is nothing to recover.

**Comment by RodneyBaker** [comment]
If you are crashing EVER then that is too much.
This is another reason I'll recommend joining an online group so that they can share advice on that.
You can't afford to constantly crash while working on your projects.

**Comment by RodneyBaker** [comment]
You mention above the TLV files.  Examine those thoroughly via the Level Editor... not the main viewer.
Those are the files you are after (toonz reaster levels) and they may have the frames present but simply not being exposed/used.
This seems a bit unlikely given the information we've seen thus far but definitely worth the look.

**Comment by Agatha7Shokuko** [comment]
Every path says that i only have 1 frame, so...It'll be back to stack 0, right?

**Comment by Agatha7Shokuko** [comment]
> 

Opentoonz discord is on the official website? I've checked there yesterday and there's only twitter and facebook
Also, the only issue remaining then is how to fix the crashes...

**Comment by RodneyBaker** [comment]
Technically there is no 'official' Opentoonz discord.
The main one historically however has been this one:

Invite:  https://discord.gg/UQxvYBKW5U

From there we can easily link you to the other discords and venues as people frequent them all.

**Comment by Agatha7Shokuko** [comment]
Thank you for the link!

**Comment by RodneyBaker** [comment]
Will close this report but please do add any additional information you feel necessary that relates to the specific issue of crashing and losing your levels/frames in the first place.
