### ISSUE TITLE
Creating a motion path got stuck accepting the new path

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#4864]
### Description

After drawing a motion path, the dialog appeared, asking if I want to replace the motion path. Clicking yes just re-showed the same dialog.
I closed and re-opened OpenToonz and it happened again. So I had to find a different work around to move my matte.

### Steps to Reproduce

1. In the stage schematic, I selected a column, then pressed the Motion Path button to add a path to it.
2. Then I selected the brush and drew the path
3. The dialog appeared (Are you sure you want to replace the motion path), clicking Yes closed and reopened the dialog. Clicking No did the same! I had to press the X to get out of the cycle.

Notice that when I first pressed Yes, the Green filled rectangle moved (this is the image on the column), and subsequently clicking yes, the rectangle followed my click. It appeared that instead of the button getting the click, the viewer did, which recreated the path (with a single point) and that's why the question re-appeared.

### Expected Behavior

Clicking yes should accept my path.

### Screenshots, Video & Crash Logs

![ScreenRecording](https://user-images.githubusercontent.com/28575907/235445622-6b618b95-58eb-4546-9c20-76a42fd3d3de.gif)

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

V1.7rc

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Initially I couldn't reproduce but after some time I was able to reproduce it regularly.
Not entirely sure what release I was using at any given time so I need to verify.

Also, as I mentioned in discord as a workaround to escaping that endless loop of OT asking if we want to replace the motion path... try using the Enter key instead of clicking on the buttons as that appears to work.

**Comment by RodneyBaker** [comment]
@shun-iwasawa 
I'm not sure where this problem was introduced but I get this issue consistently and persistently with latest nightly release.
It's as if OT thinks we are drawing a new path... not recognizing the dialogue box is there.

This does NOT appear to occur with a mouse.
Use of Enter key works because we aren't drawing with that.

I would provide steps but for me currently the only steps are:
- Create level
- In Schematic create Motion path
- Draw motion path
- Note that dialogue refuses to easily acknowledge we are interacting with it and instead thinks we are drawing a new path... which then triggers the dialogue again.

**Comment by andeon** [comment]
> Probably fixes that (I have not yet updated OT to test these new things), so, perhaps the solution is also to replace e->accept() with that version of that second commit I listed.
> 

You mean override the `e->accept();`

for

`QGraphicsView::tabletEvent(e);` ?
