### ISSUE TITLE
Previewing or rendering files are blank/white

### ISSUE THREAD

**Issue by uplre** [opentoonz/opentoonz#4927]
Whenever I try previewing a file or rendering it, it always turns up white. I tried turning off and on the columns and it doesn't seem to work. Is there a solution to problem?

**Comment by RodneyBaker** [comment]
Can you post some (full) screenshots.
That would likely tell the tale of what is going on.

Use the Print Screen key on your keyboard (if using Windows) and then just Control V (paste) here in this report.

Someone else recently had a similar issue and they were able to easily remedy the problem.

**Comment by artisteacher** [comment]
Sometimes that happens if there are multiple output in the FX schematic - if the output that is active isn't connected to the Xsheet. You don't want this:
<img width="247" alt="Screenshot 2023-06-02 at 9 44 28 PM" src="https://github.com/opentoonz/opentoonz/assets/21159116/a0632e6f-04b8-4884-856c-43d5ec2019c7">

Every once in a while that happens to one of my students. 

Might be a case of accidentally triggering the shortcut. Making a new output automatically makes the new output active. At the same time, the new output isn't connected. Personally I don't see the point of making new outputs active without also connecting them to the Xsheet node. I think it would be better to automatically connect it. This could be a small change that could cut down on a lot of confusion.

Of course, there could be something else going on here.

**Comment by artisteacher** [comment]
Another possibility, if you are using vector levels & only have line-work, you could have zero-thickness lines. They are intended to create regions for cel-shading and as such, do not display in the render. If that's the problem, you can use the selection tool (probably with the mode set to whole level) and drag on the pump widget to add thickness to the lines:
<img width="110" alt="Screenshot 2023-06-02 at 9 54 40 PM" src="https://github.com/opentoonz/opentoonz/assets/21159116/3f218bce-da32-4073-986a-cb81b115e143">

**Comment by RodneyBaker** [comment]
@uplre Were you able to solve the problem?
Inquiring minds want to know.
