### ISSUE TITLE
Export animate GIF

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#494]
I think animate GIF is funny and Interesting. OT should be able to export that. (Maybe import that too)

**Comment by blurymind** [comment]
Importing it would be awesome for quick refetence

**Comment by turtletooth** [comment]
I am working on H264 support which will be using ffmpeg.  The version of ffmpeg I built includes webm support and gif support is built in to ffmpeg natively.  Maybe if I have time after H264, I can take a look at that.

**Comment by blurymind** [comment]
Gif import would be amazing too :b

**Comment by yamisama** [comment]
@turtletooth, sorry for being slightly off-topic, but before you invest too much work into ffmpeg integration: As I suggested in #419, it might actually be worth considering to not implement ffmpeg support directly, but instead work on integrating [OpenFX](http://openfx.sourceforge.net) plugin support with the reader/writer extension. That way the existing [ffmpeg plugin](https://github.com/MrKepzie/openfx-io) from [Natron](http://natron.fr) could be used.

It would save a lot of duplication of efforts, help alleviate licensing issues and make it easy to update the plugin to new ffmpeg versions without making a full release of the main application. Plus we'd get support for OpenEXR and a bunch of other file formats basically thrown in for free (not to mention loads of new effects plugins, including [Boris FX](http://borisfx.com/), [Genarts Sapphire](http://www.genarts.com) and Natron's file format plugins for [Open Image IO](http://openimageio.org/) and all the effects they built, including integration of Disney Animation's [SeExpr](http://www.disneyanimation.com/technology/seexpr.html), which would also address #344).

**Comment by blurymind** [comment]
@yamisama it would be good to consider which is a lower hanging fruit. @turtletooth has already started work on ffmpeg.
The  OpenFX support is sure nice, but it is more aimed at the FX schematic and might be a much bigger task to implement in OT.

**Comment by turtletooth** [comment]
@yamisama It looks like Natron's ffmpeg plugin is GPL licensed which would not work with OT.

**Comment by blurymind** [comment]
@turtletooth I think he is asking not for the plugin, but for a way to load the plugin in OT via the openFx wrapper.
In this case we wont be able to include natron's ffmpeg's plugin with OT, so it wont make for a built in exporter.

**Comment by yamisama** [comment]
The legal situation with GPL is not that simple as far as I can tell. The [GNU FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF) mentions calling external processes being ok and plugins that don't do much more than calling a main function and passing data back and forth being a "borderline case".

Since OFX plugins are more or less separate entities in their own right where the target host is not really known when they are developed, I'd argue that OFX host interaction is more akin to interacting with an operating system API in this case and the fact that they are compatible with a wide variety of hosts does not constitute them "form[ing] a single program". If, however, they did indeed "form a single program", it is questionable whether applying GPL to a plugin that could theoretically be used in a non-GPL compatible host, is even possible.

In general, this is what the [GNU FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF) suggests:

`However, you can resolve that legal problem by adding an exception to your plug-in's license, giving permission to link it with the non-free main program.`

I imagine that it could be possible to work something out with the Natron team regarding such an exception. Otherwise, what is the point in developing it as an OFX plugin in the first place. 

Whether it is possible to distribute OFX plugins that are under a license like GPL directly with OpenToonz is of course another matter. But that's the whole point:

My reasoning behind getting the ffmpeg support into a plugin, OFX or not, is that can be distributed separately. While the GIF patents have expired by now in most countries, H.264, ProRes and many other codecs supported by ffmpeg are still subject to a huge number of patents. H.264 for instance is represented by MPEG LA, which represents Sony, Microsoft, Panasonic, and many other large companies. It is questionable whether it would be legal to distribute an encoder with a software like OpenToonz without paying royalties, and laws may differ from country to country. To my knowledge, that's also why [Blender](http://www.blender.org) still doesn't have H.264 encoding of renders via ffmpeg.

Therefore putting the ffmpeg support into a separate plugin that can be distributed and installed separately would make it possible to let users install and use the plugin without creating a big legal question mark for OpenToonz itself.

@blurymind Installing an OFX plugin is as easy as it gets, basically drag and drop to a designated shared plugin folder (exact location depends on the OS) so that the plugins are accessible from all hosts on the system. Most commercial plugins come with installers to make it even more trivial. It's described in detail the official [programming reference.](http://openfx.sourceforge.net/Documentation/1.4/ofxProgrammingReference.html#ArchitectureInstallingLocation) 

The file format plugins could be hooked up inside the application like normal importer/exporters, using the standard render and file I/O UI. No need to go through the schematic.

**Comment by blurymind** [comment]
@yamisama can you dostribite the exporters with the software in that scenario?

**Comment by blurymind** [comment]
We could use google's open source encoding instead. You know, the one they developed for youtube

**Comment by turtletooth** [comment]
@yamisama There is some good info there.  From my understanding, H.264 royalties are only encumbered if you distribute more than 100,000 copies per year.  If OpenToonz gets there, there is also the option of bypassing ffmpeg and using the OpenH264 binaries that Cisco provides by giving users the option during install to include h.264 support and then downloading the binaries provided by Cisco- for which Cisco covers the patent fees.

I am sure that OFX plugin support would be a great addition.  I have very little experience with OFX (every time I have tried using Natron, it has crashed on me).  The learning curve in getting OFX support into OT is more than I can do right now.  I also feel like h.264 export is a more pressing item than OFX support.  

I am a middle school teacher and definitely need h.264 support for my students- AVI files are too large to turn in.  Getting h.264 working so far has already been a pretty big challenge for me (I have only been doing C++ for 2 months.)  In the future, if there is demand for it and I (or someone else) have the time, I would be glad to look into it.

**Comment by blurymind** [comment]
@turtletooth its worth looking into what krita is doing:
https://phabricator.kde.org/rKRITAf062517d322335a438728c3912512bf5a01b0872
Implemented saving the animation into mkv, ogv, gif and mp4

Also look into webm:
https://www.webmproject.org/

This codec is supported by all web browsers now - to view the animation people dont need to download and install anything.
Google developed webm precisely in order to solve the issue of codec patents - it affected them directly because youtube used to have a lot of videos with the patent infringing codecs.
Webm has an incredibly good quality, it is widely supported and has no royalty fees.

I advice everyone to support its use - that way the h.264 codec will become obsolete and its royalty fees will plummet

**Comment by yamisama** [comment]
@turtletooth If you have only 2 months of C++ experience, I have a lot of respect for you – ffmpeg/libavcodec is a notoriously messy C API and making everything exception and thread safe can be quite a challenge.

If you need H.264 for yourself and want to do it, that's great of course, though it would be sad if large portions of your work ultimately ended up being replaced. 100 000 copies doesn't sound unrealistic to me. We'll have to also see what the DWANGO team's take on the legal situation is.

If you just want to encode animations for delivery, you could always just have them render to an image sequence and then run a quick one-line shell/batch script that encodes the result using the ffmpeg command line tool [like this.](https://forums.creativecow.net/thread/291/1051).

But if native ffmpeg (or OpenImageIO) support really happens, GIF would of course be very nice as it's still sort of the undisputed standard for delivering short animations for the web, despite its limitations.

@blurymind That Krita patch seems to be using a C++ wrapper around ffmepg's crude C API to do the encoding. It's called [avTranscoder](https://github.com/avTranscoder/avTranscoder).

WebM is a nice idea, but Apple's iOS devices have a dedicated H.264 decoder chip built-in and don't support WebM natively, hence H.264 is still the better delivery format in practice for now. With ffmpeg support in place, encoding it would only be a few lines of code extra, though.

**Comment by blurymind** [comment]
Perhaps looking into avTranscoder might help @turtletooth

**Comment by walkerka** [comment]
@turtletooth Regarding of gif exporting, here's a very simple library to use.
https://github.com/ginsweater/gif-h

Not powerful as ffmpeg(nor giflib) but really easy to use. No license issue (public domain).

**Comment by turtletooth** [comment]
@blurymind @yamisama lt looks like Dwango wants to link to command line ffmpeg, but thanks for suggesting avTranscoder.

@walkerka Thanks for the suggestion.  It looks like gif-h only takes rgb8 as input, so there would still need to be a transcoder from rgb32 to rgb8.  So ffmpeg command line is probably a better option here, especially with the palette gen feature. (http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html).  

I've got the basic h264 working (but buggy).  If anyone wants to help take a look at the code, that will make gif export happen faster.  It will use the same process, with a few small changes.

**Comment by blurymind** [comment]
@turtletooth Thank you for the work on ffmpeg and for submitting a PR for gif export:
https://github.com/opentoonz/opentoonz/pull/624

**Comment by turtletooth** [comment]
Windows users can test this here: https://github.com/turtletooth/OpenToonzPortable/releases/tag/1.0.3-FeatureTest

**Comment by turtletooth** [comment]
Merged #624
