### ISSUE TITLE
Assistant Tool TZM file not recognized? [Linux]

### ISSUE THREAD

**Issue by deathchimera** [opentoonz/opentoonz#4958]
### Description

When first creating an assistant level, the terminal gives the error *"/home/ghost/assistant_test/assistant_test2/extras/C.tzm: seems it's not TZM"*. The assistant level shows up on the xsheet, but the assistant tool is greyed out, and the level itself is plain black. The files themselves don't look mangled in any way, though I haven't read any specifications on the file format or how it's read by OT.

Simple OT scene below containing the generated TZM files in the extras folder. Note that I ran it twice. The issues apply to each separate TZM file the same way.

### Steps to Reproduce

1. Create an assistant level

### Expected Behavior

For the assistant tool to be made available and the level to be read by OT.

### Screenshots, Video & Crash Logs

[assistant_test.zip](https://github.com/opentoonz/opentoonz/files/11778160/assistant_test.zip)
![temp-screenshot](https://github.com/opentoonz/opentoonz/assets/77942602/a304799b-6832-414a-b800-7cfc5a279b13)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

built Jun 17 2023

### Operating System

Linux

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
The black menu items are often an indicator that UI elements in the config directory are not present.
While perhaps not the issue here it will be worth checking to see if the new Assistants Tool UI elements were successfully incorporated into the stuff directory.  

In other words, if you got the program elements of the Assistants Tool but not the GUI elements that might explain the black menu items as they didn't exist before and would be missing when running the program.

**Comment by andeon** [comment]
Could you purge your .config/Opentoonz folder to test it? After you remove the $HOME/.config/OpenToonz directory, it will be recreated after running OpenToonz again.

**But remember to back up first if you've already created projects or any files.**

**Comment by deathchimera** [comment]
Purging the .config directory does get the assistant tool to work, but I don't believe .config is generated correctly. I had to generate .config using 1.7.1 to get the UI looking normal. Note that the TZM level still lacks its' proper UI element. The zip below is the .config directory generated when running the nightly.

[OpenToonz.zip](https://github.com/opentoonz/opentoonz/files/11780729/OpenToonz.zip)
![temp01](https://github.com/opentoonz/opentoonz/assets/77942602/980135a4-66f0-4582-8b82-1e947cafe61b)
![temp02](https://github.com/opentoonz/opentoonz/assets/77942602/a1cef8c5-5cbd-4eda-939f-044a1b21579d)

The first image is the assistant tool in action, and the second is running OT after only using the .config generated from the nightly. I have tried rebuilding the nightly to see if something changes but I haven't noticed anything.

**Comment by andeon** [comment]
@deathchimera  I pointed out this problem here https://github.com/opentoonz/opentoonz/issues/4027, we need a way to check the refactoring and follow a pattern, some things are deprecated and it's not affect only linux user.

**Comment by blackwarthog** [comment]
"C.tzm: seems it's not TZM" is just warning because file is not exists (because it is not saved yet)

The problem was only in outdated "~/.config/OpenToonz" directory.
The launching script only checks the existence of "~/.config/OpenToonz". And if it does not exist then just copy it from installation directory.
After some upgrades .config may become incompatible with newer version of OpenToonz
We still have no any system to properly upgrade the .config for Linux (may be for other OS too?)

**Comment by deathchimera** [comment]
Yea, haven't had any issues with the assistant tool or anything since updating the config directory. Had been doing manual local builds at the time cause the current aur package still hasn't fixed the build script. The past three times updating to the latest nightly show nothing out of the ordinary. Since this does just fall under the issue of separating user and app data in .config, I'll close the issue.
