### ISSUE TITLE
Mypaint Geometry tool and  TLV Raster shift for Straight line Bug.

### ISSUE THREAD

**Issue by JParks123** [opentoonz/opentoonz#4968]
### Description

Mypaint Geometry and TLV Raster and Raster Brush shift for Straight line is Broken in the Latest nightly build due to the new Assistant Perspective tool merge.

### Steps to Reproduce

1. try to use the Geometry rectangle tool with Mypaint.
2. try to use the shift for straight line Brush feature with Mypaint in Raster TLV, also Mypaint Raster brush has the same shift for straight line problem.

### Expected Behavior

the Mypaint Brush shift should let u maker straight lines and the Geometry tool should work with Mypaint brushes. 

### OpenToonz Version

1.7

### OpenToonz Version Information

current Nightly build

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RattusaurusRex** [comment]
I did a few tests to compare a pre-Assistant nightly with the current nightly.  I tested the Geometry Tool, Shift straight lines, and Ctrl+Shift straight lines with ToonzRaster and Raster standard and MyPaint brushes.

- The Geometry Tool no longer works properly with MyPaint on ToonzRaster or Raster levels.

- Shift and Ctrl+Shift straight lines no longer work at all with MyPaint on ToonzRaster levels only.

- Shift straight lines no longer work properly with Raster levels only.  Instead of letting you freely place a line at any angle, they snap (like the behavior of Ctrl+Shift).

- Also noting that Ctrl+Alt can now change the brush size with MyPaint on Raster levels only.  You could not change the MyPaint brush size with the shortcut on either ToonzRaster or Raster before the Assistant PR.


<img width="1085" alt="pre-assistant" src="https://github.com/opentoonz/opentoonz/assets/60277069/513d3cdf-7569-495c-a307-61c73080dabc">

I've marked each test failure in the current nightly with a red x:

<img width="1143" alt="currentx" src="https://github.com/opentoonz/opentoonz/assets/60277069/eb1e46dc-86c4-47db-acff-8a74d62bff0d">
