### ISSUE TITLE
The installers dont work they get stuck before they even get 100% of it done. 

### ISSUE THREAD

**Issue by jonbragado** [opentoonz/opentoonz#5011]
### Description

Neither of the installers work, both for Windows on the regular download nor the nighlty build. They get stuck at different percentages. 
See images attached below

### Steps to Reproduce

1. Download the latest version for Windows and als othe nightly build 
2. Try to install it

### Expected Behavior

I expect it to install completely and not get stuck 

### Screenshots, Video & Crash Logs

Nightly build:
![image](https://github.com/opentoonz/opentoonz/assets/47337932/51cfa2af-434d-42c2-964a-fede8f3364e8)
Latest Windows version 1.7.1
![image](https://github.com/opentoonz/opentoonz/assets/47337932/1b9d51e8-db6e-4956-9ee9-f39edc3188fc)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
@jonbragado I can confirm the installers do work... now we just need to find out why they aren't working for you.
Things that I would check if that were to happen to me include:
- Check to see if there is adequate space on the harddrive 
- Check antivirus program to include Windows Defender (if applicable)
- Ensure there isn't a read only directory involved preventing copying of installation files
- Make sure you didn't get a corrupted installer (i.e try downloading the installer again.

As your screen shots appear to show the installer stopping while in the stuff directory what you could do is rename your stuff directory (to something like "Opentoonz stuff (20230711)" and then install again.  Since there won't be any previous stuff directory any more the installer will create everything new.   Note that any project/scenes you worked on will still be in the old stuff directory so remember to look for them there.  Users can also opt to name the stuff directory something else other than 'Opentoonz stuff' during installation and that is an option even if only to test to see if that will work.

Also, you might open WIndows Task manager and check to make sure there isn't another instance of Opentoonz running that is preventing installation.  This can be true of other forks... make sure any program that is using same/similar files is not running during installation.

**Comment by jonbragado** [comment]
Solved the issue. 
I renamed the folder and when installing i unchecked "Allow to overwrite existing folder" and it passed thorough to the end of thei nstalation. Bear that i mind for future releases, you could probably make it unchecked by default. 

Thanks,
