### ISSUE TITLE
Can there be implemented a native project file format?

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#5016]
### Is your feature request related to a problem? Please describe

It's a bit of a mess to have the project tree scattered around when it potentially could be portable and clean right from the start. A solution I suggest is implement a native project format that would be read and updated on the fly with OpenToonz.

### Describe the solution you'd like

One thing that I REALLY wish OpenToonz had that other animation or art projects have is a native project format. GIMP has xcf, blender has .blend, krita has .kra, and there also exists ones like .ora for OpenRaster.  It would be incredibly convenient and more portable to have projects saved in a native project format (call it whatever you wish, .toonz or .ot for example). It doesn't even have to reinvent the wheel either, .kra is just a renamed zip file. libzip is under the 3 clause BSD license, so nothing to worry about with the GPL.
https://libzip.org/

Another reason is that I really wish to see a native project format is that it would be a one and done thing when zipping up to put it say on onedrive or wherever else I think it should go. Also, the project is rather than a large tree in a location it's just a single file zipped up containing the entire structure of a project.

**Comment by RodneyBaker** [comment]
Tagging as 'roadmap' as there is an aspect of this that is definitely moving forward.
What that takes the form of is yet to be seen and obviously a native solution will be ideal.

Some discussion was also had on discord that demonstrated a third party backup tool (for WIndows) by @DarrenTAnims that watches a directory/folder and makes zip file backups of projects whose contents have changed.  That isn't quite this feature but does come close in many ways.  That utility is currently available via gumroad at:  https://darrentanims.gumroad.com/l/Backup

Disclaimer:  The Backup utility isn't free (basically $1 or however much one wishes to pay) and you might wish to hold off on grabbing it as Darren will likely be posting a new version that fixes an issue when projects are located on drives other than C:\ Drive.  Again, Windows only so this won't be of much use to users of Mac and Linux.

**Comment by DarrenTAnims** [comment]
Thanks for mentioning the Backup tool Rodney.
This turns out to not be an issue with drives, but with how Tahoma saves. I've made a fix to this which will be uploaded to the site today.

**Comment by jointri** [comment]
> Tagging as 'roadmap' as there is an aspect of this that is definitely moving forward. What that takes the form of is yet to be seen and obviously a native solution will be ideal.
> 
> Some discussion was also had on discord that demonstrated a third party backup tool (for WIndows) by @DarrenTAnims that watches a directory/folder and makes zip file backups of projects whose contents have changed. That isn't quite this feature but does come close in many ways. That utility is currently available via gumroad at: https://darrentanims.gumroad.com/l/Backup
> 
> Disclaimer: The Backup utility isn't free (basically $1 or however much one wishes to pay) and you might wish to hold off on grabbing it as Darren will likely be posting a new version that fixes an issue when projects are located on drives other than C:\ Drive. Again, Windows only so this won't be of much use to users of Mac and Linux.

That is actually incorrect it would not have much use to Linux/MacOS users because the application Darren made was a C# program and C# works with mono for GNU/Linux as well as MacOS users. I installed mono-complete on my debian machine (for example) here and these three screenshots would show you me running it like I was on windows.
![One](https://github.com/opentoonz/opentoonz/assets/81046576/ff0619d5-98b6-45b1-9c4a-0e525a104fa8)
This is a cropped screenshot of the directory containing my OTBackup.exe application, the config, and a few unimportant shell scripts.

![Two](https://github.com/opentoonz/opentoonz/assets/81046576/4baa8d41-59cb-47d3-bfb1-8cbffa498e41)
Here is the 2nd screenshot showing typing the mono command to use the mono runtime as a VM to run the C# compiled program.

![Three](https://github.com/opentoonz/opentoonz/assets/81046576/09c7062a-288a-47f1-90dd-82053fd2aead)
Here is the last screenshot showing the end result. It looks a bit weird, but it runs the same as on windows. So in the end, installing the mono and/or dotnet runtime will allow anyone on unix systems to run this backup program. It's not just windows ony.

**Comment by RodneyBaker** [comment]
All good and thanks @jointri!  The program itself is Windows only... just reflecting what the program specifies... but those savy enough to use emulators and such can certainly use it elsewhere.  

Glad to see that is your case and Linux users will appreciate the information you have provided.
It's good that we live in a world where programs can run cross platform that weren't actually designed to run cross platform.

**Comment by jointri** [comment]
@RodneyBaker The interesting thing about C# is that it's very similar to java. It was never once a native binary. Linux has ELF binaries (or whatever the technical terminology is) and windows has PE/COM or whatever the technical terminology is. There is no emulation at all being used. Java for instance was meant to run anywhere and you never run an actual executable that was meant to be optimized for a specific operating system. Instead java programs (and C#) goes through a virtual machine to make it more cross platform. So when @DarrenTAnims compiled his C# program, it was never optimized for windows, but instead optimized for usage with the virtual machine that runs the C# program. That's why it's seamless or almost seamless to run C# programs on linux or MacOS because the VM is very good. Like I said, no emulation at all of any kind. The mono VM has been made very well to be on par with the one built into windows. Though you could still say that the OTBackup program was only meant for windows because it was built on windows and only really tested on windows, but to say it's a windows executable as in a C/C++ compiler optimized it for windows specifically would be incorrect.

**Comment by jointri** [comment]
And additionally, if I desired to and studied a bit of how to do it, I could decompile Darren's program easily because CLR (Common Language Runtime) is more or less just bytecode. It's very easy to compile a C# program compared to a native binary compiled with C or C++ through gcc or clang or whatever. That further makes it blurred from being a native binary vs just ran in a special virtual machine. Same thing with java. Now, it wouldn't be fair to say java and C# are the same. Just have a bit of similarities.

**Comment by RodneyBaker** [comment]
Windows is reportedly gaining some native support for addtional archiving formats... rolling out now in development... later in the fall for official Windows 11 releases.  

Reportedly this follows after work done in libarchive.  REF:  https://github.com/libarchive/libarchive

https://youtu.be/2Fxplhd6ads

This won't necessarily help users of Windows 10 and earlier but that might be added via libarchive itself.

With native support for .rar, .tar and zstd compression... things are at least moving in the right direction.

**Comment by jointri** [comment]
> Windows is reportedly gaining some native support for addtional archiving formats... rolling out now in development... later in the fall for official Windows 11 releases.
> 
> Reportedly this follows after work done in libarchive. REF: https://github.com/libarchive/libarchive
> 
> See also: https://youtu.be/2Fxplhd6ads
> 
> This won't necessarily help users of Windows 10 and earlier but that might be added via libarchive itself.
> 
> With native support for .rar, .tar and zstd compression, amongst other archival formats... things are at least moving in the right direction.

Nobody who knows what they're doing, uses the official built in zip extractor because it's slow. Every time I've seen it, it's 2-3x slower than just using 7zip or winrar or anything else other than the built in extractor for windows.

**Comment by jointri** [comment]
@RodneyBaker @DarrenTAnims If I could make an additional suggestion, could we possibly instead see DarrenT's backup program implemented natively into OpenToonz/Tahoma2D. His program uses the .NET file monitor capabilities, which interesting enough is also built directly into the Qt toolkit since version 4. The class is called QFileSystemWatcher.

Qt5 -
https://doc.qt.io/qt-5.15/qfilesystemwatcher.html

Qt6 -
https://doc.qt.io/qt-6/qfilesystemwatcher.html

**Comment by jointri** [comment]
> Windows can do that natively, at least with scheduled tasks, and unices can do that with cronjobs and inotify file events. Or manual backups with git and the like.
> 
> But it also wouldn't hurt it to have it in OT directly.

The windows schedule tasks requires admin rights and I can't recall right now a non admin portable way to do scheduled tasks on windows. And DarrenT's program automatically backs up any time there is a file change, can git do the same thing?

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themselves.
There may still be useful information contained in this report and it is recommended where that is the case the information be transferred either into a new report or into Opentoonz documentation.
