### ISSUE TITLE
XSheet Column UI Design

### ISSUE THREAD

**Issue by AyameLee** [opentoonz/opentoonz#513]
After looking at #490 I got thinking about the XSheet column design so I had a whip around the office to hear what some UX designers thought.

- Excessive padding between elements
- Opacity should have a button (#490 by @2dvision)
- Toggle buttons should be opaque with high contrast (accessibility)
- Lock icon should show icon at all times (unlocked padlock or locked padlock)
- No need for user facing ID (Harlequin) simply set default name to sequential numbering

Here is something we mocked up (we looked at both OpenToonz and Harlequin but applied accessibility improvements to both).

![xsheet_concept](https://cloud.githubusercontent.com/assets/18118611/16309363/5a7a9e10-3960-11e6-8845-e99136c7d9d4.png)

There is a point about always having the toggle buttons visible even when in their OFF state, instead of hiding the icons the icon should switch to a new icon.

![xsheet_concept3](https://cloud.githubusercontent.com/assets/18118611/16309945/6ec7753a-3962-11e6-8dfe-7217a6d3f198.PNG)

Just some ideas.

**Comment by blurymind** [comment]
This is a good idea. The dissappearing disabled buttons have bugged me in the start.
On a related note - that problem can also be found in node buttons in the schematic view:
https://github.com/opentoonz/opentoonz/issues/411

**Comment by shun-iwasawa** [comment]
The camera stand visibility toggle is for switching the camera-stand-opacity value between the "current value of the opacity slider" and 0. The opacity slider has effect only in the camera stand view and is ignored in rendering. 
So IMO the UI of the opacity slider should looks like more being related to the camera stand visibility toggle and separated from the preview visibility toggle somehow.

**Comment by AyameLee** [comment]
@shun-iwasawa I see, thank you.

Could an integrated draggable icon with a sliding background bar work? Here's a demo. The arrows either side of the camstand icon make it a little more obvious. Some kind of alternate key press or ctrl+left click could invoke the legacy controls.

![tz_xs_c1](https://cloud.githubusercontent.com/assets/18118611/16326840/0f64006c-39c2-11e6-8c07-b77daaa958d4.gif)

**Comment by Rayek** [comment]
I actually like the current size of the toggle button for the preview and table view. For one, it makes it very obvious to see at a glance which columns are active and which are not, and secondly tiny icons with tiny hit areas are terribly inconvenient when working with a tablet (or even a mouse). 

This sounds more like eye candy, rather than a functional convenient GUI design decision.

**Comment by blurymind** [comment]
We can add a 'click and hold to change opacity' hint when you hover over the button

**Comment by konero** [comment]
I agree with the issues raised about accessibility, try viewing OT on a low blue light or energy saving monitor and watch those icons vanish. I'm someone who believes very strongly in standardization though and everyone using the same conventions. It just reduces waste and less stuff I have to spend time teaching.

I don't know about the opacity issue, I didn't even know it existed, but if it has no bearing on the render then I don't think it's very important. That mock-up slider looks awesome though. But I think a tool-tip with a new icon could do the trick.

I also agree about the issue raised by @blurymind and others about invisible icons. I think things like this are fine in closed environments, but it has to be a bit more dummy-proof for the masses. At least once I wondered how to do something, only to find the thing I was trying to do was invisible.

Other than that I'm a big fan of that "Kiki" XSheet UX. I'm someone who _(sorry @shun-iwasawa)_ prefers the Harlequin UX _(but I'm still fine with the current one)_ because it keeps all the actions confined to one space, gives a much larger area for the labels which is important for cut-out artists _(currently there is a big eye icon that covers most labels)_ and as was highlighted above has nice contrast.

@Rayek The points seem to come from a UX (User Experience) perspective (@AyameLee & @blurymind) and not UI. I dislike small icons as much as I dislike large icons, but those icons are not much smaller than the icons in my taskbar, are the same or larger than icons found in Photoshop, Clip Studio, Krita, Natron, Retas, Fusion, Blender and Harlequin.

As long as no more icons are as small as these I'm good. :+1: 

![rlly](https://cloud.githubusercontent.com/assets/19820721/16345503/2ab2a9e0-3a3a-11e6-842b-ca4209f87c9b.PNG)

**Comment by blurymind** [comment]
Bigger and more contrasty icons would be a good change for the nodes. 
![mockupnode](https://cloud.githubusercontent.com/assets/6495061/16347596/7c331416-3a45-11e6-9dff-a6bb60deec0a.png)
 
![mockupnode2](https://cloud.githubusercontent.com/assets/6495061/16347664/e1e8292c-3a45-11e6-948f-743445d6011e.png)

Nodes can be enlarged by zooming in at least. Level buttons on the other hand can not be made bigger like that.

@AyameLee that slider does look very sexy. The buttons being ontop of the slider would make it rather difficult to deal with however.
Perhaps the slider could be over the name of the level like this:
![mockupslider](https://cloud.githubusercontent.com/assets/6495061/16347866/e7f4c342-3a46-11e6-9416-9ad9abc9fffc.png)
clicking once would allow you to change opacity, double clicking would allow you to change the name of the level.
The user already expects that a double click is needed to change the name.
As for visibility - a new single click button could be added. 
Here I share @Rayek's opinion that the button needs to stay as big as possible and clearly light up levels that are visible and dim ones that are disabled. 
So in my quick mockup I made the buttons bigger. We need another mockup for enabled and disabled state.

A simpler solution for the transparency slider is to move it to the "Table" row like this:
![mockupslider3](https://cloud.githubusercontent.com/assets/6495061/16348085/58a245c8-3a48-11e6-833d-5d48dd20d859.png)

It would require much less refactoring  and will keep the buttons big

**Comment by blurymind** [comment]
For the inactive buttons, here is a quck mockup of how they might look like:
![mockupinactivebuttons](https://cloud.githubusercontent.com/assets/6495061/16348334/c975501e-3a49-11e6-9da0-4648f8f611e0.png)
If you want to I can make them :)
The inactive light table is just a light table that has no light
The inactive eye is just a closed eye
The inactive lock is just a lock that has been unlocked

**Comment by AyameLee** [comment]
I wasn't suggesting a "eye candy" change. :confused:

I don't use OpenToonz in any commercial or personal projects at the moment, there is a lot of work that needs doing in regards to stability before I can see it being deployed, this was simply some accessibility feedback. The optimizations made in OpenToonz in all are good and everyone is doing a good job.

I don't think the current UI should change, please note this was only casual feedback from UX designers, certainly not people who would be using OpenToonz.

I'll close this topic so as not to distract from critical issues and since there isn't actually a real issue here, more of a conversation better suited to somewhere else.

:+1:

**Comment by blurymind** [comment]
@AyameLee  I never said its just eye candy. You bring up valid points that need to be addressed. 
The mockups are just ideas - not meant as final design. We are discussing ideas - which need attention.
As such I think that it would be good for opentoonz if you reopen this issue and keep it that way for others to see and give feedback :)
