### ISSUE TITLE
prblem crach

### ISSUE THREAD

**Issue by tarik010275** [opentoonz/opentoonz#5200]
### Description

my plate-form it's instabel
[Crash-20231129-160158.zip](https://github.com/opentoonz/opentoonz/files/13536767/Crash-20231129-160158.zip)

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
At a guess your log appears to have similar problems as other users:  drivers and antivirus settings being the most likely candidates.  For instance:

ig4icd64.dll relates to a graphics driver and that would suggest looking into updating your current graphics driver.
If you reasonably sure you do have the latest graphics driver then consider backing down one (or more) drivers to see if that remedies the issue (or at least leads to different outcomes because... other problems may also be present... such as:

Related to graphics drivers... the graphics card itself and operating system...
We don't know a lot about your system but... perhaps you have an older graphics card?


aswhook.dll would appear to relate to Avast antivirus...
What I personally would do is remove Avast but I understand some have an affection for that software.
If it cannot be removed/replaced at a minimum make sure Opentoonz has sufficient authority to operate.
Opentoonz is an unsigned program so that will trigger many overzealous antivirus programs (and browsers) in an attempt to save the user from some potentially austere and terrible fate.

Do you have access to another computer (even temporarily) so that you can test and see if Opentoonz will run well on that system?

**Comment by RodneyBaker** [comment]
Here's a quote from @konero that he suggested to another user that aided in resolving some platform issues:

> It's most likely an issue with your system or a software conflict, try opening a cmd prompt as admin and run `sfc /scannow`, it will check for Windows corruptions and fix issues, if it does restart your PC and keep running it until it can fix nothing else, one thing to try if you haven't yet
