### ISSUE TITLE
Issue with vector levels and DPI

### ISSUE THREAD

**Issue by VECTORLEVELSDONOTLIKEME** [opentoonz/opentoonz#5249]
### Ask a question related to OpenToonz

When using vector layers, it won't let me change the DPI or turn off the 'force square pixel' setting. How do I fix this?

**Comment by gab3d** [comment]
@VECTORLEVELSDONOTLIKEME 
...and that's exactly how they are supposed to work. 😜

I guess you need to learn more about what a vector level is and how it really works.
Vector levels are not bitmap images, thus they haven't got any pixels, nor a DPI resolution, and that's why that kind of options are ghosted in this type of Level.

**Comment by VECTORLEVELSDONOTLIKEME** [comment]
Ahh, I was under the impression that a bug I was having was part of the 'force square pixel'. Thanks.
