### ISSUE TITLE
The ability to use bucket tool between levels

### ISSUE THREAD

**Issue by GIT-AKA** [opentoonz/opentoonz#5261]
### Is your feature request related to a problem? Please describe

I am new to using opentoonz and it is quite good so far. Great program but, the inability to use the bucket tool between layers is really problematic for me. I lneed to separate my colors from my line art. 

### Describe the solution you'd like

A good fix would be to use the bucket tool between levels. Making it able to detect lineart from other levels and working similarly as if it were on the same level.

**Comment by beeheemooth** [comment]
The option you're talking about already exists in Tahoma2D, it's called "Refer Visible". It's strange that Opentoonz hasn't used this yet.
https://github.com/tahoma2d/tahoma2d/pull/733

**Comment by DarrenTAnims** [comment]
It's worth noting that you can recognise lines separately to fills for different purposes. A lot of users like to have their fills on a different layer to the lines because that's what they're used to in other art software, but they don't necessarily need that while animating, so it's worth investigating why you need the fills on a separate layer. There could be "another way".

**Comment by GIT-AKA** [comment]
> It's worth noting that you can recognise lines separately to fills for different purposes. A lot of users like to have their fills on a different layer to the lines because that's what they're used to in other art software, but they don't necessarily need that while animating, so it's worth investigating why you need the fills on a separate layer. There could be "another way".

It is quite useful to work on your lineart and colors in diffrent levels. As it lets you edit any of the two without affecting the other. 
I understand I dont really need it but there also a bug in the program that I have commented on before that I am pretty sure you replied to just now (on reddit) 

I am not above learning a new work flow but still.
I trully belive this feature would be very helpful and make the program much more accesible to newcomers.

**Comment by GIT-AKA** [comment]
> The option you're talking about already exists in Tahoma2D, it's called "Refer Visible". It's strange that Opentoonz hasn't used this yet. [tahoma2d/tahoma2d#733](https://github.com/tahoma2d/tahoma2d/pull/733)

True and I am trying it out actually right now. I just really like opentoonz itself and how customizable it all is. Thanks btw

**Comment by oliver-dreamwalker** [comment]
> As it lets you edit any of the two without affecting the other.

I think the Toonz Raster level allows something like that.

**Comment by RodneyBaker** [comment]
A workaround while waiting for such enhancements to materialize might be to use the same level but spread it across 'layers'/columns.  Then the Fill Tool should work in the way desired.

Think:  'One level to rule them all'  :)

**Comment by DarrenTAnims** [comment]
> It is quite useful to work on your lineart and colors in diffrent levels. As it lets you edit any of the two without affecting the other. I understand I dont really need it but there also a bug in the program that I have commented on before that I am pretty sure you replied to just now (on reddit)

Using vector or Toonz Raster levels you can work on lines without affecting the fills and fills without affecting the lines. It's really powerful.
The bug you're referring to, I believe, is where you tried using the brush tool for filling. The brush tool isn't intended for filling. Use the Paint Brush tool or fill bucket instead and OpenToonz knows that you're adding fills.

**Comment by konero** [comment]
I'm not against the feature (I think it'd be useful), but as has already been pointed out Toonz Raster level type stores lines and filled areas as if they're on two hidden layers already and you access the layer depending on the tool selected using the 'mode' option in the tool options bar, or with FX such as 'Palette Filter' which will let you key specific colors by ID and whether you want the line or fill versions or both.

The reason storing it on multiple levels is a bad idea is because the files are stored on disk, so you'll end up with A_lines, A_fills for each object in the scene. You'll also need to parent them together if you need to transform them.

**Comment by DarrenTAnims** [comment]
> The reason storing it on multiple levels is a bad idea is because the files are stored on disk, so you'll end up with A_lines, A_fills for each object in the scene. You'll also need to parent them together if you need to transform them.

... and you'll have to keep them in sync in the timeline. So as you change to 2s, 3s, etc, you have to make sure to do it for both levels.
One final point, you're also double the amount of space taken up in the timeline.

**Comment by GIT-AKA** [comment]
It would be so perfect if it weren't for that one bug I must say.
Thanks for all the help tho <3

**Comment by gab3d** [comment]
@GIT-AKA 
Just as with any other program out there, first be sure you explored all the possibilities within its own workflow.
It's a common reaction of newbies trying to adapt the program to what they know, rather than the other way round. 
But also, commonly, the best long term strategy is to first try to adapt oneself to the workflow of the program, and only then when shortcomings still persist, suggest an improvement to it, based (if possible) on the learned workflow.

**Comment by GIT-AKA** [comment]
Thank you very much <3 To all of you
It is true I am a noob on this program but I feel pretty welcomed and I am glad you all answered my questions and helped me figure stuff out!
I am still learning it and there are some issue I think could be imrpoved but I will be learning more of it first as gab3d suggested, and if I can add anything of value to this community I'll make sure to write about it

I am gonna shut this chat now as I did get an answer to my question and turns out its already a feature in Tahoma2D as Beeheemooth said.

My final thoughts: 
**Good point:** I agree that using multiple layers in this progam is not necessary because of the powerful cababilities of colors being editable and changeable as one goes. You can use a color for your lineart and use diffrent colors that are separate from the lineart making it basically the same.
  
**Bad point:**  That one bug with the underall brush tool option and the fact it causes unawanted pixalizations between colors.  Which I was told is an old bug, is really quite annoying, I wish it could be fixed. There are work arounds but it is a bit of a pain.
