### ISSUE TITLE
Loss reframe level when load in new scene

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#527]
If you animate and reframe level, then save that. when load level in new scene, you loss reframe and all reframe is 1's. 

"Save level" just save drawing and reframe saved in current scene.

**Comment by 2dvision** [comment]
Another problem

If the number of frames look like this 1, 4, 3, 5, 2 and save level. then load level in new scene, the frame number is 1, 2, 3, 4, 5.

**Comment by shun-iwasawa** [comment]
Note that reframing on Xsheet is just editing the placement order of animation frames of the level in Xsheet and is NOT editing the order of animation frames contained in the level itself. And since such reframing data belongs to Xsheet, it saved in the current scene.
If you would like to edit the animation frame contained in the level, please use the Level Strip panel.
If you would like to control arrangement in Xsheet when loading a level (without editing the level itself), please try the "Arrangement in Xsheet" option on the bottom-right of the Load Level popup.

**Comment by 2dvision** [comment]
I record this [screen video](https://drive.google.com/file/d/0B9wCH2-wDK31ZVBQbHlPSzU5T3M/view?usp=sharing), I think its very bad function.

What can i do, If i animate a walk cycle and i want import it to new scene?

**Comment by shun-iwasawa** [comment]
If you would like to utilize the cell order in another scene, please load the scene as sub-xsheet with Load Level command then explode it.

**Comment by blurymind** [comment]
@shun-iwasawa is correct. Levels just contain drawings (level strip). The
timing and order data in the xsheet is stored in the actual scene file. You
still have the ability to import that- you are just not doing it right
On 27 Jun 2016 11:38, "shun-iwasawa" <notifications@github.com> wrote:

If you would like to utilize the cell order in another scene, please load
the scene as sub-xsheet with Load Level command then explode it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opentoonz/opentoonz/issues/527#issuecomment-228711087>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGMbVbGJ_wbKcV-OovCh0MRdtyrVUsVKks5qP6gPgaJpZM4I-RDM>
.

**Comment by blurymind** [comment]
I think that the current design is very good, because it allows to swap a
level for another level, while keeping the frame timing data in tact. Its
good that these two things are sepparate

**Comment by 2dvision** [comment]
Thank you @shun-iwasawa . Solved with sub-xsheet for now. :)
Maybe need new fast and easy function for this.

**Comment by turtletooth** [comment]
Can this be closed as this behavior is intentional?
