### ISSUE TITLE
File not saving.

### ISSUE THREAD

**Issue by weba7** [opentoonz/opentoonz#5283]
### Description

When I create a scene then a error occurs and a message box displays cannot save scene.
After I close the messagebox a new window opens of opentoonz where I animate but still it is not saved!!
Another issue is when I used rectangle tool then the application becomes unresponsive and fault module is "ucrtbase.dll".

### Steps to Reproduce

1. Please fix it.
2. 

### Expected Behavior

I would expect that when I create the scene then it would be created successfully.
And when I use rectangle tool then it should not turn unresponsive.

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
If you'll share some images showing the dialog box and your full screen, it could give an indication to the problem. Without it we'd just be guessing.
What's in the scene?
Is this a new project or part of the Sandbox?
What did you do before you clicked save?
How did you create the scene?

**Comment by RodneyBaker** [comment]
Until you get your saving issues sorted out I will recommend using the default location to install and save to.
In your screenshot you are trying to save to a location 'C:\opennew'.
Perhaps there is a permissions issue or your antivirus (Windows Defender or otherwise) is preventing the save.

As Darren suggests, any and all information you can provide will help in troubleshooting the problem.

I'll also recommend downloading and using the latest nightly release as that contains many features and bugfixes.
That link is directly below the main download button on the Opentoonz website but you can also access the nightly here:  

https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_b9a43f42714ee033300d027c889551fd4125d41c/OpenToonzSetup.exe

**Comment by weba7** [comment]
This project in opentoonz is a new project rather than a part of sandbox. Before clicking save scene I created a new project and named it . Then I clicked on new scene and named the scene. Next I clicked save scene which makes the program unresponsive. After closing the dialog box the program become responsive yet the scene is not saved.
Then I tried to use rectangle tool but the application becomes unresponsive. If I use the plastic tool or brush tool then it works correctly.

My os=windows 7 ultimate 64bit sp1.
The error code shown by windows after using rectangle tool="
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	OpenToonz.exe
  Application Version:	0.0.0.0
  Application Timestamp:	645afc80
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.14393.2247
  Fault Module Timestamp:	5adc1d0b
  Exception Code:	40000015
  Exception Offset:	000000000006eacf
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	4e51
  Additional Information 2:	4e51f601602509c0745f989907575c95
  Additional Information 3:	0699
  Additional Information 4:	069988ce86c5c8a9e6fc9d8a5dd446d4".
Error image after save scene="
![err1](https://github.com/opentoonz/opentoonz/assets/138605749/2749116c-1077-4797-9044-b921c8b4d6c9)
"
Error image shown after using rectangle tool="
![err2](https://github.com/opentoonz/opentoonz/assets/138605749/a0965796-6c4e-4c50-8326-09ea6ae979e9)
".
