### ISSUE TITLE
IT CLOSED SUDDENLY

### ISSUE THREAD

**Issue by SebastianORE** [opentoonz/opentoonz#5328]
### Description

IT CLOSED SUDDENLY

### Steps to Reproduce

1. IT CLOSED SUDDENLY
2. 
3. 

### Expected Behavior

IT CLOSED SUDDENLY

### Screenshots, Video & Crash Logs

![AAAAAAA](https://github.com/opentoonz/opentoonz/assets/162924051/b84cf363-a6c9-4420-adfc-4d515f115370)

### OpenToonz Version

1.7

### OpenToonz Version Information

2024

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Hi @SebastianORE,
Sorry to hear you are having problems.
In order to keep this report from closing suddenly for lack of information we're going to need more information.
Short of that all we can do perhaps it suggest joining one of the Opentoonz discords where others can help you troubleshoot.

Opentoonz discord invite:  https://discord.gg/GQTTzZTT4r
