### ISSUE TITLE
TVPaint JSON Not Available in Custom Rooms

### ISSUE THREAD

**Issue by ForestEco** [opentoonz/opentoonz#5359]
### Description

Hello,

I tried modifying the XML for the rooms to add the menu options to see if OT could interpret the options, but it wont allow even a manually coding of XML to display the export option of TV Paint JSON. I really like a course's OT rooms, but it doesn't show the option and I tried enabling it through preferences and cannot seem to locate how to do it. Can someone help or is this a bug and I have to load the default rooms only? And how do you actually get TV Paint JSON to work? There doesn't seem to be clear documentation about this.

### Steps to Reproduce

1. Try loading custom rooms (I took DarrenT's course so this one shows only two options in the export)
2. Try the Default, it shows it just fine, but would have to customize the rooms by hand

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
I guess I don't understand the question.
Rather than manually adjust the XML you might just use Opentoonz option to adjust the menus of the custom room.
The option to add/remove TVPaint JSON is there by default in a newly created custom room and if removed is present in the list to be added as well.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/23d4aa0c-46e1-4bc9-939a-185c066038e0)

It may be that there just isn't a dedicated icon for the Export to TLV options so we see a blank space where the option is placed in the menu.

Here however, I've just added the option again to the end of the File menu:
![image](https://github.com/opentoonz/opentoonz/assets/2576432/d1b59f30-4077-4619-8ce9-5693a0d8fab6)

The XML entry for that looks like this in the XML file (See the last command entry):
<?xml version="1.0" encoding="UTF-8"?>
<menubar>
    <menu title="File">
        <command>MI_NewScene</command>
        <command>MI_LoadScene</command>
        <command>MI_SaveAll</command>
        <command>MI_SaveScene</command>
        <command>MI_SaveSceneAs</command>
        <command>MI_OpenRecentScene</command>
        <command>MI_RevertScene</command>
        <separator/>
        <command>MI_LoadFolder</command>
        <command>MI_LoadSubSceneFile</command>
        <separator/>
        <command>MI_ConvertFileWithInput</command>
        <separator/>
        <command>MI_LoadColorModel</command>
        <separator/>
        <menu title="Project Management">
            <command>MI_NewProject</command>
            <command>MI_ProjectSettings</command>
            <separator/>
            <command>MI_SaveDefaultSettings</command>
        </menu>
        <separator/>
        <menu title="Import">
            <command>MI_ImportMagpieFile</command>
            <command>MI_ImportOCA</command>
        </menu>
        <menu title="Export">
            <command>MI_ExportTvpJson</command>
        </menu>
        <separator/>
        <command>MI_PrintXsheet</command>
        <command>MI_Print</command>
        <separator/>
        <menu title="Script">
            <command>MI_RunScript</command>
            <command>MI_OpenScriptConsole</command>
        </menu>
        <separator/>
        <command>MI_Preferences</command>
        <command>MI_ShortcutPopup</command>
        <separator/>
        <command>MI_ClearCacheFolder</command>
        <separator/>
        <command>MI_Quit</command>
        <command>MI_ExportTvpJson</command>
    </menu>

**Comment by RodneyBaker** [comment]
Concerning any of @DarrenTAnims's specific videos you might ask on Darren's discord channel but he'll likely see this report as well.

**Comment by RodneyBaker** [comment]
As for TLV export itself, note that there are limitation to what can be exported.
For instance, only raster levels... not toonz raster or vector levels... will be exported.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/a6ea71a4-3d9b-4bab-8f29-fdb91fd7ae3a)

**Comment by ForestEco** [comment]
Thanks for all of your help. I had to place the raster and scene in drawings folder and the JSON worked.
