### ISSUE TITLE
The worst program ever

### ISSUE THREAD

**Issue by KlaimV** [opentoonz/opentoonz#5372]
### Description

I can't work in this program. It has stupid tools. I can't do anything normal. It's like free copy of Photoshop. Make program more comfortable. 

### Steps to Reproduce

1. Buid in more thing from Photoshop
2. OR delete this program

### Screenshots, Video & Crash Logs

It's just stupid program

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by gab3d** [comment]
The worst human ever.

**Description**
We can't work in this human. It has stupid thoughts. We can't do anything normal. He wants a free copy of Photoshop. Make human more reasonable.

**Steps to reproduce:**
1. Build a more sociable character.
2. OR delete this human.

**Expected Behavior**
*No response*

**Screenshots, Video & Crash Logs**
It's just stupid human

**Human Version**
0.01

**Comment by KlaimV** [comment]
Thanks !

пн, 1 квіт. 2024 р. о 09:09 Gabriel Gazzán ***@***.***> пише:

**Comment by gab3d** [comment]
@KlaimV  you're welcome.
