### ISSUE TITLE
Messed up interface

### ISSUE THREAD

**Issue by LIKHIT123498** [opentoonz/opentoonz#5378]
### Ask a question related to OpenToonz

im using opentoonz for animation, but today the interface is messed up. plz help i have attached a screenshot with this.
![Screenshot (5)](https://github.com/opentoonz/opentoonz/assets/165705754/da62faa4-0a33-4b38-8456-6454cd03acb3)

**Comment by JParks123** [comment]
you must have double-clicked the X-sheet title bar simply double-click it again to minimize the X-sheet.

**Comment by RodneyBaker** [comment]
@LIKHIT123498 If you even run into UI problems and don't want to mess with figuring out what has changed and how to get the default menu back into place we can reset the UI and after restarting have everything back in place.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/d3b82f3d-afb4-4f29-89c2-b1c2240c180c)

This beats reinstallation in order to accomplish basically the same thing.
