### ISSUE TITLE
Rendering crashes after saving *sandbox* and closing on subsequent file opens

### ISSUE THREAD

**Issue by junkbox666** [opentoonz/opentoonz#5412]
### Description

Scene will render fine both 'Render'>'Render' and  'Render'>'Fast Render to MP4'  in sandbox i.e. fresh document (untitledn). After saving the scene with a proper name, closing the application and reopening the file, the render function crashes at a certain point (seemingly random) and the application terminates. Likewise, saving an 'untitledn' while still on first run does not crash the render. However, upon closing and reopening the application and loading the above scene, the render process crashes the application.

### Steps to Reproduce

1. Create small animation ~10 frames in an untitled/sandbox document
2.  'Render'>'Render' OR 'Render'>'Fast Render to MP4'
3. Save file and close application
4. Restart application and 'Load Scene' (previous saved file)
5. 'Render'>'Render' OR 'Render'>'Fast Render to MP4'
6. Application unexpectedly terminates

### Expected Behavior

1. Start a sandbox Scene
2. Render it
3. Save it and close application
4. Come back later and render again as needed.

### Screenshots, Video & Crash Logs

[Report.txt](https://github.com/opentoonz/opentoonz/files/15047206/Report.txt)

https://github.com/opentoonz/opentoonz/assets/112841612/dbfd7674-0fa1-47ab-b611-c046a51121be

not sure the TXT file (renamed *.wer file) will help, but there is no AppData\Local\OpenToonz\OpenToonz\crash\ folder

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

1.4 (Morevna Edition)

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
You really should save your scene before rendering (using Save All).
Rendering an unsaved scene shouldn't creash but is asking for problems.

Fast Render is a method added to Opentoonz to bypass complexity and options found in Output Settings... the proper place to render scenes.  Fast render ONLY renders to MP4 format which will fail if FFMPEG isn't properly connected and potentially crash

The 'Render' option just uses the last used settings for rendering.

It sounds ot me like you should investigate your copy of FFMPEG and make sure it is properly connected to Opentoonz and it works well using Output Settings render dialogue.  If it works there it will work well with Fast Render and with the direct Render option.

Please note that the most recent release of FFMPEG does have an update that appears to break GIF rendering so you will probably want to take that into account.  Perhaps use an older release of FFMPEG prior to the May 5 release.

**Comment by junkbox666** [comment]
> You really should save your scene before rendering (using Save All). Rendering an unsaved scene shouldn't creash but is asking for problems.
> 

As stated in OP (perhaps not clearly), saving before rendering on the 'first run' produces the same results. I started a new scene using the dialog to let the application build the folder structure before hand in case 'Save As' wasn't doing it's job entirely...which it wasn't actually, output somehow remained in the sandbox folder. But starting with the wizard made the folder structure with the scene name folder and proper sub folders.
 
> Fast Render is a method added to Opentoonz to bypass complexity and options found in Output Settings... the proper place to render scenes. Fast render ONLY renders to MP4 format which will fail if FFMPEG isn't properly connected and potentially crash
> 
> The 'Render' option just uses the last used settings for rendering.
> 
> It sounds ot me like you should investigate your copy of FFMPEG and make sure it is properly connected to Opentoonz and it works well using Output Settings render dialogue. If it works there it will work well with Fast Render and with the direct Render option.
> 

As shown in the video rendering does work, but just on the first run 'Fast' Render' and menu 'Render' using last known good configuration, meaning whatever was last used in 'Render Options', was *.tif by default but I played with other formats that likewise worked. Subsequent openings of the file and render attempts still crash the application. 


> Please note that the most recent release of FFMPEG does have an update that appears to break GIF rendering so you will probably want to take that into account. Perhaps use an older release of FFMPEG prior to the May 5 release.
> 
> You might also consider trying the Tahoma2D fork of Opentoonz which is distributed with a copy of FFMPEG.
>
Reconfigured to the 6.6.1 build (Dec. 31 '23) and pointed to the correct folders again in settings, and restarted the application. Same behavior. 

If this were an FFMPEG issue wouldn't the application crash when I run it the first time? What changes after save? As stated, no matter how I crate the project or when I save it...as long as the application hasn't been closed it will render all day.

**Comment by RodneyBaker** [comment]
I'm not sure exactly what Fast Render uses.
I assume it uses a limited amount of instuctions from Output Settings.
It's hard to verify as the developer deleted their github account which made them a ghost... and PRs assigned to ghost are excluded from searches.  That search might work for repo owners but alas... most of us aren't the OT repo owner.
Here I just mean to suggest that Fast Render is not as reliable as rendering via other methods.

I mostly mention FFMPEG because use of the MP4 format in Opentoonz requires FFMPEG.
As such if there is something wrong with FFMPEG or the connectivity with FFMPEG... you'll see that when using MP4... but not TIF, as that doesn't require FFMPEG.  In other words, if TIF is working... or not working... then we can likely rule out FFMPEG beause it isn't being used.  Other formats such as MP4, APNG, GIF, etc. rely upon FFMPEG.

Footstomping aside:  Don't use 'Save As' though as that will not save your levels... Save As only saves the Scene file.
Use 'Save All' instead.  Save As will likely do its job but that will be to save ONLY the scene file.
Note that I use Save As quite often... to create new iterations of an existing scene... immediately follow up by a Save All.
The new scenes will refer to the same levels as the old scene however which... if we don't save the levels can prove to be problematic.

> 6.6.1 build (Dec. 31 '23)

Hmmm... That reads strangely to me.  Dec 31 '23 should be 7.7.1 but perhaps that is just a typo?

We can certainly continue to troubleshoot here in this report but if you are of the mind to do so I'll recommend joining the Opentoonz discord as those that will likely respond here will also be there and can respond in a more direct and timely manner.

This gets posted periodically but for convenience here's the invite link:  https://discord.gg/8HaY3rU4SA

I should mention this although it doesn't align with my experience:
Many Opentoonz users (read:  more than 5) recommend not using the Sandbox as they find it unreliable.
I use the Sandbox a lot without issue but acknowledge it is generally best to create a new Project which creates a new directory structure which then can safely contain all that projects files.  If experiencing problems with the files stored in the Sandbox perhaps this will be a useful recommendation.

**Comment by junkbox666** [comment]
>
> You might also consider trying the Tahoma2D fork of Opentoonz which is distributed with a copy of FFMPEG.
>

Did try Tahoma2d and it does not exhibit the same behavior, saving a file before during or after does not affect future renders. For giggles I pointed Tacoma's FFMPEG binary to my copies of FFMPEG both 7.0 and 6.6.1 and the application behaved as expected. Likewise I pointed OpenToonz to the binary that is packed with Tacoma2d and OpenToonz still crashed after initial save and reopen.

![output](https://github.com/opentoonz/opentoonz/assets/112841612/28ec0177-bb11-4f2a-894d-454775a607f9)
![pref](https://github.com/opentoonz/opentoonz/assets/112841612/2f773e9c-1a2a-429c-8c96-7ee1fe31f392)

In my mind this removes FFMPEG as the culprit. The prefs are the same, and every combo of the binary have been tried...leads me to believe it's the application itself.

>>
>>6.6.1 build (Dec. 31 '23)
>>
>
>Hmmm... That reads strangely to me. Dec 31 '23 should be 7.7.1 but perhaps that is just a typo?
>

![chrome_2VeidlriLm](https://github.com/opentoonz/opentoonz/assets/112841612/d7d57265-a727-4cf1-bee4-69d9d45d92e5)

I dunno.

**Comment by RodneyBaker** [comment]
John does supply his own version/build of FFMPEG so... that alone doesn't rule out FFMPEG being a problem for Opentoonz.

What WOULD likely rule that out is if you point Opentoonz to Tahoma2D's version of FFMPEG and use that.

Definitely worth doing and in fact I often recommend that immediately after downloading and installiing Opentoonz that users download Tahoma2D as that will supply FFMPEG, Rhubarb and other third party software that can also be used with Opentoonz.  Thereby negating the need to download all of those separately.

**Comment by RodneyBaker** [comment]
RE:  

> 1.4 (Morevna Edition)

Seriously?

**Comment by junkbox666** [comment]
> RE:
> 
> > 1.4 (Morevna Edition)
> 
> Seriously?
> 
> Nothing against the Morevna Edition but... um... er....
> 
> Morevna Edition is over 4 years old.

IDFK - First I've heard of opentoonz was a week ago...followed a link, I wasn't aware it was a fork. 
Grabbed the latest build from here just now. If it works, I'll burn the ticket. I do like Tacoma, I just got tasked with a music video and Tacoma 'out of the box' behaves more like Flash (interface-wise) which was my web animator of choice. So I may stick with it. However I don't want to miss out on some of the other features of core. Not clear on the interoperability of the two but will test the above behavior against the current build.

**Comment by RodneyBaker** [comment]
I'll recommend going with Tahoma2D for now in your case.
Opentoonz is right in the window just prior to the next release and some stability issues will be encountered due to that.
There is no reason you won't be able to use both. Opentoonz and Tahoma2D though as they are largely the same program.

In the June/July timeframe then you can add Opentoonz into the mix... assuming you want to use both.
Most of the Tahoma2D users on the Opentoonz discord are also on the Tahoma2D discord.
I'll recommend joining the T2D discord so you can dive deeper.
T2D discord invite link:  https://discord.gg/bN3Gu6J4Ux

**Comment by junkbox666** [comment]
Gonna burn this ticket. Did a clean install of the latest stable release from the "website" 1.7.1 and the application behaves as expected. I used a slightly older 6.6.1 build of FFMPEG, might try the new 7 build...OR won't depending on if I get around to it. This version of OpenToonz is much more friendly out of the box than the Morevna Edition. My apologies for my confusion about there being different forks, s'pose I should have guessed due to the fact that this Issue Tracker didn't have that version in the create ticket dialog dropdown for version. 
Anyhow, now I have enough faith to get grinding knowing I can render more than once :)
I think I'll keep Tahoma2D around as it's portable. I'll just need to do some playing around with interoperability between the two but that is a discussion for discord, actually there was a question in there this morning I'm going to scroll back up to and suss. Thanks for the help.
