### ISSUE TITLE
Frames deleted/ NO ICON

### ISSUE THREAD

**Issue by Rageman0329** [opentoonz/opentoonz#5424]
### Ask a question related to OpenToonz

So I have been working on my assignment for a week. My brush was lagging so I close off the program (I did save every frame of it) but then it started crashing like it was not responding once I exit it out. Once I open the program, 95% of my frames are gone. Like "No Icon" from the level thing on the right. I tried exit out (and I saved it after) but my frames are still gone. How the hell am I gonna get them back. I got a final due. I DON'T WANT TO RESTART ALL OVER AGAIN!!!!!!!

**Comment by DarrenTAnims** [comment]
"I did save every frame of it" - How did you save? Which command?

**Comment by Rageman0329** [comment]
> "I did save every frame of it" - How did you save? Which command?

I save it all. Just tell me how to get my frames back!!!!

**Comment by DarrenTAnims** [comment]
No need to be angry. I'm trying to help.
It depends how you saved, which is why I asked.
If you used Save Scene, you won't have saved your drawings, so you can't get them back.
If you used Save All, you should have a backup file. This is stored in the same place as your drawings (In the Drawings or Extras folder in your project).
To use your backup files:

- Take a copy of the project folder, so you can revert back to the original.
- Then rename the broken backup drawing file, to remove the bak extension. E.g. From A.tlv.bak to A.tlv (Drawings are stored in the Drawing or Extras folders in your project)
- Now loading your scene will load the drawings from your backup files.
- Hopefully, you've got some of your drawings back, provided that you hadn't saved over the good backups with a broken scene.

Once this is working, it's a good habit to take a copy of the whole project folder from time to time, so you can revert back to it if something goes wrong.
Good luck

**Comment by Rageman0329** [comment]
I don't think you're getting it. When I open Opentoonz, the Level shows "NO ICON".  At first, I tried to exit it out after saving all scene. It didn't work. I can't even draw on those No Icons. I WANT THOSE DRAWING IMAGES BACK. I WASTED ALL MY MONEY JUST TO GET THEM BACK FOR A STUPID PROJECT!!!!!!!

**Comment by Rageman0329** [comment]
> No need to be angry. I'm trying to help. It depends how you saved, which is why I asked. If you used Save Scene, you won't have saved your drawings, so you can't get them back. If you used Save All, you should have a backup file. This is stored in the same place as your drawings (In the Drawings or Extras folder in your project). To use your backup files:
> 
> * Take a copy of the project folder, so you can revert back to the original.
> * Then rename the broken backup drawing file, to remove the bak extension. E.g. From A.tlv.bak to A.tlv (Drawings are stored in the Drawing or Extras folders in your project)
> * Now loading your scene will load the drawings from your backup files.
> * Hopefully, you've got some of your drawings back, provided that you hadn't saved over the good backups with a broken scene.
> 
> Once this is working, it's a good habit to take a copy of the whole project folder from time to time, so you can revert back to it if something goes wrong. Good luck


I don't think you're getting it. When I open Opentoonz, the Level shows "NO ICON". At first, I tried to exit it out after saving all scene. It didn't work. I can't even draw on those No Icons. I WANT THOSE DRAWING IMAGES BACK. I WASTED ALL MY MONEY JUST TO GET THEM BACK FOR A STUPID PROJECT!!!!!!!

**Comment by RodneyBaker** [comment]
I don't think you're getting it.   @DarrenTAnims is trying to help you recover your files... assuming they are there to be recovered.
Restoring the backup files is the most likely way to get those files back.

Please share the project (the entire stuff directory if necessary) as that will help fully assess the problem and recover the files if they can be reeovered.  As the file size might be large you will probably have to upload the file elsewhere and provide a link.

**Comment by gab3d** [comment]
> I don't think you're getting it. When I open Opentoonz, the Level shows "NO ICON". At first, I tried to exit it out after saving all scene. It didn't work. I can't even draw on those No Icons. I WANT THOSE DRAWING IMAGES BACK. I WASTED ALL MY MONEY JUST TO GET THEM BACK FOR A STUPID PROJECT!!!!!!!

@Rageman0329  I won't be as polite as those two great guys have been.
Your greatest problem is not the software, but your attitude.

- First, OpenToonz is free software that you can use to do your own projects for free.
- Second, this software is made by a community, nobody here owes you anything but respect, the very same respect you owe the rest of the community.
- Third, if you want help, you should consider being kind to the ones that could give you what you so desperately need, just out of pure selfishness, if you want. 
- Four, by the kind of terms you used in your posts, you seem not to be proficient in the use of OpenToonz, so most probably your pain is being an auto-inflicted one, more than caused by a software bug.

So... I would advice you to behave in a more humble way if you want anyone in this community (or any other) to care a dime about your own problems.

Lastly, if your problems are not being caused by a software bug, this bug-tracking platform seem not to be the right place to write about it. You should go to a user forum instead.
Good luck!

**Comment by Rageman0329** [comment]
> > I don't think you're getting it. When I open Opentoonz, the Level shows "NO ICON". At first, I tried to exit it out after saving all scene. It didn't work. I can't even draw on those No Icons. I WANT THOSE DRAWING IMAGES BACK. I WASTED ALL MY MONEY JUST TO GET THEM BACK FOR A STUPID PROJECT!!!!!!!
> 
> @Rageman0329 I won't be as polite as those two great guys have been. Your greatest problem is not the software, but your attitude.
> 
> * First, OpenToonz is free software that you can use to do your own projects for free.
> * Second, this software is made by a community, nobody here owes you anything but respect, the very same respect you owe the rest of the community.
> * Third, if you want help, you should consider being kind to the ones that could give you what you so desperately need, just out of pure selfishness, if you want.
> * Four, by the kind of terms you used in your posts, you seem not to be proficient in the use of OpenToonz, so most probably your pain is being an auto-inflicted one, more than caused by a software bug.
> 
> So... I would advice you to behave in a more humble way if you want anyone in this community (or any other) to care a dime about your own problems.
> 
> Lastly, if your problems are not being caused by a software bug, this bug-tracking platform seem not to be the right place to write about it. You should go to a user forum instead. Good luck!

Alright a-hole.
1. I spend money on some guys backup tool and an extension upgrade for a .bak file
2. All I ask is some damn simple advice and none of them worked. 
3. I spend 3 hours working on a college assignment and I lost over 100 frames of it. I have every right to be this mad.
4. If you think changing my attitude is magically gonna bring my frame back, then get real.
If you're not gonna help, then don't bother if you wanna get pissy with me.

**Comment by gab3d** [comment]
@Rageman0329 
Changing your attitude would denote that you are a better person, or at least fool others to think so and help you. But no.

**Comment by Rageman0329** [comment]
> @Rageman0329 Changing your attitude would denote that you are a better person, or at least fool others to think so and help you. But no.

Yeah. Because being frustrated on an assignment with a deadline automatically makes me a bad person. You never work on a project that took you sweat and tears only for it to get the Toy Story 2 production treatment.

**Comment by gab3d** [comment]
I've worked and managed several projects involving many people.
One thing I've learned from that experience is that people that lose their temper on "high pressure" excuses are not the kind of people you want on your team, no matter the amount of pressure of the task at hand.
So, go... do your homework, develop your skills and also develop your character to a better one if you want to be successful in the industry (any industry).

**Comment by Rageman0329** [comment]
> I've worked and managed several projects involving many people. One thing I've learned from that experience is that people that lose their temper on "high pressure" excuses are not the kind of people you want on your team, no matter the amount of pressure of the task at hand. So, go... do your homework, develop your skills and also develop your character to a better one if you want to be successful in the industry (any industry).

Whatever.

**Comment by RodneyBaker** [comment]
@Rageman0329 While it is possible to troubleshoot your issue here... github isn't the best place for that.
Bug reports, software development... efforts like that work best here.

While there are no guarantees, there is a good chance you can recover your files.
Understanding how Opentoonz stores files... and backups.. can help in that process (as suggested in posts above).
The delayed communication here in github however isn't likely to help determine if the files can in fact be recovered much less get to that determination in a timely manner.

What you could do, if you are able and willing, is join the Opentoonz discord... or one of the alternative discords/venues where most of the same people that would respond here tend to assist there as well.  The difference being that the troubleshooting can occur in real time (via chat) and there are other options as well for those so inclined.

One thing you have to do of course is determine if taking the time to troubleshoot with the chance that you might not recover the files isn't worth the effort and that it might be quicker to recreate the project... or at least those parts that appear to be lost.

If are interested in the chat/discord route then here is an invite:  https://discord.gg/EW7egv6QZs
