### ISSUE TITLE
Regression Bug : Double clicking on a style thumbnail in the level palette window should open the style editor to change the color

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#543]
Basically if you double click on a style now - a window pops up to change that style's name:
![stylename](https://cloud.githubusercontent.com/assets/6495061/16438333/c212a366-3da6-11e6-9c03-2700ccb671de.PNG)
Right now the level palette window does not even show the names of the different styles by default. Yet the default double click action is to change their names.

It would be much more useful if double clicking brought the style editing window.
That way I dont have to keep the style editing window open all the time. Instead I can get it to pop out whenever a color needs to be changed.

The style editing window is big and it takes a lot of screen estate.
It doesnt need to be visible all the time. I like to keep my layout in a way that gives more space for the drawing area.

@shun-iwasawa it makes much more sense than what we have now as the default double click command.

How about this for a design proposal:
![doubleclickproposal](https://cloud.githubusercontent.com/assets/6495061/16438459/d78d6fd6-3da7-11e6-9306-c7b94fc336f9.PNG)

- Double clicking on the style thumbnail (1) brings up the Style editor window (right now we have to right click > style editor) - thus double clicking on a color lets you change said color.
- Double clicking on the Style name (2) (when visible) brings up the rename style window - thus double clicking on a name lets you change said name.

That would be much more intuitive and at the same time useful than the way it is currently. Easier to change a color without having the style editor visible all the time that way.
Since this is a usability feature, perhaps @turtletooth might be interested? :)

**Comment by turtletooth** [comment]
It seems like it could definitely be useful, but right now I'm up to my ears in h264.  ffmpeg is hard stuff.

**Comment by blurymind** [comment]
@shun-iwasawa This is actually a regression bug from Toonz Harlequin.

I just checked - in Harlequin the behavior is the same as the design that I am proposing! :)
Clicking on a color thumbnail makes the style editor pop up to change the color. Clicking on a name of a color (when visible in list view mode) - lets you change the name of the color - without any extra pop ups.
![paletteregression](https://cloud.githubusercontent.com/assets/6495061/16438889/1b54bc62-3dab-11e6-9452-9c58a65bded0.PNG)

Why it is the way it is right now is beyond me. Seems like another broken feature.

**Comment by blurymind** [comment]
@turtletooth It might be possible to get some help from other devs that use ffmpeg if you get stuck. I think a lot of non linear video editors use it for export.

**Comment by blurymind** [comment]
My biggest problem is that double clicking on a style thumbnail also brings
up a pop up to rename the style. That is totally unnecessary - especially
when the name is not visible. It should bring up the style editor instead.

**Comment by inkapnea** [comment]
Sorry, my comment was slightly unclear. We both agree that bringing the Style Editor by double clicking on the thumbnail would a great addition.
I just wished to point out that the inline renaming is already there as in Harlequin, so the code for this part is in place (and so we could completely get rid of the renaming popup window because it seems that it doesn't bring any UI benefits in its current form).

**Comment by blurymind** [comment]
That is a good point actually. The current rename pop up is completely redundant. It makes no sense

**Comment by blurymind** [comment]
Also on the normal (non pop-up) rename functionality - I agree it should preserve it's left aligned position too.

**Comment by yamisama** [comment]
I imagine that at Ghibli they set their palettes once per production and having the style editor pop up made it too easy to make accidental changes. Just a theory. However, since there is a dedicated button that locks a palette, plus the option to leave "Auto Apply" turned off, the additional safeguard is probably not needed.

I think we could preserve the renaming feature by adding a rename option to the style editor. Right now there is a text label at the bottom that shows the style name. If clicking that could bring up the rename dialog that is currently shown when the color swatch is double clicked, I'd say that would be an adequate replacement. Or the information could be moved from these labels into the Style Editor window's title bar as text (i.e. something like "Style Editor – Palette A Style #2: color_2") and an "Edit Name" button added instead.

**Comment by blurymind** [comment]
I think when the name is not visible (thumbnail mode) - the user would not need to change it. They wont see it to begin with. 

Double clicking on the style thumbnail should not bring a dialogue to change the name you dont see- 99% of the time users would rightly so expect to get the style editor instead - to change the style. That is how all other graphics software works. There is an established design language that works and is removed  here. 

When switching to 'List view' in the palette editor - if you double click on the name - you can change it - that is intuitive. You double click on the thing you want changed.

You you want to stay in thumbnail mode, but still be able to rename a style - then we can go two ways:

As @yamisama  suggests- add the option to rename the style  to the right click menu, BUT make it so that when double clicked on the thumbnail - the style editor comes up - not the style rename tool.

or

Add ability to rename the active style to the style editor - by double clicking on the name that is displayed:
![renamestyle](https://cloud.githubusercontent.com/assets/6495061/16471158/d7285406-3e52-11e6-8903-922d7cf5a5ee.PNG)

**Comment by shun-iwasawa** [comment]
As @yamisama guessed, this change was done reflecting demands from the studio, in which the workflow of color designing and ink&painting were separated. They would like to prevent opening Style Editor during ink&painting work by mistake. I think it would be better to turn back this behavior for now.
I'm focusing on developing another feature this week, so I'll work on this issue next week. Thanks.

**Comment by inkapnea** [comment]
@yamisama
I'm against moving /adding information to the Style Editor window title bar. It could add too much confusion. The other proposal is better (editing the label in place at the bottom of the Style Editor) because it's good to keep the color info **close to** the color preview as it is now.

...but, I'm still wondering if it's necessary to have the possibility of renaming colors in the Style Editor.

At a second closer look the current rename pop up window has one little advantage over the inline renaming mode... hence its 3 buttons (Ok, Apply, Cancel). Once it pops up, you rename a color swatch and press Apply, it remains open, so you can select another swatch in the Level Palette, rename it, press Apply, select the third swatch and so on... Pretty useful when you want to fast rename and bring some order to many swatches.
In my opinion, if that pop up window gets completely removed (as it was previously suggested) it will not be so much missed because there are other ways to rename fast (double clicking on the color name). Just wanted to point out that in its current form that pop up window makes sense only when called from the Level Palette and it would not be completely appropriate to link it from some other place (from the Style Editor, for example).

**Comment by blurymind** [comment]
@shun-iwasawa thank you for tackling this. As I said - my main request really is to make the double click action on a style thumbnail bring up the style editor (as it is in  toonz harlequin). 

In my personal view we can remove the rename pop up window functionality completely- because opentoonz already has a way to rename palettes by double clicking on their names.

**Comment by konero** [comment]
To me, names are important even if we use large or small tiles, to differentiate between any nuance.

Users can hover the tile to see the name.

But there seems to be no right-click menu item that allows renaming, so removing the double-click rename option means there would be no way to rename the tile without changing the layout to list view.

I think the rename popup should remain but add a right-click menu item to call on it.
