### ISSUE TITLE
Wrong Sub-xsheet FX calc order?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#5467]
### Description

Recently a user has reported in the Spanish Google Forum that he's having a weird behavior when applying series of fx in a sub-xsheet, and then inverting the subxsheet level in the main Xsheet.
I've made a scene replicating his problem and can confirm it is indeed happening (and not expected).

### Steps to Reproduce

1. Make a couple of vector levels.
2. Collapse them into a sub-xsheet.
3. Enter the sub-xsheet.
4. Apply a **Body Highlight** fx to them.
5. Exit the sub-xsheet back to the main Xsheet.
6. Select the Animate Tool and flip the subxsheet level horizontally.
7. FX keeps unaltered (i.e. not inverted), while the subxsheet level does.

### Expected Behavior

The FX applied inside the Sub-xsheet levels should invert, together with the level.

### Screenshots, Video & Crash Logs

[fx_calc_order.zip](https://github.com/opentoonz/opentoonz/files/15422123/fx_calc_order.zip)

test scene.

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by gab3d** [comment]
I've also tested storing FX caches for the sub-xsheet levels, without altering the behavior.

**Comment by RodneyBaker** [comment]
Thanks @gab3d
I haven't looked into this yet but by your description it sounds like this is expected behavior.
We generally don't want lighting to reverse on objects based on whether or not they change orientation.
Rather we would want to alter the FX settings to change the lighting.
To have the FX of Body Highlight invert when an image/level, column or subxsheet is flipped would  (I think) be cause for a report outlining that it should not do this.
If in Step 7 you mean to say that the Body Highlight does flip when the subxsheet flips then yes, I see that as problematic.

Will look into this but that's my initial though as someone that uses Body Highlight FX quite often.

**Comment by beeheemooth** [comment]
@gab3d I think this is normal effect behavior. Please note that in the Function Editor, effects have their own animation channel, which does not depend on the parameters that the Animate Tool changes. You can probably get what you want using Expressions, but I haven't tried it.

**Comment by gab3d** [comment]
Yes, you are right...
I didn't repair that much in that the effect used in the example was one that had to do with lighting.

In fact, now I've tested other effects and the do invert, in the main Xsheet.
So, I close this issue.
Thank you both!
