### ISSUE TITLE
Crash Opentooz application

### ISSUE THREAD

**Issue by ShreyAOpen** [opentoonz/opentoonz#5478]
### Description

Opentooz app is not working

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

[Crash-20240530-181150.dmp](https://github.com/opentoonz/opentoonz/files/15500151/Crash-20240530-181150.dmp)
[Crash-20240530-181150.log](https://github.com/opentoonz/opentoonz/files/15500152/Crash-20240530-181150.log)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
There isn't enough information to diagnose the problem here BUT...

It is likely that you are experiencing one of two very commonly encountered issues.
Both can be addressed by renaming or removing files.

The first relates to an outdated Logitech webcam driver issue.  REF:  #5477

The second is a different driver issue related to .MOV support seen in current nightly releases.  REF: #5449
