### ISSUE TITLE
OpenToonz crashed!

### ISSUE THREAD

**Issue by davidkk2024** [opentoonz/opentoonz#5525]
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-07-11 16:50:00
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) HD Graphics 520
GPU Version: 4.6.0 - Build 31.0.101.2111

Crash File: C:\Users\Kwame\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240711-165000.log
Mini Dump File: C:\Users\Kwame\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240711-165000.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

**Comment by RodneyBaker** [comment]
Will close this report as lacking any actionable information that can be used to troubleshoot the issue.
@davidkk2024 It seems likely you are encountering a known problem but what that is is hard to say.

You may want to start with reviewing open and closed crash reports.
Here's one that is likely to be encountered when installing the latest nightly release:  #5351 
It is recommaned that you install the latest nightly so that along with the fix mentioned in that report might just resolve your problem.

Other than that I will suggest joining one of the Opentoonz venues such as Opentoonz discord where others can assist with troubleshooting problems.
