### ISSUE TITLE
usability bug: Default Keyboard shortcuts missing - load keymap files?

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#56]
I have noticed that there are no default keyboard shortcuts with the installation (windows). The user can assign keys, but no keys have been assigned by default. So in essence opentoonz does not yet have a default keymap!

It also does not seem to have a way of saving and loading keymap files - at least not exposed to the gui. We need that in place in order for the community to create such keymaps for everyone who is migrating from different traditional animation software.

Is that something that is hard to add? We need to decide on some sort of a default key map - so others can learn the software and take advantage of keyboard shortcuts without having to set each one up.

My biggest missing keys (I am coming from tvpaint and toonboom experience):
- A button modifier combination to rotate the light table (rotate while holding alt+spacebar for example, release keys to get back to your brush/other tool)
- 'Delete' key used on the drawing canvas does not do anything - so I can not delete control points of lines, I can not delete lines. In fact there is no way to manipulate control points with the control point editor tool. No way of merging them. The right click menu only lets you set it to be linear or non linear.
Is that a missing feature or there just isn't any key assigned to delete them? It might need to be split out as another issue if so.

**Comment by odysseywestra** [comment]
You could create a spread sheet on Google Drive with all the available shortcuts and open it up for comment to the community. I've done with MyPaint and its going smooth so far.

As far implementing it, it may require a bit of work.

**Comment by blurymind** [comment]
@odysseywestra  Good idea :)

Here is a link to an open spreadsheet document:
https://docs.google.com/spreadsheets/d/1-taUohoRrFXnaNUcey8fvu3LKaFmDToydxga-jqBJy0/edit?usp=sharing

I will start populating it, anyone can join in! :)

**Comment by BillDStrong** [comment]
Would it be better to have several keymap sets available to choose from, based on other popular programs?

**Comment by blurymind** [comment]
Kind of like blender does! Yes it will! :) 
But we need some sort of a menu to switch between them - and also to locate the file where they are saved.

**Comment by odysseywestra** [comment]
I think for now we could have alternative keymaps available for download via the Wiki. At least until it has the nessesay options to switch between keyboard shortcut maps. 

Dose openToonz saves the custom keyboard shortcut map as a config file?

**Comment by blurymind** [comment]
I have started making a custom keyboard layout ini file for the toonzStuff folder here:
https://github.com/opentoonz/opentoonz/issues/80

**Comment by odysseywestra** [comment]
@blurymind this one and #80 feel like duplicates. Could you make this one focus just on keyboard shortcuts and the other one focus on Rooms Layouts?

**Comment by blurymind** [comment]
Ok, I moved it to here.

On default shortcuts - I have started adding some!
This is the progress so far:
[shortcuts.zip](https://github.com/opentoonz/opentoonz/files/192392/shortcuts.zip)

- I merged harlequin's default keyboard layout into it. I also added a number of much needed ones!

- Added delete key to the delete command. This solves this bug:
https://github.com/opentoonz/opentoonz/issues/82

- Added a shortcut to go to next and previous drawings / frames - comfortable to reach - on your left hand side. So its easy to flip between frames while drawing with a tablet.

- Added shortcut  for panning and rotating and zooming the canvas, this solves this bug:
https://github.com/opentoonz/opentoonz/issues/83
They closely mimic the ones in toonboom/tvpaint and are much more comfortable since they are close to your left hand side.

`[shortcuts]
MI_NextDrawing=Shift+X
MI_PrevDrawing=Shift+Z
A_ToolOption_AutoSelect%3APegbar=
MI_NextFrame=Shift+S
MI_PrevFrame=Shift+A
T_Hand=Space
T_Rotate=Ctrl+Space
T_Zoom=Shift+Space
A_ToolOption_FrameRange=F6
A_ToolOption_SegmentInk=F8
A_ToolOption_Selective=F7
A_ToolOption_Type%3ARectangular=F5
MI_BringForward=[
MI_BringToFront=Ctrl+]
MI_Clear=Del
MI_Duplicate=D
MI_Group=Ctrl+G
MI_OpacityCheck=1
MI_SendBack=Ctrl+[
MI_SendBackward=]
T_ActualPixelSize=N
T_Brush=B
T_ControlPointEditor=C
T_Edit=E
T_Eraser=A
T_Fill=F
T_Geometric=G
T_Pinch=P
T_StylePicker=K
T_Tape=T
T_Type=Y
T_ZoomReset=0
T_Zoomin="="
T_Zoomout=-`

**Comment by m48** [comment]
Not sure if this warrants a separate issue or not, but it's pretty relevant to keybinding in general: 

I've noticed that bindings for tools in OpenToonz have some special qualities. Basically, tool bindings can work in two ways. The first way is the same as, say, Photoshop—briefly tapping the key will switch to that tool forever. The second way, however, is a bit different. If you hold down the key longer than a certain amount of time ([exactly half a second, apparently](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/tnztools/toolhandle.cpp#L83)), OpenToonz will *temporarily* switch to that tool, returning to the previous tool as soon as you release the key. 

Why is this important? It's the only reason binding keys to the hand, rotate, and zoom tools appears to create "modifier keys." So, for example, if you bind the hand tool to space, panning around the canvas will work nearly identically to Photoshop—but *only if the user keeps the key down long enough to make the switch a temporary one.* 

This feature could be convenient, but users may confuse this for a bug. If they pan around too quickly, it will end up permanently switching to the hand tool, which is not what they want.

This problem in particular could be fixed by altering the `restoreTool()` function to always restore the tool if the active tool is the hand, rotate, or zoom tool. In general, though, it's probably just a good idea to remember this functionality exists.

I apologize if this is obvious, but it may be useful to know.

**Comment by blurymind** [comment]
I quite like the design and did not think it was a bug. My biggest issue was some of the missing keybindings (like delete key not working) seemed like a bug. Thus why i propose this new ini file to be included

**Comment by blurymind** [comment]
@shun-iwasawa thank you kindly! :)

**Comment by blurymind** [comment]
I am closing this issue now. I might update the keyboard shortcuts in the future - after more extensive use !
