### ISSUE TITLE
New feature: Pencil Test

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#562]
**What is Pencil Test?**
[Wikipedia - Traditional Animation](https://en.wikipedia.org/wiki/Traditional_animation#Pencil_test)

> While working on a scene, a key animator will usually prepare a **pencil test** of the scene. A **pencil test** is a preliminary version of the final animated scene; the pencil drawings are quickly photographed or scanned and synced with the necessary soundtracks. This allows the animation to be reviewed and improved upon before passing the work on to his assistant animators, who will go add details and some of the missing frames in the scene.

In paper-based animation workflow, the pencil testing is essential for animators during their work. In Japanese animation industry, they had used NAC's Quick Action Recorder (a.k.a QAR) machine released in 1980's, then transitioned to the software Quick Checker by Celsys (maybe released in 1999).

The pencil testing feature is quite simple - capturing animation drawings via camera and place them into xsheet as raster level (after some image adjustment). This feature will also be useful for creating clay animation with OpenToonz.

**Comment by shun-iwasawa** [comment]
The feature prototype is almost done - like this:
<img src="https://cloud.githubusercontent.com/assets/17974955/16516901/a60a09a0-3fb5-11e6-906b-1d969691b0e9.png" width=600>

**Comment by psychoanima** [comment]
Awesine feature! It will support only web cameras or dslr's as well? (like DragonFrame)

**Comment by blurymind** [comment]
Could also be useful to stop motion animators.

**Comment by turtletooth** [comment]
This is awesome!  I do stop motion with my students using DragonFrame but they always ask if there is a free software they can use at home.  Depending on how this works, I might use it instead of DragonFrame to keep all their 2D animation in one program.

**Comment by turtletooth** [comment]
@psychoanima If this is only webcam for now, we could probably eventually add DSLR support in using libgphoto2.

**Comment by Rayek** [comment]
This is awesome news! I had been investigating options to hook up a web camera, but so far I've found only indirect ways to do this. Really looking forward to this. I am hoping DSLR cameras will be supported as well at some point in the future.

**Comment by turtletooth** [comment]
Merged

**Comment by RodneyBaker** [comment]
Want you to know other folks are paying attention and testing these features/fixes as they are published.  I've successfully ran the new Pencil Test feature and... Looking good!

I did have to floow shun-Iwasawa's recommendation to use a program such as ManyCam as my webcam was not immediately recognize.  Once I installed and ran ManyCam I got an error saying that another program was using the Camera (and I didn't have an option to select the ManyCam virtual camera in OpenToonz.  Closing both ManyCam and OpenToonz and starting OpenToonz again gave me that drop down menu option and then I found it working.  

I did run into the problem (mentioned elsewhere) about a crash upon changing resolution sizes but that happened once and now I'm using a hi rez.  

I did have some intial difficulty with the image being backward (not upside down which the OT Pencil Test menu allows for) but I could change that orientation in the ManyCam menu.  I must assume that somehow I had changed the orientation earlier.

At any rate... looking very good!  Thanks dev team and thank you Shun-iwasawa!


I didn't post this to the main forum because I wasn't sure about how you might want to announce new features for OpenToonz, especially when they are in the initial stages of implementation.

**Comment by Rayek** [comment]
Just wanted to let you know how much I appreciate this new webcam option!

I tested this with a Logitech Webcam Pro 9000, and that camera works "out of the box" - no extra drivers required. And a pretty nice resolution to work with as well!

![untitled](https://cloud.githubusercontent.com/assets/10274969/16717040/42db285a-46c2-11e6-83dd-ae54cfc924fb.jpg)

The Playstation Eye camera with the Windows driver does not work, unfortunately.
https://codelaboratories.com/products/eye/driver/

I will try more cameras at work this week, and report back here.

**Comment by charliemartinez** [comment]
Hello, first of all thank you very much for this function. Is there an appimage or .deb? I use Linux but Morevna does not recognize any webcam. I'm very interested in relacing Dragonframe. Thank you very much from Buenos Aires, Argentina.
