### ISSUE TITLE
Logitech webcam related crash

### ISSUE THREAD

**Issue by rurumuk** [opentoonz/opentoonz#5660]
.

**Comment by RodneyBaker** [comment]
The good news is that you have a 'known issue' that is easily resolved.

C:\Windows\SYSTEM32\lvcod64.dll

That file listed in your crash report is a logitech webcam driver/library that is problematic with various software.
Removing or renaming the file should resolve the problem.

We have been looking at various potential fixes to this problem and the most likely at present to to blacklist 'lvcod64.dll' so that Opentoonz ignores the file if/when found.  That is not an optimal solution so hasn't been incorporated at this time.

For additional information please see:  #5551(and other similar reports).
