### ISSUE TITLE
Bug: Menu items disabled on OS X

### ISSUE THREAD

**Issue by yamisama** [opentoonz/opentoonz#618]
The Quit menu item is often grayed out on OS X (10.9.5), either right after launch, or after performing a few actions in the UI. When the main viewer has focus, pressing Cmd+Q still invokes the Quit command. Tested with a customized room set based on the Ghibli preset, stylesheet set to "gray_128_mac".

Sometimes after a longer time of working in the software, not just the "Quit" command, but pretty much all menu items become grayed out.

This issue has existed for many builds, including recent nightlies and regularly occurs.

Also, the Undo and Redo commands are only labelled "Undo" and "Redo" and do not show the name of the corresponding action like they do in other applications, eg. "Undo Brush Tool" etc.. The History panel shows labelled commands. Not sure if this is a menu handling bug or by design.

**Comment by artisteacher** [comment]
The quit menu icon is always grayed out. I've also had several students where all the menu items are greyed out when they are ready to save. This is with OpenToonz 1.1.1 on the OS X El Capitan.

**Comment by artisteacher** [comment]
This is still happening as of 1.1.2 - but only when using wacom tablets.

**Comment by artisteacher** [comment]
So I've found that quit in the menu is disabled - unless the selection tool is active. However in that case, neither the quit menu nor the quit shortcut actually work. OpenToonz does not close. If the scene was saved before trying to quit with one of those methods (with the selection tool active) an asterisk appears next to the scene name as if there was a change made. When the selection tool is not active, the quit shortcut works but quit in the menu is greyed out.

**Comment by artisteacher** [comment]
The entire menu still becomes greyed out and inaccessible when using a wacom tablet on a mac.  I'm thinking the issue may have to do with incomplete/interrupted signals from the pen. I definitely press against the buttons unintentionally fairly regularly. Disabling both buttons in the tablet's settings (in system preferences) seems to be making a big difference so far. No more disabled menu! It is mildly annoying to have to switch to the mouse or touchpad to right-click but at least the menu is staying accessible.

I wonder if this could be related to #860. 

This has no impact on quit being constantly greyed out and broken, since it never works, even without a tablet.

**Comment by artisteacher** [comment]
With the tablet fix in the recent nightly build, the menus seem to have stopped becoming inaccessible. However quit in the menu still is broken.

**Comment by artisteacher** [comment]
In the Morevna release, the menu button is disabled as well.

**Comment by artisteacher** [comment]
In 1.2, the greyed out menu was very common again with tablet use. This looks to be resolved in the latest nightly build 🎉 - now it’s just the quit menu item that’s still a problem.

**Comment by artisteacher** [comment]
So not completely fixed, but it is back to being irregular.

**Comment by artisteacher** [comment]
I think this is finally fixed in the nightly builds!

**Comment by shun-iwasawa** [comment]
OK Thank you @artisteacher for the fix!
