### ISSUE TITLE
[feature] option to use png, webp or even jpg instead of tif - for raster levels - for smaller projects 

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#622]
Ordinary raster levels in opentoonz are useful for rough sketching - because they are the only ones that allow pressure sensitivity to affect the opacity of a brush stroke.
As such - I dont consider them to be an option for export as much as any of the other levels. They are not a level type I would use as a final render.

In terms of size on the hard drive however - they are ironically the ones that take the most space! They are also consuming more memory than other levels if i understand correctly. Each individual frame is between 2 and 6 mb. When you have hundreds of these frames - it really adds up!

So that got me thinking - wouldnt it be useful to have the option when you create an ordinary raster level - to select file type for them?
Something that is better compressed - takes the least amount of space possible for each frame.

So what do you say - do you think it will be possible to optimize this level type somehow? 
Why does it have to be tif to begin with?

Ideally it should be webp:
https://developers.google.com/speed/webp/

> WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster.
> 
> WebP lossless images are 26% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller than comparable JPEG images at equivalent SSIM quality index.
> 
> Lossless WebP supports transparency (also known as alpha channel) at a cost of just 22% additional bytes. For cases when lossy RGB compression is acceptable, lossy WebP also supports transparency, typically providing 3× smaller file sizes compared to PNG.

**Comment by blurymind** [comment]
If opentoonz can already  read image sequences in other better compressed image formats - why does creating a raster level in it use tif? There are other losless formats that are much much much smaller:
http://flif.info/

**Comment by blurymind** [comment]
Think about the cases where you backup your project on dropbox - where you have a maximum backup space.
If you try to backup an opentoonz project - keeping the raster level sketch pass adds hundreds of MB and even several GB some times to your projects. You have to backup only the vector levels or delete your sketch history if its on an ordinary raster level.

**Comment by yamisama** [comment]
> They are also consuming more memory than other levels if i understand correctly.

Raster images (both ToonzRaster and regular Raster) always have to be decompressed when loading them into the application. 8-bit RGBA images (or RGBM, as Toonz calls them) require 8 Bit (Red) + 8 Bit (Green) + 8 Bit (Blue) + 8 Bit (M/Alpha) = 32 Bit per pixel, ToonzRaster images require 8 Bit (ink coverage) + 12 Bit (palette index of ink) + 12 Bit (palette index of fill) = 32 Bit per pixel, so exactly the same.

A different compression scheme/file format would primarily affect storage on disk, but that's what you are primarily after anyway.

**Comment by blurymind** [comment]
how does tvpaint keep their files so small - even with so many raster frames?

**Comment by blurymind** [comment]
I guess the feature request here really is to investigate if there is a way to make rough pass raster levels take less hard disk space.

**Comment by yamisama** [comment]
Apparently OpenToonz already uses LZW compression for TIF levels according to the "Level Info" window. So it seems that it's really a matter of how efficient the compression is.

However, a very simple sketch in 1920x1080 RGBA I just did as a test (as far as the viewport drawing and brush tool bugs permitted) had about 300 KB for me – when you create a single frame raster level and go to "Level Info", does it say "Lempel-Ziv-Welch" or is it something else (like "RLE" or "run-length encoding" or even "uncompressed")? LZW should provide at least reasonable compression, 6 MB certainly seems quite large.

On a side note, it claims the TIFF file byte order is "Mac" on my system, which, considering that all recent Macs use Intel processors, is a bit of a strange choice since it requires unnecessary byte swapping whenever the file is read from or written to.

**Comment by blurymind** [comment]
We could use lossless webp instead of png as a replacement for the tif? 

https://www.andrewmunsell.com/blog/png-vs-webp/

> Book cover – Baseline PNG (30.2 KB)
> Book cover – Lossless WebP (8.9 KB)

in example case - webp is 1/3 of the size of the png. that is 150% smaller!
So it is quite quite a difference - considering it being lossless and still having transparency! :o

**Comment by turtletooth** [comment]
My opinion after trying webp last night as the intermediate format for
ffmpeg is that it is probably too slow for most people's patience. The file
sizes and the quality are great but it comes at the cost of speed.  Saving
raster levels is already slow if there are many drawings.

I think having options for the saved format could be a good option since
the file sizes are pretty big- and I use raster levels a decent amount
because I like the transparency option.

**Comment by blurymind** [comment]
I dont mind if saving the project takes a little longer myself - because i constantly hit the save button and I assume it only saves frames that have changes on them. Or does it always save all the frames?

For as long as the playback is good - i am ok with it. Having the option to use something smaller but in less quality and even no alpha channel would be nice - especially if you use raster levels for sketching the animation and vector ones for the final render pass. You end up with a much smaller project folder.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
A PR rekated ti this request has been submitted.  REF:  #4241
