### ISSUE TITLE
opentoonz v1.0.3  not compatible for windows 10

### ISSUE THREAD

**Issue by daynala** [opentoonz/opentoonz#627]
Well I installed opentoonz and all fine but when I try to start it up it says isnt compatible and when I try to look how to fix it everyone says about a file called lvcod64.dll the proble is that I look for it and it doesn't exist, so what am I supposed to do? How can I fix this?

**Comment by RodneyBaker** [comment]
Hi Daynala,

OpenToonz v1.0.3 is definitely compatible with Windows 10.  Now we just
need to discover why it isn't working for you.

The first thing I would look to would be to make sure you've uninstalled
any previous installation of OpenToonz.
Then I would double check to make sure I'm installing v1.0.3 (as an older
installation file can look the same too).

The fix that required removing the .dll file should have been fixed back
with the v1.0.2 release so you shouldn't need to do any of that with v1.0.3.

We may need to know more about your system and setup but my gut feel is
that the issue is with the initial installation which points me to those
two things above which are:

Make sure you don't have older installations causing problems
Doube/triple check to make sure you are installing the right version (I
emphasize this point because I have every installer of OpenToonz in my
download folder and it can be difficult to know which is which).

Keep us posted on your progress!

**Comment by nittolo** [comment]
Take a look at #46

**Comment by digimikeh** [comment]
Does not work with 32 bit..  switch to 64bits if you have.
