### ISSUE TITLE
Build on Ubuntu 16.04

### ISSUE THREAD

**Issue by rauldipeas** [opentoonz/opentoonz#634]
To build OpenToonz on Ubuntu, is necessary to install "qtmultimedia5-dev", please, include this on how to.

**Comment by Itzcuauhtli** [comment]
Thank you man. For a moment I was frightened :)

**Comment by rauldipeas** [comment]
Can I provide a link for .deb that I am making?

**Comment by Itzcuauhtli** [comment]
Yeah, of course. I'd appreciate it very much. Actually I have a problem in the "make" step and It would be nice to try another solution while see how I solve this conflict (if I think in that thing xD)

**Comment by rauldipeas** [comment]
I made a solution for my own distro, but it should work on Ubuntu too...
(only portuguese, sorry)

http://avix.userecho.com/topics/37-instalacao-do-opentoonz-no-avix/

Here is my script to build OpenToonz(tested only on my own distro)...

http://avix.esy.es/private/opentoonz-build.sh

**Comment by ideasman42** [comment]
Resolved a107c1293f5971fb69565e39318ff63093397734

**Comment by inkapnea** [comment]
I tried to build Opentoonz on a fresh Debian Stable and got the error:
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake
```
Had to install the qttools5-dev package before proceeding with the compilation.
In the Linux guide there is mentioned only the qttools5-dev-tools package, but there is not any dependency relation between the two, not in Debian Stable or Ubuntu Xenial (which is why i'm reporting it here and not opening another report). Didn't try on Ubuntu but I suppose it's the same.
Please take a look here:
https://packages.debian.org/jessie/qttools5-dev-tools
http://packages.ubuntu.com/xenial/qttools5-dev-tools
So, if somebody is using a system on which this package was not already installed before, he will get the same "Qt5LinguistTools" error.
Please add the package qttools5-dev to the guide under the Debian/Ubuntu part.

**Comment by janisozaur** [comment]
you can check with https://github.com/opentoonz/opentoonz/blob/master/ci-scripts/linux/travis-install.sh, though it uses some PPA, as the Ubuntu version on Travis does not have fresh enough Qt.

**Comment by Patola** [comment]
There's also an issue where libjbig is not referenced. For me it only compiled when I added -ljbig to all linker invocations.

**Comment by janisozaur** [comment]
that's because you have `jbig` installed in your system and `libtiff` automatically picks it up. You can compile `libtiff` with `--disable-jbig`, as is done on Travis, or it can be fixed like lzma was in https://github.com/opentoonz/opentoonz/pull/563/commits/6dc4b9887163020902f44373dc66cf11ac7ac972
