### ISSUE TITLE
Combo Viewer GUI Changes Not Persistent in Ghibli Edition Rooms

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#647]
I use the **Studio Ghibli** workspace.

I added a new room titled Default with a **Combo Viewer** docked, but when trying to hide any GUI under Show/Hide GUI it only maintains the change for that session, if I restart OpenToonz the GUI is shown again.

There is no problem with the original rooms - Cleanup/PltEdit/InknPaint/Xsheet/Batches/Browser.

**Version**: [Nightly 2016-07-14 14:22:18 UTC](https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_4e9ecfd38bf6b19ffd391a24b4fcc12d5d84530f)

**Comment by shun-iwasawa** [comment]
This is a missing feature of OpenToonz.
In Toonz Ghibli Edition - the ancestor of OpenToonz- there was no feature to add/delete/rename rooms. All rooms are previously defined so that the show/hide state of Combo Viewer were needed to be saved only for specific rooms. And this specification is not modified yet.
In particular, for now OpenToonz can save and reproduce the state of the combo viewers only in the rooms named "InknPaint", "Cleanup", "PltEdit", "Schematic" and "QAR".
Thank you for point this problem!

**Comment by RodneyBaker** [comment]
This is a very old issue that apparently only applies to the Toonz Ghibli room setup.
It's not clear if subsequent changes/updates to Rooms fixed this problem.
Anyone with a desire to investigate the Ghibli Room setup this is your opportunity to shine! :)
