### ISSUE TITLE
Export animate GIF do not support transparency and trim

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#729]
First thank you very much @turtletooth

I think if animate GIF support **transparency** and **trim** (like Krita and Photoshop) animation export, it will be better.

**Comment by RodneyBaker** [comment]
Current GIF export via ffmpeg does support transparency although not specifically cropping/trim.  A workaround for that is to adjust the camera (a new camera if necessary to crop/trim the image.

Does the Alpha Channel option not appear when you select Options next to the GIF format listing when you select it?

**Comment by turtletooth** [comment]
I have not been able to find the right ffmpeg commands to keep transparency when converting from png to gif.  I can get them in there if someone finds commands that work right.

**Comment by RodneyBaker** [comment]
In seeing an example over at ffmpeg.org, the approach to transferring transparency might be of the order:

ffmpeg -loop 1 -s 4cif -i label1-0.png -r 25 -vframes 250 -vcodec png -pix_fmt
bgra test.gif

Disclaimer:  I have very little idea what all of that is doing especially where it gets to the part about '-pix fmt bgra' which is what it seems you might be looking for.  Further I'm not sure if after -vcodec that shouldn't be 'gif' instead of 'png'.

**Comment by 2dvision** [comment]
I find **reserve transparent** [palettegen](https://www.ffmpeg.org/ffmpeg-filters.html#palettegen-1) in FFmpeg Filters Documentation. For read more look at [High quality GIF with FFmpeg](http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html). Is this help?

**Comment by turtletooth** [comment]
@RodneyBaker @2dvision I have tried every option I can think of and ffmpeg (including variations on things you posted) and can't get png to keep transparency when going to gif.

I can get imagemagick to work, however, so that is an option.  I don't think the output is as nice as the palette generated gif from ffmpeg, but if transparency is needed, that would work.

@kogaki ImageMagick is Apache licensed.  Would you mind asking the legal team what they think of including the ImageMagick or parts of it with OpenToonz?

**Comment by kogaki** [comment]
@turtletooth OK, I will check the risk of ImageMagick's codes next week. But, why not calling `convert` command of ImageMagick as external process as of ffmpeg ?

**Comment by turtletooth** [comment]
> But, why not calling convert command of ImageMagick as external process as of ffmpeg ?

That's what I plan on doing, but I was wondering if we might be able to include it in the install to keep users from having one more thing to locate the path to.  Also, at least on Windows, the default download of ImageMagick will do a full install, which is overkill for what we need.  A zip version is available, but I suspect many users won't really know to download that one.  

I am only using the convert command from ImageMagick.  I think the license should be compatible with OpenToonz   
http://www.imagemagick.org/script/license.php

**Comment by turtletooth** [comment]
@kogaki Have you heard any news about Image Magick?  I ran into an issue today that could have used a transparent gif.

**Comment by kogaki** [comment]
@turtletooth Though `imagemagick` has lower risk than `ffmpeg`, we have some concern about it. For example it's unclear that `imagemagick` has risk on patent of `MPEG-2000`. 

We decided that we cannot host `imagemagick` binary because `agif` must not a essential format in professional animation.

**Comment by blurymind** [comment]
While not essential, supporting gif and webm will make it easy for people to present their work on the web. This is especially important for students and people applying for work - who need to show off their ability in the best possible way.
Supporting alpha in gifs is important when you want to show off sprites your created for a game for example.

Not supporting a format because it's 'not essential format' for film animation production is not the best way to justify it - when it clearly is essential to students and to many of the users of the software - as they confirm that by repeatedly requesting it :)

**Comment by turtletooth** [comment]
#769 PR submitted.  You have to configure ImageMagick in the preferences, but it works for both trimming and transparency.  (Only transparency requires ImageMagick.  Trimming is done internally.)

**Comment by turtletooth** [comment]
@kogaki If there were a build without mpeg2000, would they be ok with distributing it?

**Comment by turtletooth** [comment]
@2dvision - I am thinking of pulling out the transparency code to simplify life for the users.  Is there still interest in having trimming without transparency?  I personally just use the spritesheet export feature, so it doesn't matter to me.

**Comment by 2dvision** [comment]
@turtletooth I also use spritesheet, But some employers want animate gif with transparency too. I solved my problem whit ImageMagick.

Perhaps it is not necessary for all users, However i can not imagine export animate gif without support of transparency. So do you think I should close this request?

**Comment by turtletooth** [comment]
@2dvision It doesn't look like ImageMagick will be bundled with OpenToonz - requiring it to be configured in OpenToonz the same way Ffmpeg is.  I think that adds too much complexity to the export process, so I plan on removing the part of my PR that adds transparency support.  That PR also includes trimming which I don't need ImageMagick for.  Do you think there is interest in being able to trim a gif even if it doesn't support transparency?  If so, we can leave this open.

**Comment by RodneyBaker** [comment]
Transparency is such a useful part of the GIF format that I hope a solution
can still be found.
An odd thought that occurred to me is...

Could the images first be processed as PNG with transparency and then
shoehorned into the GIF format while maintaining that transparency?

Apologies if that thought is way off the mark.
The reason that this comes to mind is that I was working with PNG format
and thought it exported out to GIF with transparency as desired.
I will have to recheck to make sure I didn't just imagine that.

**Comment by turtletooth** [comment]
I have not found a ffmpeg code that will maintain transparency when converting a png to a gif.  The gif export already uses png as the intermediate format, but I can't get it to maintain the transparency without converting using ImageMagick.

**Comment by RodneyBaker** [comment]
Fully understand.  Thanks for your past efforts to find that solution.
It's something of a head scratcher as to why FFMPEG doesn't more fully
support/document that functionality.
For what it's worth I agree that adding ImageMagick, while useful, would
add unnecessary complexity and confuse people.
It should be enough for folks that need gif with transparency to render to
PNG and then use some other utility.

I imagine many users will balk at even downloading and configuring
OpenToonz with FFMPEG and that is a must have addition.
Much appreciated!

**Comment by turtletooth** [comment]
I was playing with this today (it's been a long time).  I think it adds some useful functionality without having to use ImageMagick via the command line.  

I think I will leave my PR the way it is (with the option to use ImageMagick) to keep transparent images a possibility.

PR #769

**Comment by RodneyBaker** [comment]
I'm adding a note to this because I have been able to get GIF transparency directly out of OpenToonz via a means not likely anticipated.  

Background
When we render using the Multiple Rendering option under Other Settings in Output Settings this renders all Columns of an xsheet separately (quite useful in and of itself!) but when this output is to the GIF format it allows for gif transparency.  The current issue with this approach is that output that has moving transparency displays artifacts due to the way the gif file is set to replace images.  However, this does work well when a static mask is used and all changes occur within that mask.

Here's an example of the disposal method being wrong and therefore outputting the artifacting transparency:

![zdwanko_run_col5](https://user-images.githubusercontent.com/2576432/49388001-b4be0e00-f6e8-11e8-9130-4f56467a558a.gif)

Here's a similar output but one that uses a mask to cut the transparent area:
![packaging](https://user-images.githubusercontent.com/2576432/49388100-ee8f1480-f6e8-11e8-81e8-2cbf556becb4.gif)

A question then:  How best to flip the flag of the gif disposal method so that it is proper or to simply use a different but acceptable method to achieve acceptable results.

**Comment by RodneyBaker** [comment]
For general info:

> Transparency
> Like their static cousins, animated GIFs can contain areas of transparency. You can set transparency for each frame within an animation. Previous frames  will show through the transparent area of a later frame. If the background frame is made transparent, the browser background color will show through.   You need to properly coordinate frame transparency with the disposal method.  Don’t be surprised if the transparent areas you specified in your original GIFs are made opaque when you open the files in a GIF animation utility.  You may need to reset the transparency in the animation package.  Transparent areas can be generated from black or white pixels, “first color” (the top-left pixel color), or a color chosen from the image with an eyedropper tool.

REF:  https://cs.nyu.edu/courses/fall10/V22.0004-002/animatedGifs.pdf
