### ISSUE TITLE
OSX 10.11.3: Right clicking and selecting menuitem in drawing window disables drawing

### ISSUE THREAD

**Issue by trondarild** [opentoonz/opentoonz#73]
In any drawing window, e.g. PltEdit, right clicking to show context menu freezes drawing pointer (little red circle), making further drawing impossible in that window.

[OpenToons-1.0-issue#73.mov.zip](https://github.com/opentoonz/opentoonz/files/193906/OpenToons-1.0-issue.73.mov.zip)

**Comment by odysseywestra** [comment]
Thank you for the bug report. Could you provide a 15-30 second video illustrating the problem?

**Comment by trondarild** [comment]
I uploaded a zipped .mov file showing the behaviour, I hope you can play it back.

**Comment by Goofybud16** [comment]
Effects #51 as well

**Comment by xenogenesi** [comment]
I've this issue on linux and took a peek, looks like a release event is lost, on `sceneviewerevents.cpp`, `mouseMoveEvent()` handle only left or middle mouse buttons, if left is pressed the code should flow to `tool->mouseMove(pos, toonzEvent)`, but in this case doesn't happen because once the right button has been pressed `m_mouseButton`  is set to 2 and remain so  (`Qt::RightButton`).

I tried [something](https://gist.github.com/xenogenesi/72a34b22089ba3ed2e019c973107a138) on `SceneViewer::mouseReleaseEvent()` and got the left button working again but need to click one more time after the context menu has been closed. 

I'll keep looking and eventually let you know.

**Comment by xenogenesi** [comment]
Looks like `contextMenuEvent` is handled in a different way by windows (checked using wine), the context menu is shown on mouse release button, and the event is received by the parent widget before the menu is shown, this doesn't happen on linux at least (only the press is received), would be nice to have a confirmation from "mac"/"native windows" users, here's a [simple test](https://github.com/xenogenesi/qt-contextmenu-issue)

**Comment by kogaki** [comment]
I believe #152 solved this problem.
