### ISSUE TITLE
Suggesting a hide line tool for toon vector level

### ISSUE THREAD

**Issue by arh2009** [opentoonz/opentoonz#746]

**Comment by RodneyBaker** [comment]
Can you provide a little more information regarding how this tool would work and what it would be designed to do?

Currently, vVector lines can be hidden via turning the transparency from 255 to 0 on the M channel (RGBM) in the same fashion as turning use of an Alpha Channel.  This applies to any Palette Style used with either lines or areas.

**Comment by arh2009** [comment]
sure, just like anime studio tool...
i think a tool for that will be save a lot of time 
![hide edge animestudio1](https://cloud.githubusercontent.com/assets/20434396/17837246/babbf40e-67d7-11e6-8bf5-8fb6b3a6df33.gif)

**Comment by arh2009** [comment]
it can be hide a part or some of edges or line segments, without cutter the line segment at the first

**Comment by RodneyBaker** [comment]
Here's something of a workaround... but I think you already know that method.


![colorlines](https://cloud.githubusercontent.com/assets/2576432/17837854/1dfe8558-6784-11e6-8bc2-45f2635101e8.gif)

**Comment by arh2009** [comment]
@RodneyBaker : is it a connected line or just separate lines in a group ? , as i know we can not do that if all the lines was connected.
I wish opentoonz has hide line tool for a single line connected with many segments...

**Comment by arh2009** [comment]
![sample2](https://cloud.githubusercontent.com/assets/20434396/17840428/5beae606-6831-11e6-8a76-a7a261e26e9b.png)

**Comment by animking** [comment]
yes, it's needed.

**Comment by blurymind** [comment]
I dont understand what's wrong with the approach @RodneyBaker  suggested.
It seems to be exactly the feature that you are requesting.
It already is a part of OT - you just dont know how to do it and are used to how anime studio does it.

Imo opentoonz has a better design - as it lets you set any color to the line. If you want to make the line disappear, simply set it to a transparent style

**Comment by animking** [comment]
I guess you didn't use anime studio.

**Comment by blurymind** [comment]
I used it when it was called moho

**Comment by blurymind** [comment]
I guess you want to be able to hide a part of a line, without having to cut it

**Comment by RodneyBaker** [comment]
@blurymind   I see the issue they are running into.  It would certainly be better if we could isolate a part of a line.

If you'll pardon the long post, I believe the solution to this is going to be 'Named Groups'.
This is a larger subject but perhaps an appropriate place to highlight one of the benefits to be gained in exposing more of the grouping (and potentially subgrouping) of lines and shapes.

Discussion
Currently we can assign things to groups but it's not clear if we can access elsewhere in order to take advantage of those groupings via organization, sorting and otherwise manipulating those groupings.  In this case #746 could be served by selecting a Control Point, Line Segment, Shape or Group of Shapes then Right Clicking and selecting 'Hide' or (perhaps more appropriately for the method I am discribing; 'Transparent').  I note the difference because I believe technically 'Hide' could/should be a different feature similar to an On/Off option that every object in OpenToonz could leverage.

What the 'Transparent' option would do behind the scenes is assign the Color0 Style (which is fully transparent white 255, 255, 255, 0) to the Group.  It's important to note that this is a Style being applied and not some other hard coded transparency because we want to be able to not only hide the Group but make it any color style in our Palette and further to manipulate that color and transparency across a wider range of currently available features.

Current Obstacles to Implementing Named Groups in Order to Hide Line Segments
There is no apparent way to access a Group Listing that OpenToonz surely must maintain internally.  While it's possible Groups might be exposed in the Function Editor I've yet to see them there.  Because they cannot be accessed this limits the usefulness of grouping.  

If Groups are further exposed to the user they can be organized in such a way as to allow for the hiding of line segments (which is our feature request here with #746).  But it's worth noting that a Group without a name, while still useful lacks the benefit of descriptive documentation that tells the user what the function of that Group is to be.  In the case of #746 we don't particularly care what the Group's designation is.  We just want that section of the line to disappear. In this case it is fine for the Group to be assigned a default name of 'Untitled' until such a time where the user determines it worthy of being assigned a name.  Digging entirely too deep into this Named Group feature I would propose the Named Group be allowed a Project, Scene and Level designation that can be set by the user (in a similar way as with Color Styles).  This would allow users to (eventually) sort their Named Groups according to Projects first, Scenes secondarily and Levels.

Leveraging Named Groups
Being able to name Groups will allow users to specify Groups in useful ways.  For instance, a Group named 'Everything that is Red' might be useful in setting a collection of Lines and Objects in a scene that will later have a red Color Style applied to them.

Nested Groups
In using the example above of 'Everything that is Red' as a Named Group the user might further refine their detailing by selecting some of those lines and shapes in that group and naming them 'Light Red'.  This would signal that later during the application of color to the scene a light red Color Style should be applied to that Group.  It would be useful if the Light Red group could be found inside the 'Everything that is Red' grouping.  To further facilitate this nesting of Groups folders might be allowed that also can be named.

OpenToonz already has the Framework 
Again, Named Groups would be an option the user could leverage but would automatically be applied behind the scenes.  I suspect this already occurs in OpenToonz (as the Groups we create certainly must be stored somewhere).  In most cases it is sufficient that the Group is automatically and generically named as it is simply a means to an end; of hiding a portion of a line or shape for instance.  I do think in many cases what may be ideal is a method to toggle objects in a scene On/Off but that is yet another PR/Feature.  As the goal with this feature request is to make part of a line segment disappear it seems reasonable to believe that applying a transparent Color Style to that section as a Group would suffice.  This feature request then would be to automate that process so the user doesn't sense they are going through the process of applying the transparent Color Style.  All they do is Right Click and choose 'Transparent', which applied the ever present Color0 to their selection automatically.

Again I apologize for the length of this post but I want to look beyond this feature request to a more powerful set of features.

@animking said:

> I guess you didn't use anime studio.
We do tend to use our experience with other software and overlay that experience onto OpenToonz (and that can be both good and bad) but it's important to consider how best to leverage what OpenToonz brings to the table with it's unique approach and technology.  It's not enough to simply gain the feature of another program.  If OpenToonz can leverage it's own strengths first while considering the goal at hand it can leapfrog over other programs in terms of feature sets and user experiences. It's okay to invoke the other programs but we need to be users of OpenToonz first and foremost in order to more clearly see the way forward.  That is a challenge each of us face.

**Comment by blurymind** [comment]
I agree, OT devs shouldnt just shove in other software's features. The requested feature should be carefully designed to fit in the existing design of the software and deliver the requested features in a better way than the competition - strive to do it better!

**Comment by RodneyBaker** [comment]
One of the reasons I love animation so much is that it brings everything into it.  ;)

Speaking of 'other features' and programs...
I accidentally stumbled upon a discussion on the 'new' hidden attribute in CSS and it made me think of this topic.

If you are bored or interested in such things:  https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

The only thing that really applies from that link is this quote (and the general idea behind hiding anything):

> The hidden global attribute is a Boolean attribute indicating that the element is not yet, or is no longer, relevant.

How this applies to our current discussion relates to what I said in my huge post (as an aside) about toggles for On/Off for every object in a scene.  I think it safe to say that the user is the one who should have the final say on what is on or off and the more options in this regard they have to make that decision the better although the added complexity can quickly run away with the whole thing.  This is why I emphasis Named Groups as Documentation is as important as the thing you want to go away.

If we consider also the power of OpenToonz  History feature... wow... that thing is awesome.... Named Groups would help us in that effort.  For instance, let's say we 'hide' a segment of a vector line.  This might result in the history for that decision to be labeld as:  'Set Untitled000 to hidden'.   Later on that Group's name might be changed by the user to "Epiletts"which would result in an event in History labeled, "Named Untitled000 group to Epiletts".  Later still we might adjust the line width of the bottom and top of that section of vector line to add a tapered look.  History would record something to effect of "Pump Tool blah blah blah" (Note:  I'm not sure if these events are recorded in history... I'll have to check).  And then at the DIrector's recommendation the Epilettes are determine to be light blue in color so History records that "Epilette Color Style changed from Color0  to Color45".

Sorry.  I'll stop now.  
In case you haven't noticed I'm using these discussions to explore other OpenToonz features. ;)

**Comment by RodneyBaker** [comment]
Okay, I said I would stop but I don't have a more appropriate place to note this at the moment so will add this to the mix here...

I mentioned the History that OpenToonz maintains and so I thought I'd close the loop on what we see when a Color0 is applied to a line.   If we could assign that same thing to a portion of that line then we should see something similar.

When we apply the Color0 style to a vector line History states, "Unidentified Action".
Firstly, I believe a more proper term might be 'Undocumented Action" as I think it's fair to say the Action can be identified but as of yet nothing has been paired with that Action to describe what transActed.  

But wait... I am now distracted.
I see that we do indeed have Named Groups already and they are exposed in (of all places) the Exposure Sheet.  Now how appropriate is that!  :) 

So... this feature is almost writing itself.

**Comment by arh2009** [comment]
the reason i request this tool is to save my time when I'm doing like this sample drawing in anime studio
![hide line in animestudio](https://cloud.githubusercontent.com/assets/20434396/17929962/16a26f8e-6a2e-11e6-9d5b-eaf7a21b9236.gif)
it's only took about 3 to 4 sec to hide the line and produce the image that i want...

**Comment by arh2009** [comment]
@RodneyBaker said : ^^I know that the Pump Tool appears to only pump the thickness of a segment of a line down to 1. If that could be made to include zero.... there'd be our hidden portion of our line.

but it has a problem, it will make a slope for the line width
![slope line](https://cloud.githubusercontent.com/assets/20434396/17931478/de8aa3ca-6a35-11e6-9395-2f4e789b2829.png)

**Comment by blurymind** [comment]
you need to create two nodes that are close to each other in order to avoid
the slope problem. Its not an ideal solution

**Comment by RodneyBaker** [comment]
> but it has a problem, it will make a slope for the line widt

> you need to create two nodes that are close to each other in order to avoid
> the slope problem

For the Pump Tool the two points already exist and we can adjust them via the size slider.  An issue with adjustment (currently) is that the focus doesn't remain on the canvas during the adjustment so we can't see the result of that adjustment in real time.  We have to adjust... check to see where the red lines representing the width of the tool are... adjust.... check... etc.   Then of course there remains that matter of the sloping of those lines.  That would need to be addressed and an option made available to control the visual result of the terminus of the affected line.  

The part that would need to be enhanced would be the sloping which (in similar fashion to animation itself would need to have various interpolations (Hold, Linear, Ease In/Out). Or more perhaps more realistically a simple toggle to turn the slope on/off.

The primary reason I wouldn't want to use the Pump Tool (Zero Line Thickness) solution for this problem would be that I'd rather be able to color the lines (turn them transparent) than actually reduce their width in size.  The end result can be the same in both cases... that of a hidden line... but with the sizing option we'd lose the ability to also apply a different color to the line.   Having both enhancements (Pump Tool allowing the creation of a zero thickness line) and Color Style Application to (Named) Groups) would of course be nice.

The work arounds to this problem are pretty straightforward but aren't as optimized as that seen in the Anime Studio demo.  Current methods come close... 

I would say that pending the implementation or enhancement required by this requested new workflow the quickest and most efficient workaround is going to be to place all the various object and then strategically use the cut tool to quickly separate those lines that need to be hidden (or a different color).

**Comment by RodneyBaker** [comment]
I'm adding this because I spoke a bit too soon when I said the Pump Tool cannot decrease line thickness to zero.  It turns out it can BUT...

When the line does decrease to zero it' is the entire line (all connected segments) that changes to zero.  This is interesting because if any other thickness than zero different parts of the line can be of differing thicknesses.

To put it another way...
Say we start with a rectangle that has all side lines of zero thickness.
We can use the Pump Tool to increase the thickness upward from zero but before any of the line changes to a larger thickness than another part of the line (say on the opposite side of the rectangle) the entire line will first increase to a larger size than zero.  

What does all this mean?
It simply means the Pump Tool is a likely candidate for the requested enhancement to be able to 'hide' lines.


Note:  If testing with a rectangle it can be useful to rotate the shape so that its lines are not vertical and horizontal because the bounding box will appear on the canvas as if it is the actual rectangle.  This will make it appear that the lines are not zero thickness (because if 'hide zero thickness lines' is on those lines disappear but that bounding box remains.  Because of the possibility of mistaking the bounding box for the shape it might be best to test with a sphere or other non-rectangular shape.  This caught me off guard at first because I thought the Pump Tool wasn't decreasing the lines to zero (because I could still see the bounding box on the canvas and thought that was the rectangles' lines.

Clear as mud?   Sorry about that.  ;)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
