### ISSUE TITLE
Accurate Vector Brush (quality) + Cutting Ends (overlapping cut) + Temporary Second Tool (wokflow)

### ISSUE THREAD

**Issue by AlonDan** [opentoonz/opentoonz#747]
Hello All,
This is my very first post on GitHub, Sorry about my bad English and I hope that you will understand my post.

If any of you ever used ToonBoom Animate or Harmony, Not only that their Vector brush is currently the best accurate and smooth I've ever used for Animating with Vectors (not talking about Rasters) but also there is a powerful feature that we all NEED and want in the future OpenToonz.

The reason I only use the Raster layers in OpenToonz now is only because it feels more accurate when drawing, even after messing with the smoothing options on the latest version (currently Version 1.1.1) I can't get a natural feel when drawing with vectors compare to other vector software such as ToonBoom Studio (their old software), Animate and Harmony. 
Just to be clear: Studio and Animate are no more supported and stop developed, they only have ToonBoom Harmony now, I gave these examples because even ToonBoom Studio is very old, it had the same Vector Brush engine and feel as they use now in Harmony, of course they've improved it but still it was very accurate consider it's Vector and not Raster brush.

So the 3 Features I believe lots of us will be HAPPY to have in OpenToonz are:
## 1 - Improved Vector Brush (quality + accuracy)

Higher quality and more accurate Vector Brush (just like in Harmony, but with the powerful tools of OpenToonz of course).

Maybe the OpenToonz Brush engine is too old and need to re-code from scratch or update it's features, I'm not a programmer I can only guess.
But it doesn't matter, as long as it's possible to work on the Vector Brush it will make OpenToonz MUCH more usable and stronger in the standard 2D Animation area.
## 2 - Cutter Tool for vector Brush.

I know that there is a cutter tool in OpenToonz but I mean to something different, 
It's more like in ToonBoom Animate (old) and ToonBoom Harmony (from older version until today's version).

This POWERFUL tool making the animation process much faster, and as somebody who used it for a while in their very early version of Harmony called "ToonBoom SOLO" I immediately fall in love with it and it let me animate MUCH faster because the brain tells me to use it as I draw every frame, it is like a magical shortcut that once you start use you can't stop work with it.

Let me try to explain how it works:  (see example GIF below)
Every time you add a NEW line of drawing OVER another line (stroke) you can hold the T key on your keyboard (shortcut) while using the brush tool and as long as you hold the T key the tool changes to the "CUTTER" while you hold the key and drawing on a overlap line you can cut it with No extra edges, No weird leftovers of vectors or anything it is the most accurate cut and it is VERY CLEAN you can draw and fix any shape in less than few seconds as you animate, means you do all this WHILE DRAWING! 
## 3. Holding Key for a Temporary Second Tool

Just like I described the wofklow of the Brush Tool as the main one, and the Cutter as the second one ONLY WHILE HOLDING the key:
This workflow is magical:  You choose the vector Brush Tool, drawing something and as you draw you hold the T key to use the CUTTER TOOL and fix, manipulate, clean lines.  once you let the key go, it gets back to your default Brush Tool and you continue drawing.

This workflow in general of holding a button while you're using your selected tool as the MAIN TOOL.
So you don't have to press B for brush and than again T to switch to cutter tool and again... B and so on, you just hold the T key (or any other shortcut we need) and when you stop holding the key, it will get back to your MAIN TOOL, this is much better than any regular hotkey switching in any software.

Example of all the 3 features (used in ToonBoom Harmony)

![harmony_cutter](https://cloud.githubusercontent.com/assets/21152334/17835724/0dcb3732-6782-11e6-93be-7904b7064518.gif)
- Sorry about my bad English.

I really hope to see these features in the future of OpenToonz, it will make OpenToonz much better for sure!
Keep up the good job and have a wonderful day.

**Comment by tGuMedia** [comment]
Hi Dan, 

after playing around with Toonboom i think i have a better understanding how the cutter tool works.
first off, the brush tool in ToonBoom works very different from the brush toon in OT.

TB´s brush works similar to the brush tool in Flash. they create filled areas representing lines  rather than actual lines.

in TB when to brush strokes cross they get separated in different areas 
![scr1](https://cloud.githubusercontent.com/assets/14109276/17837083/160cb0e8-67a9-11e6-9004-c7628ff34188.PNG)
which makes overflowing lines very easy to get rid off

![scr2](https://cloud.githubusercontent.com/assets/14109276/17837089/4231f7d2-67a9-11e6-92fa-3f246183a2ee.PNG)

OpenToonz also can get rid of overflowing lines but it tries to find them by itself rather then letting the user choose what lines to remove.

i really hope the OT brush tool gets rewritten, but that´s a really big task to complete.

**Comment by blurymind** [comment]
@tGuMedia @AlonDan 
I already filed this request several months ago:
https://github.com/opentoonz/opentoonz/issues/287

Basically we came to the conclusion that it can be done, but it will need to work in a different way to the one in toonboom.

You can mark this  post as a duplicate ;)

**Comment by RodneyBaker** [comment]
I commented in the same topic in the forum and its interesting to see the responses here.  I had guessed that Toonboom was working with very different type of object (basically shapes versus vector lines) which allowed them to get their particular results.

It would definitely be a major overhaul to get the same functionality.
With regard to the different way that might be pursued I posted some thoughts on that as well in my forum response that delves a little into thoughts on (vector) shaping (weld, intersect, etc.)

**Comment by AlonDan** [comment]
Thanks All, I'm glad that this subject is important to other users.
BTW  - I just shared my mind on your post on the forums Rodney :)

I hope that the amazing Devs on the OpenToonz community will take the all Brush Re-Design as a project and will upgrade it's very core to something we all be happy to use! 
([as I described in details on the forums](https://groups.google.com/d/msg/opentoonz_en/eL0zV3sPkMw/cm8g-Kp8DAAJ))

**Comment by blurymind** [comment]
Opentoonz already has feature number 3. You can hold a key to go to another tool and then release it to go back to your current tool

**Comment by AlonDan** [comment]
Thanks blurymind, That's great!  I never tried that before, I just clicked without holding.
Thanks for sharing your knowledge on this.

2 more CORE features to go... I guess ;)

**Comment by turtletooth** [comment]
@ideasman42 Right now, the brush is a single vector line.  Do you have any vector math experience?  How hard is it to convert a vector drawn this way to an outline of the vector with a zero thick stroke?  I'd love to implement this, but I have no idea where to start and have never worked with vectors before.

**Comment by RodneyBaker** [comment]
For discussion's sake I will note (naively) that a hack of the conversion
from vector line (I find I prefer the term spline here) to vector shape
might be that of rendering the image created with the vector line and then
(upon import) converting the image to vectors again but using Outline
(rather than Centerline) method.

And that might provide something of a hint as a way to proceed in that the
vector line we start with is equivalent to Centerline whereas what is
desired (for our purpose here) is Outline.

Now, how to do that without the costliness of rendering to disk (image) and
then converting (with potential for loss of detail) to vectors again with
volume... that is the question.

We might consider how OpenToonz stores the thickness associated with a line
(as modified by the Pump Tool) and what data is stored relative to Control
Points on that vector line.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
