### ISSUE TITLE
Android/iOS mobile port

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#755]
I would vouch to test it and even support it's development by purchasing it on the app store.
Even as an apk that is not hosted at the android market, i would still love to have it.

Almost everyone now has a tablet or a smartphone. A lot of these devices come with a pen - if not pressure sensitive pens for them are easy and cheap to acquire. Even wacom now has android tablets sold.  Pressure sensitive or not - varied thickness can be faked via acceleration.

If anyone else vouches to test a future port or has some information, please state your device and why you would love to have OT running on it.

For me personally these are the reasons:
- the galaxy note is an affordable alternative to cintiq. Many tablets nowadays are!
- I can carry it around the house and hold it in a more comfortable pose on the sofa - as opposed to sitting in front of my laptop to draw - it's much easier to pick up and thus the incentive to casually start OT is bigger.
- I can use it while travelling on the train, bus, or generally being outside - making OT easier to show to other people and taking it out in the world - to the eyes and hands of more people. It will make it easier to show OT to others and get them involved!
- There is currently no good basic animation software for android - especially one that is open source. 
- Multitouch makes it very easy and nice to pan,rotate and zoom on the canvas naturally. Combined with a pen - it is a combo that is hard to beat by a desktop computer. It feels so natural :) 

I know that there would be some design challenges in this- but i strongly believe that it would be worth the effort - especially if the goal is to get OT in the hands of more people!
Tvpaint is an example of a port being done right -as their port is basically the same as the desktop app almost! However tvpaint on android costs 1500£ - which in my humble opinion is an insane price tag 

There is some other software on android, but it is not professional in the slightest. It's really basic.

Open toonz is a complex piece of software, but I believe that it is not impossible to port it over to a mobile platform. You might have to change some interface elements, and cut down some of the tools at first, but it can be done.
You could even put it on the app market as freemium. It will help the popularity of OT imo.

Artrage devs made the transition and it has been incredibly successful. 

So for now, until there is actual developer interest or more information on the posibility for such a port, I vouch to test any possible ports on my tablet.

If you are a tablet user, with a stylus and are interested in such a port, please state what model tablet you have and if you can test it.

**Comment by manongjohn** [comment]
Wow. Funny, last night i decided to see what animation software was available for my Samsung Galaxy Tab S2. I found an ok freeware version called 'Animator'. Has onion skin and layers which is why i liked it better than others.

Would be cool to see an OT-lite/mobile version. Can help test too.

**Comment by ideasman42** [comment]
This would mean upgrading OpenGL usage, removing immediate mode, 

A quick check shows ~235 uses of `glBegin`, across ~55 files.

Not sure its useful to keep issues like this open unless someone plans to work on it.

**Comment by RodneyBaker** [comment]
This looks more likely to be a branch where someone takes the code and rolls out their own release of the program (ex:  @turtletooth branching out to the portable and Motion Monster versions)

**Comment by walkerka** [comment]
The Qt widgets module behaves very badly on mobile platforms. There're dozens of bugs in OpenGL related components. The stylus bugs also reproduce between versions again and again. If you really want to do something seriously on Android/iOS, do not use Qt.

On Android, there're also app memory limits (64M for my phone). The CPU is also much weaker than PC's. You have to change your design. That's not an easy task. The porting could become rewriting at the end. Maybe writing a new app from scratch is a better idea.

BTW you can use TVPaint's Android open beta forever by adjusting your system time to before 2010. It must be a bug :(

**Comment by blurymind** [comment]
@walkerka : 
1. tvpaint android is has been out of beta for a long time and the openbeta is no longer available for download, only the final version is. Do you know where one can get it?
2. The trial can not save tvpaint files - so you can not save your progress, it can not export animation without a stamp. Does the open beta also have these limitations?

**Comment by blurymind** [comment]
I would vouch to test it and even support it's development by purchasing it on the app store.
Even as an apk that is not hosted at the android market, i would still love to have it.

Almost everyone now has a tablet or a smartphone. A lot of these devices come with a pen - if not pressure sensitive pens for them are easy and cheap to acquire. Even wacom now has android tablets sold.

If anyone else vouches to test a future port or has some information, please state your device and why you would love to have OT running on it.

For me personally these are the reasons:
- the galaxy note is an affordable alternative to cintiq. Many tablets nowadays are!
- I can carry it around the house and hold it in a more comfortable pose on the sofa - as opposed to sitting in front of my laptop to draw - it's much easier to pick up and thus the incentive to casually start OT is bigger.
- I can use it while travelling on the train, bus, or generally being outside - making OT easier to show to other people and taking it out in the world - to the eyes and hands of more people. It will make it easier to show OT to others and get them involved!
- There is currently no good basic animation software for android - especially one that is open source. 
- Multitouch makes it very easy and nice to pan,rotate and zoom on the canvas naturally. Combined with a pen - it is a combo that is hard to beat by a desktop computer. It feels so natural :) 

I know that there would be some design challenges in this- but i strongly believe that it would be worth the effort - especially if the goal is to get OT in the hands of more people!
Tvpaint is an example of a port being done right -as their port is basically the same as the desktop app almost! However tvpaint on android costs 1500£ - which in my humble opinion is an insane price tag

**Comment by walkerka** [comment]
I was talking about "widgets" module in Qt5. I haven't check krita's code yet but it should be porting to "qml". It's designed for mobile. The bad news is in Qml you have to use javascript to do most things. It will take long time to port all the UI to qml.

I downloaded the TVPaint open beta 3 years ago, and it runs well on my Note2. I can only find this one now. (Chinese) I don't know whether it's same as original app. The provider says he only added Chinese translation. Please use it at your own risk.

http://pan.baidu.com/share/link?shareid=402417265&uk=470761299
1. input password  78c7
2. click on "下载“
3. click on "普通下载"
4. install and adjust the system time to before 2013

**Comment by blurymind** [comment]
@walkerka I dont get 3. I think it requires an account which i would gladly make if i knew chinese.

Could you share it to depositfiles or wetransfer please? You would make me a huge favor :)

**Comment by walkerka** [comment]
@blurymind Here's a copy, 
https://drive.google.com/file/d/0B90Sy83y1HRPNUpROTBVZm5jQ1k/view?usp=sharing

**Comment by blurymind** [comment]
@walkerka Thank you!! You're awesome.

TVP on android seems to be the complete version of tvpaint - only running on android. And it's incredibly performant too.

The only platform specific features they added seem to be:
- pressure sensitive stylus support
- multitouch - pinching to zoom in and out and also pan

I can only hope to see opentoonz ported in the same way some day.

Tvp 11 andoroid also has ability to increase the size of the gui - buttons and menus - which helps make it more accessible on tablet devices.
Unfortunately 10.5 doesnt have that, but at least you can save your project - which 11 has disabled

**Comment by blurymind** [comment]
In a relevant news, another qt based open source animation software TUPI has gotten an android port!
 https://pbs.twimg.com/media/CsPgb5hWYAAQA4t.jpg:large

> @blurymind It's being developed using @qtproject. It will be open source & available on Android but portable to iOs, Windows, Mac & Linux :)

**Comment by Amadhia** [comment]
I would vouch to test OpenToonz on iOS (iPad Pro)

I have a history in animation (Exclusively 3D for years, but I did start my career drawing on paper for an outsource house for Disney Interactive, and I have been wanting to get back into Traditional animation for my own personal enjoyment for some time).

My history as a Tester includes: LightWave 3D, and various projects I'be supervised (Video Games, healthcare, etc.)

My mentor from Disney Feature has been talking with me about doing personal projects, and I'd love to use OpenToonz for these fun little ideas.

As per Blurymind's request here are the reasons I would like to use OpenToonz on iOS:

- I'm using an iPad Pro and prefer its PENCIL far better than WACOM CINTIQ.  (Less lag, better overall feel, better pressure sensitivity

- Using multitouch to navigate/zoom/undo/redo in ProCreate and other iOS drawing apps has been such a powerful addition to digital drawing

- My iPadPro goes nearly everywhere with me -- and with 10-12h of battery time while drawing, (it's long since replaced my Windos Slate as my go-to device for digital drawing).  Being able to work on projects on such a portable, convenient device would be a godsend.

- There are no good resolution-independent, vector-based drawing programs for true animation style drawing on iOS.  (I don't count iOS Illustrator Creative Cloud since I am not fond of its drawing feel, and the fact that to get the .AI version of a file done on the free iOS app, one needs to purchase/use a subscription for the desktop version of Illustrator Creative Cloud -- so it's a "bait and switch" sort of thing to get people's money, which I think is a bit dirty.)

- There are no professional apps for animation on iPad.  (Everything I've seen so far seems like a toy or hobbiest sort of thing).

**Comment by RodneyBaker** [comment]
Just thinking out loud here...

A logical/interim progression toward a port for Ipad/ioS would seem to be a stripped down version of OpenToonz that only includes those things that are very basic... no extra bells... no whistles... no fancy frills...  only core drawing and animation features that set up and manage a basic bare bones project.  If a branch such as this could be created for Win/Mac/Linux (WiMaLi.... in that order not MaWiLi or LiMaWI or LiWiMa*) then not only would that be a useful application but the code could more easily be ported to iPad/ioS.



*Why WiMaLI versus a focus on Mac or Linux first?  There are many reasons for this... besides the number of programmers with experience on the Windows platform.  The first reason is that a Windows core release is likely the easiest to produce because the code is already there... extraneous code just needs to be removed.  Mac gets targeted secondly because (presumably) the code used for Mac will inform that of iPad/ioS.  And finally the Linux port seals the deal on cross compatibility and jettison of anything that isn't truly cross compatible.

At the point of reaching each milestone in CoreOT others could then refine that branch to perfect the user experience and underlying code.  Over all programming would (theoretically) be easier because there would be less code to wrangle.   Programmers would become very familiar with the core code whereas specialists would focus on the features that continually circle around the core looking for an optimal point of entry that will benefit the core..

**Comment by Amadhia** [comment]
That sounds like a very wise/logical approach to me too!  (Having done some programming myself, I can imagine what an Herculean task it would be to get a complete port done of such a complex application all at once!)

In the Anime/Cartoon art style crowds (the folks that love drawing still in the styles of anime, Disney, Bluth, WB, etc.) there is such a need for a tool such as Paint Tool Sai on other platforms, (Mac, and my own preference, iPad Pro).  But as much as I love Sai for my own design work, it's Vectors still must be converted to Rasters in order to flood fill, which then still slows-down the process of ink-and-paint and Tone/Highlight to a painful, snail's pace...

...An iPad Pro app that simply embodied the vector drawing/fills, and the ability to add effects (not only for great lighting and compositing effects like Backlight, Blooms and blurs, but also mattes to quickly get great soft-edged shadow tones as in this tutorial: https://www.youtube.com/watch?v=BBwJfdplYZg )... That would be such a boon to the artists who love drawing in Anime/Animation styles, I can't even begin to describe.

(Of course... I am 100% for the end-goal being a full port of OT to iPad Pro... I'd love to be able to take my iPad over to my mentor's house or a coffee shop and be able to so easily work on a project together. :)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by blurymind** [comment]
tvpaint's android port is full featured.

It only has a few additional features to make it better work on android:
- GUI scaling setting in the preferences window - allowing you to resize the controls with a global value
- Touch screen controls, which OT is already getting #1437
