### ISSUE TITLE
Crash while opening application while "Creating Main Window"

### ISSUE THREAD

**Issue by TMNTdude** [opentoonz/opentoonz#77]
I just downloaded this software OpenToonz software. Unfortunately when launching the application it crashes while "Creating Main Window". 

**Repro:**
1. Download OpenToonz software from the following link "https://opentoonz.github.io/e/download/opentoonz.html"
2. After download is complete,  start the install, and follow the install wizard instructions
3. Once completed, go to the Start Menu, and open OpenToonz

**Issues Result:**

Application crashes while "Creating Main Window" is displayed in OpenToonz start window

**Expected Result:**

Application opens normally

**Notes:**
Toshiba L650
Intel Core i3
Windows 7 Home Premium 64bit SP1
4GB of RAM
OpenToonz 1.0 installer and OpenToonz 1.0.1 installer

Updated 160329

**Comment by TheoXD** [comment]
A very strange bug, I solved it by using only single monitor, it was kinda annoying doing it all the time, then it fixed itself once I ran the application as administrator, and it no longer crashes.

**Comment by TMNTdude** [comment]
Even running it as administrator, I get the same issue. I'm only using a single monitor as well.

**Comment by sboutwell** [comment]
Had a similar issue, uninstalled and reinstalled. I was able to solve my issue.  I had installed this program and it's additional folder on my E: Drive.  It would crash each time it loaded.  Uninstalled reinstalled to the C: Drive.  Works every time so far now.  The reason for installation on my E: Drive is my C: is a Smaller SD that get's rather full.  I am using a Dual Monitor system and everything is working correctly now.

**Comment by TMNTdude** [comment]
I installed it on my C drive, and I had no other drive attached. I just installed it on my work PC, and it works fine with no issues. 

One difference is my work machine is a desktop, and my home machine is a laptop.

I'll provide my full home machine specs later.

**Comment by odysseywestra** [comment]
Is the crash still persistent with the current version of opentoonz?

https://github.com/opentoonz/opentoonz/releases/tag/v1.0.1

**Comment by TMNTdude** [comment]
Yes, still an issue with the latest 1.0.1 installer. One thing I noticed is that the crash says "OpenToonz_1.0.exe has stopped working". Should this be saying 1.0.1?

Here are some new things I noticed while trying to fix the issue. Doing a full uninstall doesn't delete the "OpenToonz 1.0 stuff" folder. But that's a separate issue. I've run c cleaner, after doing an uninstall, and also manually deleted the  "OpenToonz 1.0 stuff" folder. restarted and installed a new download of the installer, and I am still able to reproduce the issue.

I will update my original post with my machine's full specs.

I really want to use this software!!!

**Comment by odysseywestra** [comment]
> Here are some new things I noticed while trying to fix the issue. Doing a full uninstall doesn't delete the "OpenToonz 1.0 stuff" folder. But that's a separate issue.

That issue is related to #60

**Comment by scardario** [comment]
I may have information on this bug, I deleted all the configuration files created in some subfolders of "open toonz stuff" during the start of the application and it worked, about 27 files. I just make a search for all the files in that folder, organize the search by modification date and delete all of those that were created last.

The crash seems to happen when I have a window in other monitor and that configuration is saved in some file.

If I don't move a window to another monitor the software seems to start again without problems, if I use a window, like say, the combo window, to other monitor, the software will crash the next time I start it.

I use 3 monitors (2 monitors and a cintiq), changing a single window to any of the non-primary monitors will crash the application next time I start it.

Hope it helps.

**Comment by TMNTdude** [comment]
scardario -  This issue is not related the the multiple monitor issue.

**Comment by scardario** [comment]
Awh, sorry, I thought it was the same because it crashed on start while "Creating Main Window".

I will look for the multiple monitor issue.

**Comment by odysseywestra** [comment]
@scardario so far no one has issued a bug report about opentoonz crashing with multiple monitors. So go a head and open a new issue thread about that.

**Comment by scardario** [comment]
Thank you, I'll do that

**Comment by TMNTdude** [comment]
Any update on this? I tried everything last night and still couldn't fix the issue.

**Comment by ctkjedi** [comment]
Just installed this evening. I verified that I downloaded 1.01 and I get the crash as it creates the main window. It actually opened once, but since then, nothing, even if I run it as an admin. I tried to run it from the command line and got sever libpng warnings. Here's the full readout:

> C:\Program Files\OpenToonz 1.0>plugin search directory:C:\OpenToonz 1.0 stuff\plugins
walkDirectory_: C:\OpenToonz 1.0 stuff\plugins
===== PluginLoadController::finished() =====
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
create Cleanup
create PltEdit
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
create InknPaint
create Xsheet
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
create Batches
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
create Browser
Could not parse application stylesheet
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50

**Comment by AyameLee** [comment]
Could it be to do with PNG files using an older color profile? For example the PNG files for the theme. Is it worth looking at removing ICC data from those images located in **OpenToonz 1.0 stuff\config\qss\**?

This could probably be tested by just renaming the OpenToonz 1.0 stuff directory, that way OpenToonz 1.0 won't be able to find it, error out but it should still start up. I just tried it and the GUI is completely broken, but the point is to see if it starts up.

Corel Painter 2015 and 2016 has problems with color management, runs fine on one of my machines, but needs fixing on another when newly installed.

Try adding some ICC Profiles under Windows Color Management and see if that helps.

Try it on a freshly installed Windows to rule out any conflicts with other software or drivers. With Toon Boom Harmony, it won't run with Intel HD3000 iGPU drivers installed unless I uninstall OpenCL.

**Comment by AyameLee** [comment]
Could it be to do with PNG files using an older color profile? For example the PNG files for the theme. Is it worth looking at removing ICC data from those images located in **OpenToonz 1.0 stuff\config\qss\**?

This could probably be tested by just renaming the OpenToonz 1.0 stuff directory, that way OpenToonz 1.0 won't be able to find it, error out but it should still start up. I just tried it and the GUI is completely broken, but the point is to see if it starts up.

Corel Painter 2015 and 2016 has problems with color management, runs fine on one of my machines, but needs fixing on another when newly installed.

Try adding some ICC Profiles under Windows Color Management and see if that helps.

Try it on a freshly installed Windows to rule out any conflicts with other software or drivers. With Toon Boom Harmony, it won't run with Intel HD3000 iGPU drivers installed unless I uninstall OpenCL.

#109

**Comment by TMNTdude** [comment]
Why was this closed!!! If you read my reproduction of the issue you'll see I'm using a laptop and not using multiple monitors. Please re-open. If this isn't re-opened I'll create a new bug for this.

**Comment by turtletooth** [comment]
Is this still an issue?

**Comment by turtletooth** [comment]
Closing as abandoned.
