### ISSUE TITLE
Panel Spacing

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#771]
I would like to propose changing the spacing between the panels.  Right now, it seems bigger than it needs to be.  Here is my suggestion (4px):

![spacing](https://cloud.githubusercontent.com/assets/4576381/18041162/cbe9a30c-6d72-11e6-9714-cdb232796aaf.jpg)

Here is the current spacing (8px):
![spacing_old](https://cloud.githubusercontent.com/assets/4576381/18041164/d36ce062-6d72-11e6-9672-d3de60a66188.jpg)

It's an easy fix on tdockwindows.cpp at line 47 (This is to remind me where I found it)

**Comment by blurymind** [comment]
Yes please! Make it more compact

**Comment by konero** [comment]
I agree, I don't know if you've seen the Harlequin dock separator before but it was obnoxiously wide. If this is a problem for some people, it can always be added in the preferences under interface as a custom value box or something.

This might be relevant, how difficult do you think is it to build and maintain a custom window border? Like putting the menu bar and room bar in the window title. Something like this.

([view full-size](https://cloud.githubusercontent.com/assets/19820721/18048685/9092ccca-6ddb-11e6-8419-d757f9bd4c79.png))
![tz_window_ui](https://cloud.githubusercontent.com/assets/19820721/18048685/9092ccca-6ddb-11e6-8419-d757f9bd4c79.png)

**Comment by konero** [comment]
Hey, I noticed the new combo viewer icons. :+1: 

Not sure if you're able to change the spacing of them, but here is a spacing chart.

![comboview_space](https://cloud.githubusercontent.com/assets/19820721/18049098/fe25cd62-6ddd-11e6-97ee-ef188f1f5723.png)

I noticed the 3D Cam and Cam icons have no spacing, so we could increase the size of the 3d Cam icon by 1px to merge it with the Table icon as a workaround (I think that would work).

**Extended by 1px (19px)**
![3dcam](https://cloud.githubusercontent.com/assets/19820721/18049393/e6cd7cda-6ddf-11e6-9598-9b173e8060ef.png) ![3dcam_active](https://cloud.githubusercontent.com/assets/19820721/18049396/ea55de6a-6ddf-11e6-954c-fd49808cf385.png)

**Comment by turtletooth** [comment]
> This might be relevant, how difficult do you think is it to build and maintain a custom window border? Like putting the menu bar and room bar in the window title. Something like this.

I like the idea.  I haven't done anything like that before- I have to see if qt allows this.

>Not sure if you're able to change the spacing of them, but here is a spacing chart.

Thanks I will look into that when I can.  In the meantime, I will try out the new icon.

**Comment by turtletooth** [comment]
> This might be relevant, how difficult do you think is it to build and maintain a custom window border? Like putting the menu bar and room bar in the window title. Something like this.

Looks like this is totally possible.  Just takes some work.

**Comment by turtletooth** [comment]
How's this?
Before:
![before](https://cloud.githubusercontent.com/assets/4576381/18115109/cb70c7ec-6ef9-11e6-85f5-bf7651043483.jpg)

After:
![after](https://cloud.githubusercontent.com/assets/4576381/18115111/ce99b0fa-6ef9-11e6-94ec-ac28090b0feb.jpg)

**Comment by konero** [comment]
Very nice! :+1: 

It just occurred to me, these icons may look a little bit too low contrast if used on a light theme, I'm not sure how many people would use light themes these days considering eye safety and all that, but do you think it's worth slightly brightening them up for compatibility? Of course, it wouldn't matter if the icons were pushed into the stylesheets later down the road.

Here's a new pack if you want to try them, they're slightly brighter _(the off state gray background)_, I also added in some rollover icons.

I tweaked the sub camera icon to make it look more like the original, the safety guide icon to make it seem more obvious, removed the sub color from the freeze icon to simplify it and made the guide icon slightly larger since the original has a lot of unused negative space.

**Off**
![safe](https://cloud.githubusercontent.com/assets/19820721/18123754/3de4295a-6f67-11e6-91d3-f8b5c8e50b27.png) ![grid](https://cloud.githubusercontent.com/assets/19820721/18123758/40fe2794-6f67-11e6-8bae-4571f4620876.png) ![table](https://cloud.githubusercontent.com/assets/19820721/18123771/4ad1f4e4-6f67-11e6-83ea-86eb6aa62f11.png) ![3dcam](https://cloud.githubusercontent.com/assets/19820721/18123775/4f79361a-6f67-11e6-816f-0d7bb7a1b6bd.png) ![cam](https://cloud.githubusercontent.com/assets/19820721/18123778/520941f4-6f67-11e6-8485-e40d23573bb4.png) ![freeze](https://cloud.githubusercontent.com/assets/19820721/18123797/71f32e94-6f67-11e6-9cda-de9f9569e0c1.png) ![preview](https://cloud.githubusercontent.com/assets/19820721/18123803/7bc41802-6f67-11e6-9150-f3d070abd53f.png) ![subcam](https://cloud.githubusercontent.com/assets/19820721/18123805/804b3f90-6f67-11e6-819c-c27d80808b05.png)

**Active**
![safe_active](https://cloud.githubusercontent.com/assets/19820721/18123860/bedd0d56-6f67-11e6-978a-e8f001a107f3.png) ![grid_active](https://cloud.githubusercontent.com/assets/19820721/18123867/c26448ae-6f67-11e6-8b2e-c0ea33e1546b.png) ![table_active](https://cloud.githubusercontent.com/assets/19820721/18123873/c609d1ea-6f67-11e6-9793-ea97367ebce0.png) ![3dcam_active](https://cloud.githubusercontent.com/assets/19820721/18123877/c8aefd08-6f67-11e6-8e07-981f719c2cac.png) ![cam_active](https://cloud.githubusercontent.com/assets/19820721/18123881/cafa830c-6f67-11e6-9f7e-b212609d651d.png) ![freeze_active](https://cloud.githubusercontent.com/assets/19820721/18123885/ce76d4b8-6f67-11e6-8010-007b916b2963.png) ![preview_active](https://cloud.githubusercontent.com/assets/19820721/18123887/d165681a-6f67-11e6-94bd-32ebb242791b.png) ![subcam_active](https://cloud.githubusercontent.com/assets/19820721/18123888/d3dbe40c-6f67-11e6-85aa-8fa464056498.png)

**Rollover**
![safe_over](https://cloud.githubusercontent.com/assets/19820721/18123926/00bba098-6f68-11e6-86cb-5b73fb882856.png) ![grid_over](https://cloud.githubusercontent.com/assets/19820721/18123929/03a9a160-6f68-11e6-96af-98c0f85fb46c.png) ![table_over](https://cloud.githubusercontent.com/assets/19820721/18123935/09903a94-6f68-11e6-8667-4360d3c086ea.png) ![3dcam_over](https://cloud.githubusercontent.com/assets/19820721/18123936/0b9e11a8-6f68-11e6-9376-8c2d4b31feca.png) ![cam_over](https://cloud.githubusercontent.com/assets/19820721/18123940/0e309ec2-6f68-11e6-970d-e540de76ca9b.png) ![freeze_over](https://cloud.githubusercontent.com/assets/19820721/18123950/1bb678b4-6f68-11e6-8747-fe6ee3fe7e69.png) ![preview_over](https://cloud.githubusercontent.com/assets/19820721/18123957/1edc8f92-6f68-11e6-87a3-e048cfb3bcd1.png) ![subcam_over](https://cloud.githubusercontent.com/assets/19820721/18123960/2160e25e-6f68-11e6-89aa-7cd3e768d42c.png)

**ZIP:** [ComboViewer_Icons_v2.zip](https://github.com/opentoonz/opentoonz/files/446875/ComboViewer_Icons_v2.zip)
