### ISSUE TITLE
Brush Tool: Stroke Stabilizer

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#81]
Toonz brush tool currently has no way of stabilizing strokes. A brush stabilizer is a value that slows down the tracking of the stylus in order to make it easier for the user to create broad smooth strokes as he/she draws them.
![tumblr_inline_o1y6kedf9x1so46vz_540](https://cloud.githubusercontent.com/assets/6495061/14077148/b4b62936-f4e0-11e5-9786-6c922c2e81cd.png)

To show some examples of this, here is tvpaint's line smoothing:
http://www.tvpaint.com/doc/tvp11/index.php?id=lesson-first-steps-drawing-tools-line-smoothing
![scraps3_by_omni_science](https://cloud.githubusercontent.com/assets/6495061/14077215/53e7bdc6-f4e1-11e5-9499-7b924fccda47.gif)

Here is lazy nezumi - an application dedicated to stabilizing strokes in other applications that lack the feature:
http://lazynezumi.com/
![lnppressurespeedscaling](https://cloud.githubusercontent.com/assets/6495061/14077176/fd8bcac6-f4e0-11e5-8504-63db063dd653.gif)

Example of how line stabilization works:
https://youtu.be/3Hc1bexva70

Some open source examples of this - so you can potentially take code from them:

Inkscape - MASS value
https://inkscape.org/en/doc/tutorials/calligraphy/tutorial-calligraphy.en.html
> In physics, mass is what causes inertia; the higher the mass of the Inkscape calligraphy tool, the more it lags behind your mouse pointer and the more it smoothes out sharp turns and quick jerks in your stroke. By default this value is quite small (2) so that the tool is fast and responsive, but you can increase mass to get slower and smoother pen.
https://fossies.org/dox/inkscape-0.91/calligraphic-tool_8cpp.html

Krita - brush stabilizer - it has three types of stabilizing. Here is an example:
https://userbase.kde.org/Krita/Manual/Tools/FreehandBrushTool#Smoothing
https://www.youtube.com/watch?v=zRxyyFcAbRY
http://www.davidrevoy.com/article261/line-art-tips-with-krita
http://osdir.com/ml/kde-commits/2014-06/msg02993.html

**Comment by walkerka** [comment]
The basic stabilizing is easy to implement but it's really hard to make it perfect. I have implement a simple smooth algorithm by averaging N samples of the stroke. It works but as the stroke points increase, the performance becomes worse. 

Here's my code. See "void BrushTool::DrawLastStroke()" function in
  https://github.com/walkerka/anim_builder/blob/master/brushtool.cpp

It also suffers from hard transition issue near the end of stroke. Because the start and end point positions cannot be changed, the smooth weight has to be weakened near the stroke ends. It looks like TVPaint's implementation also has the same issue. Maybe you could apply smooth multiple times to improve it.

BTW, Toon Boom's stroke smoothing is the best one I've seen. It doesn't require fast movement to support smoothing. You can draw really slow without any problem.

**Comment by walkerka** [comment]
From my observation, the "Accuracy" toolbar option is already some kind of line smoothing, although it still needs improvement. 
It's in "Window->Other Windows->Tool Option Bar". Smaller value gives smoother result.

The end point doesn't look so good even with 1 accuracy. I guess the pressure is unchanged by the smoothing algorithm.
Another issue is it sometimes generates acute turns in strokes. It's not easy to predict the output of low accuracy result.

**Comment by blurymind** [comment]
The accuracy value smooths lines after the stroke is made, so it is not
quite the same. The stabilizer assists you while you make the stroke and
you get a much more controlled and predictable result. It is particularly
useful for big strokes

**Comment by blurymind** [comment]
so the two have the same goal but take a different strategy to it. I personally find it easier to do with the stabilizer @walkerka, can you implement a basic stabilizer in toonz? Both for the raster and the vector layer brush tool?

**Comment by walkerka** [comment]
@blurymind I'm still struggling for understanding the huge project before I can change anything. And current priority of the project should be make it more stable than add any new feature.

I think we need dev docs supports for beginners. Some components diagrams will help a lot. The comments in code are in 3 languages: English, Japanese & Italian. (I have no trouble with first two but know nothing about Italian)

**Comment by blurymind** [comment]
@walkerka if you ever manage to get something running , I'd love to give it a try :+1: :)

Hopefully the code will get much needed cleanup and will also be ported to compile on linux

**Comment by walkerka** [comment]
I'm still busy on my project but I have some progresses on the smoothing algorithm. It fixed the stroke ends issue like TVPaint. If someone has time to work on it, here's my code for reference. 

Please note that my code redraws the whole stroke for every mouse update. It's ok for my OpenGL renderer but may be too slow for CPU rasterizer.

Test result:
![smooth](https://github.com/walkerka/anim_builder/blob/master/doc/stroke_smooth.jpg?raw=true)

`void Stroke::UpdateSamples()
{
    mSamples.clear();	
	for(int i = 1; i  < n; ++i)
	{
		StrokePoint& p1 = mPoints[i - 1];
		StrokePoint& p2 = mPoints[i];
		StrokePoint& p0 = i - 2 >= 0 ? mPoints[i - 2] : p1;
		StrokePoint& p3 = i + 1 < n ? mPoints[i + 1] : p2;

		StrokePoint::CatmulRomSpline(p0, p1, p2, p3, mSamples);

		if (i < n - 1)
		{
			mSamples.pop_back();
		}
	}
	if (mSmooth > 0)
	{
		// Applying 1D box filter multiple times will give much smoother result
		for (int i = 0; i < 3; ++i)
		{
			StrokePoint::Smooth(mSamples, mSmooth);
		}
	}
}

void StrokePoint::Smooth(std::vector<StrokePoint>& points, int radius)
{
    int n = (int)points.size();
    if (radius < 1 || n < 3)
    {
        return;
    }

    std::vector<StrokePoint> result;

    float d = 1.0f / (radius * 2 + 1);

    for (int i = 1; i < n - 1; ++i)
    {
        int lower = i - radius;
        int upper = i + radius;

        StrokePoint total;
        total.x = 0;
        total.y = 0;
        total.pressure = 0;

        for (int j = lower; j <= upper; ++j)
        {
            int idx = j;
            if(idx < 0)
            {
                idx = 0;
            }
            else if(idx >= n)
            {
                idx = n - 1;
            }
            total.x += points[idx].x;
            total.y += points[idx].y;
            total.pressure += points[idx].pressure;
        }

        total.x *= d;
        total.y *= d;
        total.pressure *= d;
        result.push_back(total);
    }

    for (int i = 1; i < n - 1; ++i)
    {
        points[i].x = result[i - 1].x;
        points[i].y = result[i - 1].y;
        points[i].pressure = result[i - 1].pressure;
    }

	// Insert extra points on stroke ends to fix abrupt size changes issue
    if ( points.size() >= 3)
    {
        {
            std::vector<StrokePoint> pts;
            CatmulRomSplineBySpacing(points[0], points[0], points[1], points[2], 2.0f, pts);
            std::vector<StrokePoint>::iterator it = points.begin();
            it++;
            points.insert(it, pts.begin(), pts.end());
        }

        {
            n = points.size();
            std::vector<StrokePoint> pts;
            CatmulRomSplineBySpacing(points[n - 3], points[n - 2], points[n - 1], points[n - 1], 2.0f, pts);
            std::vector<StrokePoint>::iterator it = points.begin();
            it += n - 1;
            points.insert(it, pts.begin(), pts.end());
        }
    }
}`

**Comment by blurymind** [comment]
@walkerka this looks awesome, but until i try it in OT, I wont be able to tell.
To be honest I would be happy even with a smoothing similar to tvpaint. I have used the one in tvpaint on a big project and it held up quite well.
I usually had it set up to something between 17 and 25

**Comment by walkerka** [comment]
@blurymind Sorry I don't have enough time to finish this feature currently.

From my testing, TVP, mypaint and krita use similar approaches to avoid redawing the whole stroke. As the stylus or mouse moves, the shape of the stroke is always changing. But the change is limited to the smooth ranges (defined by sub line segment count or distance). So the trick is only showing the stroke segments where the shape no long changes. 

The side effect is there will be a small part of stroke segments can't show until the whole stroke completes (when user release the stylus or mouse button). Krita's stabilizer discards these segments while TVP and MyPaint show these segments when user finishes the stroke. I also checked Harmony, it only applies the smoothing after whole stroke finishes.

My code is a brute force way and doesn't have this optimization. This is because my GPU based rendering code is fast enough to show smoothed stroke in realtime. The advantage is user have finer control but it heavily relies on a fast stroke rendering backend. Here's a demo of a more pratical use case. 
[https://youtu.be/u1iAOpjN84E](url)
I drew the figure with smooth radius 15. You can see the storke keeps changing so user can adjust their stroke acoordingly.

**Comment by blurymind** [comment]
Here is krita's in case someone is interested:

https://phabricator.kde.org/diffusion/KRITA/browse/master/libs/ui/tool/kis_tool_freehand_helper.cpp

**Comment by walkerka** [comment]
@blurymind Not yet. It's in my own anime editor. I'll try porting it to OT when I have more time. Will update here if there's any progress.

**Comment by blurymind** [comment]
@walkerka This is an incredible progress!
Does this work on the brush tool in vector or raster mode? it would be nice to have in both, but mostly in vector mode.

For the interface these are the suggestions I can make. 
- First of all we need a way to enable and disable this functionality on the brush tool- perhaps a tick box?
- Secondly when enabled, a new slider needs to become visible - "stabilize" - one that controls how slow the brush gets.
or it can be as you said - when enabled accuracy can be controlled by the brush speed.

Accuracy controls the number of points that are created on the stroke.
Perhaps it would be more flexible if accuracy slider does not control the stabilizer, but stabilizer has it's own controller.

Here is mockup 1:
![stabilizer-ot-mockup](https://cloud.githubusercontent.com/assets/6495061/15942684/56eb8298-2e7d-11e6-9fb1-b23ab8bad3be.png)

In it, when you tick stabilizer - you enable it. When enabled, a new drop down menu appears and lets you select a value for the stabilizer (similar to how paint tool sai's stabilizer works). I like this approach because it does not waste a lot of horizontal space.

Alternatively the stabilizer can be just an input- when it is set to zero, it is disabled:
![stabilizer-ot-mockup](https://cloud.githubusercontent.com/assets/6495061/15942752/adf661d4-2e7d-11e6-8af6-fbad3d586b33.png)

**Comment by blurymind** [comment]
Please decouple accuracy from the stabilizer amount.
Stabilizer needs to be controlled independently.

To retain the current prototype functionality you can go with mockup 1 or 2 and simply have one of the options of the dropdown list be "use accuracy" or "acc"

**Comment by turtletooth** [comment]
@walkerka This is awesome!

**Comment by turtletooth** [comment]
@walkerka I think that accuracy and stabilizer can serve different purposes and agree with @blurymind  on mockups 1 and 2.

**Comment by Emasoft** [comment]
@walkerka Holy shit, this is a magnificent new feature! Kudos to you!

**Comment by walkerka** [comment]
@blurymind I only added smoothing for vector now. It should be easy to port it to raster too. Now there're two things left:

1. Add a control to adjust the smoothing value. I prefer your mockup 2. I have not found the exact location to change but it should be somewhere in "tooloptions.cpp".

2. Fix a crash in TStroke.cpp. It sometimes crashes when I finish ths stroke. It looks OT converts strokes to Quadratic splines before rendering.

In "void computeQuadraticsFromCubic(const TThickCubic &cubic, double error, vector<TThickQuadratic *> &chunkArray)", the assert fails because "cs_sign" is less than 0.
    assert(!(cs_sign < 0) || acos(-sqrt(cs2)) > 10 * TConsts::pi_180);

I don't quite understand the algorithm of this function so if anyone is familar with it. Please tell me how to avoid the wrong input. The parameters are:
------------------------------------------------------------------------------
cubic
+		m_p0	{x=-96.292728088119091 y=-139.08880919302925 }	TPointT<double>
+		m_p1	{x=-95.989899503066681 y=-137.57465707825921 }	TPointT<double>
+		m_p2	{x=-95.687068583438844 y=-136.06050543039282 }	TPointT<double>
+		m_p3	{x=-95.384237031318179 y=-134.54635390902470 }	TPointT<double>
------------------------------------------------------------------------------
error	
2.0000000000000000	double

**Comment by kogaki** [comment]
@walkerka thank you for trying brand new feature! But It's hard to discuss on error or UI without seeing the code. Could you open `WIP(Work in progress)` PR for further discussion?

**Comment by walkerka** [comment]
@kogaki I created [PR #432 ](https://github.com/opentoonz/opentoonz/pull/432) for this.

**Comment by kogaki** [comment]
Thanks! We will check it out.

**Comment by walkerka** [comment]
@blurymind The nightly build has already merged this PR. The windows build looks ok (i5 win7 x64). But the mac build has brush lag issue on my MacBook Air (i5 El Capitain). I don't think it's a hardware issue. At least my own editor and gimp run well without any lag.

**Comment by blurymind** [comment]
@walkerka I am using it on windows 7 - 64 bit - and it looks like a charm!!  Smooth as butter and no lag :+1: 

I think we can close this feature request now. The lag on mac needs to be filed as another bug I think. @kogaki do you experience the lag as well- i think you were on a mac too?

**Comment by kogaki** [comment]
Today I tried on windows. It actually works in a little bit different manner. I'm not sure, but it looks that the cause of this is the difference of sampling rate of the drawing between two OSs. It results that confortable value of `Smooth` different according to environments.

**Comment by walkerka** [comment]
@kogaki The algorithm depends on input sampling rate because the 1D box blur radius is measured in sample count, not distance. Usually it doesn't matter. If you want to ensure consistent behavior across devices/OSes, the blur must be measured in distance. It requires more CPU resources.

The lag I found on MacBook Air is different. It looks the stroke is rejected very frequently. When it happens, no further stroke point renders. If the stroke is not rejected on beginning, the stroke renders without lag. (It looks smooth value doesn't matter). Sometimes the stroke becomes very thin, the width is always 1 pixel when zooming. Is it a zero width stroke? So I guess it's another Qt tablet related bug?

BTW the viewer is black on startup and doesn't show anything (even draw something on it). New combo viewer works though.

**Comment by Number0001** [comment]
Here are the good settings that are also worth shifting.
 https://www.youtube.com/watch?v=r9IEmInXLQM

**Comment by GuinnessWaller** [comment]
i just started using opentoonz 1.1.2 and there seems to be some kind of stabilizer that appears as a little red circle, does anyone know if this new feature is possible to turn on and off? thanks so much!

**Comment by Ceylo** [comment]
Hello,

I am not sure where this should go but this still looks like the most appropriate place. Given that OpenToonz is licensed under BSD, I have reused the smoothing algorithm that you wrote @walkerka to implement stroke stabilization in my drawing app for Mac, [ArtOverflow](https://artoverflow.io). The latest currently released beta doesn't have this feature yet, it should come in a few days.

My adaptations are published at https://github.com/Yalir/RawInputStabilizer partly to thank you and also because I guess other people could be as happy to find it as I was when I found your implementation.

Here are the changes compared to your implementation:
- Rewritten the implementation in Swift
- In generatePoints(), CatmullRom is used to add more points **only** at the ends of the stroke, this is to lower computation time when later averaging the whole set of points. Starting from 10K points, smoothing requires too much CPU time for real time output on a i7 8700K, so interpolating only at the stroke ends helps reaching this threshold much later. Additionally the stylus input rate on macOS is quite enough to get smooth results in the middle of the stroke (removing it at the ends give much less nicer thin stroke ends though, so it is kept).
- Added an asynchronous API. This helps leveraging multicore power while keeping the main thread free to spend its time on other work: GPU task scheduling in the case of ArtOverflow.
- Implementation of the Smooth() function is fixed to properly insert CatmullRom interpolated points at the beginning and end of the generated array of points. Original implementation was inserting the end points around 10 items before the end. From what I see [in this discussion](https://github.com/opentoonz/opentoonz/issues/81#issuecomment-223610225), you didn't originally had this bug, but [the merged version has it](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/tnztools/toonzrasterbrushtool.cpp#L708) because the variable "n" isn't updated 😁
- Added unit tests, although a significant part of the value of this stabilizer is visual appreciation of the output.

At some point I also tried to optimize the algorithm itself by caching previous smoothing results, as only the last points actually change. Empirically I could determine that it could allow to apply the average passes on the last 250 points only, instead of 10K points in some cases. So this is drastically more efficient. But I failed to make it work, it produced different results, so I gave up before losing too much hair and implemented the asynchronous API instead.

I still have thoughts about optimizing this multithread version: more precisely, now with asynchronous API, it is possible to compute the updated smoothed stroke by taking into account ALL the points that arrived while last smoothing computation was done. Instead of computing the whole smoothed stroke after each SINGLE point is added. It seems quite doable and should be ~5 times more efficient than the current implementation, but I unfortunately reached the point where I should stop optimizing and ship the feature as it works well already 🙂

So again thank you, and I hope my work will useful to someone at some point!
