### ISSUE TITLE
Nightly Windows build complains about missing libpng16.dll

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#821]
Several users on the Google Group and I have noticed that when installing the latest nightly it complains about libpng16.dll being missing.  Did something change around that?

**Comment by Rayek** [comment]
I can confirm this. I installed the latest build over the existing (working) version, and now it no longer works, and complains about that dll missing.

**Comment by shun-iwasawa** [comment]
@turtletooth @Rayek 
Sorry for the inconvenience. We found that this problem is possibly caused by libpng libraries for MSVC2015-32bit version. The above PR will fix them.

As a quick workaround, please try replacing the contents of `srv` folder with [the latest working version](https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_7cd1ff71f51a8b228efacaa3dce3e191e0c350af) or just removing `srv` folder (if you don't use MOV format / type tool / audio ).

@kogaki Could you please check if the modification fixes the problem and then merge it? Thanks.
