### ISSUE TITLE
Opentoonz won't open

### ISSUE THREAD

**Issue by JohnerOzlec** [opentoonz/opentoonz#830]
Hi, I just installed recently OpenToonz from my computer and upon finishing the installation and moving the so called plugins, The dang Opentoonz won't open. No introduction window was poping up like the one's from Adobe Photoshop, After Effects and Maya and no errors are popping up like nothing happen at all when I tried to open the program. Unlike crashes this one is different it really doesn't open the program and even tried open it with administrator.

I am using Windows 7 and it's a 64 bit operating system and has 8.00 GB ram and now I can't do anything. what should I do?

btw, I am using a Dell Home Computer and I wonder if thats a cause or something and the video card is NVIDEA GeFORCE GT 220, and I had my NVIDIA control panel installed.

Thanks for anyone who can solve the problem for me.

**Comment by RodneyBaker** [comment]
Sorry to hear of your problems.

I've helped troubleshoot a few other people's installation and based on that experience the first thing I would do is confirm the use of 64bit.  That is the number one reason OpenToonz won't work and... why it won't work on a older Win 7 laptop I recently inherited. (That's probably just as well though because it only has 1GB or RAM.

There was a report of some issues with NVidea graphics cards but a quick look in the forum didn't turn up that topic.  As I recall after settings were adjusted OpenToonz started playing nice.  You might look for posts from Alon Dan.  I think he was the one having the issue.

**Comment by RodneyBaker** [comment]
As a follow up.  I read in the forum that there are (primarily) two files that when renamed/removed solves the starting problem.

One file:  lvcod64.dll appears to be from TechSmith, makers of Camtasia, Snagit and a few other programs.
The other (I think) relates to Quicktime:  t32bitsrv.exe

There was another dll file I had to rename at some point but I cannot recall what that file was.  I believe that problem was resolved early on.

**Comment by JohnerOzlec** [comment]
Hey there Rodney, I would like to make a progress report this week and well you won't believe this story.

I was supposed to reply to you the other day while browsing every tip you said and then I found this link related to Opentoonz:

https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_build_win.md

So I took at read out of curiosity and try follow some bunch of instructions yesterday and last 24th. It's still a hustle for me to download Visual Studio Express that it took 7 to 12 Gb of additional storage. anyways I did follow the written documents and I am pretty unassure I did not completely follow 20% of it especially with the QT path and building up some folders on selective areas.

that day I tested it out it didn't work not until I reopen my computer today of all of sudden it worked.

![opentoonz suddenly worked](https://cloud.githubusercontent.com/assets/22337611/18837636/78ab7668-83d2-11e6-832d-3914a12a9df5.jpg)

well that's the evidence I have now and I got something important to go today so just to keep up this up for others whose having trouble with Opentoonz and I do not know whats going to happen next the next few days of my software should it work or suddenly not. 

Anyways Thanks I think I did 50% solve the problem myself. I just want to make sure if I am doing it right.

**Comment by RodneyBaker** [comment]
That's progress.  :)

I need to follow your lead and compile OpenToonz myself if for no other reason than to acquaint myself with  the process.

I do think that it can help to restart a computer from time to time (as many of of rarely do).  It helps to clear out the cobwebs and it appears in your case that helped.  I'm not sure how true a statement the following is but I think... Windows can keep some instructions in memory even though we aren't using the program associated with those drivers.  When we shut down Windows entirely this releases that code from memory so that when we start up WIndows again there is less opportunity for conflict.   So... a golden rule of troubleshooting would be:  If you've tried everything you can think of to solve a problem on your computer shut the computer down.... go take a walk.... find some trees... running water... breath in deeply.... then return and restart the computer.  We can be amazed to find that what  previously wouldn't work no matter what we tried suddenly is found to be working.

Keep at it and keep posting your progress.  :)
