### ISSUE TITLE
Vectorizing "self-colored" line-work done in other apps in OpenToonz

### ISSUE THREAD

**Issue by Amadhia** [opentoonz/opentoonz#840]
In my tests with the vectorizing portion of OpenToonz, I've not been able to get anything but black-lines when using the "Centerline" method.

Being able to use other colored lines to indicate Tone Mattes (Shadows) and Highlights is vital to many Trad. Animation pipelines, and though "GTS" appears to be able to handle this in scanned images, I have also not yet been able to get GTS to vectorize a .TIF image it didn't scan.

I've been using ProCreate (on an iPad Pro) to do development sketches and inked drawings for a little personal project I've got going on, and I like using the "self-colored-line" technique (where the ink lines themselves are colored -- as in Disney's Lion King).

To be able to get those images into OpenToonz for "painting", shadows and highlights, while retaining their Self-Colored Lines would be fantastic.

**Comment by RodneyBaker** [comment]
@Amadhia 
I'll have to investigate the centerline method... I've never cared much for use of centerline in any program (CorelDraw, etc.).  Have you tried the outline method? Making sure the option to preserve colored fills works wonders there.  I even use the conversion process to close some pesky gaps on drawings I create in OpenToonz (i.e. drawing in OT.... print screen and crop or render out.... bring back into OT.... convert to vector.... all gaps magically closed.

**Comment by RodneyBaker** [comment]
I should have investigated the centerline mehtod a bit more before commenting.
I am testing by drawing raster drawings in OpenToonz and then converting them to vector (mostly because that makes testing easier) but I've also converted with color from images generated with other programs.  

The centerline method is working pretty well for me and colored lines are transferring well.

So... we need more information on what isn't working for you.

The one thing I would double check:
Make sure you check the option to preserve painted areas.

**Comment by Amadhia** [comment]
@RodneyBaker Thanks so much for looking into this!

I've done every permutation of settings I can find in OT (v1.1.1 Aug8, 2016), and still I've not been able to pull an acceptable auto trace with self-colored-lines from the image (attached)
![image](https://cloud.githubusercontent.com/assets/22459808/18878510/ba143bd6-8485-11e6-9984-22aa73e44a5f.png)

Using Center-Line, I have been able to pull quite good Black-Only traces...

Using Outline, (and Preserve Painted Ares,) choosing even 3-4 "Max Colors" OT yields unusable results. (Choosing its own colors which includes colors it senses in the antialiasing.)

I imagine that if one could choose specific colors in the tracing (either Centerline or Outline methods), for example, by choosing a saved palette, like GTS appears to allow for, that would be ideal (like telling OT ,"Here are the colors in this character's approved palette... Please use them when doing your trace)....

However... It would still need to be traced with Centerline if one is going to use (for example) red and blue lines to indicate colored regions without outlines (eg: eye-whites in anime, Tones, Rims and Highlights).  (Otherwise when one flood-fills up to the  edge of the scanned, traced line that indicates the edge of the character's eye-white, when one eliminates that line, there's going to be a gap between the white of the character's eye and the skin-tone because the line is a volume and not simply a line. :/

What version of OT are you using in your tests?

Could you post screen-caps of your settings (especially if you fuss around what the test image I'm using, included, and get success?)

**Comment by RodneyBaker** [comment]
> What version of OT are you using in your tests?
> 
> Could you post screen-caps of your settings (especially if you fuss around what the test image I'm using, included, and get success?)

I mostly use Turtletooth's version of of OpenToonz as it has some Project setting/saving features that I like but I use the latest nightly build of the official OpenToonz as well... basically the latest release of OpenToonz I can find and dowload at any time.  I am getting to the point of trying to stabilize and standardize on one release and for that I tend to use the last official release (currently v1.1.1)  In short, because I'm testing, I use every version of OpenToonz that seems reasonable.  Luckily, I don't have a Mac or Linux installed or I'd be tempted to use those releases too.

I'll be posting screen caps (I've posted a few mostly tiny ones on my blog) but also plan to post some tutorial type explorations (I've got an unused youtube channel that needs to be put to good use).  I keep running into excuses not to do that so I'm doing shorter pieces in order to better familiarize myself with the various features of OpenToonz.  Sometimes I find a sweet spot and think... wow, I can draw... then I take a break and go away for awhile only to discover I've forgotten what drawing is upon my return.  hehe  Thanks to you I've been exploring raster linework in OpenToonz and have been enjoying the linework produced there (I like the grittier line that raster can produce.  The conversions to vector are immediate and can soften that linework but OpenToonz can use that again later as an overlay.  The converson process sometimes close all the gaps for coloring but sometimes don't.  More experimentation necessessary.  I'll try to post some of those explorations as videos.

In the sad news department... I was putting the finishing touches on a piece that more or less walked through the stages of raster to vector conversion with black, red and blue lines when I crashed Motion Monster.  Because I was using cloned levels that didn't save (a bug I think) I lost most of the setup... so it'll be back to the drawing board for that one.  That's what I get for ignoring the autosave notifications which at that time were set to 5 minutes.  I diligently cancelled each one as it interupted me and that might have saved the work.  I've since set it to 30 minutes and will consider if that is too long.

Here's what I really want to post back at you though...

In your drawing posted above (nice drawing BTW!) I see colors that might be problematic in the conversion because they are made of multiple colors.  This might be doable via the tolerance settings but if you draw with full red, full blue, etc. those can be converted to any color you want.  

I don't know what settings you are using nor what options you've explored but just in case... it may not be obvious but the color swatches in the raster to vector convert dialog (it starts with one but we add more via the plus icon) are controlled by setting the top of the color to the input color (that'd be from the raster image) and the bottom to the color we want the line to convert to in vector.  the default is to keep the colors the same so the example is black/black which makes that swatch look like one swatch rather than two.  Perhaps the UX folks could add a margin/border to make that a little more obvious.

Since you posted your issues I have been finding I like "centerline" a little more than "outline".  Given my experience with the centerline method in other programs I didn't think that would ever be possible.  OpenToonz does an excellent job and now I mainly just need to figure out where the sweet spots are in all the settings to produce the absolute best results possible.

Sorry for the long posts... a video capture of what I'm seeing would be better.  ;)

I'll be proven wrong here too... but at this point my suggestion would be to draw with full colors (not mixed, blended or partially transparent) so that OpenToonz can easily target that color for conversion.  Set the output color to anything you want (and in order to assist with easy fill of colors after the conversion).  Alternately, keep the same input and output colors but then adjust the colors in the pallet to the desired color after conversion.

**Comment by RodneyBaker** [comment]
I've been testing a lot of stuff of late and I see in the above I confused some things found in the Cleanup Process with those found in the Raster to Vector conversion process.  Sorry about that!

**Comment by RodneyBaker** [comment]
Here's a quick test with your image.
What may not be obvious...

I did NOT fill any of the areas.  This is exactly what the raster to vector results produced.

I ran the cleanup process first before the conversion process.
I toggle the Cleanup Preview to "On" first and if I like the results turn it back off... then run cleanup.

I *might* get better results without cleanup but I wanted to test the color changing swatches (which in this case I left the same (black/black, 
![colorcleanandconvert](https://cloud.githubusercontent.com/assets/2576432/18895040/3060063e-84dc-11e6-8093-2b2bc7554bd4.png)
red/red, blue/blue, yellow/yellow).

**Comment by RodneyBaker** [comment]
Note that the black swatch (in Cleanup) doesn't appear to allow changing to other colors like the other swatches.  I'm sure this is to preserve the all important black line.
![colorcleanup](https://cloud.githubusercontent.com/assets/2576432/18895213/8ab88358-84dd-11e6-9366-73f39152641f.png)

**Comment by RodneyBaker** [comment]
A second try...

Here I've overlaid the results of a black line conversion over the top of the color conversion using the colors that came through with the conversion with one exception (I added the green for her eye... no, I don't know why I did that).  The conversion got confused up in the hand/mic region and so the front arm and the background are part of the same color area.
![2ndtry](https://cloud.githubusercontent.com/assets/2576432/18896000/b2f20cf8-84e3-11e6-8201-f8522095a464.png)

**Comment by RodneyBaker** [comment]
Thinking outloud... 
Workflow-wise I cant help but wonder if working our lines completely in black might not be more advantageous.  If specific colors are desired for areas then we could just add a dab of color inside.
The only big benefit I see to drawing with colored lines (outside of indications for light, shading and effects) would be to get the color for overlaying of lines.  This can be accomplished without the conversion process especially since OpenToonz works well with use of both raster and vector layers at the same time.

Everyone has their own workflow but consideration should also be made for pressing into common workflow where others might join together on a project.  Working strictly with black line can help in these situations.  If the artist is solo all the way... not as important.

**Comment by Amadhia** [comment]
That's great testing!  I hadn't thought of using the ClanUp Room as a part of the process (since the drawing was in my mind "already cleaned/inked" :)

I had played with area (not center-line) vectorization settings in the Browser room and was able to get something similar to your first screen cap.  (Thanks so much for those, BTW, helps to much to see what you're seeing!) But wasn't able to restrict the vectorized areas to just be those of the ink lines either. :/

I agree with you... working with Self-Colored Lines is a pain.  It's usually done by a dedicated team of inkers from the clean-ups, strictly following an ink-line color-model sheet before it goes to over to the cel-painters.  I can only really imagine Disney/Dreamworks/etc going to this hassle/expense in a production...

(Running a production of pretty-much any size, I'd go with black line... or change the color of that black line to a single gray to soften the ink-lines if necessary.)

However, for promo artwork, posters and the like, I do like the look of Self-Colored Lines (see attached)... and a good vectorization of the line-work makes it able to be enlarged at the time of output as big as one would want, without having the image size be uber-huge.

(A lot of fans of animation-as-art who do Disney-inspired styles... like the artist/animator "Vivziepop"... do Self-Colored Line in their still/promo drawings... I could imagine they would go nuts over a platform-independent alternative to PaintTool Sai... especially if it were available on iPad Pro. ;)

![img_0048](https://cloud.githubusercontent.com/assets/22459808/18937544/0cf90fea-85a6-11e6-8416-e783d422d6e2.JPG)

**Comment by Amadhia** [comment]
By the way... I've not been able to convert an imported image (PNG or JPG) from a "Raster Layer" which doesn't seem to support flood-filling.

Have you any ideas where I'm going wrong?

**Comment by RodneyBaker** [comment]
Great looking image!  Now let's see her animated!  :)
In looking at that image I can see why creative types gravitate toward 3D over traditional and digital hand drawn animation.  That look would be considerably harder to achieve in animation with the lighting in the shot as well as the textures on the character.  Certainly not impossible and OpenToonz has the compositing and effects features necessary to make it work.  Either way it's a lot of hard work.

> I've not been able to convert an imported image (PNG or JPG) from a "Raster Layer" which doesn't seem to support flood-filling.

When you say 'haven't been able to convert' I'm curious if you get an error message with that .  It certainly should work.

I've not had any issues with converting PNG or JPG (raster to vector that is... not file type to file type which also works fine).  I do think that PNG is generally preferred because most JPGs tend to be more highly pixelated and lossy.  To make sure I wasn't just imagining those two formats worked I just tested PNG and JPG in the latest nightly release of OpenToonz and both convert to vector fine.  I did have to adjust the color tolerance with the JPG to keep strange artifacts from appearing which messed up the smoother lines.

**Comment by Amadhia** [comment]
Thanks so much! <33

Yeah, that image would be more like, for example, the cover artworks for the old Disney videotapes than a production still.  (Though... there are only two blurred shadow tone levels and one blurred highlight level on the character's shading, and the other effects are just blurred simple shapes as BG set to "bloom" into and FG layers set to Color Dodge

**Comment by Amadhia** [comment]
Thanks so much! <33

Yeah, that image would be more like, for example, the cover artworks for the old Disney videotapes than a production still. (Though... there are only two blurred shadow tone levels and one blurred highlight level on the character's shading, and the other effects are just blurred simple shapes as BG set to "bloom" into the FG layers [I think maybe the "Backlit" effect in OT may be able to do this?] and blurred simple shapes in the FG layers set to Color Dodge.  So... I think it would probably be quite possible... but with every line and fill taking time, unless one had an army of people lending their time to a project, it would be utterly unwieldy.)

And oh, I'm sorry I misspoke myself when I said "convert" an imported image, (I was being rushed out the door to get to my weekly jam-session. :P )

I meant that I am wondering how to use an imported image as a "Toonz Raster Level".  (So that it might be able to be flood-filled without going through the vectorization process.)

Whenever I've imported an image... though I've only tried with JPG and PNG... it's been brought into the project as a "Raster Level" (not a "Toonz Raster Level").

When I have tried to use the "paint bucket" (Fill Tool) or Paint Brush Tool on an (imported) "Raster Level", I get an error message saying, "The current tool cannot be used on a Raster Level".  (Those tools appear to only work on "Toonz Raster Levels" and "Vector Levels".)

I've tried to change the Raster Level to a Toonz Raster Level, (so the imported image could then be flood-filled without vectorization,) but have not found a way to do so yet. :/

I've also tried to copy part/all of the imported image (on a Raster level) onto a Toonz Raster Level, but that hasn't seemed to work either.

I'm importing the image through the Browser Room, by right-clicking on the image after I've browsed to it's location on the drive (outside of the project folder) and chosen "Load" (And "Expose in X-Sheet" on the "Screen Cast" section of the Browser Room if I've deleted the Layer in the X-Sheet and wanted to start testing from the beginning again.)

I'm just wondering if I'm doing something wrong in wanting to see if an imported raster image can be flood-filled as a raster image.

**Comment by Amadhia** [comment]
Oh!  Here's the first tech-test animation of Dream I did last spring:

https://www.youtube.com/watch?v=2GsAHlSmP9Y

There are a few other tests of different tech-aspects their on her YouTube Channel if you're curious.... I've been re-working her design away from the Anime / "human form with anthropomorphized animal elements" and into more traditionally cartoon animal designs, and should have the first pose-test of one of her band-members up on her Channel early next week.

Yeah... I miss drawing on paper so much... that's why I'm really excited about OpenToonz for possibly doing some things with my mentor just for fun! :D

**Comment by RodneyBaker** [comment]
(We may want to move this discussion to the regular forum as it may be leaving it's original topic's focus.  We don't want the developers to get distracted by the off topic stuff... they've got code to write!)

With regard to the video link you posted.
That's very impressive work.
While I know the standard answers to questions such as the following... 
The quality and extent of your work begs the question, "If you can do something like that in 3D then why bother with hand drawn animation?"   And you've supplied several of those answers yourself... artwork for covers (promotional work, etc.) as well as for working with your mentor... and. perhaps most importantly... to have fun.

To return to some of the detail you've provided.. you state you are using the Browser Room and I must admit that I rarely use the Browser in OpenToonz (although I expect to use it in the future (and I like that it can have a preview image to survey what a file is before loading it).  The primary reason I shy away from using it is that sequences of images with wrong kinds of filenames can be detrimental to OpenToonz staying open.   In other words... I have a lot of success dragging and dropping into the xsheet but not so much using the browser and Right Click/Load Level (via xsheet).  I've recently seen a little improvement when I make sure I generate a Project first.  This is possibly because I'm trying to open standard images when I should be trying to open .pli files (Toonz images).  I'm not overly concerned at this point because I can get images in via other methods.  Others don't seem to have the same import problem and it should be very obvious if they do... so... I'll be patient.

You said:
Whenever I've imported an image... though I've only tried with JPG and PNG... it's been brought into the project as a "Raster Level" (not a "Toonz Raster Level").

The first thing I would check would be to see if your preferences specify normal Raster format over Toonz Raster formatting (in the preferences).  That's the only thing that springs to mind.   In slightly related news... I note that when dragging and dropping a Toonz Raster into a Toonz Vector cell in the Xsheet it automagically gets converted to vector.... now that is entirely too cool.  I've been doodling sketches in OpenToonz lately, trying to find a sweet spot for brush work and I can see how that capabilty is going to be very useful.

I've been enjoying the discussion and I encourage you to post your work/links in the main OpenToonz forum.  Even a topic such as "Raster to vector conversions" should get some interest going.  

I suppose the question at hand... where are we with regard to your being able to convert "color lines" from raster to vector?  Is this an issue the developers can close?

**Comment by RodneyBaker** [comment]
Here is the only image I can find related to the demo I mentioned I was putting together.
I appreciate questions like yours because they get me to experiment!

![colorlinessm](https://cloud.githubusercontent.com/assets/2576432/19057251/2a199e68-8994-11e6-8a8a-261888a2ea51.gif)

**Comment by Amadhia** [comment]
Heya!  Sorry for the weekend-long delay, it was a busy one! :D 

Sorry to have jumped off-topic, (though I'm glad you liked the animation! <3 )

With regard to vectorizing pre-inked drawings with multiple colored ink-lines, I've not been able to find any successful solutions for Centerline Vectorization of an pre-inked drawing with Self-Colored Lines.

I should think it would be not too terribly difficult to add to the existing Vectorization code to be able to recognize a pre-defined Palette (as it seems GTS does?), since OT can Vectorize an imported image that has been "Binarized" so that it is only Aliased, Black, Red, Green, Blue, and White (Transparent)... ...and the vectorization of my test image after Binarization looked quite promising!

And yes, I would think that it would be an important thing to include... (the Centerline Vectorization of images with a pre-defined palette of Self-Colored-Lines)... because of the following:
- Centerline Vectorization is in my experience the best for animation clean-up.  (I believed that's what we used at the Traditional studios I worked early in my career.)
- Allows for same tool-set within OpenToonz to create promotional and packaging artwork as was used on the show itself to preserve artistic continuity
- Opens user-base to fans of animation who like to draw stills in animation/anime styles who long for an alternative to tools that are close-but-not-quite... and tools that exist on one OS but not others, (I'm still 100% wishing for an iOS port for iPad Pro! <333 )

-------------------
I did check my  settings and the default layer type is a Toonz Vector level (which is totally awesome for my tastes. :)

And no matter how and what I dragged... whenever I dragged a (non-Toonz) Raster Level onto a Toonz Raster Level, OT never allowed me to drag-and-drop the Raster Level frame/image onto a Toonz Raster Level... it always crated a new Raster Level and put the dragged image there.

Great image, BTW!  (That came up in my browser as I was typing... :)  Can't wait to see the demo when you are ready to share it! :D 

P.S.  I did get the new character design style _finally_ done... here's a link to the image on my Twitter feed so it hopefully doesn't clutter info for the developers! :)  https://twitter.com/my_amadhia/status/782989426758561792
--------------------

So... to sum-up...
- In OpenToonz, I've not been able to Centerline Vectorize an imported image wherein the Vectorized Ink Lines are colored ("Self-Colored Lines").
- It would be immensely beneficial for OT to incorporate the functionality wherein an end-user can specify a custom palette for Centerline Vectorization.

:)

**Comment by RodneyBaker** [comment]
>
> And no matter how and what I dragged... whenever I dragged a (non-Toonz)
> Raster Level onto a Toonz Raster Level, OT never allowed me to
> drag-and-drop the Raster Level frame/image onto a Toonz Raster Level... it
> always crated a new Raster Level and put the dragged image there.


Ouch.  Sorry about that.  I didn't mean to say "drag and drop" I meant
"copy and paste".

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
