### ISSUE TITLE
Crashing upon starting in Windows 10

### ISSUE THREAD

**Issue by Ningy909** [opentoonz/opentoonz#841]
I have the latest english build of Opentoonz (V. 1.1 is the newest on their website) and it constantly crashes before it even opens.  When I try to open the program, the Opentoonz normal startup logo appears and says 'Initializing Toonz environment' and freezes at that.  It stays that way until I click it and Windows says it has stopped responding.  I've tried leaving it alone and it'll just stay that way for hours.  I've tried every way to fix the problem (System32, ivcod64.dll, and even messing around with an older version of Opentoonz that has the same problems) but none of them have worked.  Does anyone know how to fix this?  All fixes I've found are for older versions and aren't working.

**Comment by RodneyBaker** [comment]
There are several things to try/test... but we should probably get more information on your system first.  You may have mentioned these elsewhere but it helps to have them all in one place so they can be considered/reviewed:

Here's what I think you are operating (please correct where I get it wrong):
Windows 10?  
64bit?
Fully uninstalled prior OpenToonz installations before installing the latest release?

I'll stop there so that we can establish that foundation first.

Hang in there and you'll be up and running soon.  :)

**Comment by turtletooth** [comment]
Closing since no reply.  If this is still an issue please let us know.
