### ISSUE TITLE
Delete Frames from Level Strip

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#855]
Does anyone know if it is possible to delete a frame from the level strip? On a Mac, the drawing itself deletes, leaving behind an empty frame.

**Comment by RodneyBaker** [comment]
Hi,
This is more of a question for the regular forum (LINK(https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting)) but. since we are here...    :)

Yes, we can delete the frame itself but not directly via the Delete key.
After selecting the frame or frames you want to remove, on Windows, Right Click and Select "Cut".
I assume the equivalent on Macs without the ability to Right Click this will be Command Click and then select "Cut".

Give that a try and see if that works.

**Comment by artisteacher** [comment]
I'll make sure to use the forum next time I have a question. Thanks, so much. Cmd-click then Cmd-X works!

**Comment by RodneyBaker** [comment]
The important thing is that it works!  
Keep on keeping on.  :)

Devs... it appears this issue is resolved and can be closed.

**Comment by shun-iwasawa** [comment]
OK, @RodneyBaker thank you for answering! I'll close this.
