### ISSUE TITLE
Program crashing with eraser tool.

### ISSUE THREAD

**Issue by SandDance** [opentoonz/opentoonz#860]
At the moment this can only be confirmed on raster mode but the program crashes if you quickly alternate between eraser and brush tools.
Example Using a wacom pen and you Alternate between eraser (back of the pen) and the point (front of the pen) quickly it will crash.

**Comment by ideasman42** [comment]
This is not enough information: please give *exact steps* (what you do to setup the scene, how you access tools in a way that crashes)

**Comment by TheGaluMoD** [comment]
I have also encountered this issue. here are the details:
Whenever you hold down whatever button you have the eraser tool set to, and then let go of the button before you are done erasing (so basically you are still touching the tablet with the pen) the program crashes. Obviously the expected behaviour is to continue erasing until you stop touching the tablet. The same thing also happens with the brush. So if you have the eraser tool selected for example, and then you hold down 'b' (or whatever you set the brush tool to), start drawing, and then let go of 'b' while still finishing a line, opentoonz crashes. I don't know if there are any other tools affected by this. The selection tool seems to not exhibit this behaviour, so it looks like it affects drawing related tools. Also it looks like it doesn't matter what level type you have selected (raster, or toonz raster/vector)

The best way to circumvent this issue atm is to not hold down a button when using a tool, but instead just tap it to switch to said tool, and then switch to the previous one when you're done. Of course you can also just keep holding down the button until your done erasing/drawing, however I don't trust myself to do that. I just instinctively let go of the button while erasing ^^

Also this is my first post here. I'm really thankful for this great software, and the amazing community surrounding it :) Great job guys! <3

**Comment by ideasman42** [comment]
Can this crash be done without a tablet?

**Comment by TheGaluMoD** [comment]
Yes, it's the same deal. You hold down the shortcut button, and then stop holding it down, while still pressing the left mouse button. For me those are all the steps required for the program to crash (without any type of error message, it just closes). I'm using Win10 x64.

**Comment by ideasman42** [comment]
Managed to redo:

- Run OpenToonz with the default startup file.
- Press S-Key once,
- Press B-Key, while held LMB drag to paint.
- Without releasing the left mouse button, release the B-Key.
- Notice the brush stroke isn't executed properly *(doesn't draw at all or draws wrong color, for others it may crash)*.

I didn't manage to get a crash, but it does cause some strange half-finished brush state to be left.

Probably this isn't so hard to fix, just need to delay the key-release action once the stroke is finished.

**Comment by TheGaluMoD** [comment]
I can confirm that on Win10 it also does not crash when having the select tool selected and then holding the brush key. It only results in an unfinished brush. However when you have the brush selected and then hold down the eraser key or vice versa it does crash

**Comment by turtletooth** [comment]
Are there any steps to consistently make it crash.  I can't get it to crash to see what needs to be changed.

**Comment by turtletooth** [comment]
Got it to crash using brush tool then holding a for eraser and letting go before I finished erasing.  Same thing with the hand tool (let go of space before panning) - raster levels.  I can see how this might be easy to trigger.

**Comment by turtletooth** [comment]
@blackwarthog You are probably the resident expert on raster levels here.  Any idea on how to stop tool switching if a tool working (brushing, erasing, panning. . .) or to end the action before a tool is switched?  There's probably a onToolSwitched signal, but I'm guessing by then it'd be too late.

**Comment by blackwarthog** [comment]
We can check mousestate in function `ToolHandle::setTool` (tnztools/toolhandle.cpp:36)
For example we may add: `if (QApplication::mouseButtons()) return;` But it produce artifacts in GUI - toolbox shows wrong selection. Also we can to call `m_tool->leftButtonUp/Down`, but we should to know mouse coordinates.

May be in future would be cool to separate functions for event-call and event-handle, and make events cascaded.

**Comment by turtletooth** [comment]
@blackwarthog I submitted a PR #1228 - I'm not sure it's the best way to go, but it works.
