### ISSUE TITLE
[FEATURE Request] Add the option to display text labels on each icon to improve usability

### ISSUE THREAD

**Issue by Emasoft** [opentoonz/opentoonz#864]
Icons in OpenToonz are too criptic. I don't understand what they mean. 
We need OpenToonz to have the option to display a text label below every icon, like many professional programs do. Usability can be improved only with a "label+icon" UI.
OpenToonz UI is already very hard to learn and understand. 
Having also Icons without labels is a very stupid way of shooting ourselves in the feet.

![schermata 2016-10-16 alle 22 21 02](https://cloud.githubusercontent.com/assets/713559/19420603/e6b58afa-93ee-11e6-9708-e7819a16ba87.png)
![schermata 2016-10-16 alle 22 20 14](https://cloud.githubusercontent.com/assets/713559/19420602/e6b4926c-93ee-11e6-8b6c-1a0f7686e47c.png)

**Comment by blurymind** [comment]
Having labels everywhere will potentially make the whole interface super
cluttered.
Can you make a mockup of how the OT gui will look like in that mode?

Icons are very obvious in what they do, but I think they can be improved in
a number of other ways for clarity.

For example the toolbar can be context sensitive and only show tools that
can be used for the active level:
https://github.com/opentoonz/opentoonz/issues/343

**Comment by RodneyBaker** [comment]
I know you didn't mean it in a harsh way but it's probably best not to not to categorize any development on OpenToonz as 'stupid'.  I've noted several people using similarly demeaning words to refer to earlier development work that besides being rude doesn't justify treading on the hard work that others have put into OpenToonz to get it to where it is today.  Something might need to be improved... something might even be broke... but the best way forward is not to spit on people that have brought us to this point.  And besides all that... using that language is a pretty sure way to get a request ignored.  

To weigh in on the subject... I'm a big fan of context sensitive menus, especially via Right Click and 'tool tips'.  Hovering a mouse over an icon and getting more information about that icon is generally sufficient to remind us what that icon represents.  Moving to the next level of understanding is usually going to require selecting that icon/pushing that button and exploring the possibilities.

**Comment by Emasoft** [comment]
What I meant is that it is against out interest making the UI even harder to decode.

And Icons+Label are the best design choice, as every usability expert knows. When the OpenToonz UI was designed, usability was not even a science. Making "wall-of-icons" was the usual practice at the time, because they didn't know better. Today UX Design is an academic course in many universities and UX designers are most wanted by software companies.

Here are some quotes from usability studies, papers and reference articles:

* "Icons are notoriously ineffective as labels, being very difficult to interpret correctly without training or experience. For most situations, users learn correct interpretations better with text alone than with icons alone." - _Wiedenbeck, S (1999) "The use of icons and labels in an end user application program: An empirical study of learning and retention. Behaviour & Information Technology, 18(2), p68-82._
* "Icons are especially bad for anything abstract, since abstract things generally do not have any strong visual image. Similarly, icons are particularly bad for actions; it’s hard to clearly show a process with a static picture. Users are frequently confused by icons on toolbars: on average, users know only six Word toolbar items after regularly using Word for two years."
* "Icons can save space over text, but at the price of recognition. For small icons, such as 16x16 pixel, it’s very difficult for users to even recognize what they are supposed to be a picture of, let alone what the picture is supposed to stand for. One user thought the “disk” icon for save was a picture of a TV. Another used Word for years thinking the Track Changes icon was a stylized Rosetta Stone. Expert users find it easier to rely on the memorized physical position of the toolbar controls rather than the icon labels to pick a control." 
* It’s extraordinarily difficult to get icons right. Do not attempt to develop a new icon without extensive iterations of user testing. Even then, you may fail. Microsoft designers tried everything to make interpretable icons for Outlook’s toolbar before giving up and going with text labels on key controls.
Icon labels also make tech support insanely difficult (e.g., “Click on the yellow sheet with a blue checkmark,” versus “Click on ‘Accept’”).
* "Tooltips are required for icons when they are used alone, but they are a poor substitute for text labels. Your users shouldn’t have to use your app by groping around for things. The fact that text labels never need graphic tooltips is a pretty good clue that text is better than icons."
* "Icons combined with text work always best. A user’s understanding of an icon is based on previous experience. Due to the absence of a standard usage for most icons, text labels are necessary to communicate the meaning and reduce ambiguity." - From the Neilson/Norman group study on icons usability.
* To help overcome the ambiguity that almost all icons face, a text label must be present alongside an icon to clarify its meaning in that particular context. (And even if you’re using a standard icon, it’s often safer to include a label, especially if you slightly altered the icon to match your aesthetic preferences or constraints.)
* Icon labels should be visible at all times, without any interaction from the user. For navigation icons, labels are particularly critical. Don’t rely on hover to reveal text labels: not only does it increase the interaction cost, but it also fails to translate well on touch devices.
* As we stated as part of our design guidelines for homepage usability years ago, if you find you need to ponder to come up with an icon, chances are it’s not going to be easily recognizable or intuitive for users. Stripping icons of text labels renders them completely meaningless and is counterproductive to the goal of providing easy access to content.
* Many researchers have shown that icons are hard to memorize and are often highly inefficient. The Microsoft Outlook toolbar is a good example: the former icon-only toolbar had poor usability and changing the icons and their positioning didn’t help much. What did help was the introduction of text labels next to the icons. It immediately fixed the usability issues and people started to use the toolbar. In another study, the team of UIE observed that people remember a button’s position instead of the graphic interpretation of the function.
* In most projects, icons are very difficult to get right and need a lot of testing. For abstract things, icons rarely work well.
* UIE conducted two experiments to test how people use icons. First they changed the pictures of icons in a toolbar but kept them in the same location. People quickly adapted to this change. Afterwards, they kept the images but shuffled their location in the toolbar. This change confused the participants and caused problems for them. - Orbitz Can’t Get A Date. More on the importance of icons’ position in Did you move your users’ cheese?
* Michael Zuschlag says that “icons contrary to intuition, do not necessarily help the user find a menu item better than a text label alone (see Wiedenbeck S 1999. The use of icons and labels in an end user application program: an empirical study of learning and retention, Behaviour & Information Technology, 18(2), p68-82). It’s not worth it.” He also discusses his views on UX Exchange.
* The story of the Microsoft Outlook toolbar: until labels were added to the icons, non-expert users didn’t use the toolbar’s buttons at all (with the exception of the ‘Delete’ icon). Then “Different fixes were tried: new icons, rearrangement of the icons, positioning icons under the menus from which the commands came from. In the end, one change caused a total turnaround: labeling the important toolbar buttons. Almost immediately, the toolbars were a big hit and everyone at all skill levels started using them.” - The Importance Of Labels
* A user’s understanding of an icon is based on previous experience. Due to the absence of a standard usage for most icons, text labels are necessary to communicate the meaning and reduce ambiguity. - Icon Usability
* Nothing says “manage” like “manage”. In other words, in the battle of clarity between icons and labels, labels always win. - Labels always win.
* “When in doubt, always remember this: the best icon is a text label.”
* The article The Problem With Icons provides a nice example how it’s difficult to guess an icon’s meaning without a text label next to it.
* 37signals applauds Apple’s MobileMe service for changing their logout icon from a power button to a “logout” label. - UI Sighting: Clear over clever on MobileMe
* Peter Steen Høgenhaug conducted a test to measure how people understand icons of a CMS editor. The result: the widely used 'insert link’ icon was understood only by 35% of the participants, even the classic 'undo’ and 'redo’ icons were only recognized by half of the participants.
* “In our study, we found that for icons with labels, users were able to correctly predict what would happen when they tapped the icon 88% of the time. For icons without labels, this number dropped to 60%. And for unlabeled icons that are unique to the app, users correctly predicted what would happen when they tapped the icon only 34% of the time.” - Hannah Alvarez, UserTesting 
* “To help overcome the ambiguity that almost all icons face, a text label must be present alongside an icon to clarify its meaning in that particular context.” “Use the 5-second rule: if it takes you more than 5 seconds to think of an appropriate icon for something, it is unlikely that an icon can effectively communicate that meaning.” - Aurora Bedford, User Experience Specialist 

Links:
https://www.nngroup.com/articles/icon-usability/
http://uxmyths.com/post/715009009/myth-icons-enhance-usability
https://www.usertesting.com/blog/2015/08/04/user- friendly-ui-icons/

**Comment by blurymind** [comment]
So much precious screen estate wasted :). These studies assume that the
user is not very intelligent and incapable of learning new visual signs

**Comment by Emasoft** [comment]
@blurymind : Are all the people struggling to learn OpenToonz "not very intelligent"? I don't think so. Usability exists for everybody. And you cannot just ignore it because you already learned how to use an application. A step learning curve is a barrier for everybody, and very few people have the time and the patience to indulge a badly designed UI.

**Comment by blurymind** [comment]
@Emasoft no need to insult the current design. It is pretty good compared to some of the proprietary industry standards out there..
You should try using Maya or toonboom :) 

actually most proprietary software out there does not have the feature you are asking for- so its not something standard. Your screenshot looks like something that came out of the 90ies kde

**Comment by ideasman42** [comment]
User interface issues are typical things people will disagree on with no real conclusions.

These kinds of topics will keep coming up - so we should really have some procedure to handle them. (unless we want to have many open UI topics).

And reminder that there is for sure more than one way to design an effective UI, different methods having their own trade-offs. It's unlikely one solution will make everyone happy.

Suggest to

**Comment by RodneyBaker** [comment]
Thanks for dialing the rhetoric back.  :)

To cut to the chase, here's a quickly put together example of how the addition of text might look next to the icons.

![icon with text example](https://cloud.githubusercontent.com/assets/2576432/19438163/1fcb2508-943e-11e6-9d08-0f4480ae803e.png)


I have many reservations against adding text where none may be necessary but there are certainly good reasons to have it.  It is especially useful during initial exposure... learning phase... but less so afterwards where shortcuts are preferred to be taken.  These shortcuts include the shortcut keys as well as the icons themselves.  Once shortcuts are learned, the presence of text becomes unnecessary.  This echos the theme of 'universal' signs and symbols which are recognized either with or without accompanying text.

One approach might be to allow users to select from 16x16 icons or 16x64 where the wider icon includes the text.

Of note is that this approach works fairly well when the icons are vertical but wouldn't work as well if at the top running horizontally.

The underlying issue to me is that added text does not automatically tell the user what the icon represents.  The user then may have an icon with text and still have little or no idea what to expect.  That knowledge can only be gained by clicking the icon and seeing the outcome for oneself.

**Comment by VidelXi** [comment]
The icons are self explanatory to me. It's no trouble pulling up the tool tip every now and then when I need reminding of something, it literally takes 2 seconds, shorter than that "5 second rule" mentioned in one of those articles.

Is that really so much effort?

**Comment by blurymind** [comment]
Baking the text label into the icon file would make it impossible to
localize to different languages

**Comment by Emasoft** [comment]
@RodneyBaker Wow, that mockup is a dream! That would be SO MUCH BETTER that the current UI. Please improve the UI like that. That will finally stop me wasting time trying to guess icons all the time! No more migrains!

And about the text labels being too short for automatically tell the user what the icon represents: the solution is the one used by many applications, and it is the use of category labels. That would create a "context"+"toolname" information, enough to guess what the button does in practice.

For example the "Pinch" icon, would be put inside the "Deform" section. So in such context the user really reads: "Deform [with the] Pinch [tool]".

I added a couple of categories (Measure and Deform) to your mockup as an example:
![opentoonzmockupiconslabels](https://cloud.githubusercontent.com/assets/713559/19476863/aeabf542-953b-11e6-9d09-bf37797680ac.png)

**Comment by blurymind** [comment]
I think that while it looks nice on a screenshot, I would much rather have that wasted label space to the canvas instead.

Horizontal bar labels will potentially eat vertical space, which is even more precious

**Comment by Emasoft** [comment]
@blurymind The labels would be OPTIONAL, of course. If some experienced user like you choose to see icons without labels, he must be able to see only that. But you can't force all the people to go through the pain and the hassle of learning OpenToonz the hard way. Time is money, and many artists do not have much time to waste in learning a cryptic UI, or in moving the mouse pointer on all icons and toolbars to scan the tooltips everytime you don't remember where a certain function was.

**Comment by blurymind** [comment]
I hope you are not suggesting that having labels should be the optional
mode xD
oh god

**Comment by blurymind** [comment]
" ...you think your users are idiots, only idiots will use it."
~Linus Torvalds
https://en.wikiquote.org/wiki/Linus_Torvalds

**Comment by automated-reckoning** [comment]
This seems like much ado about nothing. I do not know of a single program that uses text on top level icons. It breaks a lot of UI conventions for nearly no gain, since as others have mentioned the text doesn't really explain anything unless you already know what it does.

The closest thing I can think of to what you want is ensuring that the menu bar options that mirror toolbar functionality have the same icon. Then, when you're unsure where the option you need is you drop down a likely menu and are reminded of what most of the icons are for.

**Comment by adamearle** [comment]
Hi

This is great for beginners. I am wondering how minimal can we get for
advanced users?


*Adam Earle*
*Phone:* 0431799431
*Google Hangout: * MrAdamEarle@Gmail.com
*Email:* MrAdamEarle@Gmail.com

**Comment by pocketviz** [comment]
Most of the icons have text when you hover over them already. Why would this be better?

**Comment by RodneyBaker** [comment]
@pocketviz  queried:  
Most of the icons have text when you hover over them already. Why would this be better?

@Emasoft pointed to several references where UI/UX experts suggest the use of icons with titles is preferred to other alternatives (icons alone, text alone, icons with tool tips, etc.)

I get the point but also recognize how the adding of text would dramatically change the current program as well as take up considerable screen space.  @Emasoft would suggest this would be for the better.

From a practical approach adding text would seem appropriate in a few cases.  I can think of at least two. with the first being that of a 'kid's version' or 'learning edition'.  The second would be in an effort to move OpenToonz toward mobile platforms where (unfortunately) screen space is even more restrictive.

Others have pointed out potential pitfalls, alternative perspectives and contrary views.
@adamearle 's suggestion points in the other direction... acknowledging usefulness but hinting at an interface that for hard core users would not even require icons or text... only shortcut keys (sorry for expanding on your query @admamearle I'm just taking your consideration of minimization to its full  conclusion).

Feature requests of this sort are those that certainly can be incorporated but require a champion (developer) to take them on.  This might take on the form of a branch of OpenToonz that targeting beginners or run on a smartphone.  My view here is such a branch would likely strip a lot of functionality out of OpenToonz and take on the form of a simpler animation sketching program, thumbnailer or asset organizer.

So to the question of 'Why would this be better' we can assume the answer to be that the user doesn't have to ever guess what an icon represents as (basic) title of that function is placed there along side the icon.

While I see the purpose and potential of such an addition, my personal take is that adding a title largely defeats the purpose of using icons in the first place which is to quickly navigate via use of symbols without reading any text.  

The crux of the matter appears to be that of a need to memorize what a specific symbol represents in cases where they are not 'universally' recognized.  At issue here would be the fact that many processes themselves in animation are not universally recognized themselves.  For instance, even an icon with text that states 'onion skin' would likely be confusing to someone who has not been exposed to that reference.  So learning must take place.

People proceed differently while navigating in a program and I find my own process to be mostly spatial.  My muscle memory recalls that an icon at the bottom of the menu initiates the 'Plastic Tool' and so I go there and (almost) instinctively click it (barely noticing the icon's image).  In this case the icons are there mostly to ensure I don't select the wrong icon by mistake because I know I'm not looking for them... no... not that one.... not that one... aha!  There it is!   I can't quite see how the addition of text would improve this situation but can easily imagine how its addition could slow down the process of selection even if only incrementally.

In the references @Emasoft posted I think it easy to see the wisdom in the advise to add text to icons.  The benefits are very clear and evident.  This does not however mean that it would be wise to add the text without considering the purpose and the target audience for that addition or of how it might effect the program as it currently is and its current users.

All of this suggest to me that any development in this area would likely target a branch of OpenToonz specifically for beginners compatible with mobile platforms and that would be a considerable undertaking.  The way forward here might take on the form of a continuity line where at one end of the scale are huge icons with descriptive text underneath while at the other end of the scale OpenToonz would have no icons whatsoever; the goal being to have everything automated and con-textual with shortcut keys the primary means for professionals to navigate on a desktop.  The first might be for use by our left brain with the latter used by our right.   :)

 

.

**Comment by blurymind** [comment]
I think it will be a complete waste of developer resource and will handicap usability -reducing massively the actual canvas area.

There are many more critical things missing in opentoonz at the moment

**Comment by turtletooth** [comment]
Closing this- general consensus is that it is not desirable, and I doubt any developer is going to take this on.
