### ISSUE TITLE
Terms of Use in conflict with license??

### ISSUE THREAD

**Issue by omouse** [opentoonz/opentoonz#87]
The binaries download link has a terms of use; how does that square with the license of the code? https://opentoonz.github.io/e/download/opentoonz.html doesn't that make it non-free/non-open source to some extent? or is it similar to whatever Mozilla has as a terms of use for Firefox?

**Comment by scribblemaniac** [comment]
I'm no legal expert, and I can't read japanese, but since this project uses new BSD, the only clause that is really applicable here is:
- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

So as long as they reproduce the copywriter notice and put the bsd license in any materials provided with the distribution, they should be able to do whatever they want with it, including adding additional terms.

**Comment by ideasman42** [comment]
Agree with @scribblemaniac 's conclusion, but the Eula continues to contain some strange requirements, eg: *"inappropriate acts judged by Dwango."*, wouldn't it be better to leave this open until the issue is resolved?

**Comment by turtletooth** [comment]
I can see what you are saying.  I closed this since the BSD license and the EULA were separate and cover different areas.  I was also trying to clean up stale issues.  But I don't mind leaving this open to hopefully eventually receive some clarification about the phrasing.

**Comment by ideasman42** [comment]
@turtletooth - agree and thanks for closing various inactive issues. Even though I suggested keeping open, I don't really have a strong opinion on this topic - would just be nice to replace the Eula with something less restrictive.

Its unfortunate github can't separate project-level issues from regular bugs.

**Comment by Aspie96** [comment]
It looks like Visual Studio code.
Just because the source is free, it doesn't mean that the binary version is free also.

You should compile from source.

@turtletooth I STRONGLY disagree with closing this issue. If having binary and source under different licenses is intended (which is perfectly fine), it should be explicit, again see the VS Code example. The parts of the source under BSD license are clearly open source, and forever will be, even if the license is changed.
@ideasman42 The EULA likely isn't necessary to begin with. The BSD license is a perfectly valid license for software. If anything, it is likely MORE valid than the current EULA: because it is widely used, it is has been widely studied and is well-understood.

The current EULA defenitely doesn't apply to the source code, which is mostly under BSD and it looks like it applies to the distributed binaries. Obviously, a user can just download the source and compile it from scratch: in this case they will be able to reject the EULA and still leagally use the program. Again, all of this is perfectly fine.
But is it really the intention? If so, it should be stated clearly as the current situation is extremely confusing. If it is not the intention, the EULA should be replaced with the license.
Even better, the EULA should be replaced with the license, but the third-party licenses, instead of being referenced, should be copied verbatim in it. Why? Because a user installing the binaries likely will never read the source code, but still need to read this terms.

I realize I am responding more than 3 years later, but the issue is still true currently. An old issue shouldn't be closed because it didn't get resolved.
