### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#881]
- [x] **Palette Window White Accent**

Non-stylable, a big annoyance.

This is also present in the **Style Editor Window**.

![fix16](https://cloud.githubusercontent.com/assets/19820721/19606660/c5c6315c-97bb-11e6-94a1-dd3056f35de2.png)

---
- [x] **Autocenter Alignment**
1. GroupBox doesn't line up with the other boxes.
2. CheckBox isn't being styled.

![fix1](https://cloud.githubusercontent.com/assets/19820721/19606300/41cc2962-97b9-11e6-8d38-160e054f08ff.png)

---
- [x] **Autosave Checkbox**

Missing style.

![fix2](https://cloud.githubusercontent.com/assets/19820721/19606379/b8e33cac-97b9-11e6-9544-2f47b5176d71.png)

---
- [ ] **Startup Window Check Label**

Changing the style or removing it shows the label is too narrow.

![fix4](https://cloud.githubusercontent.com/assets/19820721/19606425/193c0a34-97ba-11e6-874c-3b3d23ceb49b.png)

---
- [ ] **Cleanup Settings Window: Despeckling QLineEdit Gets Cropped**

![fix5](https://cloud.githubusercontent.com/assets/19820721/19606442/3bc1ac62-97ba-11e6-9ce5-d32a1508acb7.png)

---
- [ ] **Miter QLineEdit Gets Cropped**

Found under...
1. Brush Options
2. Selection Tool Options
3. Geometric Tool Options

![fix6](https://cloud.githubusercontent.com/assets/19820721/19606471/7606097c-97ba-11e6-828c-57fd8f0bbc98.png)

---
- [ ] **Geometric Tool Polygon Sides QLineEdit Gets Cropped**

![fix8](https://cloud.githubusercontent.com/assets/19820721/19606529/d21e6aa6-97ba-11e6-9804-5d016cd4efe0.png)

---
- [ ] **Pump Tool Accuracy QLineEdit Gets Cropped**

![fix10](https://cloud.githubusercontent.com/assets/19820721/19606564/1cb9e202-97bb-11e6-8c45-0619be98d2a0.png)

---
- [x] **Double QSlider Has Hard-Coded Styling**

AKA: #IntPairField / #DoublePairField.

![fix11](https://cloud.githubusercontent.com/assets/19820721/19606583/37f593a4-97bb-11e6-8b4d-3e43df6f2055.png)

---
- [ ] **Camera Capture Multiple QLineEdit Crops**

![fix15](https://cloud.githubusercontent.com/assets/19820721/19606621/848edb94-97bb-11e6-877e-4105c6143555.png)

**Comment by turtletooth** [comment]
@konero I was playing with the double pair slider.  And made sure all the colors were accessible in qss.  
However, the box outline is hard coded via drawn pixels.  Because it is a custom UI element and not a standard qt element, the only way I can think of making the round vs square corner an option is to break each side into two pieces (4 total) - two would be the color for the pixels needed for the rounded look, and the other 2 would be the pixels needed for the square look (which can be made to blend in with the background).  Currently the other sliders use rounded for the two darker themes and squared for the lighter theme. 

I personally prefer the softer look, but the above proposal allows the styling to go both directions.  This also adds some complexity, but I don't know another way to do it and give the freedom to style it in qss.

What are your thoughts?  BTW- Hope you are doing well.  Haven't seen you around here lately.

**Comment by turtletooth** [comment]
Here's a picture with the softer look:
![doublepair](https://cloud.githubusercontent.com/assets/4576381/22715169/019271a0-ed4d-11e6-8e48-9e6b28989eff.PNG)
