### ISSUE TITLE
Please create an "OpenToonz Developers forum" Google Group

### ISSUE THREAD

**Issue by justinclift** [opentoonz/opentoonz#93]
Please create an "OpenToonz Developers forum" Google Group. :smile:

The OpenToonz Users form is a good place for discussion & collaboration by OpenToonz end users:

&nbsp; &nbsp; https://groups.google.com/forum/#!forum/opentoonz_en

There are a lot of people actively working with the OpenToonz source code, so it would be very beneficial to have one for developers too.

**Comment by m48** [comment]
Until there is a forum for more general purpose development discussion, what type of topics do you think are acceptable to bring up in the GitHub issues tracker? How welcome are, say, feature requests/UX improvement ideas? Or should the issue tracker *just* be for bugs?

**Comment by odysseywestra** [comment]
So far, Feature Request/UX improvements ideas are okay to add as long as you have a solution to implement it. 

The only thing I would advise not have on the issue tracker is user support issues. That is more fit for the google groups forum.

**Comment by m48** [comment]
Okay. Sounds good. I'm going to ask for some clarification, though, to make sure I don't irritate people, and to set some ground rules.

What would constitute a "solution to implement it"? Having a clear idea of the scale of the change and what parts of the codebase would need to be addressed? Or being willing to code it yourself?

And what would constitute "user support issues"? Would that be threads that are more like "how do I do this" than "the program is weird in this specific way"?

**Comment by odysseywestra** [comment]
Actually it might be best to use IRC if what you are looking for is for developers and contributors to communicate to each other in real time. Another alternative is use [Gitter](https://gitter.im/) which integrates into Github. However for that kind of functionality, it requires one of the lead developers to create one that connect to this repository. Sadly I can't do it.

However that doesn’t mean we can create our own channel with Gitter till they create it.

**Comment by justinclift** [comment]
IRC is a reasonable idea in some situations, but most developers aren't familiar with it.  It's also not a great solution for distributed teams (eg multiple time zones).  Note - I am familiar with IRC, and have been in jobs where it was required.  The timezone thing really sucks. :wink:

Gitter I'm not yet familiar with.  It seems to be another chat style thing (eg IRC, but web based).  Does it have full, searchable history functionality like mailing lists or Google Groups? :smile:

**Comment by 3Rton** [comment]
Generally speaking I don't think the ratio of coders to artists is big enough yet to warrant entirely dedicated group, especially since the main forum just got cleaned up and seems like it'll be good to build on. However, if you truly feel it's necessary for this phase of cleaning the initial build of bugs and fixing stuff I guess your best bet is to contact Yuri directly about it. I still think it's over excessive, though, and divides the community for no major gain.
Gitter sounds good, though, that should definitely be forwarded to the mods. Also perhaps ask for them to add developer sub-thread to the new organization? The troubleshooting seems to be more of a bug/user error thread. The feature request seems to be more of a "well we could have something like this to do X-job which concurrently we are doing with Y-work around". So we could use a developer thread just for purely talking about implementation. Just my thoughts on it, though. 

Regardless which way we go I think we should do what Westra said and get this closed asap. There is going to be enough bugs on the issues folder as is without not so code related issues we might have with organizational stuff. I could contact Yuri and ask her about opening a Gitter and inserting thread for Development on the Users Forum? Or if you'd rather go the independent forum path you can contact her too, should still probably mention the Gitter, too.

**Comment by justinclift** [comment]
@3Rton Ahhh, hadn't seen the new reorganisation of the google group.  Looks like it's been subdivided into functional areas, which will help focus things. A "Development" area there would do the trick.  If you're ok to ping Yuri, please do so.  We should leave this Issue open until that's been decided either way (shouldn't take long). :smile:

Note - Not really seeing a need for Gitter (for this project yet) personally.

**Comment by 3Rton** [comment]
Done, let's see when they'll find time to reply. I'm sort of agreeing on the gitter not much need for real time chatting at least for now. Could change soon but I'm sure it will come up more if the need arises. I'll post here when I get a reply.

**Comment by cryovat** [comment]
My impression with Gitter is that it's mostly useful if you have a distributed team that needs to communicate in real-time. Like IRC it's really hard to keep track of multiple topics in it. So a dedicated Google Group area sounds like the best option. :smile:

**Comment by 3Rton** [comment]
Hm I don't seem to be getting reply, though :/ Maybe someone else should try?

**Comment by justinclift** [comment]
Yeah, this is why people have been saying things along the lines of "spending time developing OpenToonz isn't really worth it" (my summary wording).  The owners just aren't interested in ongoing development.

**Comment by metellius** [comment]
I'm feeling that people want to believe that (as an analogy) we have gone from closed-source to libreoffice, while in reality we're closer to the openoffice stage at the moment.

**Comment by metellius** [comment]
I'm feeling that people want to believe that (as an analogy) we have gone from closed-source to libreoffice, while in reality we're closer to the openoffice stage at the moment.

**Comment by justinclift** [comment]
Yeah
