### ISSUE TITLE
Schematic:  Wrong display nodes with click on "Reorder Nodes"

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#964]
I record my screen, [watch here](https://drive.google.com/open?id=0B9wCH2-wDK31U1RZWTdRRUx2S3M).

**Comment by artisteacher** [comment]
I had a student who had the same issue on OS X 10.11.6. Toggling from the FX schematic to the Stage schematic and then back to the FX schematic seemed to reset the view back to the expected display.

**Comment by gab3d** [comment]
@turtletooth 
@shun-iwasawa 
@manongjohn 
@morevnaproject 

I still experience this same bug...
once I enter into this behavior I can't get it back to operate properly, so is rather limiting for any fx node work. 🤒 

anyone had a look into it already?
thanks!

**Comment by RodneyBaker** [comment]
What happens when you save everything, close OT and then reopen everything
again?

**Comment by gab3d** [comment]
While it didn't revert the nodes layout to a good shape (i.e. the Output node still appears faaaar to the right), it does however allow to use the "Reorder Nodes" function properly again.
So, even if the bug is still the same bug, now the importance of it has decreased notoriously.
Thanks @RodneyBaker  ! :)

**Comment by phillycheese007** [comment]
Was about to post an issue but found this.  still happens on nightly release for this month.  Do other people find this issue often? notice any width height boundaries to prevent this?

**Comment by phillycheese007** [comment]
its strange ive never seen this happen in the stage schematic

**Comment by artisteacher** [comment]
I've run into this occasionally but not super recently. A difference between the stage and fx schematic is the icon view in the fx schematic. It would be interesting to know if the standard view and icon views both have the problem or just the icon view. Thanks to @manongjohn we can switch between the 2 views on demand instead of based on the zoom level.

**Comment by RodneyBaker** [comment]
I'm not sure if one of several Schematic updates might have fixed this issue.
Recommend watching closing as those PRs get merged to see if resolved.

**Comment by manongjohn** [comment]
This will be fixed with #2407.
