### ISSUE TITLE
gts wont detect my scanner

### ISSUE THREAD

**Issue by darkflamessussano** [opentoonz/opentoonz#979]
gts program wont detect my scanner but my laptop will . it says "cannot communicate with scanner, cable may be disconnected or scanner may be turned off , scanner driver closing "

**Comment by shun-iwasawa** [comment]
@darkflamessussano 
Please make sure that you have installed a scanner driver and it supports TWAIN. GTS needs to work with TWAIN compatible drivers.
If you have any other issues related to GTS, please post to [GTS Issues](https://github.com/opentoonz/GTS/issues). Thanks!

**Comment by darkflamessussano** [comment]
Now the message I'm getting when I plug my scanner up is "scan critical error, save config and restart "

**Comment by CodyEakins** [comment]
While it'd be nice if GTS supported a greater variety of scanners/drivers, I think this issue is native to your system.
I saw your thread on the OpenToonz reddit too, @darkflamessussano, message me there, and I'll work with you 1 on 1 to solve the issue. 

We should keep issues like this our of the repository...

- CodyAE (one of the r/opentoonz mods)
