### ISSUE TITLE
Cell zoom in

### ISSUE THREAD

**Issue by lightthebeacons** [opentoonz/opentoonz#992]
I cannot figure out how to zoom out of the cells. I cant see more than 26 cells and 10 columns at one time and it would be easier to see more. Can somebody tell me how to zoom them out please?

**Comment by RodneyBaker** [comment]
Not sure about zooming but...

We can drag the borders of the window to view as many columns and cells as desired.
This will be limited by the screen real estate you have available.
If you have multiple monitors you can drag the size through to those other monitors.

Seeing more columns is very easy... in the horizontal... because that is the general orientation of screens and multiple screens.  Going vertical is a little more difficult but doable also.

Adjusting your screen's resolution will allow more screen space as well.

Also, if this is not a request for a 'Cell Zoom In' feature it may be a topic better suited for the general OpenToonz forum.  That's the place for informational queries and such.

**Comment by lightthebeacons** [comment]
Thank you for the information. It is very helpful.
